### ISSUE TITLE
ResponseFilter of ClientFilter does not support MutableHttpResponse

### ISSUE THREAD

**Issue by eratolekov** [micronaut-projects/micronaut-core#10008]
### Expected Behavior

The content-type of response of httpclient (HttpBinClient) is rewrited from `application/json` to `text/plain`
```kotlin
    @ResponseFilter
    fun filter(request: MutableHttpRequest<*>, response: MutableHttpResponse<*>) {
        response.headers.set("content-type", "text/plain")
    }
```

ps
My goal is to fix a header of declarative httpclient's response. Some remote service returns broken content-type, I guess the best  way to fix it is ResponseFilter of ClientFilter.

### Actual Behaviour

The exception is raised:
```plain
Unexpected error occurred: class io.micronaut.http.client.netty.FullNettyClientHttpResponse cannot be cast to class io.micronaut.http.MutableHttpResponse (io.micronaut.http.client.netty.FullNettyClientHttpResponse and io.micronaut.http.MutableHttpResponse are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.micronaut.http.client.netty.FullNettyClientHttpResponse cannot be cast to class io.micronaut.http.MutableHttpResponse (io.micronaut.http.client.netty.FullNettyClientHttpResponse and io.micronaut.http.MutableHttpResponse are in unnamed module of loader 'app')
	at com.github.mn.$HttpBinFilter$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:447)
	at io.micronaut.http.filter.FilterRunner$FilterMethod.filter0(FilterRunner.java:640)
	at io.micronaut.http.filter.FilterRunner$FilterMethod.filter(FilterRunner.java:629)
...
```

### Steps To Reproduce

1. Run the [project](https://github.com/eratolekov/micronaut-responsefilter-bug)
2. Perform request
   ```curl -v -X GET "http://localhost:8080/json"```
3. See stacktraces in application logs:
   ```Unexpected error occurred: class io.micronaut.http.client.netty.FullNettyClientHttpResponse cannot be cast to class io.micronaut.http.MutableHttpResponse (io.micronaut.http.client.netty.FullNettyClientHttpResponse and io.micronaut.http.MutableHttpResponse are in unnamed module of loader 'app')```

### Environment Information

OS: Windows 11 21H2 x64
JVM: 17.0.1 (Oracle Corporation 17.0.1+12-39)
Micronaut 4.1.5: Gradle, Kotlin, Spock, Reactor, Netty

### Example Application

https://github.com/eratolekov/micronaut-responsefilter-bug

### Version

4.1.5

**Comment by eratolekov** [comment]
Also, HttpResponse works like a charm
```kotlin
    @ResponseFilter
    fun filter(request: MutableHttpRequest<*>, response: HttpResponse<*>) {
        //response.headers.set("content-type", "text/plain")
    }
```

But the response is immutable for changes in this case. And header of response can not be rewrited. But I have to

**Comment by VishaPatil** [comment]
I am seeing the same error.

> class io.micronaut.http.client.netty.FullNettyClientHttpResponse cannot be cast to class io.micronaut.http.MutableHttpResponse (io.micronaut.http.client.netty.FullNettyClientHttpResponse and io.micronaut.http.MutableHttpResponse are in unnamed module of loader 'app')

**Comment by NickHackman** [comment]
Same error, but with the continuation use case as well on Micronaut 4.7.6

```kotlin
@ClientFilter
public class ClientFilter {

    @RequestFilter
    @ExecuteOn(TaskExecutors.BLOCKING)
    public fun filter(
        request: MutableHttpRequest<*>,
        continuation: FilterContinuation<MutableHttpResponse<*>>,
    ) {
           // this line throws
           // class io.micronaut.http.client.netty.FullNettyClientHttpResponse cannot be cast to class io.micronaut.http.MutableHttpResponse
            val response = continuation.proceed()
        }
    }
```

EDIT: the default return type for the Response fails the casting, but if you type it as an `HttpResponse<*>` that's fine.

```kotlin
val response: HttpResponse<*>? = continuation.proceed()
```

**Comment by graemerocher** [comment]
Triage: validated and still reproducible from the supplied project plus a later 4.7.6 continuation report. `ResponseFilter` explicitly accepts `MutableHttpResponse`, but `MethodFilter` passes the raw response and the Netty client supplies `FullNettyClientHttpResponse`, which implements only `HttpResponse`; the generated dispatch then fails with `ClassCastException`. Fix by converting the response to a mutable response before binding a mutable filter argument (preserving body, headers, cookies, attributes, and streaming/lifecycle semantics), or narrow the contract and provide an explicit mutable-response operation. Add client tests for annotation filters, continuation responses, headers, and streaming responses.
