### ISSUE TITLE
@ConfigurationInjection with kotlin data classes when using kotlin default values does not work

### ISSUE THREAD

**Issue by aaronjwhiteside** [micronaut-projects/micronaut-core#10016]
### Expected Behavior

```kotlin
@ConfigurationProperties("testing")
data class TestProperties @ConfigurationInject constructor
    val enabled: Boolean = true
}
```
This should just work and the value of enabled when injected should be `true`,

Instead I receive this error..

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [enabled] of class: ......TestProperties

Message: Failed to inject value for parameter [enabled] of class: ....TestProperties

Message: Error resolving property value [testing.enabled]. Property doesn't exist
```

However If I change the property definition to this..

```kotlin
    val enabled: Boolean? = true
```

It works as expected, but now I have to deal with nullable issues.

I've also found that adding `@Bindable(defaultValue = "true")` also works, but this is annoying too, as I have other properties to use default values for that already have constants I can reuse (Enum values, Duration values etc), and I don't want to have to duplicate these constants.

### Actual Behaviour

See Expected Behavior

### Steps To Reproduce

N/A

### Environment Information

MacOs
JDK 17
Micronaut Platform: 4.1.5

### Version

Micronaut Platform: 4.1.5

**Comment by graemerocher** [comment]
KAPT or KSP?

**Comment by dstepanov** [comment]
We only support the default parameters in the introspected beans when used with KSP. The beans support has not been implemented yet.

**Comment by aaronjwhiteside** [comment]
So this was with KAPT, I switched to KSP, but get another error..

```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.micronaut.context.AbstractInitializableBeanDefinition.getPropertyValueForConstructorArgument(io.micronaut.context.BeanResolutionContext, io.micronaut.context.BeanContext, int, String, String)" is null
	at details.mn.dbscheduler.$DbSchedulerProperties$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)

```

The generated code..

```kotlin
@Generated
class $DbSchedulerProperties$Definition extends AbstractInitializableBeanDefinition<DbSchedulerProperties> {
    private static final AbstractInitializableBeanDefinition.MethodOrFieldReference $CONSTRUCTOR;

    public DbSchedulerProperties instantiate(BeanResolutionContext var1, BeanContext var2) {
        DbSchedulerProperties var3 = new DbSchedulerProperties((Boolean)super.getPropertyValueForConstructorArgument(var1, var2, 0, "db-scheduler.enabled", (String)null), (Integer)super.getPropertyValueForConstructorArgument(var1, var2, 1, "db-scheduler.threads", (String)null), (Duration)super.getPropertyValueForConstructorArgument(var1, var2, 2, "db-scheduler.heartbeat-interval", (String)null), (String)super.getPropertyValueForConstructorArgument(var1, var2, 3, "db-scheduler.scheduler-name", (String)null), (String)super.getPropertyValueForConstructorArgument(var1, var2, 4, "db-scheduler.table-name", (String)null), (Boolean)super.getPropertyValueForConstructorArgument(var1, var2, 5, "db-scheduler.immediate-execution-enabled", (String)null), (Duration)super.getPropertyValueForConstructorArgument(var1, var2, 6, "db-scheduler.polling-interval", (String)null), (PollingStrategyConfig.Type)super.getPropertyValueForConstructorArgument(var1, var2, 7, "db-scheduler.polling-strategy", (String)null), (Double)super.getPropertyValueForConstructorArgument(var1, var2, 8, "db-scheduler.polling-strategy-lower-limit-fraction-of-threads", (String)null), (Double)super.getPropertyValueForConstructorArgument(var1, var2, 9, "db-scheduler.polling-strategy-upper-limit-fraction-of-threads", (String)null), (Boolean)super.getPropertyValueForConstructorArgument(var1, var2, 10, "db-scheduler.delay-startup-until-context-ready", (String)null), (Duration)super.getPropertyValueForConstructorArgument(var1, var2, 11, "db-scheduler.delete-unresolved-after", (String)null), (Duration)super.getPropertyValueForConstructorArgument(var1, var2, 12, "db-scheduler.shutdown-max-wait", (String)null), (LogLevel)super.getPropertyValueForConstructorArgument(var1, var2, 13, "db-scheduler.failure-logger-level", (String)null), (Boolean)super.getPropertyValueForConstructorArgument(var1, var2, 14, "db-scheduler.failure-logger-log-stack-trace", (String)null), (String)super.getPropertyValueForConstructorArgument(var1, var2, 15, "db-scheduler.datasource", (String)null));
        var3 = (DbSchedulerProperties)this.inject(var1, var2, var3);
        return var3;
    }
....
```

Looks like the first call ```(Boolean)super.getPropertyValueForConstructorArgument(var1, var2, 0, "db-scheduler.enabled", (String)null)``` is returning null and that's trying to cast to a primitive boolean..


After switching to KSP, the `@Bindable(defaultValue = "true")` annotation has stopped working completely.

I guess KSP and kotlin data class constructor injection are just not compatible at the moment?

Moving back to a normal kotlin class with default values on variables works fine..

```kotlin
@ConfigurationProperties("testing")
class TestProperties {
    var enabled: Boolean = true
}
```

However it would be really nice to have immutability.

**Comment by altro3** [comment]
@dstepanov Hi! Are you planing to fix it? I can confirm that the bug exists with KSP. Everything is as described in the issue. 

This code does not work (if you haven't value in `application.yml`):
```kotlin
@ConfigurationProperties("testing")
data class TestProperties @ConfigurationInject constructor(
    val enabled: Boolean = true
)
```
Exception:
```
Message: Failed to inject value for parameter [enabled] of class: com.micronaut.bug.config.TestProperties

Message: Error resolving property value [testing.enabled]. Property doesn't exist
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [com.micronaut.bug.config.TestProperties] could not be loaded: Failed to inject value for parameter [enabled] of class: com.micronaut.bug.config.TestProperties

Message: Failed to inject value for parameter [enabled] of class: com.micronaut.bug.config.TestProperties

Message: Error resolving property value [testing.enabled]. Property doesn't exist
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1980)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:291)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3322)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3677)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:199)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:322)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:308)
	at com.micronaut.bug.Application$Companion.main(Application.kt:25)
	at com.micronaut.bug.Application.main(Application.kt)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [enabled] of class: com.micronaut.bug.config.TestProperties

Message: Failed to inject value for parameter [enabled] of class: com.micronaut.bug.config.TestProperties

Message: Error resolving property value [testing.enabled]. Property doesn't exist
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
Path Taken: new TestProperties(boolean enabled) --> new TestProperties([boolean enabled])
	at io.micronaut.context.exceptions.DependencyInjectionException.missingProperty(DependencyInjectionException.java:289)
	at io.micronaut.context.AbstractInitializableBeanDefinition.lambda$resolvePropertyValue$9(AbstractInitializableBeanDefinition.java:2144)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolvePropertyValue(AbstractInitializableBeanDefinition.java:2144)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getPropertyValueForConstructorArgument(AbstractInitializableBeanDefinition.java:1393)
	at com.micronaut.bug.config.$TestProperties$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2667)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1974)
	... 10 common frames omitted
```

This code works fine:
```kotlin
@ConfigurationProperties("testing")
class TestProperties {
    var enabled: Boolean = true
}
```

With KAPT I have the same exception.

Example app to reproduce the problem you can find here: https://github.com/altro3/micronaut3-bug/tree/kotlin  (branch `kotlin`)
