### ISSUE TITLE
@Bean(typed=[Something::class]) does not work for proxied beans

### ISSUE THREAD

**Issue by aaronjwhiteside** [micronaut-projects/micronaut-core#10035]
### Expected Behavior

Given a @Factory like

```kotlin
    @Singleton
    @InterceptMyAnnotation
    @Bean(typed = [TestService::class])
    fun testService() : TestServiceImpl {
        return TestServiceImpl()
    }
```

A an injection point like:

```koltin
@Controller("/hello")
class HelloController(private val service: TestService) {
.....
```

The `HelloController` bean should be able to location the `TestService` bean in the context..

### Actual Behaviour

However this does not work and I receive an exception:

```
Message: No bean of type [test.TestServiceImpl] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new HelloController(TestService service) --> new HelloController([TestService service])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at example.micronaut.$HelloController$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
.....
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [test.TestServiceImpl] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.BeanDefinitionRegistry.lambda$getProxyTargetBeanDefinition$3(BeanDefinitionRegistry.java:553)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.context.BeanDefinitionRegistry.getProxyTargetBeanDefinition(BeanDefinitionRegistry.java:553)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1473)
	at example.micronaut.$Config$TestService0$Definition$Intercepted.<init>(Unknown Source)
	at example.micronaut.$Config$TestService0$Definition$Intercepted$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	... 89 common frames omitted

```

### Steps To Reproduce

[micronaut-inject-issue.zip](https://github.com/micronaut-projects/micronaut-core/files/13185496/micronaut-inject-issue.zip)

See attached sample project

### Environment Information

MacOS
JDK 17
Micronaut Platform 4.1.5

### Version

Micronaut Platform 4.1.5

**Comment by graemerocher** [comment]
Triage: valid-looking proxy-generation bug with an attached reproducer, but it needs a current KAPT/KSP and Java/Kotlin matrix before implementation. This overlaps the design request in [#10044](https://github.com/micronaut-projects/micronaut-core/issues/10044). The likely fix is to use the interfaces from `@Bean(typed = …)` as the intercepted proxy surface when they are all interfaces, while retaining the concrete factory return type for construction, lifecycle, and method metadata. Add a regression test proving injection by the exposed interface, proxy interception, final/concrete implementation support, and behavior when `typed` includes a concrete class.
