### ISSUE TITLE
Failed to query data from MongoDB if run as GraalVM native image

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-core#10053]
### Expected Behavior

Micronaut application should work without issues when built as GraalVM native image.

### Actual Behaviour

Hi

We tried to run our Micronaut application as GraalVM native image. Some functionality works perfectly. But we couldn't query data from MongoDB database because of this error:

```
 org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for CodecCacheKey{clazz=class model.Account, types=null}.
 	at org.bson.internal.ProvidersCodecRegistry.lambda$get$0(ProvidersCodecRegistry.java:87)
 	at java.base@21.0.1/java.util.Optional.orElseGet(Optional.java:364)
 	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:80)
 	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:50)
 	at com.mongodb.internal.operation.Operations.createFindOperation(Operations.java:186)
 	at com.mongodb.internal.operation.Operations.find(Operations.java:176)
 	at com.mongodb.internal.operation.SyncOperations.find(SyncOperations.java:98)
 	at com.mongodb.client.internal.FindIterableImpl.asReadOperation(FindIterableImpl.java:246)
 	at com.mongodb.client.internal.FindIterableImpl.asReadOperation(FindIterableImpl.java:41)
 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)
 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
 	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:116)
 	at com.mongodb.client.internal.MongoIterableImpl.into(MongoIterableImpl.java:125)
```

It's unclear for us whether this error is raised because of MongoDB driver or Micronaut incompatiblity with GraalVM native image. So here's our code that configures codec registry:

```
CodecProvider pojoCodecProvider = PojoCodecProvider.builder().register("model")
				.build();
codecRegistry = fromRegistries(getDefaultCodecRegistry(), fromProviders(pojoCodecProvider));
```

And code that queries data from mongoDB:

```
	protected MongoCollection<T> getCollection(Class<T> clz) {
		MongoDatabase database = mongoClient.getDatabase(databaseName).withCodecRegistry(codecRegistry);
		return database.getCollection(collection, clz);
	}

	public List<Account> findAll() {
		MongoCollection<Account> providers = getCollection(Account.class);

		FindIterable<Account> iterable = providers.find(eq(PROPERTY_ENABLED, true));
		return iterable.into(new ArrayList<>());
	}
```

### Environment Information

JDK 21

GraalVM 22.3.3

### Version

4.1.4

**Comment by sergey-morenets** [comment]
MongoDB engineers claims that Java driver supports GraalVM: https://jira.mongodb.org/browse/JAVA-3537
