### ISSUE TITLE
Micronaut Declarative Client SSL Error with PKIX path building failed

### ISSUE THREAD

**Issue by GavinLi-2025** [micronaut-projects/micronaut-core#10171]
### Expected Behavior

Client ssl configuration should be taken into account and therefore, it is possible to call the service with the specified certificate.

### Actual Behaviour

```
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1647)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1493)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	... 4 common frames omitted
```

### Steps To Reproduce

Configure a service in application.yml as follows:
```
micronaut:
  application:
    name: "xxx-api"
  http:
    client:
      ssl:
        enabled: true
        key-store:
          path: classpath:ssl/client_keystore.jks
          password: mypassword
          type: JKS
        trust-store:
          path: classpath:ssl/truststore.jks
          password: mypassword
          type: JKS
    services:
      MyServiceClient:
        read-timeout: 10s
        connect-timeout: 5s
        ssl-configuration:
          enable: true
```

### Environment Information

- OS: Macos Monterey 12.6
- Micronaut: 4.2.0
- JDK: Amazon Corretto-17

### Version

4.2.0

**Comment by yawkat** [comment]
can you try moving the ssl config to the service ssl config

**Comment by GavinLi-2025** [comment]
Tried with move the ssl config to service level in application.yml, but got another error as below seems like micronaut cannot pick up the ssl configuration
```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Client 'https://3rd-party-web-service.com': Error occurred reading HTTP response: javax.net.ssl.SSLException: Tag mismatch
io.micronaut.http.client.exceptions.HttpClientException: Client 'https://3rd-party-web-service.com': Error occurred reading HTTP response: javax.net.ssl.SSLException: Tag mismatch
	at io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2047)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
	at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1203)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.micronaut.http.client.netty.ResettableReadTimeoutHandler$NextInterceptor.channelRead(ResettableReadTimeoutHandler.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.micronaut.http.client.netty.ResettableReadTimeoutHandler.channelRead(ResettableReadTimeoutHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by yawkat** [comment]
tag mismatch seems more like a server issue. please make a reproducer.

**Comment by GavinLi-2025** [comment]
could you please let me know what do you mean by make a reproducer? You mean reproduce the error?

**Comment by yawkat** [comment]
yes, an independent test case that reproduces this issue.

**Comment by GavinLi-2025** [comment]
Here was the reproduced one: 
My declarative client interface:

```
@Client("https://third-party-web-services.com/endpoint")
@Headers(
    Header(name = HttpHeaders.ACCEPT, value = "application/json")
)

interface MyDeclarativeClient {
    @Get("/xxx")
    fun getXXX(): List<XXX>
}
```
And here is the application.yml:
```
micronaut:
  application:
    name: "my-api"
  http:
    services:
      MyDeclarativeClient:
        ssl:
          key-store:
            path: classpath:ssl/client_keystore.jks
            password: testpassword
            type: JKS
          trust-store:
            path: classpath:ssl/truststore.jks
            password: testpassword
            type: JKS
          read-timeout: 10s
          connect-timeout: 5s
```

and error shows as below: 

```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Client 'https://third-party-web-services.com/endpoint': Error occurred reading HTTP response: javax.net.ssl.SSLException: Tag mismatch
io.micronaut.http.client.exceptions.HttpClientException: Client 'https://third-party-web-services.com/endpoint': Error occurred reading HTTP response: javax.net.ssl.SSLException: Tag mismatch
	at io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2047)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.exceptionCaught(DefaultHttpClient.java:2279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at java.base/java.lang.Thread.run(Thread.java:840)
... 35 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Flux.blockFirst(Flux.java:2704)
		at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:548)
		at io.micronaut.http.client.netty.DefaultHttpClient$1.retrieve(DefaultHttpClient.java:555)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		... 35 common frames omitted
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Tag mismatch
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	... 25 common frames omitted
Caused by: javax.net.ssl.SSLException: Tag mismatch
```

**Comment by yawkat** [comment]
`https://third-party-web-services.com/endpoint` is not a thing. Please see http://sscce.org/

**Comment by GavinLi-2025** [comment]
that's my test third party url, for the security purpose I just gave an example, not real one

**Comment by yawkat** [comment]
we need a real one to reproduce it

**Comment by sgammon** [comment]
@YuxuanLi819 you could try a test like https://ssllabs.com/ssltest/analyze.html, which may surface server side issues

**Comment by GavinLi-2025** [comment]
Sorry guys, the real third party url is: `https://test.ws.postbillpay.securepay.com.au/pbpapi`

And I gave a try with above link, seems like the server side doesn't have issue, and the result shown as below: 
![FireShot Capture 010 - SSL Server Test_ test ws postbillpay securepay com au (Powered by Qua_ - www ssllabs com](https://github.com/micronaut-projects/micronaut-core/assets/16631542/045084f6-7143-4886-83cf-d8e18c7a7a5e)

**Comment by GavinLi-2025** [comment]
And I've tested for the same key store my springboot application is running ok

**Comment by yawkat** [comment]
cant reproduce
