### ISSUE TITLE
io.grpc:grpc-bom must be upgraded to version 1.59.1, since 1.59.0 fails with io.netty:netty-codec-http2 4.1.101.Final which prevents upgrade to Micronaut 4.2.0, if using GRPC

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-core#10175]
### Expected Behavior

No failure, when calling a GRPC service.

### Actual Behaviour

This failure, when calling a GRPC service:

```
io.grpc.StatusException: UNKNOWN
	at io.grpc.Status.asException(Status.java:552)
...
Caused by: java.lang.UnsupportedOperationException
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
...
```

See also https://github.com/grpc/grpc-java/issues/10665

### Steps To Reproduce

1. Clone https://github.com/runenielsen/netty-grpc-bug
2. Run the test NettyGrpcBugTest and see it fails
3. In `build.gradle.kts` comment in the line `//    implementation(platform("io.grpc:grpc-bom:1.59.1"))`
4. Run the test NettyGrpcBugTest and see it now works

### Environment Information

- macOS
- JDK 17

### Example Application

https://github.com/runenielsen/netty-grpc-bug

### Version

4.2.0

**Comment by sdelamo** [comment]
Thanks for reporting. 

this should be fixed by https://github.com/micronaut-projects/micronaut-grpc/releases/tag/v4.2.0 
 Micronaut Framework 4.2.1 bom will include that version.
