### ISSUE TITLE
Error loading scheduled beans that make use of random expressions

### ISSUE THREAD

**Issue by rorueda** [micronaut-projects/micronaut-core#10176]
### Expected Behavior

This was reported by a user at discord: https://discord.com/channels/1121511613250412714/1179161327462273136

Multiple scheduled beans that make use of random expressions should be loaded without errors.

### Actual Behaviour

Randomly:

```
io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${random.long[12,24]}
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver$PlaceholderSegment.getValue(DefaultPropertyPlaceholderResolver.java:392)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholdersString(DefaultPropertyPlaceholderResolver.java:125)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholdersObject(DefaultPropertyPlaceholderResolver.java:119)
	at io.micronaut.context.env.PropertySourcePropertyResolver.resolvePlaceHoldersIfNecessary(PropertySourcePropertyResolver.java:791)
	at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:388)
	at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:140)
	at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:157)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveExpression(DefaultPropertyPlaceholderResolver.java:216)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver$PlaceholderSegment.getValue(DefaultPropertyPlaceholderResolver.java:382)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholdersString(DefaultPropertyPlaceholderResolver.java:125)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholders(DefaultPropertyPlaceholderResolver.java:110)
	at io.micronaut.inject.annotation.EnvironmentAnnotationValue.lambda$new$2(EnvironmentAnnotationValue.java:58)
	at io.micronaut.core.annotation.AnnotationValue.getRawSingleValue(AnnotationValue.java:1688)
	at io.micronaut.core.annotation.AnnotationValue.stringValue(AnnotationValue.java:998)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.process(ScheduledMethodProcessor.java:100)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$30(DefaultBeanContext.java:2033)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Steps To Reproduce

Add to `PropertySourcePropertyResolverSpec`:

```
@RepeatUntilFailure(maxAttempts = 5, ignoreRest = false)
void "test concurrent access to get expression resolvers"() {
    given:
    PropertyResolver propertyResolver = new MapPropertyResolver(Map.of())
    DefaultPropertyPlaceholderResolver propertyPlaceholderResolver = new DefaultPropertyPlaceholderResolver(propertyResolver, ConversionService.SHARED)

    when:
    Collection<PropertyExpressionResolver>[] resolvers = new Collection<PropertyExpressionResolver>[2]
    Thread[] threads = (0..1).collect{it -> new Thread(() -> {
        resolvers[it] = propertyPlaceholderResolver.getExpressionResolvers()
    })}
    threads.each {it -> it.start()}
    threads.each {it -> it.join()}

    then:
    resolvers.each {it -> assert !it.isEmpty()}
    resolvers[0] == resolvers[1]
}
```

### Environment Information

N/A

### Example Application

N/A

### Version

4.2.x

**Comment by katoquro** [comment]
I have just come to create an issue) Thanks
