### ISSUE TITLE
RuntimeExceptions in endpoints returning Writable hang

### ISSUE THREAD

**Issue by dansiviter** [micronaut-projects/micronaut-core#10199]
### Expected Behavior

Error returned to client, potentially HTTP 500 Internal Server Error.

### Actual Behaviour

Connection simply hangs. Exception is logged but client must timeout or potentially be connected indefinately.

```
Exception in thread "io-executor-thread-1" java.lang.RuntimeException: Baaaaad!
	at com.acme.rest.RestResource.lambda$1(RestResource.java:19)
RestResource.java:19
	at io.micronaut.core.io.Writable.writeTo(Writable.java:77)
Writable.java:77
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$encodeHttpResponse$6(RoutingInBoundHandler.java:1002)
RoutingInBoundHandler.java:1002
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
InvocationInstrumenterWrappedRunnable.java:47
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
ThreadPoolExecutor.java:1130
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
ThreadPoolExecutor.java:630
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### Steps To Reproduce

1. Write a `@Controller` endpoint that returns a `io.micronaut.core.io.Writable`,
2. The usage of the endpoint throws any `RuntimeException`,
3. Call that endpoint.

### Version

3.10.2

**Comment by yawkat** [comment]
is this still an issue in 4?

**Comment by dansiviter** [comment]
@yawkat Yes, I've just tried `io.micronaut:micronaut-http-server-netty:4.2.1` and it's present in that too:

```
Exception in thread "virtual-executor1" java.lang.RuntimeException: Baaaaad!
        at com.acme.rest.RestResource.lambda$bad$1(RestResource.java:19)
        at io.micronaut.core.io.Writable.writeTo(Writable.java:77)
        at io.micronaut.http.netty.body.NettyWritableBodyWriter.writeTo(NettyWritableBodyWriter.java:88)
        at io.micronaut.http.netty.body.NettyWritableBodyWriter.writeTo(NettyWritableBodyWriter.java:56)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.writeNettyMessageBody(RoutingInBoundHandler.java:359)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$encodeHttpResponse$0(RoutingInBoundHandler.java:336)
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
```
It does appear to handle `IOException` correctly, just not `RuntimeException`.

**Comment by graemerocher** [comment]
The report is still valid in the current response-writer path: `WritableBodyWriter.writeTo` converts `IOException` to `CodecException`, but a `RuntimeException` from `Writable.writeTo` can escape the encoding task and leave the response incomplete. Open PR #12445 addresses this exact issue by wrapping the runtime failure and adding a TCK regression that expects HTTP 500. Suggested resolution: merge/adapt #12445, preserving the normal codec exception/error-handler path.
