### ISSUE TITLE
Internal Server Error: All possible Introduction advise exhausted and no implementation found for method

### ISSUE THREAD

**Issue by jfisbein** [micronaut-projects/micronaut-core#1025]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an app `mn create-app quotes-frontend2 --features=http-client,http-server,java --build=maven`
2. add lombok support (don't sure if this affects the result)
3. create a simple rest client
4. Try to use it from  a controller

### Expected Behaviour

The controller should be able to use the client

### Actual Behaviour

when the controller is called it generates an error:
```
 java -jar quotes-frontend2-0.1.jar 
12:57:21.015 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1128ms. Server Running: http://localhost:8081
12:57:30.994 [pool-1-thread-3] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.example.quotes.frontend.client.CharactersClient$Intercepted] executed with error: All possible Introduction advise exhausted and no implementation found for method: List getCharacters()
io.micronaut.aop.exceptions.UnimplementedAdviceException: All possible Introduction advise exhausted and no implementation found for method: List getCharacters()
        at io.micronaut.aop.chain.InterceptorChain.lambda$new$0(InterceptorChain.java:87)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:508)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:74)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at com.example.quotes.frontend.client.CharactersClient$Intercepted.getCharacters(Unknown Source)
        at com.example.quotes.frontend.QuotesController.index(QuotesController.java:23)
        at com.example.quotes.frontend.$QuotesControllerDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2401)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$13(RoutingInBoundHandler.java:1255)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14429)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14426)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
12:57:31.047 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: All possible Introduction advise exhausted and no implementation found for method: List getCharacters()
io.micronaut.aop.exceptions.UnimplementedAdviceException: All possible Introduction advise exhausted and no implementation found for method: List getCharacters()
        at io.micronaut.aop.chain.InterceptorChain.lambda$new$0(InterceptorChain.java:87)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:508)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:74)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at com.example.quotes.frontend.client.CharactersClient$Intercepted.getCharacters(Unknown Source)
        at com.example.quotes.frontend.QuotesController.index(QuotesController.java:23)
        at com.example.quotes.frontend.$QuotesControllerDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2401)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$13(RoutingInBoundHandler.java:1255)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14429)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14426)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Notes
example remote server response: 
```
curl -v http://localhost:8080/characters
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /characters HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 12 Dec 2018 12:08:58 GMT
< 
* Connection #0 to host localhost left intact
["Abe Simpson","Abuelo Simpson","Actor Secundario Bob","Apu","Barney","Bart Simpson","Carl","Clancy Wiggum","Doctor Hibbert","Edna Krabappel","Fat Tony","Hans Topo","Helen Lovejoy","Homer Simpson","Jebediah Springfield","Kent Brockman","Lenny","Lisa Simpson","Marge Simpson","Milhouse","Moe","Ned Flanders","Nelson","Otto","Ralph","Reverendo Lovejoy","Selma Bouvier","Skinner","Sr. Burns","Troy McClure","Willie"]
```
### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.0.1
- **JDK Version:** Oracle java version "1.8.0_191"

### Example Application

https://github.com/jfisbein/quotes-frontend

**Comment by jfisbein** [comment]
Thanks a lot, it worked using `@Client("/characters")`

**Comment by graemerocher** [comment]
I am going to re-open so we can improve the handling of `/path`

**Comment by jameskleeh** [comment]
@graemerocher To support a compilation error we would have to add something to the validator package which would add http-client to the annotation processor path. What do you think about making this a runtime error? We can update the javadoc of the annotation to indicate path is reliant on one of the other properties to be set
