### ISSUE TITLE
Multiple possible bean candidates found: InterceptorRegistry

### ISSUE THREAD

**Issue by BramMeerten** [micronaut-projects/micronaut-core#10251]
### Actual Behavior

Only when I run my application containerized I get the following error, when running it directly via java there is no issue:
```
Message: Multiple possible bean candidates found: [InterceptorRegistry, InterceptorRegistry]
Path Taken: new NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2324)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2917)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2891)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3506)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3454)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3424)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1451)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:897)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:887)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$1(ApplicationEventPublisherFactory.java:215)
	at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:602)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:304)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:79)
	at com.example.app.Application.main(Application.java:10)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [InterceptorRegistry, InterceptorRegistry]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2428)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:602)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3212)
	at io.micronaut.context.DefaultBeanContext.pickOneBean(DefaultBeanContext.java:3156)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3112)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3095)
	at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:2745)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2720)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1729)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:856)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:848)
	at io.micronaut.aop.chain.InterceptorChain.resolveInterceptors(InterceptorChain.java:213)
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:152)
	at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.<init>(Unknown Source)
	at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
```

A similar issue was reported [here](https://github.com/micronaut-projects/micronaut-core/issues/6579):
> right, the reason is normally a classpath issue where you have multiple versions of the same JAR on your classpath

But this does not seem to be the issue for me, I inspected my classpath and container image for duplicate JARs, but could not find any.

### Steps To Reproduce

It only happens with some specific project structure / dependencies. I created a reproducible [example here](https://github.com/BramMeerten/micronaut-multiple-interceptor-registry):
- All are micronaut 4.2.1 modules
- The application is a multi-module application, the main module `module2` depends on `module1`
- `module1` depends on a library, `my-lib`. The library has only one dependency: `micronaut-jackson-databind` and has micronaut as a parent.

The error disappears in the following cases:
- If I remove the jackson dependency in the library - [commit f48a4dc](https://github.com/BramMeerten/micronaut-multiple-interceptor-registry/commit/f48a4dcaae2df5a001eaf0e53e07fae8d701300e)
- Or if I depend on the library via the main module `module2` instead of via `module1` - [commit 2f2ac51](https://github.com/BramMeerten/micronaut-multiple-interceptor-registry/commit/2f2ac5185ffbc3d862854f23729a1ae19066c64b)
- Or if I remove the `micronaut-http-client` dependency in the main module - [commit 15b3edd](https://github.com/BramMeerten/micronaut-multiple-interceptor-registry/commit/15b3eddcb17a56681b8cc8c77407b8ea637b8b00)

### Verifying the contents of the image
I inspected the jib-classpath-file in the image. InterceptorRegistry should be in `micronaut-aop` JAR, but can only find one JAR.
```
/app/resources:/app/classes:/app/libs/module1-3.0.0.jar:/app/libs/my-lib-1.0.0.jar:/app/libs/micronaut-http-server-netty-4.2.1.jar:/app/libs/slf4j-api-2.0.9.jar:/app/libs/micronaut-http-server-4.2.1.jar:/app/libs/micronaut-http-4.2.1.jar:/app/libs/micronaut-core-reactive-4.2.1.jar:/app/libs/micronaut-context-propagation-4.2.1.jar:/app/libs/micronaut-router-4.2.1.jar:/app/libs/micronaut-core-4.2.1.jar:/app/libs/micronaut-http-netty-4.2.1.jar:/app/libs/micronaut-buffer-netty-4.2.1.jar:/app/libs/netty-codec-http2-4.1.101.Final.jar:/app/libs/netty-handler-4.1.101.Final.jar:/app/libs/netty-resolver-4.1.101.Final.jar:/app/libs/netty-transport-native-unix-common-4.1.101.Final.jar:/app/libs/netty-codec-http-4.1.101.Final.jar:/app/libs/netty-common-4.1.101.Final.jar:/app/libs/netty-buffer-4.1.101.Final.jar:/app/libs/netty-transport-4.1.101.Final.jar:/app/libs/netty-codec-4.1.101.Final.jar:/app/libs/reactor-core-3.5.11.jar:/app/libs/reactive-streams-1.0.4.jar:/app/libs/micronaut-http-client-4.2.1.jar:/app/libs/micronaut-context-4.2.1.jar:/app/libs/micronaut-inject-4.2.1.jar:/app/libs/jakarta.inject-api-2.0.1.jar:/app/libs/jakarta.annotation-api-2.1.1.jar:/app/libs/micronaut-aop-4.2.1.jar:/app/libs/micronaut-http-client-core-4.2.1.jar:/app/libs/micronaut-json-core-4.2.1.jar:/app/libs/micronaut-discovery-core-4.2.1.jar:/app/libs/micronaut-websocket-4.2.1.jar:/app/libs/netty-handler-proxy-4.1.101.Final.jar:/app/libs/netty-codec-socks-4.1.101.Final.jar:/app/libs/logback-classic-1.4.13.jar:/app/libs/logback-core-1.4.13.jar:/app/libs/micronaut-jackson-databind-4.2.1.jar:/app/libs/micronaut-jackson-core-4.2.1.jar:/app/libs/jackson-core-2.15.3.jar:/app/libs/jackson-annotations-2.15.3.jar:/app/libs/jackson-databind-2.15.3.jar:/app/libs/jackson-datatype-jdk8-2.15.3.jar:/app/libs/jackson-datatype-jsr310-2.15.3.jar:/app/libs/snakeyaml-2.0.jarroot@90187e199d9a:/app# exit
```

I also inspected the libs folder in the image:
```
├── libs
│   ├── jackson-annotations-2.15.3.jar
│   ├── jackson-core-2.15.3.jar
│   ├── jackson-databind-2.15.3.jar
│   ├── jackson-datatype-jdk8-2.15.3.jar
│   ├── jackson-datatype-jsr310-2.15.3.jar
│   ├── jakarta.annotation-api-2.1.1.jar
│   ├── jakarta.inject-api-2.0.1.jar
│   ├── logback-classic-1.4.13.jar
│   ├── logback-core-1.4.13.jar
│   ├── micronaut-aop-4.2.1.jar
│   ├── micronaut-buffer-netty-4.2.1.jar
│   ├── micronaut-context-4.2.1.jar
│   ├── micronaut-context-propagation-4.2.1.jar
│   ├── micronaut-core-4.2.1.jar
│   ├── micronaut-core-reactive-4.2.1.jar
│   ├── micronaut-discovery-core-4.2.1.jar
│   ├── micronaut-http-4.2.1.jar
│   ├── micronaut-http-client-4.2.1.jar
│   ├── micronaut-http-client-core-4.2.1.jar
│   ├── micronaut-http-netty-4.2.1.jar
│   ├── micronaut-http-server-4.2.1.jar
│   ├── micronaut-http-server-netty-4.2.1.jar
│   ├── micronaut-inject-4.2.1.jar
│   ├── micronaut-jackson-core-4.2.1.jar
│   ├── micronaut-jackson-databind-4.2.1.jar
│   ├── micronaut-json-core-4.2.1.jar
│   ├── micronaut-router-4.2.1.jar
│   ├── micronaut-websocket-4.2.1.jar
│   ├── module1-3.0.0.jar
│   ├── my-lib-1.0.0.jar
│   ├── netty-buffer-4.1.101.Final.jar
│   ├── netty-codec-4.1.101.Final.jar
│   ├── netty-codec-http-4.1.101.Final.jar
│   ├── netty-codec-http2-4.1.101.Final.jar
│   ├── netty-codec-socks-4.1.101.Final.jar
│   ├── netty-common-4.1.101.Final.jar
│   ├── netty-handler-4.1.101.Final.jar
│   ├── netty-handler-proxy-4.1.101.Final.jar
│   ├── netty-resolver-4.1.101.Final.jar
│   ├── netty-transport-4.1.101.Final.jar
│   ├── netty-transport-native-unix-common-4.1.101.Final.jar
│   ├── reactive-streams-1.0.4.jar
│   ├── reactor-core-3.5.11.jar
│   ├── slf4j-api-2.0.9.jar
│   └── snakeyaml-2.0.jar
```

### Environment Information

JDK: 17
OS: MacOS Ventura

### Example Application

https://github.com/BramMeerten/micronaut-multiple-interceptor-registry

### Version

4.2.1

**Comment by graemerocher** [comment]
you need to disable shading in the `lib` module otherwise it repackage all the jars into the lib module and you end up with duplicates https://github.com/BramMeerten/micronaut-multiple-interceptor-registry/blob/main/lib/pom.xml

You can run `java -verbose -jar foo.jar` to diagnose class loading issues like this and see where classes are being loaded from

**Comment by BramMeerten** [comment]
Thanks @graemerocher it works!

I tried `lib`, but it was actually the `module1` where I needed to disable shading:
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

For others this is how I inspected the class loading using Graeme's method:
```
# Run without starting the java command
docker run -it --entrypoint /bin/bash module2

# Run java manually
java -verbose -cp @/app/jib-classpath-file com.example.app.Application > classthingy.txt
# or: java -verbose -cp @/app/jib-classpath-file com.example.app.Application | grep InterceptorRegistry

# Copy output to file outside docker container, for easier inspection
docker cp <my-container-id>:/classthingy.txt ~/Desktop/classthingy.txt
```

Result:
```
...
[3.853s][info][class,load] io.micronaut.aop.internal.InterceptorRegistryBean source: file:/app/libs/module1-3.0.0.jar
[3.854s][info][class,load] io.micronaut.inject.proxy.InterceptedBean source: file:/app/libs/module1-3.0.0.jar
[3.854s][info][class,load] io.micronaut.aop.Intercepted source: file:/app/libs/module1-3.0.0.jar
[3.854s][info][class,load] io.micronaut.aop.InterceptorRegistry source: file:/app/libs/module1-3.0.0.jar
...
```
