### ISSUE TITLE
Mapper bean could not be created when using Mapping annotation with Kotlin

### ISSUE THREAD

**Issue by steventen** [micronaut-projects/micronaut-core#10356]
### Expected Behavior

A mapper bean is created and can map an entity class to a DTO

### Actual Behaviour

Exception: `io.micronaut.context.exceptions.NoSuchBeanException` is thrown. No bean of type [xxx] exists

### Steps To Reproduce

The problem only exists if we use `@Mapping`, however, if we just use `@Mapper` it works.

I've created an example in this repo: https://github.com/steventen/micronaut-bean-mapper-example

I have a `CompanyMapper` in the [Mapper](https://github.com/steventen/micronaut-bean-mapper-example/blob/main/src/main/kotlin/com/example/Mapper.kt) file, which looks like this:
```Kotlin
@Singleton
abstract class CompanyMapper {
    @Mapping(to = "companyName", from = "#{company.name}")
    abstract fun toDto(company: Company): CompanyDto
}
```
Where the entity and dto are defined as:
```Kotlin
@Entity
@Table(name = "companies")
@Introspected
data class Company(
    @Id
    val id: String,

    @Column(name = "company_name")
    val name: String,

    @Column(name = "company_value")
    val value: BigDecimal?,
)

@Serdeable
data class CompanyDto(
    val companyName: String,
)
```

To reproduce, pull the code from the repo, then
1. start the database: docker-compose up
2. start the server: ./gradlew run
3. visit the endpoint: http://localhost:8080/companies/a

When I call the api endpoint (http://localhost:8080/companies/a) which retrieves a Company record and map it to CompanyDto, it causes the following exception:
```
Message: No bean of type [com.example.CompanyMapper] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new CompanyController(CompanyRepository companyRepository,CompanyMapper companyMapper) --> new CompanyController(CompanyRepository companyRepository,[CompanyMapper companyMapper])
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2181)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
        at com.example.$CompanyController$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2917)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2891)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1695)
        at io.micronaut.context.DefaultBeanContext$BeanContextExecutionHandle.getTarget(DefaultBeanContext.java:4247)
        at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4214)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:228)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
        at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
        at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:470)
        at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$2(RequestLifecycle.java:146)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
        at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$4(RequestLifecycle.java:146)
        at io.micronaut.http.server.RequestLifecycle.lambda$runWithFilters$14(RequestLifecycle.java:264)
        at io.micronaut.http.filter.TerminalFilter.processRequestFilter(TerminalFilter.java:58)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:153)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:153)
        at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$2(FilterRunner.java:153)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
        at io.micronaut.http.filter.MethodFilter.processRequestFilter(MethodFilter.java:263)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:153)
        at io.micronaut.http.filter.FilterRunner.filterRequest(FilterRunner.java:137)
        at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:132)
        at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:281)
        at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:143)
        at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:85)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:220)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:357)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:206)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.example.CompanyMapper] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2773)
        at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:304)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2735)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1729)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
```

Also tried to use `interface` and the problem is the same.

### Environment Information

- MacOS 14.2.1
- JDK 17

### Example Application

https://github.com/steventen/micronaut-bean-mapper-example

### Version

4.2.3

**Comment by altro3** [comment]
@steventen Does it work correctly with KAPT?

**Comment by steventen** [comment]
@altro3 I just tried kapt, it does work without the issue.
