### ISSUE TITLE
ValidatingInterceptor not throwing ConstraintViolationException sometimes

### ISSUE THREAD

**Issue by jbescos** [micronaut-projects/micronaut-core#10370]
### Expected Behavior

I have one test that expects to throw ConstraintViolationException when the input of the next method contains a space:
```
    @Test
    void testBeanValidation() {
        assertThrows(ConstraintViolationException.class, () -> myBean.getOwner("wrong name"), "Name should not contain spaces");
    }

    @ApplicationScoped
    public static class MyBean {
        @Inject
        private DbPetRepository petRepository;
        @Inject
        private Connection connection;
        @Inject
        CdiOnly cdiOnly;

        @Transactional
        public String getOwner(@Pattern(regexp = "\\w+") String pet) {
            assertThat(connection, notNullValue());
            assertThat(cdiOnly.message(), is("Hello"));
            Thread.dumpStack();
            return petRepository.findByName(pet)
                    .map(Pet::getOwner)
                    .map(Owner::getName)
                    .orElse(null);
        }
    }
```

### Actual Behaviour

Sometimes works, and sometimes not. When it fails, the line with `Thread.dumpStack();` prints the next:

```
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:2209)
	at io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean.getOwner(MicronautDataCdiExtensionTest.java:88)
	at io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean$Proxy$_$$_WeldSubclass.getOwner$$super(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at io.helidon.integrations.micronaut.cdi.MicronautMethodInvocationContext.proceed(MicronautMethodInvocationContext.java:124)
	at io.micronaut.transaction.interceptor.TransactionalInterceptor.lambda$intercept$5(TransactionalInterceptor.java:140)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.lambda$execute$2(AbstractPropagatedStatusTransactionOperations.java:68)
	at io.micronaut.transaction.TransactionCallback.apply(TransactionCallback.java:37)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeTransactional(AbstractTransactionOperations.java:333)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeWithNewTransaction(AbstractTransactionOperations.java:318)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeNew(AbstractTransactionOperations.java:235)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:137)
	at io.micronaut.transaction.support.AbstractTransactionOperations.lambda$doExecute$0(AbstractTransactionOperations.java:122)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:143)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:120)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.execute(AbstractPropagatedStatusTransactionOperations.java:65)
	at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:140)
	at io.helidon.integrations.micronaut.cdi.MicronautMethodInvocationContext.proceed(MicronautMethodInvocationContext.java:111)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.helidon.integrations.micronaut.cdi.MicronautInterceptor.invoke(MicronautInterceptor.java:88)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean$Proxy$_$$_WeldSubclass.getOwner(Unknown Source)
	at io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean$Proxy$_$$_WeldClientProxy.getOwner(Unknown Source)
	at io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest.lambda$testBeanValidation$0(MicronautDataCdiExtensionTest.java:58)
```
You can see that next line is executed:
`at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)`

However, there is also a TransactionalInterceptor in the chain that is executed after ValidatingInterceptor. This interceptor is able to hit the `MyBean#getOwner` method I wrote before, and this should not happen.

### Steps To Reproduce

```
git clone https://github.com/jbescos/helidon.git
git checkout issue7206_4x
cd helidon
#With JDK 21
mvn clean install -DskipTests
cd integrations/micronaut/data
#Run this till it fails
mvn clean install
```

### Environment Information

JDK: 21+35-LTS-2513
Linux Mint 21

### Version

4.2.2

**Comment by dstepanov** [comment]
It looks like Helidon doesn't use the annotation metadata generated by Micronaut and that's a big problem. In Micronaut 4 the validation processor annotates the arguments to select them for the validation and that's is missing for you.

**Comment by jbescos** [comment]
@dstepanov sometimes the test is passing as you can see in the below stacktrace. I am not sure this is a Helidon issue, because otherwise, how do you explain the next stacktrace?. This is when the test passes and it correctly throws a ConstraintViolationException. I am going to debug Micronaut to check why sometimes fails and sometimes passes.

```
Thread [main] (Suspended (breakpoint at line 32 in jakarta.validation.ConstraintViolationException))	
	jakarta.validation.ConstraintViolationException.<init>(java.lang.String, java.util.Set<? extends jakarta.validation.ConstraintViolation<?>>) line: 32	
	jakarta.validation.ConstraintViolationException.<init>(java.util.Set<? extends jakarta.validation.ConstraintViolation<?>>) line: 48	
	io.micronaut.validation.ValidatingInterceptor.intercept(io.micronaut.aop.MethodInvocationContext<java.lang.Object,java.lang.Object>) line: 119	
	io.helidon.integrations.micronaut.cdi.MicronautInterceptor.invoke(jakarta.interceptor.InvocationContext) line: 88	
	java.lang.invoke.LambdaForm$DMH.0x00007fe840024000.invokeVirtual(java.lang.Object, java.lang.Object, java.lang.Object) line: not available	
	java.lang.invoke.LambdaForm$MH.0x00007fe840690000.invoke(java.lang.Object, java.lang.Object, java.lang.Object) line: not available	
	java.lang.invoke.Invokers$Holder.invokeExact_MT(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object) line: not available	
	jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[]) line: 154	
	jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.lang.Object, java.lang.Object[]) line: 103	
	java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object...) line: 580	
	org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(jakarta.interceptor.InvocationContext) line: 73	
	org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(java.lang.Object, java.lang.reflect.Method, java.lang.reflect.Method, java.lang.Object[], org.jboss.weld.interceptor.proxy.InterceptorMethodHandler$CachedInterceptionChain, org.jboss.weld.bean.proxy.InterceptionDecorationContext$Stack) line: 84	
	org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(java.lang.Object, java.lang.reflect.Method, java.lang.reflect.Method, java.lang.Object[], org.jboss.weld.interceptor.spi.model.InterceptionType, org.jboss.weld.bean.proxy.InterceptionDecorationContext$Stack) line: 72	
	org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(org.jboss.weld.bean.proxy.InterceptionDecorationContext$Stack, java.lang.Object, java.lang.reflect.Method, java.lang.reflect.Method, java.lang.Object[]) line: 56	
	org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(org.jboss.weld.bean.proxy.InterceptionDecorationContext$Stack, java.lang.Object, java.lang.reflect.Method, java.lang.reflect.Method, java.lang.Object[], boolean, boolean) line: 79	
	org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(org.jboss.weld.bean.proxy.InterceptionDecorationContext$Stack, java.lang.Object, java.lang.reflect.Method, java.lang.reflect.Method, java.lang.Object[]) line: 68	
	io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean$Proxy$_$$_WeldSubclass.getOwner(java.lang.String) line: not available	
	io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$MyBean$Proxy$_$$_WeldClientProxy.getOwner(java.lang.String) line: not available	
	io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest.lambda$testBeanValidation$0() line: 58	
	io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest$$Lambda.0x00007fe840689398.execute() line: not available	
	org.junit.jupiter.api.AssertThrows.assertThrows(java.lang.Class<T>, org.junit.jupiter.api.function.Executable, java.lang.Object) line: 53	
	org.junit.jupiter.api.AssertThrows.assertThrows(java.lang.Class<T>, org.junit.jupiter.api.function.Executable, java.lang.String) line: 39	
	org.junit.jupiter.api.Assertions.assertThrows(java.lang.Class<T>, org.junit.jupiter.api.function.Executable, java.lang.String) line: 3099	
	io.helidon.integrations.micronaut.cdi.data.MicronautDataCdiExtensionTest.testBeanValidation() line: 58	
	java.lang.invoke.LambdaForm$DMH.0x00007fe840130800.invokeVirtual(java.lang.Object, java.lang.Object) line: not available	
	java.lang.invoke.LambdaForm$MH.0x00007fe840684c00.invoke(java.lang.Object, java.lang.Object) line: not available	
	java.lang.invoke.Invokers$Holder.invokeExact_MT(java.lang.Object, java.lang.Object, java.lang.Object) line: not available	
```

**Comment by jbescos** [comment]
I found the missing annotation that happens sometimes:

In `io.micronaut.validation.validator.DefaultValidator#887`
When it works:
`{io.micronaut.validation.annotation.ValidatedElement={}, jakarta.validation.constraints.Pattern={regexp=\w+, payload=[Ljava.lang.Class;@13bdf540, flags=[Ljakarta.validation.constraints.Pattern$Flag;@526e8108, groups=[Ljava.lang.Class;@4dcbae55}, jakarta.validation.constraints.Pattern$List={value=[@jakarta.validation.constraints.Pattern(regexp=\w+, payload=[], flags=[], groups=[])]}}`
When it doesn't work (it is missing `io.micronaut.validation.annotation.ValidatedElement`):
`{jakarta.validation.constraints.Pattern={regexp=\w+, payload=[Ljava.lang.Class;@29896529, flags=[Ljakarta.validation.constraints.Pattern$Flag;@e29f4f6, groups=[Ljava.lang.Class;@41b64020}, jakarta.validation.constraints.Pattern$List={value=[@jakarta.validation.constraints.Pattern(regexp=\w+, payload=[], flags=[], groups=[])]}}`

**Comment by jbescos** [comment]
@dstepanov I found the generated classes by annotation processor contains the `io.micronaut.validation.annotation.ValidatedElement`. You can download the attached folder, that contains the classes. You will see that `$MicronautDataCdiExtensionTest$MyBean$Definition$Exec.class` contains `io.micronaut.validation.annotation.ValidatedElement`, so it is not an issue in Helidon.

Moreover, running the test with the same classes, sometimes passes and sometimes not. This means that it is not related to missing Micronaut annotations.
[classes.zip](https://github.com/micronaut-projects/micronaut-core/files/13939706/classes.zip)

Could you reopen this issue?.

**Comment by dstepanov** [comment]
But Helidon doesn't use those classes, it's using reflection to generate Micronaut method metadata. It needs to be changed to load `BeanDefinition` and use generated method annotation metadata.

**Comment by jbescos** [comment]
> But Helidon doesn't use those classes, it's using reflection to generate Micronaut method metadata. It needs to be changed to load `BeanDefinition` and use generated method annotation metadata.

I disagree, Helidon is already obtaining the method annotation metadata from the BeanDefinition, see: https://github.com/jbescos/helidon/blob/eca0b8ea6267523b923fb9ccc89e44085e76b262/integrations/micronaut/cdi/src/main/java/io/helidon/integrations/micronaut/cdi/MicronautCdiExtension.java#L357

There is actually a micronaut Validated annotation:
![annotationMetadata](https://github.com/micronaut-projects/micronaut-core/assets/4736283/9408806b-512b-4c2d-b0df-149d17519dcd)

And let me stress again that it is working sometimes.

**Comment by jbescos** [comment]
I think I found where the issue is. It is in Helidon in this part:
https://github.com/helidon-io/helidon/blob/224f99d56c7212e9d6426d7310ad1f714f6247b5/integrations/micronaut/cdi/src/main/java/io/helidon/integrations/micronaut/cdi/CdiExecutableMethod.java#L211

When it finds the Repeatable stereotype it ignores the next annotations. For this case, it was ignoring `io.micronaut.validation.annotation.ValidatedElement`.

The randomness comes because the annotations are stored in maps, so they are iterated in different way in each execution.

Now I agree we can close it.

Thank you for your support.
