### ISSUE TITLE
NoSuchMethodError: GenericHttpFilter GenericHttpFilter.terminalFilter(Function)

### ISSUE THREAD

**Issue by TWiStErRob** [micronaut-projects/micronaut-core#10411]
### Expected Behavior

Tests pass as before (skip updating the version to see it work).

### Actual Behaviour

```
2024-01-24T20:51:54,819 DEBUG [default-nioEventLoopGroup-1-1] io.micronaut.http.client.netty.DefaultHttpClient(DefaultHttpClient.java:1765) Sending HTTP GET to http://localhost:8080/favicon.ico
2024-01-24T20:51:54,900 WARN  [qtp181372317-73] org.eclipse.jetty.util.thread.QueuedThreadPool(QueuedThreadPool.java:1198) Job failed
java.lang.NoSuchMethodError: 'io.micronaut.http.filter.GenericHttpFilter io.micronaut.http.filter.GenericHttpFilter.terminalFilter(java.util.function.Function)'
	at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:262)
	at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:143)
	at io.micronaut.servlet.http.ServletHttpHandler$ServletRequestLifecycle.handleNormal(ServletHttpHandler.java:507)
	at io.micronaut.servlet.http.ServletHttpHandler.lambda$service$5(ServletHttpHandler.java:212)
	at io.micronaut.servlet.engine.DefaultServletHttpRequest.lambda$executeAsync$1(DefaultServletHttpRequest.java:176)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
	at org.eclipse.jetty.server.AsyncContextState$1.run(AsyncContextState.java:148)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

1. Clone https://github.com/TWiStErRob/net.twisterrob.travel
2. Check out [3da41da](https://github.com/TWiStErRob/net.twisterrob.travel/commit/3da41da8325bef1cf9c81b074d70006132569bfa)
3. Bump micronaut-http in toml from 4.2.4 to 4.3.0/4.3.1
4. `gradlew :web:status-history:test --tests=IndexControllerIntegrationTest`

### Environment Information

Here's the dependency changes between 4.2.4 to 4.3.1:
[before.txt](https://github.com/micronaut-projects/micronaut-core/files/14043555/before.txt)
[after.txt](https://github.com/micronaut-projects/micronaut-core/files/14043556/after.txt)
(diff the two files)

### Version

https://github.com/TWiStErRob/net.twisterrob.travel/blob/3da41da8325bef1cf9c81b074d70006132569bfa/gradle/libs.versions.toml#L37-L40 + see repro

**Comment by TWiStErRob** [comment]
Caused by removal here: https://github.com/micronaut-projects/micronaut-core/commit/77c198c7bb5d7279da731fb8d7303d29ff194cdd#diff-6b5b6139d725e80e9b5a52a04d1265ce3ea1337008c491423315bf5186824c0dL74 cc @dstepanov

This seems relevant from after.txt:
```
+--- io.micronaut.views:micronaut-views-handlebars:5.1.0
|    +--- io.micronaut.views:micronaut-views-core:5.1.0
|    |    \--- io.micronaut:micronaut-core-bom:4.2.3
|    |         +--- io.micronaut:micronaut-http:4.2.3 -> 4.3.1 (c)
|    |         +--- io.micronaut:micronaut-http-client:4.2.3 -> 4.3.1 (c)
|    |         +--- io.micronaut:micronaut-http-client-core:4.2.3 -> 4.3.1 (c)
|    |         +--- io.micronaut:micronaut-http-netty:4.2.3 -> 4.3.1 (c)
|    |         +--- io.micronaut:micronaut-http-server:4.2.3 (c) <======= interesting one, not matched to 4.3.x
```

I wonder why `io.micronaut.platform:micronaut-platform` doesn't align `-http-` artifacts? cc @sdelamo 

I thought `micronaut { version = "4.2.3" }` would give me some safety.

**Comment by sdelamo** [comment]
why are you defining explicitly these versions: 

```
micronaut = "4.2.1"
micronaut-http = "4.2.4"
micronaut-jackson = "2.7.1"
micronaut-handlebars = "5.1.0"
```

You should only define:
```
micronaut = "4.2.4"
```

and use [the BOM](https://github.com/micronaut-projects/micronaut-platform).

You should only define one version. The version of Micronaut platform 4.2.4 and use: 

```
    annotationProcessor(platform("io.micronaut.platform:micronaut-platform:4.2.4"))
    implementation(platform("io.micronaut.platform:micronaut-platform:4.2.4"))
    testAnnotationProcessor(platform("io.micronaut.platform:micronaut-platform:4.2.4"))
    testImplementation(platform("io.micronaut.platform:micronaut-platform:4.2.4"))
```

You can check the versions we know work well together: 

https://github.com/micronaut-projects/micronaut-platform/blob/4.2.x/gradle/libs.versions.toml

**Comment by TWiStErRob** [comment]
Blesseth be thy versions 🤓, thanks it works: https://github.com/TWiStErRob/net.twisterrob.travel/pull/93/commits/ae9987fc99505b3760f5a700f18cd6ed1c42b4e5

It seems the BOM is already added by the Gradle plugin.
