### ISSUE TITLE
Issue with consul on GKE

### ISSUE THREAD

**Issue by ramzimaalej** [micronaut-projects/micronaut-core#1041]
I created a mn application with service discovery that I deployed on GKE. The application is able to register itself with consul, but then I'm receiving this exception in the logs.

My app has nothing other than a websocket server enabled.
Any ideas why this is happening?

`io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | null
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:608)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
	at io.micronaut.cache.interceptor.CacheInterceptor$1$1$1.onError(CacheInterceptor.java:415)
	at io.reactivex.internal.util.HalfSerializer.onError(HalfSerializer.java:70)
	at io.reactivex.internal.subscribers.StrictSubscriber.onError(StrictSubscriber.java:103)
	at io.reactivex.internal.operators.flowable.FlowableReduce$ReduceSubscriber.onError(FlowableReduce.java:96)
	at io.reactivex.internal.operators.flowable.FlowableReduce$ReduceSubscriber.onNext(FlowableReduce.java:84)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663)
	at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:141)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:53)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onNext(FlowableOnErrorNext.java:79)
	at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:141)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:53)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:307)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapInnerSubscriber.onNext(FlowableSwitchMap.java:391)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onNext(FlowableOnErrorNext.java:79)
	at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutSubscriber.onNext(FlowableTimeoutTimed.java:99)
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.lambda$onNext$1(ClientServerRequestTracingPublisher.java:60)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:60)
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableCreate$NoOverflowBaseAsyncEmitter.onNext(FlowableCreate.java:403)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1763)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1695)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:189)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at io.micronaut.discovery.CompositeDiscoveryClient.lambda$getInstances$1(CompositeDiscoveryClient.java:64)
	at io.reactivex.internal.operators.flowable.FlowableReduce$ReduceSubscriber.onNext(FlowableReduce.java:80)
	... 65 more
"  
`

**Comment by ramzimaalej** [comment]
I'm also seeing this message in the logs.

`i.m.d.registration.AutoRegistration - Error reporting passing state to Consul: Internal Server Error`

**Comment by graemerocher** [comment]
you can set the `host` explicitly to the IP address. Otherwise if you wish to send a PR the code that performs the registration is here: https://github.com/micronaut-projects/micronaut-core/blob/master/discovery-client/src/main/java/io/micronaut/discovery/consul/registration/ConsulAutoRegistration.java#L165

**Comment by graemerocher** [comment]
I pushed some changes that allow using `consul.client.registration.prefer-ip-address` and an explicit `consul.client.registration.ip-addr` setting to override the lookup.

If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.0.2.BUILD-SNAPSHOT'
    }
}
```

**Comment by ramzimaalej** [comment]
@graemerocher I tested this very quickly today and I noticed the following errors:

On micronaut side: i.m.d.registration.AutoRegistration - Error reporting passing state to Consul: Internal Server Error

On Consul side: HTTP request failed: Get http://notification-service-7dd96b849-r4x77:8080/health: dial tcp: lookup notification-service-7dd96b849-r4x77 on 10.0.0.10:53: no such host

I sorry I could not do further investigation as I'm swamped with other production issues.

**Comment by rvanderwerf** [comment]
This is working for me, however micronaut crashes after about 30 minutes with out of memory. There are tons of netty memory leak messages show (probably a leak for each status sent to consul):
2019-01-31 00:33:11
06:33:11.185 [nioEventLoopGroup-1-4] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
2019-01-31 00:33:11
Recent access records:
2019-01-31 00:33:11
Created at:
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:221)
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:199)
2019-01-31 00:33:11
io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:255)
2019-01-31 00:33:11
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
2019-01-31 00:33:11
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
2019-01-31 00:33:11
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
2019-01-31 00:33:11
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
2019-01-31 00:33:11
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-01-31 00:33:11
java.lang.Thread.run(Thread.java:748)
2019-01-31 00:33:11
06:33:11.186 [nioEventLoopGroup-1-4] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
2019-01-31 00:33:11
Recent access records:
2019-01-31 00:33:11
Created at:
2019-01-31 00:33:11
io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
2019-01-31 00:33:11
io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
2019-01-31 00:33:11
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
2019-01-31 00:33:11
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
2019-01-31 00:33:11
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
2019-01-31 00:33:11
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-01-31 00:33:11
java.lang.Thread.run(Thread.java:748)
2019-01-31 00:33:11
06:33:11.186 [nioEventLoopGroup-1-4] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
2019-01-31 00:33:11
Recent access records:
2019-01-31 00:33:11
Created at:
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:221)
2019-01-31 00:33:11
io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:199)
2019-01-31 00:33:11
io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:255)
2019-01-31 00:33:11
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
2019-01-31 00:33:11
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
2019-01-31 00:33:11
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2019-01-31 00:33:11
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2019-01-31 00:33:11
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2019-01-31 00:11:07
06:11:07.277 [nioEventLoopGroup-1-3] INFO i.m.d.registration.AutoRegistration - Registered service [scheduler] with Consul
2019-01-31 00:11:07
06:11:07.140 [main] INFO io.micronaut.runtime.Micronaut - Startup completed in 8589ms. Server Running: http://ab2015065381:8098
2019-01-31 00:11:06
06:11:06.675 [main] WARN o.g.d.g.v.c.e.DefaultConstraintEvaluator - Derived properties may not be constrained. Property [eventId] of domain class com.css.scheduler.domain.TimeSlot will not be checked during validation.
2019-01-31 00:11:06
06:11:06.549 [main] WARN o.g.d.g.v.c.b.ConstrainedPropertyBuilder - Property [runVersion] of domain class com.css.scheduler.domain.Schedule has type [int] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2019-01-31 00:11:05
06:11:05.754 [Thread-2] INFO c.c.s.service.ScheduleUpsertService - Starting schedule update server on localhost:9091
2019-01-31 00:11:05
06:11:05.069 [main] INFO o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2019-01-31 00:11:04
06:11:04.926 [main] INFO o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
2019-01-31 00:11:04
06:11:04.901 [main] INFO o.g.o.h.GrailsHibernateTransactionManager - Using DataSource [org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy@d120d7c] of Hibernate SessionFactory for HibernateTransactionManager
2019-01-31 00:11:03
06:11:03.657 [main] INFO org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
2019-01-31 00:11:03
06:11:03.585 [main] INFO o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2019-01-31 00:11:03
06:11:03.391 [main] INFO o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
2019-01-31 00:11:03
06:11:03.363 [main] INFO o.h.validator.internal.util.Version - HV000001: Hibernate Validator null
2019-01-31 00:11:03
06:11:03.294 [main] INFO org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
2019-01-31 00:11:03
06:11:03.292 [main] INFO org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
2019-01-31 00:11:03
06:11:03.291 [main] INFO org.hibernate.Version - HHH000412: Hibernate Core {5.1.9.Final}
2019-01-31 00:11:01
06:11:01.345 [main] INFO i.m.c.h.g.HibernateDatastoreFactory - Starting GORM for Hibernate
2019-01-31 00:10:58
06:10:58.518 [main] INFO i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, qa]
