### ISSUE TITLE
Configuring micronaut.server.netty.compression-level ends in strange StringIndexOutOfBoundsException since version 4.2.0

### ISSUE THREAD

**Issue by mschlebusch** [micronaut-projects/micronaut-core#10543]
### Expected Behavior

micronaut.server.netty.compression-level should be configurable with value 9 as before.

### Actual Behaviour

Since version 4.2.0 there is an strange StringIndexOutOfBoundsException caused by ReadableBytesTypeConverter#convert when configuring micronaut.server.netty.compression-level with valid int value 9. Till micronaut version 4.1.6 it worked fine, because there was an change in ReadableBytesTypeConverter#convert since 4.2.0 which executes the following:

```
long numberPart = Long.parseLong(value.substring(0, value.length() - 2));
```

Since configured value 9 is related to the docs a valid int config value, this line causes an StringIndexOutOfBoundsException. 

Strange is, that the following lines in the convert function are expecting any size units such as "KB", "MB" or "GB". Those units are not valid for configuring the netty compression-level (see https://docs.micronaut.io/4.2.0/guide/configurationreference.html). Don't know if this converter should not be executed for this config value but it already did in previous versions (e. g. 4.1.6).

```
09:39:59.881 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.xml.jackson.server.XmlHttpContentSubscriberFactory] could not be loaded: Error instantiating bean of type  [io.micronaut.xml.jackson.server.XmlHttpContentSubscriberFactory]

Message: begin 0, end -1, length 1
Path Taken: new XmlHttpContentSubscriberFactory(NettyHttpServerConfiguration configuration) --> new XmlHttpContentSubscriberFactory([NettyHttpServerConfiguration configuration])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.xml.jackson.server.XmlHttpContentSubscriberFactory] could not be loaded: Error instantiating bean of type  [io.micronaut.xml.jackson.server.XmlHttpContentSubscriberFactory]

Message: begin 0, end -1, length 1
Path Taken: new XmlHttpContentSubscriberFactory(NettyHttpServerConfiguration configuration) --> new XmlHttpContentSubscriberFactory([NettyHttpServerConfiguration configuration])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1980)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:291)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3322)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3677)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:199)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at com.dw.sitemaps.SitemapServiceApplication.main(SitemapServiceApplication.java:23)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.xml.jackson.server.XmlHttpContentSubscriberFactory]

Message: begin 0, end -1, length 1
Path Taken: new XmlHttpContentSubscriberFactory(NettyHttpServerConfiguration configuration) --> new XmlHttpContentSubscriberFactory([NettyHttpServerConfiguration configuration])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2324)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2917)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1729)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.xml.jackson.server.$XmlHttpContentSubscriberFactory$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2676)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1974)
	... 7 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at io.micronaut.core.convert.format.ReadableBytesTypeConverter.convert(ReadableBytesTypeConverter.java:47)
	at io.micronaut.core.convert.DefaultMutableConversionService$4.convert(DefaultMutableConversionService.java:595)
	at io.micronaut.core.convert.DefaultMutableConversionService$4.convert(DefaultMutableConversionService.java:586)
	at io.micronaut.core.convert.DefaultMutableConversionService$2.convert(DefaultMutableConversionService.java:327)
	at io.micronaut.core.convert.DefaultMutableConversionService$2.convert(DefaultMutableConversionService.java:318)
	at io.micronaut.core.convert.DefaultMutableConversionService.convert(DefaultMutableConversionService.java:256)
	at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:50)
	at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:128)
	at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:394)
	at io.micronaut.context.DefaultApplicationContext.getProperty(DefaultApplicationContext.java:231)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolvePropertyValue(AbstractInitializableBeanDefinition.java:2108)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getPropertyValueForSetter(AbstractInitializableBeanDefinition.java:1076)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfiguration$Definition.inject(Unknown Source)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfiguration$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
	... 27 common frames omitted
4 actionable tasks: 1 executed, 3 up-to-date
```

### Steps To Reproduce

Configure micronaut.server.netty.compression-level with int value 9 since Micronaut version 4.2.0.

### Environment Information

Windows 11, JDK 17

### Version

4.2.0

**Comment by mschlebusch** [comment]
Fixed with https://github.com/micronaut-projects/micronaut-core/issues/10401
