### ISSUE TITLE
Micronaut 4 with Logbook does not seem to work anymore

### ISSUE THREAD

**Issue by ericsnx** [micronaut-projects/micronaut-core#10633]
### Expected Behavior

To be able perform request and response logging

### Actual Behaviour

Something seems to be broken and therefore we are unable to properly setup the customizer.

```
09:42:34.217 [default-nioEventLoopGroup-1-7] ERROR i.m.h.n.AbstractCompositeCustomizer - Failed to trigger customizer event
java.util.NoSuchElementException: http-streams-codec
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at com.example.LogbookNettyServerCustomizer$Customizer.onStreamPipelineBuilt(LogbookFactory.kt:71)
	at io.micronaut.http.netty.AbstractCompositeCustomizer.forEach(AbstractCompositeCustomizer.java:109)
	at io.micronaut.http.server.netty.CompositeNettyServerCustomizer.onStreamPipelineBuilt(CompositeNettyServerCustomizer.java:53)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.configureForHttp1(HttpPipelineBuilder.java:383)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.initChannel(HttpPipelineBuilder.java:299)
	at io.micronaut.http.server.netty.NettyHttpServer$Listener.initChannel(NettyHttpServer.java:892)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

1. Clone and Execute the project 
 `https://github.com/ericsnx/micronaut-logbook-issue`

2. Call `curl http://localhost:8080/hello/world`

3. Error should be logged in the logs.

### Environment Information

Jdk Version: 17 and 21.

### Example Application

https://github.com/ericsnx/micronaut-logbook-issue

### Version

4.3.6

**Comment by yawkat** [comment]
The netty pipeline is not stable between micronaut versions. you have to update customizers to work with new micronaut versions. The current logbook setup is described here: https://docs.micronaut.io/latest/guide/index.html#nettyServerPipeline

Also be aware that the logbook integration may stop working by default in 4.5.0 for http2. https://github.com/micronaut-projects/micronaut-core/discussions/10524

**Comment by ericsnx** [comment]
@yawkat Thanks for the quick reply, I did not understand what exactly I need to update though, I actually used this exact link to set up my customizer, I'm not sure what i'm missing here.

**Comment by yawkat** [comment]
the setup in the docs changes slightly. your code is not the same as the docs, you likely used a previous version. please change it to match the docs.

in the medium term i think a micronaut-logbook module will have to be introduced.

**Comment by ericsnx** [comment]
> the setup in the docs changes slightly. your code is not the same as the docs, you likely used a previous version. please change it to match the docs.
> 
> in the medium term i think a micronaut-logbook module will have to be introduced.

Ok, I will try again then, Thanks.


**Update**: I literally copied and pasted the code form the docs and still I've got.

```
15:11:23.301 [default-nioEventLoopGroup-1-3] ERROR i.m.h.n.AbstractCompositeCustomizer - Failed to trigger customizer event
java.util.NoSuchElementException: micronaut-http-response
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at com.example.LogbookNettyServerCustomizer$Customizer.onStreamPipelineBuilt(LogbookFactory.kt:63)
	at io.micronaut.http.netty.AbstractCompositeCustomizer.forEach(AbstractCompositeCustomizer.java:109)
	at io.micronaut.http.server.netty.CompositeNettyServerCustomizer.onStreamPipelineBuilt(CompositeNettyServerCustomizer.java:53)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.configureForHttp1(HttpPipelineBuilder.java:383)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.initChannel(HttpPipelineBuilder.java:299)
	at io.micronaut.http.server.netty.NettyHttpServer$Listener.initChannel(NettyHttpServer.java:892)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

something is not right cc: @yawkat 

I will leave this for now because I spend half day of work, maybe docs are outdated, not sure my project is available on gh if anyone feels like having a go.
