### ISSUE TITLE
Memory leak on Micronaut HTTP server

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-core#10677]
### Expected Behavior

No memory leak.

### Actual Behaviour

Heap histograms show a potential memory leak.
The following part of the heap histograms are relevant:
```
   1:      57108507     1370604168  io.micronaut.core.execution.DelayedExecutionFlowImpl$Map
   2:      57108505     1370604120  io.micronaut.core.execution.DelayedExecutionFlowImpl$OnErrorResume
   3:      38072339      913736136  io.micronaut.core.execution.DelayedExecutionFlowImpl$FlatMap
   4:      19036169      456868056  io.micronaut.core.execution.DelayedExecutionFlowImpl$OnComplete
```

There are more than 50 millions of `io.micronaut.core.execution.DelayedExecutionFlowImpl$Map` in memory! And this heap histogram is on an application with very few request (so there cannot be 50 millions of file currently uploading).

I think it may be related to this endpoint that bind one part with `@Part Publisher<StreamingFileUpload> files` then use a raw `HttpRequest<?> inputs` as we have parts both as files and String attributes.

```java
@ExecuteOn(TaskExecutors.IO)
    @Post(uri = "/{namespace}/{id}", consumes = MediaType.MULTIPART_FORM_DATA)
    public Execution create(
        @Parameter(description = "The inputs") HttpRequest<?> inputs, 
        @Parameter(description = "The inputs of type file") @Nullable @Part Publisher<StreamingFileUpload> files
    ) throws IOException {
        Map<String, Object> inputMap = (Map<String, Object>) inputs.getBody(Map.class).orElse(null);
        // do something with the files ..
    }
```

The memory leak is new in Micronaut 4, in Micronaut 3 we bind multiple times the body, once in a part as today, and once in an `@Body Map<String, Object> inputMap` which is no more possible in Micronaut 4.

Reference GitHUb discussion: https://github.com/micronaut-projects/micronaut-core/discussions/10662GitHub

### Environment Information

- Operating System: Linux 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Lin
- Java: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1

### Version

4.3.4

**Comment by loicmathieu** [comment]
In fact I have the feeling that this memory leak is coming from the Access Log, if I disable them, I didn't saw any `io.micronaut.core.execution.DelayedExecutionFlowImpl` in the heap but when I enable it those objects starts to pille up.

This is our access log configuration:

```yaml
micronaut:
  server:
    netty:
      access-logger:
        enabled: true
        logger-name: io.kestra.webserver.access
        log-format: "%{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}t | %r | status: %s | ip: %a | length: %b | duration: %D"
        exclusions:
          - /ui/.+
          - /health
          - /prometheus
```

**Comment by loicmathieu** [comment]
I don't know if it is of any help but I notice on an heap dump that it appears that in the `DelayedExecutionFlowImpl` there is a head attribute which contains a next attribute which contains a next attribute... recursively without apparent ends, looks like all the  `DelayedExecutionFlowImpl`  are next of a parent one ...

**Comment by loicmathieu** [comment]
cc @yawkat

**Comment by loicmathieu** [comment]
More information to help diagnose the issue.
A single `StreamingByetBody` is handling 6 millions `DelayedExecutionFloImplt$OnErrorResume` objects into a `RequestLifecycle` lambda retaining 1.6GB.
![image](https://github.com/micronaut-projects/micronaut-core/assets/1819009/a65bb562-80a9-4a62-958f-203992d7cfc3)

**Comment by tchiotludo** [comment]
Just raw information, our whole application is broken due to this memory leak and customers and users are complaining, we try multiple workaround with no success 😭
We also try to make a PR, but definitely http server part are really complex for new comers. 
If you have any workaround advice, it will be awesome

**Comment by yawkat** [comment]
@tchiotludo please give us some way to reproduce this. The form/multipart code is very complex and I don't see a starting point for debugging here

**Comment by loicmathieu** [comment]
@yawkat it's very problematic as I didn't succeed in reproducing the problem.

That's why I added as much information as I could; users seem to not using form/multipart that much, and the memory leak points to `RequestLifecycle` so I'm not sure it is linked to form/multipart at all.

I can ask if I can share the dump if you want, but as a memory dump can contain sensitive data, I need to check first with the user and share it privately.

I can ask our users to provide more information but creating a reproducer seems to be very complex.

**Comment by yawkat** [comment]
you could try setting `micronaut.server.netty.server-type: full_content`

**Comment by loicmathieu** [comment]
Thanks @yawkat we will test it, meanwhile I'll try my best to make a reproducer

**Comment by katoquro** [comment]
Hello. 
We don't use multipart data at all. Recently I've deployed a new service that answers only health checks, promethus metrics, and rare POSTs with data to store it mongo. It is a very simple micro so I gave 0.5 Gb of RAM to it and I see 1 per day or 2 days OOM there
We use MN 4.2.0, netty, NO GraalVM, and Project Reactor everywhere
I'll try to investigate a bit deeper later

**Comment by loicmathieu** [comment]
@yawkat we cannot use `micronaut.server.netty.server-type: full_content` it crash for all requests with:

```
2024-04-09 11:33:36,466 WARN  default-nioEventLoopGroup-1-3 io.netty.channel.ChannelInitializer Failed to initialize a channel. Closing: [id: 0x646fd7cb, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:48850]
java.lang.IllegalArgumentException: maxContentLength : -2147483648 (expected: >= 0)
	at io.netty.util.internal.ObjectUtil.checkPositiveOrZero(ObjectUtil.java:144)
	at io.netty.handler.codec.MessageAggregator.validateMaxContentLength(MessageAggregator.java:88)
	at io.netty.handler.codec.MessageAggregator.<init>(MessageAggregator.java:77)
	at io.netty.handler.codec.http.HttpObjectAggregator.<init>(HttpObjectAggregator.java:128)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$StreamPipeline.insertMicronautHandlers(HttpPipelineBuilder.java:608)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$StreamPipeline.insertHttp1DownstreamHandlers(HttpPipelineBuilder.java:638)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.configureForHttp1(HttpPipelineBuilder.java:380)
	at io.micronaut.http.server.netty.HttpPipelineBuilder$ConnectionPipeline.initChannel(HttpPipelineBuilder.java:299)
	at io.micronaut.http.server.netty.NettyHttpServer$Listener.initChannel(NettyHttpServer.java:892)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by loicmathieu** [comment]
@katoquro to check if it's the same issue you can try the following command to see if the same objects are accumulating:

```
jmap -histo:live <pid> | grep io.micronaut.core.execution
```

**Comment by yawkat** [comment]
@loicmathieu only works if you lower your max-request-size to something that fits in memory.

**Comment by loicmathieu** [comment]
@yawkat on user confirm that using the following configuration fixes the issue (or works around it):

```yaml
configuration:
  micronaut:
    server:
      max-request-size: 1GB
      netty:
        server-type: full_content
```

**Comment by loicmathieu** [comment]
@yawkat with this configuration, file of more than 1GB lead to a request that seems to be "blocked forever" without an exception. So it's a workaround for some of our users but not a long term solution.

Do you still need a reproducer (I'm working on it but still didn't make it reproduce the issue)?

**Comment by yawkat** [comment]
yes i still need a reproducer, either from you or from @katoquro .

full_content buffers the full request and bypasses most places that use DelayedExecutionFlow. but it's not recommended for permanent use.

**Comment by katoquro** [comment]
@loicmathieu 
from the first glance, not my case. The micro is run for 5 hours
```
4245:             1             24  io.micronaut.core.execution.ImperativeExecutionFlowImpl
```
I will look for a leak in another place 🤔
![image](https://github.com/micronaut-projects/micronaut-core/assets/1694937/90b783fc-aff9-4431-bc51-9372255f9703)

**Comment by loicmathieu** [comment]
@katoquro remove the grep and look at the most present objects in the histogram: `jmap -histo:live <pid>` you took multiple one and check which objects grow in number this could be an easy way to find a leak.

And if it's a different leak, better to open a new issue ;)

**Comment by dstepanov** [comment]
Can you analyze the memory dump and see what is being leaked? You can try https://eclipse.dev/mat/

**Comment by katoquro** [comment]
@dstepanov @loicmathieu 
I think my case is really different. I have next graph where green line is metrics about total committed heap provided by micronenter (sum of `jvm_memory_committed_bytes`) and yellow is the consumed memory by the java process taken from `/proc/<pid>/stat` 
![image](https://github.com/micronaut-projects/micronaut-core/assets/1694937/908802e5-a9d6-4e65-bf30-d84d653b9928)

it's something out of heap, non-heap, etc... 🤔

**Comment by graemerocher** [comment]
@loicmathieu any luck on a reproducer?

**Comment by loicmathieu** [comment]
@graemerocher unfortunately, no, that's why I added as much information as I could have.

**Comment by graemerocher** [comment]
@loicmathieu is there a way to run a Kestra locally to reproduce?

**Comment by loicmathieu** [comment]
@graemerocher yes, you can either run it from its [repository](https://github.com/kestra-io/kestra) or its [docker image](https://kestra.io/docs/installation/docker).

But what very annoy me is that I cannot reproduce it myself, some users report the issue, I tried to setup Kestra locally with the same configuration and use it with the same scenario but didn't succeed in triggering the issue.

I'll try to take some time this week to try to reproduce the issues I opened lately.

**Comment by graemerocher** [comment]
ok thanks

**Comment by tchiotludo** [comment]
Sorry for the up, but the issue is still present on our [latest version](https://github.com/kestra-io/kestra/tree/v0.20.11) with [micronaut platform 4.7.0 ](https://github.com/kestra-io/kestra/blob/v0.20.11/platform/build.gradle#L31C1-L31C67). 

We are still unable to reproduce locally, and only one of user was able to reproduce quickly @brokenjacobs  with its environnements can reproduce the issues, crashing the production and being able to reproduce in 5 min in the develop env. 

We can see in the heap : 
```
   1:      99740294     2393767056  io.micronaut.core.execution.DelayedExecutionFlowImpl$Map
   2:      99740287     2393766888  io.micronaut.core.execution.DelayedExecutionFlowImpl$OnErrorResume
   3:      66493528     1595844672  io.micronaut.core.execution.DelayedExecutionFlowImpl$FlatMap
   4:      33246765      79792236
0  io.micronaut.core.execution.DelayedExecutionFlowImpl$OnComplete
``` 

The user just need to browse multiple page on the ui of kestra, to reproduce this issue. 
The pods was using 8Gb of memory during this time and stop responding (normally 2Gb). 
Without browsing the ui, the application will not crashed despite a lot of service is running in the background. 

Any things that we could provide (except a reproducer to help you debug) 

Attached threadump : 
[jattach-output.txt](https://github.com/user-attachments/files/18382746/jattach-output.txt)

**Comment by brokenjacobs** [comment]
I guess we got "lucky".

**Comment by graemerocher** [comment]
@brokenjacobs @tchiotludo it would be good if you could run it with Netty leak detection set to paranoid. See https://docs.micronaut.io/4.7.11/guide/configurationreference.html#io.micronaut.http.netty.configuration.NettyGlobalConfiguration

**Comment by loicmathieu** [comment]
@dstepanov the fix provided in https://github.com/micronaut-projects/micronaut-core/pull/11546 has been tested successfully since multiple days and no more out of memory.
Moreover, memory usage is less than with the workaround of `server-type: full_content`.

**Comment by loicmathieu** [comment]
Thanks all the team for your support in fixing this issue.
