### ISSUE TITLE
Deserialization into Kotlin data class with more than 32 attributes

### ISSUE THREAD

**Issue by temofey1989** [micronaut-projects/micronaut-core#10730]
### Expected Behavior

System should be able to deserialize into Kotlin data class with more than 32 attribute.

### Actual Behaviour

During deserialization into data class with more than 32 attributes, the system throws an exception:
```
java.lang.NoSuchMethodError: 'void com.test.Product.<init>(..., int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at com.test.$Product$Introspection.instantiateInternal(Unknown Source)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:327)
	at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserialize(SimpleRecordLikeObjectDeserializer.java:87)
	at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserializeNullable(SimpleRecordLikeObjectDeserializer.java:102)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:177)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:169)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:215)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:141)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:168)
```

Kotlin Compiler creates groups of 32 for attributes to manage defaults. See [this thread](https://kotlinlang.slack.com/archives/C7L3JB43G/p1711535217541629) for explanation.
In case you have more then 32 attributes in your data class and defaults in both "groups", Kotlin Compiler will create constructor for both groups.

`Product.decompiled.java`:
```java
   ...
   // $FF: synthetic method
   public Product(String var1, ..., int var40, int var41, DefaultConstructorMarker var42) {
      if ((var40 & 1073741824) != 0) {
         var31 = null;
      }

      if ((var40 & Integer.MIN_VALUE) != 0) {
         var32 = null;
      }

      if ((var41 & 1) != 0) {
         var33 = null;
      }

      if ((var41 & 2) != 0) {
         var34 = null;
      }

      ...

      this(var1, ... var39);
   }
   ...
```
In this code example there are two groups: `var40` and `var41`.

Nevertheless, the logic of generation of introspection is a little bit different.
`Product$Introspection.java`:
```java
   ...
       public Object instantiateInternal(Object[] var1) {
        int var2 = 0;
        if ((String)var1[30] == null) {
            var2 |= 1073741824;
        }

        if ((OffsetDateTime)var1[31] == null) {
            var2 |= Integer.MIN_VALUE;
        }

        if ((ProductBaseAllOfRefinancingAmountLimit)var1[32] == null) {
            var2 |= 0;
        }

        if ((Integer)var1[33] == null) {
            var2 |= 0;
        }
        
        ...

        return new Product((String)var1[0], ..., (List)var1[38], var2, (DefaultConstructorMarker)null);
    }
```
You can see that `var2` is pushed as attribute of the constructor of the `Product` class.
And than you'll get an exception, because this constructor does not exist.
You need a second group parameter.

### Steps To Reproduce

1. Use Kotlin language
2. Create data class with more than 32 attributes. These attributes should have defaults in "first group" (e.g. first attribute has `null` as default value) and similar attribute in "second group" (e.g. last attribute has also `null` as default value).
3. Create an object of that data class.
4. Serialize it into String using `io.micronaut.serde.ObjectMapper`
5. Deserialize this text back into the instance of the data class. This step should fail.

### Environment Information

- macOS 14.3.1
- JDK 17

### Version

4.2.1

**Comment by temofey1989** [comment]
Ou... I see that this problem is fixed in `4.3.5`...
Nevertheless, there is a problem with order of the parameters...

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.LocalDate (java.lang.String and java.time.LocalDate are in module java.base of loader 'bootstrap')
	at com.example.$Product$Introspection.instantiateInternal(Unknown Source)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:327)
	at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserialize(SimpleRecordLikeObjectDeserializer.java:89)
	at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserializeNullable(SimpleRecordLikeObjectDeserializer.java:104)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:203)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:195)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:241)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:141)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:168)
```

See this problem in [this repo](https://github.com/temofey1989/micronaut-bug).

**Comment by temofey1989** [comment]
Ok. I think I got it...
In the introspected code of example in the [repo](), there is a code:
```java
    public Object instantiateInternal(Object[] var1) {
        int var2 = 0;
        if ((String)var1[31] == null) {
            var2 |= Integer.MIN_VALUE;
        }

        int var3 = 0;
        if ((LocalDate)var1[0] == null) {
            var3 |= 1;
        }

        return new Product((String)var1[0], ((Number)var1[1]).longValue(), (String)var1[2], ((Number)var1[3]).longValue(), (String)var1[4], ((Number)var1[5]).longValue(), (String)var1[6], ((Number)var1[7]).longValue(), (String)var1[8], ((Number)var1[9]).longValue(), (String)var1[10], ((Number)var1[11]).longValue(), (String)var1[12], ((Number)var1[13]).longValue(), (String)var1[14], ((Number)var1[15]).longValue(), (String)var1[16], ((Number)var1[17]).longValue(), (String)var1[18], ((Number)var1[19]).longValue(), (String)var1[20], ((Number)var1[21]).longValue(), (String)var1[22], ((Number)var1[23]).longValue(), (String)var1[24], ((Number)var1[25]).longValue(), (String)var1[26], ((Number)var1[27]).longValue(), (String)var1[28], ((Number)var1[29]).longValue(), ((Number)var1[30]).intValue(), (String)var1[31], (LocalDate)var1[32], (OffsetDateTime)var1[33], (String)var1[34], ((Number)var1[35]).longValue(), (String)var1[36], ((Number)var1[37]).longValue(), (String)var1[38], ((Number)var1[39]).longValue(), var2, var3, (DefaultConstructorMarker)null);
    }
```
The problem on this line:
```java
        if ((LocalDate)var1[0] == null) {
```
It algorithm should respect a "group number" (length 32) of the constructor attributes array (`var1`).
I guess it should be:
```java
        if ((LocalDate)var1[32] == null) {
```
like on line:
```java
        return new Product(..., (LocalDate)var1[32], ...);
```

**Comment by dstepanov** [comment]
Maybe you can try to fix it here https://github.com/micronaut-projects/micronaut-core/blob/4.4.x/core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java#L250

And add a test like [KotlinBeanIntrospectionSpec.kt](https://github.com/micronaut-projects/micronaut-core/commit/5d6e5ac84d804c48613b1e839fe5d6cbc5dbd4ab#diff-f514d065d0e2b941d737f1bd762dd8d5fea944267d712d61f16d7ebb9b4ca042)
