### ISSUE TITLE
Micronaut Controller not working with lombok

### ISSUE THREAD

**Issue by f-ambroz** [micronaut-projects/micronaut-core#10731]
### Expected Behavior

When injecting dependency with constructor dependency injection using lomboks 
```java 
@RequiredArgsConstructor(onConstructor_ = @Inject)
```
 with 
```java 
private final MyService myService;
```
 as field in controller class, Injection should be successful.

### Actual Behaviour

When trying to call a endpoint on controller following error occurs:
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type  [com.my.amazing.package.api.controller.MyController]

Message: com.my.amazing.package..api.controller.MyController: method 'void <init>()' not found
Path Taken: new MyController()

# Workaround
Use instead lomboks
```java
@Setter(onMethod_ = @Inject)
```
with
```java
private MyService myService;
```

### Steps To Reproduce

Have following controller
```java
package com.my.amazing.package.api.controller;

import jakarta.inject.Inject;

import com.my.amazing.package.api.service.MyService;

import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Get;
import lombok.RequiredArgsConstructor;

@Controller
@RequiredArgsConstructor(onConstructor_ = {@Inject})
public class MyController {
    private final MyService myService;

    @Get("/my-endpoint")
    public HttpResponse<Void> callMe() throws IOException {
        myService.doStuff();
        return HttpResponse.ok();
    }
}
```

## OS
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

## Java
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)

## Build
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Version

4.3.8

**Comment by dstepanov** [comment]
Please make sure you have the correct order of the annotation processors

**Comment by f-ambroz** [comment]
Sorry, I have forgotten to add the pom.
here is the desired section
```xml
<annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-http-validation</artifactId>
              <version>${micronaut.core.version}</version>
            </path>
            <path>
              <groupId>io.micronaut.openapi</groupId>
              <artifactId>micronaut-openapi</artifactId>
              <version>${micronaut.openapi.version}</version>
              <exclusions>
                <exclusion>
                  <groupId>io.micronaut</groupId>
                  <artifactId>micronaut-inject</artifactId>
                </exclusion>
              </exclusions>
            </path>
            <path>
              <groupId>io.micronaut.serde</groupId>
              <artifactId>micronaut-serde-processor</artifactId>
              <version>${micronaut.serialization.version}</version>
              <exclusions>
                <exclusion>
                  <groupId>io.micronaut</groupId>
                  <artifactId>micronaut-inject</artifactId>
                </exclusion>
              </exclusions>
            </path>
          </annotationProcessorPaths>
```

**Comment by dstepanov** [comment]
Please create a sample project

**Comment by f-ambroz** [comment]
## Example Application
[https://github.com/f-ambroz/micronaut-lombok-sample-project](https://github.com/f-ambroz/micronaut-lombok-sample-project)

Using lomboks `@Setter` fixes
```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type [com.my.amazing.package.api.controller.MyController]

Message: com.my.amazing.package..api.controller.MyController: method 'void ()' not found
Path Taken: new MyController()
```
However, now I have found new error:

```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
        at com.my.amazing.pckg.api.controller.MyController.callMe(MyController.java:22)
        at com.my.amazing.pckg.api.controller.$MyController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
        at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:230)
        at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)
        at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:478)
        at io.micronaut.http.server.RequestLifecycle.callRoute(RequestLifecycle.java:201)
        at io.micronaut.http.server.RequestLifecycle.executeRoute(RequestLifecycle.java:191)
        at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$1(RequestLifecycle.java:181)
        at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:155)
        at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:135)
        at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:357)
        at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:181)
        at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:88)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:227)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:388)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```
It says, that the injected service is null

**Comment by dstepanov** [comment]
This configuration will append the extra processors to the parent's processors. You need to override the configuration completely `annotationProcessorPaths combine.self="override"`

**Comment by f-ambroz** [comment]
When I tried using annotationProcessorPaths combine.self="override", the endpoint wasn't alive returning 'page not found'. The same thing for swagger-ui

**Comment by dstepanov** [comment]
Because you are missing `micronaut-inject-java`

**Comment by f-ambroz** [comment]
You are right, my bad. I had commented-out that section before. Thank you for support!
