### ISSUE TITLE
Micronaut 4: migration issues

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-core#10817]
### Expected Behavior

# Use case 1: A project dependency has a DTO that requires arbitrary parsing

The following DTO comes from a library dependency.

```java
public class TokenizerResponse {
    @Getter
    public List<Object> parseTree;
}
```

# Use case 2: An http client from a dependency requires parsing DTOs composed of internal and other dependencies DTOs

```java
package com.xxxxx.tools.client.act.dto;
 
import com.xxxx.datamodel.Purpose;
import com.xxxx.datamodel.Targeting;
import io.micronaut.serde.annotation.Serdeable;
import java.util.Set;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
 
@NoArgsConstructor
@Serdeable
@Getter
@Setter
// Used for tests
@EqualsAndHashCode
@ToString
public final class RemoteActionDto {
  private String id;
  private String uuid;
  private String name;
  private String description;
 
  private Set<Purpose> purpose;
  private Targeting targeting;
  private ScriptInfoDto scriptInfo;
...
```
Purpose and Targeting classes both come from a dependency of the library defining the HTTP client.
```java
package com.xxxxxx.tools.client.act.dto;
 
import com.xxxx.datamodel.Input;
import com.xxxx.datamodel.Output;
import java.util.Collections;
import java.util.List;
import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;
 
@Jacksonized
@Builder
@Value
public class ScriptInfoDto {
  String runAs;
  int timeoutSeconds;
  boolean hasScriptWindows;
  boolean hasScriptMacOs;
  @Builder.Default List<Input> inputs = Collections.emptyList();
  @Builder.Default List<Output> outputs = Collections.emptyList();
}
```
Same as for RemoteActionDto, Input, Output come from external dependencies of the library

In the microservice, the deserialization of RemoteActionDto fails with the following NullPoiinterException
```
Client 'act-api-client': Error decoding HTTP response body: Error decoding JSON stream for type [B]: Error decoding property [ScriptInfoDto scriptInfo] of type [class com.xxxxxx.tools.client.act.dto.RemoteActionDto]: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "this.deserializer" is null
io.micronaut.http.client.exceptions.HttpClientResponseException: Client 'act-api-client': Error decoding HTTP response body: Error decoding JSON stream for type [B]: Error decoding property [ScriptInfoDto scriptInfo] of type [class com.xxxxxxl.tools.client.act.dto.RemoteActionDto]: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "this.deserializer" is null
    at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeNormalBodyParseError(DefaultHttpClient.java:2293)
    at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2223)
    at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2179)
    at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2147)
...
Caused by: java.lang.NullPointerException: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "derProperty.deserializer" is null
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserializeValue(SpecificObjectDeserializer.java:300)
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer$ConstructorValuesDeserializer.tryConsume(SpecificObjectDeserializer.java:691)
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer$ArgsConstructorBeanDeserializer.tryConsume(SpecificObjectDeserializer.java:831)
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserialize(SpecificObjectDeserializer.java:105)
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserialize(SpecificObjectDeserializer.java:73)
    at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserializeNullable(SpecificObjectDeserializer.java:239)
```

# Use case 3: custom jackson serializers need to be rewritten using the Micronaut 4 custom serializer
@JsonSerialize using member is not supported yet. So there is no other way than rewrite the serializer

# Use case 4: Blocking calls are detected in the event loop and crashes the request
This exception message is thrown by one of our clients that doesn't return reactive constructs

```
"You are trying to run a BlockingHttpClient operation on a netty event loop thread. This is a common cause for bugs: Event loops should never be blocked. You can either mark your controller as @ExecuteOn(TaskExecutors.BLOCKING), or use the reactive HTTP client to resolve this bug. There is also a configuration option to disable this check if you are certain a blocking operation is fine here."

```

### Actual Behaviour

# Use case 1: A project dependency has a DTO that requires arbitrary parsing

Solution: add a mixin
```java
@Serdeable.Deserializable(using = TokenizerResponseDeserializer.class)
public interface TokenizerResponseDeserializationMixin {}
```
```java
package com.xxxxxx.content.manager.externals.datamodel.api.deserialization;
 
import com.xxxxxx.querybuilder.TokenizerResponse;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.type.Argument;
import io.micronaut.serde.Decoder;
import io.micronaut.serde.Deserializer;
import jakarta.inject.Singleton;
import java.io.IOException;
import java.util.List;
import lombok.AllArgsConstructor;
 
@Singleton
@AllArgsConstructor
public class TokenizerResponseDeserializer implements Deserializer<TokenizerResponse> {
 
  @Override
  public @Nullable TokenizerResponse deserialize(
      @NonNull Decoder decoder,
      @NonNull DecoderContext context,
      @NonNull Argument<? super TokenizerResponse> type)
      throws IOException {
    var tokens = new TokenizerResponse();
    var rootObjectDecoder = decoder.decodeObject();
    var key = rootObjectDecoder.decodeKey();
    if ("parseTree".equals(key)) {
      tokens.parseTree = parseParseTree(rootObjectDecoder);
    }
    rootObjectDecoder.close();
    return tokens;
  }
 
  private List<Object> parseParseTree(Decoder rootObjectDecoder) throws IOException {
    var result = rootObjectDecoder.decodeArbitrary();
    if (result instanceof List asList) {
      return asList;
    }
    throw new IOException("whatever");
  }
}
```

# Use case 2: An http client from a dependency requires parsing DTOs composed of internal and other dependencies DTOs

**Solution/workaround**
Micronaut doesn't seem to support @SerdeImport on classes which are already @Introspected (maybe the introspection companion objects are not compatible ?). To circumvent that we redefined com.xxxxx.datamodel.Output and com.xxxxx.datamodel.Input locally as @Serdeable objects. Which was not bad since we were already cherry-picking dependencies from the com.xxxxx.* package to build our own dtos

# Use case 3: custom jackson serializers need to be rewritten using the Micronaut 4 custom serializer

**Solution**
Just rewrite the custom serializers. The API from Micronaut is quite similar to the Jackson API therefore the rewrite is straightforward

# Use case 4: Blocking calls are detected in the event loop and crashes the request

**Solution**
Apply https://docs.micronaut.io/latest/guide/index.html#atBlocking

### Environment Information

- JDK 21

### Version

4.3.7

**Comment by sdelamo** [comment]
can you split this issue into multiple issues? it seems you have 4 different problems.

**Comment by alvarosanchez** [comment]
This should probably be a discussion instead. As far as I can tell, only use case 2 is an actual issue

**Comment by sdelamo** [comment]
@marcosflobo if you want to create [discussions](https://github.com/micronaut-projects/micronaut-core/discussions), create them separate as well.

**Comment by marcosflobo** [comment]
Hello team! I issue 2 I´ve put it in a separate issue https://github.com/micronaut-projects/micronaut-serialization/issues/844

The rest, I will move them to the discussions panel.

Thanks!

**Comment by marcosflobo** [comment]
And here the discussion https://github.com/micronaut-projects/micronaut-core/discussions/10822

Thanks folks!
