### ISSUE TITLE
NettyHttpClient fails in tests with MockBean(HttpClient.class) due to casting error

### ISSUE THREAD

**Issue by ChaimaaeROUAI** [micronaut-projects/micronaut-core#10837]
### Expected Behavior

The test should successfully mock the HttpClient without causing a casting exception.

### Actual Behaviour

test fails with the following exception 
```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider]

Message: class mushop.orders.services.$OrderServiceTest$HttpClient2$Definition$Intercepted cannot be cast to class io.micronaut.http.client.netty.DefaultHttpClient (mushop.orders.services.$OrderServiceTest$HttpClient2$Definition$Intercepted and io.micronaut.http.client.netty.DefaultHttpClient are in unnamed module of loader 'app')
Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration) --> DatasourceFactory.dataSource([DatasourceConfiguration datasourceConfiguration]) --> new HikariPoolConfigurationListener([OracleWalletArchiveProvider walletArchiveProvider],BeanLocator beanLocator) --> new OracleWalletArchiveProvider([Database databaseClient])
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
	at app//io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
	at app//io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
	at app//io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
	at app//io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
	at app//io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:502)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:341)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at java.base@21.0.2/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider]

```

### Steps To Reproduce

Set up the test 
```
@MockBean(HttpClient.class)
HttpClient httpClient() {
    return mock(HttpClient.class);
}
```
Constructor
```
public OrdersService(CustomerOrderRepository customerOrderRepository,
                     MeterRegistry meterRegistry,
                     OrdersPublisher ordersPublisher,
                     PaymentClient paymentClient,
                     OrdersConfiguration ordersConfiguration,
                     @Client("users") HttpClient userClient,
                     @Client("carts") HttpClient cartsClient) {
    this.customerOrderRepository = customerOrderRepository;
    this.meterRegistry = meterRegistry;
    this.ordersPublisher = ordersPublisher;
    this.paymentClient = paymentClient;
    this.ordersConfiguration = ordersConfiguration;
    this.userClient = userClient;
    this.cartsClient = cartsClient;
}

```

It appears that the changes in the latest version require a specific implementation of HttpClient (DefaultHttpClient) which conflicts with the mocked version.

### Environment Information

Operating System: windows 11
JDK : 21 GraalVM 

### Version

Micronaut 4.3.4

**Comment by yawkat** [comment]
When did this work? micronaut-oraclecloud-httpclient-netty has always required DefaultHttpClient. Maybe in the past you didn't use micronaut-oraclecloud-httpclient-netty?
