### ISSUE TITLE
@Parameter is not recognized unless same variable identifier is used in POST request

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-core#1083]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. `@Validated` controller with base URI, like `@Controller(value = "/api/issues")`
1. `@Post` request that "processes" JSON with path variable
1. Pass two parameters: one `String` (for the path variable) and a POJO; name `String` one as `id`
1. Annotate the `String` variable with `@Parameter("something-id")` and the POJO with `@Body @Valid`

### Expected Behaviour

The request should succeed and the parameter `id` should be mapped/recognized by `@Parameter("something-id")`. Curiously, this is working fine on another controller that I have in the same application, but on a `GET` operation.

Tell us what should happen

See: `Expected Behaviour`.

### Actual Behaviour

```shell
01-05-2019 23:41:05.067 |- TRACE in DefaultHttpClient:1907 [nioEventLoopGroup-1-3] - ----

io.micronaut.http.client.exceptions.HttpClientResponseException: io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [String id] not specified

	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1760)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1701)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:189)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: `Linux uplink 4.19.13-1-lts #1 SMP Sun Dec 30 07:38:47 CET 2018 x86_64 GNU/Linux`
- **Micronaut Version:** `io.micronaut:micronaut-bom:1.0.2`
- **JDK Version:** `Java(TM) SE Runtime Environment (build 1.8.0_191-b12)`

### Example Application

`https://github.com/x80486/kotlin-micronaut/` – no link :rofl:

**Comment by graemerocher** [comment]
`@Parameter` is used for DI.. maybe you should be using `@QueryValue`?

**Comment by x80486** [comment]
I've tried with `@QueryValue` also...exactly the same result :sob::

```shell
01-06-2019 12:12:17.003 |- DEBUG in DefaultHttpClient:1534 [nioEventLoopGroup-1-3] - Sending HTTP Request: POST /api/issues/13f36c4e-c525-4d76-9831-b768c00345d2/comments
01-06-2019 12:12:17.004 |- DEBUG in DefaultHttpClient:1535 [nioEventLoopGroup-1-3] - Chosen Server: localhost(9080)
01-06-2019 12:12:17.005 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - Accept: application/json
01-06-2019 12:12:17.005 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - Content-Type: application/json
01-06-2019 12:12:17.005 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - host: localhost:9080
01-06-2019 12:12:17.005 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - connection: close
01-06-2019 12:12:17.005 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - content-length: 41
01-06-2019 12:12:17.006 |- TRACE in DefaultHttpClient:1904 [nioEventLoopGroup-1-3] - Request Body
01-06-2019 12:12:17.006 |- TRACE in DefaultHttpClient:1905 [nioEventLoopGroup-1-3] - ----
01-06-2019 12:12:17.006 |- TRACE in DefaultHttpClient:1906 [nioEventLoopGroup-1-3] - {"text":"comment-controller-micronautfw"}
01-06-2019 12:12:17.006 |- TRACE in DefaultHttpClient:1907 [nioEventLoopGroup-1-3] - ----
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1712 [nioEventLoopGroup-1-3] - HTTP Client Response Received for Request: POST http://localhost:9080/api/issues/13f36c4e-c525-4d76-9831-b768c00345d2/comments
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1713 [nioEventLoopGroup-1-3] - Status Code: 500 Internal Server Error
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - Date: Sun, 6 Jan 2019 12:12:17 GMT
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - content-type: application/json
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - content-length: 257
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1925 [nioEventLoopGroup-1-3] - connection: close
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1904 [nioEventLoopGroup-1-3] - Response Body
01-06-2019 12:12:17.097 |- TRACE in DefaultHttpClient:1905 [nioEventLoopGroup-1-3] - ----
01-06-2019 12:12:17.098 |- TRACE in DefaultHttpClient:1906 [nioEventLoopGroup-1-3] - {"timestamp":1546794737069,"status":500,"error":"Internal Server Error","message":"io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [String id] not specified","path":"/api/issues/13f36c4e-c525-4d76-9831-b768c00345d2/comments"}
01-06-2019 12:12:17.098 |- TRACE in DefaultHttpClient:1907 [nioEventLoopGroup-1-3] - ----

io.micronaut.http.client.exceptions.HttpClientResponseException: io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [String id] not specified
...
```

I updated the project to use `@QueryValue` in `CommentController.kt`; I left `IssueController.kt` using `@Parameter` just to compare those, but I do understand what you said: in both cases what's correct is to use `@QueryValue` – which I didn't know :laughing: ...so thanks for the tip!

**Comment by graemerocher** [comment]
The new `@PathVariable` annotation can be used to handle this case https://github.com/micronaut-projects/micronaut-core/commit/b0a6be7ed69b75fede1e3ce5c82aa9cdc6d08861
