### ISSUE TITLE
"Multiple possible bean candidates found" error in IntelliJ

### ISSUE THREAD

**Issue by opaquot** [micronaut-projects/micronaut-core#10847]
### Expected Behavior

The Micronaut service starts properly.

### Actual Behaviour

At the startup of several of my Micronaut services, I get the error message: "Message: Multiple possible bean candidates found: [Serde<Object>, Serde<Object[]>, ObjectArraySerde]". This only happens in IntelliJ but not if I start my service in command line after building it.

The full stack trace:
```
15:21:09.798 [main] INFO  i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment - Established active environments: [dev]
15:21:10.376 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [objectArraySerde] of class: io.micronaut.serde.support.DefaultSerdeRegistry

Message: Multiple possible bean candidates found: [Serde<Object>, Serde<Object[]>, ObjectArraySerde]
Path Taken: new NettyJsonHandler(JsonMapper jsonMapper) --> new NettyJsonHandler([JsonMapper jsonMapper]) --> new JacksonJsonMapper([SerdeRegistry registry],SerdeConfiguration serdeConfiguration,SerdeJacksonConfiguration jacksonConfiguration) --> new DefaultSerdeRegistry(BeanContext beanContext,ObjectSerializer objectSerializer,ObjectDeserializer objectDeserializer,[Serde objectArraySerde],SerdeIntrospections introspections,ConversionService conversionService,SerdeConfiguration serdeConfiguration,SerializationConfiguration serializationConfiguration,DeserializationConfiguration deserializationConfiguration)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [objectArraySerde] of class: io.micronaut.serde.support.DefaultSerdeRegistry

Message: Multiple possible bean candidates found: [Serde<Object>, Serde<Object[]>, ObjectArraySerde]
Path Taken: new NettyJsonHandler(JsonMapper jsonMapper) --> new NettyJsonHandler([JsonMapper jsonMapper]) --> new JacksonJsonMapper([SerdeRegistry registry],SerdeConfiguration serdeConfiguration,SerdeJacksonConfiguration jacksonConfiguration) --> new DefaultSerdeRegistry(BeanContext beanContext,ObjectSerializer objectSerializer,ObjectDeserializer objectDeserializer,[Serde objectArraySerde],SerdeIntrospections introspections,ConversionService conversionService,SerdeConfiguration serdeConfiguration,SerializationConfiguration serializationConfiguration,DeserializationConfiguration deserializationConfiguration)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2181)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.serde.support.$DefaultSerdeRegistry$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.serde.jackson.$JacksonJsonMapper$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.http.netty.body.$NettyJsonHandler$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2951)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1716)
	at io.micronaut.http.body.DefaultMessageBodyHandlerRegistry.findWriterImpl(DefaultMessageBodyHandlerRegistry.java:143)
	at io.micronaut.http.body.RawMessageBodyHandlerRegistry.findWriter(RawMessageBodyHandlerRegistry.java:123)
	at io.micronaut.http.body.DefaultMessageBodyHandlerRegistry.findWriter(DefaultMessageBodyHandlerRegistry.java:51)
	at io.micronaut.web.router.DefaultRouteInfo.<init>(DefaultRouteInfo.java:94)
	at io.micronaut.web.router.DefaultMethodBasedRouteInfo.<init>(DefaultMethodBasedRouteInfo.java:75)
	at io.micronaut.web.router.DefaultRequestMatcher.<init>(DefaultRequestMatcher.java:51)
	at io.micronaut.web.router.DefaultUrlRouteInfo.<init>(DefaultUrlRouteInfo.java:71)
	at io.micronaut.web.router.DefaultRouteBuilder$DefaultUriRoute.toRouteInfo(DefaultRouteBuilder.java:880)
	at io.micronaut.web.router.DefaultRouter.<init>(DefaultRouter.java:116)
	at io.micronaut.web.router.$DefaultRouter$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.http.server.$RouteExecutor$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.http.server.netty.$DefaultNettyEmbeddedServerFactory$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1732)
	at io.micronaut.http.server.netty.$DefaultNettyEmbeddedServerFactory$BuildDefaultServer0$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1813)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1788)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:872)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:346)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:74)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:301)

```

### Steps To Reproduce

1. In IntelliJ
2. Start a Micronaut service
3. I get an error "Message: Multiple possible bean candidates found: [Serde<Object>, Serde<Object[]>, ObjectArraySerde]"
4. It doesn't appear when lauching in command line.

### Environment Information

- OS: Linux
- IntelliJ versions: 2023.3.6 and 2024.1.1
- Plugins:
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.22"
    id("org.jetbrains.kotlin.kapt") version "1.9.22"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.3.4"
    id("io.micronaut.test-resources") version "4.3.4"
    id("com.google.cloud.tools.jib") version "3.4.0"
    id("io.micronaut.aot") version "4.3.4"
    id("org.sonarqube") version "4.3.1.3277"
    id("jacoco")
}
```
- Dependencies:
```
dependencies {
    implementation("com.entreprise.core.package:business-logic:0.0.25-SNAPSHOT")
    implementation("com.entreprise.core.package:adapters:0.0.25-SNAPSHOT")

    kapt("io.micronaut:micronaut-http-validation")
    kapt("io.micronaut.openapi:micronaut-openapi")
    kapt("io.micronaut.serde:micronaut-serde-processor")
    kapt("io.micronaut.validation:micronaut-validation-processor")
    kapt("io.micronaut.data:micronaut-data-document-processor")

    implementation("io.micrometer:context-propagation")
    implementation("io.micronaut.kotlin:micronaut-kotlin-extension-functions")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("io.micronaut.data:micronaut-data-mongodb")
    implementation("org.springframework:spring-core:6.1.3")
    implementation("jakarta.validation:jakarta.validation-api")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
    implementation("com.eventstore:db-client-java:4.3.0")
    implementation("io.micronaut:micronaut-management")

    compileOnly("io.micronaut:micronaut-http-client")
    compileOnly("io.micronaut.openapi:micronaut-openapi-annotations")

    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("org.yaml:snakeyaml")
    runtimeOnly("org.mongodb:mongodb-driver-reactivestreams")

    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("io.micronaut:micronaut-http-client")
    testImplementation("org.hamcrest:hamcrest")
    testImplementation("io.mockk:mockk")
    testImplementation("io.micronaut.testresources:micronaut-test-resources-extensions-junit-platform")
}
```

### Version

4.3.4

**Comment by opaquot** [comment]
I believe I have found a solution to my problem. In the run configuration, if I remove the option "Add dependencies with "provided" scope to classpath", then the service starts:
![image](https://github.com/micronaut-projects/micronaut-core/assets/26593818/797c54d8-39b7-475c-801c-e502e50ac962)
