### ISSUE TITLE
Declarative client unable to understand/parse empty HTTP Not Found

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-core#1090]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller with a method returning an `<HttpResponse<SomeType>`
1. Conditionally return (in the same method) an HTTP `OK` / `NOT FOUND`
1. Create a _declarative_ HTTP client to test both scenarios

### Stacktrace

```shell
05-14-2019 08:42:03.455 |- DEBUG in DefaultHttpClient:1551 [nioEventLoopGroup-1-12] - Sending HTTP Request: GET /api/issues/ac88422a-7807-4169-a7f6-61fde9e813ea
05-14-2019 08:42:03.455 |- DEBUG in DefaultHttpClient:1552 [nioEventLoopGroup-1-12] - Chosen Server: localhost(22665)
05-14-2019 08:42:03.456 |- TRACE in DefaultHttpClient:1959 [nioEventLoopGroup-1-12] - Accept: application/json
05-14-2019 08:42:03.456 |- TRACE in DefaultHttpClient:1959 [nioEventLoopGroup-1-12] - host: localhost:22665
05-14-2019 08:42:03.456 |- TRACE in DefaultHttpClient:1959 [nioEventLoopGroup-1-12] - connection: close
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1735 [nioEventLoopGroup-1-12] - HTTP Client Response Received for Request: GET http://localhost:22665/api/issues/ac88422a-7807-4169-a7f6-61fde9e813ea
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1736 [nioEventLoopGroup-1-12] - Status Code: 404 Not Found
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1959 [nioEventLoopGroup-1-12] - Date: Tue, 14 May 2019 12:42:03 GMT
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1959 [nioEventLoopGroup-1-12] - connection: close
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1938 [nioEventLoopGroup-1-12] - Response Body
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1939 [nioEventLoopGroup-1-12] - ----
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1940 [nioEventLoopGroup-1-12] - 
05-14-2019 08:42:03.461 |- TRACE in DefaultHttpClient:1941 [nioEventLoopGroup-1-12] - ----
05-14-2019 08:42:03.462 |- TRACE in DefaultHttpClient:216 [nioEventLoopGroup-1-12] - Full HTTP response received an empty body
05-14-2019 08:42:03.462 |- TRACE in DefaultHttpClient:199 [nioEventLoopGroup-1-12] - Unable to convert response body to target type class java.lang.String
05-14-2019 08:42:03.464 |- ERROR in RecoveryInterceptor:205 [main] - Type [io.shido.http.IssueControllerTest$HttpClient$Intercepted] executed with error: Not Found
io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1771)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1723)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found

	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1771)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1723)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected Behaviour

Tests should succeed without any exception(s) being thrown – in the same way it happens when the application is running.

### Actual Behaviour

When using the HTTP client and an HTTP `Not Found` is sent back, it fails with:

```shell
01-06-2019 15:15:15.577 |- TRACE in DefaultHttpClient:190 [nioEventLoopGroup-1-3] - Unable to convert response body to target type class java.lang.String
01-06-2019 15:15:15.579 |- ERROR in RecoveryInterceptor:206 [main] - Type [io.shido.http.IssueControllerTest$HttpClient$Intercepted] executed with error: Not Found
io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found
    at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1748)
    at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1701)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    ...
```

StackOverflow Question: https://stackoverflow.com/questions/54065647/sending-back-an-httpresponse-notfound-results-in-exception-httpclientresponsee/

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** `1.0.3` (also happens with `1.0.2`)
- **JDK Version:** OpenJDK `1.8` or OpenJDK `11`

### Example Application

https://github.com/x80486/kotlin-micronaut/

> Relevant pieces: `IssueController` and `IssueControllerTest`

**Comment by EmmanuelDemey** [comment]
I have the same problem during my first dev with Micronaut. 
Any solutions ?

**Comment by x80486** [comment]
Hello folks! I just gave it another whirl to this one with version `1.1.1` and the issue is still there.

Is there any feedback? I provided everything you ask for...it should be a matter of running that test to get the result(s) back.

**Comment by jameskleeh** [comment]
This would also happen for clients that return void

**Comment by jameskleeh** [comment]
Thanks for the report!
