### ISSUE TITLE
JDBC + DBCP2 configuration

### ISSUE THREAD

**Issue by jacaetevha** [micronaut-projects/micronaut-core#1109]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. download or clone [the repo](https://github.com/jacaetevha/micronaut-jdbc-commons-dbcp2-configuration-failure)
2. cd /path/to/repo
3. ./gradlew -t run

### Expected Behaviour

Neither `BeanContext.run().getBean(DataSource.class)` nor `BeanContext.run().getBean(DatabaseBean.class)` should fail to instantiate a `javax.sql.DataSource`

### Actual Behaviour

Exceptions are thrown when attempting to instantiate a `javax.sql.DataSource`:

```shell
$> ./gradlew -t run
Continuous build is an incubating feature.

> Task :compileJava
Note: Creating bean classes for 1 type elements

> Task :run
11:59:13.609 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1537ms. Server Running: http://localhost:8080
11:59:13.613 [main] INFO  test.app.Application -
**************************************************
  BeanContext.run().getBean(DatabaseBean.class)
**************************************************
11:59:13.628 [main] ERROR test.app.Application - error getting DatabaseBean: {}
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dataSource] of class: test.app.DatabaseBean

Path Taken: new DatabaseBean([DataSource dataSource])
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
        at test.app.$DatabaseBeanDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:512)
        at test.app.Application.main(Application.java:17)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [test.app.DatabaseBean]

Message: Missing bean arguments for type: io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration. Requires arguments: String name
Path Taken: new DatabaseBean([DataSource dataSource])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1304)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:896)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
        ... 7 common frames omitted
11:59:13.628 [main] INFO  test.app.Application -
**************************************************
  BeanContext.run().getBean(DataSource.class)
**************************************************
11:59:13.639 [main] ERROR test.app.Application - error getting DataSource: {}
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration]

Message: Missing bean arguments for type: io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration. Requires arguments: String name

        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1304)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:512)
        at test.app.Application.main(Application.java:25)
```

### Environment Information

- **Operating System**: Mac OS/X Mojave (10.14)
- **Micronaut Version:** 1.0.2
- **JDK Version:** 1.8.0_152

### Example Application

- https://github.com/jacaetevha/micronaut-jdbc-commons-dbcp2-configuration-failure

**Comment by jacaetevha** [comment]
Thanks @graemerocher, that was definitely the issue. RE: not doing this in `main`, I know. It was just a quick'n'dirty example.
