### ISSUE TITLE
ArgumentInjectionPoint not working anymore in version 4.5

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-core#11198]
### Expected Behavior

We can inject `@PulsarReader` in a constructor

### Actual Behaviour

We got the error
>Message: Outer injection point inaccessible from here
Path Taken: MessageBrokerIntegrationTest.pulsarConsumer --> new MessageBrokerIntegrationTest$PulsarMessageConsumer$Intercepted([Reader reader],BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.frogdevelopment.pulsar.MessageBrokerIntegrationTest$PulsarMessageConsumer$Intercepted]

### Steps To Reproduce

1. Clone the demo repository https://github.com/FrogDevelopper/micronaut-4_5
2. switch to [example/pulsar](https://github.com/FrogDevelopper/micronaut-4_5/tree/example/pulsar) branch
3. Check that [gradle.properties#micronautVersion](https://github.com/FrogDevelopper/micronaut-4_5/blob/example/pulsar/gradle.properties) is **4.4.3** (= micronaut-inject:4.4.10)
4. Run test in [MessageBrokerIntegrationTest.java](https://github.com/FrogDevelopper/micronaut-4_5/blob/example/pulsar/src/test/java/com/frogdevelopment/pulsar/MessageBrokerIntegrationTest.java) (start [pulsar service](https://github.com/FrogDevelopper/micronaut-4_5/blob/example/pulsar/docker-compose.yaml) before)=> test pass ✅ 
5. Upgrate [gradle.properties#micronautVersion](https://github.com/FrogDevelopper/micronaut-4_5/blob/example/pulsar/gradle.properties) to **4.5.1** (= micronaut-inject:4.5.4)
6. Run test in [MessageBrokerIntegrationTest.java](https://github.com/FrogDevelopper/micronaut-4_5/blob/example/pulsar/src/test/java/com/frogdevelopment/pulsar/MessageBrokerIntegrationTest.java) => test fail ❌ with error
>Message: Outer injection point inaccessible from here
Path Taken: MessageBrokerIntegrationTest.pulsarConsumer --> new MessageBrokerIntegrationTest$PulsarMessageConsumer$Intercepted([Reader reader],BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2343)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:3010)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1350)
	at com.frogdevelopment.pulsar.$MessageBrokerIntegrationTest$PulsarMessageConsumer$Intercepted$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2328)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3022)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2983)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1694)
	at com.frogdevelopment.pulsar.$MessageBrokerIntegrationTest$Definition.inject(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doInjectAndInitialize(DefaultBeanContext.java:2655)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:1012)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:459)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeEach(MicronautJunit5Extension.java:223)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.UnsupportedOperationException: Outer injection point inaccessible from here
	at io.micronaut.context.AbstractBeanResolutionContext$ConstructorArgumentSegment.getOuterInjectionPoint(AbstractBeanResolutionContext.java:504)
	at io.micronaut.pulsar.PulsarReaderFactory.getReaderByInjectionPoint(PulsarReaderFactory.java:115)
	at io.micronaut.pulsar.PulsarReaderFactory.getReaderByInjectionPoint(PulsarReaderFactory.java:90)
	at io.micronaut.pulsar.$PulsarReaderFactory$GetReaderByInjectionPoint0$Definition.doInstantiate(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.instantiate(AbstractInitializableBeanDefinition.java:770)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2326) 

### Environment Information

- JDK version: 21

### Example Application

https://github.com/FrogDevelopper/micronaut-4_5

### Version

4.5.1

**Comment by dstepanov** [comment]
It works fine with 4.6.1
