### ISSUE TITLE
mn CLI tool generates unbuildable project

### ISSUE THREAD

**Issue by nedelva** [micronaut-projects/micronaut-core#11212]
### Expected Behavior

MN should generate a buildable project (no matter the combination of features chosen)

### Actual Behaviour

When you generate a Lambda application with the following comand:

> mn create-function-app --build=maven --jdk=21 --lang=java --test=junit --features=aws-lambda,yaml,http-client,jackson-databind,email-mailjet,security-jwt com.example.lambdademo

The `mvn verify` fails with
> [INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.FunctionRequestHandlerTest
10:45:02.112 [main] INFO  i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment - Established active environments: [function, lambda]
10:45:02.164 [main] ERROR i.m.f.aws.MicronautRequestHandler - Exception initializing handler
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.security.endpoints.$LoginController$Definition$Intercepted] could not be loaded: Failed to initialize the bean [class io.micronaut.security.endpoints.$LoginController$Definition$Intercepted]: io/micronaut/http/server/util/HttpHostResolver
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1983)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:307)
	at io.micronaut.context.DefaultBeanContext.configureAndStartContext(DefaultBeanContext.java:3314)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:345)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:215)
	at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:123)
	at io.micronaut.function.aws.MicronautRequestHandler.buildApplicationContext(MicronautRequestHandler.java:140)
	at io.micronaut.function.aws.MicronautRequestHandler.<init>(MicronautRequestHandler.java:67)
	at com.example.FunctionRequestHandler.<init>(FunctionRequestHandler.java:10)
	at com.example.FunctionRequestHandlerTest.setupServer(FunctionRequestHandlerTest.java:16)

### Environment Information

- macOS
- JDK 21 Temurin

### Version

4.6.2

**Comment by nedelva** [comment]
**UPDATE**: The issue does not occur on version 4.7.5
