### ISSUE TITLE
Context Path Missing in Swagger YAML (Micronaut 4.6.2)

### ISSUE THREAD

**Issue by tabhus** [micronaut-projects/micronaut-core#11233]
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/11228

Micronaut version 4.6.2 appears to have a regression in Swagger documentation generation. The context path defined in application.properties using micronaut.server.context-path is not being included in the generated Swagger YAML file. This behavior differs from version 4.5.1, where the context path was correctly added to endpoint URLs.

Steps to Reproduce:

1. Create a Micronaut application with version 4.6.2 and the Micronaut OpenAPI extension.
2. Set the context path in application.properties:

micronaut.server.context-path=/myservice

3. Define a controller with a Swagger annotation and an endpoint:
Java
@Controller
public class MyController {

  @Operation(... (your Swagger annotations) ...)
  @Get(uri = "/hello/{title}")
  public Responses myEndpoint(String parameter) {
    // ...
  }
}

4. Build the application.

Examine the generated Swagger YAML file.

**Expected Behavior:**

The generated Swagger YAML should include the context path in endpoint URLs. For example, the endpoint _/hello/{title}_ should be represented as **/myservice/hello/{title}** in the YAML.

Actual Behavior:

The context path is missing from endpoint URLs in the Swagger YAML. The endpoint appears as simply /hello/{title}.

**Comment by tabhus** [comment]
When calling the /hello endpoint after service startup, the application logs a io.micronaut.http.server.exceptions.NotFoundException at the end of execution. 

io.micronaut.http.server.exceptions.NotFoundException: Page Not Found
	at io.micronaut.http.server.RequestLifecycle.onRouteMiss(RequestLifecycle.java:525)
	at io.micronaut.http.server.RequestLifecycle$2.provideResponse(RequestLifecycle.java:380)
	at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:245)
	at io.micronaut.http.server.RequestLifecycle.runServerFilters(RequestLifecycle.java:422)
	at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:160)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:93)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:235)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:415)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	
It seems it is application is also encountering an additional issue related to a missing resource but the resource is executed fine when I call the /hello endpoint.

**Comment by altro3** [comment]
Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1775 Wait micronaut-openapi 6.13.0
