### ISSUE TITLE
NoSuchMethodError when Parameter is Generated Class

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#1123]
I am seeing a strange error. If I have a controller endpoint where one of the parameters is a generated class, the Definition class generated by Micronaut's annotation processor incorrectly skips the parameter as though there was no parameter at all.

For example:
```
@Controller("/email-drafts")
public class EmailDraftController {
	@Delete("/{draft}")
	public void delete(EmailDraft draft) {
		draft.delete();
	}
}
```
```
curl -X DELETE 'http://localhost/email-drafts/ZHJAZnSOvYifonFVn_OmM-hjZrY_22gYvsvLdvNatVE'
```
```
[nioEventLoopGroup-1-9] ERROR io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: com.vercettie.switchboard.email.messages.drafts.EmailDraftController.delete()V
java.lang.NoSuchMethodError: com.vercettie.switchboard.email.messages.drafts.EmailDraftController.delete()V
at com.vercettie.switchboard.email.messages.drafts.$EmailDraftControllerDefinition$$exec12.invokeInternal(Unknown Source)
at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2413)
at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237)
at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1284)
at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
at io.reactivex.Flowable.subscribe(Flowable.java:14479)
at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14479)
at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
at io.reactivex.Flowable.subscribe(Flowable.java:14479)
at io.reactivex.Flowable.subscribe(Flowable.java:14429)
at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:130)
at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
at io.reactivex.Flowable.subscribe(Flowable.java:14479)
at io.reactivex.Flowable.subscribe(Flowable.java:14426)
at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:69)
at java.lang.Thread.run(Thread.java:748)
```

I have played with the order of the `annotationProcessor` entries in my build.gradle, but it doesn't seem to have any effect.

- **Operating System**: Linux Ryan-Laptop 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Micronaut Version:** 1.0.3
- **JDK Version:** OpenJDK 1.8.0_191

**Comment by graemerocher** [comment]
Could you upload an example that reproduces the issue?

**Comment by RyanHoldren** [comment]
Thanks for looking into this, @graemerocher. Here is an example of what I am talking about:

[Example.zip](https://github.com/micronaut-projects/micronaut-core/files/2766472/Example.zip)

1. Unzip
2. `gradle :parent:server:run`
3. `curl localhost:8080/example`

**Comment by RyanHoldren** [comment]
Thanks for looking into this, @graemerocher. It definitely seems better to fail fast, but do you have any suggestions on how I would make the example work? It seems like Micronaut's annotation processor is executing _before_ the class is generated, but I don't see any way to postpone its execution until after the class is generated.

**Comment by graemerocher** [comment]
I do not know if it is possible to generate source code from an annotation processor that is then processed by another annotation processor

**Comment by RyanHoldren** [comment]
I believe that is possible, yes. I have successfully generated source code via an annotation processor that itself contained [Immutables](https://immutables.github.io/) annotations.

**Comment by RyanHoldren** [comment]
This issue can also occur in other places. In particular, it looks like `GenericUtils` should be modified so that all the `switch`'es on `TypeKind` throw an exception when the mirror is of type `ERROR`. At present, I am getting some very strange runtime errors instead.
