### ISSUE TITLE
NPE "io.micronaut.http.filter.FilterContext.response()" because "newFilterContext" is null

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#11341]
### Expected Behavior

App does not crash

### Actual Behaviour

App crashes with: 

```
09:55:59.419 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Cannot invoke "io.micronaut.http.filter.FilterContext.response()" because "newFilterContext" is null
java.lang.NullPointerException: Cannot invoke "io.micronaut.http.filter.FilterContext.response()" because "newFilterContext" is null
	at io.micronaut.http.filter.AroundLegacyFilter$FilterChainImpl.lambda$proceed$1(AroundLegacyFilter.java:124)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.micronaut.core.execution.ExecutionFlow.lambda$toCompletableFuture$2(ExecutionFlow.java:213)
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.onComplete(ImperativeExecutionFlowImpl.java:132)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl$OnComplete.apply(DelayedExecutionFlowImpl.java:330)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.work(DelayedExecutionFlowImpl.java:51)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete0(DelayedExecutionFlowImpl.java:64)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete(DelayedExecutionFlowImpl.java:70)
	at io.micronaut.http.netty.body.StreamingNettyByteBody$SharedBuffer.complete(StreamingNettyByteBody.java:557)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingInboundHandler.read(PipeliningServerHandler.java:542)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps To Reproduce

Clone `https://github.com/Micronaut-TODO/micronauttodo/tree/bug` branch `bug`. 

Run the app with `./gradlew run`

Attempt to login with bogus credentials. Try several times, it is a flaky error. You will see the above error. 

### Example Application

https://github.com/Micronaut-TODO/micronauttodo/tree/bug

### Version

4.7.0

**Comment by yawkat** [comment]
I tried many times and also in an infinite loop with curl, wasn't able to reproduce the issue

**Comment by sdelamo** [comment]
see a video showing the issue @yawkat Were you using the `bug` branch. Can you reproduce it?

https://github.com/user-attachments/assets/8c4f88e9-6aa3-45fb-8a4e-d88c64077fb3

if signup work, try to login and logout and you may see the error as well.

**Comment by vitezg** [comment]
Hello, might not be much, but I am encountering the same issue too with 4.8.3. Happens with POSTs. The application is way too big, and unfortunately I don't have much time to try to create a small reproducer. Also the bug is not consistent, sometimes it shows up, sometimes it does not.

**Comment by vitezg** [comment]
A bit more information, using multipart forms without CSRF protection seems to work around the issue. I'm still trying to turn on CSRF checking with multipart forms.

**Comment by yawkat** [comment]
Interesting, maybe there's something wrong with CSRFFilter

**Comment by vitezg** [comment]
Yes you are totally right, the issue is indeed with the CSRFFilter, and not with the form encoding. 

I have reverted to the version that does not use multipart forms, and have also disabled the csrf filter, by setting micronaut.security.csrf.filter.content-types to an empty array, and this works too, totally bugfree. 

A bit of background, I have a small application with 4 forms. Most of the forms only work with simple data, checkboxes, text input fields, and the controllers for these do not show an issue. However I have a form with a textarea, in which thymleaf templates can be edited, and only this shows the error. So I'm wandering if it's some parsing related issue inside the CSRFFilter.

**Comment by vitezg** [comment]
I tried to create a reproducer, however I'm too much of a newbie to Micronaut, and could not get a token with csrfTokenRepository.findCsrfToken(request) - probably logging in is missing. My original app uses google oauth, but I did not want to go with that, in order to have minimal code.

Do you maybe have small example somewhere? Or something I could start from?

**Comment by graemerocher** [comment]
Triage: this is the same CSRF-triggered `FilterContext.response()` NPE now tracked in open [micronaut-security#1984](https://github.com/micronaut-projects/micronaut-security/issues/1984), which includes the same stack-trace pattern, the supplied reproducer, and the finding that `CsrfFilter` is invoked twice. The security issue is the authoritative owner because the trigger is in `CsrfFilter`; closing this Core copy as a duplicate. Any generic filter-chain hardening can be handled as follow-up from that investigation.
