### ISSUE TITLE
ConcurrentModificationException in FullNettyClientHttpResponse::getBody

### ISSUE THREAD

**Issue by Virelion** [micronaut-projects/micronaut-core#11360]
### Expected Behavior

No ConcurrentModificationException happening 

### Actual Behaviour

I see stacktrace about `ConcurrentModificationException` coming from `FullNettyClientHttpResponse`.

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:191)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:157)
	// internal stacktrace
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

This seems like similar issue to https://github.com/micronaut-projects/micronaut-core/pull/3549 
that was fixed by https://github.com/micronaut-projects/micronaut-core/pull/3549/commits

### Environment Information

- Kotlin 1.8.10 
- JVM: 17.0.10 (Amazon.com Inc. 17.0.10+7-LTS)

### Version

3.9.5

**Comment by graemerocher** [comment]
can you upgrade to a newer version of Micronaut and confirm if the issue still exists?

**Comment by Virelion** [comment]
I reproduced the issue with Micronaut:4.7.0 and Kotlin:1.9.25

Here is the project:
[cme-micronaut-bug.zip](https://github.com/user-attachments/files/17832357/cme-micronaut-bug.zip)

please use ./gradlew test to launch the only test `showBug`.

If necessary please increase repeat number (now 1000) if it does not reproduce

**Comment by Virelion** [comment]
As a potential workaround using:
```kotlin
        synchronized(response) { response.getBody(String::class.java) }
```

**Comment by Virelion** [comment]
I checked on [cme-micronaut-bug.zip](https://github.com/user-attachments/files/17832357/cme-micronaut-bug.zip) test project with version 4.7.1 and bug does not reproduce anymore.
