### ISSUE TITLE
KSP type element symbol processing failure - "element is postponed to the next round!"

### ISSUE THREAD

**Issue by jdpgrailsdev** [micronaut-projects/micronaut-core#11382]
### Expected Behavior

Existing Micronaut-annotated entity data class should be processed by the Micronaut KSP symbol processor. 

### Actual Behaviour

After upgrading to the latest Micronaut release (4.7.1 with Micronaut Core 4.7.4 and Micronaut Data 4.10.4), a previously existing Kotlin-based, Micronaut Data annotated entity class fails KSP processing with the following stack trace during a clean build:

```
> Task :oss:airbyte-data:kspKotlin FAILED
e: [ksp] Originating element: UserInvitation
e: [ksp] /Users/jpearlin/Projects/airbyte/airbyte-platform-internal/oss/airbyte-data/src/main/java/io/airbyte/data/repositories/domain/UserInvitation.java:31: Original element: io.airbyte.data.repositories.domain.UserInvitation is postponed to the next round!
e: io.micronaut.inject.visitor.ElementPostponedToNextRoundException: Original element: io.airbyte.data.repositories.domain.UserInvitation is postponed to the next round!
        at io.micronaut.inject.beans.visitor.IntrospectedTypeElementVisitor.processBuilderDefinition(IntrospectedTypeElementVisitor.java:205)
        at io.micronaut.inject.beans.visitor.IntrospectedTypeElementVisitor.processIntrospected(IntrospectedTypeElementVisitor.java:165)
        at io.micronaut.inject.beans.visitor.IntrospectedTypeElementVisitor.visitClass(IntrospectedTypeElementVisitor.java:85)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitClassDeclaration(TypeElementSymbolProcessor.kt:266)
        at com.google.devtools.ksp.symbol.impl.java.KSClassDeclarationJavaImpl.accept(KSClassDeclarationJavaImpl.kt:170)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor.process(TypeElementSymbolProcessor.kt:130)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

[This class](https://github.com/airbytehq/airbyte-platform/blob/0be62b72122162cc24075d2894f42c7926cadb5b/airbyte-data/src/main/kotlin/io/airbyte/data/repositories/entities/UserInvitation.kt) was successfully processed with previous Micronaut releases. 

### Steps To Reproduce

1. Check out https://github.com/airbytehq/airbyte-platform/tree/main
2. Modify [`deps.toml`](https://github.com/airbytehq/airbyte-platform/blob/0be62b72122162cc24075d2894f42c7926cadb5b/deps.toml) to use Micronaut 4.7.1, micronaut-core 4.7.4 and micronaut-data 4.10.4
3. Run `./gradlew clean build`

### Example Application

https://github.com/airbytehq/airbyte-platform/

### Version

4.7.1

**Comment by graemerocher** [comment]
I'm confused why KSP is trying to compile Java code? Shouldn't it only handle Kotlin

**Comment by jdpgrailsdev** [comment]
> I'm confused why KSP is trying to compile Java code? Shouldn't it only handle Kotlin

@graemerocher It is trying to compile a Kotlin-based entity class:  https://github.com/airbytehq/airbyte-platform/blob/0be62b72122162cc24075d2894f42c7926cadb5b/airbyte-data/src/main/kotlin/io/airbyte/data/repositories/entities/UserInvitation.kt.  The repo contains both Java and Kotlin code.

**Comment by jdpgrailsdev** [comment]
@graemerocher Actually...on second pass, there appears to be another Java-based version of the class.  That must be the root cause here.  I'll remove it and confirm.  Not sure why this wasn't an issue with previous releases.

**Comment by jdpgrailsdev** [comment]
That was it:  the class was converted to Kotlin but the Java duplicate of it was left behind.  Removing the Java version of the class fixed the issue.  It's worth noting that the two classes were in separate packages which is why it did not cause a compilation issue.  Previous releases must have tolerated this scenario with a Java and Kotlin class with the same name in different packages.  @graemerocher Sorry for the false alarm and thanks for the rubber ducking.  Closing.
