### ISSUE TITLE
HttpClient requires web metrics enabled after migrating from 4.6.2 to 4.7.0

### ISSUE THREAD

**Issue by pskowronek** [micronaut-projects/micronaut-core#11424]
### Expected Behavior

Bean using Micronaut HttpClient should not fail if web metrics are not enabled

### Actual Behaviour

HttpClient fails expecting web metrics to be enabled:

```

Caused by: io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: io.micronaut.configuration.metrics.binder.web.ClientMetricsFilter] method definition [void onRequest(HttpRequest
<Object B> request)]: Bean [class io.micronaut.configuration.metrics.binder.web.ClientMetricsFilter] is disabled since bean property [enabled] value is not equal to [true]
at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:98)

at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:98)
at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:44)
at io.micronaut.context.DefaultBeanContext.triggerBeanCreatedEventListener(DefaultBeanContext.java:2387)
at io.micronaut.context.DefaultBeanContext.postBeanCreated(DefaultBeanContext.java:2364)
at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2308)
at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2316)
at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3127)
at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3029)
at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2990)
at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2756)
at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1745)
at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188)
at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1350)
at io.micronaut.http.client.netty.$DefaultNettyHttpClientRegistry$Definition.instantiate(Unknown Source)
at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2334)

Caused by: io.micronaut.context.exceptions.DisabledBeanException: Bean [class io.micronaut.configuration.metrics.binder.web.ClientMetricsFilter] is disabled since bean property [enabled] value is not equal to [tr
ue]
"}
```

### Steps To Reproduce

1) Have an application that uses Micronaut HttpClient either injected or defined via annotation `@Client`
2) application.yml should contain:
```
  metrics:
    enabled: true
    binders:
      web:
        enabled: false <---
      jvm:
        enabled: true
```
3) On Micronaut 4.6.2 bean using HttpClient is properly initialized, whereas on 4.7.0 it fails (see actual behavior for stacktrace)

### Environment Information

- Docker, linux
- openjdk 17.0.12

### Version

4.7.0

**Comment by glorrian** [comment]
please provide example application to reproduce

**Comment by graemerocher** [comment]
Might be fixed in https://github.com/micronaut-projects/micronaut-micrometer/pull/882

**Comment by pskowronek** [comment]
> please provide example application to reproduce

Tried to build a minimalistic example, but I had no luck to reproduce the case until:

> Might be fixed in [micronaut-projects/micronaut-micrometer#882](https://github.com/micronaut-projects/micronaut-micrometer/pull/882)

This was the root cause. After bumping Micronaut version to 4.7.1 the problem disappeared.

Thank you all! I'm closing this issue.
