### ISSUE TITLE
Blocking Call in io.micronaut.http.client.netty.CancellableMonoSink

### ISSUE THREAD

**Issue by kgreulich** [micronaut-projects/micronaut-core#11456]
### Expected Behavior

No blocking Call in a Reactive Environment 

### Actual Behaviour

Blockhound finds blocking call while Running Tests:

```
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
    at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
    at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990)
    at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
    at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
    at io.micronaut.http.client.netty.CancellableMonoSink.tryEmitValue(CancellableMonoSink.java:91)
    at io.micronaut.http.client.netty.ConnectionManager$Pool$ConnectionHolder.emitPoolHandle(ConnectionManager.java:1360)
    at io.micronaut.http.client.netty.ConnectionManager$Pool$Http1ConnectionHolder.dispatch0(ConnectionManager.java:1519)
    at io.micronaut.http.client.netty.ConnectionManager$Pool$ConnectionHolder.lambda$dispatch$3(ConnectionManager.java:1388)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
import io.micronaut.http.client.BlockingHttpClient;
import io.micronaut.http.client.HttpClient;

@Inject
@Client("/v1/test-client-url")
private HttpClient httpClient;

private BlockingHttpClient blockingHttpClient;

@Test
void oneTest() {
  stubFor(post(urlEqualTo(TEST_URL)).willReturn(serviceUnavailable()));
  var requestJson = encodePubsubRequest(VALID_PUBSUB_REQUEST);
  var request = HttpRequest.POST("/", requestJson);

  HttpClientResponseException e = assertThrows(HttpClientResponseException.class, () -> blockingHttpClient.exchange(request));
  assertEquals(HttpStatus.BAD_GATEWAY, e.getStatus());
}
```

### Steps To Reproduce

1. Does not fail every run, only occasionally. 
2. I cannot figure out when this called.

application config

```micronaut:
  application:
    name: xxx
  netty:
    event-loops:
      default:
        num-threads: 3
        prefer-native-transport: true
  http:
    client:
      follow-redirects: true
      event-loop-group: default
      read-timeout: 10s
    services:
      one:
        urls:
          - "http://localhost:8081"
        pool:
          enabled: true
          max-connections: 50
        read-timeout: 10s
     two: # Otherwise identical HTTP Client with a longer read-timeout
        urls: ${micronaut.http.services.pi-api.urls}
        pool:
          enabled: ${micronaut.http.services.pi-api.pool.enabled}
          max-connections: ${micronaut.http.services.pi-api.pool.max-connections}
        read-timeout: 10s
  server:
    reactive: true
  otel:
    enabled: false

hbx:
  pubsub:
    dead-letter-topic: test-topic

logger:
  levels:
    io.micronaut:
      http.client: DEBUG
      reactor: DEBUG
      retry.intercept.RecoveryInterceptor: OFF
```

### Environment Information

- Micronaut: 4.7.0
- <jdk.version>17</jdk.version>
- micronaut-http-server-netty
- micronaut-http-client
- micronaut-reactor
- reactor-test
- blockhound-junit-platform: 1.0.10.RELEASE

### Version

4.7.0

**Comment by yawkat** [comment]
Probably fixed by #11288

**Comment by kgreulich** [comment]
This will be in 4.8.x then?

**Comment by graemerocher** [comment]
@yawkat can we add a test verifying it is fixed?

**Comment by yawkat** [comment]
I don't think it's feasible
