### ISSUE TITLE
Application with Consul doesn't start with Graal RC13

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1196]
I've found a different error when starting an native-image Micronaut application with Consul support.

- `git clone https://github.com/micronaut-graal-tests/micronaut-service-discovery-consul-http-client`
- `cd micronaut-service-discovery-consul-http-client`
- `git checkout graal-rc13`
- Use latest GraalRC13 build from master branch
- `./build-native-image.sh`
- The image is built without problems, but when executing it:

```
$ ./service-discovery
10:02:52.400 [main] ERROR i.m.h.server.netty.NettyHttpServer - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.discovery.consul.registration.ConsulAutoRegistration]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new ConsulAutoRegistration(Environment environment,[ConsulClient consulClient],HeartbeatConfiguration heartbeatConfiguration,ConsulConfiguration consulConfiguration,ServiceInstanceIdGenerator idGenerator)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.consul.registration.ConsulAutoRegistration]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new ConsulAutoRegistration(Environment environment,[ConsulClient consulClient],HeartbeatConfiguration heartbeatConfiguration,ConsulConfiguration consulConfiguration,ServiceInstanceIdGenerator idGenerator)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1333)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1901)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1622)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1602)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978)
	at io.micronaut.discovery.consul.registration.$ConsulAutoRegistrationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2237)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2142)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:516)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:918)
	at io.micronaut.http.server.netty.NettyHttpServer.lambda$bindServerToHost$2(NettyHttpServer.java:412)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:410)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:303)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:107)
	at io.micronaut.runtime.Micronaut.lambda$start$1(Micronaut.java:73)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:195)
	at io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted.<init>(Unknown Source)
	at io.micronaut.discovery.consul.client.v1.$AbstractConsulClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	... 22 common frames omitted
10:02:52.404 [main] ERROR i.m.h.server.netty.NettyHttpServer - Error stopping Micronaut server: Error instantiating bean of type  [io.micronaut.discovery.consul.registration.ConsulAutoRegistration]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new ConsulAutoRegistration(Environment environment,[ConsulClient consulClient],HeartbeatConfiguration heartbeatConfiguration,ConsulConfiguration consulConfiguration,ServiceInstanceIdGenerator idGenerator)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.consul.registration.ConsulAutoRegistration]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new ConsulAutoRegistration(Environment environment,[ConsulClient consulClient],HeartbeatConfiguration heartbeatConfiguration,ConsulConfiguration consulConfiguration,ServiceInstanceIdGenerator idGenerator)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1333)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1901)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1622)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1602)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978)
	at io.micronaut.discovery.consul.registration.$ConsulAutoRegistrationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2237)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2142)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:516)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:918)
	at io.micronaut.http.server.netty.NettyHttpServer.stopInternal(NettyHttpServer.java:454)
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:430)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:303)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:107)
	at io.micronaut.runtime.Micronaut.lambda$start$1(Micronaut.java:73)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:195)
	at io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted.<init>(Unknown Source)
	at io.micronaut.discovery.consul.client.v1.$AbstractConsulClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	... 21 common frames omitted
10:02:52.404 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Unable to start Micronaut server on port: 8080
io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8080
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:431)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:303)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:107)
	at io.micronaut.runtime.Micronaut.lambda$start$1(Micronaut.java:73)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at example.micronaut.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.consul.registration.ConsulAutoRegistration]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new ConsulAutoRegistration(Environment environment,[ConsulClient consulClient],HeartbeatConfiguration heartbeatConfiguration,ConsulConfiguration consulConfiguration,ServiceInstanceIdGenerator idGenerator)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1333)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1901)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1622)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1602)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978)
	at io.micronaut.discovery.consul.registration.$ConsulAutoRegistrationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2237)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2142)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:516)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:918)
	at io.micronaut.http.server.netty.NettyHttpServer.lambda$bindServerToHost$2(NettyHttpServer.java:412)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:410)
	... 8 common frames omitted
Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:195)
	at io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted.<init>(Unknown Source)
	at io.micronaut.discovery.consul.client.v1.$AbstractConsulClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	... 22 common frames omitted
```

**Comment by ilopmar** [comment]
With latest changes in Micronaut an Graal now it's possible to build the image. However the execution fails: https://github.com/micronaut-projects/micronaut-core/issues/1121
