### ISSUE TITLE
Mixed-case property names not found from properties file

### ISSUE THREAD

**Issue by gboersma** [micronaut-projects/micronaut-core#1217]
If a property name is mixed case, it is not found in the application.yml properties file, even though it is specified the same as in the code, e.g. `@Property(name="mixedCase")` does not match the property with the name "mixedCase". 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Specify a @Property or @Value referencing a property name with mixed case.
2. Specify the property in the application.yml file.

### Expected Behaviour

Property with that name should be pulled out of application.yml OR an error that the property name is not valid.

### Actual Behaviour

Cannot find property (e.g. {"message":"Internal Server Error: Failed to inject value for field [property] of class: property.name.issue.RootController\n\nMessage: Error resolving field value [propertyName]. Property doesn't exist or cannot be converted\nPath Taken: RootController.property"})

```
12:03:12.696 [pool-1-thread-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for field [property] of class: property.name.issue.RootController

Message: Error resolving field value [propertyName]. Property doesn't exist or cannot be converted
Path Taken: RootController.property
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [property] of class: property.name.issue.RootController

Message: Error resolving field value [propertyName]. Property doesn't exist or cannot be converted
Path Taken: RootController.property
	at io.micronaut.context.AbstractBeanDefinition.getValueForField(AbstractBeanDefinition.java:1185)
	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:717)
	at property.name.issue.$RootControllerDefinition.injectBean(Unknown Source)
	at property.name.issue.$RootControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:496)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2424)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2445)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1288)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14429)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version**: 1.0.4
- **JDK Version:** 1.8

### Example Application

https://github.com/gboersma/property-name-issue

**Comment by graemerocher** [comment]
This is currently by design, you should always use kebab case (lower case / hyphen separated) when referring to property names.

**Comment by gboersma** [comment]
I am fine with the convention, but it should be clearly documented and micronaut should warn me when I try to define a property that breaks the naming standard, rather than just telling me it can't find a property that I do have in the property file. That led to some head scratching, and I only figured it out by messing with it.

**Comment by graemerocher** [comment]
The behaviour is described in https://docs.micronaut.io/latest/guide/index.html#propertySource

See section "Property Value Binding" .. if you wish to improve that doc to make it more clear please do

**Comment by gboersma** [comment]
Will do. 

I read that to say that if I define a property name in my code as "mixedCase", it will match to a property defined in the property source as "mixed-case". This doesn't happen. If I have a reference "mixedCase" in the code, I get the "undefined property" if I have the property "mixed-case" defined in the application.yml.

I have updated my sample accordingly: https://github.com/gboersma/property-name-issue

**Comment by jameskleeh** [comment]
> read that to say that if I define a property name in my code as "mixedCase", it will match to a property defined in the property source as "mixed-case".

No, the opposite is true. The properties from property sources are normalized to kabab case. So a property in application.yml like `mixedCase` will be referenced in your application like `mixed-case`.

**Comment by jameskleeh** [comment]
@graemerocher Thoughts on logging a warning when a camel case property name is used?

**Comment by edalex-joe** [comment]
This bit me recently; if my understanding of the above is correct, Micronaut is forcing all property values to be kebab-case, and breaks with any that are camel case. That is heavy-handed to put it lightly, but at least emitting a warning would be good. Aside from that, it appears property value injection only works for constructors, not instance variables.

**Comment by jameskleeh** [comment]
@edalex-joe It definitely works for instance variables. Are you expecting the value to be set while inside the constructor? If so, then that is expected since the field is injected after construction

**Comment by edalex-joe** [comment]
Ah of course, that makes sense thanks James. Yes I was inside a constructor.

**Comment by graemerocher** [comment]
Following the above commit using incorrect casing in property placeholder references will result in a compilation error

**Comment by agentgt** [comment]
This hit me hard as I was hooking in our configuration framework with Micronaut (through the Environment).

I have hard time understanding why do all this kebab case resolution instead of just explicit resolution particularly:

 * Because Java is inherently camel case.
 * Spring allows camel case and just about every other java configuration framework.
 * Its very confusing to see a property name change names
 * Certain frameworks expect Class name configuration: Hystrix
 * Here is a typesafe config using spec to generate code: https://github.com/carueda/tscfg (camel cased).

In my experience the only time complicated property resolution has to happen is environment variables and that largely can be avoided by either not allowing it (ie environment variables are just locked to upper camel case) or by using special prefixes and then doing some resolution on that. Otherwise its doing something special about (".") which most folks are familiar with (e.g. TypeSafe Config path).

From the documentation:

> Micronaut still allows specifying the latter in configuration, but normalizes the properties into kebab case form to optimize memory consumption and reduce complexity when resolving properties. The following table summarizes how properties are normalized from different sources

I really have hard time buying this particularly after seeing #1714 .  

Its seems like you are really fighting what most Java developers expect and its seems overcomplicated for reasons that are not documented nor apparent.

**Comment by graemerocher** [comment]
It was a memory optimization, but you make some valid points. Please raise a feature request to allow storing both the normalized and non-normalized configuration for property sources that are not environment variables and we can see what we can do
