### ISSUE TITLE
Unclear Error Message

### ISSUE THREAD

**Issue by algotradersxyz** [micronaut-projects/micronaut-core#1236]
I believe Micronaut can revolutionize the Error Finding capabilities - Something that Spring/Boot seriously lacks. Stuck with the error below not sure what is causing it.

io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: null

io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryDefinition

Warm Regards,
Sudeep Batra

**Comment by graemerocher** [comment]
Please provide an example that reproduces the error

**Comment by maxx-ukoo** [comment]
@graemerocher 
I have issue with the same error.
I want to init app during startup, I updated scope from @Singleton to @Context. It lead to error:

> 21:23:34.153 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
21:23:34.508 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {[WORKING]}
21:23:34.509 [main] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
21:23:34.698 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator null
21:23:34.710 [main] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
21:23:34.955 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
21:23:35.577 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Hibernate: create table global (id bigint not null, platformType integer not null, primary key (id))
Hibernate: create table gpio (id bigint not null, address integer not null, mode integer not null, name varchar(255) not null, pullup integer not null, primary key (id))
Hibernate: create table mqtt (id bigint not null, host varchar(255) not null, port integer not null, publisherId varchar(255) not null, primary key (id))
Hibernate: alter table global drop constraint if exists UK_46dqy3ls5xqnodnmdxny5oe0o
Hibernate: alter table global add constraint UK_46dqy3ls5xqnodnmdxny5oe0o unique (platformType)
Hibernate: alter table gpio drop constraint if exists UK_o8jxho4qklqfewkv7r4hkhsex
Hibernate: alter table gpio add constraint UK_o8jxho4qklqfewkv7r4hkhsex unique (address)
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
21:23:36.395 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
21:23:36.530 [main] INFO  o.h.h.i.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory
Hibernate: select globalconf0_.id as id1_0_, globalconf0_.platformType as platform2_0_ from global globalconf0_
Hibernate: call next value for hibernate_sequence
Hibernate: insert into global (platformType, id) values (?, ?)
Hibernate: select gpioconfig0_.id as id1_1_, gpioconfig0_.address as address2_1_, gpioconfig0_.mode as mode3_1_, gpioconfig0_.name as name4_1_, gpioconfig0_.pullup as pullup5_1_ from gpio gpioconfig0_
21:23:36.769 [main] INFO  ua.net.maxx.service.GPIOSevice - Got config for 0 pins
21:23:37.027 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]:
null
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]: null
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1076)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:191)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2084)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:169)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:142)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:273)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:259)
        at ua.net.maxx.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: null
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1382)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1948)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1579)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1074)
        ... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.hibernate.type.spi.TypeConfiguration.scope(TypeConfiguration.java:159)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
        at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactory(EntityManagerFactoryBean.java:171)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryDefinition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:196)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1366)
        ... 11 common frames omitted

I don't have simple app with example, you can find code by this link - https://github.com/maxx-ukoo/pi-easy/tree/micronaut-issue

This commit (https://github.com/maxx-ukoo/pi-easy/commit/4fb83ba84a8a1e502f7fa5901df960ebd4be5829) fix issue.  No any issue (except lazy init) with @Singleton scope

**Comment by maxx-ukoo** [comment]
Workaround for my case: 
implement ApplicationEventListener<ServiceStartedEvent> and execute init method in onApplicationEvent(final ServiceStartedEvent event)
