### ISSUE TITLE
Micronaut triggers android flag of use of Restrictions on non-SDK interfaces

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#124]
See: https://developer.android.com/preview/restrictions-non-sdk-interfaces

How to reproduce: 

Start an Android App using Micronaut DI with Android P

<img width="684" alt="napkin 7 09-05-18 12 35 25 pm" src="https://user-images.githubusercontent.com/864788/39810493-7402904a-5385-11e8-9fc8-624416b195cb.png">

You will see an error such as: 

<img width="282" alt="napkin 7 09-05-18 12 36 21 pm" src="https://user-images.githubusercontent.com/864788/39810526-94889b66-5385-11e8-9b4c-b3ec1d369c1a.png">

**Comment by dthommes** [comment]
**Problem**

This issue will cause an app to crash on Android 9.0, when the **targetSdkVersion** of the project is set to **28** (28 = Android 9.0). With a Stacktrace like this:

> Caused by: java.lang.Error: java.lang.NoSuchFieldException: No field threadLocalRandomProbe in class Ljava/lang/Thread; (declaration of 'java.lang.Thread' appears in /system/framework/core-oj.jar)
>         at io.micronaut.caffeine.base.UnsafeAccess.objectFieldOffset(UnsafeAccess.java:59)
>         at io.micronaut.caffeine.cache.StripedBuffer.<clinit>(StripedBuffer.java:88)
>         at io.micronaut.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:191)
>         at io.micronaut.caffeine.cache.SS.<init>(Unknown Source:0)
>         at io.micronaut.caffeine.cache.SSMS.<init>(Unknown Source:0)
>         at java.lang.reflect.Constructor.newInstance0(Native Method) 
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
>         at io.micronaut.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(Unknown Source:166) 
>         at io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3043) 
>         at io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3039) 
>         at io.micronaut.caffeine.cache.Caffeine.build(Caffeine.java:926) 
>         at io.micronaut.context.DefaultBeanContext.<init>(DefaultBeanContext.java:90) 
>         at io.micronaut.context.DefaultApplicationContext.<init>(DefaultApplicationContext.java:79) 
>         at io.micronaut.context.DefaultApplicationContextBuilder.build(DefaultApplicationContextBuilder.java:123) 
>         at io.micronaut.context.ApplicationContextBuilder$$CC.start(Unknown Source:120) 
>         at io.micronaut.context.DefaultApplicationContextBuilder.start(Unknown Source:0) 
>         at io.micronaut.context.ApplicationContext$$CC.run$$STATIC$$(Unknown Source:109) 

**Findings** 

There is access to two forbidden APIs. One of them is on the dark greylist. As of Android 9.0, access to dark-grey listed fields will cause a NoSuchFieldException when targetSdk is 28. When the app is compiled with targetSdk 27, only warnings are logged.

> 08-21 22:21:54.728 17330-17330/nevernull.remoteuilocalexample W/euilocalexampl: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
> 08-21 22:21:54.733 17330-17330/nevernull.remoteuilocalexample W/euilocalexampl: Accessing hidden field Ljava/lang/Thread;->threadLocalRandomProbe:I (dark greylist, reflection)

The problem is Caffeine, which accesses threadLocalRandomProbe via Reflection here:

https://github.com/ben-manes/caffeine/blob/v2.6.2/caffeine/src/main/java/com/github/benmanes/caffeine/cache/StripedBuffer.java#L88

**Comment by GongHuixue** [comment]
The issue also happened on my Android app. if the targetSdk is higher than 28 and the caffeine version lower than 3.0.0, the issue will appear.
i found there is something changed in Thread.java, as following pic showed.
![image](https://user-images.githubusercontent.com/34301712/170488709-f2380121-6656-46e9-a490-d6c22f7a5570.png)

but i have no idea to resolve the issue. is anybody have idea?

**Comment by graemerocher** [comment]
We plan to remove caffeine as a dependency for the next major version

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-core/issues/7039

**Comment by ben-manes** [comment]
Caffeine wasn’t designed for Android which is very different than server-side Java. The 2.x series had to use Unsafe tricks for performance, whereas 3.x uses VarHandles for purity. While that should work on Android, all of the design assumptions and optimization goals differ between the two platforms. I don’t think caches for one will ever be good for the other, so removing caffeine from core makes sense if wanting to extend to the mobile ecosystem.

**Comment by GongHuixue** [comment]
@graemerocher , thanks for quickly response.
@ben-manes , thanks for your explanation, in fact i not use Caffeine directly in Android, i am using owlapi in my Android Project, and owlapi depend on caffeine.

 "The 2.x series had to use Unsafe tricks for performance, whereas 3.x uses VarHandles for purity."
i had tried to use caffeine 3.0 in my project.
![image](https://user-images.githubusercontent.com/34301712/170608006-1ed12e04-6a7b-4575-86a7-bdd15f49f608.png)
the issue of "Caused by: java.lang.Error: java.lang.NoSuchFieldException: No field threadLocalRandomProbe in class Ljava/lang/Thread;" not exist, 
however another issue happened
"NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger "
https://github.com/SandroHc/reactive-jikan/issues/10

![image](https://user-images.githubusercontent.com/34301712/170608436-b2a38c79-e9fd-4d4d-99c3-21588e45758f.png)
it seems that Android jar sdk don't have this class and methods, is any idea to resolve the issue?
look foraward your reply.

**Comment by ben-manes** [comment]
Caffeine 2.x uses a trick from `j.u.c.a.LongAdder` which uses these fields in the `Thread` class. Since we already used `Unsafe` it was coupled to the JDK and reasonable to emulate. When moving to pure Java via `VarHandles`, the logic was changed to use the thread id instead (theoretically worse, but practically the same). It took until [3.0.2](https://github.com/ben-manes/caffeine/releases/tag/v3.0.2) to fully remove our unsafe behavior, but you should be fine using that or the latest version (currently 3.1.1).

Even if you make it work, the design constraints of Android are very different than server-side Java. For libraries that need to be cross ecosystem they can use a bridge interface, often just `ConcurrentMap`. Otherwise Android-specific libraries like https://github.com/MobileNativeFoundation/Store likely fit the application use-cases better than something like Caffeine does.

**Comment by graemerocher** [comment]
Triage: resolved by the completed Caffeine-removal work tracked in #7039. The original Android restriction came from the old shaded Caffeine implementation; the current Core source contains no shaded io.micronaut.caffeine implementation or Caffeine runtime dependency. The remaining Caffeine guidance applies to the separate cache integration, not Micronaut DI itself. No additional reproducer or PR is needed; closing as completed.
