### ISSUE TITLE
Log4j2 and class not found error

### ISSUE THREAD

**Issue by missourian55** [micronaut-projects/micronaut-core#1248]
Trying to run a micronaut 1.0.4 application with log4j2

### Task List

- [ ] Steps to reproduce provided
**Declare log4j2 dependencies (I used 2.11.2) and place log4j2.xml in resources folder**
- [ ] Stacktrace (if present) provided
```
2019-02-13 20:25:09,840 ERROR i.m.c.DefaultBeanContext [ForkJoinPool.commonPool-worker-3] Error processing bean method Definition: io.micronaut.management.health.monitor.HealthMonitorTask.void monitor() with processor (io.micronaut.scheduling.processor.ScheduledMethodProcessor@537c8c7e): Error instantiating bean of type  [io.micronaut.configuration.metrics.aggregator.MeterRegistryConfigurer]

Message: ch/qos/logback/classic/turbo/TurboFilter
Path Taken: MeterRegistryConfigurer.meterRegistryConfigurer([Collection binders],Collection filters)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.configuration.metrics.aggregator.MeterRegistryConfigurer]

Message: ch/qos/logback/classic/turbo/TurboFilter
Path Taken: MeterRegistryConfigurer.meterRegistryConfigurer([Collection binders],Collection filters)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1333) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2238) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2166) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:754) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1084) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1680) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1079) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:958) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.micrometer.$MeterRegistryFactory$MeterRegistryConfigurerDefinition.build(Unknown Source) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2238) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2166) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:534) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:521) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.BeanLocator.streamOfType(BeanLocator.java:107) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.micrometer.MeterRegistryCreationListener.onCreated(MeterRegistryCreationListener.java:49) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.micrometer.MeterRegistryCreationListener.onCreated(MeterRegistryCreationListener.java:38) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1364) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:496) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.UnresolvedProvider.get(UnresolvedProvider.java:59) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder.onCreated(ExecutorServiceMetricsBinder.java:66) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder.onCreated(ExecutorServiceMetricsBinder.java:48) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1364) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.scheduling.$ScheduledExecutorTaskSchedulerDefinition.build(Unknown Source) ~[micronaut-runtime-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1721) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1625) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:903) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:506) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.process(ScheduledMethodProcessor.java:97) ~[micronaut-runtime-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.lambda$null$24(DefaultBeanContext.java:1096) ~[micronaut-inject-1.0.4.jar:1.0.4]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_171]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_171]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_171]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_171]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/classic/turbo/TurboFilter
	at io.micronaut.configuration.metrics.binder.logging.LogbackMeterRegistryBinderFactory.logbackMetrics(LogbackMeterRegistryBinderFactory.java:52) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.binder.logging.$LogbackMeterRegistryBinderFactory$LogbackMetricsDefinition.build(Unknown Source) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319) ~[micronaut-inject-1.0.4.jar:1.0.4]
	... 44 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.turbo.TurboFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at io.micronaut.configuration.metrics.binder.logging.LogbackMeterRegistryBinderFactory.logbackMetrics(LogbackMeterRegistryBinderFactory.java:52) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.configuration.metrics.binder.logging.$LogbackMeterRegistryBinderFactory$LogbackMetricsDefinition.build(Unknown Source) ~[micronaut-micrometer-core-1.0.4.jar:1.0.4]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319) ~[micronaut-inject-1.0.4.jar:1.0.4]
	... 44 more
2019-02-13 20:25:09,841 DEBUG i.m.c.DefaultBeanContext [main] Resolved bean candidates [Definition: io.micronaut.configuration.metrics.micrometer.prometheus.PrometheusMeterRegistryFactory, Definition: io.micronaut.configuration.metrics.micrometer.MeterRegistryFa
```
### Expected Behaviour

Works with log4j2

### Actual Behaviour

No Classdef found error

### Environment Information

- **Operating System**: mac os
- **Micronaut Version:** 1.0.4
- **JDK Version:** JDK 8 192

**Comment by jameskleeh** [comment]
As a workaround, try setting `micronaut.metrics.binders.logback.enabled` to false
