### ISSUE TITLE
mn-cli create-federation with multiple services fails - 1.1.0.M1

### ISSUE THREAD

**Issue by monsdroid** [micronaut-projects/micronaut-core#1284]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

`mn create-federation -i -f kotlin,security-jwt,management,micrometer,postgres-reactive,swagger-kotlin,junit -s user,dummy --stacktrace`

### Expected Behaviour

Federation Project with user and dummy

### Actual Behaviour
Federation Project with user
```
........
|Federation created at C:\***\tmp
|Generating Kotlin project...
................................................................
|Generating Kotlin project...
...Error
|
Error occurred running Micronaut CLI: C:\***\tmp\dummy does not exist. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
: C:\***\tmp\dummy does not exist.
        at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:505)
        at org.apache.tools.ant.taskdefs.MatchingTask.getDirectoryScanner(MatchingTask.java:193)
        at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:539)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at io.micronaut.cli.profile.commands.AbstractCreateCommand.replaceBuildTokens(AbstractCreateCommand.groovy:449)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.micronaut.cli.profile.commands.AbstractCreateCommand.handle(AbstractCreateCommand.groovy:351)
        at io.micronaut.cli.profile.commands.CreateFederationCommand.handle(CreateFederationCommand.groovy:86)
        at io.micronaut.cli.MicronautCli.executeCommand(MicronautCli.groovy:353)
        at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:233)
        at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:174)

Error |
Error occurred running Micronaut CLI: C:\Users\Simon\Projekte\tmp\dummy does not exist.


### Environment Information

- **Operating System**: Windows 10 git-bash
- **Micronaut Version:** 1.1.0.M1
- **JDK Version:** 11.0.2

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/810e73d7d0605afeb01be00321cee9f4a4690303
