### ISSUE TITLE
java.lang.IllegalStateException: BeanDefinition.requiresMethodProcessing()

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1300]
Using the new Bean Introspection API I've found and error when executing the Graal native image for a RabbitMQ application. Please note that:
- The application doesn't use `micronaut-http-server-netty`.
- I've adjusted `MicronautSubstitutions` and `build-native-image` to remove all references to Netty.
- The same application works fine using the previous approach to generate the native image (the code is available in branch `graal`).

To reproduce the issue:
- `git clone https://github.com/micronaut-guides/micronaut-rabbitmq-rpc`
- `cd micronaut-rabbitmq-rpc/complete/bookcatalogue`
- `git checkout graal-bean-introspection`
- `sdk use java 1.0.0-rc-12-grl`
- `./build-native-image.sh`

The native image is created correctly but when running it:

```
12:36:37.408 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: BeanDefinition.requiresMethodProcessing() returned true but method has no @Executable definition. This should never happen. Please report an issue.
java.lang.IllegalStateException: BeanDefinition.requiresMethodProcessing() returned true but method has no @Executable definition. This should never happen. Please report an issue.
	at io.micronaut.context.DefaultBeanContext.lambda$null$23(DefaultBeanContext.java:1131)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$24(DefaultBeanContext.java:1130)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1127)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2099)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:185)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:273)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:259)
```

**Comment by graemerocher** [comment]
Probably `Executable` is needed in `reflect.json`
