### ISSUE TITLE
io.micronaut.context.exceptions.BeanContextException: Error processing bean, method definition: No value available for annotation member 

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1301]
To reproduce the issue:
- `git clone https://github.com/micronaut-guides/micronaut-rabbitmq-rpc`
- `cd micronaut-rabbitmq-rpc`
- Start RabbitMQ: `docker run --rm -it --network=host rabbitmq:3.7.11-management`
- `git checkout graal-bean-introspection`
- `./gradlew complete/bookcatalogue:run`
- Please note that `BookCatalogueService` uses `Book` that is annotated with `@Introspected`

The application doesn't start:
```
13:04:21.687 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error processing bean [Definition: example.micronaut.bookcatalogue.BookCatalogueService] method definition [List listBooks()]: No value available for annotation member @io.micronaut.configuration.rabbitmq.annotation.Queue[reQueue] of type: boolean
io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: example.micronaut.bookcatalogue.BookCatalogueService] method definition [List listBooks()]: No value available for annotation member @io.micronaut.configuration.rabbitmq.annotation.Queue[reQueue] of type: boolean
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:92)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1429)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2235)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:587)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:574)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1137)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2099)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:185)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:273)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:259)
	at example.micronaut.bookcatalogue.Application.main(Application.java:8)
Caused by: java.lang.IllegalStateException: No value available for annotation member @io.micronaut.configuration.rabbitmq.annotation.Queue[reQueue] of type: boolean
	at io.micronaut.core.annotation.AnnotationValue.lambda$getRequiredValue$0(AnnotationValue.java:224)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.micronaut.core.annotation.AnnotationValue.getRequiredValue(AnnotationValue.java:224)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:108)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:61)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	... 15 common frames omitted

> Task :complete/bookcatalogue:run FAILED

FAILURE: Build failed with an exception.
```

**Comment by chery-qualset-hcd-ca-gov** [comment]
I get this error when I create a new grails 4.0.2 app. Am I missing a required configuration? 
- grails create-app --profile=rest-api
- change 
    testCompile "io.micronaut:micronaut-http-client"
to
    compile "io.micronaut:micronaut-http-client:1.3.6"

- add the following to build.gradle
    implementation "io.micronaut:micronaut-security-jwt:1.4.0"

- compile and run the app

result:
C:\tools\java\jdk1.8.0_251\bin\java.exe -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -Djline.WindowsTerminal.directConsole=false -Dfile.encoding=UTF-8 -classpath C:\Users\cqualset\AppData\Local\Temp\classpath516224761.jar org.grails.cli.GrailsCli run-app --plain-output

|Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL in 2s
|Running application...
The Class-Path manifest attribute in C:\Users\cqualset\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\jaxb-runtime\2.3.1\dd6dda9da676a54c5b36ca2806ff95ee017d8738\jaxb-runtime-2.3.1.jar referenced one or more files that do not exist: file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/jaxb-api-2.3.1.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/txw2-2.3.1.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/istack-commons-runtime-3.0.7.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/stax-ex-1.8.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/FastInfoset-1.2.15.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.1/dd6dda9da676a54c5b36ca2806ff95ee017d8738/javax.activation-api-1.2.0.jar
The Class-Path manifest attribute in C:\Users\cqualset\.gradle\caches\modules-2\files-2.1\com.sun.xml.bind\jaxb-impl\2.3.1\a1a12b85ba1435b4189e065f7dafcc3fb9410d38\jaxb-impl-2.3.1.jar referenced one or more files that do not exist: file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/jaxb-runtime-2.3.1.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/txw2-2.3.1.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/istack-commons-runtime-3.0.7.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/stax-ex-1.8.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/FastInfoset-1.2.15.jar,file:/C:/Users/cqualset/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.1/a1a12b85ba1435b4189e065f7dafcc3fb9410d38/javax.activation-api-1.2.0.jar
2020-06-06 13:03:09.368 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

io.micronaut.context.exceptions.BeanContextException: Error loading bean [io.micronaut.web.router.version.VersionAwareRouterListener]: io/micronaut/inject/annotation/AnnotationMetadataHierarchy
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$32(DefaultBeanContext.java:1419)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1429)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:241)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidatesInternal$68(DefaultBeanContext.java:2473)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidatesInternal(DefaultBeanContext.java:2473)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2511)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:894)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:620)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:350)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1233)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2445)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:200)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:155)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
	at apisucker.Application.main(Application.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NoClassDefFoundError: io/micronaut/inject/annotation/AnnotationMetadataHierarchy
	at io.micronaut.web.router.version.$VersionAwareRouterListenerDefinition.<init>(Unknown Source)
	at io.micronaut.web.router.version.$VersionAwareRouterListenerDefinitionClass.load(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:63)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$32(DefaultBeanContext.java:1417)
	... 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.micronaut.inject.annotation.AnnotationMetadataHierarchy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 39 common frames omitted
