### ISSUE TITLE
Unexpected error occurred: Error instantiating bean with Bean Introspection API

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1302]
Please note that this works using the current approach to generate Graal native images (available in `graal` branch)

To reproduce the issue:
- `git clone https://github.com/micronaut-guides/micronaut-rabbitmq-rpc`
- `cd micronaut-rabbitmq-rpc/complete/bookrecommendation`
- `git checkout graal-bean-introspection`
- `sdk use java 1.0.0-rc-12-grl`
- `./build-native-image.sh`
- `./bookrecommendation`
- `curl localhost:8080/books`

There is an error:
```
$ ./bookrecommendation 
13:19:10.577 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 37ms. Server Running: http://localhost:8080

13:19:13.961 [nioEventLoopGroup-2-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [example.micronaut.bookrecommendation.BookController]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new BookController([CatalogueClient catalogueClient],InventoryClient inventoryClient)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [example.micronaut.bookrecommendation.BookController]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new BookController([CatalogueClient catalogueClient],InventoryClient inventoryClient)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1398)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1971)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1692)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1672)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:940)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at example.micronaut.bookrecommendation.$BookControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1384)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1971)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1692)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1672)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:549)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2516)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2537)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$15(RoutingInBoundHandler.java:1285)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:194)
	at example.micronaut.bookrecommendation.CatalogueClient$Intercepted.<init>(Unknown Source)
	at example.micronaut.bookrecommendation.$CatalogueClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1384)
	... 52 common frames omitted

**Comment by graemerocher** [comment]
To debug problems like this you can add to `logback.xml`:

```xml
<logger name="io.micronaut.core.reflect" level="trace" />
```

Which results in output like:

```
18:09:00.506 [nioEventLoopGroup-1-3] DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class io.micronaut.retry.annotation.Recoverable
18:09:00.506 [nioEventLoopGroup-1-3] DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class io.micronaut.retry.annotation.Recoverable
18:09:00.506 [nioEventLoopGroup-1-3] DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class io.micronaut.configuration.rabbitmq.annotation.RabbitClient
18:09:00.506 [nioEventLoopGroup-1-3] DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class io.micronaut.configuration.rabbitmq.annotation.RabbitClient
```

Which tells you the class names that need to go into `reflect.json` to resolve the issue.

Having said that it shouldn't be necessary to add these, so investigating.
