### ISSUE TITLE
Graal native image fails to start if cors enabled

### ISSUE THREAD

**Issue by dekstroza** [micronaut-projects/micronaut-core#1321]
Micronaut 1.0.4 (also Micronaut 1.1.0.M2)
Graal rc12
OS (Linux, OSX)

Example of graal native application in micronaut guides works fine with micronaut 1.0.4 and graal rc12, but if application.yaml is modified to enable cors, image can be created but fails to run with following error:
```
11:50:10.051 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1399)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:941)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
        at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:959)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:560)
        at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:132)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
        at io.dekstroza.Application.main(Application.java:8)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
        at java.lang.Class.getDeclaredClasses0(DynamicHub.java)
        at java.lang.Class.getDeclaredClasses(DynamicHub.java:1867)
        at java.lang.Class$2.run(Class.java:1504)
        at java.lang.Class$2.run(Class.java:1499)
        at java.security.AccessController.doPrivileged(AccessController.java:62)
        at java.lang.Class.getClasses(DynamicHub.java:1498)
        at io.micronaut.context.AbstractBeanDefinition.isInnerConfiguration(AbstractBeanDefinition.java:1642)
        at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:753)
        at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.injectBean(Unknown Source)
        at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
        ... 17 common frames omitted
```
In order to get the image to compile and work, I had to modify the build-native-image.sh to look like this (removing ServiceLoader line and META-INF/services in -HIncludeResources line :
```
#!/bin/zsh
./mvnw package
java -cp target/mongonaut-0.1.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
native-image --no-server \
             --class-path target/mongonaut-0.1.jar \
             -H:ReflectionConfigurationFiles=target/reflect.json \
             -H:EnableURLProtocols=http \
             -H:IncludeResources="logback.xml|application.yml" \
             -H:Name=mongonaut \
             -H:Class=io.dekstroza.Application \
             -H:+ReportUnsupportedElementsAtRuntime \
             -H:+AllowVMInspection \
             --allow-incomplete-classpath \
             --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' \
             --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient
```
I can provide small reproducer if needed. Any help is appreciated.

**Comment by ilopmar** [comment]
I've created a sample app with latest Micronaut snapshot and with that there is a different error. To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app/`
- `git checkout issue-1321_cors`
- Use latest Graal from master branch
- `./build-native-image.sh`

The error is:

```
$ ./basic-app
14:58:25.745 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [cors] of method [setCors] of class: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration

Message: Error resolving property value [micronaut.server.cors]. Property doesn't exist
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> NettyHttpServerConfiguration.setCors([CorsConfiguration cors])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [cors] of method [setCors] of class: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration

Message: Error resolving property value [micronaut.server.cors]. Property doesn't exist
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> NettyHttpServerConfiguration.setCors([CorsConfiguration cors])
	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:772)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.injectBean(Unknown Source)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:941)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:959)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:560)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:132)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at example.micronaut.Application.main(Application.java:8)
```

**Comment by dekstroza** [comment]
Hi @ilopmar, thanks for looking into it. 
In case you wish to take a look, here is the reproducer:
```
➜  mongonaut git:(graal) java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-20181024123616.buildslave.jdk8u-src-tar--b12)
GraalVM 1.0.0-rc12 (build 25.192-b12-jvmci-0.54, mixed mode)

➜  mongonaut git:(graal) uname -a
Darwin Dejans-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

- git clone git@github.com:dekstroza/sandbox.git
- cd sandbox
- git checkout graal
- cd mongonaut
- ./mvn clean install
- ./build-native-image.sh
- ./mongonaut

Gives error from my previous comment, while 
```
java -jar target/mongonaut-0.1.jar
```
works as expected, when called with curl -v localhost:8086/mongonaut/conferences.

**Comment by dekstroza** [comment]
Hi @ilopmar 

I have ran your version, the error is same as what I have originally wrote
```
➜  micronaut-basic-app git:(issue-1321_cors) ./basic-app
15:27:48.049 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
Path Taken: new NettyHttpServer([NettyHttpServerConfiguration serverConfiguration],ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1399)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:941)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:959)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:560)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:132)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at example.micronaut.Application.main(Application.java:8)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
	at java.lang.Class.getDeclaredClasses0(DynamicHub.java)
	at java.lang.Class.getDeclaredClasses(DynamicHub.java:1867)
	at java.lang.Class$2.run(Class.java:1504)
	at java.lang.Class$2.run(Class.java:1499)
	at java.security.AccessController.doPrivileged(AccessController.java:62)
	at java.lang.Class.getClasses(DynamicHub.java:1498)
	at io.micronaut.context.AbstractBeanDefinition.isInnerConfiguration(AbstractBeanDefinition.java:1642)
	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:753)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.injectBean(Unknown Source)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	... 17 common frames omitted```

**Comment by ilopmar** [comment]
@dekstroza I've tried my test application with Graal-RC12 and I see the same error as you. Graal is changing fast, that's why I use the latest version from master branch to test Micronaut applications and to report issues.
I also try published Graal versions to check if there was a regression, but in most of the errors there isn't. 
That's why I'm reporting the error with latest Graal version.

**Comment by dekstroza** [comment]
Cool, thanks again for looking into it.

**Comment by ilopmar** [comment]
I've enabled CORS support in the basic-app application to avoid regressions on this: https://github.com/micronaut-graal-tests/micronaut-basic-app/commit/8250d0e14f658855cb2ef321e09d3300a86ae86c
