### ISSUE TITLE
Cannot read jaeger.properties with Jaeger and Graal

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1327]
As a workaround for #732 I've added the missing Zipkin dependencies (that I don't really need it because I'm using Jaeger).

To reproduce the issue:
- `git clone https://github.com/ilopmar/micronaut-jaeger-graal`
- `cd micronaut-jaeger-graal`
- `git checkout workaround`
- Use latest GraalVM from master branch (it won't work with RC13)
- `./build-native-image.sh`
- `./mn-jaeger-graal`

Error:
```
$ ./mn-jaeger-graal 
09:17:01.857 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
09:17:01.858 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
09:17:01.859 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.tracing.instrument.scheduling.ExecutorServiceInstrumenter]

Message: Cannot read jaeger.properties
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.tracing.instrument.scheduling.ExecutorServiceInstrumenter]

Message: Cannot read jaeger.properties
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1399)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:941)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.tracing.instrument.scheduling.$ExecutorServiceInstrumenterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2339)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2267)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:797)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:565)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:332)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1075)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2102)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:186)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at micronaut.jaeger.graal.Application.main(Application.java:8)
Caused by: java.lang.RuntimeException: Cannot read jaeger.properties
	at io.jaegertracing.internal.JaegerTracer.getVersionFromProperties(JaegerTracer.java:641)
	at io.jaegertracing.internal.JaegerTracer.loadVersion(JaegerTracer.java:626)
	at io.jaegertracing.internal.JaegerTracer.<init>(JaegerTracer.java:93)
	at io.jaegertracing.internal.JaegerTracer$Builder.createTracer(JaegerTracer.java:614)
	at io.jaegertracing.internal.JaegerTracer$Builder.build(JaegerTracer.java:610)
	at io.micronaut.tracing.jaeger.JaegerTracerFactory.jaegerTracer(JaegerTracerFactory.java:128)
	at io.micronaut.tracing.jaeger.$JaegerTracerFactory$JaegerTracerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.jaegertracing.internal.JaegerTracer.getVersionFromProperties(JaegerTracer.java:638)
	... 27 common frames omitted
Exception in thread "Timer-0" java.lang.NullPointerException
	at io.jaegertracing.internal.samplers.RemoteControlledSampler.updateSampler(RemoteControlledSampler.java:91)
	at io.jaegertracing.internal.samplers.RemoteControlledSampler$1.run(RemoteControlledSampler.java:70)
```

**Comment by graemerocher** [comment]
static resources are not included by default in graal native images, most likely you need to update `-H:IncludeResources` to include `jaeger.properties`

**Comment by ilopmar** [comment]
Adding that and modifying `reflect.json` leads to a NPE in Jaeger code when starting the application. I'll open an issue on their issue tracker.
```
$ ./mn-jaeger-graal 
17:01:18.460 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
17:01:18.461 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
Exception in thread "Timer-0" java.lang.NullPointerException
	at io.jaegertracing.internal.samplers.RemoteControlledSampler.updateSampler(RemoteControlledSampler.java:89)
	at io.jaegertracing.internal.samplers.RemoteControlledSampler$1.run(RemoteControlledSampler.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
17:01:18.503 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 59ms. Server Running: http://localhost:8080
Exception in thread "jaeger.RemoteReporter-FlushTimer" java.lang.NullPointerException
	at io.jaegertracing.internal.reporters.RemoteReporter.flush(RemoteReporter.java:114)
	at io.jaegertracing.internal.reporters.RemoteReporter$1.run(RemoteReporter.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by ilopmar** [comment]
https://github.com/jaegertracing/jaeger-client-java/issues/600

**Comment by dekstroza** [comment]
Hi @ilopmar, I got this working in my own tutorials for micronaut, there are few issues here, one with [io.jaegertracing.internal.metrics.Metrics](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/metrics/Metrics.java) and second with the [*SamplingStrategy classes/SamplingStrategyResponse](https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core/src/main/java/io/jaegertracing/internal/samplers/http). 

Adding these typehints
```
@TypeHint(value = { io.jaegertracing.internal.samplers.http.SamplingStrategyResponse.class,
           io.jaegertracing.internal.samplers.http.ProbabilisticSamplingStrategy.class,
           io.jaegertracing.internal.samplers.http.RateLimitingSamplingStrategy.class,
           io.jaegertracing.internal.metrics.Metrics.class }, accessType = { TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS,
           TypeHint.AccessType.ALL_DECLARED_FIELDS, TypeHint.AccessType.ALL_DECLARED_METHODS })
public class Application {
public static void main(String[] args) {
        Micronaut.run(Application.class);
}
```
and enabling write access to these final fields 
```
@AutomaticFeature
public class RuntimeReflectionRegistrationFeature implements Feature {

    public void beforeAnalysis(BeforeAnalysisAccess access) {
        try {
            RuntimeReflection.register(true, ProbabilisticSamplingStrategy.class.getDeclaredField("samplingRate"));
            RuntimeReflection.register(true, SamplingStrategyResponse.class.getDeclaredField("probabilisticSampling"));
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }
    }
}
```
will get it all working nicely. Tested with micronaut 1.1.0 and graal-rc16 (also tested with jaeger-thrift 0.34.0, and if you throw in jaeger-micrometer dependency too, it will use it's MetricsFactory rather then NoopMetricsFactory). 
I wasn't sure how to enable write access to final fields using micronaut's graal related annotations, had a brief look at the *typehint* code but didnt see anything that could do it so reverted to the `@AutomaticFeature and RuntimeReflection.register` to do it.

I can send pull request if you want. Full code(rather complex example that I am building) is on my [github](https://github.com/dekstroza/sandbox/tree/working-mongonaut)

**Comment by graemerocher** [comment]
Believe this has been resolved. If that is not that case @ilopmar please reopen
