### ISSUE TITLE
Async onApplicationEvents are called twice on Context beans

### ISSUE THREAD

**Issue by LeviSchuck** [micronaut-projects/micronaut-core#1345]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a context class with `implements ApplicationEventListener<YourEventHere>`
2. Add `@Async` to the `onApplicationEvent` method
3. Create another class which publishes to an instance of `ApplicationEventPublisher`

### Expected Behavior

Event listener is called once on an async thread

### Actual Behavior

Called twice, one for the normal bean, one for the intercepted bean
I set a breakpoint in the inject event code and saw it list the same bean twice (once was a generated injected wrapper)
![image](https://user-images.githubusercontent.com/245911/54079961-107dd180-42ac-11e9-82aa-509d4255df1d.png)
_This screenshot is from another project, a minimal project is listed below._

### Environment Information

- **Operating System**: Mac OS X 10.14.3
- **Micronaut Version:** 1.0.4
- **JDK Version:** 10.0.2

### Example Application
https://github.com/LeviSchuck/doubleevent

If I add `new Throwable().printStackTrace()` on my event listener in the above example, the following is printed.

```
java.lang.Throwable
	at com.levischuck.EventListener.onApplicationEvent(EventListener.java:17)
	at com.levischuck.$EventListenerDefinition$Intercepted.$$access0(Unknown Source)
	at com.levischuck.$EventListenerDefinition$Intercepted$$proxy0.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:90)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
	at io.micronaut.scheduling.async.AsyncInterceptor.lambda$intercept$3(AsyncInterceptor.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.Throwable
	at com.levischuck.EventListener.onApplicationEvent(EventListener.java:17)
	at com.levischuck.EventListener.onApplicationEvent(EventListener.java:7)
	at io.micronaut.context.DefaultBeanContext.lambda$publishEvent$16(DefaultBeanContext.java:933)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:927)
	at com.levischuck.EventMaker.sayHello(EventMaker.java:20)
	at com.levischuck.$EventMakerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:77)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by LeviSchuck** [comment]
Output from sample project:
```
EventListener constructed
EventListener constructed
EventMaker constructed
Publishing 0
New event! HelloEvent{count=0}
New event! HelloEvent{count=0}
20:53:37.616 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2539ms. Server Running: http://localhost:8080
Publishing 1
New event! HelloEvent{count=1}
New event! HelloEvent{count=1}
Publishing 2
New event! HelloEvent{count=2}
New event! HelloEvent{count=2}
```

**Comment by jameskleeh** [comment]
Can you test on 1.1.0.M2 ? Pretty sure this is fixed in the latest release

**Comment by jameskleeh** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/492

**Comment by LeviSchuck** [comment]
I updated `mavenBom 'io.micronaut:micronaut-bom:1.1.0.M2'`, cleaned, rebuilt, but the output is the same.

**Comment by jameskleeh** [comment]
What is the purpose of the `@Context` annotation for the event listener?

**Comment by LeviSchuck** [comment]
Wow! Thanks for the fix

The purpose is that such seemed to be the obvious way of getting a singleton event listener instantiated and listening, without being pulled as a dependency into a controller. 

Similar to using `@Context` and `@Scheduled` I believe.

**Comment by jameskleeh** [comment]
The event listeners will be retrieved as soon as an event is published that they are listening for, so `@Context` is not necessary unless there is some other reason you want the bean to be initialized at startup.

**Comment by hrpath** [comment]
Hi we're using 1.3.7 and we can reproduce the bug
We got twice Suggestion Startup in the console.
Thx

```
@Singleton
public class Application implements ApplicationEventListener<ApplicationStartupEvent>  {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }

    @Override
    public void onApplicationEvent(ApplicationStartupEvent event) {
        System.out.println("Suggestion Startup");
    }
}
```
