### ISSUE TITLE
Error creating native image containing hibernate-jpa and netty server

### ISSUE THREAD

**Issue by NicklasWallgren** [micronaut-projects/micronaut-core#1460]
Dependencies:
compile "io.micronaut:micronaut-http-server-netty"
compile "io.micronaut.configuration:micronaut-hibernate-jpa"

### Actual Behaviour
native-image -H:+ReportExceptionStackTraces --allow-incomplete-classpath --no-server -cp build/libs/hello-world-0.1.jar 

```
Error: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@7766e264  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public void java.net.HttpURLConnection.setInstanceFollowRedirects(boolean)  of class: java.lang.reflect.Method
    root: null

com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@7766e264  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public void java.net.HttpURLConnection.setInstanceFollowRedirects(boolean)  of class: java.lang.reflect.Method
    root: null

	at com.oracle.svm.core.util.UserError.abort(UserError.java:67)
	at com.oracle.svm.hosted.image.NativeImageHeap.verifyTargetDidNotChange(NativeImageHeap.java:558)
	at com.oracle.svm.hosted.image.NativeImageHeap.writeReference(NativeImageHeap.java:595)
	at com.oracle.svm.hosted.image.NativeImageHeap.write(NativeImageHeap.java:584)
	at com.oracle.svm.hosted.image.NativeImageHeap.writeField(NativeImageHeap.java:578)
	at com.oracle.svm.hosted.image.NativeImageHeap.writeObject(NativeImageHeap.java:841)
	at com.oracle.svm.hosted.image.NativeImageHeap.writeHeap(NativeImageHeap.java:290)
	at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:431)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:600)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:416)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.1.0.RC2
- 1.0.0-rc-14-grl

**Comment by ilopmar** [comment]
This issue is related to https://github.com/oracle/graal/issues/659 and https://github.com/oracle/graal/issues/717 and it has been fixed in Graal master branch (currently rc15-dev). 
I'm trying to build a new native-image with that version and it fails with other error (I'll open more issues in their issue tracker)

**Comment by ilopmar** [comment]
https://github.com/oracle/graal/issues/1127

**Comment by NicklasWallgren** [comment]
Alright, thanks for the info.

**Comment by ilopmar** [comment]
It's now possible to build native images with Hibernate/JPA but I've found a new issue: https://github.com/micronaut-projects/micronaut-core/issues/1569
