### ISSUE TITLE
Race condition (infinite loop) JPA CurrentSession

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#1484]
After upgrading from `RC1` to `RC2` I sometimes (not always) get following error. It is really hard
to get the error consistently. It shows up in about every 3rd test run and sometimes when running the application.

### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

(… very hard …)
1. create a jpa project with `RC1` 
2. update to `RC2`
3. run tests (controller accessing JPA repo) a few times until error happens

### Expected Behaviour

No error occurs.

### Actual Behaviour

Every 3rd to 6th time following error shows up on all JPA related services:

```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted]: null
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1482)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1895)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1807)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:854)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.$resolveTarget(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.interceptedTarget(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at io.micronaut.configuration.hibernate.jpa.$$EntityManagerFactoryBean$CurrentSessionDefinition$InterceptedDefinition$$exec134.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createQuery(Unknown Source)
	at 
```

### Environment Information

- **Operating System**:  Linux
- **Micronaut Version:** 1.1.0.RC2
- **JDK Version:** 8

**Comment by graemerocher** [comment]
Will investigate, thanks for the report

**Comment by graemerocher** [comment]
Can reproduce in the micronaut-sql project, it isn't so much a race condition but a load order problem

**Comment by sdelamo** [comment]
Find attached a sample app with reproduces this issue.

Run` ./gradlew check  `and you should see: 


```
repository.count() == 0
|          |
|          io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted]: null
<example.micronaut.$NodeEntityRepositoryImplDefinition$Intercepted@44deae0a $interceptors=[[io.micronaut.validation.ValidatingInterceptor@27b57663, io.micronaut.spring.tx.annotation.TransactionInterceptor@3083558c], [io.micronaut.validation.ValidatingInterceptor@27b57663, io.micronaut.spring.tx.annotation.TransactionInterceptor@3083558c], [io.micronaut.validation.ValidatingInterceptor@27b57663, io.micronaut.spring.tx.annotation.TransactionInterceptor@3083558c]] $proxyMethods=[Number count(), Integer save(Node node), void delete(Integer id)] entityManager=io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted@462276ae>

	at example.micronaut.NodeEntityRepositoryImplSpec.if no nodes, count() does not throw an exception and it returns 0(NodeEntityRepositoryImplSpec.groovy:29)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted]: null
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1482)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1895)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1807)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:854)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
...
..
.
```

[app.zip](https://github.com/micronaut-projects/micronaut-core/files/3042465/app.zip)

**Comment by graemerocher** [comment]
Thanks

**Comment by sascha-frinken** [comment]
Could you confirm, that this is RC2 related or have I just been lucky it didn't hit me on RC1 yet...?

**Comment by graemerocher** [comment]
It is RC2 specific yes

**Comment by goeh** [comment]
I also have this problem in one of my services. Reverting to RC1 solves the problem. Good to hear you are able to reproduce it.

**Comment by graemerocher** [comment]
If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle` once the build https://travis-ci.org/micronaut-projects/micronaut-core/builds/516231862 completes:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.0.BUILD-SNAPSHOT'
    }
}
```

**Comment by graemerocher** [comment]
Actually it will be build https://travis-ci.org/micronaut-projects/micronaut-core/builds/516235507

**Comment by sascha-frinken** [comment]
As I couldn't reproduce the error consistently in my project, I can only say 0 errors in 10 test runs, what makes me think the error is fixed. Thank you. 
Any estimate for RC3?

**Comment by goeh** [comment]
I can also confirm the fix. My test suite failed almost every time with RC2. I've now run the tests 10 times with BUILD-SNAPSHOT without failure. Switched back to RC2 and it failed again. No failures with RC1. Thanks!

**Comment by sdelamo** [comment]
It has fixed the error for us as well.
