### ISSUE TITLE
Exception when using Scheduled Jobs and calling ApplicationContext.refresh() 

### ISSUE THREAD

**Issue by mrwilby** [micronaut-projects/micronaut-core#1515]
### Task List

- [X ] Steps to reproduce provided
- [ X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

Create a very simple app that has a scheduled job 

```
@Singleton
public class TestJob {

    private final ApplicationContext context;

    @Inject
    public TestJob(ApplicationContext context) {
        this.context = context;
    }

    @Scheduled(fixedRate = "3s")
    public void process() {
        this.context.refresh();
    }
}
```

It doesn't matter whether you call ApplicationContext.refresh() from within the job or outside. Either way, an exception then occurs. 

### Expected Behaviour

- No exception is expected
- The app continues to run

### Actual Behaviour

- An exception occurs
- The app shuts down

```
08:46:05.852 [ForkJoinPool.commonPool-worker-1] ERROR i.m.context.DefaultBeanContext - Error processing bean method Definition: example.app.TestJob.void process() with processor (io.micronaut.scheduling.processor.ScheduledMethodProcessor@5176d279): Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@44b60105 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@72e14a41[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@44b60105 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@72e14a41[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
	at io.micronaut.scheduling.instrument.InstrumentedScheduledExecutorService.scheduleAtFixedRate(InstrumentedScheduledExecutorService.java:47)
	at io.micronaut.scheduling.ScheduledExecutorTaskScheduler.scheduleAtFixedRate(ScheduledExecutorTaskScheduler.java:109)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.process(ScheduledMethodProcessor.java:144)
	at io.micronaut.context.DefaultBeanContext.lambda$null$25(DefaultBeanContext.java:1204)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Environment Information

- **Operating System**: Mac OS X 10.13.6
- **Micronaut Version:** 1.1.0-RC2
- **JDK Version:** jdk1.8.0_181.jdk

### Example Application

- Not included but the code is pasted above.

**Comment by graemerocher** [comment]
Why exactly are you calling `refresh()` from within the job?

**Comment by mrwilby** [comment]
As said, it doesn't matter where you call refresh() from. The same thing happens.

**Comment by graemerocher** [comment]
Calling refresh() during initialization is likely to result in weird things happening since it will shutdown active beans. However we should improve the error message. This is related to #1421

**Comment by mrwilby** [comment]
I can't seem to call refresh() from anywhere without this exception being thrown (when using scheduled jobs). For example, if I call refresh() from within a controller endpoint, the exact same exception occurs. It doesn't appear to be anything related to initialization, unless I misunderstood.

**Comment by graemerocher** [comment]
We will have a look. Thanks.

**Comment by sorin-silaghi** [comment]
I believe we had the same issue while running tests with `rebuildContext = true`. It seems to only happen on linux since my colleague who is on windows couldn't reproduce the problem. I thought this information might be useful.

**Comment by graemerocher** [comment]
Triage: Type Bug. This report targets Micronaut 1.1.0-RC2 and calls ApplicationContext.refresh(), but current ApplicationContext no longer exposes that refresh API. The pasted failure therefore cannot be reproduced through the current supported API. If the intended scenario uses ApplicationContextLifeCycle or a current refresh mechanism, please reopen with a current minimal application and define whether scheduled tasks must be re-registered during refresh. Closing as stale; no new reproducer is needed.
