### ISSUE TITLE
No bean of type [javax.persistence.EntityManager] exists with Hibernate and Graal

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1569]
I'm using Micronaut's Bean Validator introduced in 1.2.0.BUILD-SNAPSHOT  and I've excluded `hibernate-validator` that it's pulled in by `micronaut-hibernate-jpa`. I can build the native image but there is an error when executing a request

- `git clone https://github.com/micronaut-graal-tests/micronaut-hibernate-graal`
- `cd micronaut-hibernate-graal`
- Use Graal from master branch (currently rc17)
- `./build-native-image.sh`
- Start MySql: `docker run -it --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=mydb mysql:8.0.12`
- `./hibernate-graal`
- Execute curl: `curl -X POST localhost:8080/user/save -H 'Content-Type:application/json' -d '{"username":"ivan","firstName":"Iván","lastName":"López"}'`

```
$ ./hibernate-graal
16:37:23.616 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 45ms. Server Running: http://localhost:8080
16:37:32.712 [pool-2-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for parameter [entityManager] of class: example.micronaut.$UserServiceDefinition$Intercepted

Message: No bean of type [javax.persistence.EntityManager] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new UserController([UserService userService]) --> new $UserServiceDefinition$Intercepted([EntityManager entityManager],BeanContext beanContext,Interceptor[] interceptors)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [entityManager] of class: example.micronaut.$UserServiceDefinition$Intercepted

Message: No bean of type [javax.persistence.EntityManager] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new UserController([UserService userService]) --> new $UserServiceDefinition$Intercepted([EntityManager entityManager],BeanContext beanContext,Interceptor[] interceptors)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:989)
	at example.micronaut.$$UserServiceDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at example.micronaut.$UserControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:567)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2661)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2682)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:295)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1348)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [javax.persistence.EntityManager] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1815)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	... 51 common frames omitted
```

**Comment by ilopmar** [comment]
The same error happens using Micronaut 1.1.0 and Hibernate-validator.

**Comment by graemerocher** [comment]
That is because the error has nothing to do with validation

**Comment by bufferings** [comment]
I got the same error. I don't know why No bean of type [javax.persistence.EntityManager] exists only when it's run as native image...

**Comment by bufferings** [comment]
I finally made the application run successfully with this change:

https://github.com/bufferings/micronaut-hibernate-graal/commit/8d93183d7eb316e2bd07cf8633861da16c6ad463

Like this:

```
❯ ./hibernate-graal
01:32:15.598 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
01:32:15.641 [main] INFO  org.hibernate.type.BasicTypeRegistry - HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@5592be073df8
01:32:15.713 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
01:32:15.713 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - constraint "uk_r43af9ap4edm43mmtq01oddj6" of relation "users" does not exist, skipping
01:32:15.720 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
01:32:15.761 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 275ms. Server Running: http://localhost:8080
```

```
❯ curl -X POST localhost:8080/user/save -H 'Content-Type:application/json' -d '{"username":"ivan","firstName":"Iván","lastName":"López"}'
{"id":1,"username":"ivan","firstName":"Iván","lastName":"López"}

❯ curl localhost:8080/user/1
{"id":1,"username":"ivan","firstName":"Iván","lastName":"López"}
```

I explain one by one.

## My environment

GraalVM 1.0.0 RC16 & Micronaut 1.1.0

```
❯ sdk current java

Using java version 1.0.0-rc-16-grl

❯ mn --version
| Micronaut Version: 1.1.0
| JVM Version: 1.8.0_202
```

## 1. Stopped `@Entity` scan

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [javax.persistence.EntityManager] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotat
ion processing.
```

This is caused by `@Entity` scan at runtime. As a workaround, I created `NoScanMetadataSourcesFactoryBean` to replace the original one and register `User` entity manually.

It might be good for Micronaut to support compile time Entity scan?

## 2. Added XercesImpl

Then I faced following error at runtime:

```
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.stream.events.XMLEventFactoryImpl
```

So I added Xerces:

```groovy
compile 'xerces:xercesImpl:2.12.0'
```

## 3. Added `@TypeHint` to the `Application` class

InstantiationException at runtime:

```
Caused by: java.lang.InstantiationException: Type `org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
```

Therefore I added `@TypeHint` to the `Application` class and finally it looks like this:

```java
@TypeHint({
    ImplicitNamingStrategyJpaCompliantImpl.class
})
public class Application {
```

## 4. Switched to PostgreSQL

Then I got this error:

```
Apr 28, 2019 9:17:55 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
SEVERE: Unable to create initial connections of pool.
java.sql.SQLException: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.WrongArgumentException
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:332)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739)
```

It seems MySQL driver doesn't work well with native image so far: https://bugs.mysql.com/bug.php?id=91968

So I swithed to PostgreSQL:

```sh
docker run -it --rm -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=mydb postgres:11.2-alpine
```

application.yml:

```yaml
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/mydb'
    username: root
    password: secret
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
```

In addition, I needed to add `PostgreSQL95Dialect` to the `@TypeHint`.

## 5. public field for `User` entity

Then, I faced following exeption:

```
Message: No identifier specified for entity: example.micronaut.User
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
```

It seems because the annotations such as `@Id` on private fields are lost. So I changed the fields public.

At the same time, I added `IdentityGenerator` to the `@TypeHint`.

## 6. Added `@TypeHint`

I needed to add these classes to the `@TypeHint`:

```
SingleTableEntityPersister.class,
EntityMetamodel.class,
PojoEntityTuplizer.class,
SpringSessionContext.class
```

## 7. Marked `User` class as final

I marked `User` class as final to avoid Hibernate to use proxy enhancement. But this might mean we can't use lazy loading.

```
...
Caused by: java.lang.IllegalArgumentException: Could not create type
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.load(ByteBuddyState.java:178)
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.loadProxy(ByteBuddyState.java:102)
        at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyHelper.buildProxy(ByteBuddyProxyHelper.java:54)
        at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyFactory.postInstantiate(ByteBuddyProxyFactory.java:61)
        at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
        at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:156)
        at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
        ... 27 common frames omitted

```

## 8. DynamicProxyConfigurationFiles

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface java.sql.Statement] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
```

It seems the relative path of `-H:DynamicProxyConfigurationFiles` is started from current directory. So I created `dynamic-proxy/config.json` in the project:

```json
[
  ["java.sql.Statement"],
  ["java.sql.PreparedStatement"]
]
```

And I added the option to the following file:

src/main/resources/META-INF/native-image/example.micronaut/hibernate-application/native-image.properties

```
Args = -H:IncludeResources=logback.xml|application.yml \
       -H:Name=hibernate-graal \
       -H:Class=example.micronaut.Application \
       -H:DynamicProxyConfigurationFiles=dynamic-proxy/config.json
```

## 9. Delay class initialization

This is an optional configuration and just for suppressing warnings:

src/main/resources/META-INF/native-image/example.micronaut/hibernate-application/native-image.properties

```
--delay-class-initialization-to-runtime=org.apache.commons.logging.LogAdapter$Log4jLog,org.hibernate.secure.internal.StandardJaccServiceImpl,org.postgresql.sspi.SSPIClient,org.hibernate.dialect.OracleTypesHelper
```

## Then it works!

:)

But these are the minimum configuration for running example app. We need to add many classes for reflection if we use other features of Hibernate.

**Comment by graemerocher** [comment]
Well done! I think rather than make the class final the correct solution is to use build time enhancement https://docs.jboss.org/hibernate/orm/5.0/topical/html/bytecode/BytecodeEnhancement.html#_build_time_enhancement

**Comment by bufferings** [comment]
Thank you! I will give it a try!

**Comment by graemerocher** [comment]
Btw Micronaut 1.1 does feature an API to do build time scanning. It is just not integrated with the Hibernate support yet. You can however use `BeanIntrospector.findIntrospections(Entity.class, "mypackage")` and it will find the introspections for all `@Entity` classes

Other than that what makes sense is to include the patches you worked out for `@TypeHint` etc. into the `hibernate-jpa` subproject so that all this work is not required. Thanks for going to the effort to get it all figured out!

**Comment by recursivecodes** [comment]
I've used @bufferings work here to get this working with Oracle ATP, and a simple `entityManager.find()` works great.  However, trying entityManager.createQuery()` is turning into quite a rabbit hole of compiling, running, erroring, adding more `@TypeHint` classes.  There's got to be a better way, yes?  Am I doing something wrong?  Here's my `@TypeHint` annotation so far (and I've still got more errors)...

```
@TypeHint({
        ImplicitNamingStrategyJpaCompliantImpl.class,
        Oracle12cDialect.class,
        OracleDriver.class,
        OracleSSOKeyStoreSpi.class,
        OraclePKI.class,
        PKCS12PBE.class,
        SHA.class,
        DES_EDE.class,
        RSAPrivateKey.class,
        RSAPublicKey.class,
        KeyUsageExtension.class,
        BasicConstraintsExtension.class,
        SubjectKeyIDExtension.class,
        CRLDistPointExtension.class,
        AuthorityKeyIDExtension.class,
        AuthorityInfoAccessExtension.class,
        CertificatePoliciesExtension.class,
        HqlToken.class,
        Node.class,
        QueryNode.class,
        SqlNode.class,
        FromClause.class,
        OrderByClause.class,
        SequenceStyleGenerator.class,
        SingleTableEntityPersister.class,
        EntityMetamodel.class,
        PojoEntityTuplizer.class,
        SpringSessionContext.class
})
```

Am I doing something wrong?

**Comment by recursivecodes** [comment]
I should also note that I did not have success with the Hibernate Build Time enhancement.  I had to also make my model `public final` - as well as having to make `EntityManager` `public final` to get the injection to work into my repository implementation.

**Comment by bufferings** [comment]
@graemerocher 

> Well done! I think rather than make the class final the correct solution is to use build time enhancement https://docs.jboss.org/hibernate/orm/5.0/topical/html/bytecode/BytecodeEnhancement.html#_build_time_enhancement

I tried build time enhancement and it works without final modifier. Thank you. Here's the change:

https://github.com/bufferings/micronaut-hibernate-graal/commit/c3b351e59acafd9b31f366248f0d374548d2f688

But I don't understand the build-time-enhancement & gradle very well, so I would like to check more details about them to know the best configuration.

> Btw Micronaut 1.1 does feature an API to do build time scanning. It is just not integrated with the Hibernate support yet. You can however use `BeanIntrospector.findIntrospections(Entity.class, "mypackage")` and it will find the introspections for all `@Entity` classes

Sounds interesting. I will check it.

> Other than that what makes sense is to include the patches you worked out for `@TypeHint` etc. into the `hibernate-jpa` subproject so that all this work is not required. Thanks for going to the effort to get it all figured out!

Thank you for the advice. I'm glad to hear that. I'm currently trying to replace Spring PetClinic to Micronaut PetClinic and make it run as Native Image. After that, I will have better understanding of JPA TypeHint etc and I would like to send patches.

**Comment by graemerocher** [comment]
Sounds great, PRs welcome!

**Comment by bufferings** [comment]
@recursivecodes 

year... it's very tough work. I also want to know if there's a better way to check it.

Regarding query issue, I noticed I need to add almost all the classes in `org.hibernate.hql.internal.ast.tree` to `@TypeHint`.

Current my `@TypeHint` for another project (PetClinic) is as follows, though I'm not sure these are all necessary:

```
@TypeHint(value = {
  // for Hibernate
  HibernatePresenceCondition.class,
  EntitiesInPackageCondition.class,
  // for Thymeleaf
  MultiplicationDivisionRemainderExpression.class,
  MultiplicationExpression.class,
  RemainderExpression.class,
  DivisionExpression.class,
  AndExpression.class,
  AdditionSubtractionExpression.class,
  AdditionExpression.class,
  SubtractionExpression.class,
  GreaterLesserExpression.class,
  LessOrEqualToExpression.class,
  GreaterOrEqualToExpression.class,
  LessThanExpression.class,
  GreaterThanExpression.class,
  EqualsNotEqualsExpression.class,
  EqualsExpression.class,
  NotEqualsExpression.class,
  OrExpression.class,
  Temporals.class,
  Fields.class,
  // for Hibernate
  ExpressionFactoryImpl.class,
  ImplicitNamingStrategyJpaCompliantImpl.class,
  PostgreSQL95Dialect.class,
  IdentityGenerator.class,
  SingleTableEntityPersister.class,
  EntityMetamodel.class,
  PojoEntityTuplizer.class,
  BasicCollectionPersister.class,
  SpringSessionContext.class,
  HqlToken.class,
  OneToManyPersister.class,
  // AST
  AggregateNode.class,
  AssignmentSpecification.class,
  BetweenOperatorNode.class,
  BinaryArithmeticOperatorNode.class,
  BinaryLogicOperatorNode.class,
  BooleanLiteralNode.class,
  CastFunctionNode.class,
  CollectionFunction.class,
  ComponentJoin.class,
  ConstructorNode.class,
  CountNode.class,
  DeleteStatement.class,
  DotNode.class,
  EntityJoinFromElement.class,
  FromClause.class,
  FromElement.class,
  FromElementFactory.class,
  FromReferenceNode.class,
  HqlSqlWalkerNode.class,
  IdentNode.class,
  ImpliedFromElement.class,
  IndexNode.class,
  InLogicOperatorNode.class,
  InsertStatement.class,
  IntoClause.class,
  IsNotNullLogicOperatorNode.class,
  IsNullLogicOperatorNode.class,
  JavaConstantNode.class,
  LiteralNode.class,
  MapEntryNode.class,
  MapKeyEntityFromElement.class,
  MapKeyNode.class,
  MapValueNode.class,
  MethodNode.class,
  Node.class,
  NullNode.class,
  OrderByClause.class,
  ParameterNode.class,
  QueryNode.class,
  ResultVariableRefNode.class,
  SearchedCaseNode.class,
  SelectClause.class,
  SelectExpressionImpl.class,
  SelectExpressionList.class,
  SimpleCaseNode.class,
  SqlFragment.class,
  SqlNode.class,
  UnaryArithmeticNode.class,
  UnaryLogicOperatorNode.class,
  UpdateStatement.class
}, accessType = {TypeHint.AccessType.ALL_PUBLIC})
public class PetClinicApplication {
```

**Comment by recursivecodes** [comment]
Thanks @bufferings - is your repo public somewhere that I can take a look?

**Comment by bufferings** [comment]
Congrats @recursivecodes ! I'm so glad.

> Edit: FYI - I have asked our internal engineers (I work at Oracle) to look into supporting packages instead of just classes in reflection-config.json and they have said it is on their radar.

That's great! I checked whether package is supported or not and found it isn't (yet). That would be great feature!

My repo isn't  too messy to be public. I will sort out my thoughts and codes and make it public in a week.

**Comment by recursivecodes** [comment]
This might not be the best place for this comment, but, I thought I'd share as it relates to Micronaut Graal images with Hibernate.  I threw a tiny load test at my native image and ended up with an empty thread pool.  Seems connections are not being released back to the pool once they are used.  I'll dig into it, but just wanted to throw it out here in case anyone had any thoughts.

```
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [pool-3-thread-7] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:100; busy:100; idle:0; lastwait:30000].
```

**Comment by bufferings** [comment]
@recursivecodes Interesting. If possible, could you please try to use PostgreSQL with your load test so that we can know whether it's from Driver or not? With my simple app with PostgreSQL (just getting user), it shows no error with my simple load test with Gatling (written below). So if you get the same error even with PostgreSQL, my test is wrong.

```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                      30000 (OK=30000  KO=0     )
> min response time                                      1 (OK=1      KO=-     )
> max response time                                  18085 (OK=18085  KO=-     )
> mean response time                                    49 (OK=49     KO=-     )
> std deviation                                        746 (OK=746    KO=-     )
> response time 50th percentile                          8 (OK=8      KO=-     )
> response time 75th percentile                         17 (OK=17     KO=-     )
> response time 95th percentile                         67 (OK=67     KO=-     )
> response time 99th percentile                        149 (OK=149    KO=-     )
> mean requests/sec                                309.278 (OK=309.278 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                         29943 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                           57 (  0%)
> failed                                                 0 (  0%)
================================================================================
```

Regarding the main topic of this issue, I found several improvement in my code following @graemerocher 's advices, so I will update the information in a few days ;)

**Comment by recursivecodes** [comment]
OK, I'm seriously stumped here.  Once the app hits 100 connections it freezes up and memory util jumps to 300MB. This doesn't make any sense.  I've enabled trace debugging and see the connection being released and closed, but obviously they're not being fully released.  This is only a problem when running as a native image.  I'd rather not switch DBs at this point.  @graemerocher, when you're around - do you have any ideas?

I tried 'removeAbandoned' on the datasource, but that's certainly not a permanent solution (and memory usage keeps climbing, so something is leaking somewhere).

**Comment by graemerocher** [comment]
@recursivecodes Are there some instructions somewhere on how to setup the database locally on Mac OS X? If it is happening with Oracle and not with Postgres it is certainly related to the Oracle driver, in which case folks at Oracle may be better placed to debug the issue. @shelajev @cstancu are you aware of any issues with Substrate and the Oracle JDBC driver not closing connections?

**Comment by recursivecodes** [comment]
@graemerocher I can provide you with some temporary credentials to hit an oracle DB if you're interested in testing this.  I'm seeing a new thread spawned for every single request when running the native image and only 1 or 2 threads spawned if I load test the JAR running outside of the native image.

**Comment by recursivecodes** [comment]
Not sure if this is relevant, but @cstancu shared this link with me about [finalizers in Graal](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#finalizers) and Hibernate uses finalizers in [DriverManagerConnectionProviderImpl](https://github.com/hibernate/hibernate-orm/blob/6911efdfb71beff3a30162b663c308dbacca7c76/hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java#L211).  Would there be a way to work around this?

@bufferings code suggests he is not using connection pooling (no "pooled" attribute in his config file) so maybe that's why he's not seeing this issue? I dunno... :)

**Comment by graemerocher** [comment]
I will try reproduce tomorrow and check the configs. If it is a pooling problem then it should not matter which database is used

**Comment by recursivecodes** [comment]
I tried against Postgres tonight and observed the memory increasing under load, but it seemed the connections were properly released back to the pool as the app did not run out of connections.  Still seems weird that the memory consumption would climb like that under such a small load (500 connections over a minute)...

Then I pointed at a Docker container running Oracle XE and observed the same issue as when I was pointing at ATP, so it definitely seems driver related (or something to do with Graal + OJDBC) so I'll follow up with our engineers.  Thanks.

**Comment by bufferings** [comment]
Here's the update for my work https://github.com/micronaut-projects/micronaut-core/issues/1569#issuecomment-487395933

## build-time enhancement 

It works. So I don't need to make User class final any more, though the feature seems incubating stage.

## Define allDeclaredFields for User 

The reason I needed to make User's fields public was reflection configuration.

I need `allDeclaredFields` for User. But `Introspected` annotation, which is automatically added by `EntityIntrospectedAnnotationMapper`, only generate `allPublicFields`. So I created a file for this time to set `allDeclaredFields` as a workaround.

With that, I don't need to make the fields private any more.

## Use BeanIntrospector to scan Entity annotated classes for MetadataSources

As @graemerocher told me, it works with BeanIntrospector. So we don't need to register Entities manually.

I sent a pull request to the micronaut-hibernate-graal repository. I think this is all from me in this issue. Thank you.

**Comment by graemerocher** [comment]
I've made some progress on improvements to the support for the next version of Micronaut.

I have sent a PR to show the simplifications: https://github.com/bufferings/micronaut-petclinic/pull/6

**Comment by graemerocher** [comment]
Micronaut Data now fully supports Hibernate and GraalVM native images so I think we are good here
