### ISSUE TITLE
Maven build fails on fresh aws function project created by cli 

### ISSUE THREAD

**Issue by adilfulara** [micronaut-projects/micronaut-core#1606]
Using the cli, when using the maven build, the project build fails due to log4j2 error.

### Steps to Reproduce

```
mn create-function aws-hello-world --build maven
cd aws-hello-world
mvn package
```

### Expected Behaviour

The jar file to be built

### Actual Behaviour

build failure

```
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ aws-hello-world ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running aws.hello.world.AwsHelloWorldFunctionTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 s <<< FAILURE! - in aws.hello.world.AwsHelloWorldFunctionTest
[ERROR] aws.hello.world.AwsHelloWorldFunctionTest  Time elapsed: 0.048 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/StackLocatorUtil
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.StackLocatorUtil

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   AwsHelloWorldFunctionTest » NoClassDefFound org/apache/logging/log4j/util/Stac...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.485 s
[INFO] Finished at: 2019-04-30T17:11:19-07:00
[INFO] ------------------------------------------------------------------------
```

### Environment Information

- **Operating System**: OSX Mojave
- **Micronaut Version:** 1.1.0
- **JDK Version**
```
➜  aws-hello-world java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

To fix the build delete 
```
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j2</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <version>2.9.1</version>
      <scope>runtime</scope>
    </dependency>
```
**but a fresh project should not need this.**

**Comment by benrhine** [comment]
So I've done a bit of extra poking on this and the results are interesting. So for the above mentioned issue and for the above mentioned version of `micronaut 1.1.0` this error can be resolved by adding the following dependency
```
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>2.9.1</version>
    <scope>runtime</scope>
</dependency>
```
This also holds true for the current version 1.2.7, just add the above dependency and everything should work correctly

Unfortunately in building current micronaut (1.3.X) locally and adding the above dependency leads us to this error
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.645 s <<< FAILURE! - in aws.hello.world.AwsHelloWorldFunctionTest
[ERROR] aws.hello.world.AwsHelloWorldFunctionTest  Time elapsed: 1.644 s  <<< ERROR!
io.micronaut.context.exceptions.BeanInstantiationException: 
Error instantiating bean of type  [io.micronaut.function.web.AnnotatedFunctionRouteBuilder]

Message: tried to access class io.micronaut.function.executor.AbstractExecutor from class aws.hello.world.$AwsHelloWorldFunctionDefinition$$exec1
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver) --> new DefaultRouter([Collection builders]) --> new AnnotatedFunctionRouteBuilder(ExecutionHandleLocator executionHandleLocator,UriNamingStrategy uriNamingStrategy,ConversionService conversionService,[MediaTypeCodecRegistry codecRegistry],String contextPath)
Caused by: java.lang.IllegalAccessError: tried to access class io.micronaut.function.executor.AbstractExecutor from class aws.hello.world.$AwsHelloWorldFunctionDefinition$$exec1
```
Which is the same error that will occur if you delete the above two mentioned dependencies when using the current version as well. Upgrading them to the latest `1.1.0` and `2.12.1` does not change the error. What do you think @graemerocher

**Comment by samblake** [comment]
I just has the IllegalAccessError building with gradle on 1.3.0.M1. Works fine on 1.2.8.

**Comment by ctoestreich** [comment]
I am getting the same issue on 1.3.0.M2 and I had to also add the dep listed by @benrhine 

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class io.micronaut.function.executor.AbstractExecutor from class example.initializr.function.$exampleInitializrFunctionFunctionDefinition$$exec1
        at example.initializr.function.$exampleInitializrFunctionFunctionDefinition$$exec1.<init>(Unknown Source)
        at example.initializr.function.$exampleInitializrFunctionFunctionDefinition.<init>(Unknown Source)
        at example.initializr.function.$exampleInitializrFunctionFunctionDefinition.<init>(Unknown Source)
        at example.initializr.function.$exampleInitializrFunctionFunctionDefinitionClass.load(Unknown Source)
        at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:63)
        at io.micronaut.context.DefaultBeanContext.lambda$getBeanDefinitions$12(DefaultBeanContext.java:1019)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.micronaut.context.DefaultBeanContext.getBeanDefinitions(DefaultBeanContext.java:1022)
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:58)
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1741)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2394)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2076)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2050)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:623)
        at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:88)
        at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:64)
        at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:62)
        at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:98)
        at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:60)
        at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:50)
```

**Comment by PaulienVa** [comment]
This bugs still occur for functions with feature `openfaas` which is quite weird, as the following dependency is not needed at all

Although deleting this dependency is a fine workaround, is there a way to remove this from the generated code?
```
<dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j2</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
```
