### ISSUE TITLE
Micronaut is not able to find key-store resource even though it exists on defined path.

### ISSUE THREAD

**Issue by mkkhedawat** [micronaut-projects/micronaut-core#1608]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create Micronaut-Kotlin project from CLI
2. Inject RxHttpClient in sample service
3. Set application.yml as below
```
micronaut:
    http:
        client:
            ssl:
                key-store:
                    path: test.jks
                    password: changeit
                    type: jks
```
4. place dummy jks file , same path as .classpath
5. Start server and hit endpoint

### Expected Behaviour
The application should be able to read key-store and RxHttpClient should be able to use it.
If resource (jks) doesn't exist on path, error should be thrown compile time.

### Actual Behaviour
There is no compile-time error and when application endpoint is hit, the server throws run-time error as below :
```
16:30:02.569 [pool-1-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [com.hello.myservice.utils.TokenUtil]

Message: An error occurred configuring SSL
Path Taken: new TokenController([TokenService tService]) --> new TokenService([TokenUtil tUtil]) --> new TokenUtil([RxHttpClient hClient],String readEndpoint,String createEndpoint)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.hello.myservice.utils.TokenUtil]

Message: An error occurred configuring SSL
Path Taken: new TokenController([TokenService tService]) --> new TokenService([TokenUtil tUtil]) --> new TokenUtil([RxHttpClient hClient],String readEndpoint,String createEndpoint)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1492)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:727)
	at io.micronaut.context.DefaultBeanContext$5.get(DefaultBeanContext.java:1916)
	at io.micronaut.http.client.scope.ClientScope.lambda$get$3(ClientScope.java:128)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.http.client.scope.ClientScope.get(ClientScope.java:104)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1900)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1831)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at com.hello.myservice.utils.$TokenUtilDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at com.hello.myservice.services.$TokenServiceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at com.hello.myservice.controllers.$TokenControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:567)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2661)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2682)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:295)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1348)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.http.ssl.SslConfigurationException: An error occurred configuring SSL
	at io.micronaut.http.client.ssl.NettyClientSslBuilder.getKeyManagerFactory(NettyClientSslBuilder.java:112)
	at io.micronaut.http.client.ssl.NettyClientSslBuilder.build(NettyClientSslBuilder.java:79)
	at io.micronaut.http.client.DefaultHttpClient.<init>(DefaultHttpClient.java:240)
	at io.micronaut.http.client.$DefaultHttpClientDefinition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:113)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1467)
	... 66 common frames omitted
Caused by: io.micronaut.http.ssl.SslConfigurationException: The resource /Users/mansa/projects/myservice/test.jks could not be found
	at io.micronaut.http.ssl.SslBuilder.load(SslBuilder.java:140)
	at io.micronaut.http.ssl.SslBuilder.getKeyStore(SslBuilder.java:115)
	at io.micronaut.http.client.ssl.NettyClientSslBuilder.getKeyManagerFactory(NettyClientSslBuilder.java:106)
	... 71 common frames omitted

```

> I tried giving absolute path as well, same issue.

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 1.1
- **JDK Version:** 8

**Comment by croudet** [comment]
Have you tried with the following syntax for the `path`: `file:/path/to/the/file`

**Comment by mkkhedawat** [comment]
Sorry, With file prefix it does work.
Shouldn't this error be thrown compile-time and not runtime ?

**Comment by graemerocher** [comment]
We don't currently verify configuration at compile time. An improvement such as that is probably beyond the scope of this issue
