### ISSUE TITLE
When using Hibernate-GORM, how to convert a domain class into a JSON string?

### ISSUE THREAD

**Issue by wureka** [micronaut-projects/micronaut-core#1651]
For using Hibernate-GORM in Micronaut 1.1.1, I use below command to create a micronaut app:

*mn create-app foo -l=groovy -f=hibernate-gorm*

And, for adding the ability of approaching JSON , I add below line to build.gradle in order to use JsonSlurper to approace JSON:

*compile 'org.codehaus.groovy:groovy-all:2.5.6'*

So my build.gralde looks like below:

    plugins {
        id "io.spring.dependency-management" version "1.0.6.RELEASE"
        id "groovy"
        id "com.github.johnrengelman.shadow" version "4.0.2"
        id "application"
    }
    
    version "0.1"
    group "memberservice"
    
    repositories {
        mavenCentral()
        maven { url "https://jcenter.bintray.com" }
    }
    
    dependencyManagement {
        imports {
            mavenBom 'io.micronaut:micronaut-bom:1.1.1'
        }
    }
    
    configurations {
        // for dependencies that are needed for development only
        developmentOnly 
    }
    
    dependencies {
        compile 'org.codehaus.groovy:groovy-all:2.5.6'
        compile "io.micronaut:micronaut-runtime-groovy"
        compile "io.micronaut:micronaut-validation"
        compile "io.micronaut:micronaut-http-client"
        compile "io.micronaut.configuration:micronaut-hibernate-validator"
        compile "io.micronaut.configuration:micronaut-hibernate-gorm"
        compile "io.micronaut:micronaut-http-server-netty"
        compileOnly "io.micronaut:micronaut-inject-groovy"
        runtime "ch.qos.logback:logback-classic:1.2.3"
        runtime "com.h2database:h2"
        runtime "org.apache.tomcat:tomcat-jdbc"
        testCompile("org.spockframework:spock-core") {
            exclude group: "org.codehaus.groovy", module: "groovy-all"
        }
        testCompile "io.micronaut:micronaut-inject-groovy"
        testCompile "io.micronaut.test:micronaut-test-spock"
    }
    
    test.classpath += configurations.developmentOnly
    
    mainClassName = "memberservice.Application"
    tasks.withType(GroovyCompile) {
        groovyOptions.forkOptions.jvmArgs.add('-Dgroovy.parameters=true')
    }
    
    shadowJar {
        mergeServiceFiles()
    }
    
    run.classpath += configurations.developmentOnly
    run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')

Now I have a domain class as below:

    import grails.gorm.annotation.Entity
    
    @Entity
    class Member {
        String memberId
        String email
    
        static constraints = {
            memberId    maxSize: 20, nullable: false, unique: true
            email       maxSize: 60, nullable: false
        }
    }

And I have a controller as below:

    import groovy.json.JsonBuilder
    import groovy.util.logging.Slf4j
    import io.micronaut.http.annotation.Controller
    import io.micronaut.http.annotation.Get
    import memberservice.domain.Member
    
    @Slf4j
    @Controller('/member')
    class MemberController {
    
    
        @Get('/testFetchMember')
        def testFetchMember() {
            Member member
            Member.withTransaction {
                member = Member.findByMemberId('A0001')
            }
            log.info("member.email is ${member.email}")
            def jsonObject = new JsonBuilder(member)
            log.info("check point 1001: finish JsonBuilder")
            String jsonString = jsonObject.toPrettyString()
            log.info("jsonString=" + jsonString)
            return jsonString
        }
    
        @Get('/buildSampleData')
        def buildSampleData() {
            Member member = new Member()
            member.with {
                memberId = 'A0001'
                email = 'foo@gmail.com'
            }
            Member.withTransaction {
                member.save()
    //            new Member(memberId: 'A0002', 'foo1@mail.com').save()
    //            new Member(memberId: 'A0003', 'foo2@mail.com').save()
            }
            return "Sample data built done"
        }
    }

Below are output log:

    09:23:30.610 [pool-2-thread-1] INFO  m.controller.MemberController - member.email is foo@gmail.com
    09:23:30.619 [pool-2-thread-1] INFO  m.controller.MemberController - check point 1001: finish JsonBuilder
    09:23:31.069 [pool-2-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null
    java.lang.StackOverflowError: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
	at groovy.lang.PropertyValue.getValue(PropertyValue.java:42)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getProperties(DefaultGroovyMethods.java:557)
	at groovy.json.DefaultJsonGenerator.getObjectProperties(DefaultJsonGenerator.java:242)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:236)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)
        .....
        .....
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:221)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.writeIterator(DefaultJsonGenerator.java:402)
	at groovy.json.DefaultJsonGenerator.writeArray(DefaultJsonGenerator.java:285)

It seems that both JsonSlurper and JsonBuilder can not handle domain classes built from GORM.

So, is there any elegant way to convert domain classes to JSON string in Micronaut ? Please don't ask me to use Jackson library because the approach way of Jackson is so urgly.

I know in Grails, the converter JSON can convert a domain class to JSON string without any problem. So, is it possible to add the feature of JSON converter into Micronaut just like Grails ?

**Comment by jameskleeh** [comment]
Please ask questions in [gitter](https://gitter.im/micronautfw/questions)
