### ISSUE TITLE
After a client closes connection an IOException will be thrown

### ISSUE THREAD

**Issue by Ragin-LundF** [micronaut-projects/micronaut-core#1719]
Hi,

I created a REST application with non-reactive endpoints (simply returned the object or a HttpResponse<T> object) and after I tested it with external tools (Postman and a load test application with an OkHttpClient), the application has worked until I closed Postman or until the test application finished.
After that, the application was thrown exceptions (see below), which confused me, because most consumers will close their connections and if I use this in production, it writes my logs full of those Exceptions.

So I tried to use the micronaut example application, but the results are the same.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a simple REST application (i.e. use micronaut hello-world example for Java)
2. Use Postman (or another client) to call the endpoint (i.e. http://localhost:8080/hello/me)
3. till here all is fine.....
4. close Postman (or your Test-application)
5. An exception will be thrown on the server

### Expected Behaviour

If a "normal" REST-client closes the connection, no Exception should be thrown

### Actual Behaviour

The application throws the following exception:

`?[36m00:12:48.611?[0;39m ?[1;30m[nioEventLoopGroup-1-3]?[0;39m ?[1;31mERROR?[0;39m ?[35mi.m.h.s.netty.RoutingInBoundHandler?[0;39m - Unexpected error occurred: An existing connection was closed by the remote host
java.io.IOException: An existing connection was closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
        at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:813)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
`

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.2
- **JDK Version:** JDK 1.8, JDK 1.11, GraalVM 19.0.0

### Example Application

https://github.com/micronaut-projects/micronaut-examples/tree/master/hello-world-java

**Comment by graemerocher** [comment]
You can add a error handler with the `@Error` annotation that catches `IOException` and checks whether the error is closed by the remote host and handles it gracefully by returning a 500 or some such.
