### ISSUE TITLE
mn create-app - Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:service:jar: in micronautCentral

### ISSUE THREAD

**Issue by menilub** [micronaut-projects/micronaut-core#173]
### Steps to Reproduce

1. mn create-app hello

### Expected Behaviour
create a new Java application in a directory called hello

### Actual Behaviour
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:service:jar: in micronautCentral (https://repo.micronaut.io/) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:service:jar: in micronautCentral (https://repo.micronaut.io/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:129)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:121)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:88)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:73)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:81)
	at io.micronaut.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:293)
	at io.micronaut.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:416)
	at io.micronaut.cli.MicronautCli.executeCommandWithArgumentValidation(MicronautCli.groovy:276)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:252)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:158)
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:service:jar: in micronautCentral (https://repo.micronaut.io/)

### Environment Information

- **Operating System**: MacOs
- **Micronaut Version:** TODO
- **JDK Version: openjdk version "1.8.0_172"

**Comment by ilopmar** [comment]
You also need to build and publish locally the profiles. Please take a look at this: https://github.com/micronaut-projects/micronaut-core#building-from-source
