### ISSUE TITLE
Deadlock at startup

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#1738]
I'm currently investigating a deadlock situation in a Micronaut 1.1.2 service.
This is a service that I have not touched for a while (other than upgrading Micronaut) and I can't remember having this problem before. I will try to downgrade Micronaut and see if it works. The application uses GORM data services.
I can't publish the code right now but I will try to create a sample app to reproduce the problem. I just wanted to publish the stacktrace before I loose it.

### Steps to Reproduce

1. Start application or start a test

### Expected Behaviour

No deadlock.

### Actual Behaviour

Application hangs on startup. Tests also hang on startup.

I paused the hanging test in IntelliJ and got the following stacktrace:
```
transfer:2426, ConcurrentHashMap (java.util.concurrent)
addCount:2288, ConcurrentHashMap (java.util.concurrent)
computeIfAbsent:1720, ConcurrentHashMap (java.util.concurrent)
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2027, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1804, DefaultBeanContext (io.micronaut.context)
getBean:997, DefaultBeanContext (io.micronaut.context)
getBeanForConstructorArgument:982, AbstractBeanDefinition (io.micronaut.context)
build:-1, $ObjectMapperFactory$ObjectMapperDefinition (io.micronaut.jackson)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
createAndRegisterSingleton:2163, DefaultBeanContext (io.micronaut.context)
getBeanForDefinition:1849, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1829, DefaultBeanContext (io.micronaut.context)
getBean:997, DefaultBeanContext (io.micronaut.context)
getBeanForConstructorArgument:982, AbstractBeanDefinition (io.micronaut.context)
build:-1, $JsonMediaTypeCodecDefinition (io.micronaut.jackson.codec)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
createAndRegisterSingleton:2163, DefaultBeanContext (io.micronaut.context)
getBeanForDefinition:1849, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1829, DefaultBeanContext (io.micronaut.context)
getBean:997, DefaultBeanContext (io.micronaut.context)
getBeanForConstructorArgument:982, AbstractBeanDefinition (io.micronaut.context)
build:-1, $HttpClientIntroductionAdviceDefinition (io.micronaut.http.client.interceptor)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
addCandidateToList:2495, DefaultBeanContext (io.micronaut.context)
getBeansOfTypeInternal:2395, DefaultBeanContext (io.micronaut.context)
getBeansOfType:854, DefaultBeanContext (io.micronaut.context)
lambda$getBeansOfTypeForConstructorArgument$10:1088, AbstractBeanDefinition (io.micronaut.context)
resolveBean:-1, 2143233788 (io.micronaut.context.AbstractBeanDefinition$$Lambda$176)
resolveBeanWithGenericsFromConstructorArgument:1697, AbstractBeanDefinition (io.micronaut.context)
getBeansOfTypeForConstructorArgument:1083, AbstractBeanDefinition (io.micronaut.context)
getBeanForConstructorArgument:959, AbstractBeanDefinition (io.micronaut.context)
build:-1, $AbstractEurekaClient$InterceptedDefinition (io.micronaut.discovery.eureka.client.v2)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
addCandidateToList:2495, DefaultBeanContext (io.micronaut.context)
getBeansOfTypeInternal:2417, DefaultBeanContext (io.micronaut.context)
getBeansOfType:854, DefaultBeanContext (io.micronaut.context)
lambda$getBeansOfTypeForConstructorArgument$10:1088, AbstractBeanDefinition (io.micronaut.context)
resolveBean:-1, 2143233788 (io.micronaut.context.AbstractBeanDefinition$$Lambda$176)
resolveBeanWithGenericsFromConstructorArgument:1697, AbstractBeanDefinition (io.micronaut.context)
getBeansOfTypeForConstructorArgument:1083, AbstractBeanDefinition (io.micronaut.context)
getBeanForConstructorArgument:959, AbstractBeanDefinition (io.micronaut.context)
build:-1, $$CachingCompositeDiscoveryClientDefinition$InterceptedDefinition (io.micronaut.discovery.client)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
getScopedBeanForDefinition:1949, DefaultBeanContext (io.micronaut.context)
getBeanForDefinition:1851, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1829, DefaultBeanContext (io.micronaut.context)
getBean:582, DefaultBeanContext (io.micronaut.context)
matches:38, HeartbeatDiscoveryClientCondition (io.micronaut.health)
matchesCustomConditions:308, RequiresCondition (io.micronaut.context)
processPostStartRequirements:188, RequiresCondition (io.micronaut.context)
matches:83, RequiresCondition (io.micronaut.context)
isEnabled:53, AbstractBeanContextConditional (io.micronaut.context)
isEnabled:89, AbstractBeanDefinition (io.micronaut.context)
lambda$findBeanCandidates$33:1333, DefaultBeanContext (io.micronaut.context)
test:-1, 1004430079 (io.micronaut.context.DefaultBeanContext$$Lambda$117)
accept:174, ReferencePipeline$2$1 (java.util.stream)
accept:193, ReferencePipeline$3$1 (java.util.stream)
accept:175, ReferencePipeline$2$1 (java.util.stream)
forEachRemaining:1382, ArrayList$ArrayListSpliterator (java.util)
copyInto:481, AbstractPipeline (java.util.stream)
wrapAndCopyInto:471, AbstractPipeline (java.util.stream)
evaluateSequential:708, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:499, ReferencePipeline (java.util.stream)
findBeanCandidates:1334, DefaultBeanContext (io.micronaut.context)
findBeanCandidates:241, DefaultApplicationContext (io.micronaut.context)
findConcreteCandidateNoCache:2038, DefaultBeanContext (io.micronaut.context)
lambda$findConcreteCandidate$54:2028, DefaultBeanContext (io.micronaut.context)
apply:-1, 859690270 (io.micronaut.context.DefaultBeanContext$$Lambda$81)
lambda$compute$0:721, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
apply:-1, 1275028674 (io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$79)
computeIfAbsent:1660, ConcurrentHashMap (java.util.concurrent)
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2027, DefaultBeanContext (io.micronaut.context)
registerSingleton:456, DefaultBeanContext (io.micronaut.context)
registerSingleton:124, DefaultApplicationContext (io.micronaut.context)
registerSingleton:94, ApplicationContext (io.micronaut.context)
addApplicationListener:52, ConfigurableEventPublisherAdapter (io.micronaut.configuration.gorm.event)
registerEventListeners:372, HibernateDatastore (org.grails.orm.hibernate)
<init>:121, HibernateDatastore (org.grails.orm.hibernate)
<init>:200, HibernateDatastore (org.grails.orm.hibernate)
<init>:221, HibernateDatastore (org.grails.orm.hibernate)
hibernateDatastore:62, HibernateDatastoreFactory (io.micronaut.configuration.hibernate.gorm)
build:-1, $HibernateDatastoreFactory$HibernateDatastoreDefinition (io.micronaut.configuration.hibernate.gorm)
doCreateBean:1494, DefaultBeanContext (io.micronaut.context)
createAndRegisterSingleton:2163, DefaultBeanContext (io.micronaut.context)
loadContextScopeBean:1771, DefaultBeanContext (io.micronaut.context)
initializeContext:1172, DefaultBeanContext (io.micronaut.context)
initializeContext:236, DefaultApplicationContext (io.micronaut.context)
readAllBeanDefinitionClasses:2313, DefaultBeanContext (io.micronaut.context)
start:199, DefaultBeanContext (io.micronaut.context)
start:187, DefaultApplicationContext (io.micronaut.context)
startApplicationContext:234, AbstractMicronautExtension (io.micronaut.test.extensions)
startApplicationContext:128, MicronautSpockExtension (io.micronaut.test.extensions.spock)
beforeClass:160, AbstractMicronautExtension (io.micronaut.test.extensions)
lambda$visitSpecAnnotation$0:57, MicronautSpockExtension (io.micronaut.test.extensions.spock)
intercept:-1, 1978869058 (io.micronaut.test.extensions.spock.MicronautSpockExtension$$Lambda$1)
proceed:97, MethodInvocation (org.spockframework.runtime.extension)
invoke:475, BaseSpecRunner (org.spockframework.runtime)
runSetupSpec:154, BaseSpecRunner (org.spockframework.runtime)
runSetupSpec:149, BaseSpecRunner (org.spockframework.runtime)
doRunSpec:94, BaseSpecRunner (org.spockframework.runtime)
invoke:81, BaseSpecRunner$1 (org.spockframework.runtime)
invokeRaw:484, BaseSpecRunner (org.spockframework.runtime)
invoke:467, BaseSpecRunner (org.spockframework.runtime)
runSpec:73, BaseSpecRunner (org.spockframework.runtime)
run:64, BaseSpecRunner (org.spockframework.runtime)
run:63, Sputnik (org.spockframework.runtime)
run:137, JUnitCore (org.junit.runner)
startRunnerWithArgs:68, JUnit4IdeaTestRunner (com.intellij.junit4)
startRunnerWithArgs:47, IdeaTestRunner$Repeater (com.intellij.rt.execution.junit)
prepareStreamsAndStart:242, JUnitStarter (com.intellij.rt.execution.junit)
main:70, JUnitStarter (com.intellij.rt.execution.junit)
```

### Environment Information

- **Operating System**: MacOS 10.14.5
- **Micronaut Version:** 1.1.2
- **JDK Version:** 1.8.0_202

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by goeh** [comment]
Interesting... I ran service and controller/client tests successfully 10 times in a loop with Micronaut 1.1.0. Then I changed to 1.1.1 and the application deadlocked on the first run. CPU is 100% when it hangs.

**Comment by graemerocher** [comment]
Can you provide the thread dump? CTRL + / in terminal I believe

**Comment by goeh** [comment]
Line 2426 in ConcurrentHashMap#transfer were it hangs looks like this:
```
synchronized (f) {
```
I'll try to make a thread dump, stay tuned...

**Comment by goeh** [comment]
jstack output:
```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode):

"Attach Listener" #13 daemon prio=9 os_prio=31 tid=0x00007f93589e9800 nid=0xe07 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Tomcat JDBC Pool Cleaner[1442407170:1559412175474]" #11 daemon prio=5 os_prio=31 tid=0x00007f9358500000 nid=0x5503 in Object.wait() [0x00007000044ea000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0a47aa0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000006c0a47aa0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007f935585d000 nid=0x4503 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007f9355842800 nid=0x4103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f9354802800 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9354801800 nid=0x3e03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f935403c800 nid=0x3d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9355833000 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f9354035800 nid=0x5003 in Object.wait() [0x0000700003cd2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0035078> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000006c0035078> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9354035000 nid=0x3603 in Object.wait() [0x0000700003bcf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0035300> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c0035300> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007f9353805000 nid=0x2603 runnable [0x00007000031ae000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.Unsafe.getObjectVolatile(Native Method)
	at java.util.concurrent.ConcurrentHashMap.tabAt(ConcurrentHashMap.java:755)
	at java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap.java:2427)
	- locked <0x0000000778307c00> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2288)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1720)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2017)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1794)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)
	at io.micronaut.jackson.codec.$JsonMediaTypeCodecDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1484)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2153)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1839)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1819)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)
	at io.micronaut.http.client.interceptor.$HttpClientIntroductionAdviceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1484)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2485)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2385)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:854)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1088)
	at io.micronaut.context.AbstractBeanDefinition$$Lambda$159/979532928.resolveBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1697)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1083)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:959)
	at io.micronaut.discovery.eureka.client.v2.$AbstractEurekaClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1484)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2485)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2407)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:854)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1088)
	at io.micronaut.context.AbstractBeanDefinition$$Lambda$159/979532928.resolveBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1697)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1083)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:959)
	at io.micronaut.discovery.client.$$CachingCompositeDiscoveryClientDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1484)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1939)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1841)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1819)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:582)
	at io.micronaut.health.HeartbeatDiscoveryClientCondition.matches(HeartbeatDiscoveryClientCondition.java:38)
	at io.micronaut.context.RequiresCondition.matchesCustomConditions(RequiresCondition.java:308)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:188)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:83)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:53)
	at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:89)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$32(DefaultBeanContext.java:1323)
	at io.micronaut.context.DefaultBeanContext$$Lambda$106/1258084361.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1324)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:241)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2028)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$53(DefaultBeanContext.java:2018)
	at io.micronaut.context.DefaultBeanContext$$Lambda$102/1104443373.apply(Unknown Source)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$74/992846223.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x0000000778307c00> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2017)
	at io.micronaut.context.DefaultBeanContext.registerSingleton(DefaultBeanContext.java:456)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultApplicationContext.registerSingleton(DefaultApplicationContext.java:124)
	at io.micronaut.context.ApplicationContext.registerSingleton(ApplicationContext.java:94)
	at io.micronaut.configuration.gorm.event.ConfigurableEventPublisherAdapter.addApplicationListener(ConfigurableEventPublisherAdapter.java:52)
	at org.grails.orm.hibernate.HibernateDatastore.registerEventListeners(HibernateDatastore.java:372)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:121)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:200)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:221)
	at io.micronaut.configuration.hibernate.gorm.HibernateDatastoreFactory.hibernateDatastore(HibernateDatastoreFactory.groovy:62)
	at io.micronaut.configuration.hibernate.gorm.$HibernateDatastoreFactory$HibernateDatastoreDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1484)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2153)
	- locked <0x00000006c01b1250> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1761)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1172)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2303)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	- locked <0x00000006c0035668> (a io.micronaut.context.DefaultApplicationContext)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	- locked <0x00000006c0035668> (a io.micronaut.context.DefaultApplicationContext)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:288)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at org.gr8crm.estate.Application.main(Application.groovy:26)

"VM Thread" os_prio=31 tid=0x00007f935402e800 nid=0x3403 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9353811000 nid=0x1d07 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9353811800 nid=0x2a03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9353812800 nid=0x2b03 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f9353813000 nid=0x5303 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007f9354007000 nid=0x2e03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007f9353813800 nid=0x2f03 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007f9355800000 nid=0x3103 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007f9355801000 nid=0x3303 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9355834000 nid=0x4303 waiting on condition 

JNI global references: 789
```
