### ISSUE TITLE
kafka listener and Manually seeking offsets on multiple Topic listener causes java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access

### ISSUE THREAD

**Issue by vahidhedayati** [micronaut-projects/micronaut-core#1783]
Attempting to follow existing guide:
https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaOffsets

```
@KafkaListener
public class ProductListener implements ConsumerRebalanceListener, ConsumerAware {

    private Consumer consumer;

    @Override
    public void setKafkaConsumer(@Nonnull Consumer consumer) { 
        this.consumer = consumer;
    }

    @Topic("awesome-products")
    void receive(Product product) {
        // process product
    }

   @Topic("anotherawesome-products")
    void receive1(Product product) {
        // process product
    }

    @Override
    public void onPartitionsRevoked(Collection<TopicPartition> partitions) { 
        // save offsets here
    }

    @Override
    public void onPartitionsAssigned(Collection<TopicPartition> partitions) { 
        // seek to offset here
        for (TopicPartition partition : partitions) {
            consumer.seek(partition, 1);
        }
    }
}
```

As per example if you have the single Topic declaration it appears to work fine and you as user can do overrides with onPartitionsAssigned etc. The moment you have multiple topics:

You get a concurrent issue with attempting to do same thing. I have tried registering different Listeners for each topic - which doesn't throw any errors on startup but fails to pickup other listeners/topics.

```
14:44:49.778 [pool-1-thread-3] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=hotelread-kafka-add-event-listener, groupId=hotelread] Setting newly assigned partitions [hotelDelete-0]
ADD onPartitionsAssigned------------------------------------------------------------------------------------------------
14:44:49.778 [pool-1-thread-2] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=hotelread-kafka-add-event-listener, groupId=hotelread] Setting newly assigned partitions [hotelEdit-0]
ADD onPartitionsAssigned------------------------------------------------------------------------------------------------
14:44:49.779 [pool-1-thread-2] ERROR o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=hotelread-kafka-add-event-listener, groupId=hotelread] User provided listener hotel.read.event.listeners.KafkaAddEventListener failed on partition assignment
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2201)
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2185)
        at org.apache.kafka.clients.consumer.KafkaConsumer.assignment(KafkaConsumer.java:853)
        at hotel.read.event.listeners.KafkaAddEventListener.lambda$onPartitionsAssigned$1(KafkaAddEventListener.java:171)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at hotel.read.event.listeners.KafkaAddEventListener.onPartitionsAssigned(KafkaAddEventListener.java:168)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:291)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
        at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:402)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
14:44:49.779 [pool-1-thread-3] ERROR o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=hotelread-kafka-add-event-listener, groupId=hotelread] User provided listener hotel.read.event.listeners.KafkaAddEventListener failed on partition assignment
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2201)
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2185)
        at org.apache.kafka.clients.consumer.KafkaConsumer.assignment(KafkaConsumer.java:853)
        at hotel.read.event.listeners.KafkaAddEventListener.lambda$onPartitionsAssigned$1(KafkaAddEventListener.java:171)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at hotel.read.event.listeners.KafkaAddEventListener.onPartitionsAssigned(KafkaAddEventListener.java:168)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:291)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
        at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:402)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by graemerocher** [comment]
Seems like we need a consumer thread per topic
