### ISSUE TITLE
Binding lowercase enum for error types with Micronaut HTTP Client

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#1830]
### Steps to Reproduce

1. Create a sample micronaut app

`mn create-app example.micronaut --inplace`

2. Create an enum for error codes: 

```java
package example;

public enum  ErrorCode {

    AUTHORIZATION_PENDING("authorization_pending"),
    SLOW_DOWN("slow_down"),
    EXPIRED_TOKEN("expired_token");

    private String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return this.code;
    }

    @Override
    public String toString() {
        return getCode();
    }
}
```

3. Create a controller: 

```java
package example;

import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

import java.util.Collections;

@Controller
public class HelloController {

    @Get
    public HttpResponse index() {
        return HttpResponse.badRequest(Collections.singletonMap("code", ErrorCode.AUTHORIZATION_PENDING.getCode()));
    }
}
```

when you go to `/` the controller responds: 

400 

```json
{"code":"authorization_pending"}
```

5. Create a declarative HTTP clients which declares an Error Type: 

```java
package example;

import io.micronaut.core.annotation.Introspected;

@Introspected
public class Error {

    private ErrorCode code;

    public Error() {

    }

    public Error(ErrorCode code) {
        this.code = code;
    }

    public ErrorCode getCode() {
        return code;
    }

    public void setCode(ErrorCode code) {
        this.code = code;
    }
}
```

```java
package example;

import io.micronaut.http.HttpStatus;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.client.annotation.Client;

@Client(value = "app", errorType = Error.class)
public interface AppClient {
    @Get
    HttpStatus index();
}

```

6. Create a test which verifies we can bind the error response of the controller to `Error`. 

```groovy
package example

import io.micronaut.context.ApplicationContext
import io.micronaut.core.io.socket.SocketUtils
import io.micronaut.core.type.Argument
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpStatus
import io.micronaut.http.client.BlockingHttpClient
import io.micronaut.http.client.HttpClient
import io.micronaut.http.client.exceptions.HttpClientResponseException
import io.micronaut.runtime.server.EmbeddedServer
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification

class ApplicationSpec extends Specification {
    @Shared
    int port = SocketUtils.findAvailableTcpPort()

    @AutoCleanup
    @Shared
    EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer, [
            'micronaut.server.port': port,
            'micronaut.http.services.app.url' : "http://localhost:$port".toString(),
    ])

    ApplicationContext getApplicationContext() {
        embeddedServer.applicationContext
    }

    void "bind lowercase enum with a declarative http client"() {
        when:
        AppClient client = applicationContext.getBean(AppClient)
        client.index()

        then:
        HttpClientResponseException e = thrown()
        e.status == HttpStatus.BAD_REQUEST

        when:
        Optional<Error> error = e.response.getBody(Error)

        then:
        error.isPresent()
        error.get().code == ErrorCode.AUTHORIZATION_PENDING
    }

    void "bind lowercase enum without declarative http client"() {
        given:
        HttpClient httpClient = applicationContext.getBean(HttpClient)
        BlockingHttpClient client = httpClient.toBlocking()

        when:
        Argument<?> okType = Argument.of(String)
        Argument<?> badType = Argument.of(Error)
        client.exchange(HttpRequest.GET("/"), okType, badType)

        then:
        HttpClientResponseException e = thrown()
        e.status == HttpStatus.BAD_REQUEST

        when:
        Error error = e.response.getBody(Error)

        then:
        error.code == ErrorCode.AUTHORIZATION_PENDING

        cleanup:
        httpClient.close()
    }
}
```

### Expected Behaviour

Test pass.

### Actual Behaviour

Both test fail with: 

```

2:06:05.924 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - connection: close
12:06:05.924 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Response Body
12:06:05.924 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - ----
12:06:05.924 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - {"code":"authorization_pending"}
12:06:05.925 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - ----
12:06:05.958 [nioEventLoopGroup-1-3] DEBUG i.m.http.client.DefaultHttpClient - Unable to decode response body using codec JsonMediaTypeCodec:Error decoding JSON stream for type [class example.Error]: Cannot deserialize value of type `example.ErrorCode` from String "authorization_pending": value not one of declared Enum instance names: [SLOW_DOWN, AUTHORIZATION_PENDING, EXPIRED_TOKEN]
 at [Source: (byte[])"{"code":"authorization_pending"}"; line: 1, column: 9] (through reference chain: example.Error["code"])
io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [class example.Error]: Cannot deserialize value of type `example.ErrorCode` from String "authorization_pending": value not one of declared Enum instance names: [SLOW_DOWN, AUTHORIZATION_PENDING, EXPIRED_TOKEN]
 at [Source: (byte[])"{"code":"authorization_pending"}"; line: 1, column: 9] (through reference chain: example.Error["code"])
	at io.micronaut.jackson.codec.JsonMediaTypeCodec.decode(JsonMediaTypeCodec.java:139)
	at io.micronaut.http.client.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:238)
	at io.micronaut.http.client.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:188)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.micronaut.http.client.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:166)
	at io.micronaut.http.client.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:136)
	at io.micronaut.http.client.exceptions.HttpClientResponseException.initResponse(HttpClientResponseException.java:93)
	at io.micronaut.http.client.exceptions.HttpClientResponseException.<init>(HttpClientResponseException.java:62)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1773)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1725)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `example.ErrorCode` from String "authorization_pending": value not one of declared Enum instance names: [SLOW_DOWN, AUTHORIZATION_PENDING, EXPIRED_TOKEN]
 at [Source: (byte[])"{"code":"authorization_pending"}"; line: 1, column: 9] (through reference chain: example.Error["code"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
	at io.micronaut.jackson.codec.JsonMediaTypeCodec.decode(JsonMediaTypeCodec.java:136)
	... 49 common frames omitted
```

### Environment Information

- **Operating System**: MacOS 10.14.5
- **Micronaut Version:** 1.2.0.RC1
- **JDK Version:** 1.8.0_191"

**Comment by sdelamo** [comment]
Adding ```yaml
jackson:
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
```
makes both test pass.

**Comment by schrek1** [comment]
set ACCEPT_CASE_INSENSITIVE_ENUMS in application yaml not working
