### ISSUE TITLE
Broken pipe on StreamingFileUpload with big file and @Secured annotation

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1852]
In `1.2.0.RC1` I'm trying to upload file as `StreamingFileUpload` to method secured by the `@Secured` annotation:

```java
@Controller("/")  // <2>
public class HomeController {

    @Post(consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
    @Secured("ROLE_NON_EXISTING")
    public Single<HttpResponse<String>> uploadPublic(StreamingFileUpload file) {
        return null; // never reached
    }
}
```

I'm logging the user in, but he has no `ROLE_NON_EXISTING` role, so the method should end up with 403 forbidden. And indeed it ends up this way for small files (for example a few bytes). Here is the result for 10 tries for `0123456789` string as a content:

```
15:45:53.697 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.731 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.772 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.813 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.852 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.883 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.904 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.918 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.933 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
15:45:53.945 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
```

But, when I try to uploaded bigger file, for example 7MB string, which is not received as a single packet from reactive upload, it sometimes ends up with 403 forbidden, but more often with "broken pipe" `IOException`. Here's the example for 7MB file:

```
15:42:21.853 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:21.916 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:21.981 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.033 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.117 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.186 [main] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException: Broken pipe
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
	at io.micronaut.http.client.DefaultHttpClient$NettyRequestWriter.lambda$closeChannel$0(DefaultHttpClient.java:2310)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.handler.stream.ChunkedWriteHandler$PendingWrite.fail(ChunkedWriteHandler.java:341)
	at io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:278)
	at io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:273)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:702)
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:294)
	at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:639)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:744)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:945)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:638)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:405)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	... 8 more
Exception in thread "nioEventLoopGroup-1-21" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException: Broken pipe
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
	at io.micronaut.http.client.DefaultHttpClient$NettyRequestWriter.lambda$closeChannel$0(DefaultHttpClient.java:2310)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.handler.stream.ChunkedWriteHandler$PendingWrite.fail(ChunkedWriteHandler.java:341)
	at io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:278)
	at io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:273)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:702)
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:294)
	at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:639)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:744)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:945)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:638)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:405)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	... 8 more
15:42:22.273 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.320 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.358 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
15:42:22.391 [main] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
```

I suppose there's some race condition here because the output is not always the same. It seems the pipe is closed by the first exception (403 forbidded by the security interceptor) what closes the pipe, but then another upload packet comes and the whole operation ends up with `IOException: Broken pipe`.

The expected fix is:
1. The server should always return 403 forbidden in both scenarios (small/large file upload).
1. If the security interceptor rejects the controller method processing, the pipe should probably be closed and no more upload packets should be accepted, but this should be done silently from the user perspective.

**Comment by l0co** [comment]
I'm including the isolated testcase [here](https://github.com/l0co/micronaut-1852).

**Comment by l0co** [comment]
This problem is now present again in `2.0.0.M3`. I've upgraded the related repository to this version and I can see this bug here:

```bash
$ ./gradlew --info clean test 2>&1 | grep "UploadTest"
jwt.upload.UploadTest > testBig() STANDARD_OUT
    12:32:10.700 [Test worker] INFO  jwt.upload.UploadTest - Beginning test with: 7340032 bytes
    12:32:12.315 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.402 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.457 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.516 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.575 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.652 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.684 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.712 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.738 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
    12:32:12.768 [Test worker] INFO  jwt.upload.UploadTest - RuntimeException: java.io.IOException: Broken pipe
jwt.upload.UploadTest > testSmall() STANDARD_OUT
    12:32:12.774 [Test worker] INFO  jwt.upload.UploadTest - Beginning test with: 10 bytes
    12:32:12.853 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.858 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.863 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.871 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.876 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.882 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.889 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.895 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.901 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden
    12:32:12.905 [Test worker] INFO  jwt.upload.UploadTest - HttpClientResponseException: Forbidden

```
