### ISSUE TITLE
Http Client sends empty GET params

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#1932]
As discussed on [Gitter](https://gitter.im/micronautfw/questions?at=5d39d92205f6321c1a95ac73):

The micronaut http client sends all properties of a pojo even if they are empty -> **http://localhost:8080/?type=&name=John**.
This causes an error (see [Stacktrace](#stacktrace)) when one of the empty properties is an enum. 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a pojo as command object with a String property and an `@Nullable` annotated enum property
```groovy
class TestCommand {
    @Nullable
    String name

    @Nullable
    MyEnum type
}
```
2. Create a declarative http client that uses the pojo as get command
```groovy
@Get("/{?req*}")
HttpResponse test(@Valid TestCommand req)
```
3. Create a controller as endpoint for the client
4. Use the client to send the pojo with a null value for the enum property
```groovy
client.test(new TestCommand(name: "John"))
```

### Expected Behaviour

The client only sends get params that aren't empty.
The controller doesn't crash

### Actual Behaviour

Client sends all properties of the pojo even if they are empty.
Controller crashes when trying to create an enum from an empty string.

#### Stacktrace
```java
09:50:35.543 [Test worker] ERROR i.m.r.intercept.RecoveryInterceptor - Type [net.safri.TestClient$Intercepted] executed with error: Failed to convert argument [type] for value [] due to: Cannot deserialize value of type `net.safri.Type` from String "": value not one of declared Enum instance names: [A, B]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: net.safri.TestCommand["type"])
io.micronaut.http.client.exceptions.HttpClientResponseException: Failed to convert argument [type] for value [] due to: Cannot deserialize value of type `net.safri.Type` from String "": value not one of declared Enum instance names: [A, B]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: net.safri.TestCommand["type"])
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1789)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1729)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.2.0.RC2
- **JDK Version:** openjdk version "11.0.3"

### Example Application

https://github.com/safri-net/mn-http-client-get-param-issue

**Comment by sascha-frinken** [comment]
@jameskleeh if you share my opinion that the client shouldn't send empty params and point me to the right (code) direction, I would try to find some time to write a PR

**Comment by jameskleeh** [comment]
@sascha-frinken Here is where the logic is that handles this case https://github.com/micronaut-projects/micronaut-core/blob/09a4b476aba1ec48ece58f5810721d2536e83018/http/src/main/java/io/micronaut/http/uri/UriTemplate.java#L929. I personally don't see the value in having it send an empty param, but perhaps that is valuable for some use cases. Any opinion on this @graemerocher ?
