### ISSUE TITLE
Controller methods returning a CompletableFuture cannot use a TenantResolver

### ISSUE THREAD

**Issue by benco03** [micronaut-projects/micronaut-core#1944]
### Task List

- [ x ] Steps to reproduce provided
- [ x ] Stacktrace (if present) provided
- [ x ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Issue 

The issue comes when using CompletableFutures as part of a controller while trying to also use the multitenancy features of Micronaut.

Attempting to use a web-based TenantResolver in the supplier method of a CompletableFuture will throw a TenantNotFound exception due to being 'outside a web request' with the following controller code:

```
@Get("/future")
    @Produces("text/plain")
    fun getFuture(): CompletableFuture<HttpResponse<String>> {
        return CompletableFuture.supplyAsync {
            HttpResponse.ok(tenantResolver.resolveTenantIdentifier().toString())
        }
    }
```

This is because all web-based TenantResolvers use the `ServerRequestContext`, which stores the current `HttpRequest` in a `ThreadLocal`, but the supplier method runs in a different thread.

I was wanting to use the TenantResolver in my applications' repository layer in order to select a database schema to use for multitenancy. 

### Steps to Reproduce

1. set up a subdomain by modifying /etc/hosts
`127.0.0.1          master.localhost`
1. `./gradlew run` the provided application
2. GET http://master.localhost:8080/test/future
4. GET http://master.localhost:8080/test/nofuture

### Expected Behaviour

Both endpoints should return 'master' in plaintext 

### Actual Behaviour

An exception occurs on the /future because the completable future supplier method has lost the ThreadLocal HttpRequest from the initial request

#### Stack Trace
```
java.util.concurrent.CompletionException: io.micronaut.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.micronaut.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request
        at io.micronaut.multitenancy.tenantresolver.SubdomainTenantResolver.lambda$resolveTenantIdentifier$0(SubdomainTenantResolver.java:42)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.micronaut.multitenancy.tenantresolver.SubdomainTenantResolver.resolveTenantIdentifier(SubdomainTenantResolver.java:42)
        at completable.future.multitenancy.test.TestController$get$1.get(TestController.kt:17)
        at completable.future.multitenancy.test.TestController$get$1.get(TestController.kt:11)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.1.4
- **JDK Version:** 1.8.0_171

### Example Application

https://github.com/benco03/completablefuture-multitenancy-bug

**Comment by jameskleeh** [comment]
I think there should be public methods on the resolvers that use a request to take in the request instead of exclusively relying on the context

**Comment by graemerocher** [comment]
The `CompletableFuture.supplyAsync` method uses the ForkJoin pool which is designed for short lived non-blocking tasks. It is also not a thread pool we instrument to include the request as its use should generally be avoided in application code. You should use the `supplyAsync` variation that takes an `executor` and pass in Micronaut's IO thread pool that you can inject with: `@Inject @Named(TaskExecutors.IO) ExecutorService executor`

See https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#supplyAsync-java.util.function.Supplier-java.util.concurrent.Executor-

**Comment by benco03** [comment]
Can confirm that using supplyAsync with the Micronaut 'IO' thread pool fixed this issue. Thanks @graemerocher!

Working example:

```
@Controller("/test")
    class TestController(
        @Named(TaskExecutors.IO) private val executor: ExecutorService,
        private val tenantResolver: TenantResolver
    ) {

        @Get("/future")
        @Produces("text/plain")
        fun getFuture(): CompletableFuture<HttpResponse<String>> {
            return CompletableFuture.supplyAsync(Supplier<HttpResponse<String>> {
                HttpResponse.ok(tenantResolver.resolveTenantIdentifier().toString())
            }, executor)
        }
}
```
