### ISSUE TITLE
Error when executing some CLI commands

### ISSUE THREAD

**Issue by rubensyltek** [micronaut-projects/micronaut-core#196]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Below commands do not work

mn create-app myapp
mn help

### Steps to Reproduce

1. clone & build micronaut-core
2. clone & build micronaut-profiles
3. nm create-app mail-service

### Expected Behaviour

A micronaut service is created

### Actual Behaviour

| Error Error occurred running Micronaut CLI: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 4, column 16:
    testFramework: @testFramework@
                   ^

while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 4, column 16:
    testFramework: @testFramework@
                   ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:421)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547)
	at io.micronaut.cli.config.CodeGenConfig.loadYml(CodeGenConfig.groovy:135)
	at io.micronaut.cli.config.CodeGenConfig$_loadYml_closure1.doCall(CodeGenConfig.groovy:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at groovy.lang.Closure.call(Closure.java:437)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1191)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1878)
	at io.micronaut.cli.config.CodeGenConfig.loadYml(CodeGenConfig.groovy:126)
	at io.micronaut.cli.MicronautCli.loadApplicationConfig(MicronautCli.groovy:507)
	at io.micronaut.cli.MicronautCli.initializeApplication(MicronautCli.groovy:281)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:259)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:158)
| Error Error occurred running Micronaut CLI: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 4, column 16:
    testFramework: @testFramework@

### Environment Information

- **Operating System**: Mac / zsh
- **Micronaut Version:** Master
- **JDK Version:** java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by jameskleeh** [comment]
I can't reproduce this on the latest core and profiles. My micronaut-cli.yml looks like:

```
profile: service
defaultPackage: foo
---
testFramework: junit
sourceLanguage: java
```

**Comment by sescotti** [comment]
I just had the same error, it happened while trying to execute `create-app hello-world` using the interactive mode. It doesn't print any error on the console and when I try to stop it I get a  'Stopping build. Please wait...' message and it just stays like that. I had to close the terminal and open a new one, so the `micronaut.yml` file is still there and I can't create any other project until I delete it.

### Environment Information
- Operating System: Mac / bash
- Micronaut Version: Master
- java version "1.8.0_121"
- Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Hope this helps!

**Comment by ZacharyKlein** [comment]
@sescotti so the "Stopping build." message and delay is definitely not expected behavior. However, the missing `hello-world` directory is not a bug. 

When you create a project via the `mn>` interactive shell, it will be created in the current directory, *not within a new directory*. The name of the project will be written to the `micronaut-application.name` config property and the default package will be set based on that name. It is the same behavior as if you had run:
```
> mn create-app hello-world -inplace
```

I'm not particularly happy with that behavior myself, but it's intentional. Personally I think a new project directory should always be the default unless the `inplace` flag is present. cc @jameskleeh

**Comment by sescotti** [comment]
@ZacharyKlein thanks for the clarification! I was double checking and indeed, I noticed that all the files/directories were created in the same directory (maybe some deadlock trying to acquire write permissions for some particular file?). Hope at least my case could give you a hint of why the cli is failing.

**Comment by rubensyltek** [comment]
I removed the micronaut-cli.yml and tried again without using the interactive shell and it worked properly. 

I guess it's a problem with the interactive shell then

**Comment by Solido** [comment]
Been using the github build and now the sdk man and just fall on the same trap !

**Comment by jameskleeh** [comment]
I can't reproduce the issue. If you come across it with M2 (released soon), please debug the CLI with `export MN_OPTS="-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"` and report what you find
