### ISSUE TITLE
No status routes in DefaultRouter

### ISSUE THREAD

**Issue by vasigorc** [micronaut-projects/micronaut-core#1982]
Whenever a `@Body` annotated object is missing from an endpoint's payload, an `UnsatisfiedRouteException` is being thrown which is expected (see stacktrace at the bottom). However inside the `RoutingInBoundHandler` the correct `errorRoute` cannot be identified:
```
        if (cause instanceof UnsatisfiedRouteException) {
            if (declaringType != null) {
                errorRoute = (RouteMatch)this.router.route(declaringType, HttpStatus.BAD_REQUEST).orElse((Object)null);
            }

            if (errorRoute == null) {
                errorRoute = (RouteMatch)this.router.route(HttpStatus.BAD_REQUEST).orElse((Object)null);
            }
```

The reason seems to be because `statusRoutes` inside `DefaultRouter` is empty (as observed in debug mode). This ultimately ends-up in server throwing a 500 instead of 400. Is there anything that I forgot to configure?

```
io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [MyDTO myDto] not specified
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:279)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1348)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by jameskleeh** [comment]
Please ask questions in [gitter](https://gitter.im/micronautfw/). If you want to handle that exception you should register a an error route or an exception handler. https://docs.micronaut.io/latest/guide/index.html#runningServer "6.13 Error Handling"

**Comment by jameskleeh** [comment]
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1594
