### ISSUE TITLE
Return void from function client's method causes exception

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#2024]
### Steps to Reproduce

1. Create a new function
2. Change the signature of the function to return `void`
3. Create function client for the function with method also returning `void`
4. Call the function using the newly created client

### Expected Behaviour

No exception is thrown and the function is called.

### Actual Behaviour

The function is called but then an exception is thrown:

```
09:17:17.708 [main] ERROR io.micronaut.retry.intercept.RecoveryInterceptor - Type [micronaut.function.problems.MicronautFunctionProblemsClient$Intercepted] executed with error: Empty body
io.micronaut.http.client.exceptions.HttpClientResponseException: Empty body
	at io.micronaut.http.client.BlockingHttpClient.lambda$retrieve$0(BlockingHttpClient.java:140) ~[micronaut-http-client-1.2.0.jar:1.2.0]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:140) ~[micronaut-http-client-1.2.0.jar:1.2.0]
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:116) ~[micronaut-http-client-1.2.0.jar:1.2.0]
	at io.micronaut.function.client.http.HttpFunctionExecutor.invoke(HttpFunctionExecutor.java:121) ~[micronaut-function-client-1.2.0.jar:1.2.0]
	at io.micronaut.function.client.aop.FunctionClientAdvice.intercept(FunctionClientAdvice.java:97) ~[micronaut-function-client-1.2.0.jar:1.2.0]
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40) ~[micronaut-aop-1.2.0.jar:1.2.0]
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:150) ~[micronaut-aop-1.2.0.jar:1.2.0]
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:73) [micronaut-runtime-1.2.0.jar:1.2.0]
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40) [micronaut-aop-1.2.0.jar:1.2.0]
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:150) [micronaut-aop-1.2.0.jar:1.2.0]
	at micronaut.function.problems.MicronautFunctionProblemsClient$Intercepted.sendVoid(Unknown Source) [classes/:?]
	at micronaut.function.problems.MicronautFunctionProblemsClient$sendVoid$1.call(Unknown Source) [classes/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) [groovy-2.5.6.jar:2.5.6]
	at micronaut.function.problems.MicronautFunctionProblemsFunctionSpec.$spock_feature_0_2(MicronautFunctionProblemsFunctionSpec.groovy:41) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:200) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:113) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:408) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:322) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:306) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:285) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:275) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:266) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:260) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:243) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:235) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63) [spock-core-1.2-groovy-2.5.jar:1.2]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]

```

### Environment Information

- **Operating System**: Darwin
- **Micronaut Version:** 1.2.0
- **JDK Version:** Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

### Example Application

https://github.com/musketyr/micronaut-function-problems

see `micronaut.function.problems.MicronautFunctionProblemsFunctionSpec#with void`

**Comment by blazejkarmelita** [comment]
Hi there. Any update on this one?

**Comment by timyates** [comment]
Hi @musketyr 👋 

Is this still an issue with Micronaut 3?

For testing `Consumer` `FunctionalBean`s with `Client` you should just need `micronaut-function-web`

**Comment by musketyr** [comment]
Hi @timyates,

Will check next week and let you know,
Thanks!

**Comment by musketyr** [comment]
@timyates the problem still persist but the error looks bit differently

```
09:34:16.444 [Test worker] ERROR io.micronaut.retry.intercept.RecoveryInterceptor - Type [micronaut.function.problems.MicronautFunctionProblemsClient$Intercepted] executed with error: null
java.lang.NullPointerException: null
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:144) ~[micronaut-http-client-core-3.2.6.jar:3.2.6]
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:122) ~[micronaut-http-client-core-3.2.6.jar:3.2.6]
	at io.micronaut.function.client.http.HttpFunctionExecutor.invoke(HttpFunctionExecutor.java:92) ~[micronaut-function-client-3.2.6.jar:3.2.6]
	at io.micronaut.function.client.aop.FunctionClientAdvice.intercept(FunctionClientAdvice.java:93) ~[micronaut-function-client-3.2.6.jar:3.2.6]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.2.6.jar:3.2.6]
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92) ~[micronaut-runtime-3.2.6.jar:3.2.6]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.2.6.jar:3.2.6]
	at micronaut.function.problems.MicronautFunctionProblemsClient$Intercepted.sendVoid(Unknown Source) ~[test/:?]
	at micronaut.function.problems.MicronautFunctionProblemsClient$sendVoid$1.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.9.jar:3.0.9]
	at micronaut.function.problems.MicronautFunctionProblemsFunctionSpec.$spock_feature_0_2(MicronautFunctionProblemsFunctionSpec.groovy:39) ~[test/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:198) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.model.MethodInfo.lambda$new$0(MethodInfo.java:47) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:102) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$null$1(MicronautSpockExtension.java:79) ~[micronaut-test-spock-3.0.5.jar:3.0.5]
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:400) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.runFeatureMethod(PlatformSpecRunner.java:326) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.IterationNode.execute(IterationNode.java:48) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:58) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:15) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.IterationNode.lambda$around$0(IterationNode.java:63) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunIteration$5(PlatformSpecRunner.java:238) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:409) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.runIteration(PlatformSpecRunner.java:220) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.IterationNode.around(IterationNode.java:63) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SimpleFeatureNode.lambda$around$0(SimpleFeatureNode.java:52) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.FeatureNode.lambda$around$0(FeatureNode.java:29) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:201) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:102) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$null$0(MicronautSpockExtension.java:70) ~[micronaut-test-spock-3.0.5.jar:3.0.5]
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:400) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.runFeature(PlatformSpecRunner.java:194) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.FeatureNode.around(FeatureNode.java:29) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:52) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:15) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SpecNode.lambda$around$0(SpecNode.java:63) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:61) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:409) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:55) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:63) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:11) ~[spock-core-2.0-groovy-3.0.jar:2.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202) [junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181) [junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) [junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102) [gradle-testing-junit-platform-5.5.jar:5.5]
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82) [gradle-testing-junit-platform-5.5.jar:5.5]
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78) [gradle-testing-junit-platform-5.5.jar:5.5]
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61) [gradle-testing-base-5.5.jar:5.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-5.5.jar:5.5]
	at com.sun.proxy.$Proxy2.stop(Unknown Source) [?:?]
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132) [gradle-testing-base-5.5.jar:5.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) [gradle-messaging-5.5.jar:5.5]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-5.5.jar:5.5]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-5.5.jar:5.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-5.5.jar:5.5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

java.lang.NullPointerException
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:144)
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:122)
	at io.micronaut.function.client.http.HttpFunctionExecutor.invoke(HttpFunctionExecutor.java:92)
	at io.micronaut.function.client.aop.FunctionClientAdvice.intercept(FunctionClientAdvice.java:93)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at micronaut.function.problems.MicronautFunctionProblemsFunctionSpec.with void(MicronautFunctionProblemsFunctionSpec.groovy:39)

```

I've updated the test repo to the latest version

**Comment by timyates** [comment]
Awesome, thanks for that 😀👍

I've raise a PR to hopefully fix it
