### ISSUE TITLE
Error running multiple controller Spock tests

### ISSUE THREAD

**Issue by jpragma** [micronaut-projects/micronaut-core#2052]
### Steps to Reproduce

1. Using CLI create new app (Groovy or Java) with Spock as testing framework 
2. Using CLI create controller - MyTestController
3. Open MyTestControllerSpec.groovy
4. Create 2nd test method, e.g. simply copy **void "test index"()**  to **void "test index 2"()**
5. Execute ./gradlew build

### Expected Behaviour

Expecting tests to pass

### Actual Behaviour

2nd test fails with following stack trace
```
io.micronaut.http.client.exceptions.HttpClientException: Connect Error: executor not accepting a task
	at io.micronaut.http.client.DefaultHttpClient.lambda$null$26(DefaultHttpClient.java:1038)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:233)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:50)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:184)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:170)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:982)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:505)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:196)
	... 21 more
```

### Solution
Add `@Shared` annotation to the instance of RxHttpClient. Perhaps CLI should be updated to add the required annotation by default.

### Environment Information

- **Operating System**: Mac OSX 10.14.6
- **Micronaut Version:** 1.2.0
- **JDK Version:** 1.8.0_181

### Example Application
N/A

**Comment by jameskleeh** [comment]
Are you saying the CLI generated the test? If so what command did you run to generate it?
