### ISSUE TITLE
CompletableFuturePublisher doesn't handle exception from the future supplier what hangs a request

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#2054]
In 1.2.0.

When I send a GraphQL request with invalid data (in my example I'm trying to set "abc" string to `UUID` field) the request **hangs infinitely** with the following exception:

<details><summary>See the exception</summary>
<p>

```
17:22:47.389 [nioEventLoopGroup-1-2] WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker@429a837d
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
	at io.reactivex.Flowable.subscribe(Flowable.java:14927)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:133)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:133)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onComplete(InstrumentedSubscriber.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onComplete(InstrumentedSubscriber.java:112)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onComplete(MaybeToFlowable.java:80)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:92)
	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onComplete(MaybeDoOnEvent.java:115)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:92)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onComplete(FlowableElementAtMaybe.java:102)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onComplete(InstrumentedSubscriber.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onComplete(InstrumentedSubscriber.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:255)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onSubscribe(InstrumentedSubscriber.java:75)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:64)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:64)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: abc
	at java.base/java.util.UUID.fromString(UUID.java:215)
	at io.leangen.graphql.util.Scalars$1.parseLiteral(Scalars.java:95)
	at graphql.validation.ValidationUtil.parseLiteral(ValidationUtil.java:113)
	at graphql.validation.ValidationUtil.isValidLiteralValue(ValidationUtil.java:90)
	at graphql.validation.ValidationUtil.isValidLiteralValue(ValidationUtil.java:86)
	at graphql.validation.rules.ArgumentsOfCorrectType.checkArgument(ArgumentsOfCorrectType.java:23)
	at graphql.validation.RulesVisitor.checkArgument(RulesVisitor.java:98)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:65)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:33)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:28)
	at graphql.validation.Validator.validateDocument(Validator.java:43)
	at graphql.GraphQL.validate(GraphQL.java:576)
	at graphql.GraphQL.parseAndValidate(GraphQL.java:541)
	at graphql.GraphQL.lambda$parseValidateAndExecute$3(GraphQL.java:515)
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.get(NoOpPreparsedDocumentProvider.java:11)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:511)
	at graphql.GraphQL.executeAsync(GraphQL.java:495)
	at io.micronaut.configuration.graphql.DefaultGraphQLInvocation.lambda$null$0(DefaultGraphQLInvocation.java:69)
	at io.micronaut.core.async.publisher.CompletableFuturePublisher$CompletableFutureSubscription.request(CompletableFuturePublisher.java:75)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
	at io.micronaut.core.async.publisher.CompletableFuturePublisher.subscribe(CompletableFuturePublisher.java:48)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.lambda$onNext$0(InstrumentedSubscriber.java:80)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onNext(InstrumentedSubscriber.java:84)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher$1.request(Publishers.java:340)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
	at io.micronaut.reactive.rxjava2.InstrumentedSubscriber.onSubscribe(InstrumentedSubscriber.java:75)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher.subscribe(Publishers.java:330)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	... 102 common frames omitted
```

</p>
</details>

Looking on `DefaultGraphQLInvocation` from Micronaut:

```java
    @Override
    public Publisher<ExecutionResult> invoke(GraphQLInvocationData invocationData, HttpRequest httpRequest) {
        ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .query(invocationData.getQuery())
                .operationName(invocationData.getOperationName())
                .variables(invocationData.getVariables())
                .build();
        return Flowable.fromPublisher(graphQLExecutionInputCustomizer.customize(executionInput, httpRequest))
                .flatMap(customizedExecutionInput -> Publishers.fromCompletableFuture(() ->
                        graphQL.executeAsync(customizedExecutionInput)));
    }
```

The cause seems to be an unhandled exception thrown in `CompletableFuturePublisher` supplier (`() -> graphQL.executeAsync(customizedExecutionInput)` code from the example above). When the exception is thrown there, and in GraphQL it can apparently can be thrown there in case of validation/deserialization issues, the request is hung infinitely.

I prepared a testcase [here](https://github.com/l0co/micronaut-playground/tree/completable-future-publisher), please review the code from [this controller](https://github.com/l0co/micronaut-playground/blob/completable-future-publisher/src/main/java/micronaut/general/TestController.java), and try to GET `/error`:

```bash
$ curl -m 5 http://localhost:8080/error
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
```

Request is hung (timeout happens) with the following log:

```
17:32:24.133 [nioEventLoopGroup-1-4] WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.micronaut.http.netty.reactive.HandlerSubscriber$$Lambda$424/128773606@5a93364c
java.lang.IllegalArgumentException: null
	at micronaut.general.TestController.lambda$exceptionFlow$1(TestController.java:25)
	at io.micronaut.core.async.publisher.CompletableFuturePublisher$CompletableFutureSubscription.request(CompletableFuturePublisher.java:75)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at io.micronaut.http.netty.reactive.HandlerSubscriber.maybeRequestMore(HandlerSubscriber.java:216)
	at io.micronaut.http.netty.reactive.HandlerSubscriber.maybeStart(HandlerSubscriber.java:260)
	at io.micronaut.http.netty.reactive.HandlerSubscriber.provideSubscription(HandlerSubscriber.java:247)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by l0co** [comment]
Note, this is not a bug in micronaut-graphql, I've just reproduced it there. This is the bug in micronaut-core.

**Comment by jameskleeh** [comment]
I don't think this is a bug. You should not be throwing an exception from the future supplier:

```
Publishers.fromCompletableFuture(() -> {
    //always return a future, never an exception
}));
```

You can argue we could improve this to automatically do that for you

**Comment by jameskleeh** [comment]
In general its a common practice that any methods that return async/reactive types will not throw exceptions directly, but instead emit them through the reactive flow

**Comment by l0co** [comment]
Do it not for me, do it for GraphQL authors who apparently throw such exception from `GraphQL.executeAsync()`. I'm just an user of both MIcronaut and GraphQL. From this perspective currently GraphQL integration in Micronaut doesn't work and in case of deserialization issues hangs with infinite request.

**Comment by jameskleeh** [comment]
@l0co It does work, you just have to catch the exception yourself. This is not a problem that can only be solved at the framework level

For example:
```
Publishers.fromCompletableFuture(() -> {
    try {
        return graphQL.executeAsync(customizedExecutionInput);
    } catch (Throwable e) {
        CompletableFuture cf = new CompletableFuture();
        cf.completeExceptionally(e);
        return cf;
    }
})

**Comment by l0co** [comment]
I understand that, but I cannot alter this way the original code causing the problem, which is `DefaultGraphQLInvocation.invoke()`.

**Comment by l0co** [comment]
1.3.0 seems to be a little distant, couldn't this simple fix go to 1.2.1?

**Comment by jameskleeh** [comment]
@l0co Then you should file an issue here https://github.com/micronaut-projects/micronaut-graphql to get that changed

**Comment by l0co** [comment]
@jameskleeh Yup, but now we have the fix who rules all the others :)

**Comment by jameskleeh** [comment]
@l0co It does not rule for users using Micronaut prior to 1.3. I created https://github.com/micronaut-projects/micronaut-graphql/issues/21. This is an improvement and thus cannot go in a patch release according to semantic versioning. We don't follow it 100% of the time but this is a workaround for other bad behavior so it does not warrant breaking the versioning specification in my opinion.

**Comment by l0co** [comment]
OK. Anyway thanks for resolving.

I can always patch it locally with overwritten micronaut classes in the same packages, but coming from the project sources. Just need to remember to remove them after new Micronaut release. Not first and not last such Micronaut workaround in the project :D

**Comment by jameskleeh** [comment]
You definitely should not have to do that. Micronaut has features in place to override beans, which the invocation class is. See `@Replaces`

**Comment by l0co** [comment]
Don't worry. I've already been sitting in Micronaut for 6 months or so, and previously over 10 in Spring. And I'm not just a documentation reader, I like to see thing beneath, how they works.

This is the obvious thing you're talking about. And indeed this scenario can be solved with replacing the bean. But not all things can be done this way. For example if you have a bug in `@Internal` API I report it as a bug, but at the same time I make a fix for the project in the way I've described above, which is then removed after the release. Releases are too seldom in my opinion. For such an immature thing as Micronaut is (for now) it would be useful to have some nightly builds.

Don't think I'm a grumbler. I really appreciate the framework. There's a noticeable boost in proportion to Spring which has recently become overloaded. Your framework is the one I like the most at the time, and I don't see a real competitor after you make it stable and mature.

Just see some dead ends in RX and those concepts, like this one:

```java
NullPointerException npe = new NullPointerException("Actually not, but can't throw other exceptions due to RS");
```

But, I'm curious where will that go, dragging java to nodejs execution model. Rescuing some MBs of RAM to have less threads and the event loop instead, for the cost of making the code 4x more complex, stacktraces undreadable, exceptions which cannot be anymore handled in the standard way (speaking about the problem from this ticket). In a nutshell: making expensive developer a lot more expensive, and the cheap iron a little more cheap. Wondering if this is the right way :D

Cheers ;)

**Comment by jameskleeh** [comment]
> it would be useful to have some nightly builds

A snapshot build is published for every commit that the build passes for

As far as the other points, that is outside the scope of this issue, but yes there are definitely tradeoffs.

**Comment by l0co** [comment]
That's great. After migration to micronaut-graphql 1.2.1 the exception is properly thrown from the service. Thanks!

**Comment by marceloverdijk** [comment]
@l0co Thx for confirming it works now as expected, and thx again for raising the issue in the first place.
