### ISSUE TITLE
Consul support for Graal broken in 1.3.0.BUILD-SNAPSHOT because of Cache

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2137]
I've updated the Consul Graal test application to Micronaut 1.3.0.BUILD-SNAPSHOT and it fails.

To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-service-discovery-consul-http-client`
- `cd micronaut-service-discovery-consul-http-client`
- Use GraalVM 19.2.0.1: `sdk use java 19.2.0.1-grl`
- Install `native-image` command: `gu install native-image`
- `./build-native-image.sh`
- The native image is created properly
- Start consul: `docker run -it --rm -p 8500:8500 consul`
- Send the following request: `curl localhost:8080/api/hello/Micronaut`

At the end of the stacktrace there is this `Caused by: java.lang.NoClassDefFoundError: com.github.benmanes.caffeine.cache.Cache`. I'm not really sure but maybe this is related to the fact that the cache module has been moved out of micronaut-core.

This is the error:
```
13:17:49.409 [pool-2-thread-2] ERROR i.m.r.intercept.RecoveryInterceptor - Type [example.micronaut.HelloClient$Intercepted] executed with error: Error instantiating bean of type  [io.micronaut.cache.DefaultCacheManager]

Message: com.github.benmanes.caffeine.cache.Cache
Path Taken: new DiscoveryClientLoadBalancerFactory([DiscoveryClient discoveryClient]) --> new $CachingCompositeDiscoveryClientDefinition$Intercepted(DiscoveryClient[] discoveryClients,BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.cache.DefaultCacheManager]

Message: com.github.benmanes.caffeine.cache.Cache
Path Taken: new DiscoveryClientLoadBalancerFactory([DiscoveryClient discoveryClient]) --> new $CachingCompositeDiscoveryClientDefinition$Intercepted(DiscoveryClient[] discoveryClients,BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1585)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1042)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:989)
	at io.micronaut.cache.interceptor.$CacheInterceptorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2604)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2501)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:882)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1096)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1734)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1091)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:963)
	at io.micronaut.discovery.client.$$CachingCompositeDiscoveryClientDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2048)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1950)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1042)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:989)
	at io.micronaut.http.client.loadbalance.$DiscoveryClientLoadBalancerFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:584)
	at io.micronaut.http.client.DefaultLoadBalancerResolver.resolveLoadBalancerForServiceID(DefaultLoadBalancerResolver.java:125)
	at io.micronaut.http.client.DefaultLoadBalancerResolver.resolve(DefaultLoadBalancerResolver.java:111)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$getClient$20(HttpClientIntroductionAdvice.java:648)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.getClient(HttpClientIntroductionAdvice.java:637)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:160)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:73)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
	at example.micronaut.HelloClient$Intercepted.sayHi(Unknown Source)
	at example.micronaut.GatewayController.sayHi(GatewayController.java:17)
	at example.micronaut.$GatewayControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2815)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:294)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$18(RoutingInBoundHandler.java:1425)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:63)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoClassDefFoundError: com.github.benmanes.caffeine.cache.Cache
	at io.micronaut.cache.$DefaultSyncCacheDefinition.getTypeArgumentsMap(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.getTypeArguments(AbstractBeanDefinition.java:211)
	at io.micronaut.inject.DelegatingBeanDefinition.getTypeArguments(DelegatingBeanDefinition.java:167)
	at io.micronaut.inject.BeanDefinition.getTypeArguments(BeanDefinition.java:193)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:205)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:217)
	at io.micronaut.context.DefaultBeanContext$BeanKey.<init>(DefaultBeanContext.java:2840)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1501)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2604)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2524)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:882)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1096)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1734)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1091)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:966)
	at io.micronaut.cache.$DefaultCacheManagerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	... 79 common frames omitted
13:17:49.410 [pool-2-thread-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.cache.DefaultCacheManager]

Message: com.github.benmanes.caffeine.cache.Cache
Path Taken: new DiscoveryClientLoadBalancerFactory([DiscoveryClient discoveryClient]) --> new $CachingCompositeDiscoveryClientDefinition$Intercepted(DiscoveryClient[] discoveryClients,BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.cache.DefaultCacheManager]

Message: com.github.benmanes.caffeine.cache.Cache
Path Taken: new DiscoveryClientLoadBalancerFactory([DiscoveryClient discoveryClient]) --> new $CachingCompositeDiscoveryClientDefinition$Intercepted(DiscoveryClient[] discoveryClients,BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1585)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1042)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:989)
	at io.micronaut.cache.interceptor.$CacheInterceptorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2604)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2501)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:882)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1096)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1734)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1091)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:963)
	at io.micronaut.discovery.client.$$CachingCompositeDiscoveryClientDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2048)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1950)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1042)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:989)
	at io.micronaut.http.client.loadbalance.$DiscoveryClientLoadBalancerFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:584)
	at io.micronaut.http.client.DefaultLoadBalancerResolver.resolveLoadBalancerForServiceID(DefaultLoadBalancerResolver.java:125)
	at io.micronaut.http.client.DefaultLoadBalancerResolver.resolve(DefaultLoadBalancerResolver.java:111)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$getClient$20(HttpClientIntroductionAdvice.java:648)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.getClient(HttpClientIntroductionAdvice.java:637)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:160)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:73)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
	at example.micronaut.HelloClient$Intercepted.sayHi(Unknown Source)
	at example.micronaut.GatewayController.sayHi(GatewayController.java:17)
	at example.micronaut.$GatewayControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2815)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:294)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$18(RoutingInBoundHandler.java:1425)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:63)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoClassDefFoundError: com.github.benmanes.caffeine.cache.Cache
	at io.micronaut.cache.$DefaultSyncCacheDefinition.getTypeArgumentsMap(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.getTypeArguments(AbstractBeanDefinition.java:211)
	at io.micronaut.inject.DelegatingBeanDefinition.getTypeArguments(DelegatingBeanDefinition.java:167)
	at io.micronaut.inject.BeanDefinition.getTypeArguments(BeanDefinition.java:193)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:205)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:217)
	at io.micronaut.context.DefaultBeanContext$BeanKey.<init>(DefaultBeanContext.java:2840)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1501)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2604)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2524)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:882)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1096)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1734)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1091)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:966)
	at io.micronaut.cache.$DefaultCacheManagerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
	... 79 common frames omitted

```

**Comment by jameskleeh** [comment]
This is because the new cache project is not relocating the cache to our package like it used to in the main repo @alvarosanchez

**Comment by ilopmar** [comment]
So it's @alvarosanchez's fault :rofl:

**Comment by ilopmar** [comment]
It seems that there is something missing in micronaut-cache after this was fixed because the build is failing while publishing the snapshot version.

**Comment by ilopmar** [comment]
Thanks @jameskleeh for the fix in micronaut-cache. The GraalVM test now passes again on Gitlab CI
