### ISSUE TITLE
Problem with JDBC-Hikari

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#2224]
Hi,

Following the [example-jpa](https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa) I was able to build a native image of my application. For it, I was using 
```
implementation "io.micronaut.configuration:micronaut-jdbc-tomcat"
```

However, when I replaced to
```
implementation "io.micronaut.configuration:micronaut-jdbc-hikari"
```

I am getting the following exception
```
[main] ERROR com.zaxxer.hikari.pool.HikariPool - null - Error thrown while acquiring connection from data source
java.lang.NullPointerException: null
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:36)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:67)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.data.hibernate.runtime.$DataEntityManagerFactoryBean$HibernateStandardServiceRegistry0Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateMetadataSources1Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1900)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1274)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2458)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:202)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
        at com.mycompany.micronautbookapi.Application.main(Application.java:14)
21:32:11.225 [main] ERROR com.zaxxer.hikari.pool.HikariPool - null - Exception during pool initialization.
java.lang.NullPointerException: null
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:36)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:67)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.data.hibernate.runtime.$DataEntityManagerFactoryBean$HibernateStandardServiceRegistry0Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateMetadataSources1Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1900)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1274)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2458)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:202)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
        at com.mycompany.micronautbookapi.Application.main(Application.java:14)
21:32:11.226 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.boot.registry.StandardServiceRegistry]

Message: Failed to initialize pool: null
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder]) --> SessionFactoryBuilder.hibernateSessionFactoryBuilder([MetadataSources metadataSources],ValidatorFactory validatorFactory) --> MetadataSources.hibernateMetadataSources(JpaConfiguration jpaConfiguration,[StandardServiceRegistry standardServiceRegistry]) --> StandardServiceRegistry.hibernateStandardServiceRegistry(String dataSourceName,[DataSource dataSource])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.boot.registry.StandardServiceRegistry]

Message: Failed to initialize pool: null
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder]) --> SessionFactoryBuilder.hibernateSessionFactoryBuilder([MetadataSources metadataSources],ValidatorFactory validatorFactory) --> MetadataSources.hibernateMetadataSources(JpaConfiguration jpaConfiguration,[StandardServiceRegistry standardServiceRegistry]) --> StandardServiceRegistry.hibernateStandardServiceRegistry(String dataSourceName,[DataSource dataSource])
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1276)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2458)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:202)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
        at com.mycompany.micronautbookapi.Application.main(Application.java:14)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.boot.registry.StandardServiceRegistry]

Message: Failed to initialize pool: null
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder]) --> SessionFactoryBuilder.hibernateSessionFactoryBuilder([MetadataSources metadataSources],ValidatorFactory validatorFactory) --> MetadataSources.hibernateMetadataSources(JpaConfiguration jpaConfiguration,[StandardServiceRegistry standardServiceRegistry]) --> StandardServiceRegistry.hibernateStandardServiceRegistry(String dataSourceName,[DataSource dataSource])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1636)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.data.hibernate.runtime.$DataEntityManagerFactoryBean$HibernateStandardServiceRegistry0Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateMetadataSources1Definition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1975)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1094)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
        at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2319)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1900)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1274)
        ... 8 common frames omitted
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:36)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:67)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1610)
        ... 45 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        ... 52 common frames omitted
```

Best regards

**Comment by graemerocher** [comment]
I closed the wrong issue 🤦‍♂️
