### ISSUE TITLE
Micronaut 1.2.4 and jdbc-tomcat: DB pool exhausted

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2242]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Micronaut 1.2.4 app with JPA, jdbc-tomcat and Spock
2. Use Spock's PollingConditions to wait for some time +20 seconds

### Expected Behaviour

The test should fail because the condition is not met.

### Actual Behaviour

The test continuous queries to the db exhaust all the connections that are not released and there is an `org.apache.tomcat.jdbc.pool.PoolExhaustedException`.

```
userRepository.findAll().size() > 0
|              |
|              org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: 
<jdbc.tomcat.pool.$UserRepositoryImplDefinition$Intercepted@6d671ec2 $interceptors=[[io.micronaut.spring.tx.annotation.TransactionInterceptor@4c697ec4]] $proxyMethods=[List findAll()] session=io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$CurrentSession4Definition$Intercepted@b02278c>

	at jdbc.tomcat.pool.UserRepositoryImplSpec.test polling conditions_closure1(UserRepositoryImplSpec.groovy:31)
	at jdbc.tomcat.pool.UserRepositoryImplSpec.test polling conditions_closure1(UserRepositoryImplSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:405)
	at spock.util.concurrent.PollingConditions.within(PollingConditions.java:158)
	... 2 more
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: 
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:581)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:475)
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.intercept(TransactionInterceptor.java:75)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	... 6 more
Caused by: org.hibernate.TransactionException: JDBC begin transaction failed: 
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:73)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:259)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)
	at org.hibernate.internal.AbstractSharedSessionContract.beginTransaction(AbstractSharedSessionContract.java:467)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:536)
	... 10 more
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [Test worker] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:100; busy:100; idle:0; lastwait:30000].
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:717)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:226)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:67)
	... 15 more
```

### More information

This was not happening with Micronaut 1.2.3. The workaround mentioned here
https://github.com/micronaut-projects/micronaut-core/issues/2227#issuecomment-542627313 doesn't work either.

The test defines a 20 secods timeout for polling conditions. With a lower value it doesn't fail like this.
If you run the test from IntelliJ you can see the at some point the scroll bar stops moving and it actually takes more than 20 seconds for the test to fail.

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 1.2.4
- **JDK Version:** 1.8

### Example Application

https://github.com/ilopmar/mn-124-jdbc-tomcat-issue

**Comment by graemerocher** [comment]
The sample is still using `micronaut-hibernate-jpa` version `1.2.2` updating to `1.2.3.BUILD-SNAPSHOT` resolves the issue. I guess the `micronaut.sql.version=..` syntax only work with the spring dependency management plugin but not with Gradle's built in BOM support
