### ISSUE TITLE
NPE Thrown from RxHttpClient for some host hames with dashes and or dots

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#2283]
I think this is related to the host name similar to #1806 

This is only happening on the build server and not locally.  I am trying to get this test breaking locally and will update when I make some progress.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

The test below (and all httpclient injected @MicronautTest) similar to the one included worked fine in Micronaut 1.2.0, but around 1.2.2 it broke with a the same error listed in #1806 but ONLY on the build slave whose name is `slave1-6x8-jenkins-agent-2.0.1-5h7sl`.  We upgraded to 1.2.5 and the error from #1806  went away locally.  We even copied in the test from the fix to see that it worked. Now tests using an RxHttpClient are all throwing a NPE only on the build server where the hostname conforms to the pattern above.

```java
@MicronautTest
class LoginControllerSpec extends Specification {

    @Inject
    @Client('/login')
    RxHttpClient client

    @Unroll
    def "POST /login - #contentType - HTTP 200 (OK)"() {
        given:
        String username = "user"
        String password = "password"
        Map<String, String> body = ["username": username, "password": password]

        when:
        HttpResponse<Map> response = client
                .toBlocking()
                .exchange(HttpRequest.POST("/", body).contentType(contentType), Map)

        then:
        response.status == HttpStatus.OK
        response.headers.get("Username") == username
        response.headers.get(JwtConfigurationProperties.JWT_AUTHN_HEADER_NAME)
        response.body.isPresent()
        response.body.get()["name"] == username
        response.body.get()["token"]

        where:
        contentType << [ MediaType.APPLICATION_FORM_URLENCODED, MediaType.APPLICATION_JSON]
    }
}
```

```java
import io.micronaut.http.client.HttpClient
import io.micronaut.http.client.exceptions.HttpClientException
import spock.lang.Specification;

/**
 * Bug in micronaut < 1.2.5 test here for regression
 * of issue https://github.com/micronaut-projects/micronaut-core/issues/1806
 */
class HostNameSpec extends Specification {

    void "test host name with dots and dashes"() {
        when:
        def client = HttpClient.create(new URL("http://slave1-6x8-jenkins-agent-2.0.1-0vnqb"))
        client.toBlocking().retrieve("/")

        then:
        def e = thrown(HttpClientException)
        e.message.contains('Connect Error: slave1-6x8-jenkins-agent-2.0.1-0vnqb')

        cleanup:
        client.close()
    }

    void "test host name with underscores"() {
        when:
        def client = HttpClient.create(new URL("https://foo_bar"))
        client.toBlocking().retrieve("/")

        then:
        def e = thrown(HttpClientException)
        e.message.contains('Connect Error: foo_bar')

        cleanup:
        client.close()
    }


    void "test host name with underscores and port"() {
        when:
        def client = HttpClient.create(new URL("https://foo_bar:8080"))
        client.toBlocking().retrieve("/")

        then:
        def e = thrown(HttpClientException)
        e.message.contains('Connect Error: foo_bar')

        cleanup:
        client.close()
    }
}
```

All the tests fail in Spock with NPE (but only on build server....)

```
[ERROR] Errors: 
[ERROR]   LoginControllerSpec.POST /login - application/json - HTTP 200 (OK) ? NullPointer
[ERROR]   LoginControllerSpec.POST /login - application/x-www-form-urlencoded - HTTP 200 (OK) ? NullPointer
[ERROR]   TokenControllerSpec.GET /token/refresh - HTTP 200 (OK) ? NullPointer
[ERROR]   SvgBadgeControllerSpec.GET /badge/compliance?org={org}&repo={repo} - HTTP 200 (OK) ? NullPointer
[ERROR]   SvgBadgeControllerSpec.GET /badge/compliance?org={org}&repo={repo}&branch={branch} - HTTP 200 (OK) ? NullPointer
[ERROR]   SvgBadgeControllerSpec.GET /badge/latest-version?groupId={groupId}&artifactId={artifactId} - HTTP 200 (OK) ? NullPointer
.... (plus tens of more tests...)
```

**Comment by ctoestreich** [comment]
Finally got a stack from the build server

```
java.lang.NullPointerException: null
	at java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at io.micronaut.http.client.DefaultHttpClient.getHostHeader(DefaultHttpClient.java:1741)
	at io.micronaut.http.client.DefaultHttpClient.prepareHttpHeaders(DefaultHttpClient.java:1755)
	at io.micronaut.http.client.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1602)
	at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1035)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by graemerocher** [comment]
The issue is the underscore in the domain name. This results in requestURI.getHost() returning null and you have to parse the URI from `requestURI.getAuthority()`

**Comment by ctoestreich** [comment]
@graemerocher There is no underscore in the hostname `slave1-6x8-jenkins-agent-2.0.1-5h7sl`

**Comment by ctoestreich** [comment]
@graemerocher Now that I finally have a stack I am working on a fix and test in core fork atm.
