### ISSUE TITLE
mn create-app is broken

### ISSUE THREAD

**Issue by brotherdetjr** [micronaut-projects/micronaut-core#233]
### StR:
1. Download fresh mn snapshot from sonatype. Currently it is https://oss.sonatype.org/content/groups/public/io/micronaut/cli/1.0.0-SNAPSHOT/cli-1.0.0-20180529.125130-35-dist.zip
2. Unpack, add to PATH
3. Run mn create-app myapp --stacktrace

### Expected:
Application folder with lots of stuff in it created.

### Acutal:
Observing the following stdout:
```
Warning |
Unrecognized flag: stacktrace.
Error |
Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:service:jar:1.0.0.M1 in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:service:jar:1.0.0.M1 in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:129)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:121)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:107)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:90)
	at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:98)
	at io.micronaut.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:293)
	at io.micronaut.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:416)
	at io.micronaut.cli.MicronautCli.executeCommandWithArgumentValidation(MicronautCli.groovy:275)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:251)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:158)
```
Please pay attention to the requested dependency version: 1.0.0.M1 - it is absent in sonatype repo.
I see, it is taken from io.micronaut.bom. I tried to clear local maven cache, but it pulls that bom again.
It was working yesterday (2018-05-29).

Also I don't expect to see "Warning | Unrecognized flag: stacktrace." message, if the application suggested this flag itself :) But this is a pretty minor bug, considering that this flag works, even though I get warning.

- **Operating System**: Windows 7
- **Micronaut Version:** 1.0.0-SNAPSHOT (1.0.0-20180529.125130-35)
- **JDK Version:** "10.0.1" 2018-04-17

**Comment by graemerocher** [comment]
You can download 1.0 M1 from SDKman or alternatively use one of these https://oss.sonatype.org/content/groups/public/io/micronaut/cli/1.0.0.BUILD-SNAPSHOT/

**Comment by brotherdetjr** [comment]
Thank you! Will try now. So, are these sonatype SNAPSHOTs not valid anymore? What is "the official" way to get the CLI? SDKman?

**Comment by graemerocher** [comment]
you can get the latest release of the CLI via SDKman yes or direct download at http://micronaut.io/download.html

**Comment by brotherdetjr** [comment]
Yep, it worked, thank you!
