### ISSUE TITLE
Annotation @TypeHint is ignored in Kotlin project

### ISSUE THREAD

**Issue by nik-lazer** [micronaut-projects/micronaut-core#2336]
I am trying to build GraphQL service to be compiled in Graal. As expected, there are some classes in graphql library, which have to be tuned by @TypeHint annotation. Unfortunately Kapt does not seem to be handling the annotation properly because no reflection-config.json is generated:
![image](https://user-images.githubusercontent.com/1555606/68762498-53f0c280-0627-11ea-8c7b-80fc202140df.png)

Annotation processors, responsible for that, are not triggered during gradle's build. As a result, graphql engine does not work: 
![image](https://user-images.githubusercontent.com/1555606/68762245-da58d480-0626-11ea-80de-0639daedd11e.png)

```
12:13:45.103 [nioEventLoopGroup-2-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error deserializing object from JSON: Cannot construct instance of `io.micronaut.configuration.graphql.GraphQLRequestBody` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"query":"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      t"[truncated 1054 chars]; line: 1, column: 2]
java.lang.RuntimeException: Error deserializing object from JSON: Cannot construct instance of `io.micronaut.configuration.graphql.GraphQLRequestBody` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"query":"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      t"[truncated 1054 chars]; line: 1, column: 2]
        at io.micronaut.configuration.graphql.JacksonGraphQLJsonSerializer.deserialize(JacksonGraphQLJsonSerializer.java:64)
        at io.micronaut.configuration.graphql.GraphQLController.post(GraphQLController.java:145)
        at io.micronaut.configuration.graphql.$GraphQLControllerDefinition$$exec2.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2844)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:294)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$15(RoutingInBoundHandler.java:1371)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.micronaut.configuration.graphql.GraphQLRequestBody` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"query":"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      t"[truncated 1054 chars]; line: 1, column: 2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at io.micronaut.configuration.graphql.JacksonGraphQLJsonSerializer.deserialize(JacksonGraphQLJsonSerializer.java:62)
        ... 44 common frames omitted
12:13:45.104 [nioEventLoopGroup-2-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [Internal Server Error: Error deserializing object from JSON: Cannot construct instance of `io.micronaut.configuration.graphql.GraphQLRequestBody` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"query":"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      t"[truncated 1054 chars]; line: 1, column: 2]] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@7f3a17a86ce0
12:13:45.105 [nioEventLoopGroup-2-3] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=POST /graphql]
12:13:45.105 [nioEventLoopGroup-2-3] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <HttpRequestTerminatedEvent> io.micronaut.context.event.ApplicationEventListener
12:13:46.551 [pool-2-thread-7] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.health.HeartbeatTask@7f3a16caa698] for type [class io.micronaut.health.HeartbeatTask] and qualifier [null]
12:13:46.551 [pool-2-thread-7] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.health.HeartbeatEvent[source=io.micronaut.http.server.netty.NettyEmbeddedServerInstance@7f3a16c7cd48]
12:13:46.551 [pool-2-thread-7] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <HeartbeatEvent> io.micronaut.context.event.ApplicationEventListener`
```
The sample is here https://github.com/nik-lazer/graal-experiments/tree/master/graal-kotlin-graphql

At the same time Java based project is built fine and all necessary files are generated:
![image](https://user-images.githubusercontent.com/1555606/68762309-fb212a00-0626-11ea-8a7f-fa587d9b3407.png)

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone repository https://github.com/nik-lazer/graal-experiments
2. Go to the project https://github.com/nik-lazer/graal-experiments/tree/master/graal-kotlin-graphql
3. Complete the instructions from https://github.com/nik-lazer/graal-experiments/blob/master/graal-kotlin-graphql/README.md
4. Observe the issue
5. Go to the project https://github.com/nik-lazer/graal-experiments/tree/master/graal-java-graphql
6. Complete the instructions from https://github.com/nik-lazer/graal-experiments/blob/master/graal-java-graphql/README.md
7. Observe no issue
![image](https://user-images.githubusercontent.com/1555606/68762868-1a6c8700-0628-11ea-963c-f1b5acb2fdae.png)

### Expected Behaviour

During building of the Kotlin project reflection.json should be generated and placed into JAR. As a result, graphql should work and resolve queries

### Actual Behaviour

Gradle ignores @TypeHint annotation, and Graal image does not work
![image](https://user-images.githubusercontent.com/1555606/68762227-cf9e3f80-0626-11ea-81e2-3cc03b0097b8.png)

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.5
- **JDK Version:** 8

### Example Application

https://github.com/nik-lazer/graal-experiments/tree/master/graal-kotlin-graphql
https://github.com/nik-lazer/graal-experiments/tree/master/graal-java-graphql

**Comment by aherve-pro** [comment]
Hi @nik-lazer 

In Kotlin project, try to change in build.gradle

`annotationProcessor "io.micronaut:micronaut-graal"`

to 

`kapt "io.micronaut:micronaut-graal"`


Extract of : https://kotlinlang.org/docs/reference/kapt.html 

> Annotation processors (see JSR 269) are supported in Kotlin with the kapt compiler plugin.

**Comment by nik-lazer** [comment]
Hi @aherve-pro,
Many thanks for the recommendation. It is a bit strange that few weeks and it did not work for me, but I have probably done something wrong. Now I have changed build.gradle and files for Graal are in place, so artifact was built successfully. Pity just, that Micronaut CLI was not generated origninally with proper settings.
