### ISSUE TITLE
Support Alexa and Kinesis functions in Micronaut Java and Groovy

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#236]
We should support Alex and Kinesis functions in Micronaut

**Comment by rvanderwerf** [comment]
should I break these out into tasks for each one?
Alexa - needs RequestEnvelope/ResponseEnvelope signature
Kenesis - needs signature with KinesisEvent
S3 - needs signature with S3Event
SNS - needs signature with SNSEvent
Cognito - needs signature to handle class 

I have some examples from the Grails & AWS talk here: https://github.com/rvanderwerf/kinesisLambdaConsumerDemo.git

Basically we need to support the events covered in aws-lambda-java-events

amazon docs:
https://docs.aws.amazon.com/lambda/latest/dg/java-programming-model.html
https://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html

Maybe we can make one ASTTransformer and execture class for most of them (at least non-alexa ones) and use an annotation or smomething like @SNSFunction or @KenesisFunction, @CognitoFunction  that sets up the right signatures and runs them????

**Comment by rvanderwerf** [comment]
going to break this out into 2 tickets I think I have another for alexa anyways I opened. The issue for the Alexa Lambda stuff is #268

**Comment by zhangsantu** [comment]
hi:
this is problem，give me some demo! thanks!
ERROR io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: No transaction manager configured
org.springframework.transaction.TransactionSystemException: No transaction manager configured
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.resolveTransactionManager(TransactionInterceptor.java:119)
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.intercept(TransactionInterceptor.java:63)

**Comment by musketyr** [comment]
actually, I'm currently working on rewriting https://github.com/agorapulse/grails-aws-sdk for Micronaut
