### ISSUE TITLE
Error when using StreamedFile with declarative http client

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#2443]
### Steps to Reproduce

1. Create a client and controller extending common interface with a method, returning `StreamedFile`
```java
public interface ReportAPI
{

    @Post
    StreamedFile downloadReport();

}

@Controller("/report")
public class ReportController implements ReportAPI
{

    @Override
    public StreamedFile downloadReport()
    {
 
        return new StreamedFile(new ByteArrayInputStream("test".getBytes()), MediaType.TEXT_PLAIN_TYPE);
    }
}

@Client(path = "/report", id = "report-service")
public interface MarketingReportServiceClient extends ReportAPI
{
    @Override
    StreamedFile downloadReport();

}
```
2. Invoke the client from another service

### Expected Behaviour

`StreamedFile` is returned from the client.

### Actual Behaviour

```
Caused by: io.micronaut.http.codec.CodecException: Cannot decode byte buffer with value [test] to type: StreamedFile streamedFile
	at io.micronaut.runtime.http.codec.TextPlainCodec.lambda$decode$0(TextPlainCodec.java:95)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.micronaut.runtime.http.codec.TextPlainCodec.decode(TextPlainCodec.java:95)
	at io.micronaut.http.client.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:250)
	at io.micronaut.http.client.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:191)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.micronaut.http.client.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:168)
	at io.micronaut.http.client.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:101)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1844)
	... 44 common frames omitted
```

### Environment Information

- **Micronaut Version:** 1.2.5

**Comment by jameskleeh** [comment]
StreamedFile is not designed to be used as a return type for clients. File uploading and downloading have different semantics

**Comment by ivyazmitinov** [comment]
@jameskleeh 
It is pretty inconvenient when trying to design sort of "gateway" service. I suppose, there is no other solutions except not extend from common interface and define custom client?
Also, it might be useful to validate such cases (if there any similar) on client generation stage and fail compilation with meaningful error.

**Comment by jameskleeh** [comment]
Agreed some validation would be nice for the known cases

**Comment by ivyazmitinov** [comment]
@jameskleeh 
Yeah, we are just using `byte[]`. It is enough for our requirements for now.
