### ISSUE TITLE
Can't create a grpc app with 1.3.0 M1

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-core#2451]
Create a default project with 

`mn create-app helloworld --profile grpc --lang java --build gradle`
or with groovy too

Get's us to:

```
* Where:
Build file '/Users/u1/Documents/helloworld/build.gradle' line: 5

* What went wrong:
An exception occurred applying plugin request [id: 'application']
> Failed to apply plugin [class 'org.gradle.api.plugins.JavaPlugin']
   > Could not create an instance of type com.google.protobuf.gradle.ProtobufSourceDirectorySet.
      > org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;Lorg/gradle/api/internal/file/collections/DirectoryFileTreeFactory;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;Lorg/gradle/api/internal/file/collections/DirectoryFileTreeFactory;)V
        at com.google.protobuf.gradle.ProtobufSourceDirectorySet.<init>(ProtobufSourceDirectorySet.groovy:41)
        at com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated.<init>(Unknown Source)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:200)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:402)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        ... 205 more
```

Taking example as base and update the lib is working yet it use gradle 4.

**Comment by benrhine** [comment]
This can be fixed by upgrading the protobuf plugin to either version `0.8.8, 0.8.9, or 0.8.10` https://github.com/micronaut-projects/micronaut-profiles/pull/216
