### ISSUE TITLE
SSLException with HttpClient for certain certificates

### ISSUE THREAD

**Issue by liefra** [micronaut-projects/micronaut-core#250]
The HttpClient throws an SSLException for certain SSL connections, e.g. connecting to `https://httpbin.org` or `https://randomuser.me`.

### Steps to Reproduce

```java
public class SslTest {

    public static void main(String[] args) throws IOException {

        // Standard URL classes work well
        String json = new BufferedReader(new InputStreamReader(new URL("https://httpbin.org/get").openStream())).readLine();
        System.out.println(json);

        // This doesn't work and throws: javax.net.ssl.SSLException: Received fatal alert: internal_error
        String httpbin = HttpClient.create(new URL("https://httpbin.org")).toBlocking().retrieve("/get");

        // This doesn't work and throws: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        String randomuser = HttpClient.create(new URL("https://randomuser.me")).toBlocking().retrieve("/");
    }
}
```

### Actual Behaviour

```java
// stacktrace
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at java.base/sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1905)
	at java.base/sun.security.ssl.SSLEngineImpl.processInputRecord(SSLEngineImpl.java:1140)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1020)
	at java.base/sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:902)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:680)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
```

### Environment Information

- **Operating System**: Mac 10.13.5
- **Micronaut Version:** Master
- **JDK Version:** Tested 8.0.172-zulu and 10.0.1-zulu

### Additional notes

I found a similar [issue and probably related ](https://github.com/netty/netty/issues/6178#issuecomment-270867164)

**Comment by graemerocher** [comment]
We are aware of this issue. The workaround is to enable SSL:

```
micronaut:
      ssl: true
```

And use an injected client (not the `create` static method)

```
@Client("https://httpbin.org") @Inject HttpClient client
```

**Comment by liefra** [comment]
For me the workaround is not working after enabling SSL in `application.yml`

### Steps to Reproduce
```java
@Context
public class SslTest {

    private HttpClient client;

    @Inject public SslTest(@Client("https://httpbin.org") HttpClient client) {
        this.client = client;
    }

    @PostConstruct
    public void test() {

        // io.micronaut.http.client.exceptions.HttpClientException: Error occurred reading HTTP response: javax.net.ssl.SSLException: Received fatal alert: internal_error
        String json = client.toBlocking().retrieve("/get");

    }


    public static void main(String[] args) {
        Micronaut.run(SslTest.class);
    }
}
```
### application.yml
```yml
micronaut:
    ssl: true
```
