### ISSUE TITLE
Exception when typing -v in CLI

### ISSUE THREAD

**Issue by axelfontaine** [micronaut-projects/micronaut-core#2514]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Start the CLI
2. Enter `-v` followed by enter

### Expected Behaviour

Reasonable, readable error message

### Actual Behaviour

```
mn> -v
| Error Command [mn] error: No signature of method: io.micronaut.cli.MicronautCli.handle() is applicable for argument types: (io.micronaut.cli.MicronautCli$ExecutionContextImpl) values: [<io.micronaut.cli.MicronautCli$ExecutionContextImpl@d375a209>]
Possible solutions: findAll(), any(), find(), any(groovy.lang.Closure), findAll(groovy.lang.Closure), find(groovy.lang.Closure)
groovy.lang.MissingMethodException: No signature of method: io.micronaut.cli.MicronautCli.handle() is applicable for argument types: (io.micronaut.cli.MicronautCli$ExecutionContextImpl) values: [<io.micronaut.cli.MicronautCli$ExecutionContextImpl@d375a209>]
Possible solutions: findAll(), any(), find(), any(groovy.lang.Closure), findAll(groovy.lang.Closure), find(groovy.lang.Closure)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy16.handleCommand(Unknown Source)
        at io.micronaut.cli.MicronautCli.handleCommand(MicronautCli.groovy:433)
        at io.micronaut.cli.MicronautCli$_handleCommandWithCancellationSupport_closure6.doCall(MicronautCli.groovy:541)
        at io.micronaut.cli.MicronautCli$_handleCommandWithCancellationSupport_closure6.call(MicronautCli.groovy)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
| Error Command [mn] error: No signature of method: io.micronaut.cli.MicronautCli.handle() is applicable for argument types: (io.micronaut.cli.MicronautCli$ExecutionContextImpl) values: [<io.micronaut.cli.MicronautCli$ExecutionContextImpl@d375a209>]
Possible solutions: findAll(), any(), find(), any(groovy.lang.Closure), findAll(groovy.lang.Closure), find(groovy.lang.Closure)
```

### Environment Information

```
mn> -V
| Micronaut Version: 1.2.7
| JVM Version: 11.0.1
```

Running on Windows 10 x64. Note that since your issue template asks for the OS it would probably be a good idea to let the `-V` command return that info as well.

### Example Application

N/A

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/2449ac48e6986e585e7094361c2eb738d4a1766c
