### ISSUE TITLE
Netty firing IllegalArgumentException for NioSocketChannel

### ISSUE THREAD

**Issue by mbakgun** [micronaut-projects/micronaut-core#2516]
Hi all , 
I couldn't run my graal-enabled micronaut sample application in Google cloud run environment. Google cloud firestore / datastore / pubsub I got the same error in different demo applications.
I don't know if there is a conflict at that point for subscribe operations using netty in Google cloud libraries. 
Actually it was 1 week to meet micronaut, but I couldn't run the application in the cloud because of the following error.
### Stacktrace

```
java.lang.ExceptionInInitializerError: null
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:242)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:193)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:185)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:160)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:122)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:90)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:82)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:538)
	at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:385)
	at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:77)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:73)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:66)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:518)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
	at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
	at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
	at com.hextechgreen.service.TestService.getLatestValue(TestService.kt:35)
	at com.hextechgreen.controller.TestController.cmsBulk(TestController.kt:18)
	at com.hextechgreen.controller.$TestControllerDefinition$$exec3.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2844)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:235)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1400)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.IllegalArgumentException: Class NioSocketChannel does not have a public non-arg constructor
	at io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:36)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:72)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
```

### Steps to Reproduce

1. Assemble .jar file
2. Build native image container ; Run native image (RUN native-image --no-server --static -cp .jar)
3. Deploy cloud run 

### Expected Behaviour

I'm expecting to run application in Cloud Run like running it on my local environment.

### Actual Behaviour

Google Cloud services that using Netty are unable to start on Google Cloud. The reason shows that can't find classes although it's already present.

### Environment Information

- **Operating System**: alpine-glibc
- **Micronaut Version:** 19.2.1
- **JDK Version:** 1.8.0_161

### Example Application
Example source code can be found following 
https://github.com/mbakgun/micronaut-sample-firestore-cloud-run

**Comment by graemerocher** [comment]
Looks like reflective metatadata for Graal is missing for `io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory`

**Comment by mbakgun** [comment]
Hi @graemerocher ,
Thanks for your reply , reflection didn't helped to me , error still occurring. I've added like below ;

`[
  {
    "name": "io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "allPublicClasses": true
  },
  {
    "name": "io.netty.channel.socket.nio.NioSocketChannel",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "allPublicClasses": true,
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  }
]`

Then , 
RUN native-image **-H:ReflectionConfigurationFiles=reflect.json** --no-server --static -cp app.jar

**Comment by graemerocher** [comment]
Sorry my mistake it is actually `io.grpc.netty.shaded.io.netty.channel.socket.NioSocketChannel` that is missing the metadata. The issue is that GRPC shades netty which breaks the reflection metadata that GraalVM needs. See https://github.com/netty/netty/blob/4.1/transport/src/main/resources/META-INF/native-image/io.netty/transport/reflection-config.json

**Comment by mbakgun** [comment]
Hi runtime error still exist. Even though I've put It doesn't work.
And also  with this reflection 19.3.0-java11 and 19.2.1 not working.

`[
  {
    "name": "io.netty.channel.socket.nio.NioServerSocketChannel",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
  {
    "name": "io.netty.channel.socket.nio.NioSocketChannel",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
  {
    "name": "sun.nio.ch.SelectorImpl",
    "fields": [
      {
        "name": "selectedKeys",
        "allowUnsafeAccess": true
      },
      {
        "name": "publicSelectedKeys",
        "allowUnsafeAccess": true
      }
    ]
  }
]`

You mean there is a configuration that overriding my netty reflection at graal side ? If yes what is your suggestion could you provide me a workaround or smt ? 
Many thanks @graemerocher

**Comment by mbakgun** [comment]
Hi ,
Adding below helps ,
`[
  {
    "name": "io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  }
]`
