### ISSUE TITLE
Error starting GraalVM rabbitmq app in GitlabCI with Micronaut 1.3.0 snapshot

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2544]
This error started to happen once I upgraded the RabbitMQ GraalVM app to Micronaut 1.3.0. It's really strange and I don't really know why it is happening now.
I've tried to set the port in different ways and I even tried to create the native image with the Gitlab CI configuration included directly in `application.yml` so no external configuration file is necessary. It always fails with (https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/380455109):

```
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [port] of method [setPort] of class: io.micronaut.configuration.rabbitmq.connect.SingleRabbitConnectionFactoryConfig
Message: Error resolving property value [rabbitmq.port]. Unable to convert value [tcp://172.17.0.3:4369] to target type [int] due to: For input string: "tcp://172.17.0.3:4369"
Path Taken: Connection.connection([RabbitConnectionFactoryConfig connectionFactory],BeanContext beanContext) --> SingleRabbitConnectionFactoryConfig.setPort([int port])
	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:793)
	at io.micronaut.configuration.rabbitmq.connect.$SingleRabbitConnectionFactoryConfigDefinition.injectBean(Unknown Source)
	at io.micronaut.configuration.rabbitmq.connect.$SingleRabbitConnectionFactoryConfigDefinition.build(Unknown Source)
 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1611)
 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2320)
 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2002)
 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1976)
 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
 	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1005)
 	at io.micronaut.configuration.rabbitmq.connect.$RabbitConnectionFactory$Connection0Definition.build(Unknown Source)
 	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:115)
 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1611)
 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2320)
 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2002)
 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1976)
 	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1115)
 	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:628)
 	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:105)
 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1611)
 	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2320)
 	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2002)
 	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1976)
 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
 	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:119)
	... 19 common frames omitted
```

Another try. I compiled locally micronaut-rabbitmq with Micronaut 1.3.0.M1 and tried again. Now the error is (https://gitlab.com/ilopmar/test-rabbitmq/-/jobs/384247913):

```
Error starting Micronaut server: Error processing bean [Definition: example.micronaut.rabbitmq.fireandforget.analytics.AnalyticsListener] method definition [void updateAnalytics(Book book)]: Failed to retrieve a channel pool named [default] to register a listener
io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: example.micronaut.rabbitmq.fireandforget.analytics.AnalyticsListener] method definition [void updateAnalytics(Book book)]: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:92)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1741)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2705)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2604)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:656)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:643)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$29(DefaultBeanContext.java:1402)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1401)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2535)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:204)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at example.micronaut.rabbitmq.Application.main(Application.java:8)
Caused by: io.micronaut.messaging.exceptions.MessageListenerException: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:121)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:64)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	... 17 common frames omitted
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [port] of method [setPort] of class: io.micronaut.configuration.rabbitmq.connect.SingleRabbitConnectionFactoryConfig

Message: Error resolving property value [rabbitmq.port]. Property doesn't exist
Path Taken: SingleRabbitConnectionFactoryConfig.setPort([int port])
	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:794)
	at io.micronaut.configuration.rabbitmq.connect.$SingleRabbitConnectionFactoryConfigDefinition.injectBean(Unknown Source)
	at io.micronaut.configuration.rabbitmq.connect.$SingleRabbitConnectionFactoryConfigDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1685)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2394)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2076)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2050)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1115)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:628)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:105)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1685)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2394)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2076)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2050)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:119)
```
Which doesn't make sense at all because I have defined `rabbitmq.port` in the configuration file.

It's important to notice that this only happens on Gitlab CI. Everything works as expected running the native-image locally or in docker using the same docker image as in Gitlab CI, so I'm not really sure if there is anything we can do about it, but maybe the stacktrace rings a bell about something that may have been changed in Micronaut 1.3.0.

To try to reproduce this everything is in this repo: https://github.com/micronaut-graal-tests/micronaut-rabbitmq-graal

**Comment by ilopmar** [comment]
Finally I discovered the issue. Gitlab CI injects a lot of environment variables and one of them is `RABBITMQ_PORT=tcp://172.17.0.3:4369` which overrode the configuration.
After configuring the app with environment variables instead of a config files, everything works as expected: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/commit/b9567484302d7228b7124f0c5a17f1be083e082c#5f8e7ac915ffb068e541c04f03eeec138368d972_7_9
