### ISSUE TITLE
micronaut-function-aws-lambda graalvm native-image build fails

### ISSUE THREAD

**Issue by samblake** [micronaut-projects/micronaut-core#2570]
I am unable to build a native application using the [micronaut-function-aws-lambda](https://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html) example. However, I am able to create a native application following [micronaut-creating-first-graal-app](https://guides.micronaut.io/micronaut-creating-first-graal-app/guide/index.html). 

### Steps to Reproduce

1. git clone https://github.com/micronaut-guides/micronaut-function-aws-lambda.git
2. cd micronaut-function-aws-lambda/complete/vies-vat-validator-graal/
3. sdk use java 19.2.1-grl
4. gu install native-image
5. ./gradlew assemble
6. native-image --no-server --class-path build/libs/vies-vat-validator-0.1-all.jar

When run with `native-image --no-server --no-fallback --class-path build/libs/vies-vat-validator-0.1-all.jar` gives the following stack trace:

```
[vies-vat-validator:2013]    classlist:   3,387.28 ms
[vies-vat-validator:2013]        (cap):     782.93 ms
[vies-vat-validator:2013]        setup:   1,874.84 ms
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
[vies-vat-validator:2013]     analysis:   5,220.38 ms
Error: Unsupported features in 8 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:356)
Call path from entry point to io.micronaut.context.DefaultApplicationContext.findBeanCandidates(Class, BeanDefinition, boolean): 
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:241)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidatesInternal$68(DefaultBeanContext.java:2473)
	at io.micronaut.context.DefaultBeanContext$$Lambda$423/286112041.apply(Unknown Source)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$462/2000240267.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.oracle.svm.core.posix.PosixJavaNetClose.getFdEntry(PosixJavaNetClose.java:124)
	at com.oracle.svm.core.posix.PosixJavaNetClose.BLOCKING_IO_RETURN_INT(PosixJavaNetClose.java:220)
	at com.oracle.svm.core.posix.PosixJavaNetClose.NET_Send(PosixJavaNetClose.java:308)
	at com.oracle.svm.core.posix.JavaNetNetUtilMD.NET_Send(JavaNetNetUtil.java:1447)
	at com.oracle.svm.core.posix.Target_java_net_SocketOutputStream.socketWrite0(PosixJavaNetSubstitutions.java:5180)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.PrintStream.newLine(PrintStream.java:548)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2180)
Call path from entry point to io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(Class, Qualifier, boolean, boolean, boolean): 
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2165)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$57(DefaultBeanContext.java:2155)
	at io.micronaut.context.DefaultBeanContext$$Lambda$419/1395457134.apply(Unknown Source)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$462/2000240267.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.oracle.svm.core.posix.PosixJavaNetClose.getFdEntry(PosixJavaNetClose.java:124)
	at com.oracle.svm.core.posix.PosixJavaNetClose.BLOCKING_IO_RETURN_INT(PosixJavaNetClose.java:220)
	at com.oracle.svm.core.posix.PosixJavaNetClose.NET_Send(PosixJavaNetClose.java:308)
	at com.oracle.svm.core.posix.JavaNetNetUtilMD.NET_Send(JavaNetNetUtil.java:1447)
	at com.oracle.svm.core.posix.Target_java_net_SocketOutputStream.socketWrite0(PosixJavaNetSubstitutions.java:5180)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.PrintStream.newLine(PrintStream.java:548)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1917)
Call path from entry point to io.micronaut.context.DefaultBeanContext.getBeanInternal(BeanResolutionContext, Class, Qualifier, boolean, boolean): 
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1911)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:605)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:101)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:64)
	at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:62)
	at io.micronaut.function.executor.FunctionApplication$$Lambda$290/1168665863.accept(Unknown Source)
	at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:96)
	at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:60)
	at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:50)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:196)
Call path from entry point to io.micronaut.context.DefaultBeanContext.start(): 
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:193)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:120)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:81)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:64)
	at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:62)
	at io.micronaut.function.executor.FunctionApplication$$Lambda$290/1168665863.accept(Unknown Source)
	at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:96)
	at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:60)
	at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:50)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:233)
Call path from entry point to io.micronaut.context.DefaultBeanContext.stop(): 
	at io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:232)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:192)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:53)
	at io.micronaut.context.LifeCycle.close(LifeCycle.java:61)
	at io.micronaut.function.executor.AbstractExecutor.lambda$buildApplicationContext$1(AbstractExecutor.java:91)
	at io.micronaut.function.executor.AbstractExecutor$$Lambda$401/1743697755.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.env.DefaultEnvironment.<init>(DefaultEnvironment.java:209)
Call path from entry point to io.micronaut.context.env.DefaultEnvironment.<init>(ApplicationContextConfiguration): 
	at io.micronaut.context.env.DefaultEnvironment.<init>(DefaultEnvironment.java:192)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.<init>(DefaultApplicationContext.java:622)
	at io.micronaut.context.DefaultApplicationContext.createEnvironment(DefaultApplicationContext.java:162)
	at io.micronaut.context.DefaultApplicationContext.<init>(DefaultApplicationContext.java:119)
	at io.micronaut.context.DefaultApplicationContextBuilder.build(DefaultApplicationContextBuilder.java:187)
	at io.micronaut.function.executor.AbstractExecutor.buildApplicationContext(AbstractExecutor.java:88)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:76)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:64)
	at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:62)
	at io.micronaut.function.executor.FunctionApplication$$Lambda$290/1168665863.accept(Unknown Source)
	at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:96)
	at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:60)
	at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:50)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:319)
Call path from entry point to io.micronaut.context.env.DefaultEnvironment.start(): 
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:318)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:63)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:228)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:120)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:81)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:64)
	at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:62)
	at io.micronaut.function.executor.FunctionApplication$$Lambda$290/1168665863.accept(Unknown Source)
	at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:96)
	at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:60)
	at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:50)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.apache.logging.slf4j.Log4jLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.micronaut.core.io.scan.DefaultClassPathResourceLoader.lambda$isDirectory$0(DefaultClassPathResourceLoader.java:179)
Call path from entry point to io.micronaut.core.io.scan.DefaultClassPathResourceLoader.lambda$isDirectory$0(String, String): 
	at io.micronaut.core.io.scan.DefaultClassPathResourceLoader.lambda$isDirectory$0(DefaultClassPathResourceLoader.java:153)
	at io.micronaut.core.io.scan.DefaultClassPathResourceLoader$$Lambda$428/1226256230.apply(Unknown Source)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$462/2000240267.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.oracle.svm.core.posix.PosixJavaNetClose.getFdEntry(PosixJavaNetClose.java:124)
	at com.oracle.svm.core.posix.PosixJavaNetClose.BLOCKING_IO_RETURN_INT(PosixJavaNetClose.java:220)
	at com.oracle.svm.core.posix.PosixJavaNetClose.NET_Send(PosixJavaNetClose.java:308)
	at com.oracle.svm.core.posix.JavaNetNetUtilMD.NET_Send(JavaNetNetUtil.java:1447)
	at com.oracle.svm.core.posix.Target_java_net_SocketOutputStream.socketWrite0(PosixJavaNetSubstitutions.java:5180)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.PrintStream.newLine(PrintStream.java:548)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

### Expected Behaviour

Native application should be built

### Actual Behaviour

Build Fails

### Environment Information

- **Operating System**: Manjaro 18.1.2
- **Micronaut Version:** 1.2.7
- **JDK Version:** OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)

### Example Application

- https://github.com/micronaut-guides/micronaut-function-aws-lambda.git

**Comment by samblake** [comment]
In addition this is what I get when I try to create the native image with GraalVM 19.3.0.2 running `native-image --no-server -cp build/libs/vies-vat-validator-0.1-all.jar -H:+TraceClassInitialization`.

```
[vies-vat-validator:21580]    classlist:   5,434.18 ms
[vies-vat-validator:21580]        (cap):     992.26 ms
[vies-vat-validator:21580]        setup:   2,227.17 ms
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
[vies-vat-validator:21580]     analysis:   5,608.39 ms
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.logging.slf4j.Log4jLogger was unintentionally initialized at build time. io.micronaut.http.MediaType caused initialization of this class with the following trace: 
	at org.apache.logging.slf4j.Log4jLogger.<clinit>(Log4jLogger.java)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:52)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.micronaut.http.MediaType.<clinit>(MediaType.java:326)


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by SchulteMarkus** [comment]
@samblake For avoiding [that error](https://github.com/micronaut-projects/micronaut-core/issues/2570#issuecomment-569895244), it should vanish if you add ```--initialize-at-build-time=org.apache.logging.log4j --initialize-at-build-time=org.apache.logging.slf4j``` to your _native-image_ execution.

**Comment by samblake** [comment]
Awesome, that did it! I've opened a ticket on the micronaut-guides project and close this one.

https://github.com/micronaut-guides/micronaut-function-aws-lambda/issues/12
