### ISSUE TITLE
Requests with non-permitted characters in the URI  path (eg. <) result in an internal server error (500)

### ISSUE THREAD

**Issue by raphiz** [micronaut-projects/micronaut-core#2606]
### Steps to Reproduce

1. Setup a new project: `mn create-app bugreport-illegal-uri`
2. Build and launch the app: `cd bugreport-illegal-uri/; ./gradlew run`
3. Send a request containing a character that is not allowed in a URI according to [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738.txt), for example: 
  `curl -v 'http://localhost:8080/<>'`
   - Note that other characters such as `[`, `\` and `{` work as well

### Expected Behaviour

Since the user provides a url that does not conform to [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738.txt), a HTTP status code such as 400 (Bad Request) or maybe even 404 (Not Found) is expected.

### Actual Behaviour

An `URISyntaxException` is thrown on the backend, resulting in an internal server error (http status code 500) returned to the user along with the following error `Internal Server Error: Illegal character in path at index 1: /<>"`.

Here is the Log output including the stack trace:

```bash
08:09:04.983 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 943ms. Server Running: http://localhost:8080
08:09:33.468 [nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Illegal character in path at index 1: /<>
java.net.URISyntaxException: Illegal character in path at index 1: /<>
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	at io.micronaut.http.netty.AbstractNettyHttpRequest.<init>(AbstractNettyHttpRequest.java:61)
	at io.micronaut.http.server.netty.NettyHttpRequest.<init>(NettyHttpRequest.java:89)
	at io.micronaut.http.server.netty.decoders.HttpRequestDecoder.decode(HttpRequestDecoder.java:75)
	at io.micronaut.http.server.netty.decoders.HttpRequestDecoder.decode(HttpRequestDecoder.java:43)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:191)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:186)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.2.6
- **JDK Version:** OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)

### Example Application

This issue can be reproduced with in any Micronaut project that does not explicitly handle `URISyntaxException`, `Exception` or `Throwable`

### Related issues
This seems to be related with #1190.

**Comment by raphiz** [comment]
I just dug a little bit deeper and it seems as if a [fix from #1190](https://github.com/micronaut-projects/micronaut-core/commit/52a8cb5f3eb7068ea6fe7c49b27a10e12dab06aa)  was not merged. I would fix this issue in a PR very similarly (maybe in the method `exceptionCaughtInternal` instead of `exceptionCaught`), but now I'm unsure if this was not merged on purpose. @puneetbehl can you tell me more on why you didn't open a PR for this fix?

**Comment by jameskleeh** [comment]
@raphiz Puneet's change was not merged in favor of https://github.com/micronaut-projects/micronaut-core/commit/ea4ef862d8c4f28fb4d440263d5d281c8f434099

You can register an exception handler for `URISyntaxException` and return whatever you like. That wasn't possible before that change. Can we consider this issue a request to have that be the default?

**Comment by raphiz** [comment]
@jameskleeh Thanks for the background info! Yes, it would be great if that were default. Other client issues, for example a malformed JSON payload, are handled by Micronaut directly resulting in a HTTP 400. Therefore, in my opinion, that would be the more consistent behavior.
