### ISSUE TITLE
Root cause exception raise during the application context initalization are not logged

### ISSUE THREAD

**Issue by yyvess** [micronaut-projects/micronaut-core#2622]
In some case root cause exception thrown during the application context initialization aren't logged.
That give the analyze of the issue really hard and not give a good experience for beginner ;-)

Sample log message  (Micronaut 1.2.8)
```
Exception in thread "main" io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [hello.micro.Application$DataSource] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1965)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:610)
	at hello.micro.Application.main(Application.java:17)

```

Produce by this use case
```java
package hello.micro;

import io.micronaut.context.ApplicationContext;
import io.micronaut.context.annotation.EachBean;
import io.micronaut.context.annotation.EachProperty;
import io.micronaut.context.env.PropertySource;

import static io.micronaut.core.util.CollectionUtils.mapOf;

public class Application {

    public static void main(String[] args) {

        try (ApplicationContext context = ApplicationContext.run(
                PropertySource.of(mapOf("apps.datasource.primary.url", "jdbc"))).start()) {
            System.out.println(context.getBean(DataSource.class).getUrl());
        }
    }

    @EachBean(DataSourceConfiguration.class)
    public static class DataSource {

        private final DataSourceConfiguration props;

        public DataSource(DataSourceConfiguration props) {
            this.props = props;
        }
        public String getUrl() {
            return props.getUrl();
        }
    }

    @EachProperty("apps.datasource")
    public static class DataSourceConfiguration {

        private String url;

        public DataSourceConfiguration() {
            throw new NullPointerException("Oupps !!");
        }

        public String getUrl() {
            return url;
        }
        public void setUrl(String url) {
            this.url = url;
        }
    }
}
```

**Comment by yyvess** [comment]
The NullPointerException (on this example) is "loose" on the try catch of the generate class "$Application$DataSourceDefinition.class" 

`
    public DataSource build(BeanResolutionContext var1, BeanContext var2, BeanDefinition<DataSource> var3) {
        DataSourceConfiguration var4 = null;
        try {
            var4 = (DataSourceConfiguration)super.getBeanForConstructorArgument(var1, var2, 0);
        } catch (BeanContextException var6) {
            return null;
        }
        DataSource var5 = new DataSource(var4);
        var5 = (DataSource)this.injectBean(var1, var2, var5);
        return var5;
    }
`
And null is ignored here as the beanDefinition is an iterable

`                    if (bean == null) {
                        if (!(beanDefinition.isIterable()
                                || beanDefinition.getAnnotationMetadata().hasAnnotation(Factory.class))) {
                            throw new BeanInstantiationException(resolutionContext, "Bean Factory [" + beanFactory + "] returned null");
                        }
                    } else {
                        if (bean instanceof Qualified) {
                            ((Qualified) bean).$withBeanQualifier(declaredQualifier);
                        }
                    }`

**Comment by yyvess** [comment]
If we use an optional on the DataSource controller code generated is : 

```java
        public DataSource(Optional<DataSourceConfiguration> props) {
 ```
```java
    public DataSource build(BeanResolutionContext var1, BeanContext var2, BeanDefinition<DataSource> var3) {
        DataSource var4 = new DataSource((Optional)super.getBeanForConstructorArgument(var1, var2, 0));
        var4 = (DataSource)this.injectBean(var1, var2, var4);
        return var4;
    }
 ```

And we have the error that we want when we do not have an optional ! 

 ```
Exception in thread "main" io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [hello.micro.Application$DataSource]

Message: Oupps !!
Path Taken: new DataSource([Optional props])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1624)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1102)
	at io.micronaut.context.AbstractBeanDefinition.lambda$findBeanForConstructorArgument$12(AbstractBeanDefinition.java:1154)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1752)
	at io.micronaut.context.AbstractBeanDefinition.findBeanForConstructorArgument(AbstractBeanDefinition.java:1153)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:991)
	at hello.micro.$Application$DataSourceDefinition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:610)
	at hello.micro.Application.main(Application.java:20)
Caused by: java.lang.NullPointerException: Oupps !!
	at hello.micro.Application$DataSourceConfiguration.<init>(Application.java:45)
	at hello.micro.$Application$DataSourceConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:113)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	... 16 more
 ```

PS:
@Nullable work as expected

**Comment by jameskleeh** [comment]
The bytecode for factories has changed for 2.0.0 so this is no longer an issue
