### ISSUE TITLE
PUT call with @Nullable Header fails w/ 'Invalid JSON' error

### ISSUE THREAD

**Issue by ddifranc** [micronaut-projects/micronaut-core#2757]
Exposed a PUT method in a micronaut server, with a @Nullable @Header parameter.
If the client doesn't set the parameter, it fails with 
io.micronaut.http.client.exceptions.HttpClientResponseException: Invalid JSON: Unexpected character ('b' ...

Even though there should be no JSON in the picture.

If I replace it with an Optional<String> parameter, it doesn't happen.

In GET methods with @Nullable @Headers, it also doesn't happen

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Testcase uploaded to github, link below.

./gradlew run
./gradlew test

This test fails: testPutNullableHeaderNotSet

### Expected Behaviour

Put should succeed, and ignore the @Nullable header

### Actual Behaviour

client gets:

      Invalid JSON: Unexpected character ('b' (code 98)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
      at [Source: UNKNOWN; line: 1, column: 2]
      io.micronaut.http.client.exceptions.HttpClientResponseException: Invalid JSON: Unexpected character ('b' (code 98)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
      at [Source: UNKNOWN; line: 1, column: 2]
      at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1789)
      at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1707)
      at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
      at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
      at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
      at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:834)### Environment Information

- **Operating System**: MacOS 10.12.6
- **Micronaut Version:** 1.3.0.M2
- **JDK Version:** openjdk 11.0.2

### Example Application

https://github.com/ddifranc/micronaut-core-header-bug

**Comment by jameskleeh** [comment]
JSON is in the picture because you're not setting the content type of the request and thus it defaults to JSON

**Comment by ddifranc** [comment]
If I set contentType(MediaType.APPLICATION_OCTET_STREAM_TYPE), it succeeds.

But the behavior is strange: why does the error only happen if I have a @Nullable Header parameter that isn't set by the client?
All of my test cases pass except for testPutNullableHeaderNotSet()

It's OK if you close this.
Possibly the exception could be improved?
"Content-Type is application/json, but request body is not valid JSON" ?

**Comment by jameskleeh** [comment]
@ddifranc I'm going to look into it further. Optionals are handled a little bit different than nullable so that is why it's behaving differently.
