### ISSUE TITLE
Document correct usage of `ByteBuffer`

### ISSUE THREAD

**Issue by ddifranc** [micronaut-projects/micronaut-core#2758]
Exposed a PUT method in a micronaut server which accepts a body of type Flowable<ByteBuffer>.
Passing that to an HttpClient PUT call to httpbin server.

The test client gets a ReadTimeoutException.
The server logs:
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

Same error doesn't happen with Flowable<byte[]>

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Code uploaded to github.  See link below.

./gradlew run
./gradlew test

### Expected Behaviour

The PUT call should succeed

### Actual Behaviour

Test client gets ReadTimeoutException.

Server logs:

    WARN  i.n.channel.ChannelOutboundBuffer - Failed to mark a promise as success because it has failed already: DefaultChannelPromise@46addeab(failure: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1), unnotified cause:
    io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
            at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
            at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
            at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
            at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
            at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
            at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
            at io.micronaut.http.netty.stream.HttpStreamsHandler.write(HttpStreamsHandler.java:287)
            at io.micronaut.http.netty.stream.HttpStreamsClientHandler.write(HttpStreamsClientHandler.java:57)
            at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
            at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762)
            at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1089)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
            at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
            at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
            at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
            at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:92)
            at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
            at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:91)### Environment Information

- **Operating System**: MacOS 10.12.6
- **Micronaut Version:** 1.3.1-BUILD-SNAPSHOT
(requires the fix to bug https://github.com/micronaut-projects/micronaut-core/issues/2722 ,
or it doesn't even get that far)
 **JDK Version:** 11.0.2+9

### Example Application
https://github.com/ddifranc/micronaut-core-put-flowable-bug

**Comment by jameskleeh** [comment]
So basically this is happening because the `ByteBuffer` is being cleaned up after the `onNext` call coming in the request. The data is also being cleaned up after the `onNext` call as part of the response. As both steps are necessary, the only way to resolve this would be to copy the buffer before invoking the controller arguments flowable `onNext`.

**Comment by ddifranc** [comment]
My confusion may be caused because some of the APIs return ByteBuffers, like RxStreamingHttpClient.exchangeStream().
It's hard to know when to use byte[]s and when to use ByteBuffers.

**Comment by ddifranc** [comment]
Even with the workaround (byte[]s instead of ByteBuffers), if i try to upload a decently large content (~10 kb), i get ReadTimeoutException from DefaultHttpClient.

Added new testcases: 
testUploadByteArraySmall() passes
testUploadByteArrayLarge() fails w/ ReadTimeoutException

**Comment by graemerocher** [comment]
Triage: Type Feature. The original upload failure was fixed in #2722, and current ByteBody documentation now states that reactive ByteBuffer publishers may be reference-counted and must be released or retained according to their lifecycle. The remaining gap is practical migration guidance for legacy Flowable<ByteBuffer> request/response code, including when to copy with `toByteArray`, when to retain, and why returning a publisher differs from manually subscribing. Suggested solution: add a focused guide example and regression coverage for small/large streamed uploads; no new reproducer is needed unless the current API still fails after following its ownership contract.
