### ISSUE TITLE
Attempt to create abstract BeanCreatedEventListener

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#2772]
In `1.3.0` (after migration from `1.3.0.M1`).

The following code:

```java
public abstract class AbstractListener implements BeanCreatedEventListener<AutoStartingBean> {

	public static final Logger logger = LoggerFactory.getLogger(AbstractListener.class);

	@Inject protected SomeBean someBean;

	@Override
	public AutoStartingBean onCreated(BeanCreatedEvent<AutoStartingBean> event) {
		logger.debug("Listener called with: {}", event.getBean());

		return event.getBean();
	}
}

@Singleton
public class Listener extends AbstractListener {
}
```

Throws the following exception:

```
16:19:30.425 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type [micronaut.general.AbstractListener]: micronaut.general.AbstractListener
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [micronaut.general.AbstractListener]: micronaut.general.AbstractListener
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1721)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:787)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1271)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2542)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:204)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at micronaut.general.Application.main(Application.java:8)
Caused by: java.lang.InstantiationError: micronaut.general.AbstractListener
	at micronaut.general.$AbstractListenerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	... 9 common frames omitted
```

It looks Micronaut wants to create a bean from the abstract `AbstractListener` class. The injection of `SomeBean` is crucial here - if the abstract bean has no injectable fields the app still works.

**Comment by l0co** [comment]
Here is the reproducible testcase: https://github.com/l0co/micronaut-playground/tree/micronaut-2772
