### ISSUE TITLE
java.lang.IncompatibleClassChangeError when using @MockBean with Micronaut  >= 1.2.x

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#2791]
The following test:

```java
@MicronautTest
public class MockApplicationListenerTest {
    @Inject
    BeanContext beanContext;

    @Test
    public void test() {
        MyApplicationListener myApplicationListener = beanContext.getBean(MyApplicationListener.class);
        Assertions.assertEquals(
                "I'm the mock bean",
                myApplicationListener.getDescription()
        );
    }

    @MockBean(MyApplicationListener.class)
    public MyApplicationListener mockBean() {
        return new MyApplicationListener("I'm the mock bean");
    }
}
```

Produces this exception:

```
Found interface io.micronaut.context.event.ApplicationEventListener, but class was expected
java.lang.IncompatibleClassChangeError: Found interface io.micronaut.context.event.ApplicationEventListener, but class was expected
	at io.micronaut.test.junit5.$MockApplicationListenerTest$MockBean0Definition$$exec4.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:147)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
	at io.micronaut.runtime.context.scope.refresh.RefreshInterceptor.intercept(RefreshInterceptor.java:49)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.test.junit5.$MockApplicationListenerTest$MockBean0Definition$Intercepted.supports(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.lambda$publishEvent$17(DefaultBeanContext.java:1128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1127)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:215)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:277)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:175)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:48)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
```

This is reproducible in the `master` branch of https://github.com/micronaut-projects/micronaut-test

**Comment by alvarosanchez** [comment]
Can this be backported to 1.2.x?
