### ISSUE TITLE
Declarative http-client with Graal native-image fails to resolve hostname

### ISSUE THREAD

**Issue by si87** [micronaut-projects/micronaut-core#2813]
I've implemented a simple declarative http-client to execute request a simple json-api
(`http://jsonplaceholder.typicode.com/todos/1`). The app has been compiled to a native graalvm-binary according to the current docs.

Running the app within a container fails with exception provided below. 
Compiling natively and running the binary without docker on macOS worked (without static-linking, but this is a GraalVM issue on macOS)

According to https://www.graalvm.org/docs/reference-manual/native-image/ you can pass flags like `--enable-http` and `--enable-https` to `native-image` build, but it didn't help to run the app within a container.

### Steps to Reproduce
```
mn create-app -l kotlin -f=graal-native-image micronaut-graal-demo
```
implement simple declarative client and controller to trigger request.
```
./gradlew assemble
./docker-build.sh

docker run -d -p 8080:8080 micronaut-graal-demo
curl http://localhost:8080/test
```

### Expected Behaviour
`curl`-command should return something similiar like
```
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```

### Actual Behaviour
Stacktrace
```
13:19:45.344 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 25ms. Server Running: http://d24ae46f658f:8080
13:19:55.380 [pool-2-thread-3] ERROR i.m.r.intercept.RecoveryInterceptor - Type [micronaut.graal.demo.TodoClient$Intercepted] executed with error: Connect Error: jsonplaceholder.typicode.com: System error
io.micronaut.http.client.exceptions.HttpClientException: Connect Error: jsonplaceholder.typicode.com: System error
	at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1042)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:48)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.net.UnknownHostException: jsonplaceholder.typicode.com: System error
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_UnknownHostException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java)
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.net.InetAddress.getByName(InetAddress.java:1248)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:148)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:145)
	at java.security.AccessController.doPrivileged(AccessController.java:117)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:145)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
	... 24 common frames omitted
```
### Environment Information

- **Operating System**: MacOS Catalina 10.15.3
- **Micronaut Version:** 1.3.0 & 1.3.1
- **JDK Version:**
```
$ java -version 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

### Example Application
https://github.com/si87/micronaut-graal-demo

Folder `issue` contains steps to reproduce and the stacktrace.

`master`-branch with declarative client.
`bug/additional_native_build_flags_container`-branch contains a change in `Dockerfile` with additional `--enable-http` flag executing `native-image`
`bug/additional_properties_flags`-branch contains a change in `native-image.properties` with additional `--enable-http` flag.

Hope I'm not missing something here and this is not a totally stupid fault on my side.

Best regards
Si Tran

**Comment by ilopmar** [comment]
I've sent you a PR that fixes the native-image generation: https://github.com/si87/micronaut-graal-demo/pull/1.
Basically use `frolvlad/alpine-glibc` instead of scratch. I'll fix that in the profiles and our guides.

Also, please keep in mind that you don't need to enable http/https protocolos because those are already enabled in Micronaut: https://github.com/micronaut-projects/micronaut-core/blob/9ac3e4012583ac5a586b4e40816e54509f137244/inject/src/main/resources/META-INF/native-image/io.micronaut/inject/native-image.properties#L2
