### ISSUE TITLE
ServerRequestContext.currentRequest() returns empty after observeOn()

### ISSUE THREAD

**Issue by highmtworks** [micronaut-projects/micronaut-core#2841]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. install micronaut-1.3.1
2. mn create-app hello-world
3. add the following controller to the hello-world project

```
package hello.world.controller;

import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.context.ServerRequestContext;
import io.reactivex.Single;
import io.reactivex.schedulers.Schedulers;

@Controller("/hello")
public class HelloController {
    @Get(value = "/ng", produces = MediaType.TEXT_PLAIN)
    public Single<String> index() {
        return Single.just("hello").observeOn(Schedulers.computation()).map(r -> {
            if (ServerRequestContext.currentRequest().isPresent()) {
                return r;
            } else {
                throw new RuntimeException("fail");
            }
        });
    }

    @Get(value = "/ok", produces = MediaType.TEXT_PLAIN)
    public Single<String> ok() {
        return Single.just("hello").map(r -> {
            if (ServerRequestContext.currentRequest().isPresent()) {
                return r;
            } else {
                throw new RuntimeException("fail");
            }
        });
    }
}
```

4. build and run
5. access localhost:8080/hello/ng

### Expected Behaviour

The application should return `hello` with status code 200.

Actually, 

- accessing localhost:8080/hello/ok returns `hello` with status code 200.
- accessing localhost:8080/hello/ng on micronaut-1.2.10 returns `hello` with status code 200.

### Actual Behaviour

The application returns `{"message":"Internal Server Error: fail"}` with status code 500,

Stacktrace:

```
10:50:26.177 [RxComputationThreadPool-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: fail
java.lang.RuntimeException: fail
	at hello.world.controller.HelloController.lambda$index$0(HelloController.java:18)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSingleObserver.onSuccess(RxInstrumentedSingleObserver.java:81)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: Windows 10 Pro 1809 build 17763.973
- **Micronaut Version:** 1.3.1
- **JDK Version:**  
  openjdk version "11.0.6" 2020-01-14 LTS  
  OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)  
  OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

### Example Application

Sorry but see "Steps to Reproduce" .

----

Adding the following to the project makes the application pass, but I don't know whether it is correct workaround.

```
package io.micronaut.reactive.rxjava2;

import io.micronaut.context.annotation.Context;
import io.micronaut.context.annotation.Requires;
import io.reactivex.Flowable;
import io.reactivex.functions.Function;
import io.reactivex.plugins.RxJavaPlugins;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
@Context
@Requires(classes = Flowable.class)
public class RxJava2InstrumentationPatch implements AutoCloseable {
    private final RxInstrumenterFactory instrumenterFactory;

    Function<? super Runnable, ? extends Runnable> oldOnScheduleHandler;

    @Inject
    public RxJava2InstrumentationPatch(RxInstrumenterFactory instrumenterFactory) {
        this.instrumenterFactory = instrumenterFactory;
    }

    @PostConstruct
    void init() {
        if (instrumenterFactory.hasInstrumenters()) {
            oldOnScheduleHandler = RxJavaPlugins.getScheduleHandler();
            RxJavaPlugins.setScheduleHandler(runnable -> {
                var instrumenter = instrumenterFactory.create();
                if (instrumenter != null) {
                    return () -> {
                        try {
                            instrumenter.beforeInvocation();
                            runnable.run();
                        } finally {
                            instrumenter.afterInvocation();
                        }
                    };
                }
                return runnable;
            });
        }
    }

    @Override
    @PreDestroy
    public void close() throws Exception {
        if (instrumenterFactory.hasInstrumenters()) {
            try {
                RxJavaPlugins.setScheduleHandler(oldOnScheduleHandler);
            } catch (Exception e) {
                // ignore
            }
        }
    }
}
```

**Comment by jameskleeh** [comment]
Is your example representative of the actual code where this is causing a problem? If not, in what context is it occurring?

**Comment by highmtworks** [comment]
Sorry for my poor description.

Partially yes.
The example is the smallest reproduction code that is the result of our investigation to report issue.
The real situation is complicated a little to explain, but I'll try.

The actual issue we encountered is:

* We have an application running on micronaut-1.2.10
* When we upgraded micronaut from 1.2.10 to 1.3.1, the application stopped working properly,  
* Plural exceptions like the following were recorded in the log:  
  `io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [(our class in our applictation)] exists for the given qualifier: @RequestScope.`
  and the stacktrace is:
  ```
  Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [(our application package).configuration.db.DbContext] exists for the given qualifier: @RequestScope. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
  	at io.micronaut.runtime.http.scope.RequestCustomScope.get(RequestCustomScope.java:81)
  	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2146)
  	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2086)
  	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:949)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.$resolveTarget(Unknown Source)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.interceptedTarget(Unknown Source)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.(method of request scope bean)(Unknown Source)
  	at (our application package).dataaccess.db.tran.impl.(our db access class).lambda$(our db access method)$3((our db access class).java:58)
  	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
  	at io.reactivex.Single.subscribe(Single.java:3603)
  	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
  	... 5 common frames omitted
  Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [(our application package).configuration.db.DbContext] exists for the given qualifier: @RequestScope. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
  	at io.micronaut.runtime.http.scope.RequestCustomScope.get(RequestCustomScope.java:81)
  	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2146)
  	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2086)
  	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:949)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.$resolveTarget(Unknown Source)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.interceptedTarget(Unknown Source)
  	at (our application package).configuration.db.$DbContextConfiguration$DbContext1Definition$Intercepted.(method of request scope bean)(Unknown Source)
  	at (our application package).service.impl.(our service class).(our service method)((our service class).java:147)
  	at io.reactivex.internal.operators.single.SingleUsing$UsingSingleObserver.onError(SingleUsing.java:165)
  	at io.micronaut.reactive.rxjava2.RxInstrumentedSingleObserver.onError(RxInstrumentedSingleObserver.java:66)
  	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
  	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
  	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
  	... 5 common frames omitted
  ```

* The stacktrace above contains `onError` because it is around the second exception thrown in the exception handler.  
  The stacktrace around the original first exception is: (this is from debugger because it is not recorded in the log)
  
  ```
  get:81, RequestCustomScope (io.micronaut.runtime.http.scope)
  getScopedBeanForDefinition:2146, DefaultBeanContext (io.micronaut.context)
  getBeanForDefinition:2086, DefaultBeanContext (io.micronaut.context)
  getProxyTargetBean:949, DefaultBeanContext (io.micronaut.context)
  $resolveTarget:-1, $DbContextConfiguration$DbContext1Definition$Intercepted ((our application package).configuration.db)
  interceptedTarget:-1, $DbContextConfiguration$DbContext1Definition$Intercepted ((our application package).configuration.db)
  (method of request scope bean):-1, $DbContextConfiguration$DbContext1Definition$Intercepted ((our application package).configuration.db)
  lambda$(our db access method)$3:58, (our db access class) ((our application package).dataaccess.db.tran.impl)
  call:-1, 1238618141 ((our application package).dataaccess.db.tran.impl.(our db access class)$$Lambda$1480)
  subscribeActual:44, SingleFromCallable (io.reactivex.internal.operators.single)
  subscribe:3603, Single (io.reactivex)
  run:89, SingleSubscribeOn$SubscribeOnObserver (io.reactivex.internal.operators.single)
  run:578, Scheduler$DisposeTask (io.reactivex)
  run:66, ScheduledRunnable (io.reactivex.internal.schedulers)
  call:57, ScheduledRunnable (io.reactivex.internal.schedulers)
  run:264, FutureTask (java.util.concurrent)
  run:304, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
  runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
  run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
  run:834, Thread (java.lang)
  ```
  in io thread observer, which is nested in computation thread oberver (via flatMap) :
  
  ```
  lambda$(our service method)$2:53, (our service class) ((our application package).service.impl)
  apply:-1, 1193706923 ((our application package).service.impl.(our service class)$$Lambda$1447)
  map:265, Optional (java.util)
  lambda$(our service method)$4:52, (our service class) ((our application package).service.impl)
  apply:-1, 1203884522 ((our application package).service.impl.(our service class)$$Lambda$1446)
  onSuccess:76, SingleFlatMap$SingleFlatMapCallback (io.reactivex.internal.operators.single)
  onSuccess:81, RxInstrumentedSingleObserver (io.micronaut.reactive.rxjava2)
  run:81, SingleObserveOn$ObserveOnSingleObserver (io.reactivex.internal.operators.single)
  call:38, ScheduledDirectTask (io.reactivex.internal.schedulers)
  call:26, ScheduledDirectTask (io.reactivex.internal.schedulers)
  run:264, FutureTask (java.util.concurrent)
  run:304, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
  runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
  run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
  run:834, Thread (java.lang)
  ```

We also use X-Ray to trace http request which uses `ServerRequestContext.currentRequest()` to hold segment information,
the issue is not only about `@RequestScope`.

The lines below are what we are thinking.

* `RxInstrumentedSingleObserver` seems to wrap a subsequent observer,  
  but in the different way from `RxInstrumentedSingle` and the like.
    - `RxInstrumentedSingle` holds instrumenter resolved at assembly time (in the constructor).
    - `RxInstrumentedSingleObserver` holds instrumenterFactory
      and instrumenter seems to be resolved at subscription time (in onSubscribe) or runtime (in onSuccess or onError).

* Because `RxInstrumentedSingleObserver#onSuccess` at runtime is on the different thread than controller thread,  
  and instrumenter is resolved at runtime,  
  `ServerRequestContext.currentRequest()` is already empty there.

* So in the stacktrace above around the original first exception,
  that of outer computation thread observer contains `RxInstrumentedSingleObserver`,
  but that of the nested io thread observer does not contain Rx wrapper.  
  (Rx wrapper instrumentation occurs only when `ServerRequestContext.currentRequest()` is not empty.)

To return to the example application, it is a contrived example to make the described above short.

Does it make sense ?
