### ISSUE TITLE
@DefaultImplementation doesn't work (for kotlin classes?)

### ISSUE THREAD

**Issue by renannprado** [micronaut-projects/micronaut-core#2894]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I've created one interface and two classes that implement the interface. 
Then I annotated the interface with `@DefaultImplementation`, however I now got a runtime error saying that there are two possibilities of beans to inject and Micronaut doesn't know which one. I haven't tried with Java though.

### Expected Behaviour

The class referenced in the `@DefaultImplementation` should be injected.

### Actual Behaviour

Runtime exception:

```
Unexpected error occurred: Failed to inject value for parameter [myRepository] of class: example.MyController

Message: Multiple possible bean candidates found: [example.MyRepositoryInMemory, example.MyRepositoryImpl]
Path Taken: new MyController([MyRepository myRepository],DataSource dataSource)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [myRepository] of class: example.MyController

Message: Multiple possible bean candidates found: [example.MyRepositoryInMemory, example.MyRepositoryImpl]
Path Taken: new MyController([MyRepository myRepository],DataSource dataSource)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1016)
	at example.$MyControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2968)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2989)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1461)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [example.MyRepositoryInMemory, example.MyRepositoryImpl]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1796)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:403)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2384)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$57(DefaultBeanContext.java:2250)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2249)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2038)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	... 32 common frames omitted

```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.3.2
- **JDK Version:** 20.0.0.r11-grl
- **Kotlin Version:** 1.3.50

### Example Application

```kotlin
import io.micronaut.context.annotation.DefaultImplementation
import javax.inject.Singleton

@DefaultImplementation(MyRepositoryInMemory::class)
interface MyRepository {
    fun upsert()
}

@Singleton
class MyRepositoryImpl : MyRepository {
    override fun upsert() {
        
    }
}

@Singleton
class MyRepositoryInMemory : MyRepository {
    override fun upsert() {

    }
}
```

And try to inject this into any class. In my case I tried to inject into a `@Controller` which caused the above exception to be thrown.

**Comment by jameskleeh** [comment]
You're misunderstanding the purpose of `@DefaultImplementation`. See the section on https://docs.micronaut.io/latest/guide/index.html#replaces.

See the section on bean qualifiers if you would like to qualify your beans https://docs.micronaut.io/latest/guide/index.html#qualifiers

**Comment by renannprado** [comment]
Ah, ok, I **guess** I understood it now, my bad.

Thanks!
