### ISSUE TITLE
java.lang.ClassNotFoundException: io.micronaut.caffeine.cache.SSLA with Micronaut session and GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2918]
Some changes did in 1.3.x for micronaut-cache doesn't play nice with GraalVM.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-security-session-graal`
- `cd micronaut-security-session-graal`
- Use GraalVM
- `./build-native-image.sh`
- `./security-session-graal`

### Expected Behaviour

The app should start. The application works with Micronaut 1.2.x.

### Actual Behaviour

```
14:25:01.091 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.session.binder.SessionArgumentBinder]

Message: io.micronaut.caffeine.cache.SSLA
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,Router router,[RequestArgumentSatisfier requestArgumentSatisfier],MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver) --> new NettyRequestArgumentSatisfier([RequestBinderRegistry requestBinderRegistry]) --> new DefaultRequestBinderRegistry(ConversionService conversionService,[List binders]) --> new SessionArgumentBinder([SessionStore sessionStore])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.session.binder.SessionArgumentBinder]

Message: io.micronaut.caffeine.cache.SSLA
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,Router router,[RequestArgumentSatisfier requestArgumentSatisfier],MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver) --> new NettyRequestArgumentSatisfier([RequestBinderRegistry requestBinderRegistry]) --> new DefaultRequestBinderRegistry(ConversionService conversionService,[List binders]) --> new SessionArgumentBinder([SessionStore sessionStore])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1719)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at io.micronaut.session.binder.$SessionArgumentBinderDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2723)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2635)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:924)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1123)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1761)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1118)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:984)
	at io.micronaut.http.bind.$DefaultRequestBinderRegistryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at io.micronaut.http.server.netty.$NettyRequestArgumentSatisfierDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1115)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:628)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:135)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.IllegalStateException: io.micronaut.caffeine.cache.SSLA
	at io.micronaut.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101)
	at io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3392)
	at io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3388)
	at io.micronaut.caffeine.cache.Caffeine.build(Caffeine.java:988)
	at io.micronaut.session.InMemorySessionStore.newSessionCache(InMemorySessionStore.java:129)
	at io.micronaut.session.InMemorySessionStore.<init>(InMemorySessionStore.java:62)
	at io.micronaut.session.$InMemorySessionStoreDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	... 40 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.micronaut.caffeine.cache.SSLA
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:229)
	at io.micronaut.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:95)
	... 47 common frames omitted
```

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 1.3.4.BUILD-SNAPSHOT
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Seems all of the Caffeine classes need to be registered for reflection

**Comment by ilopmar** [comment]
You mean manually registering all the classes?

I did a quick test with:
```
@TypeHint(
        typeNames = {"io.micronaut.caffeine.cache.SSLA"},
        accessType = TypeHint.AccessType.ALL_PUBLIC
)
``` 

And now the error is in another class `io.micronaut.caffeine.cache.PSW`. 

But at this moment `@TypeHint` doesn't support to add a package (because GraalVM doesn't support it either). 

Do you think is worth it modifying the graal type element visitor to allow define a package and automatically add all the classes? Assuming that it's possible to get all the classes in the package during compile time.

**Comment by ilopmar** [comment]
Umm... Adding the other class makes it work:
```
@TypeHint(
        typeNames = {
                "io.micronaut.caffeine.cache.SSLA",
                "io.micronaut.caffeine.cache.PSW"
        },
        accessType = TypeHint.AccessType.ALL_PUBLIC
)
```

Do you think that would be enough?

**Comment by graemerocher** [comment]
Doubtful, it would break if you change the configuration. The issue is this code in `LocalCacheFactory`:

```java
 /**
   * Returns a cache optimized for this configuration.
   */
  static <K, V> BoundedLocalCache<K, V> newBoundedLocalCache(Caffeine<K, V> builder,
      @Nullable CacheLoader<? super K, V> cacheLoader, boolean async) {
    StringBuilder sb = new StringBuilder("com.github.benmanes.caffeine.cache.");
    if (builder.isStrongKeys()) {
      sb.append('S');
    } else {
      sb.append('W');
    }
    if (builder.isStrongValues()) {
      sb.append('S');
    } else {
      sb.append('I');
    }
    if (builder.removalListener != null) {
      sb.append('L');
    }
    if (builder.isRecordingStats()) {
      sb.append('S');
    }
    if (builder.evicts()) {
      sb.append('M');
      if (builder.isWeighted()) {
        sb.append('W');
      } else {
        sb.append('S');
      }
    }
    if (builder.expiresAfterAccess() || builder.expiresVariable()) {
      sb.append('A');
    }
    if (builder.expiresAfterWrite()) {
      sb.append('W');
    }
    if (builder.refreshes()) {
      sb.append('R');
    }
    try {
      Class<?> clazz = LocalCacheFactory.class.getClassLoader().loadClass(sb.toString());
      Constructor<?> ctor = clazz.getDeclaredConstructor(Caffeine.class, CacheLoader.class, boolean.class);
      @SuppressWarnings("unchecked")
      BoundedLocalCache<K, V> factory = (BoundedLocalCache<K, V>) ctor.newInstance(builder, cacheLoader, async);
      return factory;
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException(sb.toString(), e);
    }
  }
```
I believe this code didn't exist in Caffeine 2.5 hence we we never upgraded to a version beyond that. Reflection would need to be registered for every combination of the capital letters that the above supports. 

Note that I think access type can be limited to `ALL_DECLARED_CONSTRUCTORS` instead of `ALL_PUBLIC`

**Comment by ilopmar** [comment]
There are more than 500 classes with those letters so adding all of them would increase the native image size by a lot. Also it will be tricky to keep them updated manually. Not sure if it's better to document this somehow...

BTW, changing the access type to `ALL_DECLARED_CONSTRUCTORS` also works.

**Comment by graemerocher** [comment]
I guess we should just add

```
typeNames = {
                "io.micronaut.caffeine.cache.SSLA",
                "io.micronaut.caffeine.cache.PSW"
        },
```

since for Micronaut session users cannot reconfigure the session cache to something else

**Comment by ilopmar** [comment]
You want me to send a PR to `micronaut-security-session`, right?

**Comment by graemerocher** [comment]
Sure

**Comment by ilopmar** [comment]
PR sent: https://github.com/micronaut-projects/micronaut-security/pull/196
