### ISSUE TITLE
Liquibase Migration Fails With Micronaut 1.3.4.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-core#3014]
When updating from Micronaut 1.3.3 to 1.3.4.BUILD-SNAPSHOT, service startup fails if using micronaut-liquibase.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Update a project that includes micronaut-liquibase to Micronaut 1.3.4.BUILD-SNAPSHOT
2. Try to start the application
3. The application will fail to start
4. Revert back to Micronaut 1.3.3
5. Try to start the application
6. The application successfully starts

### Expected Behaviour

The application should run applicable Liquibase migrations and then start

### Actual Behaviour

```
23:37:18.405 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

23:37:18.405 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

Path Taken: new TransactionalConnection$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

Path Taken: new TransactionalConnection$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1359)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2547)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:204)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at liquibase.issue.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

Path Taken: new TransactionalConnection$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1719)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2407)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2393)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
	at io.micronaut.transaction.jdbc.TransactionAwareDataSource.getTransactionAwareConnection(TransactionAwareDataSource.java:55)
	at io.micronaut.transaction.jdbc.TransactionAwareDataSource.access$000(TransactionAwareDataSource.java:24)
	at io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy.getConnection(TransactionAwareDataSource.java:81)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.migrate(LiquibaseMigrationRunner.java:131)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.run(LiquibaseMigrationRunner.java:106)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$null$0(LiquibaseMigrationRunner.java:88)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:88)
	at java.util.Optional.ifPresent(Optional.java:159)
...
```

### Environment Information

- **Operating System**: Fedora Linux 30
- **Micronaut Version:** 1.3.4.BUILD-SNAPSHOT
- **JDK Version:** OpenJDK Runtime Environment (build 1.8.0_242-b08)

### Example Application

- https://github.com/JasonTypesCodes/mn-liquibase-1.3.4
  After cloning, try to start the application with `./mvnw clean compile exec:exec`

**Comment by ilopmar** [comment]
Fixed in `micronaut-liquibase` `1.3.0`
