### ISSUE TITLE
Wrong auto-completion of properties with IntelliJ and HTTP 2

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#3025]
I'm trying using HTTP 2 and it works with the following configuration but IntelliJ is complaining:

![image](https://user-images.githubusercontent.com/559192/78569741-547f3500-7824-11ea-9918-6ccfe2cf56d8.png)

If I use `http_2_0` to make IntelliJ happy:

![image](https://user-images.githubusercontent.com/559192/78569859-7d9fc580-7824-11ea-87aa-e2112ab3435c.png)

The application fails during startup:

```
Caused by: java.lang.IllegalArgumentException: No enum constant io.micronaut.http.HttpVersion.http_2_0
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.micronaut.http.HttpVersion.valueOf(HttpVersion.java:24)
	at io.micronaut.http.converters.HttpConverterRegistrar.lambda$register$0(HttpConverterRegistrar.java:60)
	at io.micronaut.core.convert.TypeConverter.lambda$of$0(TypeConverter.java:75)
	at io.micronaut.core.convert.DefaultConversionService.convert(DefaultConversionService.java:139)
	at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:117)
	at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:305)
	at io.micronaut.context.DefaultApplicationContext.getProperty(DefaultApplicationContext.java:186)
	at io.micronaut.context.AbstractBeanDefinition.resolveValue(AbstractBeanDefinition.java:1659)
	at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:817)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.injectBean(Unknown Source)
	at io.micronaut.http.server.netty.configuration.$NettyHttpServerConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1707)
```

I think we should make it work with `http_2_0` or publish the right configuration metadata so IntelliJ knows how to do the auto-completion. If we don't do anything I think users will have a bad time using HTTP 2 because they'll trust their IDE and it won't work.

### Test application

https://github.com/micronaut-graal-tests/micronaut-http2-graal

**Comment by graemerocher** [comment]
nothing we can do about this, has to be resolved by IntelliJ. I would suggest reporting an issue to the IDEA issue tracker

**Comment by ilopmar** [comment]
This also happens with VS Code, not only IntelliJ. The problem is that we're "cheating" with the values
https://github.com/micronaut-projects/micronaut-core/blob/master/http/src/main/java/io/micronaut/http/HttpVersion.java#L44-L50
because we convert from double to the enum. Probably removing that method and using the http enum should make it work.

**Comment by graemerocher** [comment]
It only happens with the value 2.0 but yes maybe we should remove that as it probably will just cause confusion
