### ISSUE TITLE
@Scheduled methods scheduling in non-beans and cause exception when created by a factory

### ISSUE THREAD

**Issue by villuv** [micronaut-projects/micronaut-core#3040]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

For exact reproduction code, please see linked repository. 

There is some weirdness in behaviour of `@Scheduled` methods.

**Case 1** 
* Create a class without annotations, having a `@Scheduled` method

**Case 2** (not a bug)
* Create a class with `@Singleton` and `@Requires` annotations, having a `@Scheduled` method

**Case 3**
* Create a class without annotations, having a `@Scheduled` method
* Create an instance of that class using a `@Factory` class

### Expected Behaviour

**Case 1** Non-bean class should not be instantiated and method should not be scheduled.

**Case 2** (No issues)

**Case 3** A bean created by factory should be equivalent with bean created using annotations, no exception.

### Actual Behaviour

**Case 1** A non-bean class having a `@Scheduled` method basically behaves as a `@Prototype` bean: A new instance of the class is created and scheduled method is run on every interval.

**Case 2** Works as expected, instance not created and method not scheduled when requirements are not met.

**Case 3** a non-annotated class having `@Scheduled` method, created by a factory causes `NonUniqueBeanException: Multiple possible bean candidates found` exception:

```
12:33:18.920 [pool-1-thread-1] ERROR i.m.s.DefaultTaskExceptionHandler - Error invoking scheduled task Multiple possible bean candidates found: [scheduled.test.ScheduledBean, scheduled.test.ScheduledBean]
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [scheduled.test.ScheduledBean, scheduled.test.ScheduledBean]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1796)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:403)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2384)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$57(DefaultBeanContext.java:2250)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2249)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2038)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: OS X 10.14.6
- **Micronaut Version:** 1.3.4 and 2.0.0.M2
- **JDK Version:** OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)

### Example Application

Minimal reproduction code for all cases:
https://github.com/villuv/micronaut-scheduled-test

See README.md for more details.

**Comment by villuv** [comment]
I found that the BeanDefinitions are generated generated twice for the bean that has `@Scheduled` method in case it is created by a factory (names are from the reproduction code repo):

From the class itself, having, `isSingleton() { return false; }`
```
$ScheduledBeanDefinition$$exec1.class  
$ScheduledBeanDefinition.class
$ScheduledBeanDefinitonClass.class
```
and from the factory, having `isSingleton() { return true; }` 
```
$BeanFactory$ScheduledBean1Definition.class
$BeanFactory$ScheduledBean1DefinitionClass.class
```
Both of those definitions have the same beanTypeName, this is why ScheduledMethodProcessor finds two candidates.

I guess the problem is that it shouldn't generate BeanDefinitions for non-annotated classes at all. And in case of factory-created beans, executable method definition ($$exec) should point to the BeanDefinitionClass that is generated from the factory.

I hope this is helpful...

**Comment by villuv** [comment]
Reproducible also with 2.0.0.M3

**Comment by jameskleeh** [comment]
@villuv The bean created by the factory cannot work the same as one that is annotated directly. Because we don't know what type will actually be returned, we cannot reason about the type. Factories should never be used for classes that you have control over.

We are going to fix it so a class with only `@Scheduled` and no explicit bean declaration are no longer beans for 2.0.

**Comment by villuv** [comment]
Thanks, @jameskleeh !

**Comment by graemerocher** [comment]
There are issues still need investigating so for the moment the fix is waiting in a PR until it is ready for merge
