### ISSUE TITLE
Deserialisation of comma separated values into a POJO property fails

### ISSUE THREAD

**Issue by ytoh** [micronaut-projects/micronaut-core#3157]
Hi guys,

we have encountered an issue with binding comma separated values from a query parameter to a `List` property in a POJO. We have a controller method that has quite a few parameters that we wanted to encapsulate into a POJO since they are always used together. One of those parameters was a `List`. Once we converted the parameters into a POJO we started getting deserialisation exceptions when multiple values were sent as a comma separated list.

Binding to a `List` method parameter works just fine. The problem arises when we want to bind to a `List` POJO property.

### Expected Behaviour

Binding a comma separated query parameter values to a POJO property will split the values by comma so that the behaviour is consistent with binding to method parameters.

### Actual Behaviour

Binding of the POJO property fails since the value to be deserialised into an `Integer` is a string of comma separated numbers.

```
Failed to convert argument [null] for value [1,2] due to: Cannot deserialize value of type `java.lang.Integer` from String "1,2": not a valid Integer value
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.appdynamics.cfgsvc.BindingTest$Pojo["values"]->java.util.ArrayList[0])
io.micronaut.http.client.exceptions.HttpClientResponseException: Failed to convert argument [null] for value [1,2] due to: Cannot deserialize value of type `java.lang.Integer` from String "1,2": not a valid Integer value
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.appdynamics.cfgsvc.BindingTest$Pojo["values"]->java.util.ArrayList[0])
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1821)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1739)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:190)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:185)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

If I try to bind to a 

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 1.3.3
- **JDK Version:** 12

### Example Application

Here is a test reproducing this behaviour:

```java
@MicronautTest
public class BindingTest {

    @Inject
    @Client("/")
    RxHttpClient client;

    @Test
    public void commaSeparatedValuesAsPojoProperty() {
        var response = client.exchange(GET("/sum?values=1,2"), int.class).blockingFirst();

        assertEquals(OK, response.getStatus());
        assertEquals(3, response.getBody().orElseThrow());
    }

    @Controller
    static class TestController {
        @Get(uri = "/sum{?pojo*}", processes = TEXT_PLAIN)
        int sum(Pojo pojo) {
            return pojo.getValues().stream().reduce(0, Integer::sum);
        }
    }

    static class Pojo {
        private List<Integer> values;

        public List<Integer> getValues() {
            return values;
        }

        public void setValues(List<Integer> values) {
            this.values = values;
        }
    }
}
```

**Comment by jameskleeh** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/1610 and https://github.com/micronaut-projects/micronaut-core/issues/2157

**Comment by ytoh** [comment]
Hi @jameskleeh,

Sorry for not finding the duplicates before posting. I have a few questions if you don't mind: What is the reason for this behaviour? Why is it that when binding to a `List` type parameter Micronaut splits the list by comma but when it is wrapped in a POJO it does not? Why should these two cases behave differently? Thank you for your answers.

**Comment by jameskleeh** [comment]
@ytoh Because we cannot assume a string with commas in it should be bound to multiple items in a list. For integers, this is less of an issue, but still an issue. For example:

`"Hello, John"` -> Should that be bound to `["Hello", " John"]` or `["Hello, John"]` ?
`1,150` -> Should that be bound to `[1, 150]` or `[1150]`. 

Going the other way though, we can do it because we already have the list and thus can convert it to a string.

`["Hello", " John"]` -> Convert to string -> `"Hello, John"`
`["a", "b"]` -> Convert to string -> `"a,b"`
`[1150]` -> Convert to string -> "1150"
`[1, 150]` -> Convert to string -> "1,150"

**Comment by ytoh** [comment]
Hi @jameskleeh,

Thank you for your answer I appreciate you taking time to answer me but we are talking about two different things. I understand that in the absence of type information Micronaut cannot just decide to split a string along commas. But I observed that it does split it when binding to a method parameter when the information is present.

### Behaviour 1

Given:

```java
@Controller
class TestController {
    @Get(uri = "/sum{?values}", processes = TEXT_PLAIN)
    int sum(@Nullable List<Integer> values) {
        return values.stream().reduce(0, Integer::sum);
    }
}
```

When:

```bash
> curl http://localhost:8080/sum?values=1,2
```

Then:

```
3
```

My other observation was that when I wrap the same parameter in a POJO Micronaut's behaviour changes even though the same type information is present.

### Behaviour 2

Given:

```java
@Controller
class TestController {
    @Get(uri = "/sum{?pojo*}", processes = TEXT_PLAIN)
    int sum(Pojo pojo) {
        return pojo.getValues().stream().reduce(0, Integer::sum);
    }

    static class Pojo {
        private List<Integer> values;

        public List<Integer> getValues() {
            return values;
        }

        public void setValues(List<Integer> values) {
            this.values = values;
        }
    }
}
```
When:

```bash
> curl http://localhost:8080/sum?values=1,2
```

Then:

```
{
  "message" : "Failed to convert argument [null] for value [1,2] due to: Cannot deserialize value of type `java.lang.Integer` from String \"1,2\": not a valid Integer value\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.appdynamics.cfgsvc.proxy.TestController$Pojo[\"values\"]->java.util.ArrayList[0])",
  "path" : "/null",
  "_links" : {
    "self" : {
      "href" : "/sum?values=1,2",
      "templated" : false
    }
  },
  "_embedded" : { }
}
```

My question was about reconciling my two observations. Because I was not expecting the behaviour to change when I use this Micronaut feature and the documentation does not say that the behaviour will change once I do. My question is about this difference in behaviours. Why are they different?

**Comment by jameskleeh** [comment]
@ytoh Seems like something changed on our end and I wasn't aware. The reason the second scenario fails is because Jackson is completely responsible for constructing your class and deserializing the parameter map to your type. I don't know what options or annotations may be available to support this use case, however any solution would be with Jackson.

**Comment by Kendo-ui-angular2305** [comment]
> Hi [@jameskleeh](https://github.com/jameskleeh),
> 
> Thank you for your answer I appreciate you taking time to answer me but we are talking about two different things. I understand that in the absence of type information Micronaut cannot just decide to split a string along commas. But I observed that it does split it when binding to a method parameter when the information is present.
> 
> ### Behaviour 1
> Given:
> 
> @Controller
> class TestController {
>     @Get(uri = "/sum{?values}", processes = TEXT_PLAIN)
>     int sum(@Nullable List<Integer> values) {
>         return values.stream().reduce(0, Integer::sum);
>     }
> }
> When:
> 
> > curl http://localhost:8080/sum?values=1,2
> Then:
> 
> ```
> 3
> ```
> 
> My other observation was that when I wrap the same parameter in a POJO Micronaut's behaviour changes even though the same type information is present.
> 
> ### Behaviour 2
> Given:
> 
> @Controller
> class TestController {
>     @Get(uri = "/sum{?pojo*}", processes = TEXT_PLAIN)
>     int sum(Pojo pojo) {
>         return pojo.getValues().stream().reduce(0, Integer::sum);
>     }
> 
>     static class Pojo {
>         private List<Integer> values;
> 
>         public List<Integer> getValues() {
>             return values;
>         }
> 
>         public void setValues(List<Integer> values) {
>             this.values = values;
>         }
>     }
> }
> When:
> 
> > curl http://localhost:8080/sum?values=1,2
> Then:
> 
> ```
> {
>   "message" : "Failed to convert argument [null] for value [1,2] due to: Cannot deserialize value of type `java.lang.Integer` from String \"1,2\": not a valid Integer value\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.appdynamics.cfgsvc.proxy.TestController$Pojo[\"values\"]->java.util.ArrayList[0])",
>   "path" : "/null",
>   "_links" : {
>     "self" : {
>       "href" : "/sum?values=1,2",
>       "templated" : false
>     }
>   },
>   "_embedded" : { }
> }
> ```
> 
> My question was about reconciling my two observations. Because I was not expecting the behaviour to change when I use this Micronaut feature and the documentation does not say that the behaviour will change once I do. My question is about this difference in behaviours. Why are they different?





https://droopinglitespeed.github.io/issac/
