### ISSUE TITLE
could not find artifact `io.micronaut.profiles:base:jar:1.0.0.M2` when running 'mn' using getting started guide

### ISSUE THREAD

**Issue by patflynn** [micronaut-projects/micronaut-core#316]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. follow instructions on https://docs.micronaut.io/latest/guide/index.html
2. after running `./gradlew publishToMavenLocal` succesfully
3. run `$ mn`

### Expected Behaviour

starts micronaut interactive shell
Tell us what should happen

### Actual Behaviour
error:

```
*****@******:~/samples$ mn --stacktrace
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:base:jar:1.0.0.M2 in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:base:jar:1.0.0.M2 in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:129)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:121)
        at io.micronaut.cli.profile.repository.MavenProfileRepository.getAllProfiles(MavenProfileRepository.groovy:175)
        at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:230)
        at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:159)
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:base:jar:1.0.0.M2 in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)

```

### Environment Information

- **Operating System**: Debian
- **Micronaut Version:** master
- **JDK Version:** 1.8.0_151

**Comment by jameskleeh** [comment]
M2 has been released so this is no longer an issue
