### ISSUE TITLE
Jackson @JsonView not working when returning Flux<>

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-core#3193]
### Steps to Reproduce

Create controller method returning Flux<*> and filter returned JSON objects using Jackson @JsonView. 

This works for Mono<*> but fails for Flux<*>. Workaround is to convert Flux to Mono with collectList(), losing JSON streaming support for Fluxes (see last method in sample bellow). 

### Expected Behaviour

See sample bellow.

/api/d and /api/e should return JSON arrays. 

### Actual Behaviour

Exception is thrown:

```
09:34:34.394 [nioEventLoopGroup-1-3] | ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Unsupported Reactive type: class [B
java.lang.IllegalArgumentException: Unsupported Reactive type: class [B
	at io.micronaut.core.async.publisher.Publishers.lambda$convertPublisher$7(Publishers.java:297)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.micronaut.core.async.publisher.Publishers.convertPublisher(Publishers.java:297)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$2.lambda$onComplete$0(RoutingInBoundHandler.java:1160)
	at java.base/java.util.Optional.map(Optional.java:258)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$2.onComplete(RoutingInBoundHandler.java:1160)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$2.onComplete(RoutingInBoundHandler.java:1155)
	at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnComplete(ContextCompletionAwareSubscriber.java:73)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:225)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onComplete(FlowableSwitchMap.java:154)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onComplete(FlowableSubscribeOn.java:108)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:225)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapInnerSubscriber.onComplete(FlowableSwitchMap.java:414)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onComplete(FlowableSubscribeOn.java:108)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:97)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:134)
	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Tell us what happens instead

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 1.3.4
- **JDK Version:** 14

### Example Application

```kotlin
package foo

import com.fasterxml.jackson.annotation.JsonView
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import reactor.core.publisher.Flux
import reactor.core.publisher.Mono
import javax.annotation.security.PermitAll

interface InternalView
interface ExternalView

data class Foo(
    @JsonView(InternalView::class) val a: Int = 10,
    @JsonView(ExternalView::class) val b: Int = 20
)

@Suppress("HasPlatformType")
@Controller("/api/")
@PermitAll
class JsonViewController {

    @Get("a")
    @JsonView(InternalView::class)
    fun a() = Foo()

    @Get("b")
    @JsonView(ExternalView::class)
    fun b() = Foo()

    @Get("c")
    @JsonView(InternalView::class)
    fun c() = Mono.just(Foo())

    @Get("d")
    @JsonView(ExternalView::class)
    fun d() = Flux.just(Foo(), Foo(b = 21))

    @Get("e")
    @JsonView(InternalView::class)
    fun e() = Flux.empty<Foo>()

    @Get("f")
    @JsonView(ExternalView::class)
    fun f() = Flux.just(Foo(), Foo(b = 21)).collectList()
}
```

**Comment by graemerocher** [comment]
Maybe be resolved in 2.x
