### ISSUE TITLE
Unable to Configure logstash in logback.xml using config server

### ISSUE THREAD

**Issue by gokulraghu** [micronaut-projects/micronaut-core#3232]
I am working on a logstash encoder via TCP. I am integrating logstash with micronaut service for ELK stack. In logback.xml, we need to externalize the logstash hostname and port values.
I  tried as given  below to read the  logstash properties that are present externally using the spring config service based on environment profile(dev).

In build.gradle, i added the below code to run the application in dev profile: locally
`run.jvmArgs(....'-Dmicronaut.environments=dev')`

Below is the logback.xml i used.

```xml
<configuration>
	<property name="logstash_hostname" source="logstash.tcpConfig.hostname" />
	<property name="logstash_port" source="logstash.tcpConfig.port" />

	<!--Setting appender for logs to be pushed to logstash directly over TCP. -->
	<appender name="stash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		<destination>${logstash_hostname}:${logstash_port}</destination>
		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<fieldNames>
				<message>log_message</message>
			</fieldNames>
		</encoder>
	</appender>
	<root level="info">
		<appender-ref ref="stash" />
	</root>
</configuration>
```

The below property is present externally in sample-service-dev.yml which is retrieved by the spring config server:
```yml
logstash:
  tcpConfig: 
    hostname: xx.xx.xx.xx
    port: xxxxx
```

During start-up, i get the below exception:

```error
00:35:53,586 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@1a3869f4 - Could not invoke method addDestination in class net.logstash.logback.appender.LogstashTcpSocketAppender with parameter of type java.lang.String java.lang.reflect.InvocationTargetException
	at java.lang.reflect.InvocationTargetException
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.invokeMethodWithSingleParameterOnThisObject(PropertySetter.java:251)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.addBasicProperty(PropertySetter.java:282)
	at 	at ch.qos.logback.core.joran.action.NestedBasicPropertyIA.body(NestedBasicPropertyIA.java:98)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:46)
	at 	at com.helloworld.sample.Application.main(Application.java:9)
Caused by: java.lang.IllegalArgumentException: Invalid destination 'logstash.tcpConfig.hostname:logstash.tcpConfig.port': unparseable port (was 'logstash.tcpConfig.port').
	at 	at net.logstash.logback.appender.destination.DestinationParser.parse(DestinationParser.java:79)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender.addDestination(AbstractLogstashTcpSocketAppender.java:953)
	at 	... 25 common frames omitted
00:35:53,727 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.fieldnames.LogstashFieldNames] for [fieldNames] property
00:35:53,733 |-ERROR in net.logstash.logback.appender.LogstashTcpSocketAppender[stash] - No destination was configured. Use <destination> to add one or more destinations to the appender
00:35:53,734 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
00:35:53,734 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
00:35:53,734 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stash] to Logger[ROOT]
00:35:53,734 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
00:35:53,736 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@63440df3 - Registering current configuration as safe fallback point

00:35:56.615 [main]
				INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
00:35:56.640 [main]
				INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
00:35:56.762 [main]
				INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
00:36:00.481 [main]
				INFO  i.m.d.c.c.DistributedPropertySourceLocator - Resolved 1 configuration sources from client: compositeConfigurationClient(spring-cloud-config-client)
00:36:01.703 [main]
				INFO  io.micronaut.runtime.Micronaut - Startup completed in 7944ms. Server Running: http://localhost:8080
 ```

Please find the link to the github project: [ https://github.com/gokulraghu/logback-config.git](url)

Environment Details: 
Micronaut Version: 1.2.9
JDK Version: Java 1.8.0_212

Thanks ,
Gokul

**Comment by graemerocher** [comment]
Please ask questions on gitter. Thanks https://gitter.im/micronautfw
