### ISSUE TITLE
Error while starting app using Java 8 and version 2.0.0.M3 in JDK1.8

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#3240]
### Steps to Reproduce

1. Clone repository https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot
2. Navigate to `book-api/micronaut-book-api` folder
3. Run `./gradlew clean run`

### Expected Behaviour

As the app is configured in Gradle as Java 8, it should run in JDK 1.8

### Actual Behaviour

App doesn't run in JDK 1.8. In JDK 11 it does.

This is the exception
```
08:52:54.886 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Prohibited package name: java.lang
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Prohibited package name: java.lang
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1456)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2682)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:216)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
        at com.mycompany.micronautbookapi.Application.main(Application.java:8)
Caused by: java.lang.SecurityException: Prohibited package name: java.lang
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at io.micronaut.core.io.service.SoftServiceLoader$ServiceLoaderIterator.next(SoftServiceLoader.java:234)
        at io.micronaut.core.io.service.SoftServiceLoader$ServiceLoaderIterator.next(SoftServiceLoader.java:183)
        at io.micronaut.core.io.service.SoftServiceLoader$1.next(SoftServiceLoader.java:160)
        at io.micronaut.core.io.service.SoftServiceLoader$1.next(SoftServiceLoader.java:136)
        at io.micronaut.core.beans.DefaultBeanIntrospector.getIntrospections(DefaultBeanIntrospector.java:93)
        at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:64)
        at io.micronaut.core.reflect.InstantiationUtils.tryInstantiate(InstantiationUtils.java:165)
        at io.micronaut.context.RequiresCondition.matchesCustomConditions(RequiresCondition.java:354)
        at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
        at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:107)
        at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:47)
        at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:89)
        at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$36(DefaultBeanContext.java:1629)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1630)
        at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:225)
        at io.micronaut.context.DefaultBeanContext.isCandidatePresent(DefaultBeanContext.java:2885)
        at io.micronaut.context.DefaultBeanContext.containsBean(DefaultBeanContext.java:694)
        at io.micronaut.context.BeanDefinitionRegistry.containsBean(BeanDefinitionRegistry.java:355)
        at io.micronaut.context.RequiresCondition.matchesPresenceOfBeans(RequiresCondition.java:543)
        at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:211)
        at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:107)
        at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:47)
        at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:89)
        at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$36(DefaultBeanContext.java:1629)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1630)
        at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:225)
        at io.micronaut.context.DefaultBeanContext.isCandidatePresent(DefaultBeanContext.java:2885)
        at io.micronaut.context.DefaultBeanContext.containsBean(DefaultBeanContext.java:694)
        at io.micronaut.context.BeanDefinitionRegistry.containsBean(BeanDefinitionRegistry.java:355)
        at io.micronaut.context.RequiresCondition.matchesPresenceOfBeans(RequiresCondition.java:543)
        at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:211)
        at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:107)
        at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:47)
        at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:89)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2078)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1454)
        ... 8 common frames omitted
```

### Environment Information

- **Operating System**: Mac OS X
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** JDK1.8 and JDK11

### Example Application

Link to GitHub app: https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot

**Comment by jameskleeh** [comment]
@ivangfr Remove `@Introspected` from `BookNotFoundException`

**Comment by ivangfr** [comment]
Hey @jameskleeh yes, removing `@ Introspected` from `BookNotFoundException` will work when running `./gradlew clean run`. However, if I _eventually_ compile to native image and run it, it won't work.

**Comment by graemerocher** [comment]
For your comparison for Docker builds for the JVM (non native) we recommend using JIB and not shadow JAR (https://micronaut.io/launch/ select feature JIB)

As for the bug it seems we don't support introspections on `BookNotFoundException` at the moment, however you can use `@TypeHint(value=BookNotFoundException.class, accessType={AccessType.ALL_PUBLIC, AccessType.ALL_DECLARED_CONSTRUCTORS})` instead until we resolve the issue.

**Comment by ivangfr** [comment]
Hi @graemerocher I will use JIB for Micronaut JVM Docker builds. Thanks for pointing me that.

Btw, about the bug, just to let you know, before at the commit `284429377ceb6f2f4d3022a9205f240fbed54208`, in the same example that I shared, I was using the version [1.2.10](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/blob/284429377ceb6f2f4d3022a9205f240fbed54208/book-api/micronaut-book-api/build.gradle#L32) and I didn't have any problem with the `@Introspected` annotation in [BookNotFoundException](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/blob/284429377ceb6f2f4d3022a9205f240fbed54208/book-api/micronaut-book-api/src/main/java/com/mycompany/micronautbookapi/exception/BookNotFoundException.java#L5)

**Comment by graemerocher** [comment]
Yes it is a bug we will get it fixed. In the meantime you can use the aforementioned workaround
