### ISSUE TITLE
AbstractExecutor illegal access from FunctionInitializer subclass

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#3360]
#3305 # Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Java function using `FunctionIntitializer`
2. Add all inherited constructors
3. Call the constructor with the `ApplicationContext`

### Expected Behaviour

The function is created and injected.

### Actual Behaviour

An exception is thrown:

```
tried to access class io.micronaut.function.executor.AbstractExecutor from class cz.orany.m20f.$MnTwoZeroFunctionHandlerDefinition$$exec1
java.lang.IllegalAccessError: tried to access class io.micronaut.function.executor.AbstractExecutor from class cz.orany.m20f.$MnTwoZeroFunctionHandlerDefinition$$exec1
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:62)
	at io.micronaut.context.DefaultBeanContext.lambda$null$38(DefaultBeanContext.java:1692)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidatesForInstance$41(DefaultBeanContext.java:1694)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidatesForInstance(DefaultBeanContext.java:1676)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:749)
	at io.micronaut.function.executor.FunctionInitializer.injectThis(FunctionInitializer.java:122)
	at io.micronaut.function.executor.FunctionInitializer.<init>(FunctionInitializer.java:70)
	at io.micronaut.function.executor.FunctionInitializer.<init>(FunctionInitializer.java:57)
	at cz.orany.m20f.MnTwoZeroFunctionHandler.<init>(MnTwoZeroFunctionHandler.java:25)
	at cz.orany.m20f.MnTwoZeroFunctionHandlerSpec.setup(MnTwoZeroFunctionHandlerSpec.groovy:18)


```

### Environment Information

- **Operating System**: Darwin Kernel Version 19.4.0
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_212-b10)

### Example Application

https://github.com/musketyr/mn-two-zero-function

**Comment by graemerocher** [comment]
Seems to be fixed in master
