### ISSUE TITLE
Mongo feature doesn't create MongoClient bean

### ISSUE THREAD

**Issue by katoquro** [micronaut-projects/micronaut-core#343]
### Steps to Reproduce

1. create new project via `mn create-app mn-mongo-check -features=mongo-reactive,groovy,spock`
2. add controller MongoController.groovy
```
package mn.mongo.check

import com.mongodb.async.client.MongoClient
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.HttpStatus


@Controller("/mongo")
class MongoController {

    MongoClient mongoClient

    MongoController(MongoClient mongoClient) {
        this.mongoClient = mongoClient
    }

    @Get("/")
    HttpStatus index() {
        mongoClient.getDatabase('test')
        return HttpStatus.OK
    }
}
```
3. run `./gradlew run` or in IDEA with enabled "Annotation Processing" 
4. call localhost:<port from log>/mongo

### Expected Behaviour

`mongoClient` is injected and controller returns response code 200

### Actual Behaviour

```
HTTP/1.1 500 Internal Server Error
Date: Tue, 3 Jul 2018 13:23:36 GMT
content-length: 345
content-type: application/json

{
    "message": "Internal Server Error: Failed to inject value for parameter [mongoClient] of class: mn.mongo.check.MongoController\n\nMessage: No bean of type [com.mongodb.async.client.MongoClient] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.\nPath Taken: new MongoController([MongoClient mongoClient])"
}
```

trace from server
```
13:23:36.957 [nioEventLoopGroup-1-5] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for parameter [mongoClient] of class: mn.mongo.check.MongoController

Message: No bean of type [com.mongodb.async.client.MongoClient] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new MongoController([MongoClient mongoClient])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [mongoClient] of class: mn.mongo.check.MongoController

Message: No bean of type [com.mongodb.async.client.MongoClient] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new MongoController([MongoClient mongoClient])
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:962)
        at mn.mongo.check.$MongoControllerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1215)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1577)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1348)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1329)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:474)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:1990)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:232)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$13(RoutingInBoundHandler.java:1149)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14419)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
        at io.reactivex.Flowable.subscribe(Flowable.java:14419)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14419)
        at io.reactivex.Flowable.subscribe(Flowable.java:14368)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14419)
        at io.reactivex.Flowable.subscribe(Flowable.java:14365)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:261)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:226)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.mongodb.async.client.MongoClient] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1335)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:833)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:954)
        ... 29 common frames omitted
```

### Environment Information

- **Operating System**: Darwin am-malyhin-osx2 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
- **Micronaut Version:** 1.0.0.M2
- **JDK Version:** 1.8.0_172

```
mn --version                                                                                                                                                                                   
| Micronaut Version: 1.0.0.M2
| JVM Version: 1.8.0_172
```

P.S. my mongo is started on the localhost and default port. This part in doc https://docs.micronaut.io/latest/guide/index.html#mongoSupport

**Comment by graemerocher** [comment]
What do you have in `application.yml`? Have you configured the mongo URI?

**Comment by katoquro** [comment]
Everything is default after generation. I just added MongoController 

application.yml
```
---
micronaut:
    application:
        name: mn-mongo-check
                
#Uncomment to set server port
#    server:
#        port: 8080

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
```

**Comment by graemerocher** [comment]
Turns out the documentation refers to `com.mongodb.async.client.MongoClient` instead of `com.mongodb.MongoClient`. So this is a documentation error. Thanks for the report.

**Comment by graemerocher** [comment]
Also the documentation doesn't mention you have to add `org.mongodb:mongo-java-driver` to use the blocking driver.

**Comment by jamesrloveday** [comment]
I've added the blocking java driver, but still get the same exception above. I have a different architecture than above but have stuck with the default settings.

**Comment by KothasLT** [comment]
I have the same problem. I want to use native driver so I include only `org.mongodb:mongo-java-driver` dependency and not `io.micronaut.configuration:micronaut-mongo-reactive`, but during startup the error occurs:
`Message: No bean of type [com.mongodb.client.MongoClient] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.`
I run application with IntelliJ with annotations processing enabled.

**Comment by graemerocher** [comment]
`io.micronaut.configuration:micronaut-mongo-reactive` is still required, it just injects a blocking driver when needed. See https://github.com/micronaut-projects/micronaut-core/blob/master/configurations/mongo-reactive/src/test/groovy/io/micronaut/configuration/mongo/reactive/MongoConfigurationSpec.groovy for an example

**Comment by jamesrloveday** [comment]
Got it, thank that's awesome. I am loving what you guys are doing. I did get it working using the reactive streaming client but I'll make a change to the program to use the blocking driver instead as I want to better understand how it's doing it's thing, seriously though guys this is fantastic and what java has needed for a long time.

**Comment by KothasLT** [comment]
Thanks, adding `io.micronaut.configuration:micronaut-mongo-reactive` dependency resolved the issue. @graemerocher Do you think that adding a note in [documentation](https://docs.micronaut.io/latest/guide/index.html#mongoSupport) that both dependencies are required for blocking driver could help other users as well?

**Comment by graemerocher** [comment]
Improvements to the docs welcome!
