### ISSUE TITLE
Introspection throws an exception with the Lombok's @Builder annotation on constructor if a nested list property is used

### ISSUE THREAD

**Issue by alexpoletaev** [micronaut-projects/micronaut-core#3451]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone demo project
2. Run tests
3. Observe that the micronaut.issue.DeserializerTest#testWithLombok test throws an exception.

### Expected Behaviour

Json should be successfully converted into DummyLombok object how it happens with a Dummy class, where the Lombok is not used. **Please note, that this happens only when the class has an `@Introspected` annotation, the property is a NESTED list and a `@Builder` annotation is used on constructor.** It works fine if the property is NOT a nested list or the `@Builder` annotation is used on a class level.

### Actual Behaviour

The exception is thrown:
`E
java.lang.NoClassDefFoundError: E
	at micronaut.issue.model.$DummyLombok$Introspection.getConstructorArguments(Unknown Source)
	at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionDeserializerModifier.updateBuilder(BeanIntrospectionModule.java:275)
.....
`

### Environment Information

- **Operating System**: Linux Manjaro
- **Micronaut Version:** 1.3.6
- **JDK Version:** 11
- **Lombok Version:** 1.18.12

### Example Application

https://github.com/alexpoletaev/micronaut-lombok-introspection-issue

run tests with `gradle test`

**Comment by graemerocher** [comment]
Triage: Type Bug. The linked project is a concrete reproducer, but it targets Micronaut 1.3.6, Lombok 1.18.12, and the old Jackson introspection integration. No exact duplicate or landed fix was found. Please rerun on current 5.2.x with current Lombok/Jackson/Serde dependencies and attach the generated introspection or current stack trace. Suggested fix if it still fails: preserve the resolved generic element type and builder constructor metadata for nested-list properties, then add a focused Lombok `@Builder` + `@Introspected` regression test across JSON codecs.
