### ISSUE TITLE
Error binding JsonError in declarative HTTP Client

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3482]
### Steps to Reproduce

1. Generate Project 

<img width="1126" alt="Screenshot 2020-06-11 at 11 11 37" src="https://user-images.githubusercontent.com/864788/84367327-5f639680-abd4-11ea-8a72-3f352127ad8b.png">

2. Create a Controller

`src/main/java/com/example/HomeController.java`

```java
package com.example;

import io.micronaut.http.HttpStatus;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Status;
import io.micronaut.http.exceptions.HttpStatusException;

@Controller
public class HomeController {

    @Status(HttpStatus.OK)
    @Get
    public void index() {
        throw new HttpStatusException(HttpStatus.BAD_REQUEST, "Item not found");
    }
}
```

`HttpStatusException` is handled by https://github.com/micronaut-projects/micronaut-core/blob/master/http-server/src/main/java/io/micronaut/http/server/exceptions/HttpStatusHandler.java

3. Create a test:

`src/test/groovy/com/example/HomeSpec.groovy`

```groovy
package com.example

import io.micronaut.http.HttpStatus
import io.micronaut.http.MediaType
import io.micronaut.http.annotation.Get
import io.micronaut.http.client.annotation.Client
import io.micronaut.http.client.exceptions.HttpClientResponseException
import io.micronaut.http.hateoas.JsonError
import io.micronaut.test.annotation.MicronautTest
import spock.lang.Specification

import javax.inject.Inject

@MicronautTest
class HomeSpec extends Specification {
    @Inject
    AppClient client

    void 'test binding JsonError works'() {
        when:
        client.index()

        then:
        HttpClientResponseException e = thrown()
        e.status == HttpStatus.BAD_REQUEST

        when:
        Optional<JsonError> jsonErrorOptional = e.response.getBody(JsonError)

        then:
        jsonErrorOptional.isPresent()
        jsonErrorOptional.get().message == "Item not found"
    }

    @Client(value = "/", errorType = JsonError)
    static interface AppClient {
        @Get(uri = "/", consumes = MediaType.APPLICATION_JSON)
        HttpStatus index()
    }
}
```

Create `src/test/resources/logback.xml` to see http logs. 

```xml
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <withJansi>true</withJansi>
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
    </root>

    <logger name="io.micronaut.http" level="trace" />
</configuration>
```

### Expected Behaviour

I expected test to pass.

### Actual Behaviour

Test fails: 

```
11:10:14.576 [nioEventLoopGroup-1-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP Request: GET /
11:10:14.576 [nioEventLoopGroup-1-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Chosen Server: localhost(58316)
11:10:14.578 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
11:10:14.578 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - host: localhost:58316
11:10:14.578 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
11:10:14.598 [nioEventLoopGroup-1-3] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:58316 Received Request: GET /
11:10:14.602 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /
11:10:14.608 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - / to controller class com.example.HomeController
11:10:14.641 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [Item not found] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@70902932
11:10:14.836 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - HTTP Client Response Received for Request: GET http://localhost:58316/
11:10:14.836 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Status Code: 400 Bad Request
11:10:14.836 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
11:10:14.836 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 294
11:10:14.836 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
11:10:14.837 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Response Body
11:10:14.837 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
11:10:14.837 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - {"message":"Item not found","logref":{"present":false},"path":{"present":false},"_links":{"self":{"href":"/","templated":false,"profile":{"present":false},"deprecation":{"present":false},"title":{"present":false},"hreflang":{"present":false},"type":{"present":false},"name":{"present":false}}}}
11:10:14.837 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
11:10:14.878 [nioEventLoopGroup-1-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Error decoding HTTP error response body: Error decoding stream for type [class io.micronaut.http.hateoas.JsonError]: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (byte[])"{"message":"Item not found","logref":{"present":false},"path":{"present":false},"_links":{"self":{"href":"/","templated":false,"profile":{"present":false},"deprecation":{"present":false},"title":{"present":false},"hreflang":{"present":false},"type":{"present":false},"name":{"present":false}}}}"; line: 1, column: 38] (through reference chain: io.micronaut.http.hateoas.JsonError["logref"])
io.micronaut.http.codec.CodecException: Error decoding stream for type [class io.micronaut.http.hateoas.JsonError]: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (byte[])"{"message":"Item not found","logref":{"present":false},"path":{"present":false},"_links":{"self":{"href":"/","templated":false,"profile":{"present":false},"deprecation":{"present":false},"title":{"present":false},"hreflang":{"present":false},"type":{"present":false},"name":{"present":false}}}}"; line: 1, column: 38] (through reference chain: io.micronaut.http.hateoas.JsonError["logref"])
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:178)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:256)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:195)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:172)
	at io.micronaut.http.client.exceptions.HttpClientResponseException.initResponse(HttpClientResponseException.java:94)
	at io.micronaut.http.client.exceptions.HttpClientResponseException.<init>(HttpClientResponseException.java:63)
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelRead0(DefaultHttpClient.java:2034)
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelRead0(DefaultHttpClient.java:1964)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:190)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:185)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (byte[])"{"message":"Item not found","logref":{"present":false},"path":{"present":false},"_links":{"self":{"href":"/","templated":false,"profile":{"present":false},"deprecation":{"present":false},"title":{"present":false},"hreflang":{"present":false},"type":{"present":false},"name":{"present":false}}}}"; line: 1, column: 38] (through reference chain: io.micronaut.http.hateoas.JsonError["logref"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1464)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1238)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1148)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:257)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3495)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:175)
	... 49 common frames omitted
11:10:14.880 [nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateoas.JsonError
11:10:14.881 [Test worker] TRACE i.m.h.client.netty.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateoas.JsonError
11:10:14.881 [Test worker] TRACE i.m.h.client.netty.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateoas.JsonError
11:10:14.881 [Test worker] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.example.HomeSpec$AppClient$Intercepted] executed with error: Bad Request
io.micronaut.http.client.exceptions.HttpClientResponseException: Bad Request
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelRead0(DefaultHttpClient.java:2034)
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelRead0(DefaultHttpClient.java:1964)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:190)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:185)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
11:10:15.018 [Test worker] TRACE i.m.h.client.netty.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateoas.JsonError
11:10:18.756 [Test worker] TRACE i.m.h.client.netty.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateoas.JsonError

Condition not satisfied:

jsonErrorOptional.isPresent()
|                 |
Optional.empty    false

Condition not satisfied:

jsonErrorOptional.isPresent()
|                 |
Optional.empty    false

	at com.example.HomeSpec.test binding JsonError works(DemoSpec.groovy:31)


```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8

### Example Application

https://github.com/grails-core-issues-forks/micronaut-core-3482

**Comment by ilopmar** [comment]
Related to #3483

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/29abf62eb79ba008804b2634565b6af54f348487
