### ISSUE TITLE
Eureka support error with Redis Health monitor

### ISSUE THREAD

**Issue by tkec** [micronaut-projects/micronaut-core#350]
### Steps to Reproduce

1.  Eureka server with Spring Cloud version `Finchley.RELEASE`.
```
@SpringBootApplication
@EnableEurekaServer
public class SpringCloudApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringCloudApplication.class, args);
	}
}
```
application.properties:
```
spring.application.name=spring-eureka-test
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
```
2. Micronaut pom.xml
```
         <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>http-server-netty</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>inject</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>runtime</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>inject-java</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>session</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.configuration</groupId>
            <artifactId>redis-lettuce</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>management</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>discovery-client</artifactId>
            <scope>compile</scope>
        </dependency>
```

 application.yml
```
micronaut:
    application:
        name: micronaut-hello-world
    server:
        port: 8081
    session:
        http:
            redis:
                enabled: true
redis:
    uri: redis://localhost:6379
eureka:
    client:
        registration:
            enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
```

### Expected Behaviour

Micronaut as a eureka instance

### Actual Behaviour

Micronaut update status to eureka error

### Environment Information

- **Operating System**: Windows7
- **Micronaut Version:** 1.0.0.M2
- **JDK Version:** JDK8

### Example Exception Trace

About 1 minute after started, the below log printed, then the error log from eureka client printed.

Micronaut Exception Trace:
```
2018-07-10 13:44:15.801 [lettuce-nioEventLoop-4-2] DEBUG i.m.m.h.monitor.HealthMonitorTask - Health monitor check failed with status HealthStatus{name='DOWN', description=null, operational=false, severity=1000}
```
```
2018-07-10 13:44:15.801 [lettuce-nioEventLoop-4-2] DEBUG i.m.m.h.monitor.HealthMonitorTask - Health monitor check failed with status HealthStatus{name='DOWN', description=null, operational=false, severity=1000}
2018-07-10 13:44:21.216 [pool-1-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.health.HeartbeatTask@315f607f] for type [class io.micronaut.health.HeartbeatTask] and qualifier [null]
2018-07-10 13:44:21.216 [pool-1-thread-1] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.health.HeartbeatEvent[source=io.micronaut.http.server.netty.NettyEmbeddedServerInstance@49206065]
2018-07-10 13:44:21.216 [pool-1-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <HeartbeatEvent> io.micronaut.context.event.ApplicationEventListener 
2018-07-10 13:44:21.217 [pool-1-thread-1] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [io.micronaut.context.event.ApplicationEventListener] for qualifier: <HeartbeatEvent> 
2018-07-10 13:44:21.217 [pool-1-thread-1] DEBUG i.m.context.DefaultBeanContext - Found 1 beans for type [<HeartbeatEvent> io.micronaut.context.event.ApplicationEventListener]: [io.micronaut.discovery.eureka.registration.EurekaAutoRegistration@d0865a3] 
2018-07-10 13:44:21.222 [nioEventLoopGroup-5-4] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: PUT /eureka/apps/micronaut-hello-world/micronaut-hello-world%3A8081/status
2018-07-10 13:44:21.222 [nioEventLoopGroup-5-4] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: localhost(8761)
2018-07-10 13:44:21.258 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted
2018-07-10 13:44:21.259 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted] for type: class io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted
2018-07-10 13:44:21.259 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted]
2018-07-10 13:44:21.259 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.aop.Intercepted
2018-07-10 13:44:21.263 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.management.endpoint.info.InfoEndpoint
2018-07-10 13:44:21.264 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.management.endpoint.info.InfoEndpoint] for type: class io.micronaut.management.endpoint.info.InfoEndpoint
2018-07-10 13:44:21.264 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.management.endpoint.info.InfoEndpoint]
2018-07-10 13:44:21.264 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: io.micronaut.management.endpoint.info.InfoEndpoint] for type: io.micronaut.management.endpoint.info.InfoEndpoint 
2018-07-10 13:44:21.264 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted] will not be loaded due to failing conditions:
2018-07-10 13:44:21.264 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.discovery.consul.ConsulConfiguration] present within context
2018-07-10 13:44:21.277 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.277 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$ConfigurationInfoSourceDefinition$Intercepted, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: micronaut.hello.client.HelloClient$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$GitInfoSourceDefinition$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$BuildInfoSourceDefinition$Intercepted] for type: interface io.micronaut.aop.Intercepted
2018-07-10 13:44:21.277 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$ConfigurationInfoSourceDefinition$Intercepted, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: micronaut.hello.client.HelloClient$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$GitInfoSourceDefinition$Intercepted, Definition: io.micronaut.management.endpoint.info.source.$BuildInfoSourceDefinition$Intercepted]
2018-07-10 13:44:21.277 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.core.naming.Described
2018-07-10 13:44:21.278 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.kubernetes.KubernetesDiscoveryClient] will not be loaded due to failing conditions:
2018-07-10 13:44:21.278 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * None of the required environments [k8s] are active: []
2018-07-10 13:44:21.279 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted] will not be loaded due to failing conditions:
2018-07-10 13:44:21.279 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.discovery.consul.ConsulConfiguration] present within context
2018-07-10 13:44:21.282 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.config.ConsulConfigurationClient] will not be loaded due to failing conditions:
2018-07-10 13:44:21.282 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [interface io.micronaut.discovery.consul.client.v1.ConsulClient] present within context
2018-07-10 13:44:21.283 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.CachingCompositeDiscoveryClient] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.283 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.283 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.discovery.config.DefaultCompositeConfigurationClient] for type: interface io.micronaut.core.naming.Described
2018-07-10 13:44:21.283 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.discovery.config.DefaultCompositeConfigurationClient]
2018-07-10 13:44:21.283 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.discovery.eureka.client.v2.EurekaOperations
2018-07-10 13:44:21.284 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted] for type: interface io.micronaut.discovery.eureka.client.v2.EurekaOperations
2018-07-10 13:44:21.284 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted]
2018-07-10 13:44:21.284 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.discovery.eureka.client.v2.EurekaClient
2018-07-10 13:44:21.285 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted] for type: interface io.micronaut.discovery.eureka.client.v2.EurekaClient
2018-07-10 13:44:21.285 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted]
2018-07-10 13:44:21.285 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface java.io.Closeable
2018-07-10 13:44:21.286 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.kubernetes.KubernetesDiscoveryClient] will not be loaded due to failing conditions:
2018-07-10 13:44:21.286 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * None of the required environments [k8s] are active: []
2018-07-10 13:44:21.288 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted] will not be loaded due to failing conditions:
2018-07-10 13:44:21.288 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.discovery.consul.ConsulConfiguration] present within context
2018-07-10 13:44:21.291 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.CachingCompositeDiscoveryClient] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.291 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.291 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41d477ed, Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.http.client.DefaultHttpClient, Definition: io.micronaut.http.server.netty.NettyHttpServer, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope, Definition: io.micronaut.scheduling.processor.ScheduledMethodProcessor, Definition: io.micronaut.http.client.scope.ClientScope] for type: interface java.io.Closeable
2018-07-10 13:44:21.291 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41d477ed, Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.http.client.DefaultHttpClient, Definition: io.micronaut.http.server.netty.NettyHttpServer, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope, Definition: io.micronaut.scheduling.processor.ScheduledMethodProcessor, Definition: io.micronaut.http.client.scope.ClientScope]
2018-07-10 13:44:21.292 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.aop.Introduced
2018-07-10 13:44:21.293 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted] will not be loaded due to failing conditions:
2018-07-10 13:44:21.293 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.discovery.consul.ConsulConfiguration] present within context
2018-07-10 13:44:21.293 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: micronaut.hello.client.HelloClient$Intercepted] for type: interface io.micronaut.aop.Introduced
2018-07-10 13:44:21.293 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: micronaut.hello.client.HelloClient$Intercepted]
2018-07-10 13:44:21.293 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface java.lang.AutoCloseable
2018-07-10 13:44:21.295 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.kubernetes.KubernetesDiscoveryClient] will not be loaded due to failing conditions:
2018-07-10 13:44:21.295 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * None of the required environments [k8s] are active: []
2018-07-10 13:44:21.296 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted] will not be loaded due to failing conditions:
2018-07-10 13:44:21.296 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.discovery.consul.ConsulConfiguration] present within context
2018-07-10 13:44:21.297 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.configuration.lettuce.DefaultRedisClusterClientFactory] will not be loaded due to failing conditions:
2018-07-10 13:44:21.297 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * Required property [redis.uris] not present
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.configuration.lettuce.DefaultRedisClusterClientFactory] will not be loaded due to failing conditions:
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.condition.Condition - * Required property [redis.uris] not present
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.CachingCompositeDiscoveryClient] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Bean [class io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted] replaces existing bean of type [class io.micronaut.discovery.DefaultCompositeDiscoveryClient]
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41d477ed, Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.configuration.lettuce.DefaultRedisClientFactory, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.http.client.DefaultHttpClient, Definition: io.micronaut.http.server.netty.NettyHttpServer, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope, Definition: io.micronaut.configuration.lettuce.NamedRedisClientFactory, Definition: io.micronaut.scheduling.processor.ScheduledMethodProcessor, Definition: io.micronaut.configuration.lettuce.DefaultRedisClientFactory, Definition: io.micronaut.http.client.scope.ClientScope, Definition: io.micronaut.configuration.lettuce.NamedRedisClientFactory] for type: interface java.lang.AutoCloseable
2018-07-10 13:44:21.298 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.configuration.lettuce.NamedRedisServersConfiguration
2018-07-10 13:44:21.299 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.configuration.lettuce.NamedRedisServersConfiguration] for type: class io.micronaut.configuration.lettuce.NamedRedisServersConfiguration
2018-07-10 13:44:21.299 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: []
2018-07-10 13:44:21.299 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.configuration.lettuce.NamedRedisServersConfiguration
2018-07-10 13:44:21.299 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.configuration.lettuce.NamedRedisServersConfiguration] for type: class io.micronaut.configuration.lettuce.NamedRedisServersConfiguration
2018-07-10 13:44:21.300 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: []
2018-07-10 13:44:21.300 [nioEventLoopGroup-5-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41d477ed, Definition: io.micronaut.discovery.eureka.client.v2.AbstractEurekaClient$Intercepted, Definition: io.micronaut.configuration.lettuce.DefaultRedisClientFactory, Definition: io.micronaut.discovery.client.CachingCompositeDiscoveryClient, Definition: io.micronaut.discovery.client.$CachingCompositeDiscoveryClientDefinition$Intercepted, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.http.client.DefaultHttpClient, Definition: io.micronaut.http.server.netty.NettyHttpServer, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope, Definition: io.micronaut.scheduling.processor.ScheduledMethodProcessor, Definition: io.micronaut.configuration.lettuce.DefaultRedisClientFactory, Definition: io.micronaut.http.client.scope.ClientScope]
2018-07-10 13:44:21.303 [nioEventLoopGroup-5-4] ERROR i.m.d.registration.AutoRegistration - Error reporting state to Eureka: 
io.micronaut.http.client.exceptions.HttpClientResponseException: 
	at io.micronaut.http.client.DefaultHttpClient$6.channelRead0(DefaultHttpClient.java:1372)
	at io.micronaut.http.client.DefaultHttpClient$6.channelRead0(DefaultHttpClient.java:1311)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:184)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

Spring Cloud Eureka Server Exception Trace:
```
2018-07-10 13:44:21.254 ERROR 29500 --- [nio-8761-exec-6] c.n.eureka.resources.InstanceResource    : Error updating instance micronaut-hello-world:8081 for status null
2018-07-10 13:44:36.240 ERROR 29500 --- [nio-8761-exec-9] c.n.eureka.resources.InstanceResource    : Error updating instance micronaut-hello-world:8081 for status null
```

**Comment by graemerocher** [comment]
Must be a change in the latest version of Eureka, will take a look

**Comment by graemerocher** [comment]
Can't reproduce this personally. Tested following the above steps with `Finchley.RELEASE` testing both the case where the server reports a health status of `UP` and `DOWN` and the described error never occurred

**Comment by tkec** [comment]
@graemerocher I missed some configurations, and the missed part is Redis session and `io.micronaut:management`, and I think the problem is due to `HealthMonitorTask` and `RedisHealthIndicator`. Would you please check it again?

**Comment by graemerocher** [comment]
Ok I will try again to reproduce
