### ISSUE TITLE
Scoped proxies not compatible with @Factory

### ISSUE THREAD

**Issue by puneetbehl** [micronaut-projects/micronaut-core#361]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a class called `V8Engine.java` as:
```java
public class V8Engine implements Engine {

    final int cylinders = 8;
    final CrankShaft crankShaft;

    V8Engine(CrankShaft crankShaft) {
        this.crankShaft = crankShaft;
    }

    @Override
    public int getCylinders() {
        return this.cylinders;
    }

    @Override
    public String start() {
        return "Starting V8";
    }
}
```
2. Now, create a factory to create V8Engine bean as follows:
```java
@Factory
public class EngineFactory {

    @Bean
    @Singleton
    @Refreshable
    V8Engine v8Engine() {
        CrankShaft crankShaft = new CrankShaft();
        return new V8Engine(crankShaft);
    }
}
```
3. Create a JUnit test to make sure bean is initialized properly.
```java
    @Test
    public void testV8Engine() {
        ApplicationContext context = ApplicationContext.run();
        V8Engine bean = context.getBean(V8Engine.class);

        Assert.assertNotNull(bean);
    }
```

### Expected Behaviour

Bean `V8Engine` should be created in the test.

### Actual Behaviour

A Exception is thrown complaining about no bean of type [testapp.CrankShaft] exists.

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [crankShaft] of class: testapp.$EngineFactory$V8EngineDefinition$Intercepted

Message: No bean of type [testapp.CrankShaft] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new $EngineFactory$V8EngineDefinition$Intercepted([CrankShaft crankShaft],BeanContext beanContext,Interceptor[] interceptors)

	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:962)
	at testapp.$$EngineFactory$V8EngineDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1215)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1577)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1348)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1329)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:479)
	at testapp.EngineFactoryTest.testV8Engine(EngineFactoryTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [testapp.CrankShaft] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1335)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:833)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:954)
	... 29 more
```

### Environment Information

- **Operating System**: macOS High Sierra (v10.13.5)
- **Micronaut Version:** Master branch
- **JDK Version:** 1.8.0_152

### Example Application

[refreshable-error.zip](https://github.com/micronaut-projects/micronaut-core/files/2173875/refreshable-error.zip)

**Comment by puneetbehl** [comment]
@jameskleeh please let me know if this is what you mean by isolating the issue?

**Comment by jameskleeh** [comment]
@puneetbehl Yeah that looks great

**Comment by jeffbrown** [comment]
For case like this where `V8Engine` isn't marked with `@Singleton` (or similar), is there any reason that the generated subclass proxy couldn't be made to have a no-arg constructor?

**Comment by jeffbrown** [comment]
(I deleted that last comment... as soon as I saved it, I knew the answer...) ;)

**Comment by jameskleeh** [comment]
This should now throw an exception
