### ISSUE TITLE
Annotating with @Validate a controller fails in Kotlin

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#365]
### Task List

`$ mn create-app validatedissue --features=kotlin`
`$ cd validatedissue`
`validatedissue$ mn
`mn> create-controller Email
| Rendered template Controller.kt to destination src/main/kotlin/validatedissue/EmailController.kt
| Rendered template ControllerTest.kt to destination src/test/kotlin/validatedissue/EmailControllerTest.kt`

Add validation dependencies to`build.gradle`

  ```
  compile "io.micronaut:validation"
 compile "io.micronaut.configuration:hibernate-validator"
  ```

Open EmailController and annotate it with `io.micronaut.validation.Validated`

```
package validatedissue

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.HttpStatus
import io.micronaut.validation.Validated

@Validated
@Controller("/email")
class EmailController {

    @Get("/")
    fun index(): HttpStatus {
        return HttpStatus.OK
    }
}
```

Try to run the app: 

```
$ ./gradlew run
w: Note: Creating bean classes for 1 type elements

> Task :run FAILED
17:07:33.764 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Cannot inherit from final class
java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
        at java.lang.Class.getGenericInterfaces(Class.java:913)
        at io.micronaut.core.reflect.GenericTypeUtils.resolveInterfaceTypeArgument(GenericTypeUtils.java:64)
        at io.micronaut.context.AbstractBeanDefinitionReference.loadType(AbstractBeanDefinitionReference.java:170)
        at io.micronaut.context.AbstractBeanDefinitionReference.isPresent(AbstractBeanDefinitionReference.java:131)
        at io.micronaut.context.AbstractBeanDefinitionReference.isEnabled(AbstractBeanDefinitionReference.java:138)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1670)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:169)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:139)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.resolveBootstrapPropertySourceLocator(DefaultApplicationContext.java:506)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:488)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:341)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:234)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:66)
        at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:174)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:65)
        at validatedissue.Application.main(Application.kt:12)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/sdelamo/.sdkman/candidates/java/8u152-zulu/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
5 actionable tasks: 4 executed, 1 up-to-date
```

### Environment Information

- **Operating System**: macOS High Sierra
- **Micronaut Version:** 1.0.0.M2
- **JDK Version:** 1.8.0_152"

**Comment by sdelamo** [comment]
A workaround is to annotate the class and the methods as `open`

```
package validatedissue

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.HttpStatus
import io.micronaut.validation.Validated

@Validated
@Controller("/email")
open class EmailController {

    @Get("/")
    open fun index(): HttpStatus {
        return HttpStatus.OK
    }
}
```

**Comment by graemerocher** [comment]
I think this a documentation issue. Any AOP advice will have the same problem with Kotlin
