### ISSUE TITLE
Squeezing memory allowance: Native app having memory issues, similar JVM app doesn't

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#3656]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

---

Hi,

I have squeezed a bit the memory available for the simple-api native and jvm (code here https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api) that I have in my Framework comparison project.

In this experiment, I gave to the docker container a maximum memory (`-m` flag) of 128MB and in the app JAVA_OPTIONS, I set `-Xmx64m`.

The jvm works fine. However, the native one that was supposed to work also, had memory problems.

Outputs below, thanks.

---

- **micronaut-simple-api-jvm**

  Run docker container
  ```
  docker run --rm --name micronaut-simple-api-jvm -p 9082:8080 \
    -m 128M -e JAVA_OPTIONS='-Xmx64m' \
    docker.mycompany.com/micronaut-simple-api-jvm:1.0.0
  ```

  Ab test
  ```
  ab -c 10 -n 7500 http://localhost:9082/api/greeting?name=Ivan
  ```

  Ab test results
  ```
  This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
  Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
  Licensed to The Apache Software Foundation, http://www.apache.org/
  
  Benchmarking localhost (be patient)
  Completed 750 requests
  Completed 1500 requests
  Completed 2250 requests
  Completed 3000 requests
  Completed 3750 requests
  Completed 4500 requests
  Completed 5250 requests
  Completed 6000 requests
  Completed 6750 requests
  Completed 7500 requests
  Finished 7500 requests
  
  
  Server Software:
  Server Hostname:        localhost
  Server Port:            9082
  
  Document Path:          /api/greeting?name=Ivan
  Document Length:        27 bytes
  
  Concurrency Level:      10
  Time taken for tests:   45.044 seconds
  Complete requests:      7500
  Failed requests:        0
  Total transferred:      1147500 bytes
  HTML transferred:       202500 bytes
  Requests per second:    166.50 [#/sec] (mean)
  Time per request:       60.059 [ms] (mean)
  Time per request:       6.006 [ms] (mean, across all concurrent requests)
  Transfer rate:          24.88 [Kbytes/sec] received
  
  Connection Times (ms)
                min  mean[+/-sd] median   max
  Connect:        0    0   0.1      0       2
  Processing:     4   59  43.0     51     922
  Waiting:        4   55  42.5     47     915
  Total:          4   59  43.0     51     922
  
  Percentage of the requests served within a certain time (ms)
    50%     51
    66%     71
    75%     86
    80%     95
    90%    117
    95%    136
    98%    159
    99%    175
   100%    922 (longest request)
  ```

- **micronaut-simple-api-native**

  Run docker container
  ```
  docker run --rm --name micronaut-simple-api-native -p 9083:8080 \
    -m 128M -e JAVA_OPTIONS='-Xmx64m' \
    docker.mycompany.com/micronaut-simple-api-native:1.0.0
  ```

  Ab test
  ```
  ab -c 10 -n 7500 http://localhost:9083/api/greeting?name=Ivan
  ```

  Ab test results
  ```
  This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
  Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
  Licensed to The Apache Software Foundation, http://www.apache.org/
  
  Benchmarking localhost (be patient)
  apr_pollset_poll: The timeout specified has expired (70007)
  Total of 27 requests completed
  ```

  Checking app logs
  ```
  15:06:57.957 [nioEventLoopGroup-1-7] ERROR i.m.h.s.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: Direct buffer memory
  java.lang.OutOfMemoryError: Direct buffer memory
  	at java.nio.Bits.reserveMemory(Bits.java:175)
  	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
  	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
  	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
  	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
  	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
  	at io.netty.buffer.PoolArena.allocate(PoolArena.java:215)
  	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
  	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
  	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
  	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
  	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
  	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.lang.Thread.run(Thread.java:834)
  	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
  	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
  ```

**Comment by graemerocher** [comment]
Think this is the same as https://github.com/micronaut-projects/micronaut-aws/issues/385

native image is stricter about memory constraints than java. You would need to adjust the `-Xmx128m` parameter passed to native image

**Comment by ivangfr** [comment]
Thanks for the fast response @graemerocher 

I've set `-m 128M -e JAVA_OPTIONS='-Xmx128m'` and had the same problem;

Then, I've set `-m 256M -e JAVA_OPTIONS='-Xmx64m'` and it worked.

Running `docker stats` after the `ab test` the app was consuming 158.6MiB of 256MiB.

**Comment by croudet** [comment]
You can try to reduce netty's pool arenas size with `-Dio.netty.allocator.maxOrder=7`

**Comment by graemerocher** [comment]
I am closing this as I don't think this is a Micronaut bug or anything we can do about this. If you wish to report an issue on the GraalVM side please do so https://github.com/oracle/graal/issues
