### ISSUE TITLE
NullPointerException at compile time when using @Requires with M2E

### ISSUE THREAD

**Issue by briankramer17** [micronaut-projects/micronaut-core#3672]
### Steps to Reproduce

1. Download sample application. Add Maven nature.
2. Set Annotation Processing Mode to "Automatically configure JDT APT"
3. Open the "Error Log" view.
4. Perfom a Maven > Update Project... (Alt+F5)

### Expected Behaviour

Should compile without errors.

### Actual Behaviour
See two build errors
```
eclipse.buildId=4.16.0.I20200604-0540
java.version=11.0.7
java.vendor=Amazon.com Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data C:\Users\Brian\gitbackup -product org.eclipse.epp.package.java.product

org.eclipse.jdt.apt.pluggable.core
Error
Tue Jul 07 17:01:47 MDT 2020
Exception thrown by Java annotation processor io.micronaut.annotation.processing.BeanDefinitionInjectProcessor@58b9daf2

java.lang.Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:958)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:932)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:278)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
```
and
```
eclipse.buildId=4.16.0.I20200604-0540
java.version=11.0.7
java.vendor=Amazon.com Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data C:\Users\Brian\gitbackup -product org.eclipse.epp.package.java.product

org.eclipse.jdt.apt.pluggable.core
Error
Tue Jul 07 17:01:47 MDT 2020
Exception thrown by Java annotation processor io.micronaut.annotation.processing.TypeElementVisitorProcessor@609d74c2

java.lang.Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:958)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:932)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:278)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
```
Removing the `@Requires` annotation from `BintrayConfiguration` will make the errors go away.
This doesn't seem to be an issue with Micronaut 1.3.6
Not seeing this issue when using maven from the command line

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0
- **JDK Version:** Amazon Corretto\jdk11.0.4_10
- **IDE Version:** Eclipse 2020-06 (4.16.0)
- **Maven Version:** 3.5.3
- **M2E Version:** 1.16.0
- **M2E-APT Version:** 1.5.2

### Example Application

- https://github.com/briankramer17/micronaut-issue-test

### Further Explanation
Recently updated to Micronaut 2.0.0 for an aws lambda project(using `MicronautRequestHandler`). Kept seeing errors when I do a full build, and it usually prevents the `META-INF` services files from being generated. I was also seeing failures in tests like: 
```
BeanInstantiationException: Bean definition [io.micronaut.context.event.ApplicationEventListener] could not be loaded: HTTP Client Health Check not enabled
```
Even though heartbeat should not be enabled since `function` is one of my active environments. I made this test app to whittle down what my issue could be. I was just going to try a simple function that makes an http client call, but found I was getting the errors just with the sample BintrayConfiguration.

**Comment by jameskleeh** [comment]
The error says the exception was thrown by our code, but the stacktrace provided doesn't have any reference to Micronaut code. You would have to get the details of the exception thrown. Does the project compile with maven?

**Comment by charkins** [comment]
I'm seeing a similar stacktrace from a freshly generated micronaut.io/launch gradle java11 application using vscode with a single hello world type controller added. Building with gradle works perfectly, vscode (via eclipse buildship) triggers this Exception and appears to prevent the separate service descriptor annotation processor from running (or at least the io.micronaut.inject.BeanDefinitionReference file is not generated). I am going to try and dig in a little more, but thought I'd comment here since they seem to be related and at least gives an idea of where in micronaut this is originating from.
```

java.lang.Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:958)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:932)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:278)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:515)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:405)
	at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:815)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$50(JDTLanguageServer.java:981)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at org.eclipse.jdt.internal.core.builder.ClasspathMultiDirectory.directoryList(ClasspathMultiDirectory.java:76)
	at org.eclipse.jdt.internal.core.builder.ClasspathDirectory.doesFileExist(ClasspathDirectory.java:133)
	at org.eclipse.jdt.internal.core.builder.ClasspathDirectory.findClass(ClasspathDirectory.java:158)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.findClass(ClasspathLocation.java:59)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findClass(NameEnvironment.java:524)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findType(NameEnvironment.java:546)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.lambda$0(LookupEnvironment.java:237)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:372)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:236)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1703)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getResolvedType(LookupEnvironment.java:1633)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getResolvedType(LookupEnvironment.java:1628)
	at org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding.buildTargetAnnotation(AnnotationBinding.java:166)
	at org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding.addStandardAnnotations(AnnotationBinding.java:79)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.retrieveAnnotations(BinaryTypeBinding.java:1698)
	at org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.getAnnotations(ReferenceBinding.java:1054)
	at org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getAnnotationBindings(TypeElementImpl.java:149)
	at org.eclipse.jdt.internal.compiler.apt.model.ElementImpl.getPackedAnnotationBindings(ElementImpl.java:66)
	at org.eclipse.jdt.internal.compiler.apt.model.ElementImpl.getAnnotationMirrors(ElementImpl.java:81)
	at io.micronaut.annotation.processing.JavaAnnotationMetadataBuilder.getRetentionPolicy(JavaAnnotationMetadataBuilder.java:140)
	at io.micronaut.annotation.processing.JavaAnnotationMetadataBuilder.getRetentionPolicy(JavaAnnotationMetadataBuilder.java:53)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildInternal(AbstractAnnotationMetadataBuilder.java:921)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildDeclared(AbstractAnnotationMetadataBuilder.java:136)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.validateAnnotationValue(AbstractAnnotationMetadataBuilder.java:412)
	at io.micronaut.annotation.processing.JavaAnnotationMetadataBuilder.readAnnotationRawValues(JavaAnnotationMetadataBuilder.java:288)
	at io.micronaut.annotation.processing.JavaAnnotationMetadataBuilder.readAnnotationRawValues(JavaAnnotationMetadataBuilder.java:53)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.processAnnotationDefaults(AbstractAnnotationMetadataBuilder.java:801)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.processAnnotationDefaults(AbstractAnnotationMetadataBuilder.java:790)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.populateAnnotationData(AbstractAnnotationMetadataBuilder.java:592)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildInternal(AbstractAnnotationMetadataBuilder.java:922)
	at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildOverridden(AbstractAnnotationMetadataBuilder.java:167)
	at io.micronaut.annotation.processing.AnnotationUtils.getAnnotationMetadata(AnnotationUtils.java:194)
	at io.micronaut.annotation.processing.AnnotationUtils.hasStereotype(AnnotationUtils.java:176)
	at io.micronaut.annotation.processing.AnnotationUtils.hasStereotype(AnnotationUtils.java:159)
	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.lambda$process$2(BeanDefinitionInjectProcessor.java:130)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.process(BeanDefinitionInjectProcessor.java:131)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 34 more
```

**Comment by charkins** [comment]
I have made some progress and I suspect it relates to issue #2922 and the solution that was implemented.

I am able to reproduce the NPE with https://github.com/briankramer17/micronaut-issue-test using vscode with vscode-java extension. Despite the NPEs, the classes are being generated:

```
target/classes/micronaut/issue/test/$BintrayConfigurationDefinitionClass.class
target/classes/micronaut/issue/test/$BintrayConfigurationDefinition.class
```
However, ```target/classes/META-INF/services/io.micronaut.inject.BeanDefinitionReference``` is not being generated, though I am not sure if this is actually related to the NPEs.  When compiling with javac, three annotation processing rounds are run, where the second round is picking up the @Generated annotated classes generated in the first round in order to generate the BeanDefinitionReference:

```
Round 1:
        input files: {micronaut.issue.test.Application, micronaut.issue.test.BintrayConfiguration}
        annotations: [io.micronaut.context.annotation.ConfigurationProperties, io.micronaut.context.annotation.Requires]
        last round: false
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-validation/2.0.0/micronaut-validation-2.0.0.jar(/io/micronaut/validation/routes/RouteValidationVisitor.class)]
[loading /modules/java.compiler/javax/annotation/processing/SupportedOptions.class]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-validation/2.0.0/micronaut-validation-2.0.0.jar(/io/micronaut/validation/async/AsyncTypeElementVisitor.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-validation/2.0.0/micronaut-validation-2.0.0.jar(/io/micronaut/validation/websocket/WebSocketVisitor.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-validation/2.0.0/micronaut-validation-2.0.0.jar(/io/micronaut/validation/internal/InternalApiTypeElementVisitor.class)]
[loading ${HOME}/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar(/javax/inject/Singleton.class)]
[loading /modules/java.base/java/lang/annotation/Documented.class]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/annotation/ConfigurationReader.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/annotation/Aliases.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/condition/TrueCondition.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-core/2.0.0/micronaut-core-2.0.0.jar(/io/micronaut/core/annotation/InstantiatedMember.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/annotation/Requirements.class)]
[loading ${HOME}/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar(/javax/inject/Scope.class)]
Processor io.micronaut.annotation.processing.TypeElementVisitorProcessor matches [/io.micronaut.context.annotation.ConfigurationProperties, /io.micronaut.context.annotation.Requires] and returns false.
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/annotation/EachProperty.class)]
[loading /modules/java.base/jdk/internal/HotSpotIntrinsicCandidate.class]
Processor io.micronaut.annotation.processing.BeanDefinitionInjectProcessor matches [/io.micronaut.context.annotation.ConfigurationProperties, /io.micronaut.context.annotation.Requires] and returns false.
Note: Creating bean classes for 1 type elements
[loading ${HOME}/tmp/micronaut-issue-test/build-javac/classes/java/main/micronaut/issue/test/$BintrayConfigurationDefinition.class]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/AbstractBeanDefinition.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-core/2.0.0/micronaut-core-2.0.0.jar(/io/micronaut/core/annotation/Internal.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/AbstractBeanContextConditional.class)]
[loading ${HOME}/tmp/micronaut-issue-test/build-javac/classes/java/main/micronaut/issue/test/$BintrayConfigurationDefinitionClass.class]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-core/2.0.0/micronaut-core-2.0.0.jar(/io/micronaut/core/annotation/Generated.class)]
[loading ${HOME}/.m2/repository/io/micronaut/micronaut-inject/2.0.0/micronaut-inject-2.0.0.jar(/io/micronaut/context/AbstractBeanDefinitionReference.class)]
Round 2:```
        input files: {micronaut.issue.test.$BintrayConfigurationDefinition, micronaut.issue.test.$BintrayConfigurationDefinitionClass}
        annotations: [io.micronaut.core.annotation.Generated]
        last round: false
Processor io.micronaut.annotation.processing.TypeElementVisitorProcessor matches [/io.micronaut.core.annotation.Generated] and returns false.
Processor io.micronaut.annotation.processing.BeanDefinitionInjectProcessor matches [/io.micronaut.core.annotation.Generated] and returns false.
Processor io.micronaut.annotation.processing.ServiceDescriptionProcessor matches [/io.micronaut.core.annotation.Generated] and returns true.
Round 3:
        input files: {}
        annotations: []
        last round: true

```

When executing the eclipse jdt compiler directly (in batch mode), only two rounds are executed, it doesn't seem to be picking up the generated classes for the second round, which prevents it from generating a BeanDefinitionReference file:

```
Round 1:
        input files: {micronaut.issue.test.Application,micronaut.issue.test.BintrayConfiguration}
        annotations: [io.micronaut.context.annotation.Requires,io.micronaut.context.annotation.ConfigurationProperties]
        last round: false
[reading    io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.class]
[reading    io/micronaut/inject/visitor/TypeElementVisitor.class]
[reading    io/micronaut/core/order/Ordered.class]
[reading    io/micronaut/validation/routes/RouteValidationVisitor.class]
[reading    io/micronaut/http/annotation/HttpMethodMapping.class]
[reading    io/micronaut/validation/async/AsyncTypeElementVisitor.class]
[reading    io/micronaut/scheduling/annotation/Async.class]
[reading    io/micronaut/validation/websocket/WebSocketVisitor.class]
[reading    io/micronaut/websocket/annotation/WebSocketComponent.class]
[reading    io/micronaut/websocket/WebSocketVersion.class]
[reading    io/micronaut/websocket/annotation/WebSocketMapping.class]
[reading    io/micronaut/validation/internal/InternalApiTypeElementVisitor.class]
Discovered processor service io.micronaut.annotation.processing.TypeElementVisitorProcessor
  supporting [*]
  in jar:file:${HOME}/.m2/repository/io/micronaut/micronaut-inject-java/2.0.0/micronaut-inject-java-2.0.0.jar!/
[reading    javax/inject/Singleton.class]
[reading    io/micronaut/context/annotation/ConfigurationReader.class]
[reading    java/lang/annotation/Target.class]
[reading    java/lang/annotation/ElementType.class]
[reading    java/lang/annotation/RetentionPolicy.class]
[reading    java/lang/annotation/Retention.class]
[reading    java/lang/annotation/Documented.class]
[reading    java/lang/InterruptedException.class]
[reading    java/lang/Throwable.class]
[reading    java/lang/CloneNotSupportedException.class]
[reading    io/micronaut/context/annotation/AliasFor.class]
[reading    io/micronaut/context/annotation/Aliases.class]
[reading    java/lang/annotation/Repeatable.class]
[reading    io/micronaut/context/condition/TrueCondition.class]
[reading    io/micronaut/core/annotation/InstantiatedMember.class]
[reading    javax/inject/Scope.class]
Processor io.micronaut.annotation.processing.TypeElementVisitorProcessor matches [io.micronaut.context.annotation.Requires io.micronaut.context.annotation.ConfigurationProperties] and returns false
Discovered processor service io.micronaut.annotation.processing.AggregatingTypeElementVisitorProcessor
  supporting []
  in jar:file:${HOME}/.m2/repository/io/micronaut/micronaut-inject-java/2.0.0/micronaut-inject-java-2.0.0.jar!/
Discovered processor service io.micronaut.annotation.processing.PackageConfigurationInjectProcessor
  supporting [io.micronaut.context.annotation.Configuration]
  in jar:file:${HOME}/.m2/repository/io/micronaut/micronaut-inject-java/2.0.0/micronaut-inject-java-2.0.0.jar!/
[reading    io/micronaut/context/annotation/EachProperty.class]
Discovered processor service io.micronaut.annotation.processing.BeanDefinitionInjectProcessor
  supporting [*]
  in jar:file:${HOME}/.m2/repository/io/micronaut/micronaut-inject-java/2.0.0/micronaut-inject-java-2.0.0.jar!/
[reading    jdk/internal/HotSpotIntrinsicCandidate.class]
Processor io.micronaut.annotation.processing.BeanDefinitionInjectProcessor matches [io.micronaut.context.annotation.Requires io.micronaut.context.annotation.ConfigurationProperties] and returns false
Discovered processor service io.micronaut.annotation.processing.ServiceDescriptionProcessor
  supporting [io.micronaut.core.annotation.Generated]
  in jar:file:${HOME}/.m2/repository/io/micronaut/micronaut-inject-java/2.0.0/micronaut-inject-java-2.0.0.jar!/
Round 2:
        input files: {}
        annotations: []
        last round: true
```

**Comment by charkins** [comment]
This appears to be an eclipse bug, I've reported it here:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=565214

With a minimal(ish) working example (without micronaut) here:

https://github.com/charkins/ecj-apt-issue

**Comment by diamondq** [comment]
For those who run into this, and want to skip digging through the Eclipse bug comments, it appears to be fixable in Eclipse by unchecking the **Scrub output folders when cleaning projects** entry under **Window->Preferences->Java->Compiler->Building->Output Folder.**

**Comment by charkins** [comment]
> For those who run into this, and want to skip digging through the Eclipse bug comments, it appears to be fixable in Eclipse by unchecking the **Scrub output folders when cleaning projects** entry under **Window->Preferences->Java->Compiler->Building->Output Folder.**


Thanks! This can be accomplished with gradle eclipse by adding this to build.gradle:
```
eclipse.jdt {
    file {
        withProperties { props ->
           props.setProperty("org.eclipse.jdt.core.builder.cleanOutputFolder", "ignore")
        }
    }
}
```

**Comment by graemerocher** [comment]
Triaged as Bug for classification, then closed as not planned: the supplied minimal analysis reproduces the failure in Eclipse JDT’s annotation-processing round handling, and the issue links the upstream Eclipse defect. The documented workaround is to disable “Scrub output folders when cleaning projects” (or set `org.eclipse.jdt.core.builder.cleanOutputFolder=ignore` in the Eclipse Gradle configuration). Command-line Maven/Gradle compilation works, so this is not a current Micronaut Core defect. Reopen only with a current Eclipse regression that remains after the upstream/workaround changes.
