### ISSUE TITLE
Graal Native Image Build Failure - Logback Rolling File Appender

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-core#3683]
Micronaut native image build error occurs when building within docker with logback rolling file appender

## Failure
```
Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone github repository
2. Run `./mvnw clean install`
3. Run `docker build . --network host -t micronaut-app`

### Expected Behaviour

The native image should build successfully

### Actual Behaviour

The native image build fails with following output:

```
Sending build context to Docker daemon  13.82MB
Step 1/10 : FROM oracle/graalvm-ce:20.1.0-java8 as graalvm
 ---> fa8819f7526a
Step 2/10 : RUN gu install native-image
 ---> Using cache
 ---> fc69ef741138
Step 3/10 : COPY . /home/app/micronaut-logback-native-image
 ---> 9caf4d4e5553
Step 4/10 : WORKDIR /home/app/micronaut-logback-native-image
 ---> Running in 3c7c99422115
Removing intermediate container 3c7c99422115
 ---> 0ddc0abc9952
Step 5/10 : RUN native-image --no-server --no-fallback --static -cp target/micronaut-logback-native-image-*.jar
 ---> Running in 034999be71ca
[micronaut-logback-native-image:22]    classlist:  12,868.67 ms,  1.68 GB
[micronaut-logback-native-image:22]        (cap):   1,159.69 ms,  1.68 GB
[micronaut-logback-native-image:22]        setup:   5,649.10 ms,  2.28 GB
[micronaut-logback-native-image:22]     (clinit):   1,685.13 ms,  3.50 GB
[micronaut-logback-native-image:22]   (typeflow):  50,058.59 ms,  3.50 GB
[micronaut-logback-native-image:22]    (objects):  32,372.07 ms,  3.50 GB
[micronaut-logback-native-image:22]   (features):   5,720.34 ms,  3.50 GB
[micronaut-logback-native-image:22]     analysis:  95,536.95 ms,  3.50 GB
Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.io.FileOutputStream.fd of
                constant java.io.FileOutputStream@271eea43 reached by 
        reading field ch.qos.logback.core.recovery.ResilientFileOutputStream.fos of
                constant ch.qos.logback.core.recovery.ResilientFileOutputStream@236b3a5d reached by 
        reading field ch.qos.logback.core.OutputStreamAppender.outputStream of
                constant ch.qos.logback.core.rolling.RollingFileAppender@ac04108 reached by 
        reading field ch.qos.logback.core.status.StatusBase.origin of
                constant ch.qos.logback.core.status.InfoStatus@2de948e4 reached by 
        indexing into array
                constant java.lang.Object[]@63f5ebc reached by 
        reading field java.util.ArrayList.elementData of
                constant java.util.ArrayList@c3d52e7f reached by 
        reading field ch.qos.logback.core.BasicStatusManager.statusList of
                constant ch.qos.logback.core.BasicStatusManager@72c88179 reached by 
        reading field ch.qos.logback.core.ContextBase.sm of
                constant ch.qos.logback.classic.LoggerContext@161a1422 reached by 
        reading field ch.qos.logback.classic.Logger.loggerContext of
                constant ch.qos.logback.classic.Logger@5f0be39d reached by 
        scanning method io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1286)
Call path from entry point to io.micronaut.context.DefaultBeanContext.notifyEventListeners(Object, Collection): 
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1285)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1280)
        at io.micronaut.scheduling.io.watch.DefaultWatchThread.lambda$start$0(DefaultWatchThread.java:119)
        at io.micronaut.scheduling.io.watch.DefaultWatchThread$$Lambda$439/53077030.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@aba851 reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3a9f3ecb reached by 
        reading field java.util.concurrent.ArrayBlockingQueue.notEmpty of
                constant java.util.concurrent.ArrayBlockingQueue@7016bbe7 reached by 
        reading field ch.qos.logback.core.AsyncAppenderBase.blockingQueue of
                constant ch.qos.logback.classic.AsyncAppender@616c9130 reached by 
        reading field ch.qos.logback.core.status.StatusBase.origin of
                constant ch.qos.logback.core.status.InfoStatus@c07841b5 reached by 
        indexing into array
                constant java.lang.Object[]@63f5ebc reached by 
        reading field java.util.ArrayList.elementData of
                constant java.util.ArrayList@c3d52e7f reached by 
        reading field ch.qos.logback.core.BasicStatusManager.statusList of
                constant ch.qos.logback.core.BasicStatusManager@72c88179 reached by 
        reading field ch.qos.logback.core.ContextBase.sm of
                constant ch.qos.logback.classic.LoggerContext@161a1422 reached by 
        reading field ch.qos.logback.classic.Logger.loggerContext of
                constant ch.qos.logback.classic.Logger@5f0be39d reached by 
        scanning method io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1286)
Call path from entry point to io.micronaut.context.DefaultBeanContext.notifyEventListeners(Object, Collection): 
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1285)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1280)
        at io.micronaut.scheduling.io.watch.DefaultWatchThread.lambda$start$0(DefaultWatchThread.java:119)
        at io.micronaut.scheduling.io.watch.DefaultWatchThread$$Lambda$439/53077030.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image --no-server --no-fallback --static -cp target/micronaut-logback-native-image-*.jar' returned a non-zero code: 1
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** `2.0.0`
- **JDK Version:** `1.8`

### Example Application

- https://github.com/brianwyka/micronaut-logback-graal-native-image

**Comment by brianwyka** [comment]
@ilopmar, some changes I made to the generated project:

* `Dockerfile` - I altered the `native-image` command to include `--no-fallback --static`
* `src/main/resources/logback.xml` - added the rolling file appender
* `src/main/java/com/github/brianwyka/Application.java#main` - added a `Logger` statement

**Comment by ilopmar** [comment]
Related https://github.com/oracle/graal/issues/1323

**Comment by ilopmar** [comment]
I've tried this, and I've been adding one class after another to `--initialize-at-run-time` until I realized that those classes are being triggered because they contain something like this: `private static final Logger LOG = LoggerFactory.getLogger(Micronaut.class);`. That triggers the initialization of the logging and thus, the creation of the log file at build time, which is not what we want and doesn't work.

I think there is no too much we can do about it and this should be fixed in either Logback or GraalVM.

**Comment by vlcheong** [comment]
Any update on this ?

**Comment by begrossi** [comment]
I solved this problem with a lazy initialization of appender. The code is on this link:
https://gist.github.com/begrossi/d807280f54d3378d407e9c9a95e5d905

Any comments and suggestions are welcome.

**Comment by graemerocher** [comment]
@begrossi nice idea.

**Comment by moonrockfamily** [comment]
@begrossi Thanks for the idea.  I've applied it to the simpler FileAppender, called LazyInitFileAppender, and it defers the file handling as expected, however `io.micronaut.context.DefaultBeanContext` has a static initialization call to `org.slf4j.LoggerFactory.getLogger(...)` causing the static initialization/binding of the configuration using the **build time** environment.

Stack to config binding:
```
configureByResource:59, ContextInitializer (ch.qos.logback.classic.util)
autoConfig:150, ContextInitializer (ch.qos.logback.classic.util)
init:84, StaticLoggerBinder (org.slf4j.impl)
<clinit>:55, StaticLoggerBinder (org.slf4j.impl)
bind:150, LoggerFactory (org.slf4j)
performInitialization:124, LoggerFactory (org.slf4j)
getILoggerFactory:417, LoggerFactory (org.slf4j)
getLogger:362, LoggerFactory (org.slf4j)
getLogger:388, LoggerFactory (org.slf4j)
**<clinit>:79, DefaultBeanContext (io.micronaut.context)**
...
```

native-image with attempt to defer Logger initialization:
```
ch.qos.logback.classic.Logger the class was requested to be initialized at run time (from jar:file:///C:/Users/thiles/.gradle/caches/modules-2/files-2.1/io.micronaut/micronaut-runtime/2.5.3/1c56bad3ffbbc1147cd4c340efd872f264b4ca9/micronaut-runtime-2.5.3.jar!/META-INF/native-image/io.micronaut/micronaut-runtime/native-image.properties). io.micronaut.context.DefaultBeanContext caused initialization of this class with the following trace: 
	at ch.qos.logback.classic.Logger.<clinit>(Logger.java:44)
	at ch.qos.logback.classic.LoggerContext.<init>(LoggerContext.java:79)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:59)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:50)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at io.micronaut.context.DefaultBeanContext.<clinit>(DefaultBeanContext.java:79)
```

The intention is to have the log filename use an environment property at runtime NOT build time, such that we can use the same native image with different logFilename settings (gsb1, geor).  The application is a CLI that is run by another vendor provided application and its responsible for publishing the file to RabbitMQ via a command like this :
`\\apps\\FilePublisher\\FilePublisher -Dmicronaut.config.files=\\apps\\FilePublisher\\:db_name.yml publishFile "\\data\\:db_name\\transcript\\id:id\_normal.pdf"`

```xml
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <withJansi>false</withJansi>
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d{yyyy-mm-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <!-- Insert the current time formatted as "yyyyMMdd'T'HHmmss" under
       the key "bySecond" into the logger context. This value will be
       available to all subsequent configuration elements. -->
    <timestamp key="bySecond" datePattern="yyyyMMdd'T'HHmmss"/>
    <timestamp key="byDay" datePattern="yyyyMMdd"/>

    <appender name="DAILY_FILE" class="util.LazyInitFileAppender">
        <!-- use the previously created timestamp to create a uniquely named log file -->
        <file>FilePublisher.${logFilename}.${bySecond}.log</file>
        <append>true</append>
        <encoder>
            <pattern>%d{yyyy-mm-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="DAILY_FILE"/>
    </root>
</configuration>
```

The end result is that the Filename is baked into the executable and will never change!
```FilePublisher.logFilename_IS_UNDEFINED.20210716T150917.log```
setting the logFilename in the system environement prior to native-image has the expected impact:
```FilePublisher.gsb1.20210716T150917.log```, but still no dynamic/runtime property consideration.

Initially I thought I could work around the instantiation of the LoggerFactory using bean injection, which works nicely for my code, but unfortunately the `io.micronaut.context.DefaultBeanContext` static LOG initialization calls it anyways!

For those interested in the Logger injection technique:

```java
package util;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Documented
@Retention(RUNTIME)
@Target({ElementType.FIELD,ElementType.PARAMETER})
public @interface ClassParam {
    Class value() default Object.class;
}
```

```java
package util;

import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Prototype;
import io.micronaut.inject.InjectionPoint;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Factory
public class Slf4jFactory {

    @Prototype
    Logger getLogger(InjectionPoint<?> injectionPoint) {
        if (inGraalImageBuildtimeCode()) return null;
        final Class clazz = injectionPoint.getAnnotationMetadata().classValue(ClassParam.class).orElse(Object.class);
        if (clazz == Object.class) {
            throw new IllegalArgumentException("Unsupported Class parameter " + clazz);
        }
        return LoggerFactory.getLogger(clazz);
    }

    //THE BELOW CODE CAN BE SUBSTITUTED BY ImageInfo.inImageBuildtimeCode() if you have it on your classpath

    private static final String PROPERTY_IMAGE_CODE_VALUE_BUILDTIME = "buildtime";
    private static final String PROPERTY_IMAGE_CODE_KEY = "org.graalvm.nativeimage.imagecode";
    /**
     * Returns true if (at the time of the call) code is executing in the context of Graal native image building
     * (e.g. in a static initializer of class that will be contained in the image).
     * Copy of graal code in org.graalvm.nativeimage.ImageInfo.inImageBuildtimeCode().
     * https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java
     */
    private static boolean inGraalImageBuildtimeCode() {
        return PROPERTY_IMAGE_CODE_VALUE_BUILDTIME.equals(System.getProperty(PROPERTY_IMAGE_CODE_KEY));
    }
}
```

and used like this:

```java
/**
 * Publishes the files in the configured directory
 */
public class BatchDirectoryPublisher {
    @Inject
    @ClassParam(BatchDirectoryPublisher.class)
    Logger log;
```

For those interested in the simpler LazyInitFileAppender:
This at least permits the creation of the native image with a **hard coded** log filename!

```java
package util;

/**
 * FileAppender with Lazy Initialization on GraalVM native image.
 * see https://github.com/micronaut-projects/micronaut-core/issues/3683
 * and https://gist.github.com/begrossi/d807280f54d3378d407e9c9a95e5d905
 */
public class LazyInitFileAppender<E> extends ch.qos.logback.core.FileAppender<E> {
    private boolean started = false;

    @Override
    public void start() {
        if (!inGraalImageBuildtimeCode()) {
            super.start();
            this.started = true;
        }

    }

    /**
     * This method is synchronized to avoid double start from doAppender().
     */
    protected void maybeStart() {
        lock.lock();
        try {
            if (!started)
                this.start();
        } finally {
            lock.unlock();
        }
    }

    @Override
    public void doAppend(E eventObject) {
        if (!inGraalImageBuildtimeCode()) {
            if (!started)
                maybeStart();

            super.doAppend(eventObject);
        }
    }

  
  //THE BELOW CODE CAN BE SUBSTITUTED BY ImageInfo.inImageBuildtimeCode() if you have it on your classpath
  
    private static final String PROPERTY_IMAGE_CODE_VALUE_BUILDTIME = "buildtime";
    private static final String PROPERTY_IMAGE_CODE_KEY = "org.graalvm.nativeimage.imagecode";
    /**
     * Returns true if (at the time of the call) code is executing in the context of Graal native image building
     * (e.g. in a static initializer of class that will be contained in the image).
     * Copy of graal code in org.graalvm.nativeimage.ImageInfo.inImageBuildtimeCode().
     * https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java
     */
    private static boolean inGraalImageBuildtimeCode() {
        return PROPERTY_IMAGE_CODE_VALUE_BUILDTIME.equals(System.getProperty(PROPERTY_IMAGE_CODE_KEY));
    }

}
```

**Comment by yj2006062** [comment]
@begrossi hi,begrossi, your link seems not aviliable now, could you share a new one?

**Comment by tianqing108** [comment]
it's tips is SLF4J: No SLF4J providers were found , how to resolve this problem?
