### ISSUE TITLE
DependencyInjectionException in native image

### ISSUE THREAD

**Issue by adamkobor** [micronaut-projects/micronaut-core#3782]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out the example repository
2. Run ./gradlew shadowJar
3. Build a native image with ./docker-build.sh
4. Run the native image with docker, send a random request to the server and watch the logs

### Expected Behaviour

It should handle the request properly.

### Actual Behaviour

The request hangs on client side and the app infinitely throws `io.micronaut.context.exceptions.DependencyInjectionException`:

```
kuvasz_1  | 21:38:25.804 [nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for field [jacksonModules] of class: com.akobor.kuvasz.config.KotlinObjectMapperFactory
kuvasz_1  | 
kuvasz_1  | Message: Error setting field value: No field 'jacksonModules' found for type: io.micronaut.jackson.ObjectMapperFactory
kuvasz_1  | 
kuvasz_1  | io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [jacksonModules] of class: com.akobor.kuvasz.config.KotlinObjectMapperFactory
kuvasz_1  | 
kuvasz_1  | Message: Error setting field value: No field 'jacksonModules' found for type: io.micronaut.jackson.ObjectMapperFactory
kuvasz_1  | 
kuvasz_1  |     at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:763)
kuvasz_1  |     at com.akobor.kuvasz.config.$KotlinObjectMapperFactoryDefinition.injectBean(Unknown Source)
kuvasz_1  |     at com.akobor.kuvasz.config.$KotlinObjectMapperFactoryDefinition.build(Unknown Source)
kuvasz_1  |     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1888)

``` 

### Environment Information

- **Operating System**: macOS 10.15.5
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

https://github.com/kuvasz-uptime/kuvasz

The application worked fine before this commit, which is weird, because it seems that the changeset contains nothing that could affect the described behavior: https://github.com/kuvasz-uptime/kuvasz/commit/677a91d020744243764ec6a294777fdbe9334199

**Comment by graemerocher** [comment]
Seems that subclasses a child with protected fields triggers reflection. We have 2 options:

* Stop using `@Inject` on protected fields (right fix IMO)
* Document how to subclass `ObjectMapperFactory`

I think we should also start printing warnings when reflection is triggered and GraalVM is in use.

**Comment by adamkobor** [comment]
I can confirm that configuring Jackson through `JacksonConfiguration` resolves this issue.

**Comment by IgorEulalio** [comment]
@graemerocher whats the best alternative for @Inject in this scenario?

**Comment by IgorEulalio** [comment]
The injection of properties doesn't work too:

```java
    @Value("${rota.cadastro-cvm:rota-exemplo-cvm}")
    private String ROTA_CADASTRO_CVM;
```

properties:

```yml
rota:
  contratacao: "rota-contratacao-properties"
  cadastro-cvm: "rota-cvm-properties"
```

Error after compiled with native image:

```
Message: Error setting field value: No field 'ROTA_CADASTRO_CVM' found for type: br.com.itau.core.biz.ValidaCadastroCvmBiz
Path Taken: new $ContratacaoRecomendacaoControllerDefinition$Intercepted([ValidaCadastroCvmBiz biz],ProximosPassosMapper mapper,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [ROTA_CADASTRO_CVM] of class: br.com.itau.core.biz.ValidaCadastroCvmBiz
```

**Comment by graemerocher** [comment]
if the field is private then it must be annotated with `@ReflectiveAccess`. Otherwise consider using package private fields or event better constructor arguments

**Comment by graemerocher** [comment]
Triaged as Bug for classification, then closed as not planned. The failure is caused by subclassing `ObjectMapperFactory` and relying on native-image reflection for injected fields; the maintainers’ supported solution is to configure Jackson through `JacksonConfiguration`/a Jackson module, or explicitly mark private reflective fields with `@ReflectiveAccess`. The current Core source still exposes the factory’s injected extension points, but there is no current-version reproducer showing a defect in those supported extension mechanisms. Reopen with a current native-image example if configuration or an explicitly reflective field still fails.
