### ISSUE TITLE
ConcurrentModificationException when initializing DefaultBeanContext

### ISSUE THREAD

**Issue by mkairys-tru** [micronaut-projects/micronaut-core#3823]
Some times I see ConcurrentModificationException on DefaultBeanContext initialization.

### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Not sure how to reproduce, occurs randomly

### Expected Behaviour

No errors should happen

### Actual Behaviour

Here is the stack trace:
`Exception in thread "ForkJoinPool.commonPool-worker-3" java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
at io.micronaut.context.env.PropertySourcePropertyResolver.lambda$containsProperties$2(PropertySourcePropertyResolver.java:170)
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
at io.micronaut.context.env.PropertySourcePropertyResolver.containsProperties(PropertySourcePropertyResolver.java:160)
at io.micronaut.context.DefaultApplicationContext.containsProperties(DefaultApplicationContext.java:203)
at io.micronaut.context.RequiresCondition.matchesProperty(RequiresCondition.java:231)
at io.micronaut.context.RequiresCondition.processPreStartRequirements(RequiresCondition.java:171)
at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:100)
at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:47)
at io.micronaut.context.AbstractBeanDefinitionReference.isEnabled(AbstractBeanDefinitionReference.java:108)
at io.micronaut.context.DefaultBeanContext.lambda$null$30(DefaultBeanContext.java:1449)
at java.util.concurrent.ConcurrentLinkedQueue.bulkRemove(ConcurrentLinkedQueue.java:1004)
at java.util.concurrent.ConcurrentLinkedQueue.removeIf(ConcurrentLinkedQueue.java:964)
at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$31(DefaultBeanContext.java:1448)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)`

### Environment Information

- **Operating System**: AWS linux
- **Micronaut Version:** 1.3.3
- **JDK Version:** 11 on graal, but I guess non-graal also

### Example Application

- not sure how to reproduce

**Comment by graemerocher** [comment]
Will need an example

**Comment by xeagle2** [comment]
Hey there,

I face the similar issue frequently building the app on every day basis via gradle.

Here is the stack trace:
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:113)
	at io.micronaut.aot.cli.Main.run(Main.java:87)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.micronaut.aot.cli.Main.execute(Main.java:134)
	at io.micronaut.aot.cli.Main.main(Main.java:138)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:107)
	... 11 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapPropertySourceLocatorPresent(DefaultApplicationContext.java:156)
	at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:308)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapEnabled(DefaultApplicationContext.java:152)
	at io.micronaut.context.DefaultApplicationContext.createEnvironment(DefaultApplicationContext.java:140)
	at io.micronaut.context.DefaultApplicationContext.getEnvironment(DefaultApplicationContext.java:174)
	at io.micronaut.aot.core.context.ApplicationContextAnalyzer.getEnvironmentNames(ApplicationContextAnalyzer.java:66)
	at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:336)
	at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
	... 16 more
`

### Environment Information

- micronaut version: 4.1.1
- gradle version: 8.1.1
