### ISSUE TITLE
@Retryable will execute for all exceptions if all includes are missing on classpath

### ISSUE THREAD

**Issue by altery** [micronaut-projects/micronaut-core#3837]
# Context
Micronaut 2.0.1

# Description

If none of the Throwables of the "includes" field of @Retryable are on the runtime classpath, the retry is executed for every exception that occurs in the annotated method.

# Expected behaviour

I'd expect that the retry is never executed, because adding at least one Throwable to "includes" changes the semantics from "execute for every exception" to "execute only if the cause is of at least one of the Throwables. This semantic should be independent of the classpath. Alternatively, I'd also understand if an exception would be thrown if the includes/excludes Throwables could not be loaded.

# Analysis

This is caused by the DefaultRetryPredicate, which calculates 'hasIncludes' only based on the number of elements in the includes list. This list is only populated if the specified includes are on the classpath.

See AnnotationRetryStateBuilder#resolveIncludes and AnnotationValue#resolveClassValues

**Comment by graemerocher** [comment]
Seems like you have provided good analysis of the problem, would you like to send a PR?

**Comment by altery** [comment]
While working on the PR I noticed that things behave differently when compiling with JDK8. Micronaut doesn't seem to generate BeanDefinitions for Groovy-Methods that contains annotations not an Classpath. As a consequence, the Spock-Tests do not execute at all: https://github.com/micronaut-projects/micronaut-core/pull/3860/checks?check_run_id=951201393

The following happens when compiling the referenced PR on JDK8 (Amazon and OpenJDK):
```
> ./gradlew :runtime:testCompile --stacktrace
(...)
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 3.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
(...)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:104)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:81)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:83)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:66)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
(...)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'io.micronaut.retry.intercept.$SimpleRetrySpec$CounterServiceDefinition$Intercepted'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
(...)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:600)
	at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
	at java.lang.reflect.Method.getAnnotation(Method.java:622)
	at java.lang.reflect.AccessibleObject.getDeclaredAnnotation(AccessibleObject.java:219)
	at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:128)
	at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:115)
	at org.junit.platform.commons.util.AnnotationUtils.isAnnotated(AnnotationUtils.java:93)
	at org.junit.jupiter.engine.discovery.predicates.IsTestableMethod.test(IsTestableMethod.java:52)
	at org.junit.jupiter.engine.discovery.predicates.IsTestFactoryMethod.test(IsTestFactoryMethod.java:26)
	at org.junit.jupiter.engine.discovery.predicates.IsTestableMethod.test(IsTestableMethod.java:26)
	at java.util.function.Predicate.lambda$or$2(Predicate.java:101)
	at java.util.function.Predicate.lambda$or$2(Predicate.java:101)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1306)
	at org.junit.platform.commons.util.ReflectionUtils.isMethodPresent(ReflectionUtils.java:1205)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.hasTestOrTestFactoryOrTestTemplateMethods(IsTestClassWithTests.java:50)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.test(IsTestClassWithTests.java:46)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:67)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 37 more
```

I think this must be resolved before continuing here.  I'm not really into ASM and Groovy, so I cannot track down the issue within reasonable amount of time, but I could file a new issue, if you like, @graemerocher

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by graemerocher** [comment]
Triaged as Bug. The analysis remains valid in current Core: unresolved classes in `@Retryable.includes` are omitted by annotation metadata resolution, so `DefaultRetryPredicate` receives an empty include list and treats the policy as “retry all exceptions.” Suggested fix: preserve unresolved class names as a distinct metadata state and fail compilation/configuration, or make the generated predicate fail closed when an explicit include list cannot be resolved; add tests for missing optional exception types on JDK 8+ and for valid includes/excludes. The old PR attempt did not establish a merged fix, so please provide a current 5.x test case.
