### ISSUE TITLE
@Introspected annotation breaks jackson mapping

### ISSUE THREAD

**Issue by katoquro** [micronaut-projects/micronaut-core#3861]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

I've created demo repo with the issue (https://github.com/katoquro/micronaut-issue). Just run test and broken one is for representing the issue. Good one is the same but without annotation `@Introspected`

1. Create a controller with micronaut validation
2. Make DTO for body value
3. annotate DTO with `@Introspected`

### Expected Behaviour

Shouldn't fail )) 

### Actual Behaviour

```
22:56:21.855 [Test worker] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.example.DemoSpec$DemoControllerClient$Intercepted] executed with error: Error encoding object [com.example.IntrospectedDto@4d19d919] to JSON: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: com.example.IntrospectedDto["mapStructure"])
io.micronaut.http.codec.CodecException: Error encoding object [com.example.IntrospectedDto@4d19d919] to JSON: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: com.example.IntrospectedDto["mapStructure"])
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:215)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:221)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$buildNettyRequest$44(DefaultHttpClient.java:1566)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1566)
	at io.micronaut.http.client.netty.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1745)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$33(DefaultHttpClient.java:1108)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: com.example.IntrospectedDto["mapStructure"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:763)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4374)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3653)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:212)
	... 24 common frames omitted
Caused by: java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap')
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.isEmpty(StringSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.isEmpty(MapSerializer.java:567)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.isEmpty(MapSerializer.java:33)
	at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionPropertyWriter.serializeAsField(BeanIntrospectionModule.java:643)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	... 30 common frames omitted

Expected no exception to be thrown, but got 'io.micronaut.http.codec.CodecException'
Expected no exception to be thrown, but got 'io.micronaut.http.codec.CodecException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at com.example.DemoSpec.test it is broken(DemoSpec.groovy:21)
Caused by: io.micronaut.http.codec.CodecException: Error encoding object [com.example.IntrospectedDto@4d19d919] to JSON: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: com.example.IntrospectedDto["mapStructure"])
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:215)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:221)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$buildNettyRequest$44(DefaultHttpClient.java:1566)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1566)
	at io.micronaut.http.client.netty.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1745)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$33(DefaultHttpClient.java:1108)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: com.example.IntrospectedDto["mapStructure"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:763)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4374)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3653)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:212)
	... 24 more
Caused by: java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap')
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.isEmpty(StringSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.isEmpty(MapSerializer.java:567)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.isEmpty(MapSerializer.java:33)
	at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionPropertyWriter.serializeAsField(BeanIntrospectionModule.java:643)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	... 30 more


```

### Environment Information

- **Operating System**: ubuntu 18.04
- **Micronaut Version:** 2.0.1
- **JDK Version:** OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)

### Example Application

https://github.com/katoquro/micronaut-issue

**Comment by graemerocher** [comment]
Triaged as Bug and closed as completed. The failure was in the old Core `BeanIntrospectionModule` Jackson integration: the current source no longer contains that module, and merged PR [#12207](https://github.com/micronaut-projects/micronaut-core/pull/12207) removed it in favor of standard Jackson handling. The reported `@Introspected`/`LinkedHashSet` serialization path is therefore addressed in current Core. Reopen with a current 5.x Jackson/Serde reproducer if the same mapping failure remains.
