### ISSUE TITLE
Multiple possible bean candidates found (using lombok)

### ISSUE THREAD

**Issue by jachinte** [micronaut-projects/micronaut-core#3918]
Micronaut is not able to select the bean to inject despite the fact that I am annotating the fields with `javax.inject.Named`. I am using Lombok to generate the constructor. If I remove lombok and specify the constructor manually, the app works as expected. The generated `.class` file does contain the correct constructor:

```java
    @java.beans.ConstructorProperties({"resolver", "serverLocale"})
    @javax.inject.Inject
    @lombok.Generated
    public HomeController(@javax.inject.Named("header") javax.inject.Provider<com.example.locale.LocaleResolver> resolver, @javax.inject.Named("default") com.example.locale.LocaleResolver serverLocale) { /* compiled code */ }
```

<details>
package com.example;

Am I doing something wrong or is this a bug?

@io.micronaut.http.annotation.Controller
@io.micronaut.security.annotation.Secured({"isAnonymous()"})
public class HomeController {
    @javax.inject.Named("header")
    private final javax.inject.Provider<com.example.locale.LocaleResolver> resolver;
    @javax.inject.Named("default")
    private final com.example.locale.LocaleResolver serverLocale;

    @io.micronaut.http.annotation.Get
    public com.example.HomeController.Locales index(io.micronaut.http.HttpRequest<?> request) { /* compiled code */ }

    @java.beans.ConstructorProperties({"resolver", "serverLocale"})
    @javax.inject.Inject
    @lombok.Generated
    public HomeController(@javax.inject.Named("header") javax.inject.Provider<com.example.locale.LocaleResolver> resolver, @javax.inject.Named("default") com.example.locale.LocaleResolver serverLocale) { /* compiled code */ }

    @io.micronaut.core.annotation.Introspected
    private static final class Locales {
        private final java.lang.String request;
        private final java.lang.String server;

        @java.beans.ConstructorProperties({"request", "server"})
        @lombok.Generated
        public Locales(java.lang.String request, java.lang.String server) { /* compiled code */ }

        @lombok.Generated
        public java.lang.String getServer() { /* compiled code */ }

        @lombok.Generated
        public boolean equals(java.lang.Object o) { /* compiled code */ }

        @lombok.Generated
        public int hashCode() { /* compiled code */ }

        @lombok.Generated
        public java.lang.String toString() { /* compiled code */ }

        @javax.inject.Inject
        @lombok.Generated
        public java.lang.String getRequest() { /* compiled code */ }
    }
}
</details>

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run `./gradlew run`
2. Visit `http://localhost:7878` in your browser

### Expected Behaviour

You should see a message with locale information in your browser.

### Actual Behaviour

An exception is thrown:

```java
00:47:44.277 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for parameter [arg0] of class: com.example.HomeController

Message: Multiple possible bean candidates found: [com.example.locale.DefaultLocaleResolver, com.example.locale.$HeaderBasedLocaleResolverDefinition$Intercepted]
Path Taken: new HomeController([Provider arg0],LocaleResolver arg1)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [arg0] of class: com.example.HomeController

Message: Multiple possible bean candidates found: [com.example.locale.DefaultLocaleResolver, com.example.locale.$HeaderBasedLocaleResolverDefinition$Intercepted]
Path Taken: new HomeController([Provider arg0],LocaleResolver arg1)
```

<details>
> Task :run
01:07:10.801 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2522ms. Server Running: http://localhost:7878
01:07:30.789 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for parameter [arg0] of class: com.example.HomeController

Message: Multiple possible bean candidates found: [com.example.locale.$HeaderBasedLocaleResolverDefinition$Intercepted, com.example.locale.DefaultLocaleResolver]
Path Taken: new HomeController([Provider arg0],LocaleResolver arg1)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [arg0] of class: com.example.HomeController

Message: Multiple possible bean candidates found: [com.example.locale.$HeaderBasedLocaleResolverDefinition$Intercepted, com.example.locale.DefaultLocaleResolver]
Path Taken: new HomeController([Provider arg0],LocaleResolver arg1)
        at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1828)
        at io.micronaut.context.AbstractBeanDefinition.getBeanProviderForConstructorArgument(AbstractBeanDefinition.java:1119)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:995)
        at com.example.$HomeControllerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2638)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2624)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.access$100(DefaultBeanContext.java:78)
        at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:426)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:469)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$9(RoutingInBoundHandler.java:1352)
        at io.micronaut.http.server.netty.RoutingInBoundHandler$$Lambda$1188/0000000000000000.call(Unknown Source)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onComplete(MaybeToFlowable.java:80)
        at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:72)
        at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onComplete(MaybeDoOnEvent.java:115)
        at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:72)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onComplete(FlowableElementAtMaybe.java:102)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:255)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:52)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
        at io.micronaut.http.server.context.ServerRequestContextFilter$$Lambda$1218/0000000000000000.subscribe(Unknown Source)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$5(RoutingInBoundHandler.java:1056)
        at io.micronaut.http.server.netty.RoutingInBoundHandler$$Lambda$1187/0000000000000000.apply(Unknown Source)
        at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:80)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:686)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:548)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:143)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:197)
        at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:191)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [com.example.locale.$HeaderBasedLocaleResolverDefinition$Intercepted, com.example.locale.DefaultLocaleResolver]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1978)
        at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:434)
        at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2615)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2539)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2469)
        at io.micronaut.context.DefaultBeanContext.getBeanProvider(DefaultBeanContext.java:1383)
        at io.micronaut.context.AbstractBeanDefinition.lambda$getBeanProviderForConstructorArgument$8(AbstractBeanDefinition.java:1120)
        at io.micronaut.context.AbstractBeanDefinition$$Lambda$235/0000000000000000.resolveBean(Unknown Source)
        at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1820)
        ... 136 common frames omitted
<=========----> 75% EXECUTING [33s]
> :run
^C%             
</details>

### Environment Information

- **Operating System**: MacOS Catalina (10.15.6)
- **Micronaut Version:** 2.0.2.BUILD-SNAPSHOT
- **JDK Version:** openjdk version "11.0.8" 2020-07-14

### Example Application

- https://github.com/jachinte/micronaut-lombok-annotations

**Comment by dstepanov** [comment]
It’s Lombok bug and hopefully fixed, can you try the latest Lombok snapshot?

**Comment by jachinte** [comment]
Unfortunately, it didn't work with the `edge-SNAPSHOT` version. Is this an interoperability error between micronaut and lombok? I see that the generated class contains the `Named` annotation.

**Comment by dstepanov** [comment]
Lombok didn't update parameters in the model https://github.com/micronaut-projects/micronaut-core/issues/1566

**Comment by jachinte** [comment]
The parameter names are correct:

```java
@java.beans.ConstructorProperties({"resolver", "serverLocale"})
@javax.inject.Inject
@lombok.Generated
public HomeController(@javax.inject.Named("header") javax.inject.Provider<com.example.locale.LocaleResolver> resolver, @javax.inject.Named("default") com.example.locale.LocaleResolver serverLocale) { /* compiled code */ }

```

**Comment by dstepanov** [comment]
@jachinte The problem here is when Lombok is processing classes it doesn't update parameter names and annotations in the model which is used by sequential processors including Micronaut. 

The problem should be fixed in the master but the edge release looks like it's was done before it.

**Comment by jachinte** [comment]
@dstepanov Just so you know, I compiled lombok locally and used the generated jar in the sample project. It produced the same error.

**Comment by dstepanov** [comment]
@jachinte Can you test with latest Lombok master?

**Comment by jachinte** [comment]
@dstepanov It does work, thank you!
