### ISSUE TITLE
ClassNotFoundException: java.sql.Date on java 10

### ISSUE THREAD

**Issue by jul1g** [micronaut-projects/micronaut-core#401]
On a simple application on java 10 : if you use Yaml format for application.properties : naming it application.yaml or application.yml : you get a ClassNotFoundException at startup

it seems to be the same issue that this one on eclipse https://bugs.eclipse.org/bugs/show_bug.cgi?id=507417 linked on a behavior change of the classloader.

> 17:17:46.640 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: java/sql/Date
java.lang.NoClassDefFoundError: java/sql/Date
	at org.yaml.snakeyaml.nodes.Tag.<clinit>(Tag.java:64)
	at org.yaml.snakeyaml.constructor.BaseConstructor.<init>(BaseConstructor.java:95)
	at org.yaml.snakeyaml.constructor.SafeConstructor.<init>(SafeConstructor.java:49)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:73)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:70)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:56)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:46)
	at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:64)
	at io.micronaut.context.env.yaml.YamlPropertySourceLoader.processInput(YamlPropertySourceLoader.java:51)
	at io.micronaut.context.env.AbstractPropertySourceLoader.read(AbstractPropertySourceLoader.java:99)
	at io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(AbstractPropertySourceLoader.java:88)
	at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:61)
	at io.micronaut.context.env.DefaultEnvironment.loadPropertySourceFromLoader(DefaultEnvironment.java:472)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:415)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:498)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:341)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:234)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:66)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:174)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:65)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:222)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:208)
	at example.Application.main(Application.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.ClassNotFoundException: java.sql.Date
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 29 common frames omitted

**Comment by jameskleeh** [comment]
@jul1g Can you include a sample application and steps to reproduce?

**Comment by jul1g** [comment]
my bad : i tried to reproduce from a fresh hello-world-java example checkout, and it works perfectly.
must be my fault
