### ISSUE TITLE
Bug v2.1.0 : Failed to inject value for parameter [binderRegistry] 

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-core#4139]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Created project using launch:
```
applicationType: default
defaultPackage: com.example
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [annotation-api, app-name, config-kubernetes, docker, file-watch, gradle, http-client, java, java-application, jib, junit, kubernetes, logback, management, netty-server, readme, yaml]
```

2. Created Controller:
```
@Controller("hello")
public class HelloController {

    public MyServiceClient client;

    public HelloController(MyServiceClient client) {
        this.client = client;
    }

    @Get("/{name}")
    public String hello(String name){
        return "Hello " + name + " !";
    }

    @Get("/ask/{name}")
    public String askService(String name){
        return client.hello(name);
    }
}
```

And my-service client:
```
@Client("my-service")
public interface MyServiceClient {

    @Get("/hello/{name}")
    String hello(String name);
}
```

### Expected Behaviour

The application starts up. 

### Actual Behaviour

Application fails on startup:
```
Looking up existing bean for key: io.micronaut.http.client.bind.HttpClientBinderRegistry
19:04:51.480 [main] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: io.micronaut.http.client.bind.HttpClientBinderRegistry
19:04:51.480 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.http.client.bind.HttpClientBinderRegistry
19:04:51.480 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [] for type: interface io.micronaut.http.client.bind.HttpClientBinderRegistry
19:04:51.482 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [binderRegistry] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice

Message: No bean of type [io.micronaut.http.client.bind.HttpClientBinderRegistry] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new DistributedPropertySourceLocator([ConfigurationClient configurationClient],Duration readTimeout) --> new DefaultCompositeConfigurationClient([ConfigurationClient[] configurationClients]) --> new KubernetesConfigurationClient([KubernetesClient client],KubernetesConfiguration configuration) --> new KubernetesClient$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new HttpClientIntroductionAdvice(BeanContext beanContext,RxHttpClientRegistry clientFactory,JsonMediaTypeCodec jsonMediaTypeCodec,List transformers,[HttpClientBinderRegistry binderRegistry])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [binderRegistry] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice

Message: No bean of type [io.micronaut.http.client.bind.HttpClientBinderRegistry] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new DistributedPropertySourceLocator([ConfigurationClient configurationClient],Duration readTimeout) --> new DefaultCompositeConfigurationClient([ConfigurationClient[] configurationClients]) --> new KubernetesConfigurationClient([KubernetesClient client],KubernetesConfiguration configuration) --> new KubernetesClient$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors]) --> new HttpClientIntroductionAdvice(BeanContext beanContext,RxHttpClientRegistry clientFactory,JsonMediaTypeCodec jsonMediaTypeCodec,List transformers,[HttpClientBinderRegistry binderRegistry])
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1035)
	at io.micronaut.http.client.interceptor.$HttpClientIntroductionAdviceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2964)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2852)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1040)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1143)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1820)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1138)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:987)
	at io.micronaut.kubernetes.client.v1.$KubernetesClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2638)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	at io.micronaut.kubernetes.configuration.$KubernetesConfigurationClientDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2964)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2875)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1040)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1143)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1820)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1138)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:987)
	at io.micronaut.discovery.config.$DefaultCompositeConfigurationClientDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2638)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	at io.micronaut.discovery.client.config.$DistributedPropertySourceLocatorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2638)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:728)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.resolveBootstrapPropertySourceLocator(DefaultApplicationContext.java:717)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:692)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:393)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:255)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:678)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:648)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:213)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at com.example.Application.main(Application.java:8)
```

### Environment Information

- **Operating System**: Docker image with JIB defaults
- **Micronaut Version:** 2.1.0.BUILD-SNAPSHOT
- **JDK Version:** Docker image with JIB defaults

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
Looks like `HttpClientBinderRegistry` needs to be annotated with bootstrap compatible /cc @jameskleeh
