### ISSUE TITLE
2.1.0 App doesn't start in AWS

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#4244]
```
│ Caused by: java.lang.UnsupportedOperationException                                                                                                                                                                                         │
│     at java.base/java.util.AbstractList.add(AbstractList.java:153)                                                                                                                                                                         │
│     at java.base/java.util.AbstractList.addAll(AbstractList.java:270)                                                                                                                                                                      │
│     at io.micronaut.context.env.DefaultEnvironment.<init>(DefaultEnvironment.java:117)                                                                                                                                                     │
│     at io.micronaut.context.DefaultApplicationContext$BootstrapEnvironment.<init>(DefaultApplicationContext.java:517)                                                                                                                      │
│     at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.createBootstrapEnvironment(DefaultApplicationContext.java:745)                                                                                          │
│     at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:695)                                                                                                               │
│     at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:665)                                                                                                               │
│     at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:213)                                                                                                                                 │
│     at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)                                                                                                                                            │
│     at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)   
```

**Comment by safarmer** [comment]
This issue is coming from setting the current environment (either through the environment variable `MICRONAUT_ENVIRONMENTS` or system property `micronaut.environments`). The `BootstrapEnvironment` passes an immutable list of environments to `DefaultEnvironment` which then attempts to add to this list.

See PR #4247 for a fix.

**Comment by jameskleeh** [comment]
@safarmer Do you have an example app that reproduces the issue? The bootstrap environment uses `Arrays.asList` as the return for `getEnvironments`, which should be mutable. https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java#L532

Edit: n/m. I saw in the source it creates an `ArrayList`, but that is `java.utils.Arrays.ArrayList`, not the same as `java.util.ArrayList`.

**Comment by safarmer** [comment]
@jameskleeh I thought I was mistaken with my fix as well, but taking that line out and running the updated tests (that use `Arrays.asList` as well) and they didn't pass.

**Comment by safarmer** [comment]
Also, it looks like another workaround is to remove `bootstrap.yaml`. From my understanding, having a bootstrap config causes Micronaut to recreate the environment and it is the second time around that the crash happens.
