### ISSUE TITLE
NonUniqueBeanException for java.util.concurrent.ThreadFactory after update to 2.1.0

### ISSUE THREAD

**Issue by Im-dex** [micronaut-projects/micronaut-core#4255]
Hi! My application doesn't start after updating to 2.1.0, cause of the error:

```
13:59:05.511 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [start_error.MyController] could not be loaded: Failed to inject value for parameter [threadFactory] of class: io.micronaut.scheduling.executor.ExecutorFactory

Message: Multiple possible bean candidates found: [java.util.concurrent.ThreadFactory, java.util.concurrent.ThreadFactory]
Path Taken: new MyController([ExecutorService service]) --> new ExecutorFactory(BeanLocator beanLocator,[ThreadFactory threadFactory])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [start_error.MyController] could not be loaded: Failed to inject value for parameter [threadFactory] of class: io.micronaut.scheduling.executor.ExecutorFactory

Message: Multiple possible bean candidates found: [java.util.concurrent.ThreadFactory, java.util.concurrent.ThreadFactory]
Path Taken: new MyController([ExecutorService service]) --> new ExecutorFactory(BeanLocator beanLocator,[ThreadFactory threadFactory])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2780)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at start_error.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [threadFactory] of class: io.micronaut.scheduling.executor.ExecutorFactory

Message: Multiple possible bean candidates found: [java.util.concurrent.ThreadFactory, java.util.concurrent.ThreadFactory]
Path Taken: new MyController([ExecutorService service]) --> new ExecutorFactory(BeanLocator beanLocator,[ThreadFactory threadFactory])
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1035)
	at io.micronaut.scheduling.executor.$ExecutorFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1206)
	at io.micronaut.scheduling.executor.$ExecutorFactory$ExecutorService1Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:143)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	at start_error.$MyControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2183)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 8 common frames omitted
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ThreadFactory, java.util.concurrent.ThreadFactory]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1987)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:434)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2548)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2478)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2259)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	... 29 common frames omitted

> Task :run FAILED
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [threadFactory] of class: io.micronaut.scheduling.executor.ExecutorFactory


Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ThreadFactory, java.util.concurrent.ThreadFactory]
```

### Steps to Reproduce

Try to inject `@Named(TaskExecutors.SCHEDULED) ExecutorService` into `@Context` scope bean.

### Expected Behaviour

Injection succeeded

### Actual Behaviour

Injection failed

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** 2.1.0
- **JDK Version:** 11

### Example Application

https://github.com/Im-dex/micronaut-thread-factory-issue

**Comment by dstepanov** [comment]
Probably `DefaultThreadFactory` needs to be `@BootstrapContextCompatible` 🤔
