### ISSUE TITLE
BeanInstantiationException: HTTP Client Health Check not enabled during application start up

### ISSUE THREAD

**Issue by mutyasaisrikar** [micronaut-projects/micronaut-core#4276]
We are using micronaut and integrating with AWS SQS. We are getting the below error during start-up of lambda everytime during start up

Bean definition [io.micronaut.context.event.ApplicationEventListener] could not be loaded: HTTP Client Health Check not enabled: io.micronaut.context.exceptions.BeanInstantiationException
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.context.event.ApplicationEventListener] could not be loaded: HTTP Client Health Check not enabled
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1533)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2763)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:227)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:125)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:80)
	at io.micronaut.function.aws.MicronautRequestStreamHandler.handleRequest(MicronautRequestStreamHandler.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Caused by: io.micronaut.context.exceptions.DisabledBeanException: HTTP Client Health Check not enabled

**Comment by ilopmar** [comment]
@mutyasaisrikar can you please check if you have the dependency on the HTTP Client? `implementation("io.micronaut:micronaut-http-client")`

By default it's not included with AWs features.

If you have it, then can you please share a sample project?

**Comment by graemerocher** [comment]
Please try upgrade to 2.1.0. I believe this is https://github.com/micronaut-projects/micronaut-core/issues/4096 which is already fixed
