### ISSUE TITLE
"Unconvertible input: null" when calling AWS GraalVM from test console

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#4287]
When deploying an AWS function as a GraalVM native image, there is an error when invoking the function directly from the AWS console.

### Steps to Reproduce

- `git clone https://github.com/micronaut-core-issues-test-app/mn-aws-function-graalvm`
- `cd mn-aws-function-graalvm`
- `sdk use java 20.2.0.r11-grl`
- `./build-native-image.sh`
- This will generate the file `build/function.zip` ready to be deployed
- Upload the file manually to AWS Lambda using a custom runtime with this config:

![image](https://user-images.githubusercontent.com/559192/95665767-9e3e3480-0b53-11eb-922a-f5b9a1bb6553.png)

If you prefer do the following to deploy using Cloudformation:
- Export the following variables:
```
export S3_BUCKET=USE-YOUR-OWN-BUCKET
export STACK_NAME=USE-YOUR-OWN-STACK-NAME
export AWS_ACCESS_KEY_ID=xxxxx
export AWS_SECRET_ACCESS_KEY=xxxxx
export AWS_DEFAULT_REGION=eu-central-1
```

```
aws cloudformation package --template-file sam-native.yaml --output-template-file build/output-sam.yaml --s3-bucket $S3_BUCKET
aws cloudformation deploy --template-file build/output-sam.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM

API_ENDPOINT=`aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[0] .Outputs[0] .OutputValue'`

curl -X POST -H 'Content-Type:application/json' -d '{"category":"foo"}' $API_ENDPOINT

# To delete everything
# aws cloudformation delete-stack --stack-name $STACK_NAME
```

The `curl` request will work:

![image](https://user-images.githubusercontent.com/559192/95665727-48698c80-0b53-11eb-9e9e-f2a1d2cf2c7d.png)

- Now go to the AWS Lambda console, open the new function created and send a "Test" request directly from the console.

![image](https://user-images.githubusercontent.com/559192/95665744-6df69600-0b53-11eb-8147-c98c487dfec4.png)

### Expected Behaviour

It should work

### Actual Behaviour

It fails with:

![image](https://user-images.githubusercontent.com/559192/95665755-7ea70c00-0b53-11eb-91ef-2c70b56d8848.png)

```
START RequestId: e2fd88e3-8c96-437a-9a4b-6371602d1e63 Version: $LATEST
Invocation with requestId [e2fd88e3-8c96-437a-9a4b-6371602d1e63] failed: Unconvertible input: nulljava.lang.IllegalArgumentException: Unconvertible input: null
	at io.micronaut.function.aws.MicronautRequestHandler.lambda$convertInput$0(MicronautRequestHandler.java:78)
	at java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.function.aws.MicronautRequestHandler.convertInput(MicronautRequestHandler.java:77)
	at io.micronaut.function.aws.MicronautRequestHandler.handleRequest(MicronautRequestHandler.java:59)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:347)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
	at example.micronaut.JokeLambdaRuntime.main(JokeLambdaRuntime.java:17)

END RequestId: e2fd88e3-8c96-437a-9a4b-6371602d1e63
REPORT RequestId: e2fd88e3-8c96-437a-9a4b-6371602d1e63	Duration: 154.80 ms	Billed Duration: 200 ms	Memory Size: 512 MB	Max Memory Used: 233 MB	
XRAY TraceId: 1-5f822cbf-1b2fc5607faa6df206ee001d	SegmentId: 614c9b2f2fe0c455	Sampled: true	
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.1.0
- **JDK Version:** 11 -> GraalVM

**Comment by ilopmar** [comment]
It doesn't work because it expects an API Gateway json and not a plain one.

Sending the rigth event makes it work.

```json
{
  "body": "{\"category\":\"foo\"}}",  <---------- WATCH THIS
  "resource": "/{proxy+}",
  "path": "/path/to/resource",
  "httpMethod": "POST",
  "isBase64Encoded": true,
  "queryStringParameters": {
    "foo": "bar"
  },
  "multiValueQueryStringParameters": {
    "foo": [
      "bar"
    ]
  },
  "pathParameters": {
    "proxy": "/path/to/resource"
  },
  "stageVariables": {
    "baz": "qux"
  },
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "max-age=0",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "1234567890.execute-api.eu-central-1.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Custom User Agent String",
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "multiValueHeaders": {
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate, sdch"
    ],
    "Accept-Language": [
      "en-US,en;q=0.8"
    ],
    "Cache-Control": [
      "max-age=0"
    ],
    "CloudFront-Forwarded-Proto": [
      "https"
    ],
    "CloudFront-Is-Desktop-Viewer": [
      "true"
    ],
    "CloudFront-Is-Mobile-Viewer": [
      "false"
    ],
    "CloudFront-Is-SmartTV-Viewer": [
      "false"
    ],
    "CloudFront-Is-Tablet-Viewer": [
      "false"
    ],
    "CloudFront-Viewer-Country": [
      "US"
    ],
    "Host": [
      "0123456789.execute-api.eu-central-1.amazonaws.com"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Custom User Agent String"
    ],
    "Via": [
      "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)"
    ],
    "X-Amz-Cf-Id": [
      "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA=="
    ],
    "X-Forwarded-For": [
      "127.0.0.1, 127.0.0.2"
    ],
    "X-Forwarded-Port": [
      "443"
    ],
    "X-Forwarded-Proto": [
      "https"
    ]
  },
  "requestContext": {
    "accountId": "123456789012",
    "resourceId": "123456",
    "stage": "prod",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "requestTime": "09/Apr/2015:12:34:56 +0000",
    "requestTimeEpoch": 1428582896000,
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "accessKey": null,
      "sourceIp": "127.0.0.1",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Custom User Agent String",
      "user": null
    },
    "path": "/prod/path/to/resource",
    "resourcePath": "/{proxy+}",
    "httpMethod": "POST",
    "apiId": "1234567890",
    "protocol": "HTTP/1.1"
  }
}
```
