### ISSUE TITLE
Unable to build the native image of an "out-of-the-box project" with Maven as building tool

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#4288]
Hi, previously, I was always creating Micronaut apps with Gradle as building tool. Today, I created an app with Maven and I am having issues building the native image.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

So, what I did:

1. went to https://micronaut.io/launch/; added the features, graalvm, jib and micrometer-prometheus; set java11; set Maven; set version 2.1.0; generated the project.
2. unzip the project;
3. navigated to project folder
4. kept the project as it is, i.e, didn't change anything in the project;
5. inside it ran, `./mvnw clean package` and then, `./docker-build.sh`

In the `docker-build.sh` run, I am getting
```
Sending build context to Docker daemon    172kB
Step 1/10 : FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
 ---> fbecb9923cd0
Step 2/10 : RUN gu install native-image
 ---> Using cache
 ---> 224342e36fff
Step 3/10 : COPY . /home/app/micronaut-simple-api
 ---> 3df8413ed52d
Step 4/10 : WORKDIR /home/app/micronaut-simple-api
 ---> Running in d1a8121bd504
Removing intermediate container d1a8121bd504
 ---> c76208dcabd6
Step 5/10 : RUN native-image -cp target/micronaut-simple-api-*.jar
 ---> Running in 90c316b47385
[micronaut-simple-api:25]    classlist:   4,332.52 ms,  0.96 GB
[micronaut-simple-api:25]        (cap):   1,220.51 ms,  0.96 GB
[micronaut-simple-api:25]        setup:   4,507.06 ms,  0.96 GB
[micronaut-simple-api:25]     (clinit):     223.00 ms,  1.19 GB
[micronaut-simple-api:25]     analysis:  20,625.29 ms,  1.19 GB
Warning: Aborting stand-alone image build due to unsupported features
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[micronaut-simple-api:107]    classlist:   3,933.68 ms,  0.96 GB
[micronaut-simple-api:107]        (cap):   1,406.68 ms,  0.96 GB
[micronaut-simple-api:107]        setup:   5,574.80 ms,  0.96 GB
[micronaut-simple-api:107]     (clinit):     224.24 ms,  1.19 GB
[micronaut-simple-api:107]   (typeflow):  14,495.19 ms,  1.19 GB
[micronaut-simple-api:107]    (objects):   6,998.20 ms,  1.19 GB
[micronaut-simple-api:107]   (features):     404.49 ms,  1.19 GB
[micronaut-simple-api:107]     analysis:  22,504.92 ms,  1.19 GB
[micronaut-simple-api:107]     universe:     844.52 ms,  1.19 GB
[micronaut-simple-api:107]      (parse):   4,992.58 ms,  1.19 GB
[micronaut-simple-api:107]     (inline):   2,807.35 ms,  1.48 GB
[micronaut-simple-api:107]    (compile):  22,245.28 ms,  1.93 GB
[micronaut-simple-api:107]      compile:  31,121.88 ms,  1.93 GB
[micronaut-simple-api:107]        image:   1,905.46 ms,  1.93 GB
[micronaut-simple-api:107]        write:     350.57 ms,  1.93 GB
[micronaut-simple-api:107]      [total]:  66,828.19 ms,  1.93 GB
Warning: Image 'micronaut-simple-api' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
Removing intermediate container 90c316b47385
 ---> 0b7ef7905aae
Step 6/10 : FROM frolvlad/alpine-glibc
 ---> 3a1c752f649f
Step 7/10 : RUN apk update && apk add libstdc++
 ---> Using cache
 ---> 04a4d1c004fd
Step 8/10 : EXPOSE 8080
 ---> Using cache
 ---> 004ab0625d5e
Step 9/10 : COPY --from=graalvm /home/app/micronaut-simple-api/micronaut-simple-api /app/micronaut-simple-api
 ---> 470f231ad5f4
Step 10/10 : ENTRYPOINT ["/app/micronaut-simple-api"]
 ---> Running in 18c6fb273f89
Removing intermediate container 18c6fb273f89
 ---> fde10bdce6ec
Successfully built fde10bdce6ec
Successfully tagged micronaut-simple-api:latest


To run the docker container execute:
    $ docker run -p 8080:8080 micronaut-simple-api
```

When I run it (`docker run -p 8080:8080 micronaut-simple-api`), I am getting
```
Error: No bin/java and no environment variable JAVA_HOME
```

Then, I added `-H:+ReportExceptionStackTraces` as it's saying in the logs.

After packaging the project again and running `./docker-build.sh`, I am getting
```
Sending build context to Docker daemon    172kB
Step 1/10 : FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
 ---> fbecb9923cd0
Step 2/10 : RUN gu install native-image
 ---> Using cache
 ---> 224342e36fff
Step 3/10 : COPY . /home/app/micronaut-simple-api
 ---> 00c65c4aa1fe
Step 4/10 : WORKDIR /home/app/micronaut-simple-api
 ---> Running in 8cb17d36324a
Removing intermediate container 8cb17d36324a
 ---> b60c628d3afb
Step 5/10 : RUN native-image -cp target/micronaut-simple-api-*.jar
 ---> Running in f5ef3334a288
[micronaut-simple-api:25]    classlist:   3,601.28 ms,  0.96 GB
[micronaut-simple-api:25]        (cap):   1,222.67 ms,  0.96 GB
[micronaut-simple-api:25]        setup:   4,512.10 ms,  0.96 GB
[micronaut-simple-api:25]     (clinit):     214.47 ms,  1.20 GB
[micronaut-simple-api:25]     analysis:  18,958.19 ms,  1.20 GB
Warning: Aborting stand-alone image build due to unsupported features
com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build due to unsupported features
	at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:209)
	at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:194)
	at com.oracle.svm.hosted.FallbackFeature.afterAnalysis(FallbackFeature.java:274)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:753)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[micronaut-simple-api:106]    classlist:   3,549.52 ms,  0.96 GB
[micronaut-simple-api:106]        (cap):   1,285.44 ms,  0.96 GB
[micronaut-simple-api:106]        setup:   4,787.19 ms,  0.96 GB
[micronaut-simple-api:106]     (clinit):     225.02 ms,  1.19 GB
[micronaut-simple-api:106]   (typeflow):  11,366.77 ms,  1.19 GB
[micronaut-simple-api:106]    (objects):   6,923.79 ms,  1.19 GB
[micronaut-simple-api:106]   (features):     381.68 ms,  1.19 GB
[micronaut-simple-api:106]     analysis:  19,280.63 ms,  1.19 GB
[micronaut-simple-api:106]     universe:     878.32 ms,  1.19 GB
[micronaut-simple-api:106]      (parse):   5,476.86 ms,  1.19 GB
[micronaut-simple-api:106]     (inline):   3,089.94 ms,  1.47 GB
[micronaut-simple-api:106]    (compile):  24,378.57 ms,  1.92 GB
[micronaut-simple-api:106]      compile:  34,196.93 ms,  1.92 GB
[micronaut-simple-api:106]        image:   2,140.38 ms,  1.92 GB
[micronaut-simple-api:106]        write:     281.63 ms,  1.92 GB
[micronaut-simple-api:106]      [total]:  65,667.34 ms,  1.92 GB
Warning: Image 'micronaut-simple-api' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
Removing intermediate container f5ef3334a288
 ---> f4c84382c801
Step 6/10 : FROM frolvlad/alpine-glibc
 ---> 3a1c752f649f
Step 7/10 : RUN apk update && apk add libstdc++
 ---> Using cache
 ---> 04a4d1c004fd
Step 8/10 : EXPOSE 8080
 ---> Using cache
 ---> 004ab0625d5e
Step 9/10 : COPY --from=graalvm /home/app/micronaut-simple-api/micronaut-simple-api /app/micronaut-simple-api
 ---> 39685b61c3d0
Step 10/10 : ENTRYPOINT ["/app/micronaut-simple-api"]
 ---> Running in ee786f10a315
Removing intermediate container ee786f10a315
 ---> fafa1b2a8d13
Successfully built fafa1b2a8d13
Successfully tagged micronaut-simple-api:latest


To run the docker container execute:
    $ docker run -p 8080:8080 micronaut-simple-api
```

### Expected Behaviour

The customer should be able to build easily the native image of an "out-of-the-box project" with Maven as building tool

### Actual Behaviour

Unable to build the native image of an "out-of-the-box project" with Maven as building tool

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.1.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
Select `jib` disables shadow jar, that is probably why

**Comment by ivangfr** [comment]
Exactly @graemerocher ! By removing `jib`, I can build the native image of an "out-of-the-box" project with Maven as building tool. I was thinking about using `jib` to build the jvm image and the traditional `docker build` to build the native one.
