### ISSUE TITLE
Add meaningful toString() for DefaultConstraintViolation

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4317]
When constraint violation is thrown using Micronaut validation here is what's visible in the logs:

```
javax.validation.ConstraintViolationException: Validation failed for classes [io.luna.service.main.finance.investment.domain.InvestmentConfig] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	io.micronaut.validation.validator.DefaultValidator$DefaultConstraintViolation@a553f8e
	io.micronaut.validation.validator.DefaultValidator$DefaultConstraintViolation@11252816
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
	at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:227)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
```

It would be useful to give more meaningful output here than `DefaultConstraintViolation@a553f8e`, for example what's the root bean, property path and invalid value.

**Comment by luis-valdez** [comment]
Hello! I would like to make my first contribution. Can I work on this?
