### ISSUE TITLE
Unable to invoke services with @Client registered in Eureka

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#440]
### Steps to Reproduce

1. Clone https://github.com/micronaut-guides/micronaut-microservices-services-discover-eureka
2. **Start Eureka Server**: 
2.1 cd eureka; 
2.2 eureka $ ./gradlew bootRun 
3. **Start bookcatalogue Micronaut app**
3.1 cd complete
3.2 complete $./gradlew bookcatalogue:run
4. **Start bookinventory Micronaut app**
4.1 cd complete
4.2 complete $./gradlew bookinventory:run
4. **Start bookrecommendation Micronaut app**
4.1 cd complete
4.2 complete $./gradlew bookrecommendation:run

Verify services get registered:

<img width="1322" alt="eurekaui" src="https://user-images.githubusercontent.com/864788/43253078-6071f1f2-90c4-11e8-8721-22b769b1aeae.png">

Try do to a request which involves invoking several services:

```
$ curl localhost:8080/books
curl: (18) transfer closed with outstanding read data remaining
```

### Expected Behaviour

Application should communicate with other services with `@Client` finding them via Eureka.

### Actual Behaviour

This error is thrown:

```
11:10:29.099 [nioEventLoopGroup-1-48] ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: Not Found
io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found
	at io.micronaut.http.client.DefaultHttpClient$6.channelRead0(DefaultHttpClient.java:1380)
	at io.micronaut.http.client.DefaultHttpClient$6.channelRead0(DefaultHttpClient.java:1319)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:184)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: MacOS High Sierra
- **Micronaut Version:** 1.0.0.M3
- **JDK Version:** 1.8.0_152

### Example Application

https://github.com/micronaut-guides/micronaut-microservices-services-discover-eureka

**Comment by graemerocher** [comment]
Some improvements have been made to this area here https://github.com/micronaut-projects/micronaut-core/commit/19c1c5f0e4376772fcb79ac2abe1e5b4ff08efde

**Comment by graemerocher** [comment]
But Eureka integration itself is working fine
