### ISSUE TITLE
Java 10 compatibility: javax.annotations split package between module java.xml.ws.annotation and JSR305 dependency

### ISSUE THREAD

**Issue by mikaelhg** [micronaut-projects/micronaut-core#441]
When building and executing a Micronaut 1.0.0.M3 application on Java 9 or 10, `micronaut-core`'s use of  annotations in the package `javax.annotations` becomes an issue.

The package `javax.annotations` holds classes from two sources: the Jigsaw module `java.xml.ws.annotation` (classes such as `javax.annotation.PostConstruct`) as well as `micronaut-core`'s direct transitive dependency `com.google.code.findbugs:jsr305:3.0.2` (classes such as `javax.annotation.Nullable`).

All this is A-OK in Java 8, but produces a situation called a "split package" from Java 9 onwards.

There are [various ways to rectify the situation](https://blog.codefx.org/java/jsr-305-java-9/), the most future-proof of which seems to be to explicitly depend on `javax.annotation:javax.annotation-api`, and skip the module dependency to `java.xml.ws.annotation` altogether, as [it has already been deprecated](https://docs.oracle.com/javase/10/docs/api/java.xml.ws.annotation-summary.html) and scheduled for later removal.

### Error messages: 

```text
$ java -Xmx32m -jar build/libs/app.jar
15:59:18.647 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.reactive.rxjava2.RxJava2Instrumentation] could not be loaded: Error instantiating bean of type [io.micronaut.reactive.rxjava2.RxJava2Instrumentation]: javax/annotation/PostConstruct
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.reactive.rxjava2.RxJava2Instrumentation] could not be loaded: Error instantiating bean of type [io.micronaut.reactive.rxjava2.RxJava2Instrumentation]: javax/annotation/PostConstruct
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:990)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:189)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1801)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:171)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:139)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
        at io.mikael.app.Application.main(app.kt:17)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.reactive.rxjava2.RxJava2Instrumentation]: javax/annotation/PostConstruct
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1283)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1682)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1378)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:988)
        ... 6 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at io.micronaut.context.DefaultMethodInjectionPoint.isPostConstructMethod(DefaultMethodInjectionPoint.java:128)
        at io.micronaut.context.AbstractBeanDefinition.postConstruct(AbstractBeanDefinition.java:628)
        at io.micronaut.reactive.rxjava2.$RxJava2InstrumentationDefinition.initialize(Unknown Source)
        at io.micronaut.reactive.rxjava2.$RxJava2InstrumentationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1267)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 14 common frames omitted

$ java --add-modules java.xml.ws.annotation -Xmx32m -jar build/libs/app.jar
15:58:37.562 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type [io.micronaut.jackson.bind.MapToObjectConverter]: javax/annotation/Nullable
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.jackson.bind.MapToObjectConverter]: javax/annotation/Nullable
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1283)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:1994)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:1925)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:736)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:520)
        at io.micronaut.context.DefaultApplicationContext.initializeTypeConverters(DefaultApplicationContext.java:317)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:185)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1801)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:171)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:139)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
        at io.mikael.app.Application.main(app.kt:17)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Nullable
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:945)
        at io.micronaut.jackson.bind.$MapToObjectConverterDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1267)
        ... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.annotation.Nullable
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 14 common frames omitted
```

**Comment by graemerocher** [comment]
This is already documented here https://docs.micronaut.io/latest/guide/index.html#java

The solution being to add the `javax.annotation` jar file. I am not sure what else we can do?

**Comment by mikaelhg** [comment]
I'm sorry, I missed that in the document. An explicit dependency would mean that people don't bump into this issue.

**Comment by msgilligan** [comment]
> This is already documented here https://docs.micronaut.io/latest/guide/index.html#java

> The solution being to add the javax.annotation jar file. I am not sure what else we can do?

@graemerocher The documentation is incorrect for Micronaut 1.1.0 adding the dependency is **no longer necessary** but there is a split package issue. (I've brought this up in Gitter and submitted a PR to the examples repo with a modular project that demonstrates the issue: https://github.com/micronaut-projects/micronaut-examples/pull/45
