### ISSUE TITLE
ServiceReadyHealthIndicator Down with Micronaut version > 2.0.1

### ISSUE THREAD

**Issue by prayadav** [micronaut-projects/micronaut-core#4508]
### Steps to Reproduce

1. Template micronaut project with version > 2.0.1  with micronaut-management dependency
2. JDK version 14
3. endpoints default configuration
endpoints:
  all:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS

### Expected Behaviour

/health endpoint should return "UP" status

### Actual Behaviour

/health endpoint returns

{
  "details": {
    "compositeDiscoveryClient()": {
      "name": "mntemplateapi", 
      "status": "UP"
    }, 
   
    "service": {
      "name": "mntemplateapi", 
      "status": "DOWN"
    }
  }, 
  "name": "mntemplateapi", 
  "status": "DOWN"
}

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 2.1.3
- **JDK Version:** 14

Running the project in debug mode shows some error in the console -

20:26:07.985 [Connector-Scheduler-1556f2dd-1] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@448f92af{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30004/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by prayadav** [comment]
It seems the service status shows down only with embedded jetty. Works fine with netty.

**Comment by prayadav** [comment]
It seems the problem manifests with embedded jetty. I tried with netty and all health indicators are fine.
