### ISSUE TITLE
Error encountered while parsing org.graalvm.home.HomeFinder.getInstance()

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#4585]
Hi guys!

I've recently updated the **Micronaut** apps inside Java framework comparison project to version `2.2.0`;

The [`micronaut-elasticsearch`](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch) app is failing to build the docker native image. Here is the exception
```
[INFO] Fatal error:
[INFO] com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.graalvm.home.HomeFinder.getInstance()
Parsing context:
  parsing org.graalvm.polyglot.Engine.getVersion(Engine.java:203)
  parsing com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getEngineVersion(GraalJSEngineFactory.java:132)
  parsing com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getParameter(GraalJSEngineFactory.java:168)
  parsing org.apache.logging.log4j.core.script.ScriptManager.<init>(ScriptManager.java:84)
  parsing org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:219)
  parsing org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
  parsing org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
  parsing org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
  parsing org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
  parsing org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
  parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
  parsing org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
  parsing org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
  parsing org.apache.logging.log4j.LogManager.getLogger(LogManager.java:602)
  parsing org.apache.logging.log4j.LogManager.getLogger(LogManager.java:669)
  parsing io.micronaut.management.endpoint.loggers.impl.Log4jLoggingSystem.getLogger(Log4jLoggingSystem.java:61)
  parsing io.micronaut.management.endpoint.loggers.impl.DefaultLoggersManager.getLogger(DefaultLoggersManager.java:55)
  parsing io.micronaut.management.endpoint.loggers.impl.$DefaultLoggersManagerDefinition$$exec1.invokeInternal(Unknown Source)
  parsing io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
  parsing io.micronaut.validation.validator.DefaultValidator.validateBean(DefaultValidator.java:1721)
  parsing io.micronaut.inject.ValidatedBeanDefinition.validate(ValidatedBeanDefinition.java:44)
  parsing io.micronaut.context.BeanDefinitionDelegate$ProxyValidatingBeanDefinition.validate(BeanDefinitionDelegate.java:276)
  parsing io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1963)
  parsing io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2392)
  parsing io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2307)
  parsing io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2279)
  parsing io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1266)
  parsing io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:744)
  parsing io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
  parsing io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
  parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
  parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
  parsing com.mycompany.micronautelasticsearch.Application.main(Application.java:8)
  parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
  parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
  parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

[INFO]

[INFO]  at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[INFO]

[INFO]  at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:331)
[INFO]

[INFO]  at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
[INFO]

[INFO]  at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
[INFO]

[INFO]  at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:434)
[INFO]

[INFO]  at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)

[INFO]  at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[INFO]

[INFO]  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[INFO]

[INFO]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[INFO]
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[INFO]

[INFO]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[INFO]
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[INFO]

[INFO]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[INFO]

[INFO] Caused by: com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key org.graalvm.home.HomeFinder
[INFO]

[INFO]  at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[INFO]
  at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:119)
[INFO]

[INFO]  at com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
[INFO]
  at org.graalvm.sdk/org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86)
[INFO]

[INFO]  at com.oracle.svm.hosted.snippets.SubstrateGraphBuilderPlugins$43.apply(SubstrateGraphBuilderPlugins.java:1011)

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:189)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.applyInvocationPlugin(BytecodeParser.java:2185)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2171)
[INFO]
  at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase$AnalysisBytecodeParser.tryInvocationPlugin(AnalysisGraphBuilderPhase.java:67)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1876)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1637)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1617)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5360)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3399)
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3206)
[INFO]

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1092)
[INFO]
  at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:986)

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[INFO]
  at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:70)
[INFO]

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[INFO]

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[INFO]

[INFO]  at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[INFO]

[INFO]  at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
[INFO]
  at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)

[INFO]  at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
[INFO]

[INFO]  ... 11 more
[INFO]

[INFO] Error: Image build request failed with exit status 1

[ERROR] The command '/bin/sh -c native-image ${GRAALVM_ARGS} -H:Class=${CLASS_NAME} -H:Name=application --no-fallback -cp "/home/app/libs/*:/home/app/classes/"' returned a non-zero code: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:38 min
[INFO] Finished at: 2020-11-21T19:13:43+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.micronaut.build:micronaut-maven-plugin:1.1.0:docker-native (default-docker-native) on project micronaut-elasticsearch: Could not build image: The command '/bin/sh -c native-image ${GRAALVM_ARGS} -H:Class=${CLASS_NAME} -H:Name=application --no-fallback -cp "/home/app/libs/*:/home/app/classes/"' returned a non-zero code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException 
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone project https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot
2. Build the docker native image as explained at https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch#docker-in-native-mode. You should see the exception during the building.

### Environment Information

- **Operating System**: Mac OS X
- **Micronaut Version:** 2.2.2
- **JDK Version:** 11

### Example Application

- https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch

**Comment by ilopmar** [comment]
This is a know issue. Reported to GraalVM https://github.com/oracle/graal/issues/2991

**Comment by ilopmar** [comment]
Btw, even with the workarounds explained in that issue, our test application hangs on https://github.com/micronaut-graal-tests/micronaut-elasticsearch-graal/blob/bda0ef2acdd33bc89fe58b560d12a49fb322145a/src/main/java/micronaut/example/service/MovieServiceImpl.java#L46
while saving a movie in Elasticsearch. This is probably due to the 7.9.3 upgrade. 
I haven't found time to test with 7.10.

**Comment by ivangfr** [comment]
Hi @ilopmar , I tried to apply the workaround in my application, i.e, add `--features=org.graalvm.home.HomeFinderFeature` in `native-image.properties`,

But I am getting
```
> Could not build image: COPY failed: stat /var/lib/docker/overlay2/3cf6dd41355290d0e029a44f7ea4d2fca8cb4390867faa1d4af4ffeb14a901da/merged/home/app/application: no such file or directory
```

The issue above was discussed here (https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/50) and it's because I set back the `native-image.properties` in `META-INF/native-image`.

How can I set `--features=org.graalvm.home.HomeFinderFeature` without creating `native-image.properties` file?

Thanks in advance.

**Comment by ilopmar** [comment]
@ivangfr The issue is not that you have a  `native-image.properties` file but that it contains `-H:Class=xxx` and `-H:Name=xxx` properties. Remove only those properties from your `native-image.properties` file.

You can also pass parameters to the native-image with:
```
nativeImage {
    args('--static')
}
```

**Comment by ivangfr** [comment]
Thanks. Yes, I am able to compile the native image and run it.

The search for movies feature works but, when I try to index a movie, the app hangs on the same point as in your test app
```
IndexRequest indexRequest = new IndexRequest(moviesIndex).source(movieAsJsonString, XContentType.JSON);
```
I've tried also with Elasticsearch `7.10.0`, the same problem.

**Comment by ilopmar** [comment]
Yeah, maybe the issue is on Elasticsearch or GraalVM side, not sure...

**Comment by ivangfr** [comment]
@ilopmar , I've been playing around with this problem and, it's weird because the app hangs by even calling the no-args constructor `IndexRequest`.
```
IndexRequest indexRequest = new IndexRequest();
```
The same happens with `DeleteRequest` and `BulkRequest`.

The `SearchRequest` is an exception, so that is why the _search_ is working.

What do the Index/Delete/BulkRequest classes have that is different?

Here are their signatures
```
public class IndexRequest extends ReplicatedWriteRequest<IndexRequest> implements DocWriteRequest<IndexRequest>, CompositeIndicesRequest
public class DeleteRequest extends ReplicatedWriteRequest<DeleteRequest> implements DocWriteRequest<DeleteRequest>, CompositeIndicesRequest
public class BulkRequest extends ActionRequest implements CompositeIndicesRequest, WriteRequest<BulkRequest>, Accountable
public class SearchRequest extends ActionRequest implements IndicesRequest.Replaceable
```

**Comment by ivangfr** [comment]
Hi @ilopmar Looks like that with **GraalVM** `21.1` the native image building issue seems to be fixed.

Now, there is a problem while executing an app that uses `Elasticsearch`. Looks like whenever we use `IndexRequest`, `DeleteRequest`, `BulkRequest`, the app gets stuck as I described in the issue https://github.com/micronaut-projects/micronaut-elasticsearch/issues/188

So, should we close this issue? Thanks!
