### ISSUE TITLE
Context scope beans don't respect @EachProperty / @EachBean event listeners correctly

### ISSUE THREAD

**Issue by wbprime** [micronaut-projects/micronaut-core#4630]
When using jooq together with data-jdbc (to gain declarative transaction support) with 2 datasources config, exception io.micronaut.context.exceptions.NoSuchBeanException got thrown when trying to perform db operations.

Below list a demo project being able to reproduce this issue.

Contact me if more info required.

### Steps to Reproduce

1. add micronaut-jooq & micronaut-data-jdbc dep
2. add 2 datasource config in application.yml
3. use 2 jooq DSLContext instance injected using @Named annotation

### Expected Behaviour

All operations on injected DSLContext should work properly.

### Actual Behaviour

Got connection injecting error: 

```
ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: No bean of type [
java.sql.Connection] exists for the given qualifier: @Named('default'). Make sure the bean is not disabled by bean requirements (enab
le trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean a
nd annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation
 processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.sql.Connection] exists for the given qualifier: @Named('de
fault'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check)
 and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'm
icronaut-inject-java' dependency should be configured as an annotation processor).
        at org.jooq_3.14.3.H2.debug(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2290)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:721)
        at io.micronaut.transaction.jdbc.TransactionAwareDataSource.getTransactionAwareConnection(TransactionAwareDataSource.java:69)
        at io.micronaut.transaction.jdbc.TransactionAwareDataSource.access$000(TransactionAwareDataSource.java:39)
        at io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy.getConnection(TransactionAwareDataSource.java:94)
        at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
        at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:649)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:338)
        at org.jooq.impl.DefaultDSLContext.execute(DefaultDSLContext.java:1124)
        at com.example.TheRepository.createTableInA(TheRepository.java:22)
        at com.example.TheController.hello(TheController.java:21)
        at com.example.$TheControllerDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:255)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1365)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$6(RoutingInBoundHandler.java:1070)
        at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:80)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:697)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:553)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:148)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199)
        at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler
.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: Archlinux 5.9.9-arch1-1 micronaut-projects/micronaut-sql#1 SMP PREEMPT x86_64 GNU/Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 

java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

### Example Application

- <https://github.com/wbprime/micronaut-tx-issue-for-2-datasources>

Try run `mvn clean test`.

Already create a issue in micronaut-data project as <https://github.com/micronaut-projects/micronaut-data/issues/822#issue-747905492>, but seems nobody is interested in this. Or maybe I misused something.

**Comment by wbprime** [comment]
@graemerocher What about the `io.micronaut.transaction.jdbc.TransactionAwareDataSource` support for multiple DataSource ?

Here is the source of `io.micronaut.transaction.jdbc.TransactionAwareDataSource`:

```
@Singleton
@Requires(missingClasses = "org.springframework.jdbc.datasource.DataSourceTransactionManager")
public class TransactionAwareDataSource implements BeanCreatedEventListener<DataSource> {
    private final BeanLocator beanLocator;

    private Connection transactionAwareConnection;
    private String qualifier;

    /**
     * Create a new DelegatingDataSource.
     *
     * @param beanLocator The bean locator
     */
    public TransactionAwareDataSource(
            BeanLocator beanLocator) {
        this.beanLocator = beanLocator;
    }

    @Override
    public DataSource onCreated(BeanCreatedEvent<DataSource> event) {
        final BeanIdentifier beanIdentifier = event.getBeanIdentifier();
        String name = beanIdentifier.getName();
        if (name.equalsIgnoreCase("primary")) {
            name = "default";
        }
        this.qualifier = name;
        return new DataSourceProxy(event.getBean());
    }

    private Connection getTransactionAwareConnection() {
        if (transactionAwareConnection == null) {
            transactionAwareConnection
                    = beanLocator.getBean(Connection.class, Qualifiers.byName(qualifier));

        }
        return transactionAwareConnection;
    }

    /**
     * The transaction aware proxy implementation.
     *
     * @author graemerocher
     * @since 1.0.1
     */
    private final class DataSourceProxy extends DelegatingDataSource {

        /**
         * Create a new DelegatingDataSource.
         *
         * @param targetDataSource the target DataSource
         */
        DataSourceProxy(@NonNull DataSource targetDataSource) {
            super(targetDataSource);
        }

        @Override
        public Connection getConnection() throws SQLException {
            return getTransactionAwareConnection();
        }
    }
}
```

Consider the inner class `DataSourceProxy`, it caches/reuses the `transactionAwareConnection` variable (as far as I see) even when multiple `BeanCreatedEvent<DataSource>` events are fired.  Does that make sense ?

**Comment by graemerocher** [comment]
@wbprime No it doesn't make sense either. Can you report a separate issue to https://github.com/micronaut-projects/micronaut-data/issues ?

**Comment by wbprime** [comment]
Done. See <https://github.com/micronaut-projects/micronaut-data/issues/822#issue-747905492>.
