### ISSUE TITLE
Failed to allocate direct memory in 2.2.1 using StreamingFileUpload

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-core#4752]
We tried upgrading one of our services from 2.0.0 to 2.2.1 to solve file corruption in one specific upload. When we upgraded all larger uploads (~70mb) caused:` [default-nioEventLoopGroup-5-4] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: failed to allocate 130023424 byte(s) of direct memory (used: 369098759, max: 496697344)` errors. When reverting (using the same resource allocations, jvm version 1.8, in k8s pod...), the memory problems were fixed.

Here's a stack trace:

```

2020-12-24 15:23:46 | io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 79691776 byte(s) of direct memory (used: 92274695, max: 170328064)
-- | --
  |   | 2020-12-24 15:23:46 | 2020-12-24 13:23:46.331 [default-nioEventLoopGroup-5-4] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: failed to allocate 79691776 byte(s) of direct memory (used: 92274695, max: 170328064)
  |   | 2020-12-24 15:20:30 | at io.micrometer.core.instrument.Timer$$Lambda$527/1709882027.run(Unknown Source)
  |   | 2020-12-24 15:20:30 | at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
  |   | 2020-12-24 15:20:30 | at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
  |   | 2020-12-24 15:20:30 | at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
  |   | 2020-12-24 15:20:30 | at io.reactivex.Flowable.subscribe(Flowable.java:14865)
  |   | 2020-12-24 15:20:30 | at io.reactivex.Flowable.subscribe(Flowable.java:14918)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
  |   | 2020-12-24 15:20:30 | at io.reactivex.Flowable.subscribe(Flowable.java:14918)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle.subscribeActual(FlowableDoOnLifecycle.java:38)
  |   | 2020-12-24 15:20:30 | at io.reactivex.Flowable.subscribe(Flowable.java:14918)
  |   | 2020-12-24 15:20:30 | at io.reactivex.processors.UnicastProcessor.subscribeActual(UnicastProcessor.java:500)
  |   | 2020-12-24 15:20:30 | at io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:398)
  |   | 2020-12-24 15:20:30 | at io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:322)
  |   | 2020-12-24 15:20:30 | at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:59)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
  |   | 2020-12-24 15:20:30 | at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:59)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
  |   | 2020-12-24 15:20:30 | at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:59)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
  |   | 2020-12-24 15:20:30 | at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:59)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
  |   | 2020-12-24 15:20:30 | at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
  |   | 2020-12-24 15:20:30 | at io.micronaut.http.server.netty.multipart.NettyStreamingFileUpload$1.onNext(NettyStreamingFileUpload.java:119)
  |   | 2020-12-24 15:20:30 | at io.micronaut.http.server.netty.multipart.NettyStreamingFileUpload$1.onNext(NettyStreamingFileUpload.java:136)
  |   | 2020-12-24 15:20:30 | at io.micronaut.http.server.netty.multipart.NettyPartData.getBytes(NettyPartData.java:79)
  |   | 2020-12-24 15:20:30 | at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1072)
  |   | 2020-12-24 15:20:30 | at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1080)
  |   | 2020-12-24 15:20:30 | at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1100)
  |   | 2020-12-24 15:20:30 | at java.util.Arrays.copyOfRange(Arrays.java:3520)
  |   | 2020-12-24 15:20:30 | Exception in thread "io-executor-thread-1" java.lang.OutOfMemoryError: Java heap space
  |   | 2020-12-24 15:18:48 | at java.lang.Thread.run(Thread.java:748)
  |   | 2020-12-24 15:18:48 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  |   | 2020-12-24 15:18:48 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  |   | 2020-12-24 15:18:48 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
  |   | 2020-12-24 15:18:48 | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
  |   | 2020-12-24 15:18:48 | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:474)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:547)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:248)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:163)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:257)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:292)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  |   | 2020-12-24 15:18:48 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.reactive.HandlerPublisher.channelRead(HandlerPublisher.java:334)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.netty.reactive.HandlerPublisher.publishMessage(HandlerPublisher.java:378)
  |   | 2020-12-24 15:18:48 | at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:52)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.server.netty.AbstractHttpContentProcessor.doOnNext(AbstractHttpContentProcessor.java:36)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.server.netty.AbstractHttpContentProcessor.doOnNext(AbstractHttpContentProcessor.java:78)
  |   | 2020-12-24 15:18:48 | at io.micronaut.http.server.netty.FormDataHttpContentProcessor.onData(FormDataHttpContentProcessor.java:115)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
  |   | 2020-12-24 15:18:48 | at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:351)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1105)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:307)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PoolArena.reallocate(PoolArena.java:288)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PoolArena.allocate(PoolArena.java:143)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:215)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:635)
  |   | 2020-12-24 15:18:48 | at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645)
  |   | 2020-12-24 15:18:48 | at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:730)
  |   | 2020-12-24 15:18:48 | at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:775)
  |   | 2020-12-24 15:18:48 | io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 79691776 byte(s) of direct memory (used: 92274695, max: 170328064)
  |   | 2020-12-24 15:18:48 | 2020-12-24 13:18:48.165 [default-nioEventLoopGroup-5-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: failed to allocate 79691776 byte(s) of direct memory (used: 92274695, max: 170328064)
```

**Comment by jameskleeh** [comment]
@dave08 Please upload a sample app or sample code that reproduces the issue

**Comment by jameskleeh** [comment]
Closed due to a lack of feedback. Will re-open when an example is uploaded
