### ISSUE TITLE
Micronaut OpenAPI POM broken

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4858]
The POM for micronaut-openapi is broken which is causing problems in Maven. The following warning is printed:

```
[WARNING] Invalid POM for io.micronaut.openapi:micronaut-openapi:jar:2.3.0, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading from central: https://repo.maven.apache.org/maven2/io/micronaut/openapi/micronaut-openapi/2.3.0/micronaut-openapi-2.3.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/micronaut/openapi/micronaut-openapi/2.3.0/micronaut-openapi-2.3.0.jar (965 kB at 4.5 MB/s)
```

And then this results in compilation errors:

```
Caused by: java.lang.NoClassDefFoundError: io/swagger/v3/oas/annotations/responses/ApiResponse
        at io.micronaut.openapi.annotation.transformers.ApiResponseRetentionPolicyAnnotationTransformer.<init>(ApiResponseRetentionPolicyAnnotationTransformer.java:32)
        ... 61 more
Caused by: java.lang.ClassNotFoundException: io.swagger.v3.oas.annotations.responses.ApiResponse
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 62 more

```

### Steps to Reproduce

1. Create a Maven project with OpenAPI
2. Try compile
3. Boom

### Expected Behaviour

Fails with compilation error

### Actual Behaviour

Should compile.

### Environment Information

- **Operating System**: Any
- **Micronaut Version:** 2.3.0
- **JDK Version:** Any

**Comment by alvarosanchez** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-openapi/issues/444
