### ISSUE TITLE
`BeanIntrospectionModule` breaks deserialization of simple String wrappers 

### ISSUE THREAD

**Issue by achaphiv** [micronaut-projects/micronaut-core#4884]
### Steps to Reproduce

- Create a new project from https://micronaut.io/launch
- Add this test:
  ```java
  public class IntrospectedDeserializationTest {
    @Introspected
    public static final class Wrapper {
      final String value;
  
      public Wrapper(String value) {
        this.value = value;
      }
    }
  
    @Test
    public void deserializeViaReflection() throws Exception {
      ObjectMapper mapper = new ObjectMapper();
  
      mapper.readValue("\"good\"", Wrapper.class);
    }
  
    @Test
    public void deserializeViaBeanIntrospection() throws Exception {
      ObjectMapper mapper = new ObjectMapper();
      mapper.registerModule(new BeanIntrospectionModule());
  
      mapper.readValue("\"bad\"", Wrapper.class);
    }
  }
  ```
- Watch it fail on 2nd test case with (truncated) stack trace:
  ```
  Cannot construct instance of `com.example.IntrospectedDeserializationTest$Wrapper` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('bad')
   at [Source: (String)""bad""; line: 1, column: 1]
  com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.example.IntrospectedDeserializationTest$Wrapper` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('bad')
   at [Source: (String)""bad""; line: 1, column: 1]
	  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	  at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455)
	  at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	  at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1408)
	  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	  at com.example.IntrospectedDeserializationTest.deserializeViaBeanIntrospection(IntrospectedDeserializationTest.java:30)
  ```

### Expected Behaviour

If regular jackson works, only adding `BeanIntrospectionModule` should also work.

### Actual Behaviour

Normal reflection still works, while `BeanIntrospectionModule` breaks deserialization.

### Environment Information

- **Operating System**: Manjaro kernel 5.10.7-3-MANJARO
- **Micronaut Version:** 2.3.1
- **JDK Version:** 11.0.10

### Example Application

https://github.com/achaphiv/issue-micronaut-introspection-2/

Maybe related to a couple of other `@Introspected` issues, but this is a smaller test case.

**Comment by achaphiv** [comment]
I can confirm that the basic types are working v2.3.3.

List wrappers are still broken.

E.G.
```java
@Introspected
public static final class ListWrapper {
  final List<String> value;

  @JsonCreator
  public Wrapper(List<String> value) {
    this.value = value;
  }
}
```

```java
@Test
public void deserializeViaBeanIntrospection() throws Exception {
  ObjectMapper mapper = new ObjectMapper();
  mapper.registerModule(new BeanIntrospectionModule());

  mapper.readValue("[\"bad\"]", ListWrapper.class);
}
```

**Comment by jameskleeh** [comment]
@achaphiv Please create a new issue
