### ISSUE TITLE
Micronaut is eagerly initialising non-singleton factory methods and parameterised beans incorrectly

### ISSUE THREAD

**Issue by neoXfire** [micronaut-projects/micronaut-core#4929]
## Steps to Reproduce
1. Checkout `hello-world-kotlin` project.
2. Add `.eagerInitSingletons(true)` in the bootstrap method call

## Expected Behaviour
The server starts
```
02:52:20.190 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1006ms. Server Running: http://localhost:8080
```

## Actual Behaviour
The server fails to start
```
02:53:14.202 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1466)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2682)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:216)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at helloworld.Application.main(Application.kt:13)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1842)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2549)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2100)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1464)
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: Not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
	at io.grpc.internal.ServerImpl.getPort(ServerImpl.java:197)
	at io.micronaut.grpc.server.GrpcEmbeddedServer.getPort(GrpcEmbeddedServer.java:123)
	at io.micronaut.grpc.server.GrpcServerChannel.serverChannel(GrpcServerChannel.java:61)
	at io.micronaut.grpc.server.$GrpcServerChannel$ServerChannel0Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1814)
	... 9 common frames omitted
````

**Comment by graemerocher** [comment]
I am transferring this issue here because there are two bugs at play in core:

1. The `isEagerInit` method is using `hasStereotype` which returns true for a non-singleton `@Bean` method of a `@Factory` . It should be using `hasDeclaredSteretype`. See https://github.com/micronaut-projects/micronaut-core/blob/be1bc41b4ac037dab48a10eeb25ec6df6059fc2f/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java#L2818
2. Micronaut is not excluded beans that requires parameters via `@Parameter` which then fail creation.
