### ISSUE TITLE
Micronaut 2.3.x unnecessarily generating proxies for JUnit tests causing test failures

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4987]
Micronaut is generating proxies for JUnit 5 tests annotated with `@MicronautTest` unnecessarily. The JUnit 5 tests fail as they cannot inject the constructor arguments with the following error:

```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [io.micronaut.context.BeanContext arg0] in constructor [public com.example.PetControllerTest$Intercepted(io.micronaut.context.BeanContext,io.micronaut.context.Qualifier,io.micronaut.aop.Interceptor[])].
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:200)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:74)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
```

### Steps to Reproduce

See attached example and just run `./gradlew test`

### Expected Behaviour

Proxies shouldn't be generated

### Actual Behaviour

They are generated

### Environment Information

micronautVersion=2.3.2

### Example Application

[demo.zip](https://github.com/micronaut-projects/micronaut-core/files/6034202/demo.zip)

**Comment by graemerocher** [comment]
Workaround is to do this in Gradle:

```groovy
test {
    exclude '**/*Test$Intercepted*'
}
```

**Comment by bernd-prager-epam** [comment]
I tried the suggested workaround to no effect. Unfortunately I am still getting ParameterResolutionException. 
:-(
