### ISSUE TITLE
NoClassDefFoundError: io/micronaut/runtime/server/EmbeddedServerInstance when using gRPC in Micronaut 2.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#4989]
An application with gRPC server using Micronaut 2.4.0-SNAPSHOT doesn't start because there is a missing class `io.micronaut.runtime.server.EmbeddedServerInstance`.

In 2.3.x the class `EmbeddedServerInstance` is in `micronaut-runtime` module in the package `io.micronaut.runtime.server`. 
In 2.4.x the class still is in `micronaut-runtime` module but in `io.micronaut.discovery` package.

P.S: This also happens with the Consul test application with a similar error message (class missing `io.micronaut.runtime.server.EmbeddedServerInstance`)

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-grpc-graal`
- `cd micronaut-grpc-graal`
- `git checkout 2.4.x`
- `./gradlew server:run`

### Expected Behaviour

The application should start

### Actual Behaviour

The application doesn't start:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.0-SNAPSHOT)

13:30:08.638 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: io/micronaut/runtime/server/EmbeddedServerInstance
java.lang.NoClassDefFoundError: io/micronaut/runtime/server/EmbeddedServerInstance
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at io.micronaut.grpc.server.GrpcEmbeddedServer.lambda$start$1(GrpcEmbeddedServer.java:174)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.micronaut.grpc.server.GrpcEmbeddedServer.start(GrpcEmbeddedServer.java:162)
        at io.micronaut.grpc.server.GrpcEmbeddedServer.start(GrpcEmbeddedServer.java:60)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:77)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.ClassNotFoundException: io.micronaut.runtime.server.EmbeddedServerInstance
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 22 common frames omitted
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.4.0-SNAPSHOT
- **JDK Version:** 8

**Comment by kengnguyen** [comment]
Hi, i'm use micronaut ver 3.7.1 and discovery-client ver 2.0.1 has this error
2022-11-14 11:46:28.394 [main] ERROR io.micronaut.runtime.Micronaut:338 - Error starting Micronaut server: io/micronaut/runtime/server/EmbeddedServerInstance
java.lang.NoClassDefFoundError: io/micronaut/runtime/server/EmbeddedServerInstance
	at io.micronaut.discovery.consul.registration.ConsulAutoRegistration.register(ConsulAutoRegistration.java:198)
	at io.micronaut.discovery.registration.AutoRegistration.onApplicationEvent(AutoRegistration.java:58)
	at io.micronaut.discovery.registration.AutoRegistration.onApplicationEvent(AutoRegistration.java:38)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
	at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:587)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:581)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:79)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
	at vn.cuckookoo.artw.master.Application.main(Application.java:10)
Caused by: java.lang.ClassNotFoundException: io.micronaut.runtime.server.EmbeddedServerInstance
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 common frames omitted

**Comment by graemerocher** [comment]
you are using an incompatible version. See https://search.maven.org/artifact/io.micronaut/micronaut-bom/3.7.3/pom for which version of `micronaut-discovery-client` is compatible with 3.7.x https://search.maven.org/artifact/io.micronaut/micronaut-bom/3.7.3/pom
