### ISSUE TITLE
Error Compiling Generic Beans 

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#5001]
I am trying to upgrade from `2.2.1` to `2.3.3`. It seems there was a regression introduced in `2.3.0` that is crashing the annotation processor during compilation of a bunch of our beans.

### Steps to Reproduce

1. Check out [the example project](https://github.com/RyanHoldren/micronaut-compilation-problem) I put together.
2. Run `gradle build`

### Expected Behaviour

It should compile.

### Actual Behaviour

An exception is thrown:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at io.micronaut.asm.Type.getObjectType(Type.java:253)
        at io.micronaut.inject.writer.AbstractClassFileWriter.getTypeReference(AbstractClassFileWriter.java:565)
        at io.micronaut.inject.writer.AbstractClassFileWriter.pushTypeArgumentElements(AbstractClassFileWriter.java:196)
        at io.micronaut.inject.writer.AbstractClassFileWriter.buildArgumentWithGenerics(AbstractClassFileWriter.java:288)
        at io.micronaut.inject.writer.AbstractClassFileWriter.pushTypeArgumentElements(AbstractClassFileWriter.java:199)
        at io.micronaut.inject.writer.AbstractClassFileWriter.pushTypeArgumentElements(AbstractClassFileWriter.java:167)
        at io.micronaut.inject.writer.BeanDefinitionWriter.lambda$finalizeTypeArguments$4(BeanDefinitionWriter.java:619)
        at io.micronaut.inject.writer.AbstractClassFileWriter.pushStoreInArray(AbstractClassFileWriter.java:817)
        at io.micronaut.inject.writer.BeanDefinitionWriter.finalizeTypeArguments(BeanDefinitionWriter.java:618)
        at io.micronaut.inject.writer.BeanDefinitionWriter.visitBeanDefinitionEnd(BeanDefinitionWriter.java:562)
        at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.processBeanDefinitions(BeanDefinitionInjectProcessor.java:251)
        at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.lambda$null$6(BeanDefinitionInjectProcessor.java:209)
        at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.lambda$process$7(BeanDefinitionInjectProcessor.java:206)
        at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.process(BeanDefinitionInjectProcessor.java:200)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.DynamicProcessor.process(DynamicProcessor.java:52)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1025)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:940)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1269)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1383)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1261)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:935)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
```

### Environment Information

- **Operating System**: Amazon Linux 2
- **Micronaut Version:** `2.3.0`, `2.3.1`, `2.3.2` or `2.3.3`
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

**Comment by jameskleeh** [comment]
Thanks for the report!

**Comment by RyanHoldren** [comment]
No, thank _you_ for the fix :)
