### ISSUE TITLE
`BeansIntrospectionModule` breaks serialization and deserialization for `@JsonAnySetter/Getter`

### ISSUE THREAD

**Issue by vlypskyi** [micronaut-projects/micronaut-core#5002]
### Task List

- [ X] Steps to reproduce provided
- [ X] Stacktrace (if present) provided
- [ X] Example that reproduces the problem uploaded to Github
- [ X] Full description of the issue provided (see below)

### Steps to Reproduce

* Create a new project from https://micronaut.io/launch
* Add this test:
```
package com.example

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.KotlinModule
import com.fasterxml.jackson.module.kotlin.readValue
import io.micronaut.core.annotation.Introspected
import io.micronaut.jackson.modules.BeanIntrospectionModule
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

@Introspected
data class Body(
    @JsonProperty("foo_id")
    val id: Long,

    @get:JsonAnyGetter
    @JsonAnySetter
    val properties: MutableMap<String, Any> = mutableMapOf()
)

@Introspected
data class Wrapper(
    @JsonProperty("body")
    val body: Body
)

class MapSerializationTest {

    @Test
    fun testSerialize() {
        val mapper = ObjectMapper().registerModule(KotlinModule.Builder().build())
        val actual = mapper.writeValueAsString(Wrapper(Body(123, mutableMapOf("foo" to "bar"))))
        val expected = """
            {"body":{"foo_id":123,"foo":"bar"}}
        """.trimIndent()
        Assertions.assertEquals(expected, actual)
    }

    @Test
    fun testSerializeIntrospected() {
        val mapper = ObjectMapper()
            .registerModule(KotlinModule.Builder().build())
            .registerModule(BeanIntrospectionModule())
        val actual = mapper.writeValueAsString(Wrapper(Body(123, mutableMapOf("foo" to "bar"))))
        val expected = """
            {"body":{"foo_id":123,"foo":"bar"}}
        """.trimIndent()
        Assertions.assertEquals(expected, actual)
    }

    @Test
    fun testDeserialize() {
        val mapper = ObjectMapper().registerModule(KotlinModule.Builder().build())
        val json = """
            {"body":{"foo_id":123,"foo":"bar"}}
        """.trimIndent()
        val actual: Wrapper = mapper.readValue(json)
        val expected = Wrapper(Body(123,  mutableMapOf("foo" to "bar")))
        Assertions.assertEquals(expected, actual)
    }

    @Test
    fun testDeserializeIntrospected() {
        val mapper = ObjectMapper()
            .registerModule(KotlinModule.Builder().build())
            .registerModule(BeanIntrospectionModule())
        val json = """
            {"body":{"foo_id":123,"foo":"bar"}}
        """.trimIndent()
        val actual: Wrapper = mapper.readValue(json)
        val expected = Wrapper(Body(123, mutableMapOf("foo" to "bar")))
        Assertions.assertEquals(expected, actual)
    }

}
```

* `testSerializeIntrospected` breaks with 
```
Expected :{"body":{"foo_id":123,"foo":"bar"}}
Actual   :{"body":{"foo_id":123}}
```

* `testDeserializeIntrospected` breaks with
```
Missing required creator property 'properties' (index 1)
 at [Source: (String)"{"body":{"foo_id":123,"foo":"bar"}}"; line: 1, column: 34] (through reference chain: com.example.Wrapper["body"])
com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'properties' (index 1)
 at [Source: (String)"{"body":{"foo_id":123,"foo":"bar"}}"; line: 1, column: 34] (through reference chain: com.example.Wrapper["body"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer._findMissing(PropertyValueBuffer.java:194)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.getParameters(PropertyValueBuffer.java:160)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
	at com.example.MapSerializationTest.testDeserializeIntrospected(MapSerializationTest.kt:83)
```

### Expected Behaviour

If regular jackson works, only adding BeanIntrospectionModule should also work.

### Actual Behaviour

Normal reflection still works, while BeanIntrospectionModule breaks deserialization.

### Environment Information

- **Operating System**: macOS Catalina 10.15.7 (19H524) Darwin 19.6.0
- **Micronaut Version:** 2.3.3
- **JDK Version:** 1.8

### Example Application

https://github.com/vlypskyi/micronaut-introspection-bug

**Comment by harissecic** [comment]
Somehow my AnySetter is working fin for me. So far I traced problems with getter up to https://github.com/micronaut-projects/micronaut-core/blob/3f33453ec8b10a3bbcdd1af71ca4189cb923d87b/runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java#L259. I can see that it ignores _anyGetter member of the builder passed in and only works on properties in the else statement. I don't know what would be the right approach to treat _anyGetter properly but "poperties" part will not contain anything that was annotated with ```@JsonAnyGetter" and so will this builder skip it. Also name of the anyGetter will be of the method itself for example "getExtraProperties()".

But to note I'm using Java 16 not Kotlin so it might be different

**Comment by safarmer** [comment]
I ran into this issue when using Java 16 records with @JsonAnyGetter/@JsonAnySetter. PR sent for review with fix to make sure the AnyGetterWriter is preserved. It looks like the field is (correctly?) being ignored in the properties already.

**Comment by harissecic** [comment]
> I ran into this issue when using Java 16 records with @JsonAnyGetter/@JsonAnySetter. PR sent for review with fix to make sure the AnyGetterWriter is preserved. It looks like the field is (correctly?) being ignored in the properties already.

This is the line I was talking about. However given that the first run is by Jackson without Micronaut module I guess it might be relying on reflection thus didn't want to provide such a pull request. But maybe I'm wrong and this is it?

**Comment by safarmer** [comment]
Good question. Hopefully it is easy enough for someone to answer on the PR review.
