### ISSUE TITLE
Health endpoint, empty reply from server when underlying resource is not available

### ISSUE THREAD

**Issue by hbxu** [micronaut-projects/micronaut-core#5025]
Health Check endpoints impacted by unavailability of Database.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Start Database (Oracle XE)
2. Check health endpoint (curl http://localhost:8080/health)
3. Stop Database
4. Check health endpoint (curl http://localhost:8080/health)

### Expected Behaviour

Expected result (pretty-printed):

```
$ curl http://localhost:8080/health -i
HTTP/1.1 200 OK
...
{
    "name": "testcase-health",
    "status": "UP",
    "details": {
        "jdbc": {
            "name": "testcase-health",
            "status": "DOWN",
            "details": {
                "jdbc:oracle:thin:@//localhost:1521/XEPDB1": {
                    "name": "testcase-health",
                    "status": "UP",
                    "details": {
                        "database": "Oracle",
                        "version": "..."
                    }
                }
            }
        },
        "compositeDiscoveryClient()": {
            "name": "testcase-health",
            "status": "UP"
        },
        "service": {
            "name": "testcase-health",
            "status": "UP"
        },
        "diskSpace": {
            "name": "testcase-health",
            "status": "UP",
            "details": {
                "total": 512108785664,
                "free": 464029450240,
                "threshold": 10485760
            }
        }
    }
}
```

### Actual Behaviour

```
$ curl http://localhost:8080/health -i
curl: (52) Empty reply from server
```

stack trace:
```
...
18:04:58.037 [io-executor-thread-1] WARN  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection oracle.jdbc.driver.T4CConnection@29e3ac79 (IO-fout: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
18:05:28.029 [io-executor-thread-1] ERROR i.m.m.health.indicator.HealthResult - Health indicator [jdbc:oracle:thin:@//localhost:1521/XEPDB1] reported exception: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:91)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.sql.SQLRecoverableException: IO-fout: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:862)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	... 4 common frames omitted
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:571)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:548)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:682)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:309)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1604)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:595)
	... 15 common frames omitted
Caused by: java.io.IOException: Connection refused: connect, socket connect lapse 2003 ms. /0:0:0:0:0:0:0:1 1521 30000 1 true
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:233)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:174)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:510)
	... 20 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:784)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:224)
	at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:99)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:77)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:192)
	... 22 common frames omitted
...
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.3.3
- **JDK Version:** OpenJDK 15

### Example Application

- https://github.com/hbxu/testcase-health

**Comment by jameskleeh** [comment]
I can't reproduce that

```
~ $ curl localhost:8080/health
{"name":"testcase-health","status":"DOWN","details":{"jdbc":{"name":"testcase-health","status":"DOWN","details":{"jdbc:mysql://localhost:3306/db":{"name":"testcase-health","status":"DOWN","details":{"error":"java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30006ms."}}}},"compositeDiscoveryClient()":{"name":"testcase-health","status":"UP"},"diskSpace":{"name":"testcase-health","status":"UP","details":{"total":1000240963584,"free":712453189632,"threshold":10485760}},"service":{"name":"testcase-health","status":"UP"}}}~ $ 
```

Note that I used mysql since I have a database lying around, but it should behave the same

**Comment by jameskleeh** [comment]
Note that if the connection timeouts for the oracle driver are very long, you could hit the timeout limit for curl. You should be able to configure it to not wait as long

**Comment by hbxu** [comment]
I tested with mysql, also the same behavior (/health is not available, when database is gone).


<details><summary>Stacktrace</summary>
<p>

```
10:49:47.297 [io-executor-thread-1] ERROR i.m.m.health.indicator.HealthResult - Health indicator [jdbc:mysql://localhost:3306/test?user=test&password=test] reported exception: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:91)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	... 4 common frames omitted
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	... 14 common frames omitted
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 17 common frames omitted
```

</p>
</details>

I will run the tests on a different machine and come back with the results.

**Comment by jameskleeh** [comment]
@hbxu I see the same stacktrace, but I get a response in curl. I couldn't reproduce `curl: (52) Empty reply from server`

**Comment by hbxu** [comment]
I can confirm that on my other machine, I am not able reproduce it either.

Thanks for the help.

<details><summary>curl 1</summary>
<p>

$ curl localhost:8080/health -i
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   584  100   584    0     0     19      0  0:00:30  0:00:30 --:--:--   164HTTP/1.1 503 Service Unavailable
Date: Wed, 3 Mar 2021 19:09:51 GMT
Content-Type: application/json
content-length: 584
connection: close

{"name":"testcase-health","status":"DOWN","details":{"jdbc":{"name":"testcase-health","status":"DOWN","details":{"jdbc:oracle:thin:@localhost:1521:xe":{"name":"testcase-health","status":"DOWN","details":{"error":"java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms."}}}},"compositeDiscoveryClient()":{"name":"testcase-health","status":"UP"},"service":{"name":"testcase-health","status":"UP"},"diskSpace":{"name":"testcase-health","status":"UP","details":{"total":254834823168,"free":9019260928,"threshold":10485760}}}}

</p>
</details>

<details><summary>curl 2</summary>
<p>

$ curl localhost:8080/health -i
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   584  100   584    0     0     19      0  0:00:30  0:00:30 --:--:--   161HTTP/1.1 503 Service Unavailable
Date: Wed, 3 Mar 2021 19:10:30 GMT
Content-Type: application/json
content-length: 584
connection: close

{"name":"testcase-health","status":"DOWN","details":{"jdbc":{"name":"testcase-health","status":"DOWN","details":{"jdbc:oracle:thin:@localhost:1521:xe":{"name":"testcase-health","status":"DOWN","details":{"error":"java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms."}}}},"compositeDiscoveryClient()":{"name":"testcase-health","status":"UP"},"service":{"name":"testcase-health","status":"UP"},"diskSpace":{"name":"testcase-health","status":"UP","details":{"total":254834823168,"free":9018843136,"threshold":10485760}}}}

</p>
</details>
