### ISSUE TITLE
mn create-federation fails with NPE

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#509]
```
java.lang.NullPointerException
	at io.micronaut.cli.profile.commands.AbstractCreateCommand$_addDependentFeatures_closure17.doCall(AbstractCreateCommand.groovy:571)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.addDependentFeatures(AbstractCreateCommand.groovy:571)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.populateFeatures(AbstractCreateCommand.groovy:544)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.evaluateFeatures(AbstractCreateCommand.groovy:477)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.handle(AbstractCreateCommand.groovy:272)
	at io.micronaut.cli.profile.commands.CreateFederationCommand.handle(CreateFederationCommand.groovy:92)
	at io.micronaut.cli.MicronautCli.executeCommand(MicronautCli.groovy:351)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:234)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:175)
| Error Error occurred running Micronaut CLI: null

```

**Comment by rverma-nikiai** [comment]
@jameskleeh Tested with current master, facing new issue as `| Error Command [mn] error: No signature of method: io.micronaut.cli.profile.commands.CreateFederationCommand.appendToYmlSubDocument() is applicable for argument types: (File, String) values: [/Users/rverma/dev/demo/out/production/resources/application.yml, ...]`
