### ISSUE TITLE
Injecting @RequestAttribute parameter in controller doesn't work when wrapped in another annotation

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-core#5101]
### Steps to Reproduce

I've prepared a demo project. Just run all tests in `com.example.DemoTest` or start an application and do a GET request to `/ok` or `/nok`.

### Expected Behaviour

I have a filter that injects string value as a request attribute:
```
    @Override
    protected Publisher<MutableHttpResponse<?>> doFilterOnce(HttpRequest<?> request, ServerFilterChain chain) {
        request.getAttributes().put(CUSTOM_ATTRIBUTE, CUSTOM_ATTRIBUTE_VALUE);          // <---- HERE
        return chain.proceed(request);
    }
```

I inject this attribute as a parameter:
```
    @Get("/ok")
    public String ok(@RequestAttribute(DemoFilter.CUSTOM_ATTRIBUTE) String attribute) {             // <---- HERE; this works - we can get value that was injected inside DemoFilter
        return attribute;
    }
```

Then for simplicity I have created an annotation that wraps @RequestAttribute:
```
@RequestAttribute(DemoFilter.CUSTOM_ATTRIBUTE)               // <---- HERE
public @interface WrappingAnnotation {
}
```

I would like to use it in controller:
```
    @Get("/nok")
    public String nok(@WrappingAnnotation String attribute) { //this annotation should work but it doesn't. It only wraps @RequestAttribute(DemoFilter.CUSTOM_ATTRIBUTE)
        return attribute;
    }
```

Note: this was working on previous versions of Micronaut. I can confirm it worked at least on 2.1.2.

### Actual Behaviour

I get 400 Bad Request with the following message:
`{"message":"Required WrappingAnnotation [attribute] not specified","path":"/attribute","_links":{"self":{"href":"/nok","templated":false}}}`

I can see stacktrace when running tests:

```
io.micronaut.http.client.exceptions.HttpClientResponseException: Required WrappingAnnotation [attribute] not specified

	at io.micronaut.http.client.netty.DefaultHttpClient$12.channelReadInstrumented(DefaultHttpClient.java:2161)
	at io.micronaut.http.client.netty.DefaultHttpClient$12.channelReadInstrumented(DefaultHttpClient.java:2076)
	at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:2776)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:193)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: Windows 10 64bit
- **Micronaut Version:** 2.4.0 (also tested on 2.3.3)
- **JDK Version:** adopt openjdk 11.0.8

### Example Application

[See here](https://github.com/lehotskysamuel/demo/)

Thank you for having a look at this.

**Comment by graemerocher** [comment]
Triaged as Bug/awaiting validation. The original reproducer is detailed but targets 2.1.2. Current binder selection resolves a binder from the Bindable stereotype and then looks up the resolved annotation type; a composed RequestAttribute annotation may still resolve to the wrapper rather than RequestAttribute itself. Please retest on current 5.2.x with direct and wrapper annotations. Suggested fix: resolve composed binders through the bindable stereotype while preserving alias values, and add a direct-vs-composed regression test.
