### ISSUE TITLE
GORM CLI app fails with `No GORM implementations configured`

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#511]
A CLI app with feature `hibernate-gorm` fails with `java.lang.IllegalStateException: No GORM implementations configured. Ensure GORM has been initialized correctly` when run.  
Same configuration as non CLI app works.

### Steps to Reproduce

1. create cli app with `mn create-cli-app --lang groovy --features hibernate-gorm test-cli`
2. create a domain class annotated with `Entity`
3. annotate the run method in `TestCliCommand` with `grails.gorm.transactions.Transactional`
4. `./gradlew assemble && java -jar build/libs/test-cli-0.1-all.jar -v`

### Expected Behaviour

`Hi!` is displayed

### Actual Behaviour

I get an exception:  
```java
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (test.cli.$TestCliCommandDefinition$Intercepted@4816c290): org.springframework.transaction.TransactionSystemException: No transaction manager configured
        at picocli.CommandLine.execute(CommandLine.java:912)
	at picocli.CommandLine.access$700(CommandLine.java:104)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1081)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1049)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:957)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1240)
	at picocli.CommandLine.run(CommandLine.java:1793)
	at picocli.CommandLine.run(CommandLine.java:1716)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:129)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:107)
	at io.micronaut.configuration.picocli.PicocliRunner$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at test.cli.TestCliCommand.main(TestCliCommand.groovy:19)
Caused by: org.springframework.transaction.TransactionSystemException: No transaction manager configured
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.resolveTransactionManager(TransactionInterceptor.java:130)
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.intercept(TransactionInterceptor.java:67)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
	at test.cli.$TestCliCommandDefinition$Intercepted.run(Unknown Source)
	at picocli.CommandLine.execute(CommandLine.java:904)
	... 14 more
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_171

### Example Application

I will provide an example if required.

**Comment by jeffbrown** [comment]
Sample project is available at https://github.com/jeffbrown/issue511.

**Comment by jameskleeh** [comment]
Also FYI this can be accomplished with `PicocliRunner.run(Issue511Command.class, ApplicationContext.run(Environment.CLI), args)` if the command is compiled statically

**Comment by jameskleeh** [comment]
I'll also go ahead and update the PicoliRunner to correctly pass through the main class so this will no longer be an issue.
