### ISSUE TITLE
Micronaut Server Error - No request state present when using HTTPS on minimal setup

### ISSUE THREAD

**Issue by galzetta** [micronaut-projects/micronaut-core#5128]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Set up a minimal micronaut project with HTTPS enabled using self signed certificates (so `micronaut.ssl.enabled=true` and `micronaut.ssl.buildSelfSigned=true` as described in the official documentation). 
2. Launch the application with `./mvnw mn:run`
3. Open a browser and go to `https://localhost:8443/verify`

### Expected Behaviour

The browser shows "Working!" and there is no error in the application logs

### Actual Behaviour

The browser shows "Working!" but the application logs are filled with the following error:

```
14:49:12.204 [default-nioEventLoopGroup-1-7] ERROR i.m.h.s.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:167)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:729)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:684)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:499)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:475)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        ... 17 common frames omitted

```

Not clear whether this error has any possible impact on the controller or if it is just clutter in the logs (that maybe would go away if we use a properly signed certificate and a truststore? But I thought micronaut self-built self-signed certificate would be trusted by the server it self?)

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.4.0 (I tried 2.1.2, 2.2.3 and 2.3.3 and all show this problem)
- **JDK Version:** 14

### Example Application

- Minimal example here:  https://github.com/galzetta/debug-micronaut-https

Note that initially I was trying to use Jetty and had some other issues (like `micronaut.server.dualProtocol=false` not being respected and HTTPS handshake failing completely), the latest commit only uses netty.

**Comment by brianwyka** [comment]
Relates to #3244.  I'm getting this again as well in latest Micronaut.

```
2021-03-17 08:34:40.129 CDT ERROR   - [default-nioEventLoopGroup-1-2] [io.micronaut.http.server.netty.RoutingInBoundHandler] Micronaut Server Error - No request state present. Cause: Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by galzetta** [comment]
I attach the log produced with `-Djavax.net.debug=all` for a single request:

[request.log](https://github.com/micronaut-projects/micronaut-core/files/6169538/request.log)

Everything looks fine until:

```
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.872 CET|SSLEngineInputRecord.java:177|Raw read (
  0000: 14 03 03 00 01 01                                  ......
)
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.872 CET|SSLEngineInputRecord.java:214|READ: TLSv1.2 change_cipher_spec, length = 1
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.872 CET|ChangeCipherSpec.java:246|Consuming ChangeCipherSpec message
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.873 CET|SSLEngineInputRecord.java:177|Raw read (
  0000: 17 03 03 00 13 92 8C 1C   26 C6 20 15 13 E3 64 FB  ........&. ...d.
  0010: 88 00 A4 E0 0F 20 B6 FE                            ..... ..
)
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.873 CET|SSLEngineInputRecord.java:214|READ: TLSv1.2 application_data, length = 19
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.873 CET|SSLCipher.java:1958|Plaintext after DECRYPTION (
  0000: 02 2E                                              ..
)
javax.net.ssl|DEBUG|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.873 CET|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "certificate_unknown"
}
)
javax.net.ssl|ERROR|1B|default-nioEventLoopGroup-1-4|2021-03-19 09:02:47.874 CET|TransportContext.java:317|Fatal (CERTIFICATE_UNKNOWN): Received fatal alert: certificate_unknown (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
```

Maybe the self-signed certificate that micronaut is generating is broken and for some reason the server is breaking for this? Although I would expect only the *client* to whine about the self-signed certificate, here it looks like the server is the culprit (or maybe for some reason the server thinks it has to do mTLS and is failing to find the client certificate?)
