### ISSUE TITLE
NullPointerException when trying to create Federation

### ISSUE THREAD

**Issue by thiagolocatelli** [micronaut-projects/micronaut-core#513]
I keep getting an NPE while trying to create a federation on my laptop.

JDK version:
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Command:
```
mn create-federation my-federation --services users,inventory,billing --build maven --features=java,junit --stacktrace --verbose
```

Stacktrace:
```
| Generating Java project.....
| Error Error occurred running Micronaut CLI: null
java.lang.NullPointerException
	at io.micronaut.cli.profile.commands.AbstractCreateCommand$_addDependentFeatures_closure17.doCall(AbstractCreateCommand.groovy:571)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:51)
	at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:53)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4891)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4763)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4735)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.addDependentFeatures(AbstractCreateCommand.groovy:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:225)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.populateFeatures(AbstractCreateCommand.groovy:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:225)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.evaluateFeatures(AbstractCreateCommand.groovy:477)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.handle(AbstractCreateCommand.groovy:272)
	at io.micronaut.cli.profile.commands.CreateFederationCommand.handle(CreateFederationCommand.groovy:92)
	at io.micronaut.cli.MicronautCli.executeCommand(MicronautCli.groovy:351)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:234)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:175)
| Error Error occurred running Micronaut CLI: null
```

The three services' folders have been created, since I cant get past this issue, I am not sure if the CLI will be also creating files in the root folder of the federation:

```
my-federation/
├── billing
│   ├── Dockerfile
│   ├── micronaut-cli.yml
│   ├── pom.xml
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── billing
│       │   │       └── Application.java
│       │   └── resources
│       │       ├── application.yml
│       │       └── logback.xml
│       └── test
│           └── java
│               └── billing
├── inventory
│   ├── Dockerfile
│   ├── micronaut-cli.yml
│   ├── pom.xml
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── inventory
│       │   │       └── Application.java
│       │   └── resources
│       │       ├── application.yml
│       │       └── logback.xml
│       └── test
│           └── java
│               └── inventory
└── users
    ├── Dockerfile
    ├── micronaut-cli.yml
    ├── pom.xml
    └── src
        ├── main
        │   ├── java
        │   │   └── users
        │   │       └── Application.java
        │   └── resources
        │       ├── application.yml
        │       └── logback.xml
        └── test
            └── java
                └── users

27 directories, 18 files
```

### Environment Information
- **Operating System**: macOS High Sierra version: 10.13.4 (17E202)
- **Micronaut Version:** 1.0.0.M4
- **JDK Version**: 1.8.0_161

**Comment by thiagolocatelli** [comment]
Just noticed there is already an open issue related to this problem.

Related to issue #509.
