### ISSUE TITLE
Error with `@Introspected` POJOs in multi-project builds with GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5164]
We have a test application for a multi-project build with the following structure:

- core module: It's a java-library that has a POJO annotated with `@Introspected` and some Jackson annotations.
- app: A Micronaut application that exposes that POJO in a controller

This application has been working properly for a long time and it still works for Micronaut 2.3.

Now with Micronaut 2.4 that app is failing with a `NoClassDefFoundError` because somehow the POJO in the 
core module is not included in GraalVM. This worked before with some 2.4.0-snapshot versions but I think a last minute merge before 2.4.0 broke this.

I've been having some issues trying to reproduce it locally but it fails all the time when running it on CI. This is [the log](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1120361929) from the last execution some hours ago.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-introspected-graal`
- `cd micronaut-introspected-graal`
- `git checkout 2.4.x`
- `sdk use java 21.0.0.2.r8-grl`
- `./build-native-image.sh`
- `./app/build/native-image/introspected`

### Expected Behaviour

The application should start and executing `curl localhost:8080/books` should also work.

### Actual Behaviour

The application fails with:

```
11:51:15.792 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud]
11:51:15.796 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]
Message: example.micronaut.pojo.Book
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,BeanProvider ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,EventLoopGroupRegistry eventLoopGroupRegistry,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver,ChannelOptionFactory channelOptionFactory,ErrorResponseProcessor errorResponseProcessor)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]
Message: example.micronaut.pojo.Book
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,BeanProvider ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,EventLoopGroupRegistry eventLoopGroupRegistry,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver,ChannelOptionFactory channelOptionFactory,ErrorResponseProcessor errorResponseProcessor)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1012)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:752)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at micronaut.example.Application.main(Application.java:8)
Caused by: java.lang.NoClassDefFoundError: example.micronaut.pojo.Book
	at micronaut.example.$BookControllerDefinition$$exec1.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinition.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinition.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinitionClass.load(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:62)
	at io.micronaut.context.DefaultBeanContext.lambda$getBeanDefinitions$13(DefaultBeanContext.java:1162)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.micronaut.context.DefaultBeanContext.getBeanDefinitions(DefaultBeanContext.java:1165)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:64)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:44)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2000)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3091)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:2994)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1059)
	at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1225)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1172)
	at io.micronaut.web.router.$DefaultRouterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	... 19 common frames omitted
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.4.2-SNAPSHOT (fails with 2.4.0 and 2.4.1 too)
- **JDK Version:** 8 & 11

**Comment by graemerocher** [comment]
You mention a last minute merge. In which case can you track down the commit that caused the problem

**Comment by ilopmar** [comment]
I spent some time on this and I wasn't able to find the commit that broke this :disappointed:

**Comment by ilopmar** [comment]
So, because of this, the GraalVM test app for this is still failing in CI since then. And now it also fails in the new branch for 2.5.x

**Comment by graemerocher** [comment]
the build currently fails with

```
A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:runtimeClasspath'.
   > Could not find micronaut-runtime-2.4.3-SNAPSHOT.jar (io.micronaut:micronaut-runtime:2.4.3-SNAPSHOT).
     Searched in the following locations:
         https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-runtime/2.4.3-SNAPSHOT/micronaut-runtime-2.4.3-SNAPSHOT.jar
   > Could not find micronaut-aop-2.4.3-SNAPSHOT.jar (io.micronaut:micronaut-aop:2.4.3-SNAPSHOT).
     Searched in the following locations:
         https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-aop/2.4.3-SNAPSHOT/micronaut-aop-2.4.3-SNAPSHOT.jar
   > Could not find micronaut-inject-2.4.3-SNAPSHOT.jar (io.micronaut:micronaut-inject:2.4.3-SNAPSHOT).
     Searched in the following locations:
         https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-inject/2.4.3-SNAPSHOT/micronaut-inject-2.4.3-SNAPSHOT.jar
   > Could not find micronaut-core-2.4.3-SNAPSHOT.jar (io.micronaut:micronaut-core:2.4.3-SNAPSHOT).
     Searched in the following locations:
         https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-core/2.4.3-SNAPSHOT/micronaut-core-2.4.3-SNAPSHOT.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by ilopmar** [comment]
That error seems a glitch with our snapshot repository. I've tried now (removing my local artifacts) and the build has been able to download all of them.
Can you retry?

**Comment by graemerocher** [comment]
seems the issue is resolved by adding `annotationProcessor "io.micronaut:micronaut-graal"` to the `core` project

For some reason Graal requires reflective loading

**Comment by ilopmar** [comment]
That was the first thing I tried and it didn't work for me. I've tried it again and it works now. Maybe we've fixed something in the gradle plugin :confused: ...

Is this the real fix or just a workaround? I'm asking because I think I created this test project to specifically test this use case and check that the dependency wasn't necessary on the `core` project.
Besides that, this worked in 2.3.x

**Comment by graemerocher** [comment]
it seems a bug in native image, worth an issue report to graalvm that I can escalate

**Comment by ilopmar** [comment]
Done: https://github.com/oracle/graal/issues/3347

I've tried the workaround and it still fails on CI :-(

**Comment by ilopmar** [comment]
Just to confirm that the workaround has failing in tonight CI execution.

**Comment by graemerocher** [comment]
it must not be generating the reflect config in that case

**Comment by ilopmar** [comment]
According to the log, it is. See https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1181379789#L59 for the 2.4.x - graalvm-21.0 execution:

```
> Task :core:compileJava
Note: Writing reflect-config.json file to destination: META-INF/native-image/example.micronaut/pojo/reflect-config.json
> Task :app:compileJava
Note: Writing resource-config.json file to destination: META-INF/native-image/micronaut.example/app/resource-config.json
Note: Creating bean classes for 1 type elements
> Task :app:processResources
...
```

**Comment by ilopmar** [comment]
And the output is the same for the other cases and java versions...

**Comment by ilopmar** [comment]
So, it turns out the culprit is our Gradle plugin. The `core.jar` file (in which Book class is supposed to be) is not being generated so it is not being included in the native image. 

See https://github.com/oracle/graal/issues/3347#issuecomment-824285147

**Comment by ilopmar** [comment]
I've been digging a little bit and I've found that everything works with plugin 1.4.0. Take a look at the output when creating the native image. The task `core:jar` is executed:


```
$ ./gradlew nativeImage
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> Task :app:processResources
> Task :core:compileJava
> Task :core:processResources NO-SOURCE
> Task :core:classes
> Task :core:jar <---- The core.jar is created

> Task :app:compileJava
Note: Writing resource-config.json file to destination: META-INF/native-image/micronaut.example/app/resource-config.json
Note: Creating bean classes for 1 type elements

> Task :app:classes
...
```

But starting in `1.4.1` the task is not executed anymore:

```
> Task :app:processResources
> Task :core:compileJava

> Task :app:compileJava
Note: Writing resource-config.json file to destination: META-INF/native-image/micronaut.example/app/resource-config.json
Note: Creating bean classes for 1 type elements
> Task :app:classes
...
```

The only fix included in 1.4.1 is this PR: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/155 which broke it.
