### ISSUE TITLE
Jackson javax.activation.MimeType deserialization error on Micronaut 2.4.x

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#5169]
While upgrading to Micronaut 2.4 if stumbled over an error while deserializing JSON string to ` javax.activation.MimeType`. 

The following test wraps the problem up and is part of the example repostories mentioned below.

```groovy
@MicronautTest
class DemoSpec extends Specification {

    @Inject
    ObjectMapper mapper

    void "Deserialize javax.activation.MimeType"() {

        given:
        String json = ' "application/json" '

        when:
        mapper.readValue(json, MimeType)

        then:
        noExceptionThrown()
    }
}
``` 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone Git Repo at https://github.com/saw303/micronaut-2.4-jackson-problem. The repo is configured to run on Micronaut 2.4
2. Run the test. This test fails https://github.com/saw303/micronaut-2.4-jackson-problem/blob/main/src/test/groovy/com/example/DemoSpec.groovy#L25
3. Goto the `gradle.properties` and set `micronautVersion=2.3.4`
4. Rerun the test and it will be green

### Expected Behaviour

Jackson should map the string to a MimeType without any error.

### Actual Behaviour

Jackson fails with this error:

```java
Expected no exception to be thrown, but got 'com.fasterxml.jackson.databind.exc.MismatchedInputException'
Expected no exception to be thrown, but got 'com.fasterxml.jackson.databind.exc.MismatchedInputException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at com.example.DemoSpec.Deserialize javax.activation.MimeType(DemoSpec.groovy:34)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `javax.activation.MimeType` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('application/json')
 at [Source: (String)" "application/json" "; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.example.DemoSpec.Deserialize javax.activation.MimeType(DemoSpec.groovy:31)
```

### Environment Information

- **Operating System**: macOS BigSur
- **Micronaut Version:** 2.4.1
- **JDK Version:** 15

### Example Application

- https://github.com/saw303/micronaut-2.4-jackson-problem

**Comment by jameskleeh** [comment]
@saw303 I don't think this has anything to do with Micronaut. `new ObjectMapper().readValue(json, MimeType)` fails with the same exception.

**Comment by saw303** [comment]
@jameskleeh so you mean this is probably an issue caused by the fact that Micronaut 2.4.x upgraded  Jackson `2.11.2` to `2.12.2`? If yes, please close this ticket and I will investigate further

**Comment by jameskleeh** [comment]
@saw303 That is the only thing that would make sense to me. If you discover that isn't the case just leave a message here and I'll reopen

**Comment by saw303** [comment]
@jameskleeh excellent. Meanwhile I was able to work it around using a dedicated custom deserializer.

```java
@Singleton
public class MimeTypeDeserializer extends StdDeserializer<MimeType> {


    protected MimeTypeDeserializer() {
        super(MimeType.class);
    }

    @Override
    public MimeType deserialize(JsonParser p, DeserializationContext ctxt) throws IOException, JsonProcessingException {
        try {
            return new MimeType(p.getValueAsString());
        } catch (MimeTypeParseException e) {
            throw new RuntimeException(e);
        }
    }
}
```
