### ISSUE TITLE
Datasource is swallowing initialisation exceptions

### ISSUE THREAD

**Issue by ikovalyov** [micronaut-projects/micronaut-core#5191]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Use datasource onfiguration with some required fields missed

The generated code for datasource looks like 

```
// $FF: synthetic class
class $DatasourceFactory$DataSource0Definition extends AbstractBeanDefinition<DataSource> implements BeanFactory<DataSource> {
    public DataSource build(BeanResolutionContext var1, BeanContext var2, BeanDefinition<DataSource> var3) {
        Object var4 = ((DefaultBeanContext)var2).getBean(var1, DatasourceFactory.class);
        DatasourceConfiguration var5 = null;

        try {
            var5 = (DatasourceConfiguration)super.getBeanForConstructorArgument(var1, var2, 0);
        } catch (BeanContextException var7) {
            return null;
        }

        DataSource var6 = ((DatasourceFactory)var4).dataSource(var5);
        var6 = (DataSource)this.injectBean(var1, var2, var6);
        return var6;
    }
```

If there are any issues with bean instantiation they are not logged. Exception should be logged to the console to make it easier to debug.

### Expected Behaviour

Error info is printed to the console

### Actual Behaviour

Only this info is printed:

```
Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Bean Factory [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] returned null
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Bean Factory [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] returned null
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1565)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:219)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2857)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
	at com.showpad.content.AppIntegrationTest$1$1.invoke(AppIntegrationTest.kt:39)
	at com.showpad.content.AppIntegrationTest$1$1.invoke(AppIntegrationTest.kt:24)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt$createSuite$1.invoke(specificationStyle.kt:88)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt$createSuite$1.invoke(specificationStyle.kt)
	at org.spekframework.spek2.runtime.Collector.group(Collectors.kt:91)
	at org.spekframework.spek2.dsl.GroupBody$DefaultImpls.group$default(dsl.kt:24)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.createSuite(specificationStyle.kt:87)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.describe(specificationStyle.kt:77)
	at org.spekframework.spek2.style.specification.SpecificationStyleKt.describe$default(specificationStyle.kt:76)
	at com.showpad.content.AppIntegrationTest$1.invoke(AppIntegrationTest.kt:25)
	at com.showpad.content.AppIntegrationTest$1.invoke(AppIntegrationTest.kt:24)
	at org.spekframework.spek2.runtime.SpekRuntime.resolveSpec(SpekRuntime.kt:90)
	at org.spekframework.spek2.runtime.SpekRuntime.access$resolveSpec(SpekRuntime.kt:18)
	at org.spekframework.spek2.runtime.SpekRuntime$filterScopes$$inlined$forEach$lambda$1.invokeSuspend(SpekRuntime.kt:27)
	at org.spekframework.spek2.runtime.SpekRuntime$filterScopes$$inlined$forEach$lambda$1.invoke(SpekRuntime.kt)
	at org.spekframework.spek2.runtime.TaskRunner$runTask$1$1.invokeSuspend(executors.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.spekframework.spek2.runtime.TaskRunner$runTask$1.run(executors.kt:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]

Message: Bean Factory [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] returned null
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1952)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2249)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1559)
	... 34 more
```

### Environment Information

- **Operating System**: Mac and Ubuntu
- **Micronaut Version:** `"io.micronaut.configuration:micronaut-jdbc-hikari:2.2.6"`, `mavenBom("io.micronaut:micronaut-bom:2.4.0")`
- **JDK Version:** 
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

**Comment by jameskleeh** [comment]
You are using the incorrect version of `micronaut-jdbc-hikari`. You should use our BOM so the versions of our libraries will always be in sync. The version should be 3.4.0 for Micronaut 2.4
