### ISSUE TITLE
Websocket client hangs when 502 or 503 received from server

### ISSUE THREAD

**Issue by pskowronek** [micronaut-projects/micronaut-core#5196]
Websocket client hangs when 502 or 503 received from server.

### Steps to Reproduce

When executing the following sample code it hangs endlesssly on connect (blockingFirst) when the server returns 502 or 503:
```
@Inject
@Client("https://some-server:443")
RxWebSocketClient webSocketClient;
...
MutableHttpRequest<?> request = GET("/some/path").bearerAuth("some-token");
MyClient myClient = webSocketClient.connect(MyClient.class, request).onErrorReturn(o -> {
-> {
                        LOG.error("caught error: {}", o.getMessage()); // Not executed
                        throw new Exception("Error caught");
                        //return null;
      }).blockingFirst();

LOG.info("Not executed, hangs on connect line");
```

Stack trace logged while executing the code:

```
ERROR i.m.h.c.w.NettyWebSocketClientHandler - Unexpected Exception in WebSocket [myproject.MyClient$Intercepted@4b2b7dcf]: Invalid handshake response getStatus: 502 Bad Gateway
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 502 Bad Gateway
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:191)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:216)
	at io.micronaut.http.client.websocket.NettyWebSocketClientHandler.channelRead0(NettyWebSocketClientHandler.java:151)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Thread dump shows the following thread is blocked endlessly:

```
"nioEventLoopGroup-1-3@3767" prio=5 tid=0x1c nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	  at io.reactivex.internal.subscribers.BlockingBaseSubscriber.blockingGet(BlockingBaseSubscriber.java:65)
	  at io.reactivex.Flowable.blockingFirst(Flowable.java:5608)
	  at myproject.Application.testClient(Application.java:81)
	  at myproject.$ApplicationDefinition$$exec1.invokeInternal(Unknown Source:-1)
	  at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	  at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2684)
	  at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
	  at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	  at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$15(RoutingInBoundHandler.java:1318)
	  at io.micronaut.http.server.netty.RoutingInBoundHandler$$Lambda$364.1996489578.call(Unknown Source:-1)
	  at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	  at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	  at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	  at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	  at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	  at io.micronaut.http.context.ServerRequestTracingPublisher$$Lambda$378.741715178.run(Unknown Source:-1)
	  at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	  at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	  at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	  at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	  at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	  at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	  at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	  at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:748)
```

### Expected Behaviour

It should not hang,  it should continue with execution reporting an error in someway (either by executing onError or other means?). Unless there is something wrong with my code sample and it must be done in a different way.

### Actual Behaviour

The connection hangs endlessly.

### Environment Information

- **Operating System**: macOS Catalina
- **Micronaut Version:**: 2.4.0
- **JDK Version:** 8

### Example Application

Sample code as above.

**Comment by pskowronek** [comment]
That was quick! Thanks!
