### ISSUE TITLE
Building native image of Kotlin app fails with 2.4.1+

### ISSUE THREAD

**Issue by veN1337** [micronaut-projects/micronaut-core#5210]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a basic Micronaut application (Micronaut CLI or https://micronaut.io/launch) with Kotlin as language (Micronaut version 2.4.1, 2.4.2 or 2.4.3-SNAPSHOT)
2. Run "./gradlew nativeImage" or "./mvnw package -Dpackaging=native-image"

### Expected Behaviour

Native image is built without any errors.
Works with Micronaut 2.4.0 and lower.

### Actual Behaviour

Native image build fails with `Error: Classes that should be initialized at run time got initialized during image building:
 kotlin.ULong was unintentionally initialized at build time.`:
```
Error: Classes that should be initialized at run time got initialized during image building:
 kotlin.ULong was unintentionally initialized at build time. com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt caused initialization of this class with the following trace: 
        at kotlin.ULong.<clinit>(ULong.kt)
        at com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt.<clinit>(UnsignedNumbers.kt:22)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 kotlin.ULong was unintentionally initialized at build time. com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt caused initialization of this class with the following trace: 
        at kotlin.ULong.<clinit>(ULong.kt)
        at com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt.<clinit>(UnsignedNumbers.kt:22)


        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

> Task :nativeImage FAILED

FAILURE: Build failed with an exception.
```

### Environment Information

- **Operating System**: Windows 10 and/or Docker Container with graalvm-ce:java11-21.0.0.2
- **Micronaut Version:** 2.4.1+
- **JDK Version:** GraalVM Version 21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)

### Example Application
Basic Kotlin Micronaut Application:
```mn create-app --build=maven --jdk=11 --lang=kotlin --test=junit com.example.demo```
or
```mn create-app --build=gradle_kotlin --jdk=11 --lang=kotlin --test=junit com.example.demo```

### Additional information

Using Micronaut 2.4.0 or lower works fine.
Increasing or decreasing the Kotlin version did not help .
Happens with Maven and Gradle (Kotlin). I didn't try normal/groovy Gradle.
Happens with GraalVM on Windows or with the ghcr.io/graalvm/graalvm-ce:java11-21.0.0.2 docker image.
Guessing this error is caused due to a newer `jackson-module-kotlin` version in Micronaut 2.4.1 compared to 2.4.0.

**Comment by vonZeppelin** [comment]
Similar issue under the `micronaut-kotlin` project, https://github.com/micronaut-projects/micronaut-kotlin/issues/257

**Comment by veN1337** [comment]
Thanks for the information. `micronaut-kotlin` seems to be the better project for this problem. I'm closing this issue.

**Comment by graemerocher** [comment]
keeping this open so it is not forgotten

**Comment by ilopmar** [comment]
This PR https://github.com/micronaut-projects/micronaut-kotlin/pull/260 fixes this issue.

**Comment by graemerocher** [comment]
@ilopmar was this released and merged and can this be closed?

**Comment by ilopmar** [comment]
Yes. The new micronaut-kotlin version was released and will be the default for next micronaut version.

To make sure this doesn't happen again I added a Kotlin app to our CI: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1177748798
