### ISSUE TITLE
Regression: HTTP client read timeout since 2.4.0

### ISSUE THREAD

**Issue by mdeso** [micronaut-projects/micronaut-core#5270]
### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

After updating a system consisting of multiple Micronaut services from 2.3.4 to 2.4.x (first tried 2.4.2, then 2.4.0) we noticed that calls of one service to another no longer work but throw a read timeout exception instead. Other calls to services with a very similar structure work (from the same service where the failing call occurs and between other services). I could not determine where the difference between these service calls is, so it's difficult to extract an example of this behavior. In 2.3.4 the failing call works without problems. This seems similar to Issue #2905 which I reported a year ago but there all calls between services failed. And the workaround mentioned there doesn't help here. I haven't found a workaround at all, so we had to revert to 2.3.4.

The failing service method has the following form:

```java
@Post(uri = "/do/something")
Single<String> doSomething(@Body DataObject data);
```
The stacktrace is
```java
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
        at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
        at io.micronaut.http.client.netty.DefaultHttpClient$12.exceptionCaught(DefaultHttpClient.java:2316)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
        at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
        at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
        at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
        at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

### Expected Behaviour

Service call should work (as in 2.3.4).

### Actual Behaviour

Read timeout exceptions.

### Environment Information

- **Operating System**: Linux, Windows
- **Micronaut Version:** 2.4.x (2.4.0 and 2.4.2 tested)
- **JDK Version:** 8

**Comment by graemerocher** [comment]
Provide an example that reproduces the issue please

**Comment by mdeso** [comment]
Unfortunately I could not reproduce the problem in a simple example. As described, other (similar) service calls work and I could not determine what distinguished the failing call from the others. Obviously there must be some difference and something must have changed from 2.3 to 2.4 to cause this but from the change log I could no derive the cause.

**Comment by graemerocher** [comment]
Most likely there is somewhere in your code where you are blocking the event loop

**Comment by mdeso** [comment]
Has event loop handling changed in 2.4? The service interfaces (including the failing one) are annotated to execute their methods on `TaskExecutors.IO`.

**Comment by mdeso** [comment]
I'll close this issue. As I just found out it seems to be some strange micronaut-data problem which causes the service to stall if it fetches data, causing it not being able to answer requests. But there's no exception or error message, even the debug log looks normal. I'll try to identify the actual problem and report it in micronaut-data if I can find it.
