### ISSUE TITLE
Error instantiating bean of type  [io.micronaut.discovery.DefaultCompositeDiscoveryClient] with Consul/Eureka and Micronaut 2.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5278]
Tonight the Consul and Eureka apps have failed in GraalVM CI with error `io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.DefaultCompositeDiscoveryClient]`

**The error also happens when running on the JVM**

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-service-discovery-consul`
- `cd micronaut-service-discovery-consul`
- `git checkout 2.5.x`
- Start Consul `docker run -it --rm -p 8500:8500 consul:latest`
- `./gradlew run`

### Expected Behaviour

The application should start

### Actual Behaviour

The application fails during startup with the following error:

```
08:51:05.593 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.discovery.DefaultCompositeDiscoveryClient]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new DefaultCompositeDiscoveryClient([List discoveryClients])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.DefaultCompositeDiscoveryClient]

Message: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
Path Taken: new DefaultCompositeDiscoveryClient([List discoveryClients])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3091)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:2994)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1059)
        at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1225)
        at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1172)
        at io.micronaut.discovery.$DefaultCompositeDiscoveryClientDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
        at io.micronaut.context.DefaultConditionContext.getBean(DefaultConditionContext.java:98)
        at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:136)
        at io.micronaut.health.HeartbeatDiscoveryClientCondition.matches(HeartbeatDiscoveryClientCondition.java:36)
        at io.micronaut.context.RequiresCondition.matchesCustomConditions(RequiresCondition.java:342)
        at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
        at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:107)
        at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
        at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:68)
        at io.micronaut.inject.BeanContextConditional.isEnabled(BeanContextConditional.java:40)
        at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$23(DefaultBeanContext.java:1585)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1599)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:219)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2857)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!
        at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:314)
        at io.micronaut.discovery.consul.client.v1.AbstractConsulClient$Intercepted.<init>(Unknown Source)
        at io.micronaut.discovery.consul.client.v1.$AbstractConsulClient$InterceptedDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
        ... 41 common frames omitted

```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.5.0-SNAPSHOT
- **JDK Version:** 8

**Comment by graemerocher** [comment]
Fixed by reverting a commit https://github.com/micronaut-projects/micronaut-core/commit/e5229cb491b616d6c8f5e4e6acb1de679732a53a

Looks like we can't make this change easily without recompiling all the modules unfortunately
