### ISSUE TITLE
@Body and proxyClient in same controller method cause subscription error

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#5299]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Define a controller method which reads the body and use the proxyClient, eg
```
   @Post("/proxy")
    public Single<HttpResponse> proxypost(@Nullable @Body Object body, HttpRequest<?> request) {
        return Single.fromPublisher(proxyHttpClient.proxy(
            request.mutate()
                .uri(builder -> builder
                    .scheme("http")
                    .host(embeddedServer.getHost())
                    .port(embeddedServer.getPort())
                    .replacePath("/"))));
    }
```

### Expected Behaviour
The body is available to read and the request is proxied.

### Actual Behaviour
When the proxyClient is triggered, an exception is thrown and the request hangs:
```
[default-nioEventLoopGroup-1-6] ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: This publisher only supports one subscriber
java.lang.IllegalStateException: This publisher only supports one subscriber
        at io.micronaut.http.netty.reactive.HandlerPublisher.subscribe(HandlerPublisher.java:127)
        at io.micronaut.http.netty.stream.DelegateStreamedHttpRequest.subscribe(DelegateStreamedHttpRequest.java:55)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.subscribeSubscriberToStream(HttpStreamsHandler.java:164)
        at io.micronaut.http.netty.stream.HttpStreamsClientHandler.subscribeSubscriberToStream(HttpStreamsClientHandler.java:137)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.unbufferedWrite(HttpStreamsHandler.java:392)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.flushNext(HttpStreamsHandler.java:436)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.write(HttpStreamsHandler.java:332)
        at io.micronaut.http.netty.stream.HttpStreamsClientHandler.write(HttpStreamsClientHandler.java:192)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
       ...
```

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** 2.4.2
- **JDK Version:** 11

### Example Application

https://github.com/luckyswede/micronaut-proxy-subscribe-issue

**Comment by graemerocher** [comment]
yeah generally `ProxyClient` is designed to be used within a filter where the body is not yet consumed

**Comment by luckyswede** [comment]
It's actually the same behavior if u move the proxyClient to a filter

**Comment by luckyswede** [comment]
I've updated the repo now to use the proxyclient from a filter, still getting the same error

**Comment by graemerocher** [comment]
I think that will be fixed by https://github.com/micronaut-projects/micronaut-core/pull/5261 in 2.5.x

**Comment by luckyswede** [comment]
Ok, what if I _want_ to read the body? In my case I want it for logging, but in a gateway app I could potentially want to do routing or ratelimiting depending on body content.

**Comment by graemerocher** [comment]
you may be better of writing your our Netty handler in that case since you would need to buffer the body and the pass it down stream

**Comment by luckyswede** [comment]
Ok, then I know
