### ISSUE TITLE
Enums stopped working in native image when updated to GraalVM 21.1.0

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-core#5309]
Enums stopped working in native image when updated to GraalVM `21.1.0`. Nothing else in application has changed.
I tried native image agent, if some new reflection configuration is not missing, but it did not help. 

### Steps to Reproduce

1. Compile following simple application to native image

```kotlin
@Controller("/test")
class TestController {
    @Get("/{choice}")
    fun test(choice: Choice) = choice
}

@Introspected
enum class Choice { A, B, C }
```

2. Run compiled native image
3. Send request for example to `GET /test/A`

### Expected Behaviour

The enum is returned, like in GraalVM `21.0.0`.

### Actual Behaviour

Error is thrown: `Internal Server Error: java.lang.ClassNotFoundException: java.lang.Object`

Stacktrace:
```
21:48:44.015 INFO  io.micronaut.runtime.Micronaut [main] Startup completed in 40ms. Server Running: http://0.0.0.0:8080
21:48:46.598 ERROR i.m.h.s.netty.RoutingInBoundHandler [io-executor-thread-1] Unexpected error occurred: java.lang.ClassNotFoundException: java.lang.Object
java.lang.RuntimeException: java.lang.ClassNotFoundException: java.lang.Object
        at com.fasterxml.jackson.databind.util.ClassUtil.closeOnFailAndThrowAsIOE(ClassUtil.java:503)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4489)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3765)
        at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:228)
        at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:237)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyAsByteBuf(RoutingInBoundHandler.java:1913)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyWithCodec(RoutingInBoundHandler.java:1856)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeResponseBody(RoutingInBoundHandler.java:1646)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeHttpResponse(RoutingInBoundHandler.java:1561)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.access$900(RoutingInBoundHandler.java:151)
        at io.micronaut.http.server.netty.RoutingInBoundHandler$3.onComplete(RoutingInBoundHandler.java:1341)
        at io.micronaut.http.server.netty.RoutingInBoundHandler$3.onComplete(RoutingInBoundHandler.java:1099)
        at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnComplete(ContextCompletionAwareSubscriber.java:73)
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
        at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
        at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:73)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onComplete(FlowableFlatMap.java:678)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onComplete(FlowableSubscribeOn.java:108)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:73)
        at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:57)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:52)
        at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.ClassNotFoundException: java.lang.Object
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:290)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType(KDeclarationContainerImpl.kt:267)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadReturnType(KDeclarationContainerImpl.kt:282)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findMethodBySignature(KDeclarationContainerImpl.kt:201)
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:69)
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:36)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt)
        at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:63)
        at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:136)
        at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findKotlinParameterName(KotlinNamesAnnotationIntrospector.kt:140)
        at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findImplicitPropertyName(KotlinNamesAnnotationIntrospector.kt:36)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:501)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:637)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:625)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:426)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:270)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
        at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:391)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:220)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:169)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1473)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1421)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:520)
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:798)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
        ... 48 common frames omitted
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.3.2, 2.4.2
- **JDK Version:** GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)

### Example Application

Example application is pretty minimal and is included in steps to reproduce.

**Comment by ilopmar** [comment]
I'm able to reproduce this issue but only because `Choice` is annotated with `@Introspected` and it shouldn't. If you remove the annotation it works as expected.

**Comment by jameskleeh** [comment]
@ilopmar Do you know why that causes the issue?

**Comment by ilopmar** [comment]
No idea but it has to do with Kotlin because with a Java application it works when annotating the enum.

**Comment by morki** [comment]
Thank you for your hint @ilopmar, it solves the problem in this minimal example, which I thought is sufficient when I was trying what is minimal reproducible code. My real problem is when used inside expanded query params:

```kotlin
@Controller("/sources")
class SourceController {
    @Get("{?filter*}")
    fun listAction(filter: SourceFilter) = TODO()
}

@Introspected
data class SourceFilter(val type: SourceType = SourceType.PENDING)

enum class SourceType { ERROR, SKIPPED, PENDING }
```

with:

```yaml
jackson:
  bean-introspection-module: false
```

because of Kotlin default values.

Previously, enum `SourceType` was annotated with `@Introspected` to "accidentaly" add it to reflection config.
With the switch to new GraalVM it stopped working. I added `SourceType` manually to `reflect-config.json` and it works now.

Probably it was misusing `@Introspected` annotation, so maybe it is not a bug, but feature request to add some other annotation only to add some class to `reflect-config.json`.

Maybe we can extend existing `@ReflectiveAccess` annotation to work with classes?
Or extend `@TypeHint` to use current annotated class, when property `classes` is not used?

Thank you very much for your time.

**Comment by ilopmar** [comment]
@morki What about adding the enum with `@TypeHint` so it is added automatically to `reflect-config.json` so you don't need to do it?.

If you annotate your Application class with: 

```
@TypeHint(value = { Choice.class })
public class Application {
    ...
}
```

This generates the following entry in `reflect-config.json`:

```json
{
  "name" : "com.example.Choice",
  "allDeclaredConstructors" : true
}
```

Does this work for you?

**Comment by morki** [comment]
Yes, it does work, but it adds some level of indirection to the code (the same as adding it to `reflect-config.json`)
The idea was to have that in place, where the enum and other data classes are declared (developer does not have to jump anywhere and break his flow).

**Comment by ilopmar** [comment]
Understood, thanks for the feedback!

**Comment by morki** [comment]
I think this can be closed with https://github.com/micronaut-projects/micronaut-core/pull/5574 :)
