### ISSUE TITLE
IllegalAccessErrors trying to run JU5 tests with packagenames that include capital letters.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#5366]
Thanks to @jbushdiecker for helping to track this down.

Note that this issue appears starting with Micronaut 2.3.0 and still exists in 2.5.0. It worked fine with 2.2.3. This is a blocker for migrating our project beyond version 2.2.3

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a class in a package that has a capital letter in the name, for example, com.example.A
2. Create  tests for that class
3. Run the tests

### Expected Behaviour
The tests should pass

### Actual Behaviour
The tests don't even run. Micronaut fails to bootstrap. As a result, even a test in a packagename with all lower case fails unless test classes in the packages with caps are removed.

```
Unexpected error loading bean definition [com.example.$A.PackagenamebugATestDefinition]: tried to access class com.example.A.PackagenamebugATest from class com.example.$A.PackagenamebugATestDefinitionClass
io.micronaut.context.exceptions.BeanContextException: Unexpected error loading bean definition [com.example.$A.PackagenamebugATestDefinition]: tried to access class com.example.A.PackagenamebugATest from class com.example.$A.PackagenamebugATestDefinitionClass
	at io.micronaut.context.AbstractBeanDefinitionReference.isPresent(AbstractBeanDefinitionReference.java:92)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalAccessError: tried to access class com.example.A.PackagenamebugATest from class com.example.$A.PackagenamebugATestDefinitionClass
	at com.example.$A.PackagenamebugATestDefinitionClass.getBeanType(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.isPresent(AbstractBeanDefinitionReference.java:84)
	... 15 more
```
### Environment Information

- **Operating System**: Windows 10 and Mac OS 11.3
- **Micronaut Version:** 2.3+ (tested with 2.3.x, 2.4.x and 2.5.x)
- **JDK Version:** AdoptOpenJDK 8.0.232.09 (Windows 10) and 8.0.282 (Mac OS)

### Example Application

- https://github.com/wetted/packagenamebug

**Comment by graemerocher** [comment]
Why on earth would you have package names with capital letters?

**Comment by wetted** [comment]
> Why on earth would you have package names with capital letters?

I agree using caps in package names isn't a best practice, but it's not illegal syntax. 

This is a legacy Swing-based application going back almost 20 years since inception, with a plugin architecture and document structure that rely on plugin package names as they are.  I wouldn't do it that way now, but it's what we have, and we can't change it now. It would be too costly and risky.

**Comment by wetted** [comment]
Kudos for a quick fix @jameskleeh. Thank you.
