### ISSUE TITLE
Uninformative exception message in exception when provide unsupported properties file

### ISSUE THREAD

**Issue by aleksandr-chermashentsev** [micronaut-projects/micronaut-core#5418]
### Steps to Reproduce

1. provide unsupported properties file format using VM argument for instance: -Dmicronaut.config.files=application.tbd

### Expected Behaviour

Exception which points that .tbd is unsupported format for properties file. List of supported formats also could be useful.

### Actual Behaviour

Exception "Unsupported properties file format: application" 

### Stacktrace
```io.micronaut.context.exceptions.ConfigurationException: Unsupported properties file format: application
	at io.micronaut.context.env.DefaultEnvironment.lambda$readPropertySourceListFromFiles$4(DefaultEnvironment.java:456) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at java.util.Optional.ifPresent(Optional.java:176) ~[?:?]
	at io.micronaut.context.env.DefaultEnvironment.readPropertySourceListFromFiles(DefaultEnvironment.java:438) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:396) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:254) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:696) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:664) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:212) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:164) ~[micronaut-inject-2.4.1.jar:2.4.1]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71) [micronaut-context-2.4.1.jar:2.4.1]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311) [micronaut-context-2.4.1.jar:2.4.1]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297) [micronaut-context-2.4.1.jar:2.4.1]```

**Comment by sapanparikh18** [comment]
May I take this up @graemerocher ? Seems like it only involves changing an exception message
```Java
else {
       throw new ConfigurationException("Unsupported properties file format: " + filePath);
}
```

**Comment by graemerocher** [comment]
Yup

**Comment by sapanparikh18** [comment]
@graemerocher I have created a PR

**Comment by sapanparikh18** [comment]
Hi, @graemerocher I had to resubmit the PR because the PR failed due to author & CLA realted issues. Will you please approve it once again so that it can run the workflow?
