### ISSUE TITLE
NoSuchBeanException for @MockBean when the original bean has a qualifier

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#5419]
In `2.5.2`, also in `2.5.3`, works well in `2.5.1`.

For the bean:

```kotlin
@TransactionalAdvice @Singleton @Handler(BankTransfer::class)
class BankTransferService
```

Annotated with `@Handler` annotation which is `@Qualifier`:

```java
@Documented
@Retention(RUNTIME)
@Target({ElementType.TYPE})
@Qualifier
public @interface Handler {
	Class[] value();
}
```

I have a test which replaces this bean with a Mockito-based mocked bean:

```kotlin
@MicronautTest
class FinanceOperationRabbitTest {

    @MockBean(BankTransferService::class)
    fun mockBankTransferService(): BankTransferService = mock(BankTransferService::class.java)

}
```

This works well in `2.5.1` but in `2.5.2` this test fails with:

```stacktrace
Error instantiating bean of type  [io.luna.service.main.finance.bank.service.$EmoneyDepositServiceDefinition$Intercepted]

Message: No bean of type [io.luna.service.main.finance.bank.service.BankTransferService] exists for the given qualifier: @Named('io.luna.feature.core.handler.Handler'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: ApplicationInitializer.loaders --> $DataLoaderExecutorDefinition$Intercepted.loaders --> new $UserLoaderDefinition$Intercepted(UserRepository repository,[UserService userService],RoleLoader roleLoader,RoleRepository roleRepository,LunaEnvironment environment,DefaultUsersConfig usersConfig,BankLoader bankLoader,BankService bankService,UserBankAccountService userBankAccountService,UserBankService userBankService,UserOfferLoader userOfferLoader,CompanyLoader companyLoader,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> new $UserServiceDefinition$Intercepted(UserRepository repository,LunaPasswordEncoder passwordEncoder,RoleRepository roleRepository,UserBankRepository userBankRepository,Notifier notifier,UserAccountService userAccountService,CompanyService companyService,[EmoneyDepositService emoneyDepositService],UserTicketRightService userTicketRightService,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> new $EmoneyDepositServiceDefinition$Intercepted(EmoneyDepositRepository repository,SequenceService sequenceService,AfterCommitExecutor afterCommitExecutor,UserAccountService userAccountService,Provider userService,Provider userBankAccountService,[BankTransferService bankTransferService],Client cashflowApi,LunaEnvironment environment,DepositService depositService,ConfigValueLoader configValueLoader,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.luna.service.main.finance.bank.service.$EmoneyDepositServiceDefinition$Intercepted]

Message: No bean of type [io.luna.service.main.finance.bank.service.BankTransferService] exists for the given qualifier: @Named('io.luna.feature.core.handler.Handler'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: ApplicationInitializer.loaders --> $DataLoaderExecutorDefinition$Intercepted.loaders --> new $UserLoaderDefinition$Intercepted(UserRepository repository,[UserService userService],RoleLoader roleLoader,RoleRepository roleRepository,LunaEnvironment environment,DefaultUsersConfig usersConfig,BankLoader bankLoader,BankService bankService,UserBankAccountService userBankAccountService,UserBankService userBankService,UserOfferLoader userOfferLoader,CompanyLoader companyLoader,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> new $UserServiceDefinition$Intercepted(UserRepository repository,LunaPasswordEncoder passwordEncoder,RoleRepository roleRepository,UserBankRepository userBankRepository,Notifier notifier,UserAccountService userAccountService,CompanyService companyService,[EmoneyDepositService emoneyDepositService],UserTicketRightService userTicketRightService,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> new $EmoneyDepositServiceDefinition$Intercepted(EmoneyDepositRepository repository,SequenceService sequenceService,AfterCommitExecutor afterCommitExecutor,UserAccountService userAccountService,Provider userService,Provider userBankAccountService,[BankTransferService bankTransferService],Client cashflowApi,LunaEnvironment environment,DepositService depositService,ConfigValueLoader configValueLoader,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2006)
	at io.micronaut.context.DefaultBeanContext.lambda$null$55(DefaultBeanContext.java:2454)
	at io.micronaut.context.ProviderUtils$MemoizingProvider.initialize(ProviderUtils.java:65)
	at io.micronaut.context.ProviderUtils$MemoizingProvider.get(ProviderUtils.java:60)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2462)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2429)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.luna.service.main.finance.bank.service.$$EmoneyDepositServiceDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.luna.service.main.rbac.service.$$UserServiceDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.luna.service.main.rbac.loader.$$UserLoaderDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3044)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1062)
	at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1232)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForField(AbstractBeanDefinition.java:1227)
	at io.luna.feature.postgres.loader.$DataLoaderExecutorDefinition.injectBean(Unknown Source)
	at io.luna.feature.postgres.loader.$$DataLoaderExecutorDefinition$InterceptedDefinition.injectBean(Unknown Source)
	at io.luna.feature.postgres.loader.$$DataLoaderExecutorDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3044)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1062)
	at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1232)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForField(AbstractBeanDefinition.java:1227)
	at io.luna.feature.core.beans.$ApplicationInitializerDefinition.injectBean(Unknown Source)
	at io.luna.feature.core.beans.$ApplicationInitializerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:732)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:3391)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3412)
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at io.luna.feature.core.beans.ApplicationInitializer$ApplicationEventListener$start1$Intercepted.onApplicationEvent(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1326)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1311)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:246)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
	at io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:348)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:239)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:54)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.luna.service.main.finance.bank.service.BankTransferService] exists for the given qualifier: @Named('io.luna.feature.core.handler.Handler'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.BeanDefinitionRegistry.lambda$getProxyTargetBeanDefinition$1(BeanDefinitionRegistry.java:300)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.micronaut.context.BeanDefinitionRegistry.getProxyTargetBeanDefinition(BeanDefinitionRegistry.java:300)
	at io.micronaut.context.DefaultBeanContext.findProxyTargetMethod(DefaultBeanContext.java:1112)
	at io.micronaut.context.ExecutionHandleLocator.getProxyTargetMethod(ExecutionHandleLocator.java:185)
	at io.luna.service.main.test.finance.operation.$FinanceOperationRabbitTest$MockBankTransferService3Definition$Intercepted.<init>(Unknown Source)
	at io.luna.service.main.test.finance.operation.$$FinanceOperationRabbitTest$MockBankTransferService3Definition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	... 122 more
```

When I turn on trace logging for `io.micronaut.context` I can see the difference here:

```
// 2.5.1
Qualifying bean [io.luna.service.main.finance.bank.service.BankTransferService] for qualifier: io.micronaut.context.DefaultBeanContext$1@29458914 
Found concrete candidate [Definition: io.luna.service.main.test.finance.operation.FinanceOperationRabbitTest] for type: io.micronaut.context.DefaultBeanContext$1@29458914 io.luna.service.main.finance.bank.service.BankTransferService 
Created bean [Mock for BankTransferService, hashCode: 1811107780] from definition [Definition: io.luna.service.main.test.finance.operation.FinanceOperationRabbitTest] with qualifier [io.micronaut.context.DefaultBeanContext$1@29458914]

// 2.5.2
Qualifying bean [io.luna.service.main.finance.bank.service.BankTransferService] for qualifier: @Named('io.luna.feature.core.handler.Handler') and io.micronaut.context.DefaultBeanContext$1@5bced20 
No qualifying beans of type [io.luna.service.main.finance.bank.service.BankTransferService] found for qualifier: @Named('io.luna.feature.core.handler.Handler') and io.micronaut.context.DefaultBeanContext$1@5bced20 
```

I'm also attaching full logs (`1` is for `2.5.1`, `2` is for `2.5.2`): [logs.tar.gz](https://github.com/micronaut-projects/micronaut-core/files/6471360/logs.tar.gz)

**Comment by graemerocher** [comment]
This makes sense to me, the mocked bean should contain the qualifier. Currently qualifiers are not automatically inherited by `@MockBean` 

Previous behaviour seems like a bug

**Comment by l0co** [comment]
This is strange for me because this qualifier is never used to get this bean in this test, so I don't understand why is it required? 

I also don't know how to accomplish *the mocked bean should contain the qualifier*? Because this:

```kotlin
    @MockBean(BankTransferService::class) @Handler(BankTransfer::class)
    fun mockBankTransferService(): BankTransferService = mock(BankTransferService::class.java)
```

Doesn't work and throws the same exception.

**Comment by graemerocher** [comment]
I think this would be resolved if this change were back ported to 2.5.x https://github.com/micronaut-projects/micronaut-core/pull/5424/files#diff-6ed11b100f79e881f2d1f257c202d3fd7402bd1093d92a3045bafe002fc72ddcR2201-R2208

You wouldn't be able to provide an example?

**Comment by l0co** [comment]
Catch the reproducible example here: https://github.com/l0co/micronaut-playground/tree/micronaut-5419

Note, that this only happens after adding `io.micronaut.sql:micronaut-hibernate-jpa` dependency and wrapping `MyBean` with `@TransactionalAdvice`, so somehow it's realed to `@Around` proxies.
