### ISSUE TITLE
ManagedChannel configuration injection failure when eager single initialization is set

### ISSUE THREAD

**Issue by paulolieuthier** [micronaut-projects/micronaut-core#5530]
ManagedChannel configuration injection fails when the application is run with eager single initialization.

### Steps to Reproduce

1. `mn create-grpc-app example-project`.
2. Add `.eagerInitSingletons(true)` to Micronaut initialization.
3. Try to run the application.

### Expected Behaviour

The application should run just fine.

### Actual Behaviour

Exception is thrown:

```
$ ./gradlew run

> Task :run FAILED
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

17:07:01.586 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1568)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2907)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at micronaut.bug.Application.main(Application.java:9)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1041)
        at io.micronaut.grpc.channels.$GrpcDefaultManagedChannelConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2294)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1562)
        ... 6 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2412)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
        ... 12 common frames omitted

FAILURE: Build failed with an exception.
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.5.4
- **JDK Version:** 11.0.11

**Comment by graemerocher** [comment]
This will be fixed by https://github.com/micronaut-projects/micronaut-grpc/pull/368

**Comment by paulolieuthier** [comment]
Any chance of getting this backported?

**Comment by graemerocher** [comment]
You can try use the 3.0.0 RC1 version in Micronaut 2.x it should be compatible https://github.com/micronaut-projects/micronaut-grpc/releases/tag/v3.0.0.RC1

**Comment by racevedoo** [comment]
@graemerocher just tried with 3.0.0 RC1 (following the same steps provided by @paulolieuthier) but its still not solved. Can we get this reopened?

```
> Task :run FAILED
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.0-RC1)

11:30:50.816 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1840)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3362)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:243)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at example.project.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1079)
        at io.micronaut.grpc.channels.$GrpcDefaultManagedChannelConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2555)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1834)
        ... 6 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2698)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1555)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1052)
        ... 12 common frames omitted

```

**Comment by racevedoo** [comment]
I did some digging that could be useful here. In a project that only uses `grpc-server-runtime`, we get the following error during app startup:
```14:19:50.835 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1568)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2905)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at com.incognia.location.events.api.Application.main(Application.java:7)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2008)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2768)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2303)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1562)
        ... 6 common frames omitted
Caused by: java.lang.IllegalStateException: Not started
        at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
        at io.grpc.internal.ServerImpl.getPort(ServerImpl.java:190)
        at io.micronaut.grpc.server.GrpcEmbeddedServer.getPort(GrpcEmbeddedServer.java:124)
        at io.micronaut.grpc.server.GrpcServerChannel.serverChannel(GrpcServerChannel.java:61)
        at io.micronaut.grpc.server.$GrpcServerChannel$ServerChannel0Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
        ... 9 common frames omitted
```

This is basically because we try to create a channel that connects to a `GrpcEmbeddedServer` when it has not been started yet:

https://github.com/micronaut-projects/micronaut-grpc/blob/83967c5fc82a06589ff502b9131832e4af5d49c6/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerChannel.java#L55-L70

According to `GrpcServerChannel`'s javadoc, it is basically used for testing, so I tried adding another `@Requires` to avoid creating the channel, unless the user asks for it. Does it make sense to provide this to users? The patch would be something like:

```
diff --git a/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerChannel.java b/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerChannel.java
index c0c5fcd..d3317de 100644
--- a/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerChannel.java
+++ b/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerChannel.java
@@ -22,6 +22,7 @@ import io.micronaut.context.annotation.Bean;
 import io.micronaut.context.annotation.Factory;
 import io.micronaut.context.annotation.Requires;
 import io.micronaut.core.util.CollectionUtils;
+import io.micronaut.core.util.StringUtils;
 import io.micronaut.scheduling.TaskExecutors;
 
 import javax.inject.Named;
@@ -51,6 +52,7 @@ public class GrpcServerChannel {
     @Singleton
     @Named(NAME)
     @Requires(beans = GrpcEmbeddedServer.class)
+    @Requires(property = GrpcServerConfiguration.PREFIX + ".channel.enabled", value = StringUtils.TRUE, defaultValue = StringUtils.FALSE)
     @Bean(preDestroy = "shutdown")
     protected ManagedChannel serverChannel(
             GrpcEmbeddedServer server,
```

**Comment by racevedoo** [comment]
Just to be clear, this does not solve the issue for `GrpcDefaultManagedChannelConfiguration`, which is included in `grpc-client-runtime` only

**Comment by racevedoo** [comment]
Any updates here guys?

**Comment by graemerocher** [comment]
Seems it is already fixed in the gRPC module just no release was done, I have triggered a 3.0.1 release
