### ISSUE TITLE
Resolve Environment Variables in properties file

### ISSUE THREAD

**Issue by mahyarmobilab** [micronaut-projects/micronaut-core#554]
Hi, 
First of thanks a lot for effort on developing this cool framework. I recently started working with it and have following problem.
I have an environment variable which contains numbers and that doesn't match to what you have considered in environment variable:
```
public class DefaultPropertyPlaceholderResolver implements PropertyPlaceholderResolver {
...
    if (expr.matches("^[\\p{Lu}_]+")) {
            String v = System.getenv(expr);
            if (StringUtils.isNotEmpty(v)) {
                builder.append(v);
                return;
            }
        }
...
}
```
I think this need to be fixed because not all the time we have control over our environment variable names. 

### Steps to Reproduce
1- Place an expression for an environment variable with name like `DD_AGENT_PORT_8125_UDP_PORT` with Uppercase letters, underscores and numbers
```
Caused by: io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${DD_AGENT_PORT_8125_UDP_ADDR} in value: ${DD_AGENT_PORT_8125_UDP_ADDR}
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveExpression(DefaultPropertyPlaceholderResolver.java:133)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolvePlaceholders(DefaultPropertyPlaceholderResolver.java:90)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholders(DefaultPropertyPlaceholderResolver.java:76)
	at io.micronaut.context.env.PropertySourcePropertyResolver.resolvePlaceHoldersIfNecessary(PropertySourcePropertyResolver.java:501)
	at io.micronaut.context.env.PropertySourcePropertyResolver.lambda$resolveSubProperties$3(PropertySourcePropertyResolver.java:308)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.micronaut.context.env.PropertySourcePropertyResolver.resolveSubProperties(PropertySourcePropertyResolver.java:303)
	at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:226)
	at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:94)
	at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:111)
	at io.micronaut.configuration.metrics.micrometer.statsd.StatsdConfigurationProperties.<init>(StatsdConfigurationProperties.java:46)
	at io.micronaut.configuration.metrics.micrometer.statsd.$StatsdConfigurationPropertiesDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1252)
	... 43 common frames omitted
```

### Actual Behaviour

Replace the expression with corresponding system environment variable

### Environment Information

- **Operating System**: macOs High Sierra (10.13.4)
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8

I think at least numbers should be allowed in this pattern.
Would you please guide me if I have to use another way for my purpose. If not and you can confirm it as a requirement, I can open a pull request.

**Comment by mahyarmobilab** [comment]
@graemerocher if it's ok with you, I'll open a pull-request for this issue.

**Comment by mahyarmobilab** [comment]
@graemerocher I fixed it but cannot open PR because of permission issue.

**Comment by jameskleeh** [comment]
@mahyarmobilab If you fork this repository, you can make changes and submit a PR

**Comment by graemerocher** [comment]
Thanks for the PR
