### ISSUE TITLE
HTTPClient - Read Timeout

### ISSUE THREAD

**Issue by paulboichat** [micronaut-projects/micronaut-core#5596]
I'm receiving a io.micronaut.http.client.exceptions.ReadTimeoutException when using HTTPClient to call an external service multiple times. The same error can be reproduced in a test application using a client to call a service within the test app

The exception appears to be thrown after using HTTPClient approximately fours times

### Steps to Reproduce

Run the Server in the example application linked below

`mvn mn:run`

Test the "client" endpoint to return 'Hello World Service'

`curl http://localhost:8080/service`

Test a single execution of the proxy service which uses a httpclient to proxy the HelloWorld Service

`curl http://localhost:8080/proxy`

This will return 'Hello World Service' any number of times without error. However, if you use an app like Postman or ab

`ab -c 5 -n 200 localhost:8080/proxy`

You'll see a io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout after approximately four calls.

Alternatively a call to

`curl http://localhost:8080/mproxy`

which calls the client multiple times will also result in an error

### Expected Behaviour

Client should return the Hello World Service 

### Actual Behaviour

After approximately four consecutive calls via the HTTPClient an exception is thrown

Type [clienttest.TestClient$Intercepted] executed with error: Read Timeout
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
        at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
        at io.micronaut.http.client.netty.DefaultHttpClient$12.exceptionCaught(DefaultHttpClient.java:2316)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
        at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
        at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
        at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
        at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:831)

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.5.5
- **JDK Version:** OpenJDK 16

### Example Application

- [https://github.com/paulboichat/clienttest](https://github.com/paulboichat/clienttest)

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

**Comment by jameskleeh** [comment]
You are blocking the event loop. Offload the execution of `proxy` https://github.com/paulboichat/clienttest/blob/main/src/main/java/clienttest/TestController.java#L29 to another thread pool or change the return type of both the client and server to be reactive
