### ISSUE TITLE
Cannot adapt method error when upgrading to Micronaut 3.0.0-M2

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5640]
During the upgrade of Micronaut Flyway to Micronaut 3.0.0-M2 so test fail with:

```
  Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.flyway.EventListenerSpec$TestEventListener$ApplicationEventListener$onStartupCleaned2$Intercepted]: Cannot adapt method [void onApplicationEvent(Object event)]. Target method [onStartupCleaned] not found on bean class io.micronaut.flyway.EventListenerSpec$TestEventListener
      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2315)
      at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3619)
      at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3495)
      at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:850)
      at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1662)
      at io.micronaut.flyway.AbstractFlywayMigration.runFlyway(AbstractFlywayMigration.java:95)
      at io.micronaut.flyway.AbstractFlywayMigration.forceRun(AbstractFlywayMigration.java:85)
      at io.micronaut.flyway.AbstractFlywayMigration.run(AbstractFlywayMigration.java:65)
      at io.micronaut.flyway.DataSourceMigrationRunner.lambda$null$0(DataSourceMigrationRunner.java:65)
      at java.util.Optional.ifPresent(Optional.java:159)
      at io.micronaut.flyway.DataSourceMigrationRunner.lambda$onCreated$1(DataSourceMigrationRunner.java:63)
      at java.util.Optional.ifPresent(Optional.java:159)
      at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:60)
      at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:37)
      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2343)
      at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3226)
      at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3212)
      at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2603)
      at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1882)
      ... 8 more
  Caused by: java.lang.IllegalStateException: Cannot adapt method [void onApplicationEvent(Object event)]. Target method [onStartupCleaned] not found on bean class io.micronaut.flyway.EventListenerSpec$TestEventListener
      at io.micronaut.aop.chain.AdapterIntroduction.lambda$new$1(AdapterIntroduction.java:75)
      at java.util.Optional.orElseThrow(Optional.java:290)
      at io.micronaut.aop.chain.AdapterIntroduction.<init>(AdapterIntroduction.java:75)
      at io.micronaut.aop.chain.DefaultInterceptorRegistry.resolveInterceptors(DefaultInterceptorRegistry.java:65)
      at io.micronaut.aop.chain.InterceptorChain.resolveInterceptors(InterceptorChain.java:206)
      at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:144)
      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2286)
      ... 26 more
```

The test looks like:

```groovy
    @Singleton
    @Requires(property = 'spec.name', value = 'EventListenerSpec')
    static class TestEventListener {
        List<MigrationFinishedEvent> migrationFinishedEvents = []
        List<SchemaCleanedEvent> schemaCleanedEvents = []

        @EventListener
        void onStartupMigrate(MigrationFinishedEvent event) {
            migrationFinishedEvents.add(event)
        }

        @EventListener
        void onStartupCleaned(SchemaCleanedEvent event) {
            schemaCleanedEvents.add(event)
        }
    }
```

## Reproduce the issue

Run the tests in this PR https://github.com/micronaut-projects/micronaut-flyway/pull/212

**Comment by graemerocher** [comment]
A bug in the Groovy impl, submitted a PR for it
