### ISSUE TITLE
NonUniqueBeanException in micronaut-test for Micronaut 3

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-core#5668]
https://github.com/micronaut-projects/micronaut-test/pull/437/checks?check_run_id=2929698418
The micronaut-test for kotlin is failing with:
```
 Path Taken: new JpaRollbackTest(EntityManager entityManager,PlatformTransactionManager transactionManager) --> new JpaRollbackTest(EntityManager entityManager,[PlatformTransactionManager transactionManager])
      at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1087)
      at io.micronaut.test.kotest.$JpaRollbackTestDefinition.build(Unknown Source)
      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2286)
      at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3226)
      at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3212)
      at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2762)
      at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2726)
      at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1634)
      at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1608)
      at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:835)
      at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:291)
      at io.micronaut.test.extensions.kotest.MicronautKotestContext.<init>(MicronautKotestContext.kt:43)
      at io.micronaut.test.extensions.kotest.MicronautKotestExtension.instantiate(MicronautKotestExtension.kt:86)
      at io.kotest.engine.spec.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:26)
      at io.kotest.engine.spec.SpecExecutor.createInstance(SpecExecutor.kt:53)
      at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:40)
      at io.kotest.engine.launchers.DefaultSpecLauncher$sequential$3$1$2.invokeSuspend(DefaultSpecLauncher.kt:56)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
  Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [org.springframework.orm.hibernate5.HibernateTransactionManager, org.springframework.jdbc.datasource.DataSourceTransactionManager]
      at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2379)
      at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:451)
      at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3198)
      at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3085)
      at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2999)
      at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2691)
      at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1568)
      at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1060)
      ... 21 more
```

Is this expected and some qualifier is needed or is that regression?

**Comment by graemerocher** [comment]
This was because both the spring and Micronaut tx management was on the path
