### ISSUE TITLE
@Replaces doesn't replace AbstractConsulClient

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-core#5671]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

This issue is based on this question and advice from Graeme Rocher:
https://stackoverflow.com/questions/68057201/micronaut-consul-client-and-retry-support/

### Expected Behaviour

MyConsulClient should replace existing AbstractConsulClient bean.

### Actual Behaviour

MyConsulClient doesn't replace existing AbstractConsulClient bean (as I saw after debugging). So retry functionality is not enabled and application terminated immediately without retry attempts.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.5.0
- **JDK Version:** 16.0.1

**Comment by jameskleeh** [comment]
Please upload an example app

**Comment by sergey-morenets** [comment]
> 
> 
> Please upload an example app

Hi @jameskleeh 
Just uploaded: https://github.com/sergey-morenets/micronaut-consul-client

If I run "gradlew run" command I immediately see an error however this application should perform at least 5 attempts (with delay 2 seconds and multiplier 2)

```
Caused by: io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: no further information: localhost/127.0.0.1:8500
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$34(DefaultHttpClient.java:1133)
	... 18 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:8500
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
```

**Comment by jeffscottbrown** [comment]
I think it is the `ConfigurationClient` (impl is `ConsulConfigurationClient`) that is throwing the exception, not the `ConsulClient`.  Is that correct?

**Comment by sergey-morenets** [comment]
> 
> 
> I think it is the `ConfigurationClient` (impl is `ConsulConfigurationClient`) that is throwing the exception, not the `ConsulClient`. Is that correct?

Hi @jeffbrown Not sure about that, but my main goal was to add retry pattern for loading external Consul configuration.So if it's possible to override ConfigurationClient default behavior it's fine for me as well.

**Comment by sergey-morenets** [comment]
@jeffbrown I added another bean declaration and it was detected by Micronaut (and replaced default ConsulConfigurationClient bean). However retry functionality still didn't work. Application was terminated immediately.

```

@Singleton
@Requires(beans = ConsulClient.class)
@BootstrapContextCompatible
@Replaces(ConsulConfigurationClient.class)
@Retryable(attempts = "5", delay = "2s", multiplier = "2")
class CustomConsulConfigurationClient extends ConsulConfigurationClient {

    public CustomConsulConfigurationClient(ConsulClient consulClient, ConsulConfiguration consulConfiguration, Environment environment) {
        super(consulClient, consulConfiguration, environment);
    }
}
```

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
