### ISSUE TITLE
Regression with HttpClient in Micronaut 2.5.6 because of a timeout

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5682]
The guides started to fail when upgrading them to Micronaut 2.5.7. I needed to restart the upgrade PR 6-7 times until the tests passed.
Now I've submitted [another PR](https://github.com/micronaut-projects/micronaut-guides/pull/333) to try Micronaut 2.5.6 and it also [fails](https://github.com/micronaut-projects/micronaut-guides/pull/333/checks?check_run_id=2952321070#step:7:1356).

The error is always the same and in the same guide: `micronaut-microservices-distributed-tracing-zipkin-maven-java/bookrecommendation` (although I've seen it fail also in kotlin/groovy).

This is the output of the test when it fails.

```
Executing 'micronaut-microservices-distributed-tracing-zipkin-maven-java/bookrecommendation' tests
09:46:31.993 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
09:46:33.380 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
09:46:34.219 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
	at io.micronaut.http.client.netty.DefaultHttpClient$9.userEventTriggered(DefaultHttpClient.java:1870)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
	at io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$4.userEventTriggered(DefaultHttpClient.java:2987)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:430)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:365)
	at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:488)
	at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
	... 29 more
Error: Exception in thread "default-nioEventLoopGroup-4-2" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
	at io.micronaut.http.client.netty.DefaultHttpClient$9.userEventTriggered(DefaultHttpClient.java:1870)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
	at io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$4.userEventTriggered(DefaultHttpClient.java:2987)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:430)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:365)
	at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:488)
	at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
	... 29 more
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 300.465 s <<< FAILURE! - in example.micronaut.BookControllerTest
Error:  testRetrieveBooks  Time elapsed: 300.358 s  <<< ERROR!
java.lang.RuntimeException: 
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input
 at [Source: UNKNOWN; line: 1, column: 35]
	at example.micronaut.BookControllerTest.testRetrieveBooks(BookControllerTest.java:25)
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: 
Unexpected end-of-input
 at [Source: UNKNOWN; line: 1, column: 35]

Error:  Errors: 
Error:    BookControllerTest.testRetrieveBooks:25 » Runtime com.fasterxml.jackson.core.i...
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project micronautguide: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/micronaut-guides/micronaut-guides/build/code/micronaut-microservices-distributed-tracing-zipkin-maven-java/bookrecommendation/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I'm not able to reproduce it locally and I think it may be because of the constraints of the CI environment that has CPUs not too powerful.

Taking a look at the commits included in 2.5.6 I think [this one](http://github.com/micronaut-projects/micronaut-core/commit/0f6cec56d635326911077fb221df40f0c4d9fbe6) could be related.

Also there is [another one related](http://github.com/micronaut-projects/micronaut-core/commit/ac32844fdd87e90cf337698261551531d56be336) but it was introduced in 2.5.7

### Steps to Reproduce

- `git clone https://github.com/micronaut-projects/micronaut-guides`
- `cd micronaut-guides`
- `./gradlew clean build -Dmicronaut.guide=micronaut-microservices-distributed-tracing-zipkin`
- `cd build/code`
- To run all the tests for language/build-tool run `./test.sh` or just run the test in the java-maven project.

### Environment Information

- **Operating System**: Github Actions CI (Linux)
- **Micronaut Version:** 2.5.6 & 2.5.7
- **JDK Version:** 8 & 11

**Comment by graemerocher** [comment]
What we will need to do is find the commit that introduced the issue

**Comment by ilopmar** [comment]
I suggested one commit that may be related, but it's hard to say without testing on CI. Tomorrow I'll publish a custom snapshot based on 2.5.6 with that commit reverted and I'll try it in the guides on CI to see if the tests pass or not.

**Comment by ilopmar** [comment]
I [reverted the commit](https://github.com/micronaut-projects/micronaut-core/commit/3cc17db6f3aa684b04e6762ae21a7d76228f0083) and [published a custom snapshot](https://github.com/micronaut-projects/micronaut-core/commit/63041c4fe6fd436a6a55944a39d7cbee008d2514) but the [build failed again](https://github.com/micronaut-projects/micronaut-guides/runs/2961027302?check_suite_focus=true#step:7:1973).

The worst part is that we need to run the full suite for all the guides to make it fail. I tried running only the zipkin guide tests a couple of times (with 2.5.6) and it always passed.

I'm running out of ideas...

**Comment by ilopmar** [comment]
New failure, this time with 2.5.7 and kotlin-gradle: https://github.com/micronaut-projects/micronaut-guides/runs/2970515018?check_suite_focus=true#step:7:1479

**Comment by yawkat** [comment]
can't reproduce this anymore
