### ISSUE TITLE
using RxWebSocketClient with wss protocol

### ISSUE THREAD

**Issue by chriskosys** [micronaut-projects/micronaut-core#5711]
It is not possible to create an RxWebSocketClient with wss protocol.
It fails in
`io.micronaut.http.client.DefaultLoadBalancerResolver.resolve(String...)`
on the constructor-call to new URL(reference)

```
            try {
                URL url = new URL(reference);
                return Optional.of(LoadBalancer.fixed(url));
            } catch (MalformedURLException e) {
                return Optional.empty();
            }
```

`java.net.MalformedURLException: unknown protocol: wss`

Or is it me doing something fundamentally wrong?

### Steps to Reproduce

1. create an RxWebSocketClient using an url with wss-protocol
i tested with following url which works fine with in a browser-test (js websocket)
> wss://stream.binance.com:9443/stream?streams=btcusdt@kline_5m/adausdt@kline_5m

### Expected Behaviour
Websocket should provide data

### Actual Behaviour
```
Caused by: io.micronaut.http.client.exceptions.HttpClientException: Invalid service reference [wss://stream.binance.com:9443] specified to @Client
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.lambda$null$0(RxNettyHttpClientRegistry.java:235)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.lambda$getClient$1(RxNettyHttpClientRegistry.java:234)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.getClient(RxNettyHttpClientRegistry.java:197)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.getClient(RxNettyHttpClientRegistry.java:148)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.resolveClient(RxNettyHttpClientRegistry.java:392)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.httpClient(RxNettyHttpClientRegistry.java:193)
	at io.micronaut.http.client.netty.$RxNettyHttpClientRegistry$HttpClient0Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:118)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1930)
	... 27 common frames omitted
```

### Environment Information

- **Operating System**: win10
- **Micronaut Version:** 2.41
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
Please upload an example project or show example code

**Comment by chriskosys** [comment]
i already pointed out the faulty code of DefaultLoadBalancerResolver in the description. just try to create an URL-Object with an "wss://" String.
Maybe i am doing something wrong. Can you provide me an example of a working RxWebSocketClient using the wss-protocol? maybe my approach is wrong. i already tried replacing wss by https but it did not work out.

**Comment by jameskleeh** [comment]
@chriskosys In general the approach is to connect via the http or https URL that will do the upgrade

```
RxWebSocketClient wsClient = applicationContext.createBean(RxWebSocketClient, <<some http|https uri>>)
wsClient.connect(BinaryChatClientWebSocket, "/binary/chat/stuff/fred")
```

**Comment by chriskosys** [comment]
Ok, so what can i do if the server does not accept https but only wss?
I tried it in a small browser based js-test and found out that the https-url does not work while the wss url does work.

does not work:
https://stream.binance.com:9443/stream?streams=btcusdt@kline_5m/adausdt@kline_5m
works:
wss://stream.binance.com:9443/stream?streams=btcusdt@kline_5m/adausdt@kline_5m

how can i use that stream with micronaut?

browser based js-test:
[websockettest.zip](https://github.com/micronaut-projects/micronaut-core/files/6779834/websockettest.zip)

**Comment by jz36** [comment]
I faced the same issue. Any updates?

**Comment by jz36** [comment]
@chriskosys hey, I've find out how to handle it. 
Just type 
```
    @Inject
    @Client("https://stream.binance.com:9443")
    RxWebSocketClient webSocketClient;
```

Binance said that it doesn't work, but actually it's work!

**Comment by chriskosys** [comment]
@jz36 Thanks for your feedback.
At the time i tried this it worked only for the /ws-endpoint but it did not work for the /stream endpoint like shown in my example. Which of the endpoints did you check?

**Comment by jz36** [comment]
@chriskosys I checked on `/ws/{symbol}@depth`
Maybe today I'll check `/stream` endpoint

**Comment by Majestry** [comment]
Same problem here.
I write my pet-project to fetch the data from moonraker (firmware for the 3D printers), and it offers the websocket only via ws:// protocol.

My code is quite simple: here is where Client is declared

```
@Inject
@Client("ws://192.168.0.19:7125/")
RxWebSocketClient client;
```

And exactly this will produce the next error:

```
Message: Invalid service reference [ws://192.168.0.19:7125/] specified to @Client
Path Taken: new $HelloWorld$Definition$Intercepted(BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> $HelloWorld$Definition$Intercepted.helloService --> HelloServiceImpl.client
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.example.service.impl.HelloServiceImpl]

Message: Invalid service reference [ws://192.168.0.19:7125/] specified to @Client
Path Taken: new $HelloWorld$Definition$Intercepted(BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> $HelloWorld$Definition$Intercepted.helloService --> HelloServiceImpl.client
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2265)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2834)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2725)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2685)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1555)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1561)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1549)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1259)
	at com.example.service.impl.$HelloServiceImpl$Definition.injectBean(Unknown Source)
	at com.example.service.impl.$HelloServiceImpl$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2834)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2725)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2685)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1555)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1561)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1549)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1259)
	at com.example.web.$HelloWorld$Definition.injectBean(Unknown Source)
	at com.example.web.$HelloWorld$Definition$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2723)
	at io.micronaut.context.DefaultBeanContext.access$100(DefaultBeanContext.java:75)
	at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:460)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:503)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$15(RouteExecutor.java:605)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
	at reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:93)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8388)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:574)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:439)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:139)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:211)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:123)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.http.client.exceptions.HttpClientException: Invalid service reference [ws://192.168.0.19:7125/] specified to @Client
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.lambda$null$0(DefaultNettyHttpClientRegistry.java:330)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.lambda$getClient$1(DefaultNettyHttpClientRegistry.java:329)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.getClient(DefaultNettyHttpClientRegistry.java:292)
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.getClient(DefaultNettyHttpClientRegistry.java:174)
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.resolveDefaultHttpClient(DefaultNettyHttpClientRegistry.java:485)
	at io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.resolveWebSocketClient(DefaultNettyHttpClientRegistry.java:288)
	at io.micronaut.rxjava2.http.client.websockets.RxWebSocketClientFactory.webSocketClient(RxWebSocketClientFactory.java:61)
	at io.micronaut.rxjava2.http.client.websockets.$RxWebSocketClientFactory$WebSocketClient0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:707)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2225)
	... 97 common frames omitted
```


Unfortunately, the 3d firmware do not offer data via http(s).
