### ISSUE TITLE
Regression 3.0.0-M3: NoClassDefFoundError: io/reactivex/Flowable when calling REST controllers on servlet runtimes

### ISSUE THREAD

**Issue by tobiasschaefer** [micronaut-projects/micronaut-core#5838]
I updated from Micronaut 3.0.0-M2 to 3.0.0-M3 but now I run into `java.lang.ClassNotFoundException: io.reactivex.FlowableEmitter` when calling a REST controller running on Tomcat, Undertow, or Jetty. It works on Netty.

Note: the error still occurs on 3.0.0-M4 and 3.0.0-SNAPSHOT

This might be related to micronaut-servlet (seeing that all servlet containers are affected), however the regression appears when updating Micronaut Core. This is probably also related to #5607 which has a comment about RxJava.

As a workaround it can be fixed with `implementation("io.reactivex.rxjava2:rxjava")`

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new project with Micronaut 3.0.0-M4
2. Switch to runtime "jetty" (or "undertow" or "tomcat")
3. Implement a REST controller which simply returns a string.
4. Call the REST controller via Unit-Test or curl

### Expected Behaviour

The REST controller should simply return the string.

### Actual Behaviour

An exception is thrown:

```
java.lang.NoClassDefFoundError: io/reactivex/Flowable
	at io.micronaut.servlet.http.ServletHttpHandler.buildResponsePublisher(ServletHttpHandler.java:521)
	at io.micronaut.servlet.http.ServletHttpHandler.invokeRouteMatch(ServletHttpHandler.java:361)
	at io.micronaut.servlet.http.ServletHttpHandler.service(ServletHttpHandler.java:206)
	at io.micronaut.servlet.engine.DefaultServletHttpHandler.service(DefaultServletHttpHandler.java:53)
	at io.micronaut.servlet.engine.DefaultMicronautServlet.service(DefaultMicronautServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: io.reactivex.Flowable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 common frames omitted
```

### Environment Information

- **Operating System**: MacOS 11.4
- **Micronaut Version:** 3.0.0-M4 (works on 3.0.0-M2)
- **JDK Version:** 11

### Example Application

- https://github.com/tobiasschaefer/httptest

**Comment by graemerocher** [comment]
This requires https://github.com/micronaut-projects/micronaut-core/pull/5837

**Comment by tobiasschaefer** [comment]
Confirmed: Updating to 3.0.0-SNAPSHOT fixes the bug
