### ISSUE TITLE
No Session found for current thread in a test using GORM

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#586]
I am getting a `No Session found for current thread` error while trying to test multitenancy with and token propagation. 

I've added these dependencies to [build.gradle](https://github.com/micronaut-projects/micronaut-core/blob/multitenancy-gorm/configurations/multitenancy-gorm/build.gradle)

```
ext {
    h2Version = '1.4.196'
    tomcatJdbcVersion = '8.5.28'
}

dependencies {
...
  testCompile project(":configurations:hibernate-validator")
    testCompile project(":configurations:hibernate-gorm")
    testCompile "org.grails:grails-datastore-gorm-hibernate5:$gormVersion"
    testRuntime "com.h2database:h2:$h2Version"
    testRuntime "org.apache.tomcat:tomcat-jdbc:$tomcatJdbcVersion"
}
```

I've a [domain class](https://github.com/micronaut-projects/micronaut-core/blob/multitenancy-gorm/configurations/multitenancy-gorm/src/test/groovy/io/micronaut/multitenancy/gorm/principal/Book.groovy)

```import grails.gorm.MultiTenant
import grails.gorm.annotation.Entity
import org.grails.datastore.gorm.GormEntity

@Entity
class Book implements GormEntity<Book>, MultiTenant<Book> {
    String title
    String username

    static mapping = {
        tenantId name:'username'
    }
}
```

I've a [GORM Data service](https://github.com/micronaut-projects/micronaut-core/blob/multitenancy-gorm/configurations/multitenancy-gorm/src/test/groovy/io/micronaut/multitenancy/gorm/principal/BookService.groovy): 

```
import io.micronaut.context.annotation.Requires
import grails.gorm.multitenancy.CurrentTenant
import grails.gorm.services.Service

@Requires(property = 'spec.name', value = 'multitenancy.principal.gorm')
@Service(Book)
@CurrentTenant
interface BookService {
    List<Book> list()
    Book save(String title)
}
````

and the [next configuration](https://github.com/micronaut-projects/micronaut-core/blob/multitenancy-gorm/configurations/multitenancy-gorm/src/test/groovy/io/micronaut/multitenancy/gorm/principal/PrincipalTenantResolverSpec.groovy): 

```
        given:
        Map gormConfig = [
                'micronaut.server.port'                       : gormPort,
                (SPEC_NAME_PROPERTY)                          : 'multitenancy.principal.gorm',
                'grails.gorm.multiTenancy.mode'               : 'DISCRIMINATOR',
                'grails.gorm.multiTenancy.tenantResolverClass': 'io.micronaut.multitenancy.gorm.PrincipalTenantResolver',
                'micronaut.security.enabled': true,
                'micronaut.security.token.jwt.enabled': true,
                'micronaut.security.token.jwt.signatures.secret.generator.secret': 'pleaseChangeThisSecretForANewOne',
                'hibernate.hbm2ddl.auto'                      : 'create-drop',
                'datasources.default.url'                     :'jdbc:h2:mem:principalGormDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE',
                'datasources.default.username'                :'sa',
                'datasources.default.password'                :'',
                'datasources.default.driverClassName'         :'org.h2.Driver',
        ]

        gormEmbeddedServer = ApplicationContext.run(EmbeddedServer, gormConfig, Environment.TEST)
```

Any idea what am I missing to use GORM for Hibernate in such a test?

### Environment Information

- **Operating System**: Mac OS HighSierra
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:**  1.8.0_181"

### Example Application

https://github.com/micronaut-projects/micronaut-core/blob/multitenancy-gorm/configurations/multitenancy-gorm/src/test/groovy/io/micronaut/multitenancy/gorm/principal/PrincipalTenantResolverSpec.groovy

Stacktrace:

```
Internal Server Error: No Session found for current thread
io.micronaut.http.client.exceptions.HttpClientResponseException: Internal Server Error: No Session found for current thread
	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1671)
	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1612)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:187)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by emmanuj** [comment]
Seeing this issue too. Using Micronaut 1.1.0. My classes are similar to @sdelamo  without multitancy. Simply injecting a service that uses GormDataService will give this error.

**Comment by puneetbehl** [comment]
@sdelamo The links to the sample application and other references are not working.

**Comment by emmanuj** [comment]
Looks like it works when I remove `@MicronautTest.` I'm running the tests from this guide (https://guides.micronaut.io/micronaut-database-authentication-provider-groovy/guide/index.html). Those tests did not have the annotation but I included one in mine and was getting this error. I'm a little confused as to when we need `@MicronautTest` and when we don't.

**Comment by puneetbehl** [comment]
@emmanuj There has been a recent fix I made in the GORM related to a similar problem. However, I need to test it. I will soon update you on this.

**Comment by puneetbehl** [comment]
@sdelamo This seems to be fixed with the latest GORM version `6.1.12`. Please see 
[hello-hibernate-gorm.zip](https://github.com/micronaut-projects/micronaut-core/files/3171597/hello-hibernate-gorm.zip)

@emmanuj It should also work with `@MicronautTest`. I think you might be missing `@Transactional` on the service method. See "Using GORM for Hibernate" section in [Micronaut-Groovy](https://micronaut-projects.github.io/micronaut-groovy/latest/guide/#gorm). Please try with the attached sample application and let me know if you still see the issues.

**Comment by puneetbehl** [comment]
@emmanuj FYI, I just tried to update tests with `@MicronautTest` in the micronaut-database-authentication-provider guide and everything works fine.

**Comment by emmanuj** [comment]
No longer seeing this issue. It is possible I was not using `@Transactional` at the time.

**Comment by kevintanhongann** [comment]
I was doing this query on hibernate-gorm 2.2.0 and get this error as well.

`def merchant = Merchant.where {
        account.email == emailOptional.get()
      }.get()`
