### ISSUE TITLE
Optional NettyHttpServerConfiguration::getPort() Missing?

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#602]
Using `1.0.0.BUILD-SNAPSHOT`, I am hitting an exception on startup.

I suspect it started happening after [this commit](https://github.com/micronaut-projects/micronaut-core/commit/2193a3af9125ae270a794c11971d741a1a719c38). I cleared my Gradle cache in case I was using old dependencies but it didn't seem to help. 

```
Message: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration.getPort()Ljava/util/Optional;
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,Router router,RequestArgumentSatisfier requestArgumentSatisfier,[MediaTypeCodecRegistry mediaTypeCodecRegistry],NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1272)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1753)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1523)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1503)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:879)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:511)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:133)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
	at com.vercettie.basement.BasementApplication.main(BasementApplication.java:7)
Caused by: java.lang.NoSuchMethodError: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration.getPort()Ljava/util/Optional;
	at io.micronaut.http.server.netty.NettyHttpServer.<init>(NettyHttpServer.java:185)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1258)
	... 10 more
```

**Comment by RyanHoldren** [comment]
Never mind, it's my mistake. I was only clearing the Gradle cache of my root project, and not subprojects.

```
find -type d -name .gradle -exec rm -rf "{}" \;
```
