### ISSUE TITLE
Uploading file "Required argument [CompletedFileUpload file] not specified"

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#612]
I am writing an app which uploads a file to S3. 

The Controller has this signature: 

https://github.com/micronaut-guides/micronaut-file-upload/blob/master/complete/src/main/java/example/micronaut/HomeController.java#L36

`public Map<String, Object> upload(CompletedFileUpload file) {`

The view has this form: 

https://github.com/micronaut-guides/micronaut-file-upload/blob/master/complete/src/main/resources/views/home.vm#L19

```
  <form method="post" action="/upload" enctype="multipart/form-data">
        <fieldset>
            <ol>
                <li><label for="file">File</label>: <input type="file" name="file" id="file"></li>
                <li><input type="submit" value="Upload"/></li>
            </ol>
        </fieldset>
    </form>
```

### Steps to Reproduce

Clone repository: https://github.com/micronaut-guides/micronaut-file-upload
$ cd complete
complete $ export AWS_S3_REGION=eu-west-3
complete $ export AWS_SECRET_KEY=XXXXXX
complete $ export AWS_S3_BUCKET=bucketname
complete $ export AWS_ACCESS_KEY_ID=XXXXXX
complete $ ./gradlew run

Go to `localhost:8080`. Select a file to upload. E.g.  `src/test/resources/blacklogo.png`. Click upload.  

### Expected Behaviour

File uploads.

### Actual Behaviour

This exception is thrown: 

```
11:52:57.478 [nioEventLoopGroup-1-2] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [CompletedFileUpload file] not specified
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:280)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$12(RoutingInBoundHandler.java:1202)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14429)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: macOS High Sierra
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_181

### Example Application

https://github.com/micronaut-guides/micronaut-file-upload

**Comment by sdelamo** [comment]
Seems to be an issue with Safari cache. I clear web content data and the issue seems to have resolved.

**Comment by riburajan** [comment]
Hi,
I am facing the same issue, please see the attached screenshot. File is already attached, but when sending the post request, its saying **"Required Part [file] not specified"**. 

Below is the code using for Post request.
`    

    //POST REQUEST
    @Post(value = "/upload",consumes = {MediaType.MULTIPART_FORM_DATA})
    public boolean uploadFile(@Part  CompletedFileUpload file) throws IOException 
    {
        s3Adapter.uploadFile(file.getFilename(),file.getBytes());
        return true; 
    }

`
If anyone resolved the same, pls share the details.

Thanks

<img width="669" alt="image" src="https://github.com/micronaut-projects/micronaut-core/assets/94977917/361cd1a0-0673-4c7e-a3b1-2fae7339fd5e">

**Comment by buuraak** [comment]
> Hi, I am facing the same issue, please see the attached screenshot. File is already attached, but when sending the post request, its saying **"Required Part [file] not specified"**.
> 
> Below is the code using for Post request. `
> 
> ```
> //POST REQUEST
> @Post(value = "/upload",consumes = {MediaType.MULTIPART_FORM_DATA})
> public boolean uploadFile(@Part  CompletedFileUpload file) throws IOException 
> {
>     s3Adapter.uploadFile(file.getFilename(),file.getBytes());
>     return true; 
> }
> ```
> 
> ` If anyone resolved the same, pls share the details.
> 
> Thanks
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/94977917/283543933-361cd1a0-0673-4c7e-a3b1-2fae7339fd5e.png">

I think the key should be matching to the parameter name. So replacing `screenshot1` to `file` in your Postman should be the fix.

**Comment by chandankumarjena** [comment]
@riburajan , @buuraak . Did you guy able to fix the issue u faced... I am facing same issue. Not sure how to fix.

**Comment by riburajan** [comment]
When you select the file in Postman, you need to specify the parameter name.
In this case, if you are using @Part CompletedFileUpload file, So, set the parameter name as 'file'.

**Comment by chandankumarjena** [comment]
Actually it was working earlier . as we moved to Micronaut 4 and JDK17.. it starts failing the peculiar thing is it is working in local but failing in remote. 

below is the code sinppet.
@Post(value = "/", consumes = {MediaType.IMAGE_PNG, MediaType.TEXT_XML, MediaType.MULTIPART_FORM_DATA})
    public HttpResponse<ConfirmMessage> createTerminalDocumentFile(@Body("multipartBody") byte[] multipartBody, @Header("documentId") String documentId, @Header("Content-Type") String contentType, HttpRequest<?> request) {
}
  
local- working fine
env- Required Body [multipartBody] not specified


Not sure where is the failure point.

**Comment by blazejkarmelita** [comment]
I'm facing the same issue with Micronaut 4.7 and **4.8** and **JDK17** when **deployed to the AWS Cloud**. I have generated the sample app using **Micronaut Launcher**, Java 17 and Maven with 2 features: **aws-lambda** and **aws-cdk** features. I have replaced the generated code with the example File Upload code published with official Micronaut documentation. I works locally but it fails once deployed to AWS Cloud with the same error as posted above.

**Comment by yawkat** [comment]
@blazejkarmelita lambda does not support multipart, sorry
