### ISSUE TITLE
Exception with message "No identifier specified for entity" is thrown at startup of a Docker native image

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#6220]
### Expected Behavior

Application should startup correctly as when it was happening in the previous versions (before `3`)

### Actual Behaviour

Application throws the following exception
```
ERROR i.m.c.h.jpa.EntityManagerFactoryBean - Hibernate mapping error
org.hibernate.AnnotationException: No identifier specified for entity: com.mycompany.micronautjpamysql.model.Book
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:783)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactoryBuilder(EntityManagerFactoryBean.java:188)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2723)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2685)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1555)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1052)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2555)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1834)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3362)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:243)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at com.mycompany.micronautjpamysql.Application.main(Application.java:8)
ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: com.mycompany.micronautjpamysql.model.Book
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: com.mycompany.micronautjpamysql.model.Book
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1840)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3362)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:243)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at com.mycompany.micronautjpamysql.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: com.mycompany.micronautjpamysql.model.Book
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2265)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2723)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2685)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1555)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1052)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3193)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3179)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2555)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1834)
	... 8 common frames omitted
Caused by: org.hibernate.AnnotationException: No identifier specified for entity: com.mycompany.micronautjpamysql.model.Book
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:783)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactoryBuilder(EntityManagerFactoryBean.java:188)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2238)
	... 21 common frames omitted
```

### Steps To Reproduce

- git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git
- cd graalvm-quarkus-micronaut-springboot/jpa-mysql
- docker-compose up -d
- cd micronaut-jpa-mysql
- ./mvnw clean package -Pgraalvm -Dpackaging=docker-native -Djib.to.image=ivanfranchin/micronaut-jpa-mysql-native:1.0.0
- run the docker native container
  ```
  docker run --rm --name micronaut-jpa-mysql-native \
    -p 9089:8080 -e MICRONAUT_ENVIRONMENTS=native -e MYSQL_HOST=mysql \
    --network jpa-mysql_default \
    ivanfranchin/micronaut-jpa-mysql-native:1.0.0
  ```

### Environment Information

- Mac OS X
- Java 11

### Example Application

https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/jpa-mysql/micronaut-jpa-mysql

### Version

3.0.1

**Comment by ilopmar** [comment]
We have a test application for that. Can you please compare it with yours? https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.0.x_mysql

**Comment by ivangfr** [comment]
Hi @ilopmar , thanks for your response.

I've tried to find something wrong in my app. But, no success.

Then, I've created from zero on `micronaut.io` two identical apps that uses `micronaut-data` and `MySQL`. The only difference between them is that one uses `Maven` and another `Gradle`.

These apps use `micronaut` version `3.0.2` and `micronaut-data` `3.0.0` (version default from `micronaut.io`)

The interesting thing is that the `Gradle` one works. On the other hand, the `Maven` one throws the same error I've mentioned in this ticket.

I've also noticed that the `Gradle` app just works when using `MySQL` `8`. It doesn't work with `5.7`.

![micronaut-data-compare](https://user-images.githubusercontent.com/10564548/134946220-910bacd2-dcc7-4c21-bac0-244f355f6182.gif)

**Comment by ivangfr** [comment]
Btw, another update... As `micronaut.io` doesn't include the following lines in `pom.xml` it generates
```
    <dependencies>
        ...
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>svm</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <scope>provided</scope>
        </dependency>
    ...
    <dependencies>
```
and the artifactId `micronaut-graal` in the `annotationProcessorPaths`
```
    <build>
        <plugins>
            ...
            <plugin>
                    ...                    
                    <annotationProcessorPaths combine.self="override">
                        ...
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-graal</artifactId>
                            <version>${micronaut.version}</version>
                        </path>
                        ...
                    </annotationProcessorPaths>
                    ...
            </plugin>
            ...
        </plugins>
    </build>
```
I've removed them from all my `micronaut` apps. All of them works fine, except for `micronaut-jpa-mysql`.

When I set the dependencies and the path back to `micronaut-jpa-mysql`, the app works fine.

**Comment by ilopmar** [comment]
I've converted our Micronaut Data-JPA MySQL app to use Maven using the `pom.xml` generated with this configuration from Launch: https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=MAVEN&test=JUNIT&features=data-jpa&features=mysql&version=3.0.2

I've tried building the application with GraalVM directly in my computer:

```
$ ./mvnw package -Dpackaging=native-image


$ ./target/demo 
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.2)

13:49:31.863 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
13:49:31.883 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
13:49:31.883 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.5.3.Final
13:49:31.884 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
13:49:31.885 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
Hibernate: create table hibernate_sequence (next_val bigint) engine=InnoDB
Hibernate: insert into hibernate_sequence values ( 1 )
Hibernate: create table owner (id bigint not null, age integer not null, name varchar(255), primary key (id)) engine=InnoDB
Hibernate: create table pet (id binary(255) not null, name varchar(255), type integer, owner_id bigint, primary key (id)) engine=InnoDB
Hibernate: alter table pet add constraint FK7qfti9yba86tgfe9oobeqxfxg foreign key (owner_id) references owner (id)
13:49:32.002 [main] INFO  example.Application - Populating data
Hibernate: select next_val as id_val from hibernate_sequence for update
Hibernate: update hibernate_sequence set next_val= ? where next_val=?
Hibernate: select next_val as id_val from hibernate_sequence for update
Hibernate: update hibernate_sequence set next_val= ? where next_val=?
Hibernate: insert into owner (age, name, id) values (?, ?, ?)
Hibernate: insert into owner (age, name, id) values (?, ?, ?)
Hibernate: insert into pet (name, owner_id, type, id) values (?, ?, ?, ?)
Hibernate: insert into pet (name, owner_id, type, id) values (?, ?, ?, ?)
Hibernate: insert into pet (name, owner_id, type, id) values (?, ?, ?, ?)
13:49:32.096 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 260ms. Server Running: http://localhost:8080
Hibernate: select pet0_.id as id1_1_0_, owner1_.id as id1_0_1_, pet0_.name as name2_1_0_, pet0_.owner_id as owner_id4_1_0_, pet0_.type as type3_1_0_, owner1_.age as age2_0_1_, owner1_.name as name3_0_1_ from pet pet0_ inner join owner owner1_ on pet0_.owner_id=owner1_.id where pet0_.name=?
Hibernate: select pet0_.name as col_0_0_ from pet pet0_ limit ?
Hibernate: select owner0_.id as id1_0_, owner0_.age as age2_0_, owner0_.name as name3_0_ from owner owner0_
Hibernate: select owner0_.id as id1_0_, owner0_.age as age2_0_, owner0_.name as name3_0_ from owner owner0_ where owner0_.name=?
```

These are the curl requests: 
```
$ curl localhost:8080/pets/Dino
{"id":"ba9651af-7d62-438a-960f-5094467cbb72","name":"Dino","owner":{"id":1,"name":"Fred","age":45},"type":"DOG"}

$ curl localhost:8080/pets     
[{"name":"Baby Puss"},{"name":"Hoppy"},{"name":"Dino"}]

$ curl localhost:8080/owners
[{"id":1,"name":"Fred","age":45},{"id":2,"name":"Barney","age":40}]

$ curl localhost:8080/owners/Fred
{"id":1,"name":"Fred","age":45}
```

I've also tried build the app inside Docker:

```
$ ./mvnw clean package -Pgraalvm -Dpackaging=docker-native -Djib.to.image=micronaut-jpa-mysql-native:1.0.0

$ docker run -it --rm -p 8080:8080 -e DATASOURCES_DEFAULT_URL=jdbc:mysql://172.17.0.2:3306/pets micronaut-jpa-mysql-native:1.0.0
```

And it also works.

P.S: I start MySQL with:

```
docker run -it --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=pets mysql:8.0.20
```

You can find the app here https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.0.x_mysql_maven

**Comment by ivangfr** [comment]
Hi @ilopmar Thanks for the example and the change you did including Maven.

Indeed, your project works! I've tested it on my machine.

However, I've spent already some time on my project trying to understand why it's not working. It works, for sure, if I add the dependencies `svm` and `graal-sdk` and also the annotationProcessorPaths `micronaut-graal`.

Besides, my project has more dependencies than yours like Mapstruct, Lombok, etc.

I will redo my project from zero adding the dependencies one by one in order to see when it starts to fail.

Thanks for the support so far.

Best regards

**Comment by ilopmar** [comment]
Just to be clear because I'm not 100% sure. If you add the `svm` and `graal-sdk` dependencies that now are not generated in Launch, does your project work?
I don't remember why or when we removed that for Maven. For Gradle they're not necessary because our plugin adds them, but for Maven I think they are mandatory because we can't add that config on-the-fly with Maven. Maybe that's the real bug and we need to add them back. This doesn't explains why it works in my project that don't have those dependencies.

Regarding Mapstruct or Lombok, maybe any of them is the problem. You need to be sure that they are executed **before** Micronaut compilation. In Gradle you do that declaring the dependencies before the micronaut dependencies (in the `annotationProcessor` scope), but I'm not sure if that fixes the problem in Maven.

**Comment by ivangfr** [comment]
Exactly, the project works by adding the `svm` and `graal-sdk` dependencies.

I've just pushed a new [commit](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/commit/3e34458bf70952dc7a7f851969918d1b627e62df) with the fix in the `pom.xml` of `micronaut-jpa-mysql` project.

P.S. I am using, in this project, **micronaut** and **micronaut-data** version `3.0.1`. But, I've been trying also with the **micronaut** `3.0.2` and **micronaut-data** `3.0.0`

**Comment by ilopmar** [comment]
So the problem here is that we removed the dependencies for Maven and we shouldn't. I'll fix it.
