### ISSUE TITLE
Jackson + Records requires reflection configuration

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#6277]
### Expected Behavior

Should work without reflection configuration

### Actual Behaviour

Fails with:

```
Caused by: java.lang.IllegalArgumentException: Failed to access RecordComponents of type `java17test.Book`
        at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.recordComponents(JDK14Util.java:124)
        at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.getRecordFieldNames(JDK14Util.java:78)
        at com.fasterxml.jackson.databind.jdk14.JDK14Util.getRecordFieldNames(JDK14Util.java:27)
        at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$RecordNaming.<init>(DefaultAccessorNamingStrategy.java:531)
        at com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$Provider.forRecord(DefaultAccessorNamingStrategy.java:448)
        at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:185)
        at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:86)
        at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
        at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:862)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:139)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1473)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1421)
        ... 35 common frames omitted
```

### Steps To Reproduce

1. Create a JDK 17 Record and annotate it with `@Introspected`
2. Serialize to JSON

### Version

3.0.3

**Comment by yawkat** [comment]
For future reference, there is another exception when deserializing:

```
Caused by: java.lang.IllegalArgumentException: Failed to access RecordComponents of type `core6277.Rec`
        at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.recordComponents(JDK14Util.java:124)
        at com.fasterxml.jackson.databind.jdk14.JDK14Util$RecordAccessor.getRecordFields(JDK14Util.java:94)
        at com.fasterxml.jackson.databind.jdk14.JDK14Util$CreatorLocator.<init>(JDK14Util.java:155)
        at com.fasterxml.jackson.databind.jdk14.JDK14Util.findRecordConstructor(JDK14Util.java:32)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:287)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
        ... 12 more
```
