### ISSUE TITLE
AbstractConcurrentCustomScope eats exceptions

### ISSUE THREAD

**Issue by Paullo612** [micronaut-projects/micronaut-core#6343]
### Expected Behavior

When extending `io.micronaut.context.scope.AbstractConcurrentCustomScope`, it is expected that exception thrown from `io.micronaut.context.scope.AbstractConcurrentCustomScope#getOrCreate` is propagated downstream (expected just because `io.micronaut.context.scope.BeanCreationContext#create` has `throws BeanCreationException` in its signature, and none of existing `AbstractConcurrentCustomScope` subclasses handles that).

Expected test application output:
```
Got bean creation exception.
Got bean creation exception.
```

### Actual Behaviour

Any exception that is thrown from `io.micronaut.context.scope.AbstractConcurrentCustomScope#doCreate` is eaten by non-locked lock unlock.

Actual test application output:
```
Got bean creation exception.
java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:444)
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:428)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:881)
	at io.micronaut.context.scope.AbstractConcurrentCustomScope.getOrCreate(AbstractConcurrentCustomScope.java:152)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2899)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2827)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1428)
	at com.github.paullo612.micronaut.$App$MyBean1$Definition$Intercepted.interceptedTarget(Unknown Source)
	at com.github.paullo612.micronaut.$App$MyBean1$Definition$Intercepted.printHelloWorld(Unknown Source)
	at com.github.paullo612.micronaut.App.main(App.java:141)
```

### Steps To Reproduce

Run test application.

### Environment Information

- Operation System: `Ubuntu 20.04`
- JDK Version: `1.8.0_292-8u292-b10-0ubuntu1~20.04-b10`

### Example Application

https://github.com/Paullo612/micronaut-scopes/tree/bug_6343

### Version

3.1.0

**Comment by graemerocher** [comment]
Thanks for the reports, the area of custom scopes was re-worked for 3.x so seems we have some issues with the new impl
