### ISSUE TITLE
Custom scopes and conditional beans

### ISSUE THREAD

**Issue by Paullo612** [micronaut-projects/micronaut-core#6348]
### Expected Behavior

I expected that I could conditionally enable or disable custom scoped beans depending on current scope state using `@Requires(condition = ...)` and custom `io.micronaut.context.condition.Condition` implementation in conjunction with `jakarta.inject.Provider`.

A real world example could be: Imagine we're writing car driving application. We want to support multiple car models. Then we introduce `CarScope`. Car model is stored in scope key as enum value. Now, we can conditionally enable or disable implementation details depending on car model (multiple cars of the same brand can have common implementations). Moreover, you can disable `Drive` bean while car's engine is not started, but sill enable `Radio` bean unconditionally (oh, if you have enough accumulator power to turn the radio on).

Expected test application output:

```
Bean1 constructor
Condition test!
Condition test!
Bean is present.
Condition test!
Condition test!
Bean is unique.
Condition test!
Condition test!
Condition test!
Condition test!
Hello World!
Bean2 constructor
Condition test!
Condition test!
Condition test!
Condition test!
Hello World!
```

### Actual Behaviour

Looks like Micronaut resolves conditions on `Provider` injection, and also when actual Provider's `get()` is called. When using `io.micronaut.context.BeanProvider`, `BeanProvider` is injected properly (it evaluates `@Requires` condition, condition tells that bean is disabled, as there is no custom scope present at injection time, and then reports that bean is not present from `io.micronaut.context.BeanProvider#isPresent` call, but `io.micronaut.context.BeanProvider#get()` is able to successfully retrieve the bean). When using `jakarta.inject.Provider`, `@Requires` is evaluated at provider injection time, condition fails and `BeanInstantiationException` is thrown.

Actual test application output:

```
Condition test!
Condition test!
Bean1 constructor
Bean is NOT present.
Condition test!
Condition test!
Bean is unique.
Condition test!
Condition test!
Condition test!
Condition test!
Hello World!
Exception in thread "main" io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.github.paullo612.micronaut.App$MyBean2]

Message: No bean of type [com.github.paullo612.micronaut.App$MyHelloWorldPrinter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new MyBean2(Provider myHelloWorldPrinterProvider,MyCustomScope myCustomScope) --> new MyBean2([Provider myHelloWorldPrinterProvider],MyCustomScope myCustomScope)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2368)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2932)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2827)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2787)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1643)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1566)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1044)
	at com.github.paullo612.micronaut.$App$MyBean2$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2341)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3289)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3275)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2825)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2787)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:893)
	at com.github.paullo612.micronaut.App.main(App.java:205)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.github.paullo612.micronaut.App$MyHelloWorldPrinter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.inject.provider.AbstractProviderDefinition.build(AbstractProviderDefinition.java:166)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2341)
	... 14 more
```

### Steps To Reproduce

Run test application.

### Environment Information

- Operation System: `Ubuntu 20.04`
- JDK Version: `1.8.0_292-8u292-b10-0ubuntu1~20.04-b10`

### Example Application

https://github.com/Paullo612/micronaut-scopes/tree/bug_6348

### Version

3.1.0

**Comment by graemerocher** [comment]
Triage: the report identifies a real semantic difference between `BeanProvider` and `jakarta.inject.Provider`. Current `BeanProviderDefinition` always allows an empty provider, while `JakartaProviderBeanDefinition` honors `BeanContextConfiguration.isAllowEmptyProviders()` (false by default) and therefore checks `containsBean` during injection. Suggested resolution is either to make the behavior explicit in the provider documentation, or align Jakarta Provider with lazy lookup/`allowEmptyProviders` semantics and add a custom-scope plus `@Requires` regression test.
