### ISSUE TITLE
HttpResponse.badRequest() throws exception if controller returns HttpResponse<Flux<byte[]>>

### ISSUE THREAD

**Issue by LPalmerMSI** [micronaut-projects/micronaut-core#6358]
### Expected Behavior

When a controller returns an HttpResponse<Flux<byte[]>>, HttpResponse.badRequest(), .unauthroized() and other convenience methods should be valid returns without throwing an exception.

### Actual Behaviour

An Exception is thrown:
```
17:38:38.199 [io-executor-thread-4] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Argument [object] cannot be null
java.lang.NullPointerException: Argument [object] cannot be null
    at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    at io.micronaut.core.async.publisher.Publishers.convertPublisher(Publishers.java:408)
```

**NOTE** This worked correctly in 2.5.  This changed in 3.1.

### Steps To Reproduce

Create a controller with a method returning HttpResponse<Flux<byte[]>>.
Return HttpResponse.badRequest();

Observer Exception. 

### Environment Information

Windows 10
Java 11
Spock Unit Test. 

### Version

3.1.0

**Comment by jameskleeh** [comment]
Can you please include more of the stacktrace or an example app?

**Comment by LPalmerMSI** [comment]
11:58:07.221 [io-executor-thread-4] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Argument [object] cannot be null
java.lang.NullPointerException: Argument [object] cannot be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at io.micronaut.core.async.publisher.Publishers.convertPublisher(Publishers.java:408)
	at io.micronaut.http.server.RouteExecutor.processPublisherBody(RouteExecutor.java:798)
	at io.micronaut.http.server.RouteExecutor.toMutableResponse(RouteExecutor.java:578)
	at io.micronaut.http.server.RouteExecutor.lambda$createResponseForBody$19(RouteExecutor.java:768)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:57)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
