### ISSUE TITLE
HTTP POST Request with String body fails

### ISSUE THREAD

**Issue by bzolivereckle** [micronaut-projects/micronaut-core#6436]
### Expected Behavior

Request is send correctly without any error

### Actual Behaviour

I get a very strange exception

```
io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class io.netty.buffer.UnpooledHeapByteBuf]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
at io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:117)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:117)
at io.micronaut.core.beans.BeanMap.of(BeanMap.java:47)
at io.micronaut.http.client.netty.DefaultHttpClient.buildFormDataRequest(DefaultHttpClient.java:2616)
at io.micronaut.http.client.netty.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1635)
at io.micronaut.http.client.netty.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1972)
at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$36(DefaultHttpClient.java:1243)
at io.micronaut.http.client.netty.DefaultHttpClient.lambda$addInstrumentedListener$59(DefaultHttpClient.java:2975)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:831)
```

Request setup

```
        val body = credentials.scope?.let { "grant_type=client_credentials&scope=${credentials.scope}" } ?: "grant_type=client_credentials"
        return HttpRequest.POST(credentials.authUrl, body)
            .basicAuth(credentials.clientId, credentials.secret)
            .contentType(MediaType.APPLICATION_FORM_URLENCODED_TYPE)
            .accept(MediaType.APPLICATION_JSON_TYPE)
```

Using RxJava2

```
    implementation("io.micronaut.rxjava2:micronaut-rxjava2")
    implementation("io.micronaut.rxjava2:micronaut-rxjava2-http-client")
    implementation("io.micronaut.rxjava2:micronaut-rxjava2-http-server-netty")
```

btw the only thing we changed is upgrading from micronaut 3.0.2 to 3.1.1

### Steps To Reproduce

Create HTTP Post Request
Call RxHttpClient.exchange

### Environment Information

- Windows
- JDK 16 (OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7))
- Gradle 7.1
- Kotlin 1.5.31 

### Version

3.1.1

**Comment by jameskleeh** [comment]
What is the class of `body` in your case? We check for string based bodies already here:

https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L1654

**Comment by bzolivereckle** [comment]
Hey @jameskleeh as mentioned somewhere in the text, the body is of type String. It also works with 3.0.2 and all we did was upgrading to 3.1.1 so i guess there must be some change in between? I am also not shure who creates the UnpooledHeapByteBuf. Looks like a netty thing. I am 100% shure we create no UnpooledHeapByteBuf.

**Comment by bzolivereckle** [comment]
Just one more thing: after investigating a little, i am very shure, the mentioned code is processed.
Cause ```charSequenceToByteBuf``` creates the ```UnpooledHeapByteBuf``` where the introspection is complaining about.

**Comment by yawkat** [comment]
Can you please provide more details to help us reproduce this? I built a very simple test project with similar client code, and it works fine:

```java
RxHttpClient client = ctx.getBean(RxHttpClient.class);
HttpRequest<?> request = HttpRequest.POST("http://localhost:8080", "foo=bar")
        .basicAuth("ab", "cd")
        .contentType(MediaType.APPLICATION_FORM_URLENCODED_TYPE)
        .accept(MediaType.APPLICATION_JSON_TYPE);
client.exchange(request, String.class).subscribe(resp -> LoggerFactory.getLogger(Application.class).info(resp.body()));
```

**Comment by bzolivereckle** [comment]
@yawkat i realy like to provide you some more details. the issue occurs within a huge project so its difficult for me to put out the right pices for you. 

What also seems strange to me, is that the exception complains about ```DefaultHttpClient.java:1635``` which is not the branch for handling the strings. But its a string ... So any idea is appreciated

**Comment by bzolivereckle** [comment]
Just to give a little more information regarding current status. We went into some debugging and figured out, that while the exchange the code arount ```DefaultHttpClient.java:1630``` is called twice. The first time the body is a string as expected. The second time its that mysterious Buffer that fails.

**Comment by jameskleeh** [comment]
Is it redirecting?

**Comment by bzolivereckle** [comment]
![image](https://user-images.githubusercontent.com/48242686/139246126-3495912d-c99f-4abd-b223-1838385661af.png)

**Comment by bzolivereckle** [comment]
And the second call
![image](https://user-images.githubusercontent.com/48242686/139246583-6143fc1a-0353-4123-86f9-f25402c6a5a0.png)

**Comment by bzolivereckle** [comment]
What i also found in the logs is that the call seems to produce a correct 200 response

``` 
2021-10-28 11:21:09,979 [multithreadEventLoopGroup-4-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP POST to https://abc/token
2021-10-28 11:21:10,033 [multithreadEventLoopGroup-4-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from https://abc/token
2021-10-28 11:21:10,108 [consumer-executor-thread-1] ERROR MyAPI - Failed to renew token
io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class io.netty.buffer.UnpooledHeapByteBuf]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:117)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:117)
	at io.micronaut.core.beans.BeanMap.of(BeanMap.java:47)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildFormDataRequest(DefaultHttpClient.java:2616)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1635)
	at io.micronaut.http.client.netty.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1972)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$36(DefaultHttpClient.java:1243)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$addInstrumentedListener$59(DefaultHttpClient.java:2975)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by yawkat** [comment]
Are you sure the two requests are related? According to your debugger, they even use different HttpClient instances.

**Comment by sambalmueslie** [comment]
Yes I am sure. The instances are different, cause in that case I run into a timeout due to the breakpoint and the pod restarted. So I took the second picture after restart

**Comment by yawkat** [comment]
you can try setting a breakpoint on the constructor of the request to see where the second request is created

**Comment by bzolivereckle** [comment]
could you give me a line number pls?

**Comment by yawkat** [comment]
Just the first `NettyClientHttpRequest` constructor.

**Comment by bzolivereckle** [comment]
okay. I found now where the body of the request is set to the ByteBuffer

![image](https://user-images.githubusercontent.com/48242686/139263859-9b477f20-1737-4242-a105-b430f67ab0b4.png)

**Comment by yawkat** [comment]
Looks like the request is being processed twice and it can't handle that.

**Comment by bzolivereckle** [comment]
yeah thats also my guess, but i dont know why ... 

also from the logs i see that a answer is received, but ignored

```
2021-10-28 13:16:06,113 [multithreadEventLoopGroup-4-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP POST to https://asdf/token
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Authorization: Basic ASDFASDF
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/x-www-form-urlencoded
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - host: asd
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 29
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Request Body
2021-10-28 13:16:06,116 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - ----
2021-10-28 13:16:06,117 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - grant_type=client_credentials
2021-10-28 13:16:06,117 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - ----
2021-10-28 13:16:06,304 [multithreadEventLoopGroup-4-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from https://asdf/token
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Date: Thu, 28 Oct 2021 13:16:06 GMT
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Connection: close
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Cache-Control: no-store
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Set-Cookie: KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/qwer/; HttpOnly
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - X-XSS-Protection: 1; mode=block
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Pragma: no-cache
2021-10-28 13:16:06,305 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - X-Frame-Options: SAMEORIGIN
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Referrer-Policy: no-referrer
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Strict-Transport-Security: max-age=15724800; includeSubDomains
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - X-Content-Type-Options: nosniff
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 1528
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - Response Body
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - ----
2021-10-28 13:16:06,306 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - {"access_token":"TOKEN","expires_in":60,"refresh_expires_in":0,"token_type":"Bearer","not-before-policy":0,"scope":"profile email"}
2021-10-28 13:16:06,307 [multithreadEventLoopGroup-4-1] TRACE i.m.h.client.netty.DefaultHttpClient - ----
2021-10-28 13:16:06,483 [consumer-executor-thread-1] ERROR MyAPI - Failed to renew token
io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class io.netty.buffer.UnpooledHeapByteBuf]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:117)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:117)
	at io.micronaut.core.beans.BeanMap.of(BeanMap.java:47)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildFormDataRequest(DefaultHttpClient.java:2616)
	at io.micronaut.http.client.netty.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1635)
	at io.micronaut.http.client.netty.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1972)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$36(DefaultHttpClient.java:1243)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$addInstrumentedListener$59(DefaultHttpClient.java:2975)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by jameskleeh** [comment]
Are you reusing the same request object?

**Comment by bzolivereckle** [comment]
@jameskleeh i create a request and call ```client.exchange``` thats all i do.

What i currently saw is that ```buildNettyRequest``` is somehow called twice (dont know where that comes from) and within that method the body of the initial request is modified from String to ByteBuffer. And within the second call, the request contains a byte buffer which is getting around the String handling ... 

So no on my side is no object reusing ..

**Comment by jameskleeh** [comment]
Absent of an example to reproduce this I don't think we can be of much more help

**Comment by yawkat** [comment]
You can try tracing back further through the reactive code, e.g. by breaking on `exchange(HttpRequest, Argument, Argument)`.

**Comment by bzolivereckle** [comment]
@yawkat i had already some breakpoints on exchange ... the thing is, that at some point its running within nettys "event loop" .. and the creation of the NettyHttpRequest is coming from there

**Comment by yawkat** [comment]
"In the event loop" is nothing special, since the reactive code can easily switch threads. The event loop just runs whatever it's fed, so you have to determine the initial cause.

**Comment by bzolivereckle** [comment]
@jameskleeh sorry i could not provide you more .. one more question on your "gut feeling" the only change we made was updating from micronaut 3.0.2 to 3.1.1 and we currently managing our dependencies within a separate project we call (micronaut-common) which creates a jar we use as a dependency. The structure looks like that 
![image](https://user-images.githubusercontent.com/48242686/139269042-4ee57256-6d88-4199-96e5-367450cdc985.png)

**Comment by bzolivereckle** [comment]
@yawcat the second "create request" comes from netty and the stack is identical. The exchange is called only once. 

```
buildNettyRequest:1624, DefaultHttpClient (io.micronaut.http.client.netty)
sendRequestThroughChannel:1972, DefaultHttpClient (io.micronaut.http.client.netty)
lambda$null$36:1243, DefaultHttpClient (io.micronaut.http.client.netty)
operationComplete:-1, DefaultHttpClient$$Lambda$1027/0x0000000801698240 (io.micronaut.http.client.netty)
lambda$addInstrumentedListener$59:2975, DefaultHttpClient (io.micronaut.http.client.netty)
operationComplete:-1, DefaultHttpClient$$Lambda$1028/0x0000000801698b18 (io.micronaut.http.client.netty)
notifyListener0:578, DefaultPromise (io.netty.util.concurrent)
notifyListeners0:571, DefaultPromise (io.netty.util.concurrent)
notifyListenersNow:550, DefaultPromise (io.netty.util.concurrent)
notifyListeners:491, DefaultPromise (io.netty.util.concurrent)
setValue0:616, DefaultPromise (io.netty.util.concurrent)
setSuccess0:605, DefaultPromise (io.netty.util.concurrent)
trySuccess:104, DefaultPromise (io.netty.util.concurrent)
trySuccess:84, DefaultChannelPromise (io.netty.channel)
fulfillConnectPromise:300, AbstractNioChannel$AbstractNioUnsafe (io.netty.channel.nio)
finishConnect:335, AbstractNioChannel$AbstractNioUnsafe (io.netty.channel.nio)
processSelectedKey:707, NioEventLoop (io.netty.channel.nio)
processSelectedKeysOptimized:655, NioEventLoop (io.netty.channel.nio)
processSelectedKeys:581, NioEventLoop (io.netty.channel.nio)
run:493, NioEventLoop (io.netty.channel.nio)
run:986, SingleThreadEventExecutor$4 (io.netty.util.concurrent)
run:74, ThreadExecutorMap$2 (io.netty.util.internal)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:831, Thread (java.lang)
```

**Comment by bzolivereckle** [comment]
We finally found a "solution" after upgrading from RxJava2 to RxJava3 it worked fine. 
I have no idea, what leads to the problem. but it seems to be related to the rxjava2 implementation or dependencies.
