### ISSUE TITLE
Cannot use MicronautCaffeineCacheMetrics.monitor if there is caches section in application.yml

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#6479]
### Expected Behavior

Upgrading an existing application from 2.x to 3.x should not fail when using both MicronautCaffeineCacheMetrics.monitor and a caches section (with cacheable functions in the application).

### Actual Behaviour

Application fails to startup with error message:

```text
Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: cache_eviction_weight
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
	at io.prometheus.client.Collector.register(Collector.java:175)
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:479)
```

### Steps To Reproduce

Download the example application provided, and run it.

Removing the "caches" entries from application.yml will stop it failing, but then doesn't provide statistics on the prometheus endpoint.

### Environment Information

JDK 11, Linux various.

### Example Application

https://github.com/markjfisher/mn-cache-graphql-monitor

### Version

3.1.3

**Comment by markjfisher** [comment]
I raised this in gitter, but can't find a way of linking, but the search is `from:"mark fisher" sent:[2021-11-04 TO 2021-11-05]`

**Comment by jameskleeh** [comment]
Try changing `OtherService` to the following:

```
        CaffeineCacheMetrics.monitor(
            meterRegistry,
            cache,
            "graphQLDocumentCache"
        )
```

Note you have to use the `com.github.benmanes.caffeine.cache` imports

**Comment by markjfisher** [comment]
Excellent, I can now see the values in prometheus, and no errors.
```
cache_evictions_total{cache="graphQLDocumentCache",} 0.0
cache_evictions_total{cache="delivery-service",} 0.0
```

**Comment by jameskleeh** [comment]
@graemerocher Do you understand the need for https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/cache/MicronautCaffeineCacheMetrics.java ? We relocate caffeine in core but I don't think any of the caches we create are setup for metrics

**Comment by graemerocher** [comment]
Should be deprecated and removed. Also the JAR jared version of caffeine should be removed IMO
