### ISSUE TITLE
Compile error with Groovy and openapi

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6503]
### Expected Behavior

Generation of management endpoints for micronaut-openapi and Groovy should work.

### Actual Behaviour

There is an error during compilation. It seems that maybe this is because of a Groovy bug, but as there is a lot of Micronaut code involved there, maybe there is something we are not doing properly.

The exception is:

```
> Task :openapi:test FAILED

io.micronaut.openapi.visitor.OpenApiIncludeVisitorGroovySpec test build OpenAPI for management endpoints FAILED

  BUG! exception in phase 'semantic analysis' in source unit 'Script_5ae5e94903413279d1aeb5b89be79aa2.groovy' null
      at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:905)
      at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
      at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
      at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
      at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
      at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
      at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
      at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
      at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
      at io.micronaut.ast.transform.test.AbstractBeanDefinitionSpec.buildBeanDefinition(AbstractBeanDefinitionSpec.groovy:106)
      at io.micronaut.openapi.visitor.OpenApiIncludeVisitorGroovySpec.test build OpenAPI for management endpoints(OpenApiIncludeVisitorGroovySpec.groovy:18)
  Caused by: java.lang.reflect.UndeclaredThrowableException
      at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
      at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
      at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
      at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
      at io.micronaut.ast.groovy.utils.AstAnnotationUtils.getAnnotationMetadata(AstAnnotationUtils.groovy:53)
      at io.micronaut.ast.groovy.visitor.GroovyVisitorContext.lambda$getClassElement$1(GroovyVisitorContext.java:124)
      at java.util.Optional.map(Optional.java:215)
      at io.micronaut.ast.groovy.visitor.GroovyVisitorContext.getClassElement(GroovyVisitorContext.java:124)
      at io.micronaut.openapi.visitor.OpenApiIncludeVisitor.visitClass(OpenApiIncludeVisitor.java:54)
      at io.micronaut.ast.groovy.visitor.LoadedVisitor.visit(LoadedVisitor.groovy:172)
      at io.micronaut.ast.groovy.TypeElementVisitorTransform$ElementVisitor.visitClass_closure1(TypeElementVisitorTransform.groovy:150)
      at io.micronaut.ast.groovy.TypeElementVisitorTransform$ElementVisitor.visitClass(TypeElementVisitorTransform.groovy:149)
      at io.micronaut.ast.groovy.TypeElementVisitorTransform.visit(TypeElementVisitorTransform.groovy:103)
      at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
      at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
      ... 10 more
  Caused by: java.lang.NoSuchMethodException: java.lang.annotation.Annotation.equals()
      at java.lang.Class.getDeclaredMethod(Class.java:2130)
      at io.micronaut.ast.groovy.annotation.GroovyAnnotationMetadataBuilder.readAnnotationDefaultValues(GroovyAnnotationMetadataBuilder.groovy:375)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.processAnnotationAlias(AbstractAnnotationMetadataBuilder.java:987)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.handleAnnotationAlias(AbstractAnnotationMetadataBuilder.java:865)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.populateAnnotationData(AbstractAnnotationMetadataBuilder.java:722)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildStereotypeHierarchy(AbstractAnnotationMetadataBuilder.java:1239)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.processAnnotationStereotypes(AbstractAnnotationMetadataBuilder.java:1538)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.processAnnotationStereotype(AbstractAnnotationMetadataBuilder.java:1518)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.includeAnnotations(AbstractAnnotationMetadataBuilder.java:1176)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.buildInternal(AbstractAnnotationMetadataBuilder.java:1097)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.build(AbstractAnnotationMetadataBuilder.java:245)
      at io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder.build(AbstractAnnotationMetadataBuilder.java:226)
      at io.micronaut.ast.groovy.utils.AstAnnotationUtils.getAnnotationMetadata_closure1(AstAnnotationUtils.groovy:54)
      at groovy.lang.Closure.call(Closure.java:412)
      ... 25 more
```

### Steps To Reproduce

- `git clone https://github.com/micronaut-projects/micronaut-openapi`
- `cd micronaut-openapi`
- `git checkout error-compiling-groovy`
- `./gradlew openapi:test --tests "io.micronaut.openapi.visitor.OpenApiIncludeVisitorGroovySpec"`

Note: There is only [one new commit](https://github.com/micronaut-projects/micronaut-openapi/commit/6349a4c52823aa4cda00c9868f75b574b9524ceb) in that branch that removed an `if` statement to make the code run for Groovy and the failing test.

### Environment Information

- Linux Mint 20.2
- JDK 8

### Version

3.1.3

**Comment by faireai-fmonorchio** [comment]
There are news about this issue with groovy? Thanks! :-)

**Comment by altro3** [comment]
@graemerocher You can close it, it's already fixed
