### ISSUE TITLE
Regression when upgrading to 3.1.4 : can't build picocli native image on windows

### ISSUE THREAD

**Issue by twobeeb** [micronaut-projects/micronaut-core#6577]
### Expected Behavior

I'm using native image to compile a Micronaut Picocli CLI for windows and linux

Following Upgrade to micronaut 3.1.4, and update from graalvm 21.1.0 to 21.3.0

Linux build is **successful**
Windows build is **failed**

### Actual Behaviour

This github actions shows the failure with micronaut 3.1.4 and graalvm 21.3.0
https://github.com/michelin/ns4kafka/actions/runs/1509108289

This github actions where I reverted the graalvm to 21.1.0
https://github.com/michelin/ns4kafka/actions/runs/1510684158

Successful linux and windows build from a previous build before migrating to Micronaut 3.1.4
https://github.com/michelin/ns4kafka/actions/runs/1491868428

The error using 21.3.0 is cryptic:
````
> Task :cli:nativeImage
[kafkactl-1.2.3-SNAPSHOT:2720]    classlist:   8,324.73 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        (cap):  15,932.31 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        setup:  19,482.44 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     (clinit):   1,344.00 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]   (typeflow):  26,308.86 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]    (objects):  90,729.54 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]   (features):  15,271.58 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     analysis: 138,586.75 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     universe:   8,968.61 ms,  3.30 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      (parse):   8,313.56 ms,  3.31 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     (inline):  20,248.14 ms,  3.23 GB
[kafkactl-1.2.3-SNAPSHOT:2720]    (compile):  73,092.83 ms,  3.10 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      compile: 105,749.87 ms,  3.10 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        image:   6,051.36 ms,  3.14 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        write:   2,305.31 ms,  3.14 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      [total]: 289,948.54 ms,  3.14 GB
# Printing build artifacts to: D:\a\ns4kafka\ns4kafka\cli\build\native-image\kafkactl-1.2.3-SNAPSHOT.build_artifacts.txt
Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLL(JNIRegistrationSupport.java:256)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLLs(JNIRegistrationSupport.java:230)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:175)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:663)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:663)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Error: Image build request failed with exit status 1
````

Hopefully, the error using 21.1.0 seems more relevant : 
````
[kafkactl-1.2.3-SNAPSHOT:5516]        (cap):  17,499.16 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:5516]        setup:  21,146.51 ms,  0.96 GB
Fatal error:java.lang.NoClassDefFoundError
[kafkactl-1.2.3-SNAPSHOT:5516]     analysis:  48,689.92 ms,  2.48 GB
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.NoClassDefFoundError: javax/inject/Provider
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:316)
	at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:178)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: javax.inject.Provider
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more
Error: Image build request failed with exit status 1
````

### Environment Information

github actions are configured with latest windows and ubuntu images
I'm using graalvm jdk 11 everywhere

### Example Application

https://github.com/michelin/ns4kafka

### Version

3.1.4

**Comment by jchanaud** [comment]
I came to understand that the error in 21.1.0 is unrelated micronaut-projects/micronaut-core#5655

So I focused to graalvm 21.3.0. 
I created a new project from micronaut launch in order to use the latest version of Micronaut (3.2.0) and micronaut plugin (3.0.0).
https://github.com/twobeeb/demo/actions
Each new commit tries to reduce the complexity of the project but no luck so far...

Thanks for your help

**Comment by jchanaud** [comment]
Ok so I found 2 issues that makes windows build fail:
- snakeyaml when used to create yaml strings from POJO https://github.com/twobeeb/demo/commit/3b96986a79a96eaf0ccb1c2002021368b244bbe2
- micronaut plugin version 2.0.8 coupled with micronaut 3.x.x https://github.com/twobeeb/demo/commit/fec0a5dfe1fd51b45cbdb21a75dcd9d62fe01013

Check the associated github actions to understand how I came to that conclusion. https://github.com/twobeeb/demo/actions
As a reminder, the linux build was always successful for every workflow run
