### ISSUE TITLE
API REST developed in micronaut 3.2.0 is not register in Eureka Spring Server  

### ISSUE THREAD

**Issue by sponce2021** [micronaut-projects/micronaut-core#6593]
### Expected Behavior

Register web service in Eureka Server

### Actual Behaviour

When i run the test or compile the artefacts i received the next error:

[ERROR] com.turingears.iam.controllers.VirtualizationControllerTest  Time elapsed: 10.562 s  <<< ERROR!
io.micronaut.context.exceptions.BeanInstantiationException:
Error instantiating bean of type  [io.micronaut.discovery.eureka.registration.EurekaAutoRegistration]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new EurekaAutoRegistration(Environment environment,[EurekaClient eurekaClient],EurekaConfiguration eurekaConfiguration,HeartbeatConfiguration heartbeatConfiguration,ServiceInstanceIdGenerator idGenerator)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]

if i remove the property micronaut.application.name in the application.yaml, the application works, but i do not have the expeccted results

### Steps To Reproduce

1.- generate a project with micronaut 3.2.0
2.- add openapi and service-discovery features 

### Environment Information

Windows 10
Java 11
Micronaut 3.2.0

### Version

3.2.0

**Comment by graemerocher** [comment]
Are you using native / graalvm?

**Comment by sponce2021** [comment]
Hi, I am using native. 

Sergio.-

On 01-12-2021, at 14:23, Graeme Rocher ***@***.***> wrote:

﻿
Are you using native / graalvm?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by graemerocher** [comment]
This looks the same as https://github.com/micronaut-projects/micronaut-core/issues/6579 which is not really a bug but a config error

**Comment by sponce2021** [comment]
the problem was that it had libraries that it had developed earlier and they were duplicated in the construction of the main api. I removed the duplicate libraries micronaut-runtime and micronaut-java-inject working correctly

**Comment by wetted** [comment]
We are getting this same error, but aren't using native/GraalVM at all. It all worked fine in Micronaut 2.5.x, We started getting this error when we upgraded to 3.2.7 and get the same behavior with 3.3. as well. This is part of a thick client (using Swing) that uses a REST client to access services we stand up in a separate VM on localhost.

```
    Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
    Path Taken: new SAFEAnalyzerServiceImpl(JobTracker jobTracker,SafeAnalyzerClient client,XSASafeConversionService xsaSafeConversionService,ObjectMapper mapper,long timeout) --> new SAFEAnalyzerServiceImpl(JobTracker jobTracker,[SafeAnalyzerClient client],XSASafeConversionService xsaSafeConversionService,ObjectMapper mapper,long timeout)
    	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
    	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
    	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
    	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
    	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
    	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
    	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
    	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
    	at com.boeing.xsasafeservices.$SAFEAnalyzerServiceImpl$Definition.build(Unknown Source)
```

Here's the weird part. `SAFEAnalyzerServiceImpl` is a Singleton. I changed it to add `@Primary` (which is sensible for it anyway),  This only happens when we run old Jemmy/JUnit4-based GUI integration tests (yeah, I know, we're stuck with that). The services seem to run fine otherwise. After adding `@Primary` the behavior changes a bit. If we do a clean checkout of the project and run the Jemmy integration tests, they still fail with the above error. However, they then pass on subsequent runs (using `gradlew --refresh-dependencies clean test`), and we're baffled why. Maybe we're doing something wrong standing up our Jemmy tests - so I am investigating that - but this didn't start until Micronaut 3.x.
