### ISSUE TITLE
io.micronaut.graal.reflect.GraalClassLoadingAnalyzer doesn't generate working reflect.json with lambda function

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#663]
This is related to #582.

- Clone repo https://github.com/micronaut-guides/micronaut-function-aws-lambda
- Install Graal `sdk use java 1.0.0-rc6-graal`
- Install the SVM Dependency `mvn install:install-file -Dfile=${JAVA_HOME}/jre/lib/svm/builder/svm.jar -DgroupId=com.oracle.substratevm -DartifactId=svm -Dversion=GraalVM-1.0.0-rc6 -Dpackaging=jar`
- `cd complete/vies-vat-validator-graal`
- `./gradlew assemble`
- Generate `build/reflect.json` with `java -cp build/libs/vies-vat-validator-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer`. 
- Build the native image: `./build-native-image.sh`
- Run it: `./vies-vat-validator`
- There is an error:
```
Error executing function (Use -x for more information): Failed to inject value for parameter [client] of class: example.micronaut.VatService

Path Taken: new ViesVatValidatorFunction([VatService vatService]) --> new VatService([RxHttpClient client])
```

On the other hand, if we generate `reflect.json` executing the function:
```
echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | java -Dgraalvm.class.analysis=true -jar build/libs/vies-vat-validator-0.1-all.jar
```
And then build the native image, everything works as expected.

This is the diff between the `reflect.json` files:
```
83,85d82
<   "name" : "io.micronaut.context.annotation.Parameter",
<   "allDeclaredConstructors" : true
< }, {
113,115d109
<   "name" : "io.micronaut.core.convert.format.ReadableBytes",
<   "allDeclaredConstructors" : true
< }, {
230,235d223
<   "name" : "io.micronaut.http.client.NettyClientHttpRequestFactory",
<   "allDeclaredConstructors" : true
< }, {
<   "name" : "io.micronaut.http.client.ServiceHttpClientCondition",
<   "allDeclaredConstructors" : true
< }, {
245,247d232
<   "name" : "io.micronaut.http.client.annotation.Client",
<   "allDeclaredConstructors" : true
< }, {
708,710d692
<   "allDeclaredConstructors" : true
< }, {
<   "name" : "javax.annotation.PreDestroy",
```

**Comment by ilopmar** [comment]
I've tried building the latest snapshot and the error is the same. The detailed exception is:
```
$ ./vies-vat-validator -x
Error executing function (Use -x for more information): Failed to inject value for parameter [client] of class: example.micronaut.VatService

Path Taken: new ViesVatValidatorFunction([VatService vatService]) --> new VatService([RxHttpClient client])

Error Detail
------------
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [client] of class: example.micronaut.VatService

Path Taken: new ViesVatValidatorFunction([VatService vatService]) --> new VatService([RxHttpClient client])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.DependencyInjectionException.<init>(DependencyInjectionException.java:42)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at example.micronaut.$VatServiceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1275)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1831)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1567)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1547)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:876)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	at example.micronaut.$ViesVatValidatorFunctionDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1275)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1831)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1567)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1547)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:506)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:99)
	at io.micronaut.function.executor.StreamFunctionExecutor.execute(StreamFunctionExecutor.java:65)
	at io.micronaut.function.executor.FunctionApplication.lambda$run$0(FunctionApplication.java:63)
	at io.micronaut.function.executor.FunctionApplication$$Lambda$289/113431116.accept(Unknown Source)
	at io.micronaut.function.executor.FunctionApplication.parseData(FunctionApplication.java:99)
	at io.micronaut.function.executor.FunctionApplication.run(FunctionApplication.java:61)
	at io.micronaut.function.executor.FunctionApplication.main(FunctionApplication.java:51)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [example.micronaut.VatService]

Path Taken: new ViesVatValidatorFunction([VatService vatService]) --> new VatService([RxHttpClient client])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.BeanInstantiationException.<init>(BeanInstantiationException.java:50)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1289)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:652)
	at io.micronaut.context.DefaultBeanContext$1.get(DefaultBeanContext.java:1641)
	at io.micronaut.http.client.scope.ClientScope.lambda$get$3(ClientScope.java:129)
	at io.micronaut.http.client.scope.ClientScope$$Lambda$774/1828787582.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.http.client.scope.ClientScope.get(ClientScope.java:105)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1625)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1569)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1547)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:876)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 21 more
Caused by: java.lang.NullPointerException
	at io.micronaut.http.client.DefaultHttpClient.<init>(DefaultHttpClient.java:234)
	at io.micronaut.http.client.$DefaultHttpClientDefinition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:113)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1268)
	... 32 more
```

Now the diff between `reflect.json` files is:
```
83,85d82
<   "name" : "io.micronaut.context.annotation.Parameter",
<   "allDeclaredConstructors" : true
< }, {
110,112d106
<   "name" : "io.micronaut.core.convert.format.ReadableBytes",
<   "allDeclaredConstructors" : true
< }, {
236,238d229
<   "name" : "io.micronaut.http.client.annotation.Client",
<   "allDeclaredConstructors" : true
< }, {
696,698d686
<   "allDeclaredConstructors" : true
< }, {
<   "name" : "javax.annotation.PreDestroy",
```
