### ISSUE TITLE
(graal) Micronaut tracing example doesn't work

### ISSUE THREAD

**Issue by abishai** [micronaut-projects/micronaut-core#6693]
### Expected Behavior

Example works https://guides.micronaut.io/latest/micronaut-microservices-distributed-tracing-jaeger-gradle-java.html

### Actual Behaviour

Example compiles, but refuses to start due to reflection and resource issues

1. No reflection settings
```
Caused by: java.lang.ExceptionInInitializerError: null
  at io.jaegertracing.internal.clock.SystemClock.<clinit>(SystemClock.java:47)
  at io.jaegertracing.internal.JaegerTracer$Builder.<init>(JaegerTracer.java:553)
  at io.jaegertracing.internal.JaegerTracer$Builder.<init>(JaegerTracer.java:564)
  at io.jaegertracing.Configuration.createTracerBuilder(Configuration.java:245)
  at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:232)
  at io.micronaut.tracing.jaeger.JaegerTracerFactory.resolveBuilder(JaegerTracerFactory.java:151)
  at io.micronaut.tracing.jaeger.JaegerTracerFactory.jaegerTracerBuilder(JaegerTracerFactory.java:102)
  at io.micronaut.tracing.jaeger.$JaegerTracerFactory$JaegerTracerBuilder1$Definition.build(Unknown Source)
  at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
  ... 45 common frames omitted
Caused by: java.lang.IllegalStateException: Could not setup microseconds accurate time supplier
  at io.jaegertracing.internal.clock.MicrosAccurateClock.<clinit>(MicrosAccurateClock.java:64)
  ... 54 common frames omitted
Caused by: java.lang.ClassNotFoundException: java.time.temporal.ChronoUnit
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:53)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:139)
  at io.jaegertracing.internal.clock.MicrosAccurateClock.<clinit>(MicrosAccurateClock.java:58)
```

2. No resource settings for jaeger.properties if above fixed
 ```
Caused by: java.lang.RuntimeException: Cannot read jaeger.properties
  at io.jaegertracing.internal.JaegerTracer.getVersionFromProperties(JaegerTracer.java:734)
  at io.jaegertracing.internal.JaegerTracer.loadVersion(JaegerTracer.java:719)
  at io.jaegertracing.internal.JaegerTracer.<init>(JaegerTracer.java:107)
  at io.jaegertracing.internal.JaegerTracer$Builder.createTracer(JaegerTracer.java:707)
  at io.jaegertracing.internal.JaegerTracer$Builder.build(JaegerTracer.java:703)
  at io.micronaut.tracing.jaeger.JaegerTracerFactory.jaegerTracer(JaegerTracerFactory.java:128)
  at io.micronaut.tracing.jaeger.$JaegerTracerFactory$JaegerTracer2$Definition.build(Unknown Source)
  at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
  ... 38 common frames omitted
Caused by: java.lang.NullPointerException: null
  at io.jaegertracing.internal.JaegerTracer.getVersionFromProperties(JaegerTracer.java:731)
  ... 45 common frames omitted
```
3. NPE on start if above fixed
```
16:50:44.820 [Timer-1] ERROR i.j.i.s.RemoteControlledSampler - Failed to update sampler
java.lang.NullPointerException: null
  at io.jaegertracing.internal.samplers.RemoteControlledSampler.updateSampler(RemoteControlledSampler.java:90)
  at io.jaegertracing.internal.samplers.RemoteControlledSampler$1.run(RemoteControlledSampler.java:71)
  at java.util.TimerThread.mainLoop(Timer.java:556)
  at java.util.TimerThread.run(Timer.java:506)
  at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
  at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

The last one is strange, I have no idea how to fix it.

### Steps To Reproduce

1. Download example https://guides.micronaut.io/latest/micronaut-microservices-distributed-tracing-jaeger-gradle-java.html
2. Update Micronaut to latest version (example is slightly outdated).
3. Compile it natively
4. Run binary

### Environment Information

- ArchLinux
- OpenJDK11

### Version

3.2.3

**Comment by ilopmar** [comment]
We don't have support for Jaeger and GraalVM, that's why the guide doesn't include the instructions about how to create the native image. I tried it sometime ago and it didn't work. See https://github.com/jaegertracing/jaeger-client-java/issues/600

**Comment by abishai** [comment]
How unfortunately. I thought we have only missing reflection dependencies.

**Comment by ilopmar** [comment]
Maybe nowadays Jaeger is more GraalVM-friendly than sometime ago. You can try the Native Agent to generate the reflect config and give it a try.
