### ISSUE TITLE
TestInstance.Lifecycle.PER_CLASS annotation blocks context init

### ISSUE THREAD

**Issue by mboogi** [micronaut-projects/micronaut-core#6709]
### Expected Behavior

It should instantiate application context

### Actual Behaviour

when starting tests annotated with TestInstance.Lifecycle.PER_CLASS, than the following error occurs:

Failed to resolve parameter [com.tests.test.SimpleService service] in constructor [public com.tests.test.SimpleServiceNOTWorkingTest(com.tests.test.SimpleService)]: Cannot invoke "io.micronaut.context.ApplicationContext.findBeanDefinition(java.lang.Class)" because "applicationContext" is null
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [com.tests.test.SimpleService service] in constructor [public com.tests.test.SimpleServiceNOTWorkingTest(com.tests.test.SimpleService)]: Cannot invoke "io.micronaut.context.ApplicationContext.findBeanDefinition(java.lang.Class)" because "applicationContext" is null
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:239)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:74)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:355)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:302)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:280)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda$340/0x000000005242b4d0.get(Unknown Source)

### Steps To Reproduce

1 test Environment
2 tried with Kotlin
3 create simple service, annotate it with @Service
4 Create test annotated as Micronaut test
5 annotate test with TestInstance.Lifecycle.PER_CLASS
6 try to run any test method

### Environment Information

- Windows
- Linux

### Version

3.0.0

**Comment by graemerocher** [comment]
Provide an example please. Many guides use `TestInstance.Lifecycle.PER_CLASS` without issues. Example https://guides.micronaut.io/latest/micronaut-mongodb-synchronous-gradle-java.html

**Comment by mboogi** [comment]
Hi graemerocher ,
the repo is here: 
https://github.com/mboogi/micronaut-test

BR
MB

**Comment by MilosBogi** [comment]
Any infos on this issue? The example above is very similar to the issue we have in production

**Comment by mboogi** [comment]
Hi to All,
this problem still persists, but after discussion with some of colleagues, there is a workaround
Instead of using constructor injection it works just by using @Inject annotation. However it is not intuitive and it is not documented. Will open an discussion

**Comment by graemerocher** [comment]
You can also use method injection into the test method

**Comment by mboogi** [comment]
As long as I am concearned, this issue is closed as there is a workarround. However it would be nice to document it this way or another
BR
MB
