### ISSUE TITLE
Postgres Reactive & Netty Compatibility Broken

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#680]
When including the

```
<dependency>
            <groupId>io.micronaut.configuration</groupId>
            <artifactId>postgres-reactive</artifactId>
        </dependency>
```

There appears to be a breaking netty dependency on netty-common 4.19.0 which causes:

```
Disconnected from the target VM, address: '127.0.0.1:58665', transport: 'socket'
14:30:26.482 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: io.netty.util.internal.ReflectionUtil.trySetAccessible(Ljava/lang/reflect/AccessibleObject;Z)Ljava/lang/Throwable;
java.lang.NoSuchMethodError: io.netty.util.internal.ReflectionUtil.trySetAccessible(Ljava/lang/reflect/AccessibleObject;Z)Ljava/lang/Throwable;
	at io.netty.channel.nio.NioEventLoop$4.run(NioEventLoop.java:210)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:203)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.micronaut.http.server.netty.NettyHttpServer.newEventLoopGroup(NettyHttpServer.java:467)
	at io.micronaut.http.server.netty.NettyHttpServer.createWorkerEventLoopGroup(NettyHttpServer.java:389)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:228)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:106)
	at io.micronaut.runtime.Micronaut.lambda$start$1(Micronaut.java:73)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
```

Upon inspecting the dependency tree it looks like the following (some removed).

```
...
[INFO] +- io.micronaut:http-server-netty:jar:1.0.0.RC1:compile
[INFO] |  +- io.micronaut:http-server:jar:1.0.0.RC1:compile
[INFO] |  |  \- io.micronaut:websocket:jar:1.0.0.RC1:compile
[INFO] |  \- io.micronaut:http-netty:jar:1.0.0.RC1:compile
[INFO] |     +- io.micronaut:buffer-netty:jar:1.0.0.RC1:compile
[INFO] |     |  \- io.netty:netty-buffer:jar:4.1.29.Final:compile
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.29.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.29.Final:compile
[INFO] |     \- io.netty:netty-handler:jar:4.1.29.Final:compile
[INFO] |        \- io.netty:netty-transport:jar:4.1.29.Final:compile
...
[INFO] +- io.micronaut.configuration:postgres-reactive:jar:1.0.0.RC1:compile
[INFO] |  +- io.reactiverse:reactive-pg-client:jar:0.9.0:compile
[INFO] |  |  \- io.vertx:vertx-core:jar:3.5.2:compile
[INFO] |  |     +- io.netty:netty-common:jar:4.1.19.Final:compile
[INFO] |  |     +- io.netty:netty-handler-proxy:jar:4.1.29.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-socks:jar:4.1.29.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http2:jar:4.1.19.Final:compile
[INFO] |  |     +- io.netty:netty-resolver:jar:4.1.19.Final:compile
[INFO] |  |     \- io.netty:netty-resolver-dns:jar:4.1.19.Final:compile
[INFO] |  |        \- io.netty:netty-codec-dns:jar:4.1.19.Final:compile
...
```

To get server to run I had to do 

```
<dependency>
            <groupId>io.micronaut.configuration</groupId>
            <artifactId>postgres-reactive</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by jameskleeh** [comment]
This is due to an internal api change https://github.com/netty/netty/commit/e72c197aa3a88e97c10793ee7870775ab8807f92 combined with different parts of netty being loaded with different versions. I think simply excluding netty-common may allow this to work, but every netty dependency should be on the same version. For example I think `netty-codec-http2` will still be using `4.1.19` with the change you included.

**Comment by jameskleeh** [comment]
@graemerocher Perhaps we should discuss shadowing netty or including some mechanism to force the version in apps
