### ISSUE TITLE
Not able to inject multiple repositories using hibernate-jpa: DependencyInjectionException: Failed to inject value for field [entityManager]

### ISSUE THREAD

**Issue by sselonick** [micronaut-projects/micronaut-core#6838]
I'm not sure this is a bug but some some help resolving my issue with injecting multiple Repositories when using hibernate-jpa would be very much appreciated.  Thanks.

### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/6837

<div type='discussions-op-text'>

<sup>Originally posted by **sselonick** January 29, 2022</sup>
# Error Summary
I have been trying to extend the micronaut-jpa-hibernate [tutorial](https://guides.micronaut.io/latest/micronaut-jpa-hibernate-gradle-java.html) to multiple data sources.  I have been unable to successfully implement a second datasource/repository. The following error is received when running the GenreController unit test.  Any insight on the issue would be much appreciated.  Thanks!  Please find the complete project that I've been working on in the repo below.

```bash
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Failed to inject value for field [entityManager] of 
class: example.micronaut.GenreRepositoryImpl$Intercepted Message: Multiple possible bean candidates found: 
[io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted, io.micronaut.configuration.hibernate.jpa.
TransactionalSession$Intercepted]
```

##### Repo:
[https://github.com/sselonick/micronautguide_extend_multiple_datasources](https://github.com/sselonick/micronautguide_extend_multiple_datasources)

```bash
./gradlew clean test --info
```

## Environment
- Gradle 7.2
- JVM: 11.0.13 (Amazon.com Inc. 11.0.13+8-LTS)
- OS:  Mac OS X 10.15.7 x86_64
- Micronaut 2.0.8

Seem to be getting same error with micronaut 3.0.0

### application.yml
```bash
micronaut:
  application:
    name: micronautguide

application:
  max: 50

datasources:
  first:
    url: ${JDBC_URL:`jdbc:h2:mem:first;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

  other:
    url: ${JDBC_URL:`jdbc:h2:mem:other;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  first:
    name: 'first'
    entity-scan:
      packages: 'example.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  other:
    name: 'other'
    entity-scan:
      packages: 'example.micronaut.other'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

```

The second repository I tried to add (`OtherRepositoryImpl`) is implemented in 
java/example/micronaut/OtherBookRepositoryImpl.java. The repository is used in the `GenreController` POST endpoint.  

```bash 
@Singleton
@Repository(value = "other")
abstract class OtherBookRepositoryImpl implements GenericRepository<OtherBook, Long> {

    @Inject
    @PersistenceContext(name = "other")
    private EntityManager entityManager;
    private final ApplicationConfiguration applicationConfiguration;

    public OtherBookRepositoryImpl(ApplicationConfiguration applicationConfiguration) {
        this.applicationConfiguration = applicationConfiguration;
    }

....

}
```

```bash
@Post
    public HttpResponse<Genre> save(@Body @Valid GenreSaveCommand cmd) {
        Genre genre = genreRepository.save(cmd.getName());

        OtherBook otherBook = otherBookRepository.save("Hello");
        System.out.println("JUST SAVED: " + otherBook.getName());

        return HttpResponse
                .created(genre)
                .headers(headers -> headers.location(location(genre.getId())));
```

I modified the initial repository GenreRepository to be an abstract class that implementing GenericRepository<Genre, Long>

```bash

@Singleton
@Repository(value = "first")
abstract class GenreRepositoryImpl implements GenericRepository<Genre, Long> {
    @Inject
    @PersistenceContext(name = "first")
    private EntityManager entityManager;
    private final ApplicationConfiguration applicationConfiguration;


    private final static List<String> VALID_PROPERTY_NAMES = Arrays.asList("id", "name");

    public GenreRepositoryImpl(ApplicationConfiguration applicationConfiguration) {
        this.applicationConfiguration = applicationConfiguration;
    }


  ....
}
````
### Error received when running the GenreController unit test

````bash
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Failed to inject value for field [entityManager] of class: example.micronaut.GenreRepositoryImpl$Intercepted

Message: Multiple possible bean candidates found: [io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted, io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted]
Path Taken: new $GenreController$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> $GenreController$Definition$Intercepted.genreRepository --> GenreRepositoryImpl$Intercepted.entityManager
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [entityManager] of class: example.micronaut.GenreRepositoryImpl$Intercepted

Message: Multiple possible bean candidates found: [io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted, io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted]
Path Taken: new $GenreController$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> $GenreController$Definition$Intercepted.genreRepository --> GenreRepositoryImpl$Intercepted.entityManager
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1588)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1549)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1259)
	at example.micronaut.$GenreRepositoryImpl$Intercepted$Definition.injectBean(Unknown Source)
	at example.micronaut.$GenreRepositoryImpl$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2821)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2783)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1639)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1566)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1549)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1259)
	at example.micronaut.$GenreController$Definition.injectBean(Unknown Source)
	at example.micronaut.$GenreController$Definition$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2821)
	at io.micronaut.context.DefaultBeanContext.access$100(DefaultBeanContext.java:151)
	at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:541)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:584)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:636)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted, io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2430)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:454)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3254)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3055)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1639)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1566)
	... 37 common frames omitted


```
</div>

**Comment by atpguru** [comment]
Same here. We only want to use jpa for one of two datasources but do get the "Multiple possible bean candidates found: [io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted" Error. Any help appreciated.

**Comment by graemerocher** [comment]
attach an example that reproduces the error

**Comment by atpguru** [comment]
we've meanwhile restructured and reduced and reorganized the overall dependencies. now it runs like a charm. but thank you very much for contacting and have a nice weekend.
