### ISSUE TITLE
Graal native image hangs with Micronaut security

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#684]
This is related to #677 

- Use Graal-RC6
- Clone the repo: https://github.com/ilopmar/micronaut-security-jwt-graal
- Start the app with `./gradlew run`
- Send the request: `curl -X POST -H "Content-Type:application/json" -d '{"username":"sherlock","password":"password"}' http://localhost:8080/login`
- The bearer token is generated and returned and this is the output in the console:
```
17:08:11.238 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1453ms. Server Running: http://localhost:8080
17:08:17.451 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.reader.HttpHeaderTokenReader - Looking for bearer token in Authorization header
17:08:17.452 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.reader.HttpHeaderTokenReader - Looking for bearer token in Authorization header
17:08:17.452 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.TokenAuthenticationFetcher - Unauthenticated request POST, /login, no token found.
17:08:17.453 [nioEventLoopGroup-1-2] DEBUG i.m.security.filters.SecurityFilter - Failure to authenticate request. POST /login.
17:08:17.454 [nioEventLoopGroup-1-2] DEBUG i.m.security.filters.SecurityFilter - Authorized request POST /login. The rule provider io.micronaut.security.rules.SecuredAnnotationRule authorized the request.
17:08:17.552 [nioEventLoopGroup-1-2] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.13.Final
17:08:17.569 [nioEventLoopGroup-1-2] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
17:08:17.825 [nioEventLoopGroup-1-2] DEBUG i.m.s.authentication.Authenticator - example.micronaut.services.AuthenticationProviderUserPassword
17:08:17.841 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.j.g.c.JWTClaimsSetGenerator - Setting expiration to 3600
17:08:17.857 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.j.g.c.JWTClaimsSetGenerator - Generated claim set: {"sub":"sherlock","nbf":1538665697,"roles":[],"iss":"micronaut","exp":1538669297,"iat":1538665697}
17:08:17.891 [nioEventLoopGroup-1-2] DEBUG i.m.s.t.j.g.c.JWTClaimsSetGenerator - Generated claim set: {"sub":"sherlock","nbf":1538665697,"roles":[],"iss":"micronaut","iat":1538665697}
```

- Execute `./build-native-image.sh` start the application and send the same request with curl
- The output in the console is:
```
$ ./mn-security 
17:10:06.641 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 22ms. Server Running: http://localhost:8080
17:10:09.897 [nioEventLoopGroup-2-2] DEBUG i.m.s.t.reader.HttpHeaderTokenReader - Looking for bearer token in Authorization header
17:10:09.897 [nioEventLoopGroup-2-2] DEBUG i.m.s.t.reader.HttpHeaderTokenReader - Looking for bearer token in Authorization header
17:10:09.897 [nioEventLoopGroup-2-2] DEBUG i.m.s.t.TokenAuthenticationFetcher - Unauthenticated request POST, /login, no token found.
17:10:09.897 [nioEventLoopGroup-2-2] DEBUG i.m.security.filters.SecurityFilter - Failure to authenticate request. POST /login.
17:10:09.897 [nioEventLoopGroup-2-2] DEBUG i.m.security.filters.SecurityFilter - Authorized request POST /login. The rule provider io.micronaut.security.rules.SecuredAnnotationRule authorized the request.
```
The process hangs there and it takes 1 cpu to 100%. Please note that when running the app with gradle the next line in the log is `INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.13.Final` and this isn't displayed in the native image log. So, maybe this hang is because some issue in Hibernate-validator.

**Comment by graemerocher** [comment]
Following the above commit the internal issues with Micronaut are resolved, however it still doesn't work with the exception being:

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found 
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:205)
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.<init>(ConstraintHelper.java:674)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:142)
	at org.h
```

Which seems to be an incompatibility with Hibernate validator. We should report the issue to the Graal issue tracker.

**Comment by graemerocher** [comment]
Reported https://github.com/oracle/graal/issues/718

**Comment by ilopmar** [comment]
Test application updated to 1.1.0.M2 (using build-snapshot). Tried with both GraalRC12 and RC14-dev from graal master branch.

Now we're hitting this issue https://github.com/oracle/graal/issues/717 (which I've also update).

**Comment by graemerocher** [comment]
Still not fixed in rc13 of Graal. Seems https://github.com/oracle/graal/issues/659 contains a patch

**Comment by ilopmar** [comment]
Closing this because the image generation now works. I'll open another issue to track the new error.
