### ISSUE TITLE
Duplicate Beans Injected when running micronaut with native image

### ISSUE THREAD

**Issue by avirkar** [micronaut-projects/micronaut-core#6857]
### Expected Behavior

We are trying to run a micronaut application with GraalVM by creating a native image using the graalvm plugin. The following is our observation.

We are trying to build a native image  for our Micronaut Application.  We are using  the following configuration

`Micronaut 3.2.1
GraalVM EE 22.0.0.2`

The following is our observation.

1. The Jar file runs perfectly fine without any issue.
2. The native executable runs fine but we need to generate the config files using the tracing agent. More details [here](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/)
3. The fallback image fails with the following error. 

`14:25:37.541 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type [com.oracle.gbu.gaes.redwoodtelemetryagent.bootstrap.OciResources$ApplicationEventListener$createOciResources1$Intercepted]: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [com.oracle.gbu.gaes.redwoodtelemetryagent.bootstrap.OciResources$ApplicationEventListener$createOciResources1$Intercepted]: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2366)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3686)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3568)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:921)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217)
	at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77)
	at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:522)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:346)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:148)
	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:78)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:76)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at com.oracle.gbu.gaes.redwoodtelemetryagent.Application.main(Application.java:10)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2430)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:455)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3254)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3055)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:889)
	at io.micronaut.aop.chain.InterceptorChain.resolveInterceptors(InterceptorChain.java:205)
	at io.micronaut.aop.chain.InterceptorChain.resolveIntroductionInterceptors(InterceptorChain.java:144)
	at com.oracle.gbu.gaes.redwoodtelemetryagent.bootstrap.OciResources$ApplicationEventListener$createOciResources1$Intercepted.<init>(Unknown Source)
	at com.oracle.gbu.gaes.redwoodtelemetryagent.bootstrap.$OciResources$ApplicationEventListener$createOciResources1$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	... 16 common frames omitted
ajvirkar-mac:redwood-telemetry-agent ajvirkar$`

### Actual Behaviour

The application starts up without any issue. 

### Steps To Reproduce

1. Have a micronaut application that uses events. 
2. Build a fallback image 
3. Ensure that you use the following graamvm plugin configuration. 

` <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <version>0.9.9</version>
        <executions>
          <execution>
            <id>build-native</id>
            <goals>
              <goal>build</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <configuration>
          <buildArgs combine.children="append">
            <buildArg>--verbose</buildArg>
            
            <buildArg>--force-fallback</buildArg>
            <buildArg>-H:-UseServiceLoaderFeature</buildArg>
          </buildArgs>
        </configuration>
      </plugin>`

### Environment Information

> Micronaut 3.2.1
> GraalVM EE 22.0.0.2

### Version

3.2.1

**Comment by AlexSlob** [comment]
Facing the same issue:

`Error starting Micronaut server: Error instantiating bean of type [io.micronaut.management.health.indicator.service.ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$Intercepted]: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.management.health.indicator.service.ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$Intercepted]: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2366)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3686)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3568)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:921)
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217)
        at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77)
        at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72)
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
        at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:522)
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:346)
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:148)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:78)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:76)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
        at com.oracle.gbu.gaes.metadata.MetadataApplication.main(MetadataApplication.java:8)`
        
     
     Environment info:
    

>  Micronaut version: 3.2.1
>  GraalVM CE 21.3.0
>  micronaut-flyway 5.0.1

**Comment by graemerocher** [comment]
hi both, we will need an example application with steps to reproduce. The most likely cause a build configuration issue. Feel free to reach out directly via email etc.

**Comment by graemerocher** [comment]
There are some very strange aspects about the sample application provided at https://github.com/AlexSlob/architecture-demo

1. A compile dependency on mockito-core is added, this should only apply to the  tests
2. A runtime dependency on the JACOCO Maven plugin is added, again this should be in the <plugins> config not under dependencies
3. Custom, unnecessary graalvm native configuration is added

With the PR https://github.com/AlexSlob/architecture-demo/pull/1

And running:

```
mvn package -Dpackaging=native-image
```

The application builds and executes just fine.
