### ISSUE TITLE
Missing HttpStatus 526 Invalid SSL certificate

### ISSUE THREAD

**Issue by message** [micronaut-projects/micronaut-core#6873]
### Expected Behavior

`HttpStatus.INVALID_SSL_CERTIFICATE`

### Actual Behaviour

When CloudFlare responds with `526 Invalid SSL certificate`, http client fails while trying to create missing HttpStatus enum.

```
java.lang.IllegalArgumentException: Invalid HTTP status code: 526
	at io.micronaut.http.HttpStatus.valueOf(HttpStatus.java:265)
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2352)
```

### Steps To Reproduce

HttpRequest.GET something that returns 526

### Version

3.3.0

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by message** [comment]
I ditched Micronaut in 2022
