### ISSUE TITLE
UP state not sent to Eureka after client was temporary DOWN

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#691]
If a Micronaut service is temporary DOWN it will never return to UP state in Eureka, even though all health checks reports UP. I think the status change from DOWN to UP is never sent to Eureka
 If I restart the unstable service it's reported UP by Eureka,

### Steps to Reproduce

1. Start a Micronaut discovery client and it will appear in Eureka dashboard as UP
2. Make the service health check report DOWN then UP after a while
3. Eureka still reports the service as being DOWN

### Expected Behaviour

The service status in Eureka should be UP after the service recovered

### Actual Behaviour

The service status is DOWN in Eureka until the service is restarted

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** BUILD-SNAPSHOT 2018-10-06
- **JDK Version:** 1.8.0_162-b12

### Example Application

https://github.com/goeh/micronaut-health-issue

**Comment by goeh** [comment]
@graemerocher were right on gitter. `eurekaClient.updateStatus()` is only called when health status != UP. When it is UP  only heartbeats are sent.

https://github.com/micronaut-projects/micronaut-core/blob/b84ecf20d6346b86477afa2fc5d07e0d0b646cd1/discovery-client/src/main/java/io/micronaut/discovery/eureka/registration/EurekaAutoRegistration.java#L113

**Comment by goeh** [comment]
I'm not sure this is related or a separate issue, but I've seen some log output that makes me wonder.
Somehow one of my services is not registered in Eureka even though it's up. I'm not sure it was registered first and then removed because it was DOWN too long, or if it never could register from the beginning. Anyway the service is up and tries to report it's status to Eureka. But since the service is not registered Eureka responds with 404 (my guessing).
```
gr8crm-notification-service_1  | 20:37:21.519 [nioEventLoopGroup-1-9] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: PUT /eureka/apps/gr8crm-notification-service/gr8crm-notification-service%3A8084/status?value=DOWN
gr8crm-notification-service_1  | 20:37:21.519 [nioEventLoopGroup-1-9] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: gr8crm-registry-service(8761)
gr8crm-notification-service_1  | 20:37:21.520 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Accept: application/json
gr8crm-notification-service_1  | 20:37:21.520 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - host: gr8crm-registry-service
gr8crm-notification-service_1  | 20:37:21.520 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - connection: close
gr8crm-notification-service_1  | 20:37:21.524 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - HTTP Client Response Received for Request: PUT /apps/gr8crm-notification-service/gr8crm-notification-service%3A8084/status?value=DOWN
gr8crm-notification-service_1  | 20:37:21.525 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Status Code: 404 
gr8crm-notification-service_1  | 20:37:21.525 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Content-Type: application/json
gr8crm-notification-service_1  | 20:37:21.526 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Content-Length: 0
gr8crm-notification-service_1  | 20:37:21.526 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Date: Sun, 07 Oct 2018 20:37:21 GMT
gr8crm-notification-service_1  | 20:37:21.526 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Connection: close
gr8crm-notification-service_1  | 20:37:21.527 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Response Body
gr8crm-notification-service_1  | 20:37:21.527 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - ----
gr8crm-notification-service_1  | 20:37:21.528 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - 
gr8crm-notification-service_1  | 20:37:21.528 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - ----
gr8crm-notification-service_1  | 20:37:21.529 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Full HTTP response received an empty body
gr8crm-notification-service_1  | 20:37:21.529 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateos.JsonError
gr8crm-notification-service_1  | 20:37:21.532 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateos.JsonError
gr8crm-notification-service_1  | 20:37:21.532 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Unable to convert response body to target type class io.micronaut.http.hateos.JsonError
gr8crm-notification-service_1  | 20:37:21.533 [nioEventLoopGroup-1-9] ERROR i.m.d.registration.AutoRegistration - Error reporting state to Eureka: 
gr8crm-notification-service_1  | io.micronaut.http.client.exceptions.HttpClientResponseException: 
gr8crm-notification-service_1  | 	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1724)
gr8crm-notification-service_1  | 	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1677)
gr8crm-notification-service_1  | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
gr8crm-notification-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
gr8crm-notification-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
gr8crm-notification-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
```

When I shutdown the service it tries to de-register itself. But since Eureka does not have an entry for this service it responds with 404 (my guessing).

```
gr8crm-notification-service_1  | 20:38:43.505 [Thread-2] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
gr8crm-notification-service_1  | 20:38:43.518 [nioEventLoopGroup-1-3] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: DELETE /eureka/apps/gr8crm-notification-service/gr8crm-notification-service%3A8084
gr8crm-notification-service_1  | 20:38:43.518 [nioEventLoopGroup-1-3] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: gr8crm-registry-service(8761)
gr8crm-notification-service_1  | 20:38:43.518 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Accept: application/json
gr8crm-notification-service_1  | 20:38:43.518 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - host: gr8crm-registry-service
gr8crm-notification-service_1  | 20:38:43.518 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - connection: close
gr8crm-notification-service_1  | 20:38:43.535 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - HTTP Client Response Received for Request: DELETE /apps/gr8crm-notification-service/gr8crm-notification-service%3A8084
gr8crm-notification-service_1  | 20:38:43.535 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Status Code: 404 
```
If I restart the service it registers with Eureka and everything is fine. I don't know why it couldn't register the first time.
