### ISSUE TITLE
calling http client unauthorized

### ISSUE THREAD

**Issue by arcturuscom** [micronaut-projects/micronaut-core#6917]
### Expected Behavior

i'm receiving unauthorized error httpClient when i enabled security.
here's a stack trace :
```
 ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: io.micronaut.http.client.exceptions.HttpClientResponseException: Unauthorized
Caused by: io.micronaut.http.client.exceptions.HttpClientResponseException: Unauthorized
at io.micronaut.http.client.netty.DefaultHttpClient$10.channelReadInstrumented(DefaultHttpClient.java:2210)
at io.micronaut.http.client.netty.DefaultHttpClient$10.channelReadInstrumented(DefaultHttpClient.java:2126)
at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:3072)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.micronaut.http.netty.reactive.HandlerPublisher.channelRead(HandlerPublisher.java:318)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:278)
at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:189)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
```

here's my config 
```
   security:
    enabled: true
    intercept-url-map:
      - pattern: /health/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            validator:
              secret: xxxxxxxxxx
 http:
    services:
      client1:
        url: http://localhost:54705
      client2:
        url: http://localhost:64477
      client3:
        url: http://localhost:64241
```

i'm using ther version 3.3.0 of Micronaut 
it's works on my windows machine but it's fails on AWS, EKS 
PS:  third party microservices are not secured

### Environment Information

- OS: EC2 Linux 
- JDK: 1.8

### Version

3.3.0

**Comment by timyates** [comment]
Do you have a simple example application that demonstrates the issue?

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback
