### ISSUE TITLE
IllegalArgumentException: VoidChannelPromise not allowed for this operation

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#692]
WORK IN PROGRESS

I created this issue to track down an exception I get in a Micronaut service that is part of a larger system. I tried to create a simple application to isolate the problem but that app works ok
 I have seen this exception in more than one service.
Once a service throws this exception it's DOWN forever in Eureka, but that's related to issue #691 

I will add information to this issue when I make progress.

### Steps to Reproduce

1. Start Micronaut service together with Eureka, MongoDB, Kafka, Postgres, ...
2. Wait for all services come up
3. After 1-2 minutes the exception (below) to appear.

### Expected Behaviour

No exception and service status should be UP in Eureka.

### Actual Behaviour

```
    | 15:59:21.242 [pool-1-thread-5] DEBUG i.m.m.h.monitor.HealthMonitorTask - Starting health monitor check
    | 15:59:21.469 [nioEventLoopGroup-1-5] DEBUG i.m.m.h.monitor.HealthMonitorTask - Health monitor check failed with status DOWN
    | io.reactivex.exceptions.CompositeException: 1 exceptions occurred.
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorReturn$OnErrorReturnSubscriber.onError(FlowableOnErrorReturn.java:60)
    | 	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onError(FlowableOnErrorNext.java:89)
    | 	at io.reactivex.internal.subscriptions.EmptySubscription.error(EmptySubscription.java:55)
    | 	at io.reactivex.internal.operators.flowable.FlowableError.subscribeActual(FlowableError.java:40)
    | 	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
    | 	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onError(FlowableOnErrorNext.java:114)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:567)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:606)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
    | 	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:221)
    | 	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onError(FlowableSwitchMap.java:142)
    | 	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:292)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:536)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:486)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:274)
    | 	at io.micronaut.http.client.DefaultHttpClient$8.exceptionCaught(DefaultHttpClient.java:1555)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
    | 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:331)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:432)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:353)
    | 	at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:460)
    | 	at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:243)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
    | 	at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529)
    | 	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
    | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    | 	at java.lang.Thread.run(Thread.java:748)
    |   ComposedException 1 :
    | 	java.lang.IllegalArgumentException: VoidChannelPromise not allowed for this operation
    | 		at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:924)
    | 		at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:600)
    | 		at io.micronaut.http.netty.stream.HttpStreamsClientHandler.close(HttpStreamsClientHandler.java:101)
    | 		at io.micronaut.http.client.DefaultHttpClient$HttpClientInitializer$4.userEventTriggered(DefaultHttpClient.java:2097)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:432)
    | 		at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 		at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:353)
    | 		at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:460)
    | 		at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:243)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
    | 		at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529)
    | 		at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
    | 		at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    | 		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    | 		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    | 		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
    | 		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    | 		at java.lang.Thread.run(Thread.java:748)
    |
    | Exception in thread "nioEventLoopGroup-1-3" io.reactivex.exceptions.CompositeException: 1 exceptions occurred.
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorReturn$OnErrorReturnSubscriber.onError(FlowableOnErrorReturn.java:60)
    | 	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onError(FlowableOnErrorNext.java:89)
    | 	at io.reactivex.internal.subscriptions.EmptySubscription.error(EmptySubscription.java:55)
    | 	at io.reactivex.internal.operators.flowable.FlowableError.subscribeActual(FlowableError.java:40)
    | 	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
    | 	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
    | 	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onError(FlowableOnErrorNext.java:114)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:567)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:606)
    | 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
    | 	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:221)
    | 	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onError(FlowableSwitchMap.java:142)
    | 	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:292)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:536)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:486)
    | 	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:274)
    | 	at io.micronaut.http.client.DefaultHttpClient$8.exceptionCaught(DefaultHttpClient.java:1555)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
    | 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:331)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:432)
    | 	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:353)
    | 	at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:460)
    | 	at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:243)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
    | 	at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529)
    | 	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
    | 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    | 	at java.lang.Thread.run(Thread.java:748)
    |   ComposedException 1 :
    | 	java.lang.IllegalArgumentException: VoidChannelPromise not allowed for this operation
    | 		at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:924)
    | 		at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:600)
    | 		at io.micronaut.http.netty.stream.HttpStreamsClientHandler.close(HttpStreamsClientHandler.java:101)
    | 		at io.micronaut.http.client.DefaultHttpClient$HttpClientInitializer$4.userEventTriggered(DefaultHttpClient.java:2097)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:432)
    | 		at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
    | 		at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:353)
    | 		at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:460)
    | 		at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:243)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
    | 		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
    | 		at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
    | 		at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529)
    | 		at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
    | 		at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    | 		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    | 		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    | 		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
    | 		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    | 		at java.lang.Thread.run(Thread.java:748)
    |

```

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** BUILD-SNAPSHOT 2018-10-06
- **JDK Version:** 1.8.0_162-b12

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
@goeh once the build completes can you try master? I can't reproduce so your feedback will be welcome. Seems there is some idle http client connection that isn't being closed correctly

**Comment by goeh** [comment]
Initial tests look very promising! Now I don't get any exceptions. But all services are UP. Later today I will try to force a service to DOWN and see if can trigger the exception.

**Comment by goeh** [comment]
@graemerocher I think you can close this as fixed. I have a few Eureka/discovery issues that disturbs my testing (some reported, some need more investigation), but I've never seen the VoidChannelPromise message after your fix. Thanks!
