### ISSUE TITLE
Micronaut Custom Exception Handler handle() not triggered when exception is thrown from a coroutine

### ISSUE THREAD

**Issue by vinmorel** [micronaut-projects/micronaut-core#6936]
### Expected Behavior

When an exception is thrown from inside a coroutine, I expect that the code inside my handle() function from an ExceptionHandler be run. 

### Actual Behaviour

The exception is not caught and the handle function doesn't run. 

### Steps To Reproduce

1. create an exception and add a custom exception handler
`DummyException.kt`

```
package com.example

import io.micronaut.context.annotation.Requirements
import io.micronaut.context.annotation.Requires
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpResponse
import io.micronaut.http.HttpStatus
import io.micronaut.http.annotation.Produces
import io.micronaut.http.server.exceptions.ExceptionHandler
import jakarta.inject.Singleton

class DummyException : RuntimeException()

@Produces
@Singleton
@Requirements(
    Requires(classes = [DummyException::class, ExceptionHandler::class])
)
class DummyExceptionHandler : ExceptionHandler<DummyException, HttpResponse<*>> {
    override fun handle(request: HttpRequest<*>?, exception: DummyException?): HttpResponse<String> {
        println("handle $exception")
        return HttpResponse.status(HttpStatus.INTERNAL_SERVER_ERROR, "Dummy Exception")
    }
}
```

2. Throw this exception from inside a coroutine in a controller.
`Controller.kt`

```
package com.example

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import kotlinx.coroutines.*

@Controller
class Controller {

    val scope = CoroutineScope(Job())

    @Get("/throw")
    fun throwDummyException() {
        scope.launch {
            throw DummyException()
        }
    }
}
```

3. Observe that the exception is not handled. 
```
Exception in thread "DefaultDispatcher-worker-1" com.example.DummyException
	at com.example.Controller$throwDummyException$1.invokeSuspend(Controller.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Environment Information

- Micronaut 3.2.0
- Kotlin 1.6.0
- Java JDK 11
- implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")

### Version

3.2.0

**Comment by jameskleeh** [comment]
I cannot reproduce this with 3.3.3. Please upload an example that reproduces the issue

**Comment by vinmorel** [comment]
Example [here](https://github.com/vinmorel/micronaut-exception-handling-issue)

**Comment by jameskleeh** [comment]
My way of reproducing the issue was invalid. Having said that I don't think its possible for us to support this because the exception is not being thrown from the method or being propagated upstream in any way

**Comment by vinmorel** [comment]
Ok, thanks for checking it out! It makes sense.

If anyone stumbles upon this in the future, check out the CoroutineExceptionHandler kotlin object.
