### ISSUE TITLE
Error compiling a simple HelloController with Spock tests due to groovy-eclipse-compiler plugin 

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#694]
There seems to be some issue with main code in Java and groovy test code.

I get compilation error:

```
$ mcv
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building micronaut-ribbon-example2 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ micronaut-ribbon-example2 ---
[INFO] Deleting /Users/rhasija/dev/projects/experimental/micronaut/micronaut-ribbon-example2/target
[INFO] 
[INFO] --- groovy-eclipse-compiler:2.9.3-01:add-groovy-build-paths (default-add-groovy-build-paths) @ micronaut-ribbon-example2 ---
[INFO] Adding /src/main/groovy to the list of source folders
[INFO] Adding /src/test/groovy to the list of test source folders
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ micronaut-ribbon-example2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ micronaut-ribbon-example2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] 1 problem (1 error)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/rhasija/dev/projects/experimental/micronaut/micronaut-ribbon-example2/src/main/java/micronaut/ribbon/example2/HelloController.java: 
1. ERROR in /Users/rhasija/dev/projects/experimental/micronaut/micronaut-ribbon-example2/src/main/java/micronaut/ribbon/example2/HelloController.java (at line 0)
        package micronaut.ribbon.example2;
        ^
Internal compiler error: java.lang.Exception: java.lang.IllegalStateException: No value available for annotation member @io.micronaut.http.annotation.HttpMethodMapping[value] of type: class java.lang.String at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
[ERROR] Found 1 error and 0 warnings.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.252 s
[INFO] Finished at: 2018-10-06T19:05:22-07:00
[INFO] Final Memory: 17M/272M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project micronaut-ribbon-example2: Compilation failure: Compilation failure: 
[ERROR] /Users/rhasija/dev/projects/experimental/micronaut/micronaut-ribbon-example2/src/main/java/micronaut/ribbon/example2/HelloController.java: 
[ERROR] 1. ERROR in /Users/rhasija/dev/projects/experimental/micronaut/micronaut-ribbon-example2/src/main/java/micronaut/ribbon/example2/HelloController.java (at line 0)
[ERROR]         package micronaut.ribbon.example2;
[ERROR]         ^
[ERROR] Internal compiler error: java.lang.Exception: java.lang.IllegalStateException: No value available for annotation member @io.micronaut.http.annotation.HttpMethodMapping[value] of type: class java.lang.String at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
[ERROR] Found 1 error and 0 warnings.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Steps to Reproduce

1. Run `mvn clean verify` on the attached project [micronaut-ribbon-example2.zip](https://github.com/micronaut-projects/micronaut-core/files/2453565/micronaut-ribbon-example2.zip)

This is how I created the project:

`mn create-app --features annotation-api,spock,netflix-ribbon,netflix-archaius,netflix-hystrix,java,http-server,http-client,discovery-eureka --lang java --build maven micronaut-ribbon-example2`

### Expected Behaviour

The project should compile.

### Actual Behaviour

The project doesn't even compile

### Environment Information

- **Operating System**: Mac OS High Sierra ( 10.13.6 )
- **Micronaut Version:** 1.0.0.RC1
- **JDK Version:** 

```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Example Application

Already attached above.

**Comment by graemerocher** [comment]
This is a known issue and a bug in the `groovy-eclipse-compiler` for Maven

**Comment by benrhine** [comment]
In addition to having switched over to `gmavenplus` in current versions there was a bug the prevented spock tests being run on maven builds that will be fixed with this pr https://github.com/micronaut-projects/micronaut-profiles/pull/201. This is also discussed here https://github.com/micronaut-projects/micronaut-core/issues/439 and here https://github.com/micronaut-projects/micronaut-kafka/issues/12 and here https://github.com/micronaut-projects/micronaut-test/issues/90.

As for your above command, cleaning it up to `mn create-app micronaut-ribbon-example2 -b maven -f spock,netflix-archaius,netflix-hystrix,http-server,http-client,discovery-eureka` will create a runnable app.

Since this ticket using an `1.0.0.RC` version and there hasn't been any more discussion in the last 14 months I am assuming you have upgraded and solved your issue. If the above links don't help you and the incoming pr fix also does not solve your issue please feel free to re-open.

**Comment by RaviH** [comment]
@benrhine Thank you so much! Appreciate the communication! I have upgraded to 1.2.6 and the tests are working now!
