### ISSUE TITLE
Get Failed to inject value for parameter [jsonMediaTypeCodec] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice(..)

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#695]
### Steps to Reproduce

1. Run `mvn clean verify` in attached project:  [micronaut-ribbon-example2.zip](https://github.com/micronaut-projects/micronaut-core/files/2453571/micronaut-ribbon-example2.zip)

### Stacktrace:

```
19:26:15.525 [main] ERROR i.m.h.server.netty.NettyHttpServer - Error stopping Micronaut server: Failed to inject value for parameter [jsonMediaTypeCodec] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice

Message: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new EurekaAutoRegistration(Environment environment,[EurekaClient eurekaClient],EurekaConfiguration eurekaConfiguration,HeartbeatConfiguration heartbeatConfiguration,ServiceInstanceIdGenerator idGenerator) --> new AbstractEurekaClient$Intercepted(EurekaDiscoveryConfiguration discoveryConfiguration,BeanContext beanContext,[Interceptor[] interceptors]) --> new HttpClientIntroductionAdvice(BeanContext beanContext,[JsonMediaTypeCodec jsonMediaTypeCodec],LoadBalancerResolver loadBalancerResolver,List transformers)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [jsonMediaTypeCodec] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice

Message: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new EurekaAutoRegistration(Environment environment,[EurekaClient eurekaClient],EurekaConfiguration eurekaConfiguration,HeartbeatConfiguration heartbeatConfiguration,ServiceInstanceIdGenerator idGenerator) --> new AbstractEurekaClient$Intercepted(EurekaDiscoveryConfiguration discoveryConfiguration,BeanContext beanContext,[Interceptor[] interceptors]) --> new HttpClientIntroductionAdvice(BeanContext beanContext,[JsonMediaTypeCodec jsonMediaTypeCodec],LoadBalancerResolver loadBalancerResolver,List transformers)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:972)
	at io.micronaut.http.client.interceptor.$HttpClientIntroductionAdviceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1263)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2113)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2021)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:746)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1069)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1655)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1064)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:941)
	at io.micronaut.discovery.eureka.client.v2.$AbstractEurekaClient$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1263)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1780)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1550)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1530)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:864)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:964)
	at io.micronaut.discovery.eureka.registration.$EurekaAutoRegistrationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1263)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2113)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2021)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:522)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:897)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:318)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:106)
	at io.micronaut.context.LifeCycle.close(LifeCycle.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1006)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:997)
	at org.spockframework.runtime.GroovyRuntimeUtil.invokeMethod(GroovyRuntimeUtil.java:171)
	at org.spockframework.runtime.extension.builtin.AutoCleanupInterceptor.intercept(AutoCleanupInterceptor.java:58)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:475)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:197)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:192)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:96)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1536)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:864)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:964)
	... 60 common frames omitted
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.972 sec <<< FAILURE!
test hello world(micronaut.ribbon.example2.HelloControllerTest)  Time elapsed: 0.482 sec  <<< ERROR!
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [jsonMediaTypeCodec] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice

Message: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
Path Taken: new HelloClient$Intercepted(BeanContext beanContext,[Interceptor[] interceptors]) --> new HttpClientIntroductionAdvice(BeanContext beanContext,[JsonMediaTypeCodec jsonMediaTypeCodec],LoadBalancerResolver loadBalancerResolver,List transformers)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:972)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1263)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2113)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2021)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:746)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1069)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1655)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1064)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:941)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1263)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1780)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1550)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1530)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:507)
	at micronaut.ribbon.example2.HelloControllerTest.test hello world(HelloControllerTest.groovy:30)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1536)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:864)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:964)
	... 14 more
```

### Expected Behaviour

Should _not_ get `Get Failed to inject value for parameter [jsonMediaTypeCodec] of class: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice`

### Actual Behaviour

The project should run the test and give an actual error vs an injection error.

### Environment Information

- **Operating System**: Mac OS High Sierra ( 10.13.6 )
- **Micronaut Version:** 1.0.0.RC1
- **JDK Version:** 

```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Example Application

Attached in Steps to Reproduce section

**Comment by graemerocher** [comment]
This is resolved in master, the actual root cause of the issue is that you had an older version of `Jackson` on your class path that was pulled in by the wire mock stuff. See `mvn dependency:tree` for information.
