### ISSUE TITLE
Illegal character in URI caused the request to hang

### ISSUE THREAD

**Issue by ruiminamywang** [micronaut-projects/micronaut-core#7027]
### Expected Behavior

We use zalando logbook

GET /v1/mypath/[ HTTP/2
Host: localhost:8080

The response should be BAD REQUEST or NOT FOUND.

### Actual Behaviour

Two exceptions were raised in the server, and no response was returned.

```
10:21:12.491 [default-nioEventLoopGroup-1-4] ERROR i.m.http.server.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: Illegal character in path at index 11: /v1/mypath/[%20HTTP/2
java.lang.IllegalArgumentException: Illegal character in path at index 11: /v1/mypath/[%20HTTP/2
	at java.base/java.net.URI.create(URI.java:906)
	at org.zalando.logbook.netty.Request.<init>(Request.java:43)
	at org.zalando.logbook.netty.LogbookServerHandler.lambda$channelRead$0(LogbookServerHandler.java:45)
	at org.zalando.fauxpas.ThrowingConsumer.accept(ThrowingConsumer.java:19)
	at org.zalando.logbook.netty.Conditionals.runIf(Conditionals.java:17)
	at org.zalando.logbook.netty.LogbookServerHandler.channelRead(LogbookServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.URISyntaxException: Illegal character in path at index 11: /v1/mypath/[%20HTTP/2
	at java.base/java.net.URI$Parser.fail(URI.java:2966)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3137)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219)
	at java.base/java.net.URI$Parser.parse(URI.java:3178)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 32 common frames omitted
10:21:12.496 [default-nioEventLoopGroup-1-4] ERROR i.m.http.server.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: Cannot invoke "org.zalando.logbook.netty.Request.buffer(io.netty.buffer.ByteBuf)" because "this.request" is null
java.lang.NullPointerException: Cannot invoke "org.zalando.logbook.netty.Request.buffer(io.netty.buffer.ByteBuf)" because "this.request" is null
	at org.zalando.logbook.netty.LogbookServerHandler.lambda$channelRead$1(LogbookServerHandler.java:49)
	at org.zalando.fauxpas.ThrowingConsumer.accept(ThrowingConsumer.java:19)
	at org.zalando.logbook.netty.Conditionals.runIf(Conditionals.java:17)
	at org.zalando.logbook.netty.LogbookServerHandler.channelRead(LogbookServerHandler.java:49)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### Steps To Reproduce

1. Add zalando logbook to the channel pipeline.

```
@Singleton
class MyHttpLogger : BeanCreatedEventListener<ChannelPipelineCustomizer> {
    private val logbook: Logbook = Logbook.builder().build()
    override fun onCreated(event: BeanCreatedEvent<ChannelPipelineCustomizer>): ChannelPipelineCustomizer {
        val customizer = event.bean
        if (customizer.isServerChannel) {
            customizer.doOnConnect { pipeline ->
                pipeline.addAfter(
                    ChannelPipelineCustomizer.HANDLER_HTTP_SERVER_CODEC,
                    "logbook",
                    LogbookServerHandler(logbook)
                )
                pipeline
            }
        } else {
            // do nothing
        }
        return customizer
    }
}
```

2. Start the server
`bazel run <target> --jvmopt='-Dmicronaut.environments=dev -DPOSTGRES_HOSTNAME=localhost -DPOSTGRES_PORT=5678'`

4. Run request:
GET /v1/mypath/[ HTTP/2
Host: localhost:8080
`curl "http://localhost:8080/v1/mypath/[" -g`

### Environment Information

macOS Monterey 12.2.1
Kotlin 1.5
JVM target 1.8
Micronaut 3.1.4
Zalando logbook 2.14

### Version

3.1.4

**Comment by yawkat** [comment]
This looks like it's an issue that is fully on logbook's side, we can't do anything about this. The logbook channel handler should not drop messages even if they're invalid. Please report this bug with them.
