### ISSUE TITLE
GraalVM Maven test application failed for 3.4.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7036]
### Issue description

The [GraalVM Pipeline failed for 3.4.0](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/pipelines/488622138)

Steps to reproduce: 

Clone `3.4.x` branch of [`micronaut-graal-tests/micronaut-maven-graal`](https://github.com/micronaut-graal-tests/micronaut-maven-graal/tree/3.4.x)

Generate an execute native image:
```
% sdk use java 22.0.0.2.r17-grl
% ./build-native-image.sh
% target/maven
```
Do request: 

`curl -s localhost:8080/hello/Maven`

Exception shown below: 

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.4.0-SNAPSHOT)

07:14:28.244 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 336ms. Server Running: http://localhost:8080
07:14:43.845 [default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)
java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:147)
	at io.netty.handler.codec.http.HttpVersion.<clinit>(HttpVersion.java:44)
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:126)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:273)
	at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:140)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
07:14:43.847 [default-nioEventLoopGroup-1-2] WARN  i.n.c.AbstractChannelHandlerContext - An exception 'java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.codec.http.HttpVersion' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:147)
	at io.netty.handler.codec.http.HttpVersion.<clinit>(HttpVersion.java:44)
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:126)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:273)
	at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:140)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
````

**Comment by graemerocher** [comment]
@yawkat can you take a look?

**Comment by yawkat** [comment]
This is a dependency divergence issue. According to `mvn dependency:tree`, netty-common has the version 4.1.63.Final, while netty-codec-http has the version 4.1.73.Final. This is the full tree:

```
[INFO] example.micronaut:maven:jar:0.1
[INFO] +- io.micronaut:micronaut-inject:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.29:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile
[INFO] |  +- io.micronaut:micronaut-core:jar:3.4.0-SNAPSHOT:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] +- io.micronaut:micronaut-validation:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-core-reactive:jar:3.4.0-SNAPSHOT:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:3.4.14:compile
[INFO] +- io.micronaut:micronaut-http-server-netty:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-http-server:jar:3.4.0-SNAPSHOT:compile
[INFO] |  |  \- io.micronaut:micronaut-router:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-http-netty:jar:3.4.0-SNAPSHOT:compile
[INFO] |  |  +- io.micronaut:micronaut-buffer-netty:jar:3.4.0-SNAPSHOT:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.73.Final:compile
[INFO] |  |     +- io.netty:netty-resolver:jar:4.1.63.Final:compile
[INFO] |  |     \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
[INFO] |  \- io.netty:netty-codec-http:jar:4.1.73.Final:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.63.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.73.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.63.Final:compile
[INFO] |     \- io.netty:netty-codec:jar:4.1.63.Final:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.10:runtime
[INFO] |  \- ch.qos.logback:logback-core:jar:1.2.10:runtime
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
[INFO] +- io.micronaut.test:micronaut-test-junit5:jar:3.1.0:test
[INFO] |  \- io.micronaut.test:micronaut-test-core:jar:3.1.0:test
[INFO] +- io.micronaut:micronaut-http-client:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-http-client-core:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-websocket:jar:3.4.0-SNAPSHOT:compile
[INFO] |  \- io.netty:netty-handler-proxy:jar:4.1.73.Final:compile
[INFO] |     \- io.netty:netty-codec-socks:jar:4.1.63.Final:compile
[INFO] +- io.micronaut:micronaut-runtime:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-http:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-aop:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- io.micronaut:micronaut-context:jar:3.4.0-SNAPSHOT:compile
[INFO] |  \- io.micronaut:micronaut-jackson-databind:jar:3.4.0-SNAPSHOT:compile
[INFO] |     +- io.micronaut:micronaut-jackson-core:jar:3.4.0-SNAPSHOT:compile
[INFO] |     |  +- io.micronaut:micronaut-json-core:jar:3.4.0-SNAPSHOT:compile
[INFO] |     |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.6:compile
[INFO] |     |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.6:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.6:compile
[INFO] |     +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.6:compile
[INFO] |     \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.6:compile
[INFO] +- io.swagger.core.v3:swagger-annotations:jar:2.1.12:compile
[INFO] +- io.micronaut.reactor:micronaut-reactor:jar:2.2.1:compile
[INFO] +- org.graalvm.sdk:graal-sdk:jar:22.0.0.2:provided
[INFO] \- org.graalvm.nativeimage:svm:jar:22.0.0.2:provided
[INFO]    +- org.graalvm.nativeimage:objectfile:jar:22.0.0.2:provided
[INFO]    +- org.graalvm.nativeimage:pointsto:jar:22.0.0.2:provided
[INFO]    +- org.graalvm.compiler:compiler:jar:22.0.0.2:provided
[INFO]    |  \- org.graalvm.truffle:truffle-api:jar:22.0.0.2:provided
[INFO]    \- org.graalvm.nativeimage:native-image-base:jar:22.0.0.2:provided
```

The netty artifacts that use 4.1.73.Final seem to be exactly those that we declare explicitly in our micronaut-bom. However in the micronaut-bom we also import the netty-bom (of the right version, 4.1.73.Final), so I don't understand where `4.1.63.Final` comes from.

@alvarosanchez can you take a look? I'm at the end of my maven knowledge, here.

**Comment by sdelamo** [comment]
CI passed. Thanks everyone
