### ISSUE TITLE
OpenAPI and @Error local error handling

### ISSUE THREAD

**Issue by adrien-bonnin-cbp** [micronaut-projects/micronaut-core#708]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller method with a `@Error` annotation for local error handling :
https://docs.micronaut.io/latest/guide/index.html#_local_error_handling
```
@Error
HttpResponse<JsonError> jsonError(HttpRequest request, JsonParseException jsonParseException) {
```
2. Add the Swagger dependencies :
https://docs.micronaut.io/latest/guide/index.html#openapi
```
compileOnly "io.micronaut.configuration:openapi"
compile "io.swagger.core.v3:swagger-annotations"
```
3. Build the project and look for the error in the _Messages_ tab :
```
Error:Groovyc: While compiling example-micronaut_main: BUG! exception in phase 'canonicalization' in source unit '[...]\HelloController.groovy' No enum constant io.micronaut.http.HttpMethod.ERROR
```
4. Remove the `@Error` and the project build successfully.

### Expected Behaviour

The project should build when a controller method is annotated with `@Error`.

### Actual Behaviour

The project doesn't build when a controller method is annotated with `@Error`.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** RC2
- **JDK Version:** 1.8

### Example Application

- https://github.com/adrien-bonnin-cbp/micronaut-issue-swagger-error.git
- stacktrace :
```
Error:Groovyc: While compiling example-micronaut_main: BUG! exception in phase 'canonicalization' in source unit '[...]\HelloController.groovy' No enum constant io.micronaut.http.HttpMethod.ERROR
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:972)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:633)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:609)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
	[...]
```

**Comment by adrien-bonnin-cbp** [comment]
I have just seen that a RC2 version has been released, I'm checking the issue on it

**Comment by adrien-bonnin-cbp** [comment]
The issue still exists on RC2, the example application has been updated

**Comment by adrien-bonnin-cbp** [comment]
Thank you 😄
