### ISSUE TITLE
GraalVM Kotlin test failure: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.isDirectSubType(Class)

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7086]
Steps to reproduce: 

- Clone `https://github.com/micronaut-graal-tests/micronaut-kotlin-graal`
- Checkout branch `3.4.x`
- `/build-native-image.sh`

https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2208554358

```
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.isDirectSubType(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.lang.Class.lambda$getPermittedSubclasses$1(Class.java:4515)
Call path from entry point to java.lang.Class$$Lambda$2be75132e7d559d3311ef60c17018ef8bfed7d1d.test(Object): 
	at java.lang.Class$$Lambda$252/0x00000007c17d14c0.test(Unknown Source)
------------------------------------------------------------------------------------------------------------------------
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.util.Optional.ifPresent(Optional.java:178)
	at java.lang.Runtime$Version.toString(Runtime.java:1383)
	at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:344)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec[103](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2208554358#L103)2c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.isDirectSubType(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.lang.Class$$Lambda$2431/0x00000007c1af3208.test(Unknown Source)
Call path from entry point to java.lang.Class$$Lambda$baad2d1fceac85786b7b640a57cfee310b8cedc0.test(Object): 
	at java.lang.Class$$Lambda$2431/0x00000007c1af3208.test(Unknown Source)
```

**Comment by yawkat** [comment]
cant reproduce this using 22.0.0.2.r17-grl

**Comment by graemerocher** [comment]
I can't reproduce this with the current stable 22.0.0.2 release of GraalVM

**Comment by sdelamo** [comment]
This happens with BUILD-SNAPSHOT of GraalVM.
