### ISSUE TITLE
GraalVM Test fails for micronaut-kotlin-graal

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7107]
### Issue description

- Clone: [micronaut-kotlin-graal](https://github.com/micronaut-graal-tests/micronaut-kotlin-graal)
- Checkout branch 3.4.x
-  `./build-native-image.sh`

Error: 

> "No instances of kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe are allowed in the image heap as this class should be initialized at image runtime."

```
./build-native-image.sh

> Task :kaptKotlin
Note: Creating bean classes for 2 type elements

> Task :generateResourcesConfigFile
[native-image-plugin] Resources configuration written into /Users/sdelamo/github/micronaut-graal-tests/micronaut-kotlin-graal/build/native/generated/generateResourcesConfigFile/resource-config.json

> Task :nativeCompile
[native-image-plugin] Using executable path: /Users/sdelamo/.sdkman/candidates/java/22.0.0.2.r11-grl/bin/native-image
========================================================================================================================
GraalVM Native Image: Generating 'kotlin'...
========================================================================================================================
[1/7] Initializing...                                                                                    (4.8s @ 0.15GB)
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
 5 user-provided feature(s)
  - com.oracle.svm.polyglot.kotlin.KotlinFeature
  - io.micronaut.buffer.netty.NettyFeature
  - io.micronaut.context.env.hocon.nativeimage.HoconFeature
  - io.micronaut.http.netty.graal.HttpNettyFeature
  - io.micronaut.kotlin.nativeimage.KotlinFeature
[2/7] Performing analysis...  [*]                                                                       (14.3s @ 1.86GB)
  11,074 (88.93%) of 12,453 classes reachable
  15,101 (62.88%) of 24,014 fields reachable
  51,844 (68.84%) of 75,311 methods reachable
     560 classes,   233 fields, and 1,411 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe.compute() 
Parsing context:
   at kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe.compute(FqNameUnsafe.java:71)
   at kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe.shortName(FqNameUnsafe.java:141)
   at kotlin.reflect.jvm.internal.impl.name.FqName.shortName(FqName.java:88)
   at kotlin.reflect.jvm.internal.impl.name.ClassId.topLevel(ClassId.java:35)
   at kotlin.reflect.jvm.internal.impl.descriptors.runtime.structure.ReflectClassUtilKt.getClassId(reflectClassUtil.kt:66)
   at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.processAnnotation(ReflectKotlinClass.kt:165)
   at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.loadClassAnnotations(ReflectKotlinClass.kt:85)
   at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClass$Factory.create(ReflectKotlinClass.kt:56)
   at kotlin.reflect.jvm.ReflectJvmMapping.getKPackage(ReflectJvmMapping.kt:107)
   at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:120)
   at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findKotlinParameterName(KotlinNamesAnnotationIntrospector.kt:118)
   at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findImplicitPropertyName(KotlinNamesAnnotationIntrospector.kt:40)
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:531)
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:421)
------------------------------------------------------------------------------------------------------------------------
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:386)
   at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:233)
   at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
   at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
   at com.fasterxml.jackson.databind.jsontype.impl.AsDeductionTypeDeserializer.buildFingerprints(AsDeductionTypeDeserializer.java:70)
   at com.fasterxml.jackson.databind.jsontype.impl.AsDeductionTypeDeserializer.<init>(AsDeductionTypeDeserializer.java:48)
   at com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder.buildTypeDeserializer(StdTypeResolverBuilder.java:166)
   at com.fasterxml.jackson.databind.ObjectMapper$DefaultTypeResolverBuilder.buildTypeDeserializer(ObjectMapper.java:305)
   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1809)
   at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:648)
   at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4805)
   at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
   at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2941)
   at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3391)
   at io.micronaut.jackson.databind.convert.JacksonConverterRegistrar.lambda$objectToJsonNodeConverter$1(JacksonConverterRegistrar.java:127)
   at io.micronaut.jackson.databind.convert.JacksonConverterRegistrar$$Lambda$1703/0x00000007c1a0cc40.convert(Unknown Source)
   at io.micronaut.core.convert.DefaultConversionService.convert(DefaultConversionService.java:136)
   at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:93)
   at io.micronaut.context.env.DefaultPropertyPlaceholderResolver$RawSegment.getValue(DefaultPropertyPlaceholderResolver.java:208)
   at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholders(DefaultPropertyPlaceholderResolver.java:86)
   at io.micronaut.context.env.PropertySourcePropertyResolver.resolvePlaceHoldersIfNecessary(PropertySourcePropertyResolver.java:816)
   at io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:320)
   at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:139)
   at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:156)
   at io.micronaut.core.value.PropertyResolver.getProperty(PropertyResolver.java:169)
   at io.micronaut.context.DefaultApplicationContext.transformIterables(DefaultApplicationContext.java:391)
   at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:249)
   at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3090)
   at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3054)
   at io.micronaut.context.DefaultBeanContext.registerSingleton(DefaultBeanContext.java:673)
                       4.5s (22.7% of total time) in 24 GCs |    at io.micronaut.context.DefaultApplicationContext.registerSingleton(DefaultApplicationContext.java:124)
Peak RSS: 4.85GB | CPU load: 10.76
   at io.micronaut.context.ApplicationContext.registerSingleton(ApplicationContext.java:98)
------------------------------------------------------------------------------------------------------------------------
   at io.micronaut.context.ApplicationContext.registerSingleton(ApplicationContext.java:122)
Produced artifacts:
   at io.micronaut.context.DefaultApplicationContextBuilder.build(DefaultApplicationContextBuilder.java:306)
   at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
   at example.micronaut.ApplicationKt.main(Application.kt:9)
   at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:150)
   at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
   at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:141)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:315)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:286)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:364)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:487)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:556)
        at com.oracle.graal.pointsto.PointsToAnalysis$2.run(PointsToAnalysis.java:598)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:195)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:179)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe.
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:133)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:575)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:217)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:188)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:81)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:51)
/Users/sdelamo/github/micronaut-graal-tests/micronaut-kotlin-graal/build/native/nativeCompile/kotlin.build_artifacts.txt
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:84)
========================================================================================================================
        at com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
Failed generating 'kotlin' after 19.3s.
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:47)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.asConstant(LoadFieldNode.java:166)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:132)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:123)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:68)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Canonicalizable$Unary.canonical(Canonicalizable.java:101)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.SimplifyingGraphDecoder.canonicalizeFixedNode(SimplifyingGraphDecoder.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.canonicalizeFixedNode(PEGraphDecoder.java:1539)
        at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.canonicalizeFixedNode(InlineBeforeAnalysis.java:194)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.SimplifyingGraphDecoder.handleFixedNode(SimplifyingGraphDecoder.java:188)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:792)
        at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:529)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:822)
        at com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:99)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:175)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:358)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:297)
        ... 14 more
Error: Image build request failed with exit status 1
```

**Comment by sdelamo** [comment]
I tried adding: 

`kotlin-runtime/src/main/resources/META-INF/native-image/io.micronaut.kotlin/kotlin-runtime/native-image.properties`

```
Args = --initialize-at-run-time=kotlin.reflect.jvm.internal.impl.name.FqNameUnsafe
```

https://github.com/micronaut-projects/micronaut-kotlin/pull/376

Publish to Maven local and use that version in the GraalVM test app but it is still fails

**Comment by sdelamo** [comment]
@yawkat any idea? we released serde 1.0.0 and merge it 3.4.0 BOM on Friday https://github.com/micronaut-projects/micronaut-core/pull/7095

**Comment by yawkat** [comment]
i dont understand, the stack trace says the `FqNameUnsafe` is created in a code path reachable from `main`, why is it running `main` in the image initialization?

**Comment by sdelamo** [comment]
> * micronaut-kotlin-graal

this is the sample app https://github.com/micronaut-graal-tests/micronaut-kotlin-graal/tree/3.4.x

**Comment by yawkat** [comment]
yes i can reproduce it locally as well, but i know too little about graal to understand why it is happening

**Comment by graemerocher** [comment]
having a look myself

**Comment by graemerocher** [comment]
Submitted a PR, needs a new release of the Kotlin module

**Comment by sdelamo** [comment]
I will review it and release the module
