### ISSUE TITLE
Epoll native transport doesn't work on Docker

### ISSUE THREAD

**Issue by arcturuscom** [micronaut-projects/micronaut-core#7226]
### Expected Behavior

I'm trying to enable epoll native transport, but it's seems not working on docker.
when i run a container i've got this issue incompatible event loop type: io.netty.channel.nio.NioEventLoop

### Actual Behaviour

`- go to https://github.com/arcturuscom/netty demo 
- run build & run dockerfile
-  error on service startup 
` 
Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.nio.NioEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:473)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:246)
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:458)
	... 8 common frames omitted
`

### Steps To Reproduce

- go to https://github.com/arcturuscom/netty demo 
- run build & run dockerfile

### Environment Information

tested on both docker desktop & Aws EKS 
- java version : 8
- Micronaut version : 3.4.2 & 3.3.4

### Example Application

https://github.com/arcturuscom/netty

### Version

3.4.2 & 3.3.4

**Comment by yawkat** [comment]
The problem is that the parent event loop isn't configured for native transport either. This config works:

```yaml
micronaut:
  application:
    name: netty
  netty:
    event-loops:
      default:
        prefer-native-transport: true
      parent:
        prefer-native-transport: true
```

However this is quite confusing and the docs aren't clear on this either, and even arguably wrong.

**Comment by arcturuscom** [comment]
it's works now, many thanks 👍 
i understand why it's does not work before, because the parent eventloop different from the default which is normal.
i think it's important to update the doc

**Comment by arcturuscom** [comment]
@yawkat  Btw i don't know if you had a chance to take a look on the Factory class  ? i was fixing the eventLoop name because actually is always NioEventLoop. i suggest to create an enhacement concerning that.
what do you think ? if yes can i take the subject ?

**Comment by yawkat** [comment]
@arcturuscom the problem is that the thread factory is managed separately from the event loops. you could have multiple event loops in the same micronaut application, some with epoll, some without. your patch does not handle that and I dont think it's even possible to handle it.

I don't think it's a huge issue (just the thread names are different) so I don't think it's worth fixing

**Comment by graemerocher** [comment]
Triage: the issue is caused by configuring only the default Netty event loop for native transport while the parent event loop remains NIO. The documented working configuration sets `prefer-native-transport: true` for both `default` and `parent`; the reporter confirmed that workaround resolves the startup failure. Closing as not a bug, with the configuration requirement recorded.
