### ISSUE TITLE
Micronaut scheduled threads in deadlock: 2 scheduled threads deadlocked on DefaultCustomScopeRegistry.scopes and DefaultBeanContext.singletonObjects locks

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#7237]
### Expected Behavior

Deadlock should not happen in Micronaut internals.

### Actual Behaviour

In our Micronaut application, which uses:
* micronaut neo4j
* micronaut `@Scheduled`
* and other features (hopefully irrelevant)

I identified 2 Micronaut scheduled threads were locking 2 locks in opposite order, in particular:
* `DefaultCustomScopeRegistry.scopes` and
* `DefaultBeanContext.singletonObjects`
and happened to end in a deadlock.

The stacktrace of the 2 threads is 
```
"scheduled-executor-thread-3" #44 prio=5 os_prio=31 cpu=376.44ms elapsed=11638.02s tid=0x00007f782981e200 nid=0xaf03 waiting for monitor entry  [0x00007000046fe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@17.0.1/ConcurrentHashMap.java:1726)
	- waiting to lock <0x00000006008044d0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at io.micronaut.context.DefaultCustomScopeRegistry.findScope(DefaultCustomScopeRegistry.java:114)
	at io.micronaut.context.DefaultCustomScopeRegistry.findDeclaredScope(DefaultCustomScopeRegistry.java:91)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2877)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3718)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3567)
	- locked <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBeanRegistrations(AbstractInitializableBeanDefinition.java:2158)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanRegistrationsForConstructorArgument(AbstractInitializableBeanDefinition.java:1444)
	at com.appdynamics.query.lang.querysimilarity.$QueryStatisticsProperties$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	- locked <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	- locked <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2035)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1281)
	at com.appdynamics.query.lang.querysimilarity.$QueryStatisticsServiceImpl$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	- locked <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	- locked <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:124)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor$$Lambda$497/0x00000008011e68d0.run(Unknown Source)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
	at io.micrometer.core.instrument.Timer$$Lambda$502/0x00000008011e7638.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.1/Executors.java:539)
	at java.util.concurrent.FutureTask.runAndReset(java.base@17.0.1/FutureTask.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.1/ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.1/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.1/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)



"scheduled-executor-thread-1" #42 prio=5 os_prio=31 cpu=16.56ms elapsed=11638.02s tid=0x00007f7859844c00 nid=0xac03 waiting for monitor entry  [0x00007000044f8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2750)
	- waiting to lock <0x0000000600802f20> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1704)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1678)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:905)
	at io.micronaut.context.DefaultCustomScopeRegistry.lambda$findScope$1(DefaultCustomScopeRegistry.java:116)
	at io.micronaut.context.DefaultCustomScopeRegistry$$Lambda$633/0x00000008012dcee8.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@17.0.1/ConcurrentHashMap.java:1708)
	- locked <0x00000006008044d0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at io.micronaut.context.DefaultCustomScopeRegistry.findScope(DefaultCustomScopeRegistry.java:114)
	at io.micronaut.context.DefaultCustomScopeRegistry$$Lambda$632/0x00000008012dcca0.apply(Unknown Source)
	at java.util.Optional.flatMap(java.base@17.0.1/Optional.java:289)
	at io.micronaut.context.DefaultCustomScopeRegistry.findDeclaredScope(DefaultCustomScopeRegistry.java:79)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2873)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2822)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1397)
	at io.micronaut.neo4j.bolt.$Neo4jDriverFactory$BoltDriver0$Definition$Intercepted.$resolveTarget(Unknown Source)
	at io.micronaut.neo4j.bolt.$Neo4jDriverFactory$BoltDriver0$Definition$Intercepted.interceptedTarget(Unknown Source)
	at io.micronaut.neo4j.bolt.$Neo4jDriverFactory$BoltDriver0$Definition$Intercepted.isMetricsEnabled(Unknown Source)
	at com.appdynamics.query.service.client.entity.TopologyServiceClientBase.metrics(TopologyServiceClientBase.java:116)
	at com.appdynamics.query.service.infra.TopologyServiceClientMetricsService.reportMetrics(TopologyServiceClientMetricsService.java:40)
	at com.appdynamics.query.service.infra.$TopologyServiceClientMetricsService$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:126)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor$$Lambda$497/0x00000008011e68d0.run(Unknown Source)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
	at io.micrometer.core.instrument.Timer$$Lambda$502/0x00000008011e7638.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.1/Executors.java:539)
	at java.util.concurrent.FutureTask.runAndReset(java.base@17.0.1/FutureTask.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.1/ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.1/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.1/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)


```
I hope the details are irrelevant but just for clarity sake:
1. the `scheduled-executor-thread-3` is running a `@Scheduled` method on a `@Singleton` bean. I believe this got deadlocked during the initialization of that singleton
2. the `scheduled-executor-thread-1` is running a different `@Scheduled` `reportMetrics()` method on a different `@Singleton` which is accessing injected neo4j `Driver` implementation in that scheduled method.

### Steps To Reproduce

I cannot reproduce this even in our application hence I cannot provide a minimal reproducer unfortunately.

### Environment Information

```
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

### Version

3.4.1

**Comment by dstepanov** [comment]
This might be fixed by the refactoring done in 3.5.0

**Comment by stepanv** [comment]
Also note that both scheduled tasks had configured the same initial delay, which was `1m` in this particular case.
As a workaround, for now, we configure different initial delays and we can optimistically expect it won't happen.

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by graemerocher** [comment]
Triage: the report could not be reproduced even in the reporter's application, and the maintainer noted that the 3.5.0 bean-context refactoring might address the lock-order cycle. The current Core code no longer uses the old global `singletonObjects` creation-lock path described in the stack trace, while custom-scope lookups use the newer registry implementation. Closing as completed based on the refactoring; reopen with a current deadlock dump and minimal reproducer if the cycle remains.
