### ISSUE TITLE
Runtime error with Zipkin and Graal

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#725]
- Clone this repo: https://github.com/ilopmar/micronaut-zipkin-graal. It is an out-of-the-box Micronaut application with Graal and Zipkin support created with `create-app micronaut-zipkin-graal --features=tracing-zipkin,graal-native-image`
- Even if I plan to use Zipkin I've added Jaeger dependency `compile 'io.jaegertracing:jaeger-core:0.31.0'` as a workaround for https://github.com/oracle/graal/issues/705
- Use Graalvm rc7
- Build the native image with `./build-native-image.sh`
- Run it:

```
$ ./micronaut-zipkin-graal 
13:00:08.983 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.DependencyInjectionException.<init>(DependencyInjectionException.java:42)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.tracing.brave.$BraveTracerFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:870)
	at io.micronaut.tracing.brave.$BraveTracerFactory$BraveTracerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	at io.micronaut.tracing.instrument.scheduling.$ExecutorServiceInstrumenterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2171)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2102)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:751)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:521)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1000)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1968)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:155)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
	at micronaut.zipkin.graal.Application.main(Application.java:8)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.tracing.brave.BraveTracerFactory]

Message: Unresolved element found 
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.BeanInstantiationException.<init>(BeanInstantiationException.java:50)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1296)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 28 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found 
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
	at io.micronaut.tracing.brave.BraveTracerConfiguration.<init>(BraveTracerConfiguration.java:70)
	at io.micronaut.tracing.brave.$BraveTracerConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	... 33 common frames omitted
```

I've also tried modifying these dependencies from `compile` to `runtime` but the error is the same:
```
    runtime "io.zipkin.brave:brave-instrumentation-http:4.19.0"
    runtime "io.zipkin.reporter2:zipkin-reporter:2.5.0"
```

**Comment by graemerocher** [comment]
Nothing we can do about `UnsupportedFeatureError` occurrences on our side. Please report to Please report to https://github.com/oracle/graal/issues

**Comment by ilopmar** [comment]
https://github.com/oracle/graal/issues/740

**Comment by pvanassen** [comment]
I have created a substitution, which most likely will break more than it will fix, but in my very very limited project, it fixes just enough for this bug: 

```
@TargetClass(AbstractBeanDefinition.class)
final class Target_io_micronaut_context_AbstractBeanDefinition_isInnerConfiguration {

    @Substitute
    private boolean isInnerConfiguration(Class argumentType) {
        return argumentType.getName().endsWith("Configuration") &&
                !argumentType.isEnum() &&
                Modifier.isPublic(argumentType.getModifiers()) && Modifier.isStatic(argumentType.getModifiers()) &&
                argumentType.getName().indexOf('$') > -1;
    }

}
```

You can place this substitution in the MicronautSubstitutions.java file.

**Comment by ilopmar** [comment]
Project added to CI pipeline: https://gitlab.com/micronaut-projects/micronaut-graal-tests/pipelines/44148458
