### ISSUE TITLE
StackOverflow in GenericUtils when using APT with Eclipse

### ISSUE THREAD

**Issue by justin-michel-boeing** [micronaut-projects/micronaut-core#7252]
Using a gradle generated Eclipse project, I tried to compile and found the following in the Eclipse log

```
java.lang.Exception: java.lang.StackOverflowError
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:950)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:377)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:309)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:272)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.StackOverflowError
	at org.eclipse.jdt.internal.compiler.apt.model.TypeVariableImpl.getUpperBound(TypeVariableImpl.java:69)
	at io.micronaut.annotation.processing.GenericUtils.resolveTypeVariable(GenericUtils.java:442)
	at io.micronaut.annotation.processing.GenericUtils.resolveTypeVariable(GenericUtils.java:444)
	at io.micronaut.annotation.processing.GenericUtils.resolveTypeVariable(GenericUtils.java:444)
       <repeats until overflow>
```

- **Operating System**: Windows 10
- **Micronaut Version:** 3.3.1
- **JDK Version:** OpenJDK 8u265
- Eclipse Version: 2021-09 (4.21.0)

**Comment by yawkat** [comment]
Can you give an example project that reproduces this issue?

**Comment by graemerocher** [comment]
Triage: the report contains a useful Eclipse/JDT stack trace showing recursive `GenericUtils.resolveTypeVariable` calls, but no project reproducer and no current-version confirmation. Suggested fix: add cycle detection/visited type-variable tracking in the JDT resolution path and a regression fixture for the recursive-bound shape that Eclipse emits. Please attach a minimal Eclipse/APT project and confirm whether the failure persists on a supported JDK/Micronaut release.
