### ISSUE TITLE
POST multipart/form-data with declarative HTTP client fails

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-core#727]
### Steps to Reproduce

Execute following test:

```
@Client("https://api.elasticemail.com/v2/email/")
interface ElasticEmailClient {

    @Post(value = "send", produces = [MediaType.MULTIPART_FORM_DATA])
    fun send(
            apiKey: String,
            to: String,
            subject: String,
            from: String? = null,
            bodyText: String? = null
    ): Mono<Map<String, Any>>
}

class ElasticEmailTest {

    @Test
    fun testSendEmail() {
        val ctx = ApplicationContext.build().start()
        val client = ctx.getBean(ElasticEmailClient::class.java)
        val result = client.send(
                apiKey = "xxxxx",
                to = "xxxx@nmote.com",
                from = "xxxxx@nmote.com",
                subject = "Test email",
                bodyText = "Test 1 2 3"
        ).block()
    }
```

### Expected Behaviour

Declarative HTTP client should make a POST request with parameters from send method call mapped to POST request parameters.

### Actual Behaviour

Fails with following exception:

```
io.micronaut.http.multipart.MultipartException: The type java.util.LinkedHashMap is not a supported type for a multipart request body

	at io.micronaut.http.client.DefaultHttpClient.buildMultipartRequest(DefaultHttpClient.java:1846)
	at io.micronaut.http.client.DefaultHttpClient.buildNettyRequest(DefaultHttpClient.java:1393)
	at io.micronaut.http.client.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1512)
	at io.micronaut.http.client.DefaultHttpClient.lambda$null$23(DefaultHttpClient.java:1011)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1474)
		at com.nmote.elasticemail.ElasticEmailTest.testSendEmail(ElasticEmailTest.kt:40)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
		at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
		at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
		at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
		at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Environment Information

- **Operating System**: macOS 10.14
- **Micronaut Version:** 1.0.RC2
- **JDK Version:** 1.8 and 11

**Comment by jameskleeh** [comment]
It would be possible to support this type of use case, however we would need to be explicit about the types of values supported. My first instinct is to say only `java.lang.String` and `java.io.File` should be supported as values. Thoughts?

**Comment by vnesek** [comment]
I would expect this to work for any parameter type (value types, collections, optionals, perhaps reactive stream) that are supported when binding request parameters without POJOs for server side controllers. See [Form data binding in latest docs](https://docs.micronaut.io/latest/guide/index.html#formData)

This way you maintain symmetry between client and server operations which is really nice feature. You can design Operations interface and then implement it in both controller and declarative client.

**Comment by jameskleeh** [comment]
@vnesek Unfortunately that really isn't possible since a simple map of keys and values can't provide the same information that the server has. Therefore the same functionality cannot be achieved. For example if the value is a POJO, there is no way for the client to know what to do with it. Should it be encoded as JSON? XML?

**Comment by jameskleeh** [comment]
Closing this due to lack of feedback

**Comment by mostwantedv2** [comment]
Can you please re-open this issue, I need it for my project. 
We should be able to send multi-part client request using declarative syntax also.

`@Client(id = 'file-client')
interface FileClient {

    @Post(value = '/multipartUpload', produces = MediaType.MULTIPART_FORM_DATA)
    Map sendFile(MultipartBody requestBody)

}`

**Comment by tonsV2** [comment]
I'm also getting this error and have created the following stackoverflow post.

https://stackoverflow.com/questions/59283256/client-posting-multipart-form-data

**Comment by Jonathan-Zollinger** [comment]
I'm also interested in seeing support for this. I'm working with an endpoint that requires multipart/form-data for the post request
