### ISSUE TITLE
Runtime error with Jaeger and Graal

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#732]
- Clone this repo: https://github.com/ilopmar/micronaut-jaeger-graal. It is an out-of-the-box Micronaut application with Graal and Zipkin support created with `create-app micronaut-jaeger-graal --features=tracing-jaeger,graal-native-image`
- I've fixed Jaeger dependency
- I've also added `compile 'io.zipkin.brave:brave-instrumentation-http:4.19.0'` to workaround  https://github.com/oracle/graal/issues/705
- Use Graalvm rc7
- Build the native image with `./build-native-image.sh`
- Run it:

```
$ ./micronaut-jaeger-graal 
23:46:57.850 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [tracer] of class: io.micronaut.tracing.instrument.scheduling.ExecutorServiceInstrumenter

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [tracer] of class: io.micronaut.tracing.instrument.scheduling.ExecutorServiceInstrumenter

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.DependencyInjectionException.<init>(DependencyInjectionException.java:42)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.tracing.instrument.scheduling.$ExecutorServiceInstrumenterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2171)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2102)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:751)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:521)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1000)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1968)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:155)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
	at micronaut.jaeger.graal.Application.main(Application.java:8)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.tracing.instrument.scheduling.ExecutorServiceInstrumenter]

Message: io.jaegertracing.spi.SenderFactory: Provider io.jaegertracing.thrift.internal.senders.ThriftSenderFactory not found
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.BeanInstantiationException.<init>(BeanInstantiationException.java:50)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1296)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 15 common frames omitted
Caused by: java.util.ServiceConfigurationError: io.jaegertracing.spi.SenderFactory: Provider io.jaegertracing.thrift.internal.senders.ThriftSenderFactory not found
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.util.ServiceConfigurationError.<init>(ServiceConfigurationError.java:72)
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.jaegertracing.internal.senders.SenderResolver.resolve(SenderResolver.java:60)
	at io.jaegertracing.Configuration$SenderConfiguration.getSender(Configuration.java:639)
	at io.jaegertracing.Configuration$ReporterConfiguration.getReporter(Configuration.java:525)
	at io.jaegertracing.Configuration$ReporterConfiguration.access$000(Configuration.java:485)
	at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:215)
	at io.micronaut.tracing.jaeger.JaegerTracerFactory.resolveBuilder(JaegerTracerFactory.java:126)
	at io.micronaut.tracing.jaeger.JaegerTracerFactory.jaegerTracer(JaegerTracerFactory.java:88)
	at io.micronaut.tracing.jaeger.$JaegerTracerFactory$JaegerTracerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	... 20 common frames omitted
```

**Comment by ilopmar** [comment]
Test application updated. New issue reported to Graal: https://github.com/oracle/graal/issues/1024

**Comment by ilopmar** [comment]
As a workaround for the previous issue I added Zipkin dependencies. That led to another Graal issue: https://github.com/oracle/graal/issues/1025

**Comment by ilopmar** [comment]
Both Graal issues have been fixed.
