### ISSUE TITLE
GraalVM RC7 stopped working with Micronaut RC3

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#742]
### Steps to Reproduce

```
git clone git@github.com:musketyr/graal-rc7-micronaut-1.0.0.RC3-error.git
sdk install java 1.0.0-rc7-graal
sdk use 1.0.0-rc7-graal
cd graal-rc7-micronaut-1.0.0.RC3-error
./build-native-image.sh 
```

### Expected Behaviour

Native executable using GraalVM is created.

### Actual Behaviour

The exception is thrown during the execution:

```
BUILD SUCCESSFUL in 2s
10 actionable tasks: 2 executed, 8 up-to-date
Graal Class Loading Analysis Enabled.
Graal Class Loading Analysis Enabled.
Writing reflect.json file to destination: build/reflect.json
[cloud-winterboots-product:62410]    classlist:   4,087.47 ms
[cloud-winterboots-product:62410]        (cap):   1,673.04 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[cloud-winterboots-product:62410]        setup:   2,483.02 ms
[cloud-winterboots-product:62410]     analysis:   9,117.56 ms
fatal error: java.lang.ArrayStoreException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:419)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:104)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getAnnotation(HotSpotResolvedObjectTypeImpl.java:800)
	at com.oracle.svm.hosted.SVMHost.platformSupported(SVMHost.java:156)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:201)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:91)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:82)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:48)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:140)
	at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:76)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$7(NativeImageGenerator.java:713)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:59)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:713)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```

### Environment Information

- **Operating System**: MacOS HighSierra
- **Micronaut Version:** 1.0.0.RC3
- **JDK Version:**  1.0.0-rc7-graal

### Example Application

https://github.com/musketyr/graal-rc7-micronaut-1.0.0.RC3-error

**Comment by musketyr** [comment]
@graemerocher I'm sorry for the confusion, I've changed it to point to `RC2` and it still fails. I'll try to dig deeper what's the problem. I've compiled very similar application many times without problems.

**Comment by graemerocher** [comment]
I can reproduce the problem, so there is definitely a problem

**Comment by musketyr** [comment]
ok, I got the pattern. it's somehow related to which Java SDK was used to compile the application. if the application was compiled using GraalVM, e.g. by add `./gradlew clean assemble` instead of `./gradlew assemble` in the `build-native-image.sh` then it fails. when I precompiled it using Oracle JDK it works.

**Comment by musketyr** [comment]
Thanks! That was very fast!

**Comment by graemerocher** [comment]
We really need integration tests for Graal, problem is the native image tool uses too much memory for Travis 😟

**Comment by musketyr** [comment]
Indeed. I've tried to compile 1000 beans + 1000 controller app and never finished. it tried to steal 6 GB of my old laptop and hanged forever. maybe using Travis build stages to run it separately might help.
