### ISSUE TITLE
Fix bean delegates with @Primary

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#7487]
The Async Mongo Guide is failing when the application starts up with a mongo repository

The failure is:

```
io.micronaut.context.exceptions.ConfigurationException: No backing RepositoryOperations configured for repository. Check your configuration and try again
	at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:196)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:96)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at example.micronaut.FruitRepository$Intercepted.findAll(Unknown Source)
	at example.micronaut.DefaultFruitService.list(DefaultFruitService.java:19)
	at example.micronaut.FruitController.list(FruitController.java:30)
	at example.micronaut.$FruitController$Definition$Exec.dispatch(Unknown Source)
...snip...
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.mongodb.operations.MongoRepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2777)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:863)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:855)
	at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:193)
```

To reproduce, check out the `microstream` branch of `micronaut-guides`, re-enable the tests in `guides/micronaut-data-mongodb-asynchronous/metadata.json`, and then run:

```
./gradlew micronautDataMongodbAsynchronousGenerateProjects
```

A Java/Gradle project for investigation will then be in `build/code/micronaut-data-mongodb-asynchronous/micronaut-data-mongodb-asynchronous-gradle-java`

This still fails after the fix here https://github.com/micronaut-projects/micronaut-core/pull/7486 but it seems potentially related

**Comment by sdelamo** [comment]
This is still not fixed. 

PR still failing: https://github.com/micronaut-projects/micronaut-guides/pull/929

Steps to reproduce: 

- Clone https://github.com/micronaut-projects/micronaut-guides/tree/microstream
- Run `./gradlew micronautDataMongodbAsynchronousBuild`. Test still fail. 

@timyates @dstepanov could you collaborate in fixing this issue?

**Comment by timyates** [comment]
@sdelamo We believe this is now fixed the tests are running in https://github.com/micronaut-projects/micronaut-guides/pull/929

We had to apply a workaround for adding `@MicronautTest` to a spock base class... there is a PR to fix this in a patch version of Micronaut-test here:

https://github.com/micronaut-projects/micronaut-test/pull/585
