### ISSUE TITLE
Problem Building Newly Created App Using Zipkin

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-core#752]
### Steps to Reproduce

    mn create-app zipkin-app --features tracing-zipkin
    cd zipkin-app
    mn create-controller Demo

Edit `src/main/java/zipkin/app/DemoController.java`:

```java
package zipkin.app;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.HttpStatus;
import io.micronaut.tracing.annotation.NewSpan;

@Controller("/demo")
public class DemoController {

    @Get("/")
    @NewSpan("some-span")
    public HttpStatus index() {
        return HttpStatus.OK;
    }
}
```

```
$ ./gradlew run

> Task :run FAILED
16:20:55.158 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
        at io.micronaut.tracing.brave.$BraveTracerFactoryDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1303)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1861)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1597)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1577)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:873)
        at io.micronaut.tracing.brave.$BraveTracerFactory$BraveTracerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1303)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1861)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1597)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1577)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:886)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
        at io.micronaut.tracing.instrument.scheduling.$ExecutorServiceInstrumenterDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1303)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2192)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2123)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:754)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:524)
        at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1010)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1989)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:158)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
        at zipkin.app.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.tracing.brave.BraveTracerFactory]

Message: brave/handler/FinishedSpanHandler
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1317)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1861)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1597)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1577)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:886)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
        ... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: brave/handler/FinishedSpanHandler
        at io.micronaut.tracing.brave.$BraveTracerConfigurationDefinition.injectBean(Unknown Source)
        at io.micronaut.tracing.brave.$BraveTracerConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1303)
        ... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: brave.handler.FinishedSpanHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 35 common frames omitted

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/jeffbrown/.sdkman/candidates/java/8u131/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```
### Environment Information

- **Operating System**: macOs
- **Micronaut Version:** 1.0.0.RC3
- **JDK Version:** 1.8.0_131

### Example Application

https://github.com/jeffbrown/zipkin-app

**Comment by jeffbrown** [comment]
Updating `runtime "io.zipkin.brave:brave-instrumentation-http:4.19.0"` to `runtime "io.zipkin.brave:brave-instrumentation-http:5.4.1"` appears to make the problem go away.  I have not investigated or tested if there are other implications with doing that upgrade.

**Comment by ilopmar** [comment]
The correct dependencies for 1.0.0.RC3 are:
```
    runtime 'io.zipkin.brave:brave-instrumentation-http:5.4.2'
    runtime 'io.zipkin.reporter2:zipkin-reporter:2.7.9'
    compile 'io.opentracing.brave:brave-opentracing:0.33.3'
```

This issue is because the dependencies in `micronaut-core` were upgraded but not in the profile. This already has been handled by https://github.com/micronaut-projects/micronaut-core/pull/744 and https://github.com/micronaut-projects/micronaut-profiles/pull/79.
Starting with 1.0.0 GA it won't be necessary to add the version in those dependencies because we use the ones defined in the bom.
