### ISSUE TITLE
java.lang.ClassCastException thrown during context destruction.

### ISSUE THREAD

**Issue by yakom** [micronaut-projects/micronaut-core#7529]
### Expected Behavior

the Micronaut context is destroyed without an exception when using DBCP.

### Actual Behaviour

when using a context with DBCP data sources, its destruction causes: `java.lang.ClassCastException: class io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy cannot be cast to class io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration`.

it happens both during context-building tests and application runs.

### Steps To Reproduce

i've created an example application to reproduce the exception.

### Environment Information

- OS : Fedora 34
- JDK : 17.0.1

### Example Application

https://github.com/yakom/bug-report-1

### Version

3.2.2

**Comment by graemerocher** [comment]
@n0tl3ss please take a look at this one too

**Comment by n0tl3ss** [comment]
I found out that problem is in dispose method of the `io.micronaut.configuration.jdbc.dbcp.$DatasourceConfiguration$Definition` that is autogenerated. Depose method looks like this:

```
    public DatasourceConfiguration dispose(BeanResolutionContext var1, BeanContext var2, DatasourceConfiguration var3) {
        DatasourceConfiguration var4 = (DatasourceConfiguration)var3;
        super.preDestroy(var1, var2, var3);
        var4.preDestroy();
        return var4;
    }
```
it requires that var3 is type of DatasourceConfiguration class. But the dispose receives `io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy` class that is wrapper around  `DatasourceConfiguration` and have `targetDataSource` field  that is instance of `DatasourceConfiguration`. Both `DataSourceProxy` and `DatasourceConfiguration` implements the `javax.sql.DataSource` interface. 

Full stack trace:
```
16:33:24.430 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
17:36:18.326 [main] ERROR i.m.h.server.netty.NettyHttpServer - Error stopping Micronaut server: class io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy cannot be cast to class io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration (io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy and io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy cannot be cast to class io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration (io.micronaut.transaction.jdbc.TransactionAwareDataSource$DataSourceProxy and io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration are in unnamed module of loader 'app')
	at io.micronaut.configuration.jdbc.dbcp.$DatasourceConfiguration$Definition.dispose(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate$ProxyDisposableBeanDefinition.dispose(BeanDefinitionDelegate.java:348)
	at io.micronaut.inject.DisposableBeanDefinition.dispose(DisposableBeanDefinition.java:44)
	at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1143)
	at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1115)
	at io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:402)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:196)
	at io.micronaut.http.server.netty.NettyHttpServer.stopInternal(NettyHttpServer.java:601)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:327)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:112)
	at io.micronaut.test.extensions.AbstractMicronautExtension.stopEmbeddedApplication(AbstractMicronautExtension.java:403)
	at io.micronaut.test.extensions.AbstractMicronautExtension.afterClass(AbstractMicronautExtension.java:319)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.afterAll(MicronautJunit5Extension.java:125)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$14(ClassBasedTestDescriptor.java:434)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$15(ClassBasedTestDescriptor.java:434)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:434)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:216)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:149)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:149)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by dstepanov** [comment]
@n0tl3ss Can you try it with 3.5.0?

**Comment by n0tl3ss** [comment]
> @n0tl3ss Can you try it with 3.5.0?

I tried it already. Above is stack trace from the 3.5.0 version.

**Comment by graemerocher** [comment]
thanks @n0tl3ss 

@dstepanov can you take over looking at this one

**Comment by dstepanov** [comment]
It should be fixed by https://github.com/micronaut-projects/micronaut-sql/commit/d1fc4c6abc01609f0607e301b43ee49064c0f083#diff-d1825198a13f7498572209266a6307d35cc405ac00a0c201eb758f6a8132727c
