### ISSUE TITLE
GraalVM native binary throws java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by miguelaferreira** [micronaut-projects/micronaut-core#7630]
### Expected Behavior

I've built an example cli application that uses a java git library form the eclipse project called [jGit](https://www.eclipse.org/jgit/). While I can build and execute the application from a jar, I cannot build a native binary that executes correctly.

### Actual Behaviour

The native binary does not execute as the jar does, and throws the following exception:
```
22:57:00.517 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
Exception in thread "main" java.lang.Error: java.lang.NoSuchMethodException: org.eclipse.jgit.internal.JGitText.<init>()
        at org.eclipse.jgit.nls.GlobalBundleCache.lookupBundle(GlobalBundleCache.java:70)
        at org.eclipse.jgit.nls.NLS.get(NLS.java:125)
        at org.eclipse.jgit.nls.NLS.getBundleFor(NLS.java:101)
        at org.eclipse.jgit.internal.JGitText.get(JGitText.java:28)
        at org.eclipse.jgit.api.CloneCommand.verifyDirectories(CloneCommand.java:255)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:166)
        at cli.app.latest.CliAppLatestCommand.clone(CliAppLatestCommand.java:53)
        at cli.app.latest.CliAppLatestCommand.run(CliAppLatestCommand.java:36)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
        at cli.app.latest.CliAppLatestCommand.main(CliAppLatestCommand.java:28)
Caused by: java.lang.NoSuchMethodException: org.eclipse.jgit.internal.JGitText.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at org.eclipse.jgit.nls.GlobalBundleCache.lookupBundle(GlobalBundleCache.java:63)
        ... 18 more
```

### Steps To Reproduce

1. Clone the example application `git clone https://github.com/miguelaferreira/issue-micronaut-graalvm-jgit.git`
2. Build the native binary `./gradlew nativeCompile`
3. Execute the native binary `build/native/nativeCompile/cli-app-latest`

### Environment Information

- Operating System: macOS Monterey 12.4 (21F79)
- JDK: GraalVM 22.0.0.2.r17

### Example Application

https://github.com/miguelaferreira/issue-micronaut-graalvm-jgit

### Version

3.5.2

**Comment by yawkat** [comment]
Graal requires configuration to be able to use reflection, which jgit appears to do: https://docs.oracle.com/en/graalvm/enterprise/20/docs/reference-manual/native-image/Reflection/ – this is unfortunately not trivial, it's hard to say if it's feasible for jgit.

Closing since this is a graal/jgit issue, nothing we can do about that (except add our own jgit integration)

**Comment by miguelaferreira** [comment]
Thanks for getting back to me @yawkat. 

I understand that Graal needs configuration for reflection, and from [this discussion](https://github.com/micronaut-projects/micronaut-core/issues/6406#issuecomment-992610623) on another issue, I got the impression that micronaut would be responsible for fully configuring the native image compilation, and that users shouldn't try to add their own configuration. 

What I don't follow from your message is this bit
> ... which jgit appears to do

What is jGit doing?

**Comment by yawkat** [comment]
No, micronaut does not (cannot) produce the reflection config for third-party libraries that we don't explicitly add support for.

jgit is using reflection.

**Comment by miguelaferreira** [comment]
Alright! Thanks.

**Comment by dstepanov** [comment]
You can use `TypeHint` annotation in combination with annotation processor dependency `micronaut-graal` to add those entries using an annotation.

**Comment by alvarosanchez** [comment]
You can also run the JAR with GraalVM and [enable the tracing agent](https://www.graalvm.org/22.1/reference-manual/native-image/Agent/)

**Comment by miguelaferreira** [comment]
@alvarosanchez Would I then need to merge the configuration the tracer agent generates with the configuration that micronaut generates under `build/classes/java/main/META-INF/native-image/picocli-generated`?

**Comment by alvarosanchez** [comment]
What I would do is to isolate jgit in a standalone project with no Micronaut dependencies, and use the GraalVM agent in there.

**Comment by miguelaferreira** [comment]
Alright, thanks!
