### ISSUE TITLE
Replace use of FileSystems.newFileSystem(URI)

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#7654]
### Issue description

`FileSystems.newFileSystem(URI)` uses globally shared file systems and is prone to race conditions. Similar to #7653, we should adopt `FileSystems.newFileSystem(Path, ...)` instead. The only other use of these file systems seems to be `DefaultClassPathResourceLoader`.

**Comment by rainboyan** [comment]
In my new [Grails 5.2.0 demo app](https://github.com/rainboyan/grails-spring-graphql-demo), similar problems also exist in `DefaultClassPathResourceLoader `.

`java -jar grails-spring-graphql-demo-0.1.jar`:
```
2022-07-11 18:32:51.686 DEBUG --- [           main] i.m.c.i.s.DefaultClassPathResourceLoader : Error establishing whether path is a directory: /application.yml

java.nio.file.NoSuchFileException: /application.yml
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:702)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:815)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:252)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at io.micronaut.core.io.scan.DefaultClassPathResourceLoader.getResourceAsStream(DefaultClassPathResourceLoader.java:126)
	at io.micronaut.context.env.DefaultEnvironment.getResourceAsStream(DefaultEnvironment.java:327)
```
