### ISSUE TITLE
Failure executing GraalVM native image with Micronaut 3.5.3-SNAPSHOT

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7671]
### Issue description

[Download 3.5.3-SNAPSHOT App](https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=graalvm&version=3.5.3-SNAPSHOT)

Steps to reproduce: 

```
$ sdk use java 22.1.0.r11-grl     
$ ./gradlew nativeCompile 
$ ./build/native/nativeCompile/demo
09:29:28.761 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2784)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:865)
	at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1682)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:354)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:190)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:306)
	at com.example.Application.main(Application.java:7)
```

The commit to fix the Grails issues https://github.com/micronaut-projects/micronaut-core/pull/7653 is the culprit.

**Comment by graemerocher** [comment]
As I said in https://github.com/micronaut-projects/micronaut-core/pull/7620#issuecomment-1168973231 

Any fix needs to be tested on native before merging 🤷‍♂️
