### ISSUE TITLE
Module exports issue with GraalVM EE 22.2.x

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#7737]
### Expected Behavior

A project that builds fine under GraalVM CE should build fine under GraalVM EE

### Actual Behaviour

Instead, errors of the following type are observed:
```
Fatal error: java.lang.IllegalAccessError: class io.micronaut.core.graal.AutomaticFeatureUtils (in unnamed module @0x42d4de20) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x42d4de20
        at io.micronaut.core.graal.AutomaticFeatureUtils.addResourcePatterns(AutomaticFeatureUtils.java:190)
        at io.micronaut.kotlin.nativeimage.KotlinFeature.beforeAnalysis(KotlinFeature.kt:53)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

### Steps To Reproduce

1. Download a fresh Micronaut project from launch.micronaut.io with the following settings:
  - **Java version:** JDK17
  - **Language:** Kotlin
  - **Build:** Gradle Kotlin
  - **Features:** `graalvm`
2. Install [GraalVM EE](https://www.oracle.com/downloads/graalvm-downloads.html) latest (`22.2.x`). Licensing applies.
3. Install `native-image` if necessary, via `gu install native-image`. Licensing applies.
4. Within the project, run: `./gradlew :nativeCompile`
5. Observe errors above

Now, to isolate this to `22.2.x`/EE (22.x is not out yet for CE), try the following:
1. Remove your GraalVM EE installation as your active JVM
2. Install or active [GraalVM CE](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.1.0)
3. Make sure to kill any active Gradle daemons with `./gradlew --stop`
4. Within the project, run: `./gradlew :nativeCompile`
5. Observe no error

### Environment Information

- Operating System: Ubuntu 18.04 (Linux)
- Architecture: `amd64`
- JVM: GraalVM EE `22.2.0`, Java 17

### Example Application

curl --location --request GET 'https://launch.micronaut.io/create/default/com.example.demo?lang=KOTLIN&build=GRADLE_KOTLIN&test=JUNIT&javaVersion=JDK_17&features=graalvm' --output demo.zip

### Version

3.5.3

**Comment by sgammon** [comment]
I was able to work around this by adding the following flags to the `native-image` invocation:
```
-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED
-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED
```

Handy copy/paste for anyone encountering this, in Kotlin DSL:
```
graalvmNative {
  binaries {
    named("main") {
      buildArgs.addAll(listOf(
        "-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED",
        "-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED",
      ))
    }
  }
}
```

**Comment by graemerocher** [comment]
@melix related issue? Perhaps we need to update the flags?

**Comment by melix** [comment]
This is fixed in the Gradle plugin release 3.5.1.

**Comment by sgammon** [comment]
yep, updating the sample fixes it. it looks like the launcher is creating projects which use `3.4.1` still. i've updated the title of this bug accordingly, thank you for the quick response 👍🏻
