### ISSUE TITLE
Migration bump micronaut-parent from 3.5.4 to 3.6.0 - disableFork not found.

### ISSUE THREAD

**Issue by jesperancinha** [micronaut-projects/micronaut-core#7856]
### Expected Behavior

Either working or with clear breaking changes

### Actual Behaviour

It fails with an exception that mentions something about a fork method that it doesn't find. I have no idea what to do, but this looks like a bug to me:

```java
Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.6.21:kapt (kapt) on project buy-oyc-commons: Compilation failure
Error:  java.lang.NoSuchMethodError: 'io.micronaut.core.io.service.SoftServiceLoader io.micronaut.core.io.service.SoftServiceLoader.disableFork()'
Error:  	at io.micronaut.annotation.processing.TypeElementVisitorProcessor.<clinit>(TypeElementVisitorProcessor.java:70)
Error:  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Error:  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
Error:  	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
Error:  	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
Error:  	at java.base/java.lang.Class.newInstance(Class.java:645)
Error:  	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:51)
Error:  	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:44)
Error:  	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension$loadProcessors$efficientProcessorLoader$1.doLoadProcessors(Kapt3Extension.kt:86)
Error:  	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:44)
Error:  	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors$default(ProcessorLoader.kt:28)
Error:  	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.loadProcessors(Kapt3Extension.kt:92)
Error:  	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:178)
Error:  	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:102)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:115)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:125)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:301)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
Error:  	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:292)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
Error:  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
Error:  	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:172)
Error:  	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
Error:  	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
Error:  	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
Error:  	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
Error:  	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execCompiler(KotlinCompileMojoBase.java:228)
Error:  	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:237)
Error:  	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:152)
Error:  	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:44)
Error:  	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute(KotlinCompileMojoBase.java:209)
Error:  	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute(K2JVMCompileMojo.java:222)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  
Error:  
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :buy-oyc-commons
Error: Process completed with exit code 1.
```

### Steps To Reproduce

Just try to build this project on the migration branch: 

https://github.com/jesperancinha/buy-odd-yucca-concert/tree/dependabot/maven/io.micronaut-micronaut-parent-3.6.0

### Environment Information

- JDK 17
- Linux / MAC-OS

### Example Application

https://github.com/jesperancinha/buy-odd-yucca-concert/tree/dependabot/maven/io.micronaut-micronaut-parent-3.6.0

### Version

3.6.0

**Comment by sdelamo** [comment]
can you look into this @yawkat ? I know you work [on this area](https://github.com/micronaut-projects/micronaut-core/pull/7608).

**Comment by graemerocher** [comment]
the parent needs to be updated but also the `micronaut.version` property which is used to configure the annotation processors. These two versions need to be aligned

**Comment by yawkat** [comment]
yea this just looks like a version divergence

**Comment by jesperancinha** [comment]
Tks, I've just done that for the data processor and the parent. They are all dependent now on `micronaut.version`, but I'm still getting the same error. Could this be related to the maven plugin? That one is still on 3.4.0.

**Comment by yawkat** [comment]
it could be a problem. not a maven expert, but i would think the maven plugin is on the same classpath that the stack trace is reporting. so again youd be mixing micronaut versions on that classpath. what do you think @alvarosanchez?

**Comment by jesperancinha** [comment]
I'm not 100% but I think I got something on this:

The parent, `micronaut-parent` still has this:

`<micronaut-maven-plugin.version>3.4.0</micronaut-maven-plugin.version>`

And I noticed that in my environment, `micronaut-core`, version `3.4.0.`, was still creeping into the compilation and only for the annotation processors. I saw this in the dependencies on the `.m2` folder after I removed it and re-downloaded all dependencies. I noticed that both versions `3.5.4` and `3.6.0` were somehow downloaded after the first build.  So I thought about just adding `micronaut-core`, version `3..6.0` to the annotation processors. That seems to work.

This whole exercise suggests that `micronaut-core` is the problem here. I'm not sure if your intention is for developers to add this dependency to the annotation processors manually, which is tedious, or if this was a slip-up, which is what it sounds like. I still think this is a bug because the old maven plugin is still not in the parent and because there seems to be no new version of the maven plugin as it stands.

Because of these reasons I leave it open for you. My PR of the migration still doesn't succeed though but that doesn't seem to be related to micronaut at the moment.

**Comment by yawkat** [comment]
@jesperancinha it seems likely to me that this is an issue in our maven setup, but since you have a workaround, i'm going to let this issue sit until our build tools people come back from vacation.
