### ISSUE TITLE
jrebel causing routing issue - Error instantiating bean of type  [io.micronaut.web.router.DefaultRouter] 

### ISSUE THREAD

**Issue by hampsterx** [micronaut-projects/micronaut-core#786]
### Steps to Reproduce

```
mn create-app -l=kotlin -f jrebel hello-world
cd hello-world
mn create-controller hello
```
Added to gradle.properties

```
rebelAgent= -agentpath:/opt/jrebel/lib/libjrebel64.so
```
```
./gradlew run
```
```
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.web.router.DefaultRouter]

Message: No such route: hello.world.HelloController.index
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> new DefaultRouter([Collection builders])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1324)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1868)
```

### Expected Behaviour

This was working with RC2

### Environment Information

- **Micronaut Version: 1.0.0 GA

**Comment by Oja95** [comment]
Hey @hampsterx,

I'm writing from JRebel Support. If the issue only happens when JRebel is present, perhaps then you could reproduce the issue and send the stack trace and `jrebel.log` file from your `${USER_HOME}/.jrebel/` directory to support@zeroturnaround.com. We can then further look into this problem.

**Comment by graemerocher** [comment]
@Oja95 thanks for suggesting that, not sure where to even start when looking into this issue

**Comment by hampsterx** [comment]
fixed, was entirely due to misconfiguration of jrebel. apologies and much thnx to JRebel support for replicating the issue!~
