### ISSUE TITLE
Issues with reading `application.yml` properties into @ConfigurationProperties bean containing `LocalDate`

### ISSUE THREAD

**Issue by juliusz-cwiakalski** [micronaut-projects/micronaut-core#7863]
### Expected Behavior

@ConfigurationProperties beans having properties of type `java.time.LocalDate` should be mapped correctly when expressed in YAML as a string or date.

Let's say I have the following property bean:
```java
@ConfigurationProperties("jcw")
@Data
@Introspected
public class Config {

  LocalDate localDateProperty;
  List<DatesListItem> dates;

  @Builder
  @Data
  @Introspected
  public static class DatesListItem {

    private String id;
    private String stringDate;
    private Date javaUtilDate;
    private LocalDate localDate;
  }

}
```

I'd expect that all examples listed in the `actual behavior` section work properly.

## Example 1:

```yaml
jcw:
  local-date-property: 2022-01-01
```

**Result**: error `Property doesn't exist` occurs on building context

## Example 2:

```yaml
jcw:
  local-date-property: '2022-01-01'
```

**Result**: error `Unable to convert value [2022-01-01] to target type [LocalDate] due to: Text '2022-01-01' could not be parsed at index 4` occurs on building context

## Example 3:

```yaml
jcw:
  dates:
    - id: stringDate
      stringDate: 2022-01-01
    - id: javaUtilDate
      javaUtilDate: 2022-01-01
    # below entry is not mapped by micronaut because local date is specified as yaml timestamp
    # see https://yaml.org/type/timestamp.html
    - id: localDateAsDate
      localDate: 2022-01-01
    - id: localDateAsString
      localDate: '2022-01-01'
    - id: justId
```
**Result**: element with `localDate: 2022-01-01` is silently discarded

### Steps To Reproduce

see example application with failing tests: https://github.com/juliusz-cwiakalski/micronaut-properties-local-date-issue

```bash
# git clone https://github.com/juliusz-cwiakalski/micronaut-properties-local-date-issue.git
Cloning into 'micronaut-properties-local-date-issue'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 56 (delta 7), reused 56 (delta 7), pack-reused 0
Receiving objects: 100% (56/56), 57.22 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (7/7), done.


# cd ./micronaut-properties-local-date-issue


# mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] -------< pl.jcw.bugreport:micronaut-properties-local-date-issue >-------
[INFO] Building micronaut-properties-local-date-issue 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ micronaut-properties-local-date-issue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ micronaut-properties-local-date-issue ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/juliuszcwiakalski/git/bugreports/tmp/micronaut-properties-local-date-issue/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ micronaut-properties-local-date-issue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/juliuszcwiakalski/git/bugreports/tmp/micronaut-properties-local-date-issue/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ micronaut-properties-local-date-issue ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/juliuszcwiakalski/git/bugreports/tmp/micronaut-properties-local-date-issue/target/test-classes
[INFO]
[INFO] --- micronaut-maven-plugin:3.4.0:start-testresources-service (default-start-testresources-service) @ micronaut-properties-local-date-issue ---
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ micronaut-properties-local-date-issue ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running pl.jcw.bugreport.LocalDateAsYamlDateTest
10:38:16.676 [main] INFO  i.m.context.env.DefaultEnvironment -
        Established active environments: [test, property-as-date]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.692 s <<< FAILURE! - in pl.jcw.bugreport.LocalDateAsYamlDateTest
[ERROR] shouldContainLocalDateExpressedAsStringInYaml  Time elapsed: 0.016 s  <<< ERROR!
io.micronaut.context.exceptions.DependencyInjectionException:
Failed to inject value for parameter [localDateProperty] of method [setLocalDateProperty] of class: pl.jcw.bugreport.Config

Message: Failed to inject value for parameter [localDateProperty] of method [setLocalDateProperty] of class: pl.jcw.bugreport.Config

Message: Error resolving property value [jcw.local-date-property]. Property doesn't exist
Path Taken: LocalDateAsYamlDateTest.config --> Config.setLocalDateProperty([LocalDate localDateProperty])
Path Taken: LocalDateAsYamlDateTest.config --> Config.setLocalDateProperty([LocalDate localDateProperty])

[INFO] Running pl.jcw.bugreport.LocalDateAsYamlStringTest
10:38:17.115 [main] INFO  i.m.context.env.DefaultEnvironment -
        Established active environments: [test, property-as-string]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.062 s <<< FAILURE! - in pl.jcw.bugreport.LocalDateAsYamlStringTest
[ERROR] shouldContainLocalDateExpressedAsStringInYaml  Time elapsed: 0.012 s  <<< ERROR!
io.micronaut.context.exceptions.DependencyInjectionException:
Failed to inject value for parameter [localDateProperty] of method [setLocalDateProperty] of class: pl.jcw.bugreport.Config

Message: Failed to inject value for parameter [localDateProperty] of method [setLocalDateProperty] of class: pl.jcw.bugreport.Config

Message: Error resolving property value [jcw.local-date-property]. Unable to convert value [2022-01-01] to target type [LocalDate] due to: Text '2022-01-01' could not be parsed at index 4
Path Taken: LocalDateAsYamlStringTest.config --> Config.setLocalDateProperty([LocalDate localDateProperty])
Path Taken: LocalDateAsYamlStringTest.config --> Config.setLocalDateProperty([LocalDate localDateProperty])

[INFO] Running pl.jcw.bugreport.DatesOnListTest
10:38:17.197 [main] INFO  i.m.context.env.DefaultEnvironment -
        Established active environments: [test, list]
[ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.315 s <<< FAILURE! - in pl.jcw.bugreport.DatesOnListTest
[ERROR] shouldReadFiveEntriesInYaml  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError:

Expected size: 5 but was: 4 in:
[Config.DatesListItem(id=stringDate, stringDate=1640995200000, javaUtilDate=null, localDate=null),
    Config.DatesListItem(id=javaUtilDate, stringDate=null, javaUtilDate=Sat Jan 01 01:00:00 CET 2022, localDate=null),
    Config.DatesListItem(id=localDateAsString, stringDate=null, javaUtilDate=null, localDate=2022-01-01),
    Config.DatesListItem(id=justId, stringDate=null, javaUtilDate=null, localDate=null)]
	at pl.jcw.bugreport.DatesOnListTest.shouldReadFiveEntriesInYaml(DatesOnListTest.java:43)

[ERROR] shouldContainLocalDateExpressedAsDateInYaml  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError:

Expecting ArrayList:
  [Config.DatesListItem(id=stringDate, stringDate=1640995200000, javaUtilDate=null, localDate=null),
    Config.DatesListItem(id=javaUtilDate, stringDate=null, javaUtilDate=Sat Jan 01 01:00:00 CET 2022, localDate=null),
    Config.DatesListItem(id=localDateAsString, stringDate=null, javaUtilDate=null, localDate=2022-01-01),
    Config.DatesListItem(id=justId, stringDate=null, javaUtilDate=null, localDate=null)]
to contain:
  [Config.DatesListItem(id=localDateAsDate, stringDate=null, javaUtilDate=null, localDate=2022-01-01)]
but could not find the following element(s):
  [Config.DatesListItem(id=localDateAsDate, stringDate=null, javaUtilDate=null, localDate=2022-01-01)]

	at pl.jcw.bugreport.DatesOnListTest.shouldContainLocalDateExpressedAsDateInYaml(DatesOnListTest.java:32)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DatesOnListTest.shouldContainLocalDateExpressedAsDateInYaml:32
Expecting ArrayList:
  [Config.DatesListItem(id=stringDate, stringDate=1640995200000, javaUtilDate=null, localDate=null),
    Config.DatesListItem(id=javaUtilDate, stringDate=null, javaUtilDate=Sat Jan 01 01:00:00 CET 2022, localDate=null),
    Config.DatesListItem(id=localDateAsString, stringDate=null, javaUtilDate=null, localDate=2022-01-01),
    Config.DatesListItem(id=justId, stringDate=null, javaUtilDate=null, localDate=null)]
to contain:
  [Config.DatesListItem(id=localDateAsDate, stringDate=null, javaUtilDate=null, localDate=2022-01-01)]
but could not find the following element(s):
  [Config.DatesListItem(id=localDateAsDate, stringDate=null, javaUtilDate=null, localDate=2022-01-01)]

[ERROR]   DatesOnListTest.shouldReadFiveEntriesInYaml:43
Expected size: 5 but was: 4 in:
[Config.DatesListItem(id=stringDate, stringDate=1640995200000, javaUtilDate=null, localDate=null),
    Config.DatesListItem(id=javaUtilDate, stringDate=null, javaUtilDate=Sat Jan 01 01:00:00 CET 2022, localDate=null),
    Config.DatesListItem(id=localDateAsString, stringDate=null, javaUtilDate=null, localDate=2022-01-01),
    Config.DatesListItem(id=justId, stringDate=null, javaUtilDate=null, localDate=null)]
[ERROR] Errors:
[ERROR]   LocalDateAsYamlDateTest.shouldContainLocalDateExpressedAsStringInYaml » DependencyInjection
[ERROR]   LocalDateAsYamlStringTest.shouldContainLocalDateExpressedAsStringInYaml » DependencyInjection
[INFO]
[ERROR] Tests run: 7, Failures: 2, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.814 s
[INFO] Finished at: 2022-08-09T10:38:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project micronaut-properties-local-date-issue: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/juliuszcwiakalski/git/bugreports/tmp/micronaut-properties-local-date-issue/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Environment Information

- MacOS Monterey 12.5 (21G72)
- java version "17.0.2" 2022-01-18 LTS

### Example Application

https://github.com/juliusz-cwiakalski/micronaut-properties-local-date-issue

### Version

3.6.0

**Comment by ivyazmitinov** [comment]
We faced this issue too, the workaround is to set the `Format` annotation ([docs](https://docs.micronaut.io/latest/guide/index.html#configurationProperties))
![image](https://user-images.githubusercontent.com/24777841/183700627-832081b8-25a5-4134-8c46-2612925d0b77.png)

```java
public class Config {
  @Format("yyyy-MM-dd")
  LocalDate localDateProperty;
...
}
```

It is applicable only to the "text" version of the property, "date" version fails anyway. Not sure why it works this way: is there a bug or the docs should be updated?

**Comment by ivyazmitinov** [comment]
It behaves even weirder when `java.util.Date` is used instead of `java.time.LocalDate`

**Comment by GavrilovSV** [comment]
As far as I know, this behaviour is explained by the underlying usage of snakeyaml library which parses dates to `java.util.Date` instead of `java.time.LocalDate`. And Micronaut does not provide automatic conversion `java.util.Date` to `java.time.LocalDate`  even when `@Format` is applied

**Comment by juliusz-cwiakalski** [comment]
I've noticed yet another related issue - putting an invalid date string value silently discards an object if it's on the list. I'd expect that Micronaut reports it somehow or even better: throw an exception

for the below YAML example `dates` list will contain only one element (`justId`)

```yaml
jcw:
  dates:
    - id: justId
    - id: invalidLocalDateAsString
      # 31st of April does not exist - Micronaut should throw an error or at least log this issue
      localDate: '2022-04-31'

```
