### ISSUE TITLE
DataSourceTransactionManagerFactory is being auto-configured

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#787]
**Micronaut  version**: 1.0.0

Hi,

I think I have found a possible bug. 

**Bigger context**: 

I have created a redis library using micronaut and I want to use it in a Spring Boot project. I want micronaut to provide `Bean`s (Singleton, Context, etc) that I have configured in `micronaut-redis-library` and that should be it. 

But, micronaut is trying to configure: `io.micronaut.spring.tx.datasource.DataSourceTransactionManagerFactory` and the reason why it’s trying to do is because: both the conditions below are satisfied. 

```
@Factory
@Requires(classes = DataSourceTransactionManager.class)
@Requires(condition = HibernatePresenceCondition.class)
public class DataSourceTransactionManagerFactory {
...
}
```

My `MicronautBeanProcessor` config:

```
@Bean
    public MicronautBeanProcessor beanProcessor() {
        return new MicronautBeanProcessor(Context.class, Singleton.class);
    }
```

Notice that in the stacktrace below Micronaut is trying to create `org.springframework.jdbc.datasource.DataSourceTransactionManager` but there’s no `DataSource` I want configured via `micronaut`. I have `mysql` datasource configured in Spring and I want Spring to answer to that. 

**Recommended Solution**

Do not autoconfigure `DataSourceTransactionManager` if a given property is present:

`io.micronaut.datasource.disabled`

_Stacktrace:_

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.jdbc.datasource.DataSourceTransactionManager': FactoryBean threw exception on object creation; nested exception is io.micronaut.context.exceptions.BeanInstantiationException: Could Not Create Bean [class org.springframework.jdbc.datasource.DataSourceTransactionManager]
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1182)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1325)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1291)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721)
    ... 64 more
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Could Not Create Bean [class org.springframework.jdbc.datasource.DataSourceTransactionManager]
    at io.micronaut.spring.beans.MicronautSpringBeanFactory.getObject(MicronautSpringBeanFactory.java:67)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
    ... 76 more
```

**Screenshot**

![image](https://user-images.githubusercontent.com/141136/47536564-aa049380-d875-11e8-854c-27fa5c69c891.png)

**Comment by graemerocher** [comment]
Please upload a sample to GitHub that reproduces the issue

**Comment by RaviH** [comment]
@graemerocher Here's the sample project showing the error:

https://github.com/RaviH/using-micronaut-in-spring-error

Please run `mvn spring-boot:run -o`

And here's the PR with the fix: https://github.com/micronaut-projects/micronaut-core/pull/792

**Comment by RaviH** [comment]
Finally: this looks good: https://github.com/micronaut-projects/micronaut-core/pull/794
