### ISSUE TITLE
Stackoverflow error when compiling kotlin micronaut project

### ISSUE THREAD

**Issue by nicholasq** [micronaut-projects/micronaut-core#7894]
### Expected Behavior

I expect the project to compile.

### Actual Behaviour

Get a stackoverflow error.

```
Caused by: java.lang.StackOverflowError
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1410)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.apiComplete(Symbol.java:688)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.getKind(Symbol.java:1476)
	at io.micronaut.inject.processing.JavaModelUtils.resolveKind(JavaModelUtils.java:76)
	at io.micronaut.inject.processing.JavaModelUtils.resolveKind(JavaModelUtils.java:94)
	at io.micronaut.inject.processing.JavaModelUtils.isInterface(JavaModelUtils.java:108)
	at io.micronaut.inject.processing.JavaModelUtils.isClassOrInterface(JavaModelUtils.java:148)
	at io.micronaut.annotation.processing.ModelUtils.classElementFor(ModelUtils.java:75)
	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.resolveBoundGenerics(AbstractJavaElement.java:473)
	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.resolveTypeVariable(AbstractJavaElement.java:451)
	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.mirrorToClassElement(AbstractJavaElement.java:389)
```

### Steps To Reproduce

To reproduce:
```
git clone https://github.com/nicholasq/jewelry-store-service.git

./gradlew clean assemble
```

### Environment Information

MacOS Monterey 12.5
Kotlin 1.6.10
Micronaut 3.5.1

### Example Application

https://github.com/nicholasq/jewelry-store-service.git

### Version

3.5.1

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
