### ISSUE TITLE
GraalVM  FasterXML - Exception

### ISSUE THREAD

**Issue by ThraaxSession** [micronaut-projects/micronaut-core#8108]
### Expected Behavior

I can build a `nativeBuild` with KMongo/MongoDB.

### Actual Behaviour

```
02.10.2022 19:13:48.692 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `technology.iatlas.spaceup.dto.db.Server` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@61521674; pos: 0]
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `technology.iatlas.spaceup.dto.db.Server` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@61521674; pos: 0]
        at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:70)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:722)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
        at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:213)
        at technology.iatlas.spaceup.core.interceptor.InstalledInterceptor.intercept(InstalledInterceptor.kt:65)
```

### Steps To Reproduce

```
import com.fasterxml.jackson.annotation.JsonProperty

data class Server(
    @field:JsonProperty("installed")
    val installed: Boolean? = false,
    @field:JsonProperty("apiKey")
    val apiKey: String?
)
```

### Environment Information

Micronaut 3.7.1
Kotlin 1.7.20
GraalVM 22.2.0

### Version

3.7.1

**Comment by graemerocher** [comment]
Add `@ReflectiveAccess` to the type
