### ISSUE TITLE
Micronaut Client slow, occasional ReadTimeoutException

### ISSUE THREAD

**Issue by kevind-wgu** [micronaut-projects/micronaut-core#8113]
### Expected Behavior

I expected that using a Micronaut Http Client would return results at a similar speed as compared with using `java.net.http.HttpClient`.

### Actual Behaviour

Comparing side by side with a direct HttpClient GET request and a Micronaut Client request the micronaut client is consistently 3-4 times slower.

- Test Application
  - java.net.http.HttpClient - 30-40 ms
  - io.micronaut.http.client.annotation.Client - 90-100 ms
- Production Application
  - java.net.http.HttpClient - 80-100 ms
  - io.micronaut.http.client.annotation.Client - 400-500 ms

I also found that the micronaut client occasionally throws a read timeout exception after hanging for 10-20 seconds. On my aws fargate instance this happens quite often. On my local box it only happens once per 30-40 requests.

`
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$exchangeImpl$44(DefaultHttpClient.java:1378)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onError(ReactorSubscriber.java:64)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

### Steps To Reproduce

1. Checkout https://github.com/kevind-wgu/mn-client-test
2. mvn clean install
3. java -jar target/mn-0.1.jar
4. curl "localhost:8080/book/direct"  (run multiple times)
5. curl "localhost:8080/book/micronaut" (run multiple times)

I have found the direct HttpClient takes about 30-40 ms to download, convert to Book object and return it.
I have found the Micronaut Client takes about 100ms to download and return a string. 
- I failed to get the micronaut client to convert the string to an object. I kept getting a `io.micronaut.http.codec.CodecException: Cannot decode bytes with value` and couldn't figure out why so I gave up assuming that returning a String instead of a Book object should be faster anyway.

### Environment Information

MacOS - Monterey, 12.5.1
Java - openjdk version "17.0.3" 2022-04-19 LTS
Maven - Apache Maven 3.6.3

### Example Application

https://github.com/kevind-wgu/mn-client-test

### Version

3.6.0

**Comment by jameskleeh** [comment]
You're blocking the event loop so that is the likely cause of the read timeouts

**Comment by kevind-wgu** [comment]
Can the Micronaut HttpClient be used in non-reactive style coding without blocking the event loop?

**Comment by graemerocher** [comment]
@kevind-wgu yes you have to re-configure the client to run on a separate event loop. See https://docs.micronaut.io/latest/guide/#clientConfiguration

**Comment by kevind-wgu** [comment]
@graemerocher Thank you for the link. I will take a look.

**Comment by kevind-wgu** [comment]
I made the changes recommended in the docs and it gets rid of the random ReadTimeout exceptions. It continues to be a little over twice as slow (80-100ms instead of 20-40).  Maybe that is expected?

Here are the changes I made to application.yml
```
micronaut:
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      event-loop-group: other
```

**Comment by rgogulakrishnan** [comment]
I am also facing this exact problem in my OCI instances where I get too many read timeouts exactly after 11s. 

Setting @ExecuteOn(TaskExecutors.IO) on controller solved the time out. But it's blocking way of doing I guess.

**Comment by ross-oreto** [comment]
Can also confirm this is happening. I'm using the httpClient in a @Scheduled controller method. Have tried with a different event loop group and also using @ExecuteOn, neither prevented the read timeout and I have the client read timeout set to "30s" which is plenty for what I'm calling.

**Comment by aseychell** [comment]
We are experiencing the same issue on micronaut 4.1 and it was not happening on 3.8 before.  We are experiencing this issue when running in a `@Scheduled` method, subscribing on a bounded elastic scheduler and blocking.  It does not happen for every invocation but happens quite regularly.

**Comment by aseychell** [comment]
Following further investigation, I'm noticing that many HTTP requests keep the thread blocked indefinitely in the bounded elastic pool and never finish, hence the read timeout is raised since the response is not processed.  I replicated this issue both on http/1 and http/2 connections.  The only way which is not causing this issue is by using the JDK HTTP client instead of the netty client.

**Comment by graemerocher** [comment]
@aseychell can you provide a reproducer in an issue report?

**Comment by aseychell** [comment]
Sure, I will submit a simple project to reproduce it.

In the meantime, I think I managed to drill a bit deeper and instead of switching to the JDK HTTP client, I disabled the connection pool to fix the issue.  I used the configuration `micronaut.http.services.*.pool.enabled=false` maybe this helps investigating.  

With some debugging, I went a bit deeper in the method `addPendingRequest` in the `PoolResizer`.
<img width="1121" alt="image" src="https://github.com/micronaut-projects/micronaut-core/assets/339626/33a12233-73e2-4614-bb1a-f7240af2fc6c">
The size of `pendingRequests` continues increasing so it also seems that whenever a client read timeout is shown, these are leaking in the pendingRequests queue.

I hope this helps, and let me know if I can provide more info.

**Comment by graemerocher** [comment]
@yawkat does this sound like any other bug that was recently fixed around the pooling implementation

**Comment by aseychell** [comment]
I created a replication project at this link: https://github.com/aseychell/micronaut4-http-readtimeouts

Would you prefer I open a separate issue?

**Comment by graemerocher** [comment]
yes please open a separate issue

**Comment by aseychell** [comment]
Opened separate issue:  #9933

**Comment by markahlemeier** [comment]
Noticed in some of the suggestions here that we should try 

micronaut:
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      event-loop-group: other
      
 but when trying this we get an http error: `Specified event loop group is not defined: other` seems perhaps this isn't supported?

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by graemerocher** [comment]
Triage: this report is a duplicate of #9933, which tracked the same Micronaut HTTP client connection-pool progress/read-timeout failure and was closed after fixes released in Core 4.1.11 / Platform 4.1.6. The original report has no current reproducer, so please reopen with a supported-version benchmark if the timeout still occurs after those fixes.
