### ISSUE TITLE
Consul support for Graal-RC7 is not working witn Micronaut 1.0.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#815]
**NOTE: This was working with RC2**

- Clone this repo https://github.com/ilopmar/micronaut-1.0.0-consul-graal-rc7
- Generate the fatjar `./gradlew assemble`
- Build the docker image `docker build . -t micronaut-graal-consul`

```
$ docker build . -t micronaut-graal-consul
Sending build context to Docker daemon  65.79MB
Step 1/7 : FROM oracle/graalvm-ce:1.0.0-rc7
 ---> 190460ed2a63
Step 2/7 : EXPOSE 8080
 ---> Using cache
 ---> 6d5e673122d8
Step 3/7 : COPY build/libs/*-all.jar mn-graal-consul.jar
 ---> 7efb973e58a0
Step 4/7 : ADD . build
 ---> 3a29c896eca1
Step 5/7 : RUN java -cp mn-graal-consul.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
 ---> Running in d84b99545d03
Graal Class Loading Analysis Enabled.
Graal Class Loading Analysis Enabled.
Writing reflect.json file to destination: build/reflect.json
Removing intermediate container d84b99545d03
 ---> d29d4e90086b
Step 6/7 : RUN native-image --no-server              --class-path mn-graal-consul.jar 			 -H:ReflectionConfigurationFiles=build/reflect.json 			 -H:EnableURLProtocols=http 			 -H:IncludeResources="logback.xml|application.yml|META-INF/services/*.*" 			 -H:Name=mn-graal-consul 			 -H:Class=mn.graal.consul.Application 			 -H:+ReportUnsupportedElementsAtRuntime 			 -H:+AllowVMInspection 			 --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' 			 --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom
 ---> Running in 182acbc97ecf
[mn-graal-consul:8]    classlist:   9,740.09 ms
[mn-graal-consul:8]        (cap):   1,112.86 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[mn-graal-consul:8]        setup:   2,328.61 ms
Warning: class initialization of class io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator failed with exception java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider. This class will be initialized at runtime because option --report-unsupported-elements-at-runtime is used for image building. Use the option --delay-class-initialization-to-runtime=io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator failed with exception java.lang.ExceptionInInitializerError. This class will be initialized at runtime because option --report-unsupported-elements-at-runtime is used for image building. Use the option --delay-class-initialization-to-runtime=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.ReferenceCountedOpenSslEngine failed with exception java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSL. This class will be initialized at runtime because option --report-unsupported-elements-at-runtime is used for image building. Use the option --delay-class-initialization-to-runtime=io.netty.handler.ssl.ReferenceCountedOpenSslEngine to explicitly request delayed initialization of this class.
[mn-graal-consul:8]     analysis:  55,328.48 ms
error: No instances are allowed in the image heap for a class that is initialized or reinitialzied at image runtime: sun.security.provider.NativePRNG
Detailed message:
Error: No instances are allowed in the image heap for a class that is initialized or reinitialzied at image runtime: sun.security.provider.NativePRNG
Trace: 	object java.security.SecureRandom
	method com.sun.jndi.dns.DnsClient.query(DnsName, int, int, boolean, boolean)
Call path from entry point to com.sun.jndi.dns.DnsClient.query(DnsName, int, int, boolean, boolean): 
	at com.sun.jndi.dns.DnsClient.query(DnsClient.java:178)
	at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
	at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:129)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
	at io.micronaut.discovery.client.DnsResolver.getCNamesFromTxtRecord(DnsResolver.java:59)
	at io.micronaut.discovery.client.EndpointUtil.getEC2DiscoveryUrlsFromZone(EndpointUtil.java:197)
	at io.micronaut.discovery.client.EndpointUtil.getServiceUrlsFromDNS(EndpointUtil.java:141)
	at io.micronaut.discovery.client.EndpointUtil.getServiceUrlsFromDNS(EndpointUtil.java:65)
	at io.micronaut.discovery.client.DiscoveryServerInstanceList.getInstances(DiscoveryServerInstanceList.java:61)
	at io.micronaut.http.client.loadbalance.ServiceInstanceListRoundRobinLoadBalancer.select(ServiceInstanceListRoundRobinLoadBalancer.java:42)
	at io.micronaut.http.client.DefaultHttpClient.resolveRequestURI(DefaultHttpClient.java:1091)
	at io.micronaut.http.client.DefaultHttpClient$8.channelRead0(DefaultHttpClient.java:1577)
	at io.micronaut.http.client.DefaultHttpClient$8.channelRead0(DefaultHttpClient.java:1550)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:475)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002ethread_002eJavaThreads_0024ThreadStartData_0029(generated:0)

Error: Image building with exit status 1
The command '/bin/sh -c native-image --no-server              --class-path mn-graal-consul.jar 			 -H:ReflectionConfigurationFiles=build/reflect.json 			 -H:EnableURLProtocols=http 			 -H:IncludeResources="logback.xml|application.yml|META-INF/services/*.*" 			 -H:Name=mn-graal-consul 			 -H:Class=mn.graal.consul.Application 		 -H:+ReportUnsupportedElementsAtRuntime 			 -H:+AllowVMInspection 			 --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' 			 --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom' returned a non-zero code: 1
```
The class `io.micronaut.discovery.client.DnsResolver` was created on October 19th to fix #740 so probably that fix broke Consul support for Graal.
Please note that commenting out the dependency `compile "io.micronaut:micronaut-discovery-client"` allows create the image correctly.

**Comment by ilopmar** [comment]
Adding `com.sun.jndi.dns.DnsClient` to `--delay-class-initialization-to-runtime` makes it work but I'm not sure if this is the correct way to solve this issue or maybe we need to change anything else on Micronaut.

@graemerocher if you confirm me this is how we solve it I'll add a PR to micronaut-profiles to include the option.

**Comment by ilopmar** [comment]
Thanks. PRs submitted.
