### ISSUE TITLE
ClosedChannelException using micronaut declarative rest client

### ISSUE THREAD

**Issue by knvijay** [micronaut-projects/micronaut-core#8188]
### Expected Behavior

we use micronaut declarative rest client to invoke different https endpoints (using Post operation with a json payload). These rest client operations are expected to work fine (without experiencing any ClosedChannelException).

### Actual Behaviour

Under stress tests, the rest client invocation sometimes results in java.nio.channels.ClosedChannelException with the following stack trace.
  java.nio.channels.ClosedChannelException: null
  at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)

### Steps To Reproduce

micronautVersion=3.4.1
Invoke Post operation with json payload against different https endpoints (as part of a stress test)
See the exception when retrieving result
  java.nio.channels.ClosedChannelException: null
  at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)

### Environment Information

JDK 11

### Version

3.4.1

**Comment by sdelamo** [comment]
@yawkat 👆🏻

**Comment by sdelamo** [comment]
I think this is related to it https://github.com/micronaut-projects/micronaut-core/pull/8149

@knvijay can you try 3.7.2  ?

**Comment by sdelamo** [comment]
Closing it for now. @knvijay let use know if this issue is still present.
