### ISSUE TITLE
io.micronaut.http.cookie.SameSiteConverter cannot be cast to io.micronaut.http.server.netty.NettyServerCustomizer$Registry

### ISSUE THREAD

**Issue by TristanSpeakEasy** [micronaut-projects/micronaut-core#8191]
### Expected Behavior

Configuring a Netty Server Pipeline according to the docs https://docs.micronaut.io/snapshot/guide/index.html#nettyServerPipeline and importing it with the `@Import` annotation https://docs.micronaut.io/latest/guide/#beanImport should result in it being successfully setup and able to be used for request logging and other similar tasks.

### Actual Behaviour

When Importing an external `NettyServerCustomizer` I got this error:

```
15:50:32.717 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: io.micronaut.http.cookie.SameSiteConverter cannot be cast to io.micronaut.http.server.netty.NettyServerCustomizer$Registry
java.lang.ClassCastException: io.micronaut.http.cookie.SameSiteConverter cannot be cast to io.micronaut.http.server.netty.NettyServerCustomizer$Registry
        at dev.speakeasyapi.micronaut.SpeakeasyNettyServerCustomizer.onCreated(SpeakeasyNettyServerCustomizer.java:14)
        at dev.speakeasyapi.micronaut.SpeakeasyNettyServerCustomizer.onCreated(SpeakeasyNettyServerCustomizer.java:9)
        at io.micronaut.context.DefaultBeanContext.triggerBeanCreatedEventListener(DefaultBeanContext.java:2407)
        at io.micronaut.context.DefaultBeanContext.postBeanCreated(DefaultBeanContext.java:2385)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2309)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3511)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3457)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3427)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:484)
        at io.micronaut.context.DefaultApplicationContext.initializeTypeConverters(DefaultApplicationContext.java:520)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:248)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
        at hello.world.Application.main(Application.java:10)
```

It seems the:

```@Override
    public NettyServerCustomizer.Registry onCreated(BeanCreatedEvent<NettyServerCustomizer.Registry> event) {
        NettyServerCustomizer.Registry registry = event.getBean();
        registry.register(new Customizer(null)); //
        return registry;
    }
```

received the wrong bean.

When using a `NettyServerCustomizer` that was defined directly in the application it worked. So it seems the @Import annotation is causing something strange to happen.

### Steps To Reproduce

1. In a micronaut hello-world example
2. Try to import an external implementation of a `NettyServerCustomizer`
3. Observe the above error

### Version

3.7.2

**Comment by TristanSpeakEasy** [comment]
Okay so I assumed some of this was due to me importing a fat jar, but now I get this problem:

```
> Task :compileJava FAILED
/home/trist/workspace/speakeasy-java-test-service/micronaut/src/main/java/hello/world/Application.java:8: error: Cannot create associated bean with no accessible primary constructor. Consider supply the constructor with createWith(..)
public class Application {
       ^
Note: Creating bean classes for 4 type elements
1 error

FAILURE: Build failed with an exception.
```

**Comment by graemerocher** [comment]
as described in the error you are probably trying to import a bean that has a constructor that is either package private or inaccessible

**Comment by TristanSpeakEasy** [comment]
Thanks for the hint, I got the import statement to work without erroring, I had to separate the classes I am importing from other internal classes for the lib into separate packages.

I still have an issue where the filters, servercustomisers and other classes that use annotations don't seem to be being injected as expected but that is another issue
