### ISSUE TITLE
Around Advice: Error instantiating bean of type - Multiple possible bean candidates found

### ISSUE THREAD

**Issue by TristanSpeakEasy** [micronaut-projects/micronaut-core#8194]
### Expected Behavior

Following the documentation for adding an Around Advice Annotation https://docs.micronaut.io/latest/guide/index.html#aroundAdvice in the hello-world project results in working Around Advice

### Actual Behaviour

Following the documentation for adding an Around Advice Annotation https://docs.micronaut.io/latest/guide/index.html#aroundAdvice and adding the example NotNull annotation to the HelloController in the hello-example resulted in the below error at runtime:

```
11:35:04.780 [boundedElastic-1] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type  [hello.world.$HelloController$Definition$Intercepted]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new $HelloController$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [hello.world.$HelloController$Definition$Intercepted]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new $HelloController$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1583)
        at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:559)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:236)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472)
        at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:488)
        at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058)
        at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
        at io.micronaut.aop.chain.InterceptorChain.resolveInterceptors(InterceptorChain.java:205)
        at io.micronaut.aop.chain.InterceptorChain.resolveAroundInterceptors(InterceptorChain.java:125)
        at hello.world.$HelloController$Definition$Intercepted.<init>(Unknown Source)
        at hello.world.$HelloController$Definition$Intercepted$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        ... 40 common frames omitted
```

### Steps To Reproduce

1. Follow the docs to create a hello-world application https://docs.micronaut.io/latest/guide/index.html#creatingServer
2. Follow the docs to create NotNull Around Advice https://docs.micronaut.io/latest/guide/index.html#aroundAdvice
3. Apply the annotation to the `index` method in the `HelloController`
4. Run the server via `gradle run`
5. Curl `http://localhost:8080/hello`
6. Observe the above error

### Version

3.7.2

**Comment by graemerocher** [comment]
Hmm can you attach your example?

**Comment by TristanSpeakEasy** [comment]
Thanks @graemerocher for taking a look here is the example repo https://github.com/TristanSpeakEasy/micronautexample

I realized putting together a minimal example the error above doesn't happen just with the hello-world example and the annotation example.

but is caused when compiling in a library we are currently building to add some middleware to micronaut you can see that code here https://github.com/speakeasy-api/speakeasy-java-sdk/tree/feature/spe-608/src/main/java/dev/speakeasyapi/micronaut

We are trying to add a `NettyServerCustomizer.Registry` from an external lib which might mean this is related to https://github.com/micronaut-projects/micronaut-core/issues/8191

**Comment by graemerocher** [comment]
This error could happen if you have multiple versions of the `micronaut-aop` module on your classpath or if you are including a fat jar containing duplicate classes. Perhaps check that is not the case.

**Comment by TristanSpeakEasy** [comment]
> This error could happen if you have multiple versions of the `micronaut-aop` module on your classpath or if you are including a fat jar containing duplicate classes. Perhaps check that is not the case.

Thanks I will start digging around the dependencies, we do have everything pinned to the same version but will look into what else might be duplicated

**Comment by TristanSpeakEasy** [comment]
So working through this trying to understand what is conflicting and causing the issues, I was able to get it to a minimal reproducible where I wasn't even using any micronaut code in the external lib and it was just the inclusion of:

`implementation 'io.micronaut:micronaut-http-server:3.7.2'`

as a dependency in my lib that causes the above issue.

If I remove it then the Around Advice works without the above error.

I was including this dependency originally as I am trying to define a `NettyServerCustomizer` in my external lib, which I can't currently get working because of https://github.com/micronaut-projects/micronaut-core/issues/8191

**Comment by graemerocher** [comment]
can you provide a link to the reproducer?

**Comment by TristanSpeakEasy** [comment]
Example service here: https://github.com/TristanSpeakEasy/micronautexample
The library being included:  https://github.com/speakeasy-api/speakeasy-java-sdk/tree/feature/spe-608 (specifically this branch with the WIP work for micronaut)

The example service imports a jar built from the `speakeasy-java-sdk` :

```
implementation files('./src/main/resources/speakeasy-java-sdk-1.2.3-plain.jar')
```

which currently is not using any micronaut dependencies (the classes are commented out) but is including the line:

`implementation 'io.micronaut:micronaut-http-server:3.7.2'`

in its `build.gradle` file which causes the above error

**Comment by graemerocher** [comment]
you seem to be creating a fat jar out of your speakeasy-java-sdk which is likely what is causing the problem with the Micronaut classes duplicated within `speakeasy-java-sdk-1.2.3-plain.jar`

**Comment by TristanSpeakEasy** [comment]
Thank you so much for the help. I had to learn what a fat jar is (I'm not a native java dev) but think I found out how to fix it.
