### ISSUE TITLE
MQTT build against Micronaut 4.0.0-SNAPSHOT doesn't create MqttIntroductionAdvice

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#8355]
When running the mqttv3 tests for the `micronaut-4` branch of mqtt, ie: this one

https://github.com/micronaut-projects/micronaut-mqtt/blob/micronaut-4/mqttv3/src/test/groovy/io/micronaut/mqtt/bind/id/V3IdBindingSpec.groovy

It fails with an exception

```
All possible Introduction advise exhausted and no implementation found for method: void send()
io.micronaut.aop.exceptions.UnimplementedAdviceException: All possible Introduction advise exhausted and no implementation found for method: void send()
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:126)
	at app//io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:91)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.mqtt.test.bind.id.IdBindingSpec.test id binding(IdBindingSpec.groovy:36)
```

When debugging, before 4.0.0 inside `MethodInterceptorChain.proceed` there were 2 introductions, the RecoveryIntroduction and a MqttIntroductionAdvice

However for 4.0.0-SNAPSHOT, there's only the recovery advice

Java 17
Micronaut 4.0.0-SNAPSHOT

**Comment by timyates** [comment]
The issue was that `mqtt-core/src/main/java/io/micronaut/mqtt/intercept/AbstractMqttIntroductionAdvice.java` used Caffeine as a cache, and this was not an `api` dependency

I'll leave this issue open as a placeholder for a better error message when we encounter this kind of failure
