### ISSUE TITLE
Native Image build fails after upgrade to Micronaut 3.8.0 

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#8552]
### Expected Behavior

The Docker image should be built w/o any error.

### Actual Behaviour

See problem description below.

### Steps To Reproduce

given the following generated `DockerfileNative` 

```Dockerfile
FROM ghcr.io/graalvm/native-image:ol7-java17-22.2.0 AS graalvm
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN mkdir /home/app/config-dirs
COPY config-dirs/generateResourcesConfigFile /home/app/config-dirs/generateResourcesConfigFile
RUN native-image -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar --no-fallback -H:Name=application -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jni=ALL-UNNAMED -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -H:ConfigurationFileDirectories=/home/app/config-dirs/generateResourcesConfigFile -H:Class=ch.onstructive.salessystem.Application
FROM frolvlad/alpine-glibc:alpine-3.12
RUN apk --no-cache update && apk add libstdc++
EXPOSE 8080
HEALTHCHECK CMD curl -s localhost:8080/endpoints/health | grep '"status":"UP"'
COPY --from=graalvm /home/app/application /app/application
ENTRYPOINT ["/app/application"]
```

The build of the Docker image fails with the following error regarding Logback.

```
#17 8.263 [1/7] Initializing...                                                                                    (7.3s @ 0.52GB)
#17 8.263  Version info: 'GraalVM 22.2.0 Java 17 CE'
#17 8.263  Java version info: '17.0.4+8-jvmci-22.2-b06'
#17 8.263  C compiler: gcc (redhat, aarch64, 4.8.5)
#17 8.263  Garbage collector: Serial GC
#17 8.264  8 user-specific feature(s)
#17 8.264  - ch.onstructive.salessystem.graalvm.SalesServerHibernateFeature
#17 8.264  - io.micronaut.buffer.netty.NettyFeature
#17 8.264  - io.micronaut.configuration.hibernate.jpa.graal.HibernateFeature
#17 8.264  - io.micronaut.core.graal.ServiceLoaderFeature
#17 8.264  - io.micronaut.flyway.graalvm.FlywayFeature
#17 8.264  - io.micronaut.http.netty.graal.HttpNettyFeature
#17 8.264  - io.micronaut.jackson.JacksonDatabindFeature
#17 8.264  - io.micronaut.jdbc.nativeimage.JdbcFeature
#17 32.43 [2/7] Performing analysis...  [*]                                                                       (23.9s @ 2.34GB)
#17 32.43   12,973 (88.23%) of 14,703 classes reachable
#17 32.44   14,253 (52.78%) of 27,005 fields reachable
#17 32.47   52,532 (57.74%) of 90,982 methods reachable
#17 32.47    1,361 classes,   776 fields, and 4,464 methods registered for reflection
#17 32.47 
#17 32.47 Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder.onCreated(io.micronaut.context.event.BeanCreatedEvent) 
#17 32.47 Parsing context:
#17 32.47    at io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder.onCreated(ExecutorServiceMetricsBinder.java:64)
#17 32.47    at io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder.onCreated(ExecutorServiceMetricsBinder.java:48)
#17 32.47    at io.micronaut.context.DefaultBeanContext.triggerBeanCreatedEventListener(DefaultBeanContext.java:2407)
#17 32.47    at io.micronaut.context.DefaultBeanContext.postBeanCreated(DefaultBeanContext.java:2385)
#17 32.47    at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2309)
#17 32.47    at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
#17 32.47    at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
#17 32.47    at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2906)
#17 32.47    at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853)
#17 32.47    at io.micronaut.context.DefaultBeanContext.loadListeners(DefaultBeanContext.java:1872)
#17 32.47    at io.micronaut.context.DefaultBeanContext.triggerPreDestroyListeners(DefaultBeanContext.java:1184)
#17 32.47    at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1144)
#17 32.47    at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1119)
#17 32.47    at io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:406)
#17 32.47    at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:200)
#17 32.47    at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:63)
#17 32.47    at io.micronaut.context.LifeCycle.close(LifeCycle.java:61)
#17 32.47    at java.io.FileDescriptor.closeAll(FileDescriptor.java:345)
#17 32.47    at java.io.FileInputStream.close(FileInputStream.java:457)
#17 32.47    at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:366)
#17 32.47    at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:204)
#17 32.47    at java.io.InputStreamReader.close(InputStreamReader.java:192)
#17 32.47    at java.io.BufferedReader.close(BufferedReader.java:525)
#17 32.47    at com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:61)
#17 32.47    at com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
#17 32.47    at com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
#17 32.47    at com.oracle.svm.core.containers.cgroupv2.CgroupV2Subsystem.getLongVal(CgroupV2Subsystem.java:56)
#17 32.47    at com.oracle.svm.core.containers.cgroupv2.CgroupV2Subsystem.getCpuShares(CgroupV2Subsystem.java:174)
#17 32.47    at com.oracle.svm.core.ContainerInfo.getCpuShares(ContainerInfo.java:49)
#17 32.47    at com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:129)
#17 32.47    at com.oracle.svm.core.jdk.Target_java_lang_Runtime.availableProcessors(JavaLangSubstitutions.java:245)
#17 32.47    at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2564)
#17 32.47    at com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:367)
#17 32.47    at com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:359)
#17 32.47    at java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java:652)
#17 32.47    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:306)
#17 32.47    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
#17 32.47    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
#17 32.47    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
#17 32.47    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
#17 32.47    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
#17 32.47    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
#17 32.47    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
#17 32.47    at java.lang.reflect.Executable.sharedToString(Executable.java:122)
#17 32.47    at java.lang.reflect.Method.toString(Method.java:412)
#17 32.47    at java.lang.String.valueOf(String.java:4218)
#17 32.47    at java.lang.AssertionError.<init>(AssertionError.java:75)
#17 32.47    at com.oracle.svm.core.snippets.ImplicitExceptions.throwNewAssertionErrorObject(ImplicitExceptions.java:319)
#17 32.47 
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:558)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:635)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
#17 32.47       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
#17 32.47       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
#17 32.47       at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
#17 32.47       at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3321)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:243)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:692)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:680)
#17 32.47       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:736)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
#17 32.47 Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger.
#17 32.47       at parsing io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics.bindTo(ExecutorServiceMetrics.java:304)
#17 32.47       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2506)
#17 32.47       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
#17 32.47       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3367)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3319)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3164)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:176)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
#17 32.48       ... 21 more
#17 32.48 Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger.
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:140)
#17 32.48       at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:583)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:105)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:84)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:55)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:78)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:51)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.tryConstantFold(ConstantFoldLoadFieldPlugin.java:61)
#17 32.48       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.handleLoadStaticField(ConstantFoldLoadFieldPlugin.java:57)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4753)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4724)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5218)
#17 32.48       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3359)
#17 32.48       ... 46 more
#17 32.48 ------------------------------------------------------------------------------------------------------------------------
#17 32.48                         2.5s (7.8% of total time) in 22 GCs | Peak RSS: 5.40GB | CPU load: 3.24
#17 32.48 ========================================================================================================================
#17 32.48 Failed generating 'application' after 31.5s.
#17 33.28 Error: Image build request failed with exit status 1

```

### Environment Information

- macOS Ventura, Linux
- Micronaut 3.8.0

### Version

3.8.0

**Comment by saw303** [comment]
Maybe related with #8548

**Comment by sdelamo** [comment]
@saw303 can you confirm that forcing `4.5.0` of open telemetry solves the issue?

```
configurations.all {
    resolutionStrategy {
        force "io.micronaut.tracing:micronaut-tracing-opentelemetry-annotation:4.5.0"
    }
}
```

**Comment by saw303** [comment]
@sdelamo unfortunately no. I have applied the following to my `gradle.build`

```groovy
resolutionStrategy {
   force "io.micronaut.tracing:micronaut-tracing-opentelemetry:4.5.0"
   force "io.micronaut.tracing:micronaut-tracing-opentelemetry-http:4.5.0" // otherwise it remains at 4.4.0
}
```

That does not solve the issue. My project uses micrometer, and I suspect that the issue is also related to this.

I added am small example app. Here are the steps to reproduce:

1. `./gradlew clean buildNativeLayersTask dockerPrepareContext`
2. `cd build/docker/native-main`
3. `docker build --no-cache -t delete:deleteme -f DockerfileNative .`

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger
```

As you can see in the stacktrace, the issue is micrometer related.

Note: I'm on a Apple Silicon Mac and therefore I cannot use the built-in Micronaut Gradle task to build the Docker image. (Looking forward to Micronaut 4).

**Comment by sdelamo** [comment]
> Note: I'm on a Apple Silicon Mac and therefore I cannot use the built-in Micronaut Gradle task to build the Docker image. (Looking forward to Micronaut 4).

see: 
https://micronaut.io/2022/11/22/how-to-build-a-graalvm-native-executable-of-a-micronaut-application-from-an-apple-silicon-mac-and-deploy-it-to-aws-lambda-arm-architecture/

**Comment by sdelamo** [comment]
do you have a sample app?

**Comment by saw303** [comment]
@sdelamo Yes, I have added it this morning to the ticket. Take a look at the updated description 👆🏻

**Comment by n0tl3ss** [comment]
Hi @saw303 

Can you try to add into your `build.gradle`?

```
graalvmNative {
    binaries {
        main {
            buildArgs.add('--initialize-at-build-time=io.micrometer.common.util.internal.logging.LocationAwareSlf4JLogger')
        }
    }
}
```

**Comment by saw303** [comment]
@n0tl3ss this works. 👍🏻
Will this be part of the Gradle plugin in the future?

**Comment by graemerocher** [comment]
needs to go into the Micrometer module

**Comment by graemerocher** [comment]
although won't be needed in Micronaut 4
