### ISSUE TITLE
Multiple possible bean candidates issue when using micronaut-security-oauth2

### ISSUE THREAD

**Issue by menesty** [micronaut-projects/micronaut-core#8607]
### Expected Behavior

redirect to google auth 

### Actual Behaviour

18:19:01.013 [default-nioEventLoopGroup-1-4] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Request GET /oauth/login/google
18:19:04.265 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: OpenIdProviderMetadata
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata null Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: OpenIdClientConfiguration
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties null Definition: io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties]
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties @nAmed('google') Definition: io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties @nAmed('facebook') Definition: io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory]
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata @nAmed('google') Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata @nAmed('facebook') Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory
18:19:04.266 [default-nioEventLoopGroup-1-4] DEBUG i.m.context.DefaultBeanContext - Searching for @primary for type [OpenIdProviderMetadata] from candidates: [Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory, Definition: io.micronaut.security.oauth2.client.OpenIdClientFactory]
18:19:04.266 [default-nioEventLoopGroup-1-4] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Multiple possible bean candidates found: [io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]
at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472)
at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:488)
at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249)
at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140)
at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058)
at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788)
at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790)
at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680)
at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1655)
at io.micronaut.context.DefaultBeanContext.resolveArgumentValues(DefaultBeanContext.java:1059)
at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1022)
at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:1001)
at io.micronaut.context.BeanContext.createBean(BeanContext.java:180)
at io.micronaut.security.oauth2.client.DefaultOpenIdClient.authorizationRedirect(DefaultOpenIdClient.java:119)
at io.micronaut.security.oauth2.routes.DefaultOauthController.login(DefaultOauthController.java:77)
at io.micronaut.security.oauth2.routes.$DefaultOauthController$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
at io.micronaut.inject.ExecutionHandle$1.invoke(ExecutionHandle.java:114)
at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2508)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:601)
at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:457)
at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:147)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:224)
at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:134)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
18:19:04.268 [default-nioEventLoopGroup-1-4] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Response 500 - GET /oauth/login/google

### Steps To Reproduce

micronaut version 3.8.0, 3.8.1  - on version 3.5.1 no issue
configure two oauth2 clients - one google, facebook
go to http://localhost/oauth/login/google

### Environment Information

MacOs
Java 17

### Version

3.8.0, 3.8.1

**Comment by ed-luke** [comment]
I am having the same issue after upgrading to Micronaut 3.8.1. Our application is multi-tenanted using a subdomain tenancy resolver. Each tenant has their own authentication provider configured. After upgrading Micronaut, we now get the error:

`Multiple possible bean candidates found: [io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata, io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]`
