### ISSUE TITLE
Intermittent NPE in isCandidateBean

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8627]
### Expected Behavior

Should not NPE

### Actual Behaviour

NPEs with:

```
java.lang.NullPointerException: Cannot invoke "io.micronaut.inject.BeanDefinitionReference.isCandidateBean(io.micronaut.core.type.Argument)" because "this.reference" is null
      at app//io.micronaut.context.DefaultBeanContext$BeanDefinitionProducer.isReferenceCandidateBean(DefaultBeanContext.java:4187)
      at app//io.micronaut.context.DefaultBeanContext.collectBeanCandidates(DefaultBeanContext.java:2183)
      at app//io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2161)
      a
```

Broken in this commit https://github.com/micronaut-projects/micronaut-core/commit/6b8fa8a693a2c311663319734bea80c2ec9ab846

### Steps To Reproduce

Run tests in Micronaut Serialization or core

### Version

4.0.x

**Comment by graemerocher** [comment]
also probably related to this failure

https://ge.micronaut.io/s/dtgkahiutgtai/tests/:inject-java:test/io.micronaut.inject.lifecycle.beancreationeventlistener.BeanCreationEventListenerSpec/test%20bean%20creation%20listener%20eager?top-execution=1
