### ISSUE TITLE
Micronaut Upgrade to version: 3.8.2 giving java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8657]
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/8653

<div type='discussions-op-text'>

<sup>Originally posted by **npathai** January 23, 2023</sup>
When trying to upgrade from Micronaut version: 3.3.3 to version 3.8.2, I am getting following error.

Micronaut Version: 3.8.2 (But the issue also occurs with >= 3.4.0)
Java version: 11
Micronaut Data Version: 3.9.4

```
Caused by: java.lang.VerifyError: Bad type on operand stack

  Location:
    consumerdetails/$ConsumerDetails$Introspection.dispatch(ILjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; @28: invokevirtual
  Reason:
    Type 'consumerdetails/$ConsumerDetails$Introspection' (current frame, stack[1]) is not assignable to 'io/micronaut/context/AbstractExecutableMethodsDefinition'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'consumerdetails/$ConsumerDetails$Introspection', integer, 'java/lang/Object', '[Ljava/lang/Object;' }
    stack: { 'java/lang/Object', 'consumerdetails/$ConsumerDetails$Introspection', integer }
  Bytecode:
    0000000: 1baa 0000 0000 0035 0000 0014 0000 0015
    0000010: 0000 0017 0000 0026 2c2a 1014 b601 06b2
    0000020: 010c b801 1201 b02c 2a10 15b6 0106 b201
    0000030: 0cb8 0112 01b0 2a1b b600 fcbf          
  Stackmap Table:
    same_frame(@24)
    same_frame(@39)
    same_frame(@54)

	at consumerdetails.$ConsumerDetails$IntrospectionRef.load(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospections(DefaultBeanIntrospector.java:67)
	at io.micronaut.core.beans.BeanIntrospector.findIntrospections(BeanIntrospector.java:91)
	at io.micronaut.configuration.hibernate.jpa.JpaConfiguration$EntityScanConfiguration.findEntities(JpaConfiguration.java:389)
	at io.micronaut.configuration.hibernate.jpa.conf.AbstractHibernateFactory.buildMetadata(AbstractHibernateFactory.java:78)
	at io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory.buildMetadata(SessionFactoryPerDataSourceFactory.java:88)
	at io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildMetadata2$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:769)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:158)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
```</div>

**Comment by npathai** [comment]
Have created a sample project here: https://github.com/npathai/micronaut-upgrade-version-issue/
You will find the description in the README file regarding the steps to execute and reproduce.

We have a `User` class and it extends an abstract class `Auditable`.
The issue is occurring because of `@PrePersist` annotation in the super class. If we remove the annotation from the super class the issue goes away.
