### ISSUE TITLE
Websocket with Kotlin suspend function throws NullPointerException on DelegatingCoroutineContext

### ISSUE THREAD

**Issue by lpicanco** [micronaut-projects/micronaut-core#8663]
### Expected Behavior

This code should work:

```kotlin
@ServerWebSocket("/")
class WebsocketController {
    @OnMessage
    suspend fun messageHandler(message: String, session: WebSocketSession) {
        delay(500)
    }
}
```

### Actual Behaviour

NullPointerException error:

```
[default-nioEventLoopGroup-1-2] ERROR i.m.h.s.n.w.NettyServerWebSocketHandler - Unexpected Exception in WebSocket [com.example.WebsocketController@3cd3e42e]: null
java.lang.NullPointerException: null
        at io.micronaut.http.bind.binders.DelegatingCoroutineContext.get(ContinuationArgumentBinder.kt:105)
        at kotlinx.coroutines.CancellableContinuationImpl.installParentHandle(CancellableContinuationImpl.kt:306)
        at kotlinx.coroutines.CancellableContinuationImpl.initCancellability(CancellableContinuationImpl.kt:98)
        at kotlinx.coroutines.DelayKt.delay(Delay.kt:166)
        at com.example.WebsocketController.messageHandler(WebsocketController.kt:12)
        at com.example.$WebsocketController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.core.bind.DefaultExecutableBinder$1.invoke(DefaultExecutableBinder.java:109)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketHandler.lambda$invokeExecutable0$6(NettyServerWebSocketHandler.java:349)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketHandler.invokeExecutable0(NettyServerWebSocketHandler.java:348)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketHandler.lambda$invokeExecutable$5(NettyServerWebSocketHandler.java:330)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketHandler.lambda$instrumentPublisher$3(NettyServerWebSocketHandler.java:283)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketHandler.lambda$instrumentPublisher$4(NettyServerWebSocketHandler.java:282)
        at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Steps To Reproduce

1. Run `./gradlew run`
2. On another terminal run:
2.1. `npm install artillery` 
2.2. `node_modules/.bin/artillery run loadtest.yml`
3. See error: `java.lang.NullPointerException: null
    at io.micronaut.http.bind.binders.DelegatingCoroutineContext.get(ContinuationArgumentBinder.kt:105)`

### Environment Information

- OS: Macos Venture 13.1
- JDK: 11.0.14-ms

### Example Application

https://github.com/lpicanco/micronaut-wsocket-coroutine-error

### Version

3.8.2

**Comment by lpicanco** [comment]
It seems to be related to [#6582](https://github.com/micronaut-projects/micronaut-core/issues/6582)

**Comment by stralytic** [comment]
I've also got this issue. My digging points to `ContinuationArgumentBinder.bind` creating a brand new `CustomContinuation` when one already exists in the `source` `HttpRequest` object. This brand new `CustomContinuation` never has its `delegatingCoroutineContext` set, but the one in the `HttpRequest` does have one set.

**Comment by yawkat** [comment]
is this still an issue in 4? i cant reproduce yet because of old node version

**Comment by PaulinaJonusaiteZenitech** [comment]
Different use case, exactly the same result. I tried to implement a proxy (`@ServerFilter` bean with a `@RequestFilter` method that calls a `ProxyHttpClient`) using a `suspend fun`. Debugging shows the same exact findings as @stralytic: `ContinuationArgumentBinder.bind` is called to create a new `CustomContinuation`, but the delegating context is never set up.

```
java.lang.NullPointerException: null
	at io.micronaut.http.bind.binders.DelegatingCoroutineContext.get(ContinuationArgumentBinder.kt:99) ~[gateway-0.1.jar:?]
	at kotlin.coroutines.jvm.internal.ContinuationImpl.intercepted(ContinuationImpl.kt:112) ~[gateway-0.1.jar:?]
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.intercepted(IntrinsicsJvm.kt:182) ~[gateway-0.1.jar:?]
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:327) ~[gateway-0.1.jar:?]
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:179) ~[gateway-0.1.jar:?]
	at kotlinx.coroutines.reactive.AwaitKt.awaitSingle(Await.kt:77) ~[gateway-0.1.jar:?]
	at ----------------.ProxyFilter.proxyFilter(ProxyFilter.kt:36) ~[gateway-0.1.jar:?]
	at ----------------.$ProxyFilter$Definition$Exec.dispatch(Unknown Source) ~[gateway-0.1.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.MethodFilter.filter0(MethodFilter.java:361) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.MethodFilter.filter(MethodFilter.java:350) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.MethodFilter.processRequestFilter(MethodFilter.java:288) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.FilterRunner.filterRequest(FilterRunner.java:283) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.FilterRunner.lambda$filterRequest$2(FilterRunner.java:280) ~[gateway-0.1.jar:?]
	at io.micronaut.http.filter.AroundLegacyFilter$FilterChainImpl.proceed(AroundLegacyFilter.java:122) ~[gateway-0.1.jar:?]
	at io.micronaut.security.filters.SecurityFilter.lambda$checkRules$7(SecurityFilter.java:164) ~[gateway-0.1.jar:?]
	<...snip...>
```

Happy to create a new issue if this is not related enough.

**Comment by smocherla-brex** [comment]
+1 to @PaulinaJonusaiteZenitech’s report. @RequestFilter methods declared as suspend are effectively a footgun when the filter needs to access or inherit the coroutine context.

In practice, this makes suspend @RequestFilter methods unusable for their intended purpose: synchronous code may execute successfully, but the filter can fail with a NPE as soon as it performs real suspending work or accesses the coroutine context. The filter runs eagerly and the `DelegatingCoroutineContext` is expected to be non-null [here](https://github.com/micronaut-projects/micronaut-core/blob/v4.8.10/http/src/main/kotlin/io/micronaut/http/bind/binders/ContinuationArgumentBinder.kt#L95). Interestingly this doesn't seem to be a problem for http controller as the coroutine context is setup [here](https://github.com/micronaut-projects/micronaut-core/blob/v4.8.11/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L462) explicitly calls `setupCoroutineContext` before the controller method is invoked but that is not the case with filters.

We worked around this by making the filter non-suspending, returning a reactive type, and bridging to coroutines with mono and an explicit coroutine context. We’re seeing this on Micronaut 4.8.11. I’m happy to file a separate issue with a minimal reproduction if that would help.

**Comment by graemerocher** [comment]
Triage: this is a validated Kotlin websocket bug with an exact open fix PR #12437. That PR adds a concurrency regression test and makes DelegatingCoroutineContext null-safe for the unset-context path. Please keep the issue linked to the PR and verify the test on the supported Kotlin/Core matrix before merging.
