### ISSUE TITLE
Implementing an interface in a different source set loses parameter names (with -parameters)

### ISSUE THREAD

**Issue by alanbino** [micronaut-projects/micronaut-core#870]
Issue raised in Micronaut Gitter and was advised to raise issue by @jameskleeh .

When you have an interface that defines your HTTP API, and another `@Client` interface which extends that API interface, using the `@Client` to execute a method that defines a URL Path Parameter **coupled with** a second `@QueryValue` parameter will not work e.g.:

```
@Get("/path/{someParam}") 
public String getSomething(String someParam, @QueryValue String someOtherParam) //...
```

A work-around is to redefine the same method signature in your `@Client` interface, which is already defined in the parent in the same way (but it seems redundant to have to do that).
To test this work-around, please uncomment the code in TestClient.java from my git repository.

### Task List

- [Y] Steps to reproduce provided
- [Y] Stacktrace (if present) provided
- [Y] Example that reproduces the problem uploaded to Github
- [Y] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the provided GIT Repo
2. Run the JUnit Test provided called 'TestControllerTest.java'
3. See that the test fails
4. Uncomment the code in TestClient.java which is the same method definition from the parent interface
5. Re-run the tests -> tests will pass

### Expected Behaviour

I would expect that when my `@Client` extends an existing interface that uses URL Path Parameters coupled with a second `@QueryValue` parameter, that it should work like other `@Get` examples that do not use this combination. I would expect that you shouldn't have to re-define the same method signature in the extending interface for this to work.

### Actual Behaviour

The `@Client` executing the method with the URL Path Parameter and second `@QueryValue` parameter fails

### Stacktrace

```
16:05:09.126 [nioEventLoopGroup-1-3] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: GET /test/testMethod/?otherTestString=OTHER_TEST_STRING
16:05:09.126 [nioEventLoopGroup-1-3] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: localhost(35341)
16:05:09.128 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Accept: application/json
16:05:09.129 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - host: localhost
16:05:09.129 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - connection: close
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - HTTP Client Response Received for Request: GET /testMethod/?otherTestString=OTHER_TEST_STRING
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Status Code: 404 Not Found
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Date: Wed, 7 Nov 2018 16:05:09 GMT
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - content-type: application/json
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - content-length: 127
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - connection: close
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - Response Body
16:05:09.295 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - ----
16:05:09.296 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - {"_links":{"self":{"href":"/test/testMethod/?otherTestString=OTHER_TEST_STRING","templated":false}},"message":"Page Not Found"}
16:05:09.296 [nioEventLoopGroup-1-3] TRACE i.m.http.client.DefaultHttpClient - ----
iface.extend.test.TestControllerTest > testMethod FAILED
    java.lang.AssertionError at TestControllerTest.java:37

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at iface.extend.test.TestControllerTest.testMethod(TestControllerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

1 test completed, 1 failed
> Task :test FAILED
FAILURE: Build failed with an exception.
```

### Environment Information

Operating System: Mac OSX v10.13.6 (High Sierra)
Micronaut Version: 1.0.0
JDK Version: 1.8.0_144

### Example Application

https://github.com/alanbino/iface-extend-test.git

**Comment by jameskleeh** [comment]
The client implementation is losing the argument names when the interface is in a different source set. Moving `TestClient` to `src/main` fixes the issue

**Comment by jameskleeh** [comment]
This seems like a bug with the annotation processor API, however we may be able to work around it

**Comment by jameskleeh** [comment]
It also works if the `@QueryValue` annotation is removed

**Comment by jameskleeh** [comment]
This was fixed in JDK11
