### ISSUE TITLE
@JsonCreator being ignored

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-core#8739]
### Expected Behavior

Using `@JsonCreator` Annotation to build Objects.

### Actual Behaviour

`@JsonCreator` is being ignored when it's a static factory. It's always using the Constructor.

Exception:

```
Caused by: java.lang.IllegalArgumentException: No enum constant com.foo.bar.Foo.bar
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at io.micronaut.serde.support.serdes.EnumSerde.deserializeNonNull(EnumSerde.java:42)
	at io.micronaut.serde.support.serdes.EnumSerde.deserializeNonNull(EnumSerde.java:36)
	at io.micronaut.serde.util.NullableDeserializer.deserialize(NullableDeserializer.java:38)

```

### Steps To Reproduce

Use the following Enum:

```
@Serdeable
public enum Foo {
  BAR("bar"),
  BAZ("baz");

  private final String value;

  public Foo(String value) {
    this.value = value;
  }

  @JsonCreator
  public static Foo fromValue(String value) {
    return Arrays.stream(values())
        .filter(foo -> Objects.equals(foo.toString(), value))
        .findFirst();
  }
  
  public String toString() {
    return this.value;
  }

}
```

### Environment Information

- Operating System: MacOS
- Java 17

### Version

3.8.5

**Comment by driverpt** [comment]
This happens when using HttpClient or Controller binding
