### ISSUE TITLE
NullPointerException when calling LoggersEndpoint over http with configuredLevel=null

### ISSUE THREAD

**Issue by semeiser** [micronaut-projects/micronaut-core#875]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new micronaut application with management endpoints:
```
mn create-app micronaut-logger-endpoint --features management
```
2. Run the application
```
./gradlew run
```
3. Try to reset the loglevel of a specific logger over http and supply null as configuredLevel.
```
curl -XPOST http://localhost:8080/loggers/io.micronaut -H "Content-Type: application/json" -d '{"configuredLevel":null}'
``` 

### Expected Behaviour

The loglevel should be reset like in the test `io.micronaut.management.endpoint.loggers.LoggersEndpointSpec#test that log levels on logger "#name" can be configured via the loggers endpoint`

### Actual Behaviour

A NullPointerException is thrown (using an empty body works `curl -XPOST http://localhost:8080/loggers/io.micronaut -H "Content-Type: application/json" -d '{}'`):
```
13:26:26.456 [nioEventLoopGroup-1-5] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Optional.<init>(Optional.java:96)
        at java.util.Optional.of(Optional.java:108)
        at io.micronaut.jackson.convert.JsonNodeToObjectConverter.convert(JsonNodeToObjectConverter.java:54)
        at io.micronaut.jackson.convert.JsonNodeToObjectConverter.convert(JsonNodeToObjectConverter.java:36)
        at io.micronaut.core.convert.DefaultConversionService.convert(DefaultConversionService.java:127)
        at io.micronaut.context.env.DefaultEnvironment.convert(DefaultEnvironment.java:275)
        at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:117)
        at io.micronaut.jackson.convert.ObjectNodeConvertibleValues.get(ObjectNodeConvertibleValues.java:78)
        at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.resolveValue(AbstractAnnotatedArgumentBinder.java:109)
        at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.doResolve(AbstractAnnotatedArgumentBinder.java:84)
        at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.doBind(AbstractAnnotatedArgumentBinder.java:67)
        at io.micronaut.http.bind.binders.ParameterAnnotationBinder.bind(ParameterAnnotationBinder.java:115)
        at io.micronaut.http.bind.binders.ParameterAnnotationBinder.bind(ParameterAnnotationBinder.java:45)
        at io.micronaut.http.server.binding.RequestArgumentSatisfier.lambda$getValueForArgument$2(RequestArgumentSatisfier.java:142)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:255)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$13(RoutingInBoundHandler.java:1244)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14429)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14426)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: macOS 10.14
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_131

**Comment by jameskleeh** [comment]
Thanks for the report
