### ISSUE TITLE
Micronaut 3.8.5 fails to start when using programmatic logger configuration on logback > 1.2.11

### ISSUE THREAD

**Issue by jamatu** [micronaut-projects/micronaut-core#8810]
### Expected Behavior

Micronaut application should start when using a recent logback version and log levels defined within the application.xml file, or give an appropriate error message.

### Actual Behaviour

Silent application startup failure first observed on 3.8.4 (similar to #8758), is still present on 3.8.5. Issue only occurs when logger level(s) are defined within the application.xml, issue is not present when these are removed. Switching to logback 1.2.11 is tested to resolve the issue. 

The following output is seen when running the application, the error is silent:
```
DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: io.micronaut.logging.LoggingSystem
DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: LoggingSystem E
DEBUG i.m.context.condition.Condition - Bean [Definition: io.micronaut.management.endpoint.loggers.impl.LogbackLoggingSystem] will not be loaded due to failing conditions:
DEBUG i.m.context.condition.Condition - * No bean of type [class io.micronaut.management.endpoint.loggers.LoggersEndpoint] present within context
DEBUG i.m.context.condition.Condition - Bean [io.micronaut.management.endpoint.loggers.impl.$Log4jLoggingSystem$Definition] will not be loaded due to failing conditions:
DEBUG i.m.context.condition.Condition - * Class [org.apache.logging.log4j.core.LoggerContext] is not present
DEBUG i.m.context.condition.Condition - Bean [io.micronaut.logging.impl.$Log4jLoggingSystem$Definition] will not be loaded due to failing conditions:
DEBUG i.m.context.condition.Condition - * Class [org.apache.logging.log4j.core.config.Configurator] is not present
DEBUG i.m.context.DefaultBeanContext -   class io.micronaut.logging.impl.LogbackLoggingSystem null Definition: io.micronaut.logging.impl.LogbackLoggingSystem
DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.logging.impl.LogbackLoggingSystem]
DEBUG i.m.context.DefaultBeanContext -   class io.micronaut.logging.impl.LogbackLoggingSystem null Definition: io.micronaut.logging.impl.LogbackLoggingSystem
DEBUG io.micronaut.context.lifecycle - Created bean [io.micronaut.logging.impl.LogbackLoggingSystem@2f09e6b2] from definition [Definition: io.micronaut.logging.impl.LogbackLoggingSystem] with qualifier [null]
DEBUG i.m.context.DefaultBeanContext - Found a registration BeanRegistration: io.micronaut.logging.impl.LogbackLoggingSystem@2f09e6b2 for candidate: Definition: io.micronaut.logging.impl.LogbackLoggingSystem with qualifier: null

Process finished with exit code 1
```

Debugging produces the following error:
```
ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.logging.PropertiesLoggingLevelsConfigurer] could not be loaded: Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]

Message: 'void ch.qos.logback.classic.spi.Configurator.configure(ch.qos.logback.classic.LoggerContext)'
Path Taken: new PropertiesLoggingLevelsConfigurer(Environment environment,List loggingSystems)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.logging.PropertiesLoggingLevelsConfigurer] could not be loaded: Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]

Message: 'void ch.qos.logback.classic.spi.Configurator.configure(ch.qos.logback.classic.LoggerContext)'
Path Taken: new PropertiesLoggingLevelsConfigurer(Environment environment,List loggingSystems)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]

Message: 'void ch.qos.logback.classic.spi.Configurator.configure(ch.qos.logback.classic.LoggerContext)'
Path Taken: new PropertiesLoggingLevelsConfigurer(Environment environment,List loggingSystems)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
	... 9 common frames omitted
Caused by: java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.spi.Configurator.configure(ch.qos.logback.classic.LoggerContext)'
	at io.micronaut.logging.impl.LogbackUtils.programmaticConfiguration(LogbackUtils.java:96)
	at io.micronaut.logging.impl.LogbackUtils.configure(LogbackUtils.java:74)
	at io.micronaut.logging.impl.LogbackUtils.configure(LogbackUtils.java:53)
	at io.micronaut.logging.impl.LogbackLoggingSystem.refresh(LogbackLoggingSystem.java:57)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.micronaut.logging.PropertiesLoggingLevelsConfigurer.initLogging(PropertiesLoggingLevelsConfigurer.java:83)
	at io.micronaut.logging.PropertiesLoggingLevelsConfigurer.<init>(PropertiesLoggingLevelsConfigurer.java:67)
	at io.micronaut.logging.$PropertiesLoggingLevelsConfigurer$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	... 16 common frames omitted
```

The return type of `Configurator.configure` was changed from `void` to `ExecutionStatus` in logback 1.3.0, so it seems this is another incompatbility caused by compiling and running against different versions of logback

### Steps To Reproduce

1. Create a micronaut 3.8.4/5 application using logback 1.4.5
2. Add a programmatic log level configuration to the application.xml file, as shown in the user documentation [here](https://docs.micronaut.io/latest/guide/#logging). Eg:
```
logger:
  levels:
    io.micronaut.http: DEBUG
```
3. Observe failure to start application when launched

### Environment Information

All operating systems
JDK 17

### Version

3.8.5

**Comment by sdelamo** [comment]
As a workaround downgrade to 1.2,11 which is the version we used for Micronaut Framework 3.x. We will upgrade to 1.4.5 in Micronaut Framework 4.0.

**Comment by timyates** [comment]
I cannot see a way to support Logback 1.3+ properly prior to Micronaut 4

Logback 1.3 introduced a change that broke binary compatibility.  We could introduce a check to get this case passing, however it is then broken with Programmatic configuration

**Comment by jamatu** [comment]
Regarding my specific case, I have downgraded to 1.2.11 without issue

Some kind of warning or error stating that logback 1.3+ is not supported would have been useful given this did work (intentionally or not) before 3.8.4

Thanks!

**Comment by sdelamo** [comment]
We introduced a snippet in the docs https://github.com/micronaut-projects/micronaut-core/pull/8846
