### ISSUE TITLE
HttpRequest getBody does not return a body even when body type is specified

### ISSUE THREAD

**Issue by Adil-Iqbal** [micronaut-projects/micronaut-core#8923]
### Expected Behavior

```java
boolean isBodyPresent = ServerRequestContext
    .currentRequest()
    .get()
    .getBody(SpecificBody.class)
    .isPresent();

Assert.assertTrue(isBodyPresent); // fails
```

### Actual Behaviour

The above behavior should pass. 

The body of a request should be present.

See also: #1113 and #1467

### Environment Information

17.0.0

### Version

3.8.6

**Comment by Adil-Iqbal** [comment]
The request body contains information that is necessary for security validations. Which means I need access to request context from a non-controller bean.

**Comment by graemerocher** [comment]
currently this is only possible with a Netty channel handler with the default server. Here is a naive implementation as an example:

```java
package request.body.test;

import java.nio.charset.StandardCharsets;

import io.micronaut.context.event.BeanCreatedEvent;
import io.micronaut.context.event.BeanCreatedEventListener;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Post;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.server.netty.NettyServerCustomizer;
import io.micronaut.runtime.EmbeddedApplication;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import io.netty.buffer.ByteBufUtil;
import io.netty.buffer.CompositeByteBuf;
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.HttpContent;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.HttpVersion;
import io.netty.handler.codec.http.LastHttpContent;
import io.netty.util.ReferenceCountUtil;
import jakarta.inject.Singleton;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

import jakarta.inject.Inject;

import static io.micronaut.http.netty.channel.ChannelPipelineCustomizer.HANDLER_HTTP_SERVER_CODEC;

@MicronautTest
class RequestBodyTestTest {

    @Inject
    EmbeddedApplication<?> application;

    @Test
    void testItWorks(RequestBodySender sender) {
        Foo foo = sender.send(new Foo("test"));
        Assertions.assertNotNull(foo);
    }

    @Client("/test")
    interface RequestBodySender {
        @Post
        Foo send(@Body Foo foo);
    }
}


@Introspected
record Foo(String name) {}

@Controller("/test")
class TestController {
    @Post
    Foo receive(@Body Foo foo) {
        return foo;
    }
}

@Singleton
class BodyValidator implements BeanCreatedEventListener<NettyServerCustomizer.Registry>, NettyServerCustomizer {

    private final Channel channel;
    private final CompositeByteBuf body;

    public BodyValidator(@Nullable Channel channel) {
        this.channel = channel;
        if (channel != null) {
            this.body = channel.alloc().compositeBuffer();
        } else {
            this.body = null;
        }
    }

    @Override
    public NettyServerCustomizer.Registry onCreated(BeanCreatedEvent<NettyServerCustomizer.Registry> event) {
        NettyServerCustomizer.Registry registry = event.getBean();
        registry.register(this);
        return registry;
    }

    @Override
    public NettyServerCustomizer specializeForChannel(Channel channel, ChannelRole role) {
        return new BodyValidator(channel);
    }


    @Override
    public void onStreamPipelineBuilt() {
        if (channel != null) {
            channel.pipeline().addAfter(HANDLER_HTTP_SERVER_CODEC, "body-validator", new SimpleChannelInboundHandler<>() {
                @Override
                protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
                    if (body != null && msg instanceof HttpContent httpContent) {
                        body.addComponent(true, httpContent.content());
                        if (httpContent instanceof LastHttpContent) {
                            byte[] bytes = ByteBufUtil.getBytes(body);
                            // validate bytes
                            String s = new String(bytes, StandardCharsets.UTF_8);
                            if (s.contains("test")) {
                                ctx.writeAndFlush(
                                    new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, new HttpResponseStatus(HttpResponseStatus.BAD_GATEWAY.code(), "Request failed validation"))
                                ).addListener(listener -> channel.close());
                                return;
                            }
                        }
                    }
                    ctx.fireChannelRead(msg);
                }

                @Override
                public void handlerRemoved(ChannelHandlerContext ctx) throws Exception {
                    if (body != null) {
                        ReferenceCountUtil.safeRelease(body);
                    }
                }
            });

        }
    }
}
```

Alternatively you could choose one of the Servlet based servers where you can write a servlet filter or and using blocking I/O

**Comment by graemerocher** [comment]
Simpler and maybe safer solution using an aggregator:

```java
package request.body.test;

import java.nio.charset.StandardCharsets;

import io.micronaut.context.event.BeanCreatedEvent;
import io.micronaut.context.event.BeanCreatedEventListener;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Post;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.client.exceptions.HttpClientResponseException;
import io.micronaut.http.server.HttpServerConfiguration;
import io.micronaut.http.server.netty.NettyServerCustomizer;
import io.micronaut.runtime.EmbeddedApplication;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import io.netty.buffer.ByteBufUtil;
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.FullHttpRequest;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.HttpVersion;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.junit.jupiter.api.Test;

import static io.micronaut.http.netty.channel.ChannelPipelineCustomizer.HANDLER_HTTP_STREAM;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@MicronautTest
class RequestBodyTestTest {

    @Inject
    EmbeddedApplication<?> application;

    @Test
    void testInvalid(RequestBodySender sender) {
        HttpClientResponseException responseException = assertThrows(HttpClientResponseException.class, () ->
                sender.send(new Foo("test"))
        );
        assertEquals(HttpStatus.BAD_REQUEST, responseException.getStatus());
    }

    @Test
    void testValid(RequestBodySender sender) {
        Foo foo = sender.send(new Foo("other"));
        assertNotNull(foo);
    }

    @Client("/test")
    interface RequestBodySender {
        @Post
        Foo send(@Body Foo foo);
    }
}


@Introspected
record Foo(String name) {}

@Controller("/test")
class TestController {
    @Post
    Foo receive(@Body Foo foo) {
        return foo;
    }
}

@Singleton
class BodyValidator implements BeanCreatedEventListener<NettyServerCustomizer.Registry>, NettyServerCustomizer {

    private static final String BODY_AGGREGATOR = "body-aggregator";
    private static final String BODY_VALIDATOR = "body-validator";
    private final Channel channel;
    private final HttpServerConfiguration serverConfiguration;

    public BodyValidator(@Nullable Channel channel, HttpServerConfiguration serverConfiguration) {
        this.channel = channel;
        this.serverConfiguration = serverConfiguration;
    }

    @Override
    public NettyServerCustomizer.Registry onCreated(BeanCreatedEvent<NettyServerCustomizer.Registry> event) {
        NettyServerCustomizer.Registry registry = event.getBean();
        registry.register(this);
        return registry;
    }

    @Override
    public NettyServerCustomizer specializeForChannel(Channel channel, ChannelRole role) {
        return new BodyValidator(channel, serverConfiguration);
    }


    @Override
    public void onStreamPipelineBuilt() {
        if (channel != null) {
            ChannelPipeline pipeline = channel.pipeline();
            pipeline.addBefore(HANDLER_HTTP_STREAM, BODY_AGGREGATOR, new HttpObjectAggregator((int) serverConfiguration.getMaxRequestSize()));
            pipeline.addAfter(BODY_AGGREGATOR, BODY_VALIDATOR, new SimpleChannelInboundHandler<FullHttpRequest>() {
                @Override
                protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest msg) {
                    byte[] bytes = ByteBufUtil.getBytes(msg.content());
                    // validate bytes
                    String s = new String(bytes, StandardCharsets.UTF_8);
                    if (s.contains("test")) {
                        ctx.writeAndFlush(
                            new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, new HttpResponseStatus(HttpResponseStatus.BAD_REQUEST.code(), "Request failed validation"))
                        ).addListener(listener -> channel.close());
                    } else {
                        ctx.fireChannelRead(msg);
                    }
                }
            });
        }
    }
}
```

**Comment by Adil-Iqbal** [comment]
The use case requires that I access the request body from a static context. Would there be a way to populate `ServerRequestContext.currentRequest().get()` (which returns a `HttpRequest` object) with a request body (I can work with a raw string or byte array). Currently its empty.

**Comment by graemerocher** [comment]
Not with the Netty server because it doesn't use a thread per request model so thread locals are a non starter 

If you need that you probably need to switch to a servlet based server

**Comment by Adil-Iqbal** [comment]
Your solution worked! Thanks a lot man! I used the `ChannelInboundHandlerAdapter.java` for my specific use case. And set body elements that I needed as application protocol headers.

EDIT: Anyone else who comes upon this problem, "Netty In Action" is a great book to help you understand what's going on in the code above. Some scoundrel has also published the PDF for free and made it easily searchable on google. (which I do not condone for the record).

**Comment by mzubala** [comment]
I'm trying to use this solution in order to log requests body in my application. However every request ends up with an error like so:
```
12:54:33.416 [default-nioEventLoopGroup-1-3] ERROR i.m.http.server.RouteExecutor [2b1009244a0c008a] - Unexpected error occurred: refCnt: 0, decrement: 1
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.release(HttpObjectAggregator.java:378)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Here's my "filter" code based on what was posted in this thread.

```
@Singleton
internal class RequestLoggingFilter(private val channel: Channel?, private val serverConfiguration: HttpServerConfiguration) :
    BeanCreatedEventListener<NettyServerCustomizer.Registry>, NettyServerCustomizer {

    companion object {
        private const val BODY_AGGREGATOR = "body-aggregator"
        private const val BODY_VALIDATOR = "body-validator"
        private val log by logger()
    }

    init {
        log.info("Elo")
    }

    override fun onCreated(event: BeanCreatedEvent<NettyServerCustomizer.Registry>): NettyServerCustomizer.Registry {
        val registry: NettyServerCustomizer.Registry = event.getBean()
        registry.register(this)
        return registry
    }

    override fun specializeForChannel(
        channel: Channel,
        role: NettyServerCustomizer.ChannelRole
    ): NettyServerCustomizer {
        return RequestLoggingFilter(channel, serverConfiguration)
    }

    override fun onStreamPipelineBuilt() {
        if (channel != null) {
            val pipeline: ChannelPipeline = channel.pipeline()
            pipeline.addBefore(
                HANDLER_HTTP_STREAM,
                BODY_AGGREGATOR,
                HttpObjectAggregator(serverConfiguration.maxRequestSize.toInt())
            )
            pipeline.addAfter(
                BODY_AGGREGATOR,
                BODY_VALIDATOR,
                object : SimpleChannelInboundHandler<FullHttpRequest>() {
                    override fun channelRead0(ctx: ChannelHandlerContext, msg: FullHttpRequest) {
                        val bytes = ByteBufUtil.getBytes(msg.content())
                        val body = String(bytes, StandardCharsets.UTF_8)
                        log.info(
                            StringBuilder().apply {
                                append("Request ${msg.method().name()} ${msg.uri()} ")
                                append(body)
                            }.toString()
                        )
                        ctx.fireChannelRead(msg)
                    }
                })
        }
    }
}
```

Do you have any suggestions how to fix this error?

**Comment by yawkat** [comment]
@mzubala please make a separate issue or discussion
