### ISSUE TITLE
java.lang.IllegalAccessError for redis session

### ISSUE THREAD

**Issue by mos3** [micronaut-projects/micronaut-core#901]
`micronaut.session.http.cookiePath=/`

```
Caused by: java.lang.IllegalAccessError: tried to access method io.micronaut.session.http.HttpSessionConfiguration.setCookiePath(Ljava/lang/String;)V from class io.micronaut.configuration.lettuce.session.$RedisHttpSessionConfigurationDefinition
	at io.micronaut.configuration.lettuce.session.$RedisHttpSessionConfigurationDefinition.injectBean(Unknown Source)
	at io.micronaut.configuration.lettuce.session.$RedisHttpSessionConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
```

**Comment by jameskleeh** [comment]
@graemerocher It seems we should be able to detect this possibility at compile time and fail compilation. The setter in the parent class is protected and the definition class is in a different package.
