### ISSUE TITLE
Validation of List<@NotNull Type> throw NPE

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#9030]
### Expected Behavior

If I want to validate this type: 
```java
    @Valid
    @NotEmpty
    @NotNull
    private List<@NotNull Task> tasks;
```
with this data: 
```yaml 
tasks: 
- 
```
it thrown an NPE

### Actual Behaviour

<details>
  <summary>Stacktrace</summary>

  ```
java.lang.NullPointerException: Argument [bean] cannot be null

	at io.micronaut.core.util.ArgumentUtils.requireNonNull(ArgumentUtils.java:56)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanPropertyImpl.get(AbstractInitializableBeanIntrospection.java:449)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1102)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToOneIntrospection(DefaultValidator.java:1404)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToOne(DefaultValidator.java:1361)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToIterableValue(DefaultValidator.java:1268)
	at io.micronaut.validation.validator.DefaultValidator.access$800(DefaultValidator.java:98)
	at io.micronaut.validation.validator.DefaultValidator$3.indexedValue(DefaultValidator.java:1166)
	at io.micronaut.validation.validator.extractors.DefaultValueExtractors.lambda$new$4(DefaultValueExtractors.java:62)
	at io.micronaut.validation.validator.DefaultValidator.lambda$doValidate$9(DefaultValidator.java:1137)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1137)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToOneIntrospection(DefaultValidator.java:1404)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToOne(DefaultValidator.java:1361)
	at io.micronaut.validation.validator.DefaultValidator.cascadeToIterableValue(DefaultValidator.java:1268)
	at io.micronaut.validation.validator.DefaultValidator.access$800(DefaultValidator.java:98)
	at io.micronaut.validation.validator.DefaultValidator$3.indexedValue(DefaultValidator.java:1166)
	at io.micronaut.validation.validator.extractors.DefaultValueExtractors.lambda$new$4(DefaultValueExtractors.java:62)
	at io.micronaut.validation.validator.DefaultValidator.lambda$doValidate$9(DefaultValidator.java:1137)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1137)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:166)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:133)
	at io.kestra.core.models.validations.ModelValidator.isValid(ModelValidator.java:25)
  ```
</details>

### Version

3.8.7

**Comment by graemerocher** [comment]
validation of generics will be supported in 4.x when it is released
