### ISSUE TITLE
Micronaut 2.5.13 with Java 11, fails to load yml file

### ISSUE THREAD

**Issue by chandan-infa** [micronaut-projects/micronaut-core#9159]
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/9157

<div type='discussions-op-text'>

<sup>Originally posted by **chandan-infa** April 26, 2023</sup>
Hi All,
I am able to run the micronaut project on intellij, After creating a shadow jar.
Shadow jar fails to run due to property loader for yml. 
Have added snakeyaml in the dependencies.

/Users/Library/Java/JavaVirtualMachines/azul-11.0.18/Contents/Home/bin/java -Dio.netty.leakDetectionLevel=advanced -Xms1G -Xmx2G -Djava.io.tmpdir=/mnt/tmp -Dmicronaut.config.files=/Users/Documents/GitHub/services/analyzer/build/libs/conf/application.yml -jar analyzer-1.0-all.jar
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.13)

2023-04-26 20:14:49.737 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.shouldDeduceEnvironments(363)    - Environment deduction is using the default of: true
2023-04-26 20:14:49.767 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.start(250)    - Starting environment io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@140d1230 for active names []
2023-04-26 20:14:49.781 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(500)    - Reading property sources from loader: io.micronaut.jackson.env.JsonPropertySourceLoader@6b8280e6
2023-04-26 20:14:49.781 io.micronaut.context.env.AbstractPropertySourceLoader [main] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(108)    - No PropertySource found for file name: application.json
2023-04-26 20:14:49.782 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(500)    - Reading property sources from loader: io.micronaut.jackson.env.EnvJsonPropertySourceLoader@19382338
2023-04-26 20:14:49.782 io.micronaut.context.env.AbstractPropertySourceLoader [main] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(108)    - No PropertySource found for file name: application.json
2023-04-26 20:14:49.782 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(500)    - Reading property sources from loader: io.micronaut.jackson.env.CloudFoundryVcapApplicationPropertySourceLoader@66420549
2023-04-26 20:14:49.782 io.micronaut.context.env.AbstractPropertySourceLoader [main] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(108)    - No PropertySource found for file name: application.VCAP_APPLICATION
2023-04-26 20:14:49.782 io.micronaut.context.env.DefaultEnvironment [main] DEBUG io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(500)    - Reading property sources from loader: io.micronaut.jackson.env.CloudFoundryVcapServicesPropertySourceLoader@15dc339f
2023-04-26 20:14:49.783 io.micronaut.context.env.AbstractPropertySourceLoader [main] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(108)    - No PropertySource found for file name: application.VCAP_SERVICES
2023-04-26 20:14:49.787 io.micronaut.runtime.Micronaut [main] ERROR io.micronaut.runtime.Micronaut.handleStartupException(326)    - Error starting Micronaut server: Unsupported properties file format: /Users/chrr/Documents/GitHub/cdi-assurance-V2/phoenix-master/services/log-analyzer/build/libs/conf/application.ymlio.micronaut.context.exceptions.ConfigurationException: Unsupported properties file format: /mnt/tmp -Dmicronaut.config.files=/Users/Documents/GitHub/services/analyzer/build/libs/conf/application.yml
	at io.micronaut.context.env.DefaultEnvironment.lambda$readPropertySourceListFromFiles$4(DefaultEnvironment.java:456)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySourceListFromFiles(DefaultEnvironment.java:438)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:396)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:254)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:721)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:689)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:227)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:179)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at com.informatica.gcs.assurance.Application.main(Application.groovy:27)

</div>

**Comment by chandan-infa** [comment]
Missed to add
shadowJar {
    mergeServiceFiles()
}
