### ISSUE TITLE
M3 breaks KAPT compilation

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#9220]
### Actual Behaviour

KAPT fails with:
```
at io.micronaut.annotation.processing.TypeElementVisitorProcessor.getSupportedOptions(TypeElementVisitorProcessor.java:211)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.getSupportedOptions(incrementalProcessors.kt)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.createDependencyCollector(incrementalProcessors.kt:49)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.access$createDependencyCollector(incrementalProcessors.kt:26)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor$dependencyCollector$1.invoke(incrementalProcessors.kt:29)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor$dependencyCollector$1.invoke(incrementalProcessors.kt:29)	
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.getRuntimeType(incrementalProcessors.kt:84)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalAptCache.updateCache(IncrementalAptCache.kt:30)	
	at org.jetbrains.kotlin.kapt3.base.incremental.JavaClassCacheManager.updateCache(cache.kt:23)	
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:100)	
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)	
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:47)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:568)	
	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:311)	
	at org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction.execute(KaptWithoutKotlincTask.kt:257)	
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)	
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)	
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)	
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)	
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)	
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)	
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
```

### Steps To Reproduce

Currently, Micronaut Data fails to compile https://ge.micronaut.io/s/ofbffe5ntinvm/failure?expanded-stacktrace=WyI1LTE3LTI0LTI1Il0#6

### Version

M3

**Comment by dstepanov** [comment]
@graemerocher Can you please take a look?

**Comment by graemerocher** [comment]
I can't reproduce this
