### ISSUE TITLE
Special case of Groovy classes in a custom package are generated with a slash prefix

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#9221]
### Actual Behaviour

Compilation fails:

```
Standard error from JVM:
    Terminating due to fatal error
    java.lang.ClassFormatError: Illegal class name "/$Address2$Introspection" in class file $Address2$Introspection
    	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
    	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
    	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
    	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
    	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:831)
    	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
    	at org.junit.platform.commons.function.Try.of(Try.java:93)
    	at org.junit.platform.commons.function.Try.call(Try.java:57)
    	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:794)
    	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:750)
    	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:74)
    	at com.gradle.enterprise.testdistribution.launcher.forked.b.b(SourceFile:21)
    	at com.gradle.enterprise.testdistribution.launcher.forked.b.a(SourceFile:14)
    	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
    	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
    	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
```

The test case is a special case with Groovy file having a different package:
https://github.com/micronaut-projects/micronaut-data/blob/05371432e8b6b30ca150d4d121668ca22200023d/data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoEmbeddedSpec2.groovy#L50

 Notice:
 ```
 package example  // Keep example package for testing non micronaut package
 ```

It used to work in M2

### Version

M3

**Comment by dstepanov** [comment]
@graemerocher Can you please take a look?
