### ISSUE TITLE
MN:4.0.0-M3: Deserializing @Introspected-annotated data class (Kotlin) fails when using a @Client-annotated declarative client

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-core#9249]
### Expected Behavior

When running test in 
https://github.com/roar-skinderviken/micronaut-M3-introspected-issue
using `mvn clean verify`, I expect test to pass.

We're having a lot of @Introspected-annotated classes with MN:3.9.1 with no issues.

### Actual Behaviour

Test fails with the following start of stack-trace:

```
[ERROR] no.javatec.mn.ApiClientTest  Time elapsed: 0.235 s  <<< ERROR!
io.micronaut.http.client.exceptions.HttpClientResponseException: 
Error decoding HTTP response body: Error decoding stream for type [class no.javatec.mn.TestViewModel]: Missing required creator property 'description' (index 2)
 at [Source: (byte[])"{"id":"4a4a3a69-5712-41e8-acdc-76d90c347c30","name":"~̃test~"}"; line: 1, column: 63]
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeNormalBodyParseError(DefaultHttpClient.java:2285)
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2213)
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2119)
        at io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2091)
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2155)
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2119)
        at io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:49)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:214)
        at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:179)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
```

### Steps To Reproduce

1. Clone https://github.com/roar-skinderviken/micronaut-M3-introspected-issue
2. Run `mvn clean verify`
3. Observe that test is failing

Remove `@Introspected` from `TestViewModel`, and test will pass.

This behavior was discovered along with some other issues when performing a trial migration from MN:3.9.1 to MN:4.0.0-M3 for a real-world app that runs in GKE. We also tested to replace Jackson with micronaut-serialization during the trial-migration, but writing a lot of type converters for enums with constructor, became too overwhelming.

### Environment Information

Ubuntu 22.04
Kotlin 1.8.20
JDK 17

### Example Application

https://github.com/roar-skinderviken/micronaut-M3-introspected-issue

### Version

4.0.0-M3

**Comment by graemerocher** [comment]
Same error occurs in Micronaut 3.9.1 for me

**Comment by roar-skinderviken** [comment]
That is confirmed @graemerocher, we're having all `@Introspected`-annotated classes in lib-repos, Sorry for the inconvenience. I'm closing this issue.

**Comment by roar-skinderviken** [comment]
The final fix in the original application I''m working with, was to replace  ObjectMapper   like shown below.  @Introspected  now works for Kotlin classes with default values.

```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import io.micronaut.context.annotation.Factory
import io.micronaut.context.annotation.Replaces
import jakarta.inject.Singleton

@Factory
class ObjectMapperFactory {

    @Singleton
    @Replaces(ObjectMapper::class)
    fun objectMapper() = jacksonObjectMapper()
}
```
