### ISSUE TITLE
Issue with @Requires(missingBeans) and processed beans throws StackOverflowException.

### ISSUE THREAD

**Issue by alordtas** [micronaut-projects/micronaut-core#9315]
### Expected Behavior

When using the @Requires(missingBeans) on a bean which has method annotations (which I assume) are preprocessed (e.g. @Async or @NotNull), then on the injection of the bean into a constructor, a StackOverflowException is thrown.
Removing @Requires annotation the bean is injected as expected

When injecting a bean which does not have these method annotations, then all works as expected.

### Actual Behaviour

The stack trace is given below:

[36m10:35:50.249[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Startup completed in 1115ms. Server Running: http://localhost:8080
[36m10:35:57.031[0;39m [1;30m[default-nioEventLoopGroup-1-2][0;39m [1;31mERROR[0;39m [35mi.m.http.server.RouteExecutor[0;39m - Unexpected error occurred: Error instantiating bean of type  [com.test.controller.TestController]

Path Taken: new TestController(ServiceOne serviceOne)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.test.controller.TestController]

Path Taken: new TestController(ServiceOne serviceOne)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1583)
	at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:559)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2508)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:601)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:457)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:147)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:224)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:134)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.StackOverflowError: null
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.hasDeclaredAnnotation(DefaultAnnotationMetadata.java:1124)
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.hasAnnotation(DefaultAnnotationMetadata.java:1129)
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.hasStereotype(DefaultAnnotationMetadata.java:1134)
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.resolveRepeatableAnnotations(DefaultAnnotationMetadata.java:1910)
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.resolveAnnotationValuesByType(DefaultAnnotationMetadata.java:1898)
	at io.micronaut.inject.annotation.DefaultAnnotationMetadata.getAnnotationValuesByType(DefaultAnnotationMetadata.java:999)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:98)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinitionReference.isEnabled(AbstractInitializableBeanDefinitionReference.java:180)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2089)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:260)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2047)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:254)
	at io.micronaut.context.RequiresCondition.matchesAbsenceOfBeans(RequiresCondition.java:597)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:219)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:111)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractInitializableBeanDefinition.isEnabled(AbstractInitializableBeanDefinition.java:100)
........

### Steps To Reproduce

See the sample application at

[https://github.com/alordtas/micronaut_requires_bug](https://github.com/alordtas/micronaut_requires_bug)

Run with gradlew run 
and send a Get request to http://localhost:8080/test

When the [TestController ](https://github.com/alordtas/micronaut_requires_bug/blob/main/src/main/java/com/test/controller/TestController.java) class is instantiated (i.e. sending a GET request to the server), the above exception is thrown if [ServiceOne ](https://github.com/alordtas/micronaut_requires_bug/blob/main/src/main/java/com/test/service/impl/ServiceOneImpl.java) or [ServiceTwo ](https://github.com/alordtas/micronaut_requires_bug/blob/main/src/main/java/com/test/service/impl/ServiceTwoImpl.java) is injected but not for [ServiceThree](https://github.com/alordtas/micronaut_requires_bug/blob/main/src/main/java/com/test/service/impl/ServiceThreeImpl.java).

### Environment Information

Project created with the Micronaut mn command and upgraded to Micronaut 3.9.2.

Tested with versions 3.8.7 -> 3.9.2 with the same behaviour.

### Example Application

https://github.com/alordtas/micronaut_requires_bug

### Version

3.9.2

**Comment by graemerocher** [comment]
Triage: this remains a valid Core bean-resolution bug with a public reproducer. The stack shows @Requires(missingBeans) recursively evaluating candidate conditions while a processed/AOP bean is being resolved, eventually re-entering the same candidate search until StackOverflowError. Add a re-entrancy/cycle guard or defer missing-bean condition evaluation until candidate resolution is stable, and preserve the intended semantics for @Async/@NotNull processed beans; add a regression test using the supplied ServiceOne/ServiceTwo shape.
