### ISSUE TITLE
Micronaut v4: `IllegalStateException: cannot send more responses than requests`

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#9366]
### Expected Behavior

1. upgrading to micronaut v4 should not yield new errors for regular http requests
2. we upgraded to micronaut 4 and observed the following exception

### Actual Behaviour

our app happens to use expect/continue, but these exceptions surface even if this functionality is disabled in relevant clients, so it seems not related:

```
[16:25:03.820 ERROR] io.micronaut.http.server.netty.RoutingInBoundHandler Micronaut Server Error - No request state present. Cause: java.lang.IllegalStateException: cannot send more responses than requests
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: cannot send more responses than requests
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:124)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:302)
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.write(PipeliningServerHandler.java:257)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$FullOutboundHandler.writeSome(PipeliningServerHandler.java:765)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.writeSome(PipeliningServerHandler.java:281)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelWritabilityChanged(PipeliningServerHandler.java:226)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:505)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:498)
        at io.netty.handler.stream.ChunkedWriteHandler.channelWritabilityChanged(ChunkedWriteHandler.java:146)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:526)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:505)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:498)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelWritabilityChanged(CombinedChannelDuplexHandler.java:448)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:129)
        at io.netty.channel.CombinedChannelDuplexHandler.channelWritabilityChanged(CombinedChannelDuplexHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:526)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:505)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:498)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1433)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:524)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:505)
        at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:931)
        at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:638)
        at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:604)
        at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:197)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:283)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:362)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:438)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
        at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:313)
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.write(PipeliningServerHandler.java:257)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$FullOutboundHandler.writeSome(PipeliningServerHandler.java:765)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.writeSome(PipeliningServerHandler.java:281)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$OutboundAccess.write(PipeliningServerHandler.java:633)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$OutboundAccess.lambda$write$0(PipeliningServerHandler.java:623)
        at io.micronaut.configuration.metrics.binder.netty.MonitoredQueue$TimedRunnable.run(MonitoredQueue.java:263)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalStateException: cannot send more responses than requests
        at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:125)
        at io.micronaut.http.server.netty.SmartHttpContentCompressor.encode(SmartHttpContentCompressor.java:65)
        at io.micronaut.http.server.netty.SmartHttpContentCompressor.encode(SmartHttpContentCompressor.java:33)
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
        ... 77 common frames omitted
```

### Steps To Reproduce

investigating

### Environment Information

- Operating System: macOS Ventura 13.3.1
- JDK:
```
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Zulu20.30+11-CA (build 20.0.1+9)
OpenJDK 64-Bit Server VM Zulu20.30+11-CA (build 20.0.1+9, mixed mode, sharing)
```

### Example Application

pending

### Version

4.0.0-Mx

**Comment by graemerocher** [comment]
you don't happen to have an example that reproduces?

**Comment by sgammon** [comment]
@graemerocher i'm trying to isolate but we only observe it under load in our regular app so far

**Comment by yawkat** [comment]
i'm not sure what could cause this, PipeliningServerHandler does its own duplicate detection that's supposed to prevent this. i can think of only two options: something weird with a streaming response returning a HttpResponse mid-stream, or a bug in PipeliningServerHandler.

**Comment by graemerocher** [comment]
the error is coming from a web socket connection, not sure if that has an impact

**Comment by yawkat** [comment]
i doubt it from the stack trace

**Comment by graemerocher** [comment]
I assume that was the case based on this:

```
[16:25:03.820 ERROR] io.micronaut.http.server.netty.RoutingInBoundHandler Micronaut Server Error - No request state present. Cause: java.lang.IllegalStateException: cannot send more responses than requests
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: cannot send more responses than requests
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:124)
  ```

ie `WebSocketServerExtensionHandler.write`

**Comment by yawkat** [comment]
that's just the WebSocketServerCompressionHandler, we add it to every pipeline.

**Comment by graemerocher** [comment]
Gotcha

**Comment by asantare** [comment]
I'm having the same problem when upgrading to Micronaut v4.

[demo.zip](https://github.com/micronaut-projects/micronaut-core/files/12173642/demo.zip)

I've uploaded a demo project with a fake test.
It seems the problem is related to the PipeliningServerHandler implementation, which is very difficult to read (shared properties (not volatile) updated by various threads).

I was able to reproduce it and it appears to occur when:
- multiple threads are involved (I'm using coroutines)
- the server does partial flushes of the response (I'm using jackson JsonNode)
- big response (more than the high of WriteBufferWaterMark.DEFAULT of netty)

**Comment by yawkat** [comment]
@asantare thanks! i can reproduce it, will take a look.

**Comment by yawkat** [comment]
thanks for the reproducer @asantare , that really helped a lot.

**Comment by asantare** [comment]
I'm happy that it helped (and btw I had fun debugging and trying to reproduce it :)). 
Thank you for the swift fix! and the proper test case :))
