### ISSUE TITLE
Health checks stop working under graal native image

### ISSUE THREAD

**Issue by wwadge** [micronaut-projects/micronaut-core#944]
Management endpoints cease to work under native compile via graalvm.

### Steps to Reproduce

1. git clone https://github.com/wwadge/micronaut-graalvm-native-basic.git
2. ./gradlew dockerBuildCurrentImage
3. docker run -it -p 8080:8080 complete
4. curl localhost:8080/health

### Expected Behaviour

Management health endpoint should return data under native compile. 

### Actual Behaviour

This works if you use the fat-jar (java -jar complete-0.1-all.jar) but acts as if management endpoint wasn't switched on under native compile.

### Environment Information

- **Operating System**: OSX/docker
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8

### Example Application

https://github.com/wwadge/micronaut-graalvm-native-basic.git

**Comment by ilopmar** [comment]
Just a bit more information. When sending the curl it return 404 and in the log we can see:

```
11:21:14.928 [nioEventLoopGroup-2-2] DEBUG i.m.web.router.RouteMatchUtils - Route match attribute for request (/health) not found
```

If we keep the server running a few more minutes we see the following error which maybe it's related to this issue:
```
$ docker run -it --rm -p 8080:8080 micronaut-graalvm-native-basic:0059eb61
11:21:11.830 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 54ms. Server Running: http://6ba96cc72707:8080
11:21:14.928 [nioEventLoopGroup-2-2] DEBUG i.m.web.router.RouteMatchUtils - Route match attribute for request (/health) not found
11:22:11.829 [pool-2-thread-4] ERROR i.m.s.DefaultTaskExceptionHandler - Error invoking scheduled task Failed to inject value for parameter [discoveryClient] of class: io.micronaut.management.health.indicator.discovery.DiscoveryClientHealthIndicator

Path Taken: new HealthMonitorTask(CurrentHealthStatus currentHealthStatus,[HealthIndicator[] healthIndicators]) --> new DiscoveryClientHealthIndicator([DiscoveryClient discoveryClient])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [discoveryClient] of class: io.micronaut.management.health.indicator.discovery.DiscoveryClientHealthIndicator

Path Taken: new HealthMonitorTask(CurrentHealthStatus currentHealthStatus,[HealthIndicator[] healthIndicators]) --> new DiscoveryClientHealthIndicator([DiscoveryClient discoveryClient])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.DependencyInjectionException.<init>(DependencyInjectionException.java:42)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.management.health.indicator.discovery.$DiscoveryClientHealthIndicatorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2237)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2165)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:765)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1079)
	at io.micronaut.context.AbstractBeanDefinition$$Lambda$673/1790606474.resolveBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1674)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1074)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:950)
	at io.micronaut.management.health.monitor.$HealthMonitorTaskDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:507)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:109)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor$$Lambda$802/491056313.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.management.health.indicator.discovery.DiscoveryClientHealthIndicator]

Message: Class io.micronaut.discovery.DiscoveryClient[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.RuntimeReflection
Path Taken: new HealthMonitorTask(CurrentHealthStatus currentHealthStatus,[HealthIndicator[] healthIndicators]) --> new DiscoveryClientHealthIndicator([DiscoveryClient discoveryClient])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.BeanInstantiationException.<init>(BeanInstantiationException.java:50)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1343)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:896)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class io.micronaut.discovery.DiscoveryClient[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.RuntimeReflection
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
	at com.oracle.svm.core.genscavenge.graal.AllocationSnippets.checkArrayHub(AllocationSnippets.java:182)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:951)
	at io.micronaut.discovery.$DefaultCompositeDiscoveryClientDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
	... 32 common frames omitted
```

**Comment by ilopmar** [comment]
Yes, I think it should be included. I've tried manually modifying the generated `reflect.json` with:
```
{
  "name" : "[Lio.micronaut.discovery.DiscoveryClient",
  "allDeclaredConstructors" : true
}
```
But I get this error:
```
[mn-management-endpoints-graal:26661]    classlist:   5,130.85 ms
[mn-management-endpoints-graal:26661]        (cap):   1,044.63 ms
[mn-management-endpoints-graal:26661]        setup:   1,770.50 ms
error: Error parsing reflection configuration in /home/ivan/workspaces/micronaut-apps/mn-management-endpoints-graal/build/reflect.json:
Class [Lio.micronaut.discovery.DiscoveryClient not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Image building with exit status 1
```

And declaring it without being an array:
```
{
  "name" : "io.micronaut.discovery.DiscoveryClient",
  "allDeclaredConstructors" : true,
}
```
Doesn't fix the exception.

**Comment by wwadge** [comment]
This looks related to some missing declarations in reflect.json eg: io.micronaut.management.endpoint.EndpointEnabledCondition is missing

**Comment by wwadge** [comment]
Got it to work:
```[
  {
    "name": "io.micronaut.management.endpoint.EndpointEnabledCondition",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  }
]
```
together with
```

@AutomaticFeature
public class RuntimeReflectionRegistrationFeature implements Feature {
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        RuntimeReflection.register(DiscoveryClient[].class);
        RuntimeReflection.register(javax.sql.DataSource[].class);
        RuntimeReflection.register(HealthIndicator[].class);
     
    }
}
```
