### ISSUE TITLE
Multiple possible bean candidates found when calling subclass

### ISSUE THREAD

**Issue by LajosPolya** [micronaut-projects/micronaut-core#9494]
### Expected Behavior

Given a base class with multiple subclasses, when one of the subclasses are dependency injected, then an exception shouldn't be thrown when one of the injected class' methods are called.

### Actual Behaviour

**Summary**:
`io.micronaut.context.exceptions.NonUniqueBeanException` thrown when calling a method on one of the injected subclasses of a base class.

**Root cause**:
After some digging I found the root cause of the error.

The execution flow starts in [DefaultParameterNameProvider::getParameterNames](https://github.com/micronaut-projects/micronaut-hibernate-validator/blob/2.0.x/hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/DefaultParameterNameProvider.java#L66) but eventually leads to the methods below.

In micornaut-inject-3.4.4 [DefaultBeanContext.java::findBeanDefinition(Argument beanType, Qualifier qualifier)](https://github.com/micronaut-projects/micronaut-core/blob/3.4.x/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java#L796) calls `findConcreteCandidate` setting the `throwNonUnique` parameter to `false`.

In micronaut-ingect-3.5.0 [DefaultBeanContext.java::findBeanDefinition(Argument beanType, Qualifier qualifier)](https://github.com/micronaut-projects/micronaut-core/blob/3.5.x/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java#L786) calls `findConcreteCandidate` setting the `throwNonUnique` parameter to `true`.

This was most likely introduced during a refactor: https://github.com/micronaut-projects/micronaut-core/pull/7196

Does this mean this is a bug? And how can I circumvent this?

**Explanation and Example**:

On this project I use a design pattern that allows a service to communicate with a specific datasource depending on whether the current transaction is readonly. Here's the code example below:

```
import io.micronaut.transaction.support.TransactionSynchronizationManager

open class RepositoryProvider<T>(
    private val readOnlyRepo: T,
    private val readWriteRepo: T
) {

    val repo: T
        get() {
            val readOnlyTransaction = TransactionSynchronizationManager.isCurrentTransactionReadOnly()
            return if (readOnlyTransaction) readOnlyRepo else readWriteRepo
        }
}
```

```
import io.micronaut.data.annotation.Repository
import javax.inject.Named
import javax.inject.Singleton
import javax.persistence.EntityManager
import javax.transaction.Transactional


@Singleton
class ExampleRepositoryProvider(
        readOnlyRepository: ExampleReadOnlyRepository,
        readWriteRepository: ExampleReadWriteRepository
) : RepositoryProvider<ExampleRepository>(readOnlyRepository, readWriteRepository)


@Repository("default")
abstract class ExampleReadWriteRepository(
        @Named("default") entityManager: EntityManager
) : ExampleRepository(entityManager)

@Repository("readonly")
abstract class ExampleReadOnlyRepository(
        @Named("readonly") entityManager: EntityManager
) : ExampleRepository(entityManager)


// Always obtain an instance using ExampleRepositoryProvider
abstract class ExampleRepository(
        private val entityManager: EntityManager
) {

    @Transactional
    fun findByExample() {
        val criteriaBuilder = entityManager.criteriaBuilder
        ...
    }
}

```

In Micronaut 3.4.4 I'm able to inject the `ExampleRepositoryProvider` into a service and call the `findByExample` method without any issues. But after updating to 3.5.0 (I've also tried newer 3.x and 4 versions), when the service tries to call the method a `io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found:` exception is throw.

An example of how the repository is used:

```

import com.example.repository.ExampleRepositoryProvider
import javax.inject.Singleton

@Singleton
class ExampleService(
    private val exampleRepositoryProvider: ExampleRepositoryProvider,
) {

     fun example() {
         // when debugging I can tell that the correct instance of the repo is returned
        val repo = exampleRepositoryProvider.repo
        // but an exception is thrown when this method is called
        repo.findByExample()
    }
}
```

In version 3.4.4 I can see that [DefaultParameterNameProvider::getParameterNames](https://github.com/micronaut-projects/micronaut-hibernate-validator/blob/2.0.x/hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/DefaultParameterNameProvider.java#L66) is called with `ExampleRepository` and everything works fine, but in version 3.5.0 I can see that `ExampleReadOnlyRepository` and `ExampleReadWriteRepository` are both found as candidates and therefore an exception is thrown.

### Steps To Reproduce

See **Root Cause** section

### Environment Information

- OS: MacOS Ventura 13.4
- JDK Version: Temurin-16
- Micronaut Version: 3.5.0 and beyond
- `io.micronaut.configuration:micronaut-hibernate-validator:2.0.0`

### Version

3.5.0 and beyond

**Comment by LajosPolya** [comment]
@dstepanov Do you mind taking a look at this since you worked on https://github.com/micronaut-projects/micronaut-core/pull/7196?

**Comment by dstepanov** [comment]
The latest behavior is correct before it returns the first bean, which is invalid.
I suspect the validator code needs to get the owner class, not the declared one, to find the bean.
As a workaround, you might try to add `@Order` annotation.

**Comment by LajosPolya** [comment]
But after the line `val repo = exampleRepositoryProvider.repo` I could see that the correct bean is returned. The failure occurs at `repo.findByExample()`. 


At this point  [DefaultParameterNameProvider::getParameterNames](https://github.com/micronaut-projects/micronaut-hibernate-validator/blob/2.0.x/hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/DefaultParameterNameProvider.java#L66) is called with the correct subclass' constructor, but right after it's called with the base class' constructor and that's when the failure occurs. At that point shouldn't it already know which child class to return?

**Comment by dstepanov** [comment]
Can you post a stacktrace?

**Comment by LajosPolya** [comment]
```
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [com.example.ExampleReadOnlyRepository$Intercepted, com.example.ExampleReadWriteRepository$Intercepted]
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3207)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3112)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3030)
	at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:784)
	at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:793)
	at io.micronaut.context.BeanDefinitionRegistry.findBeanDefinition(BeanDefinitionRegistry.java:566)
	at io.micronaut.configuration.hibernate.validator.DefaultParameterNameProvider.getParameterNames(DefaultParameterNameProvider.java:66)
	at org.hibernate.validator.internal.util.ExecutableParameterNameProvider.getParameterNames(ExecutableParameterNameProvider.java:40)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable.getParameterName(JavaBeanExecutable.java:86)
	at org.hibernate.validator.internal.metadata.aggregated.ParameterMetaData$Builder.build(ParameterMetaData.java:165)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.findParameterMetaData(ExecutableMetaData.java:436)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:391)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataBuilder$BuilderDelegate.build(BeanMetaDataBuilder.java:260)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataBuilder.build(BeanMetaDataBuilder.java:133)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.createBeanMetaData(BeanMetaDataManagerImpl.java:206)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanMetaData(BeanMetaDataManagerImpl.java:165)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:267)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:235)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:91)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.ExampleReadWriteRepository$Intercepted.findByExample(Unknown Source)
	at com.example.ExampleService.example$lambda-0(ExampleService.kt:14)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.micronaut.rxjava2.instrument.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by dstepanov** [comment]
It's a bit strange why this is trying to validate the constructor.

Can you debug and see what is the constructor name `DefaultParameterNameProvider.java:66`?

**Comment by LajosPolya** [comment]
That method is executed a couple of times. The first time it's executed for `ExampleReadWriteRepository`. Then the second time that breakpoint is hit it's executed for the base class `ExampleRepository`, which is when the failure occurs.

**Comment by dstepanov** [comment]
You should use Micronaut Hibernate Validator 3, which has this problem fixed.

**Comment by LajosPolya** [comment]
@dstepanov I don't believe it's released yet. I only see up to version 2.0.0 on https://mvnrepository.com/artifact/io.micronaut.configuration/micronaut-hibernate-validator

**Comment by LajosPolya** [comment]
I switched to `io.micronaut.beanvalidation:micronaut-hibernate-validator:3.3.0`, updated some dependencies and everything works now. Thanks!

**Comment by lpolya-tl** [comment]
Just in case anyone else runs into this issue. After updating to version 3.9.4 I had to update the repositories to the following:
```
@Repository("default")
@TransactionalAdvice("default")
abstract class ExampleReadWriteRepository(
        @PersistenceContext
        @Named("default") private val entityManager: EntityManager
) : ExampleRepository(entityManager)

@Repository("readonly")
@TransactionalAdvice("readonly")
abstract class ExampleReadOnlyRepository(
        @PersistenceContext(name = "readonly")
        @Named("readonly") private val entityManager: EntityManager
) : ExampleRepository(entityManager)

```

**Comment by LajosPolya** [comment]
Just in case anyone else runs into this issue. After updating to version 3.9.4 I had to update the repositories to the following:

```
@Repository("default")
@TransactionalAdvice("default")
abstract class ExampleReadWriteRepository(
    @PersistenceContext
    @Named("default") private val entityManager: EntityManager
) : ExampleRepository(entityManager)

@Repository("readonly")
@TransactionalAdvice("readonly")
abstract class ExampleReadOnlyRepository(
    @PersistenceContext(name = "readonly")
    @Named("readonly") private val entityManager: EntityManager
) : ExampleRepository(entityManager)
```
