### ISSUE TITLE
health endpoing not working with Tomacat embedded

### ISSUE THREAD

**Issue by bhattumang7** [micronaut-projects/micronaut-core#9527]
### Expected Behavior

When running using Tomcat, the health endpoint should respond with available health information.

### Actual Behaviour

We are facing an error when hitting the health endpoint when running with Tomcat. 
Here is a sample repository that reproduces the error. We have to open `\health` endpoint. 
[https://github.com/bhattumang7/micronaut-tomcat-health](https://github.com/bhattumang7/micronaut-tomcat-health)

Here is the stack trace:

```
16:47:07.779 [io-executor-thread-1] ERROR i.m.servlet.http.ServletHttpHandler - Request [null - /health] completed with error: Failed to encode object [io.micronaut.management.health.indicator.DefaultHealthResult@6d921e93] to content type [application/json]: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@6d921e93] to JSON: Failed write
io.micronaut.http.codec.CodecException: Failed to encode object [io.micronaut.management.health.indicator.DefaultHealthResult@6d921e93] to content type [application/json]: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@6d921e93] to JSON: Failed write
        at io.micronaut.servlet.http.ServletHttpHandler.encodeResponse(ServletHttpHandler.java:882)
        at io.micronaut.servlet.http.ServletHttpHandler.lambda$subscribeToResponsePublisher$15(ServletHttpHandler.java:546)
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955)
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:248)
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:56)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955)
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955)
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955)
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
        at io.micronaut.servlet.http.ServletHttpHandler$1.doOnNext(ServletHttpHandler.java:714)
        at io.micronaut.servlet.http.ServletHttpHandler$1.doOnNext(ServletHttpHandler.java:705)
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:56)
        at io.micronaut.core.async.publisher.Publishers$2.doOnNext(Publishers.java:292)
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:56)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2034)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:894)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:997)
        at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.http.codec.CodecException: Error encoding object [io.micronaut.management.health.indicator.DefaultHealthResult@6d921e93] to JSON: Failed write
        at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:212)
        at io.micronaut.servlet.http.ServletHttpHandler.encodeResponse(ServletHttpHandler.java:879)
        ... 64 common frames omitted
Caused by: org.apache.coyote.CloseNowException: Failed write
        at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:549)
        at org.apache.coyote.http11.filters.IdentityOutputFilter.doWrite(IdentityOutputFilter.java:73)
        at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:194)
        at org.apache.coyote.Response.doWrite(Response.java:615)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:340)
        at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:784)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:299)
        at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:252)
        at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:157)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1245)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4629)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3828)
        at io.micronaut.jackson.databind.JacksonDatabindMapper.writeValue(JacksonDatabindMapper.java:124)
        at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:210)
```

### Steps To Reproduce

1. Clone git repository from [https://github.com/bhattumang7/micronaut-tomcat-health](https://github.com/bhattumang7/micronaut-tomcat-health)
2. Run the application using gradle run.
3. open the web browser and open http://localhost:8080/health

### Environment Information

- Windows 10 
- Java 17
- Mironaut version 3.9.2. Able to reproduce with the latest version as well.

### Example Application

https://github.com/bhattumang7/micronaut-tomcat-health

### Version

3.9.2

**Comment by npathai** [comment]
@graemerocher Do we have an ETA for the fix? If you could point us in the right direction, we can try to fix and submit a PR.
