### ISSUE TITLE
"Error loading BeanIntrospection" during Jackson serialization

### ISSUE THREAD

**Issue by jeremyg484** [micronaut-projects/micronaut-core#9528]
### Expected Behavior

In implementing the new graphql-ws protocol support in micronaut-graphql, we need to exchange various JSON message types with the client that are specified by the protocol. I created a hierarchy of `Message` classes to match the JSON message types. These types should all be serializable to JSON, using standard Jackson databind annotations for the mapping.

The message types as I would prefer to structure them are all defined here in this micronaut-graphql branch: 
https://github.com/micronaut-projects/micronaut-graphql/blob/SerializationError/graphql/src/main/java/io/micronaut/configuration/graphql/ws/Message.java

Note that sealed classes are being used to define the type structure.
 

### Actual Behaviour

When executing any of the features of the [GraphQLWsHandlerSpec](https://github.com/micronaut-projects/micronaut-graphql/blob/SerializationError/graphql/src/test/groovy/io/micronaut/configuration/graphql/ws/GraphQLWsHandlerSpec.groovy) that test handling of the [SubscribeMessage](https://github.com/micronaut-projects/micronaut-graphql/blob/e91ef4ef99fc48117189037e98115d757073c18b/graphql/src/main/java/io/micronaut/configuration/graphql/ws/Message.java#L290) type, serialization from the test client fails with the following error:

```
Error loading BeanIntrospection for type [class io.micronaut.configuration.graphql.ws.SubscribeMessage]: Bad type on operand stack
Exception Details:
  Location:
    io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection.dispatchOne(ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @106: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[3]) is not assignable to 'io/micronaut/configuration/graphql/ws/SubscribeMessage$SubscribePayload'
  Current Frame:
    bci: @106
    flags: { }
    locals: { 'io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection', integer, 'java/lang/Object', 'java/lang/Object', top, 'io/micronaut/configuration/graphql/ws/SubscribeMessage' }
    stack: { uninitialized 93, uninitialized 93, 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: 1baa 0000 0000 0093 0000 0000 0000 0007
    0000010: 0000 002f 0000 0037 0000 004e 0000 0056
    0000020: 0000 006d 0000 0075 0000 0080 0000 0088
    0000030: 2cc0 0061 b600 6fb0 2cc0 0061 3a04 bb00
    0000040: 6159 1904 b600 732d c000 44b7 0076 b02c
    0000050: c000 61b6 0073 b02c c000 613a 05bb 0061
    0000060: 592d c000 3219 05b6 006f b700 76b0 2cc0
    0000070: 0061 b600 79b0 bb00 7b59 127d b700 80bf
    0000080: bf2c c000 61b6 0084 b0bb 007b 5912 86b7
    0000090: 0080 bfbf 2a1b b600 8abf               
  Stackmap Table:
    same_frame(@48)
    same_frame(@56)
    same_frame(@79)
    same_frame(@87)
    same_frame(@110)
    same_frame(@118)
    full_frame(@128,{},{Object[#140]})
    full_frame(@129,{Object[#2],Integer,Object[#142],Object[#142]},{})
    same_frame(@137)
    full_frame(@147,{},{Object[#140]})
    full_frame(@148,{Object[#2],Integer,Object[#142],Object[#142]},{})

io.micronaut.core.beans.exceptions.IntrospectionException: Error loading BeanIntrospection for type [class io.micronaut.configuration.graphql.ws.SubscribeMessage]: Bad type on operand stack
Exception Details:
  Location:
    io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection.dispatchOne(ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @106: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[3]) is not assignable to 'io/micronaut/configuration/graphql/ws/SubscribeMessage$SubscribePayload'
  Current Frame:
    bci: @106
    flags: { }
    locals: { 'io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection', integer, 'java/lang/Object', 'java/lang/Object', top, 'io/micronaut/configuration/graphql/ws/SubscribeMessage' }
    stack: { uninitialized 93, uninitialized 93, 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: 1baa 0000 0000 0093 0000 0000 0000 0007
    0000010: 0000 002f 0000 0037 0000 004e 0000 0056
    0000020: 0000 006d 0000 0075 0000 0080 0000 0088
    0000030: 2cc0 0061 b600 6fb0 2cc0 0061 3a04 bb00
    0000040: 6159 1904 b600 732d c000 44b7 0076 b02c
    0000050: c000 61b6 0073 b02c c000 613a 05bb 0061
    0000060: 592d c000 3219 05b6 006f b700 76b0 2cc0
    0000070: 0061 b600 79b0 bb00 7b59 127d b700 80bf
    0000080: bf2c c000 61b6 0084 b0bb 007b 5912 86b7
    0000090: 0080 bfbf 2a1b b600 8abf               
  Stackmap Table:
    same_frame(@48)
    same_frame(@56)
    same_frame(@79)
    same_frame(@87)
    same_frame(@110)
    same_frame(@118)
    full_frame(@128,{},{Object[#140]})
    full_frame(@129,{Object[#2],Integer,Object[#142],Object[#142]},{})
    same_frame(@137)
    full_frame(@147,{},{Object[#140]})
    full_frame(@148,{Object[#2],Integer,Object[#142],Object[#142]},{})

	at app//io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:104)
	at app//io.micronaut.jackson.modules.BeanIntrospectionModule.findIntrospection(BeanIntrospectionModule.java:170)
	at app//io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionSerializerModifier.updateBuilder(BeanIntrospectionModule.java:302)
	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:468)
	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:295)
	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:240)
	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at app//com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1503)
	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1451)
	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:556)
	at app//com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:834)
	at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:307)
	at app//com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at app//com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3923)
	at app//io.micronaut.jackson.databind.JacksonDatabindMapper.writeValue(JacksonDatabindMapper.java:194)
	at app//io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:231)
	at app//io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:280)
	at app//io.micronaut.http.netty.websocket.WebSocketMessageEncoder.encodeMessage(WebSocketMessageEncoder.java:74)
	at app//io.micronaut.http.netty.websocket.NettyWebSocketSession.sendSync(NettyWebSocketSession.java:179)
	at app//io.micronaut.websocket.interceptor.ClientWebSocketInterceptor.send(ClientWebSocketInterceptor.java:112)
	at app//io.micronaut.websocket.interceptor.ClientWebSocketInterceptor.intercept(ClientWebSocketInterceptor.java:89)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.configuration.graphql.ws.GraphQLWsHandlerSpec.client subscribes to a single-result query operation and receives result(GraphQLWsHandlerSpec.groovy:101)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection.dispatchOne(ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @106: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[3]) is not assignable to 'io/micronaut/configuration/graphql/ws/SubscribeMessage$SubscribePayload'
  Current Frame:
    bci: @106
    flags: { }
    locals: { 'io/micronaut/configuration/graphql/ws/$SubscribeMessage$Introspection', integer, 'java/lang/Object', 'java/lang/Object', top, 'io/micronaut/configuration/graphql/ws/SubscribeMessage' }
    stack: { uninitialized 93, uninitialized 93, 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: 1baa 0000 0000 0093 0000 0000 0000 0007
    0000010: 0000 002f 0000 0037 0000 004e 0000 0056
    0000020: 0000 006d 0000 0075 0000 0080 0000 0088
    0000030: 2cc0 0061 b600 6fb0 2cc0 0061 3a04 bb00
    0000040: 6159 1904 b600 732d c000 44b7 0076 b02c
    0000050: c000 61b6 0073 b02c c000 613a 05bb 0061
    0000060: 592d c000 3219 05b6 006f b700 76b0 2cc0
    0000070: 0061 b600 79b0 bb00 7b59 127d b700 80bf
    0000080: bf2c c000 61b6 0084 b0bb 007b 5912 86b7
    0000090: 0080 bfbf 2a1b b600 8abf               
  Stackmap Table:
    same_frame(@48)
    same_frame(@56)
    same_frame(@79)
    same_frame(@87)
    same_frame(@110)
    same_frame(@118)
    full_frame(@128,{},{Object[#140]})
    full_frame(@129,{Object[#2],Integer,Object[#142],Object[#142]},{})
    same_frame(@137)
    full_frame(@147,{},{Object[#140]})
    full_frame(@148,{Object[#2],Integer,Object[#142],Object[#142]},{})

	at app//io.micronaut.core.beans.DefaultBeanIntrospector.lambda$findIntrospection$0(DefaultBeanIntrospector.java:95)
	at java.base@17.0.6/java.util.Optional.map(Optional.java:260)
	at app//io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:91)
	... 22 more
```

I have tried various solutions such as adding `@Introspected` annotations, and relocating `SubscribePayload` to a top-level class, but they do not make a difference. I ultimately had to work around the issue by using a `Map<String, Object>` for the payload of the `SubscribeMessage` instead of the `SubscribePayload` inner class. 

### Steps To Reproduce

1. Pull the `SerializationError` branch from [micronaut-graphql](https://github.com/micronaut-projects/micronaut-graphql/tree/SerializationError)
2. Execute the `GraphQLWsHandlerSpec`

### Environment Information

- macOS Monterey 12.5
- Tested with both GraaalVM CE 17.0.7 and Temurin 17.0.7

### Example Application

https://github.com/micronaut-projects/micronaut-graphql/tree/SerializationError

### Version

4.0.0.RC3

**Comment by nbrugger-tgm** [comment]
@dstepanov the same happened to me created a reproducer

is this covered too? https://github.com/nbrugger-tgm/micronaut-bytecode-reproducer

This is a very minimal example with one change commit - its very simmilar and can be circumvented by changing the `Boolean` to `boolean`. Is at least very closely related:
```    Type top (current frame, stack[7]) is not assignable to 'java/lang/Boolean'```

**Comment by yawkat** [comment]
@nbrugger-tgm can you create a new issue? i dont want to reopen this one
