### ISSUE TITLE
Client Connection Pool gets into an unrecoverable state

### ISSUE THREAD

**Issue by Discordia** [micronaut-projects/micronaut-core#9545]
### Issue description

The problem is that we see that the client connection pool at times gets into an unrecoverable state where there seem to be old connections that can't be used but are filling up the pool and new ones can't be created because the max-connections are hit.

I have not put in as a `bug` but rather `other` as I do not have a way of reproducing it, but I have put in a post in https://gitter.im that got low traction and now also a StackOverflow post: https://stackoverflow.com/questions/76639572/client-connection-pool-gets-into-an-unrecoverable-state

Micronuat version is 3.8.4. (We are testing out Micronuat 3.9.4 on one service to see if that helps.)

The error thrown is: 
```
Connect Error: Too many outstanding acquire operations
	at io.micronaut.http.client.netty.ConnectionManager.lambda$connectForExchange$6(ConnectionManager.java:480)
	at io.micronaut.http.client.netty.ConnectionManager.lambda$addInstrumentedListener$16(ConnectionManager.java:907)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [1 skipped]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Too many outstanding acquire operations
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [4 skipped]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [1 skipped]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	... 4 common frames omitted
```

We are looking for any ideas on how to debug or look into a problem with the client connection pool in Micronaut.
We can't reproduce this at will but we have had it happen to us between 20-30 times in the last few months.
It is often preceded by a request spike but it does not have to be. It can also be (we think) that the service the client connection pool calls are behaving badly or the IP used are removed from the DNS.

Client connection pool config values that seem relevant:

```
micronaut.http.client.read-timeout=PT6S
micronaut.http.client.read-idle-timeout=PT6S
micronaut.http.client.connect-timeout=PT2S
micronaut.http.client.connect-ttl=PT60S
micronaut.http.client.pool.enabled=true
micronaut.http.client.pool.max-connections=50
micronaut.http.client.pool.max-pending-acquires=50
micronaut.http.client.pool.acquire-timeout=PT10S
micronaut.http.client.connection-pool-idle-timeout=60s
```

**Comment by yawkat** [comment]
this is likely #9449

**Comment by yawkat** [comment]
@Discordia can you verify whether this is fixed with the latest 3.10?

You could also upgrade to 4.x, which replaces the client connection pooling logic entirely.

**Comment by Discordia** [comment]
Hi, I will try out 3.10 first and then report back. It will take some time to verify as we have no way of really reproducing this. Will have to have it running for a while.

**Comment by Discordia** [comment]
We have not seen this on Mn 3.10.x. So I think this can be closed, we have not tested with MN 4.x yet.

**Comment by yawkat** [comment]
ok thank you!
