### ISSUE TITLE
Kotlin KSP failes with `java.lang.NullPointerException: Cannot read the array length because "<local3>" is null`

### ISSUE THREAD

**Issue by Spikhalskiy** [micronaut-projects/micronaut-core#9593]
### Expected Behavior

The project currently builds using KAPT with Micronaut 4 and works as expected. 
The expectation is that we drop in KSP instead of KAPT and the project still builds successfully.

### Actual Behaviour

```
> Task :kspKotlin
i: [ksp] loaded provider(s): [io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessorProvider, io.micronaut.kotlin.processing.beans.BeanDefinitionProcessorProvider]
e: [ksp] Originating element: apiKey
e: [ksp] <our_package>/StripeConfig.kt:35: Cannot read the array length because "<local3>" is null

error message: java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at io.micronaut.core.naming.NameUtils.isReaderName(NameUtils.java:362)
	at io.micronaut.context.visitor.ConfigurationReaderVisitor.isGetter(ConfigurationReaderVisitor.java:179)
	at io.micronaut.context.visitor.ConfigurationReaderVisitor.visitAbstractMethod(ConfigurationReaderVisitor.java:135)
	at io.micronaut.context.visitor.ConfigurationReaderVisitor.visitMethod(ConfigurationReaderVisitor.java:99)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor$visitNativeProperty$3.invoke(TypeElementSymbolProcessor.kt:350)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor$visitNativeProperty$3.invoke(TypeElementSymbolProcessor.kt:350)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitNativeProperty$lambda$6(TypeElementSymbolProcessor.kt:350)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitNativeProperty(TypeElementSymbolProcessor.kt:350)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitMembers(TypeElementSymbolProcessor.kt:282)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitClassDeclaration(TypeElementSymbolProcessor.kt:270)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor.process(TypeElementSymbolProcessor.kt:124)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:289)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:289)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execAndOutputXml(CLICompiler.kt:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileInProcessImpl(GradleKotlinCompilerWork.kt:360)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.access$compileInProcessImpl(GradleKotlinCompilerWork.kt:78)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:333)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:332)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

The class structure that triggers this problem according to the logs and works fine with kapt:

```
@Context
@ConfigurationProperties(StripeConfig.PREFIX)
class StripeConfig {
    companion object {
        const val PREFIX = "stripe"
    }

    @Valid
    @NotNull
    var usa: UsaStripeClientConfig = UsaStripeClientConfig()

    @Valid
    @NotNull
    var canada: CanadaStripeClientConfig = CanadaStripeClientConfig()

    @Introspected
    interface StripeClientConfig {
        val apiKey: String
        val webhookSecret: String
    }

    @Context
    @ConfigurationProperties(UsaStripeClientConfig.PREFIX)
    @Introspected
    class UsaStripeClientConfig : StripeClientConfig {
        internal companion object {
            internal const val PREFIX = "usa"
        }

        override lateinit var apiKey: String
        override lateinit var webhookSecret: String
    }

    @Context
    @ConfigurationProperties(CanadaStripeClientConfig.PREFIX)
    @Introspected
    class CanadaStripeClientConfig : StripeClientConfig {
        internal companion object {
            internal const val PREFIX = "canada"
        }

        override lateinit var apiKey: String
        override lateinit var webhookSecret: String
    }
}

```

### Environment Information

Java 17.0.7

### Version

Micronaut Platform: 4.0.1
Kotlin: 1.8.20 && 1.9.0
KSP: 1.8.20-1.0.12 && 1.9.0-1.0.12

**Comment by Spikhalskiy** [comment]
I tried build with the just released Micronaut Platform 4.0.4 and the same issue is present
