### ISSUE TITLE
Error in kotlin controller that does not return a result

### ISSUE THREAD

**Issue by bvella** [micronaut-projects/micronaut-core#9611]
### Expected Behavior

it should work by returning an empty http body

### Actual Behaviour

io.micronaut.http.codec.CodecException: Error encoding object [kotlin.Unit] to JSON: No serializable introspection present for type Unit. Consider adding Serdeable. Serializable annotate to type Unit. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Unit.class) to enable serialization of this type.
	at io.micronaut.json.body.JsonMessageHandler.decorateWrite(JsonMessageHandler.java:127) ~[micronaut-json-core-4.0.0.jar:4.0.0]
	at io.micronaut.json.body.JsonMessageHandler.writeTo(JsonMessageHandler.java:136) ~[micronaut-json-core-4.0.0.jar:4.0.0]
	at io.micronaut.http.body.MessageBodyWriter.writeTo(MessageBodyWriter.java:138) ~[micronaut-http-4.0.0.jar:4.0.0]
	at io.micronaut.http.netty.body.NettyJsonHandler.writeTo(NettyJsonHandler.java:133) ~[micronaut-http-netty-4.0.0.jar:4.0.0]
	at io.micronaut.http.server.netty.RoutingInBoundHandler$CompatNettyWriteClosure.writeTo(RoutingInBoundHandler.java:546) ~[micronaut-http-server-netty-4.0.0.jar:4.0.0]
	at io.micronaut.http.server.netty.RoutingInBoundHandler.writeNettyMessageBody(RoutingInBoundHandler.java:362) ~[micronaut-http-server-netty-4.0.0.jar:4.0.0]
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeHttpResponse(RoutingInBoundHandler.java:341) ~[micronaut-http-server-netty-4.0.0.jar:4.0.0]
	at io.micronaut.http.server.netty.RoutingInBoundHandler.writeResponse(RoutingInBoundHandler.java:236) ~[micronaut-http-server-netty-4.0.0.jar:4.0.0]

### Steps To Reproduce

```
@Controller(BASE_PATH)
class SomeController() {
    
    @Post("/notify")
    suspend fun notify(@Body payload: String) {}

}
```

### Environment Information

jdk 17.0.7, kotlin 1.9.0

### Version

4.0.0

**Comment by jlbadano** [comment]
Having the same issue with version 3.10.1

**Comment by trumank-il** [comment]
I am also experiencing this in version 4.2.2.
In my case, despite my functions having no return type, I am getting this same error, but about an AWS SDK object from a Kotlin DynamoDB client.
Some example code:
```kotlin
@Controller("/items")
class ItemsController(
  @Inject itemRepository: ItemRepository
) {
  @Post
  @Status(HttpStatus.NO_CONTENT)
  suspend fun post(newItem: Item) {
    itemRepository.createItem(item)
  }
}

@Singleton
class ItemRepository(
  @Inject itemMapper: ItemMapper
) {
  suspend fun createItem(newItem: Item) {
    dynamoDbClient.putItem {
      tableName = "tableName"
      item = itemMapper.toAttributeMap(item)
    }
  }
}
```
The exception then complains about `PutItemResponse`, the return type from putItem, instead of `Unit`:
```
RouteExecutor - Unexpected error occurred: Error encoding object [PutItemResponse(attributes=null,consumedCapacity=null,itemCollectionMetrics=null)] to JSON:
No serializable introspection present for type PutItemResponse. Consider adding Serdeable. Serializable annotate to type PutItemResponse.
Alternatively if you are not in control of the project's source code, you can use @SerdeImport(PutItemResponse.class) to enable serialization of this type.
```
This behavior seems like a lambda's, in that the last statement is the implicitly the return value, possibly because of how the suspend functions are being adapted by Micronaut. I don't think there is anything special about the DynamoDB client, other than it is why I am using suspend functions in the first place. I was also able to get the same exception with `Unit` by removing the call on the dynamoDbClient.

__Workarounds__
I am not familiar enough with how Micronaut handles suspend functions to say why this is happening. However, there are two workarounds I have found:

__1)__ Doing as the exception suggests and using `@SerdeImport(PutItemResponse.class)`. This doesn't make a ton of sense though, as the response body will be empty.

__2)__ Explicitly returning an HttpResponse, with a type parameter of unit:
```kotlin
  @Post
  suspend fun post(newItem: Item): HttpResponse<Unit> {
    itemRepository.createItem(item)
    return HttpResponse.status(HttpStatus.NO_CONTENT)
  }
```
This is a little verbose though.

Hopefully this provides some insight for a solution, and viable alternatives until then.

**Comment by graemerocher** [comment]
Triage: this is a valid Kotlin coroutine response-handling bug, but it is already addressed by #10992 and fix PR #11006 (merged). The current RouteExecutor coroutine path explicitly suppresses the resumed value when the route return type is Kotlin Unit, so the reported serialization failure should no longer occur on a current Micronaut version. Please upgrade to a current Micronaut release; if the failure remains, reopen with a current version and a minimal application reproducer.
