### ISSUE TITLE
Is Micronaut 3.8.6 really built with java 8? Because we saw NoSuchMethodError on java.nio.ByteBuffer.clear()

### ISSUE THREAD

**Issue by fujianyang** [micronaut-projects/micronaut-core#9637]
### Issue description

We are using Micronaut 3.8.6 and build our code and container with java 8. Then at runtime we noticed the following:

java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; 
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;r	at io.micronaut.http.uri.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:367)r	at io.micronaut.http.uri.QueryStringDecoder.addParam(QueryStringDecoder.java:323)r	at io.micronaut.http.uri.QueryStringDecoder.decodeParams(QueryStringDecoder.java:266)r	at io.micronaut.http.uri.QueryStringDecoder.parameters(QueryStringDecoder.java:201)r	at io.micronaut.http.uri.DefaultUriBuilder.<init>(DefaultUriBuilder.java:74)r	at io.micronaut.http.uri.UriBuilder.of(UriBuilder.java:132)r	at io.micronaut.http.client.netty.NettyClientHttpRequest.lambda$decodeParameters$1(NettyClientHttpRequest.java:222)r	at io.micronaut.http.netty.NettyHttpParameters.add(NettyHttpParameters.java:107)r	at io.micronaut.http.MutableHttpParameters.add(MutableHttpParameters.java:37)r

Our guess is it's because one of our Micronaut dependency is built with java 9 or later version, and because of the signature change on java.nio.ByteBuffer.clear() between java 8 and 9 this created a discrepancy between the built library and the java 8 JRE.

Can someone confirm this is the case?

Thanks!

https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#clear--
https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html

**Comment by altro3** [comment]
Hm... don't know how you get this exception, but if you look to java 1.8 sources you wiil see that class `ByteBuffer` extends class `Buffer` and Buffer class has method `clear` thus the ByteBuffer class has this method too

**Comment by sdelamo** [comment]
yes, Micronaut Framework 3 supports a java baseline of 8

**Comment by fujianyang** [comment]
@sdelamo That's what I thought too. But we build our container with java 8 installed, run our application that's built with java 8 and Micronaut 3.8.6, and when running the application the NoSuchMethodError happened, see my first post for details.

From the stack trace, we can see that ByteBuffer.clear() is directly from Micronaut code base, and since we are sure there is only java 8 installed in our container, there seems to be only one possibility, which is somehow the Micronaut module was built with JDK 9 or later version. Otherwise I can't find an appropriate interpretation of the error.

We didn't use Micronaut declarative http client and manually add query parameters by calling MutableHttpRequest.getParameters().add(...). This triggers the error.

The error is gone after we replaced the our original http client implementation with a Micronaut declarative http client.

Out of the curiosity how the error could happen I posted my question here just in case there is something wrong somewhere.

**Comment by mrwilby** [comment]
Related ? https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime

**Comment by yawkat** [comment]
@melix i think this is a build issue, micronaut-http is indeed built with class file version 52 (java 8) but against a newer stdlib version. my guess is we're using a newer jdk with `-target 8` instead of `-release 8`.

**Comment by melix** [comment]
We have never used `-release` (our build scripts used to declare `targetCompatibility` explicitly). Since build plugins for Micronaut 4, [we use toolchain support](https://github.com/micronaut-projects/micronaut-build/blob/11511fcd8890eaa269de387639b1f77b8532cb4a/src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy#L123-L136) and `targetCompatibility` is deprecated, but this is not the case for the 3.x branch obviously. Changing to `-release` _after_ `targetCompatibility` has been set may be trickier than it seems...

**Comment by melix** [comment]
As I imagined, moving to `-release` is not straightforward. If we do this, then compilation starts failing with:

> error: package com.sun.source.util does not exist	
> import com.sun.source.util.JavacTask;

https://ge.micronaut.io/s/vnmyavlxqnamg/console-log?page=1#L286

And if you try to add the missing classes, it complains that add-opens is not allowed...

> error: option --add-exports not allowed with target 8

https://ge.micronaut.io/s/j3oobz4geulei/console-log?page=1#L195

**Comment by melix** [comment]
Given the difficulties with `--release`, I think the easiest is to introduce this workaround in the 3.x branches: https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime/67018142#67018142

**Comment by yawkat** [comment]
that's unfortunate. i will make a pr.

why don't we just build entirely on 8?

**Comment by melix** [comment]
My guess is that's a side effect of common workflows: some projects require Java 11 APIs, so we have to build with Java 11, even for projects which are fully compatible with 8.

**Comment by yawkat** [comment]
is there something like animal-sniffer-maven-plugin for gradle? it's what we use in jackson to prevent similar bugs

**Comment by sdelamo** [comment]
> why don't we just build entirely on 8?

We changed release workflow to use Java 11: https://github.com/micronaut-projects/micronaut-project-template/pull/241 If I remember correctly, we did It to simplify synchronization which had java 11 compatibility.

**Comment by mrwilby** [comment]
I noticed this was tagged as targeting to the 4.xx release, but it will be some time before we can adopt that as it's rather breaking and disruptive. Can we get this fixed against 3.x (where it was found)? Thanks

**Comment by yawkat** [comment]
@mrwilby it's not an issue in 4.x because we don't support java 8 anymore. it will be fixed in 3.x.

**Comment by sdelamo** [comment]
@mrwilby can you update to 3.8.10 which I just released?. Please, confirm if it solves your issue.

**Comment by sdelamo** [comment]
> I noticed this was tagged as targeting to the 4.xx release, but it will be some time before we can adopt that as it's rather breaking and disruptive. Can we get this fixed against 3.x (where it was found)?

Yes, I just added to 4.0.3 so that I have it in front of me and give it priority.

**Comment by mrwilby** [comment]
Many thanks we'll give 3.8.10 a shot and report back. Thanks for the quick fix for this!

**Comment by mrwilby** [comment]
Is this also part of 3.10.0 ?

**Comment by yawkat** [comment]
no, we released it for 3.8 first so you can test

**Comment by mrwilby** [comment]
From our testing, this does appear to fix the issue. Would be great if we can get this on the latest 3.x in the next release cycle as we've moved up to 3.10 already. Thanks!

**Comment by sdelamo** [comment]
@mrwilby Yes, the plan was to merge it up to 3.9 and 3.10 as soon as you confirmed it worked.
