### ISSUE TITLE
kspKotlin fails with java enum in kotlin project

### ISSUE THREAD

**Issue by hauner** [micronaut-projects/micronaut-core#9642]
### Expected Behavior

compilation of the kotlin project with a java enum should succeed

### Actual Behaviour

`kspKotlin` fails with

```
[ksp] java.lang.IllegalStateException: unexpected class: class com.google.devtools.ksp.symbol.impl.java.KSClassDeclarationJavaEnumEntryImpl
	at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveClassDeclaration(ResolverImpl.kt:568)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignatureInternal$compiler_plugin(ResolverImpl.kt:356)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignature(ResolverImpl.kt:353)
	at io.micronaut.kotlin.processing.ExtensionsKt.getBinaryName(extensions.kt:47)
...
```

### Steps To Reproduce

1. build
2. kspKotlin fails

### Environment Information

- MacOS 13.5
- JDK 17

### Example Application

https://github.com/hauner/demo-enum

### Version

4.0.1

**Comment by tamershahin** [comment]
any news on this one?

**Comment by dstepanov** [comment]
It's broken in KSP https://github.com/google/ksp/issues/1482

**Comment by altro3** [comment]
@dstepanov it works fine now. Can be closed
