### ISSUE TITLE
Upgrade to Micronaut v4 breaks native image build

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#9664]
### Expected Behavior

Upgrading to Micronaut v4 shouldn't break our native image build

### Actual Behaviour

It breaks for unclear reasons

### Steps To Reproduce

1. Clone `git@github.com:elide-dev/elide.git` on branch `release/alpha4-micronaut4`
2. Using a recent GraalVM of Java 20, execute:
3. `./gradlew :packages:cli:nativeCompile`

### Environment Information

- Operating System: macOS Ventura 13.5
- JDK Version: JDK 20 (Oracle GraalVM)
- Output of `java -version`:
```
java version "20.0.2" 2023-07-18
Java(TM) SE Runtime Environment Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14, mixed mode, sharing)
```

### Example Application

https://github.com/elide-dev/elide/tree/release/alpha4-micronaut4

### Version

4.0.2

**Comment by sgammon** [comment]
We have cross-filed with the GraalVM team at oracle/graal#7110. The full native image build error is enclosed on that issue. Ultimately, the exception is:

```
com.oracle.svm.core.util.VMError$HostedError: types reachable for JIT compilation must not have linkage errors
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.guarantee(VMError.java:93)
	at org.graalvm.nativeimage.builder/com.oracle.svm.graal.hosted.GraalGraphObjectReplacer.createType(GraalGraphObjectReplacer.java:318)
	at org.graalvm.nativeimage.builder/com.oracle.svm.graal.hosted.GraalGraphObjectReplacer.createMethod(GraalGraphObjectReplacer.java:240)
	at org.graalvm.nativeimage.builder/com.oracle.svm.graal.hosted.GraalGraphObjectReplacer.updateDataDuringAnalysis(GraalGraphObjectReplacer.java:399)
	at org.graalvm.nativeimage.builder/com.oracle.svm.graal.hosted.LegacyRuntimeCompilationFeature.duringAnalysis(LegacyRuntimeCompilationFeature.java:235)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

There is also a summary of things we've tried.

**Comment by subash89** [comment]
@sgammon  When running the container created, I am getting 
**/app/application: /usr/glibc-compat/lib/libc.so.6: version `GLIBC_2.34' not found (required by /app/application)**

Only happens to me in 4.x.  Works fine in 3.9.x.  Not sure whether we talking exact same error per say, but certainly could not get native build working in 4.x

I am following. https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api

**Comment by sgammon** [comment]
@subash89 this isn't the same error -- the error in this issue happens when building the native image, not at runtime.

You will want an image which has `glibc` installed at the right version. You can build a native image statically to include libc in some cases. Take a look at [these docs](https://www.graalvm.org/22.1/reference-manual/native-image/StaticImages/) from the GraalVM team

the image we use as our native base is built like this:
```Dockerfile
ARG UBUNTU_VERSION=22.04
ARG UBUNTU_HASH="@sha256:b060fffe8e1561c9c3e6dea6db487b900100fc26830b9ea2ec966c151ab4c020"

FROM ubuntu:${UBUNTU_VERSION}${UBUNTU_HASH}

RUN apt-get update \
  && apt-get -y upgrade \
  && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    libc6 \
    zlib1g \
  && apt-get autoremove \
  && rm -rf /var/lib/apt/lists/*
```

This is just an example. You can see that we are installing `libc6` (that's `glibc`) and `zlib1g`, which is also required for the native image. This works for us; you can use the script above or if you want to, re-use our Docker base image. It's open source, and just consists of the commands above: `ghcr.io/elide-dev/runtime/native:latest`

**Comment by subash89** [comment]
I am using mvn -Dpackagnig=docker-native. So is there a way to pass a custom native image to the maven plugin in micronaut ?

**Comment by sgammon** [comment]
@subash89 it would probably be best to file a separate issue. this one addresses a gradle build and the `glibc` issue is certainly separate.

**Comment by sdelamo** [comment]
@msupic is this something you could help with?

**Comment by sgammon** [comment]
@sdelamo supposedly this is tracked internally by the GraalVM team, I've asked for an update ahead of the upcoming release in Sept but we're cutting it close if it hasn't already landed.

**Comment by sgammon** [comment]
This has been fixed by the latest version of GraalVM
