### ISSUE TITLE
Key password is incorrectly used to initialize the keyManagerFactory

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-core#9675]
### Expected Behavior

SslBuilder.getKeyManagerFactory() should use the key-store password in keyManagerFactory.init() to correctly access the provided keystore.

### Actual Behaviour

When a password is specified for a **key** in the ssl configuration, this is used instead of the password supplied in the **key-store** config. This then causes the initialization of the keyManagerFactory to fail and the HTTP server will not start up.

### Steps To Reproduce

Using keytool or the tool of your choice, create a PKCS12 or JKS keystore containing a key with a password:
`keytool -genkey -alias abc -storetype PKCS12 -keyalg RSA -keysize 4096 -keystore keystore.p12 -keypass skippy -validity 365`
Create a simple Micronaut web-server app.
Use the following config in application.yml:
>micronaut:
  ssl:
    enabled: true
  server:
    ssl:
      key-store:
        path: file:///somewhere/keystore.p12
        password: changeme
        type: PKCS12
      key:
        alias: abc
        password: skippy

Now try to run the application. It will crash with the stacktrace looking a little like this:

> 14:59:45.005 [default-nioEventLoopGroup-1-1] WARN io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x8af9eaf8]
io.micronaut.http.ssl.SslConfigurationException: An error occurred configuring SSL
    at io.micronaut.http.ssl.SslBuilder.getKeyManagerFactory(SslBuilder.java:111)
...
Caused by: java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
    at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:438)
    at java.security.KeyStore.getKey(KeyStore.java:1023)
...

Removing the password: skippy from the config fixes the issue (although it may not behave as expected because the private key will not be able to be read from the keystore).

### Environment Information

Linux or MacOS
JDK 8

### Version

3.10.0

**Comment by yawkat** [comment]
it seems *.ssl.key.alias and *.ssl.key.password are pointless in the current implementation.

**Comment by yawkat** [comment]
question, why do you need to configure the alias? it should be picked based on SNI, no?

**Comment by ghost** [comment]
This was a simple example but in our actual product, the customer wanted to use the alias for the key in their global keystore.

**Comment by yawkat** [comment]
Alias selection is a complex process, I don't really see a way to make it a simple config option. You basically have to implement X509KeyManager yourself.

We should deprecate the key option as it's not functional.

**Comment by graemerocher** [comment]
Triage: this is not reproducible as a Core defect against the current implementation. `SslBuilder` loads the keystore with `ssl.key-store.password`, then passes `ssl.key.password` to `KeyManagerFactory.init`, falling back to the keystore password only when no key password is configured. That is the JDK contract and is required for keystores whose private-key password differs from the store password. The reported configuration should therefore work; if it still fails, a modern reproducer must include the exact JDK, keystore type, store password, key password, and `keytool -list -v` output (without secrets). Closing as not a bug.
