### ISSUE TITLE
Redis cache -> No cache configured for name

### ISSUE THREAD

**Issue by Ehrzs** [micronaut-projects/micronaut-core#969]
### Steps to Reproduce
- Clone the repository  [micronaut-redis-cache-demo](https://github.com/Ehrzs/micronaut-redis-cache-demo).
- Start a docker redis container.
- `/gradlew run` in repository folder.
- Httprequest GET to `localhost:8080/cache`

An screenshot of the project configuration:

![error](https://user-images.githubusercontent.com/13764790/49001481-17e5f880-f15d-11e8-83dd-191614898faa.png)

### Expected Behaviour
- Receive a "hello" message alfter 1 seconds the first time to make the HttpRequest
- Receive a "hello" message in less than 100ms the second time to make the HttpRequest
- See a new key stored in the docker redis container.

### Actual Behaviour
- HttpRequest made and received:
```
09:00:49.285 [nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: N
o cache configured for name: mycache
io.micronaut.context.exceptions.ConfigurationException: No cache configured for name: mycache
        at io.micronaut.cache.DefaultCacheManager.getCache(DefaultCacheManager.java:67)
        at io.micronaut.cache.interceptor.CacheInterceptor.interceptSync(CacheInterceptor.java:176)
        at io.micronaut.cache.interceptor.CacheInterceptor.intercept(CacheInterceptor.java:128)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
        at cache.redis.demo.$CacheControllerDefinition$Intercepted.cacheable(Unknown Source)
        at cache.redis.demo.$$CacheControllerDefinition$InterceptedDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2401)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$13(RoutingInBoundHandler.java:1255)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14429)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14426)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```
### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.10

### Example Application

 [micronaut-redis-cache-demo](https://github.com/Ehrzs/micronaut-redis-cache-demo)

I'm trying to use a local redis docker container as a cache in a micronaut project but, following the micronaut docs [caching](https://docs.micronaut.io/latest/guide/index.html#caching).

**Comment by ilopmar** [comment]
I think the configuration key is not correct. According to https://docs.micronaut.io/1.0.1/guide/index.html#_configuring_caches the key should be 
```
micronaut:
    caches:
        myCache:
            maximumSize: 20
```
And not `micronaut.redis.cache`. Can you please try again with the other configuration key?

**Comment by Ehrzs** [comment]
Thanks @ilopmar 
That's something that I already tried.
In this case, the first two steps of the expected beahaviour are ok, but not the last one, so I think that changing the configuration key makes the application to run a cache in memory and not a Redis cache.

**Comment by jameskleeh** [comment]
The example project works as you expect if you simply move the redis key to be at the root of config and not under micronaut.

```
micronaut:
    application:
        name: cache-redis-demo
redis:
    uri: redis://localhost:6379
    caches:
        mycache:
            maximumSize: 20
```

The documentation is incorrect and the table below that shows the configuration keys is misleading. We will use this issue to improve the documentation.

**Comment by Ehrzs** [comment]
Thanks @jameskleeh 
Now it works!!

I'm not sure, but I believe that this combination is the only one that I didn't try.
