### ISSUE TITLE
Race condition introduced in Micronaut 4.0

### ISSUE THREAD

**Issue by riomus** [micronaut-projects/micronaut-core#9741]
### Expected Behavior

Consuming data from JDBC repository should not raise unhandled exception caused by micronaut internals

### Actual Behaviour

When calling simple find by id on JDBC repository from multiple threads in parallel, NoSuchElementException is thrown:

```
java.util.NoSuchElementException: null
    at java.util.concurrent.ConcurrentHashMap$EntryIterator.next
    at java.util.concurrent.ConcurrentHashMap$EntryIterator.next
    at io.micronaut.core.util.CopyOnWriteMap.evict(CopyOnWriteMap.java:165)
    at io.micronaut.core.convert.DefaultMutableConversionService.addToConverterCache(DefaultMutableConversionService.java:199)
    at io.micronaut.core.convert.DefaultMutableConversionService.convert(DefaultMutableConversionService.java:151)
    at io.micronaut.data.runtime.convert.DataConversionServiceImpl.convert(DataConversionServiceImpl.java:59)
    at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:80)
    at io.micronaut.data.runtime.mapper.ResultReader.convertRequired(ResultReader.java:64)
    at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.convert(SqlResultEntityTypeMapper.java:624)
    at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:472)
    at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntityId(SqlResultEntityTypeMapper.java:603)
    at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:440)
    at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper$1.processRow(SqlResultEntityTypeMapper.java:255)
    at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:341)
    at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeRead$18(DefaultJdbcRepositoryOperations.java:768)
    at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:143)
    at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
    at io.micronaut.data.connection.ConnectionOperations.executeRead(ConnectionOperations.java:71)
    at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:765)
    at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:310)
    at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
    at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
    at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
<redacted>
io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:447)
    at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4188)
    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:228)
    at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
    at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
    at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:457)
    at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
    at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
    at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
    at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
    at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
```

Our analysis: 

In micronaut 4 there was a call to `CopyOnWriteMap.evict(converterCache, CACHE_EVICTION_BATCH);` introduced:
https://github.com/micronaut-projects/micronaut-core/pull/9069/files

`addToConverterCache` (where `evict` is called) is not synchronized while `evict` plays with iterator, seems that there is a chance of clash that will throw that exception

### Steps To Reproduce

Hard to provide as it is a race condition

### Environment Information

- JDK: Temurin 17

### Version

4.0.2

**Comment by yawkat** [comment]
oops, evict is supposed to work fine on CHM. i'll take a look.
