### ISSUE TITLE
KSP: context.visitMetaInfFile(...) throws exception

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9746]
Form micronaut-openapi: I tested last fixes for KSP - now swagger file created in right place, but now I have another problem:

```
> Task :kspKotlin
w: [ksp] D:/Work/contrib/micronaut-openapi-swagger-ui-issue/src/main/kotlin/example/micronaut/Application.kt:13: Unable to generate swagger.yml: D:\Work\contrib\micronaut-openapi-swagger-ui-issue\build\generated\ksp\main\resources\META-INF\swagger\hello-world.yml - D:\Work\contrib\micronaut-openapi-swagger-ui-issue\build\generated\ksp\main\resources\META-INF\swagger\hello-world.yml.
D:\Work\contrib\micronaut-openapi-swagger-ui-issue\build\generated\ksp\main\resources\META-INF\swagger\hello-world.yml
kotlin.io.FileAlreadyExistsException: D:\Work\contrib\micronaut-openapi-swagger-ui-issue\build\generated\ksp\main\resources\META-INF\swagger\hello-world.yml
	at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:117)
	at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:67)
	at io.micronaut.kotlin.processing.visitor.KotlinVisitorContext$KspGeneratedFile.<init>(KotlinVisitorContext.kt:264)
	at io.micronaut.kotlin.processing.KotlinOutputVisitor.visitMetaInfFile(KotlinOutputVisitor.kt:53)
	at io.micronaut.kotlin.processing.visitor.KotlinVisitorContext.visitMetaInfFile(KotlinVisitorContext.kt:157)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.getDefaultFilePath(OpenApiApplicationVisitor.java:312)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.writeYamlToFile(OpenApiApplicationVisitor.java:1092)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.finish(OpenApiApplicationVisitor.java:582)
	at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor.finish(TypeElementSymbolProcessor.kt:146)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$10$1.invoke(KotlinSymbolProcessingExtension.kt:326)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$10$1.invoke(KotlinSymbolProcessingExtension.kt:325)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:325)
```

I don't know why realy file already exists, but I will assume that we have a second context. I already met this with Kotlin (see https://github.com/micronaut-projects/micronaut-core/issues/9148)

### Version

4.1.1

**Comment by altro3** [comment]
@dstepanov Could you look?

**Comment by dstepanov** [comment]
Can you debug why the file is created twice?

**Comment by altro3** [comment]
@dstepanov I understood what the problem was, everything turned out to be much simpler :-). In general, when calling the visitMetaInfFile method when you create files and directories, you need to cache the result and return the previously created file. This is how the implementation for java works.

Of course, I can cache the result myself, but if you do not cache previously created files, then the getClassesOutputPath method that tries to create a dummy file also breaks.

Look to AnnotationProcessingOutputVisitor class:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/0bc36da4-fe09-42c9-b9d1-0245f8cb6cea)

**Comment by dstepanov** [comment]
Ok, but do you know why is it invoked twice? I was thinking maybe it’s invoked once from Java and once from KSP

**Comment by altro3** [comment]
I was wrong, the context is ok. Forget about the previous assumption - it would be wrong.

The problem arises when you call the visitMetaInfFile method twice on the same file. Because, as I wrote to you above, there should be caching, and when calling a method for the same file, an already existing created file should be returned. This is how java works and everything else, but ksp works differently now.

You will get the same error if you call the getClassesOutputPath method twice, because it will try to create a dummy file twice

Fortunately. this is a problem that can be worked around. So I already did it in micronaut openapi: https://github.com/micronaut-projects/micronaut-openapi/pull/1173

Please do a code review and merge the changes.

But caching for generated files in ksp is still worth adding ;-)

**Comment by altro3** [comment]
@dstepanov The problem still exists. Need save already generted files to context (like a java-inject), becuase now you will see exception, when you try to visit the same generated file twice (see issue description)

**Comment by graemerocher** [comment]
Triage: validated as a Core KSP output-visitor bug. The current `KotlinOutputVisitor` creates a new `KspGeneratedFile` and calls `CodeGenerator.createNewFile` for every `visitMetaInfFile(path)`, so a second request for the same normalized path fails with `FileAlreadyExistsException`. PR #11846 only removed the random dummy-file suffix; it does not cache repeated paths. Suggested fix: keep a per-processing-round map keyed by normalized output path, return the existing generated-file wrapper for repeat visits, and define safe writer/close semantics. Add a KSP regression that calls `visitMetaInfFile` and `getClassesOutputPath` twice for the same path. The underlying API remains Core-owned; OpenAPI is a reproducer/consumer.
