### ISSUE TITLE
Error running executable after docker-native package

### ISSUE THREAD

**Issue by andriy-dmytruk** [micronaut-projects/micronaut-core#9759]
## Reproduce

Attempting to replicate this guide: https://guides.micronaut.io/latest/micronaut-graalvm-native-image-google-cloud-platform-cloud-run-maven-java.html. Downloaded the zip and run
```
mvn clean package -Dpackaging=docker-native -Djib.to.image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest -Pgraalvm
```
After using this PR to fix the build issues: https://github.com/micronaut-projects/micronaut-maven-plugin/pull/822 (maven install the `micronaut-maven-plugin`, use the `4.0.5-SNAPSHOT` version),
run the docker image:
```
docker run gcr.io/micronaut-guides-xxxxxx/micronautguide:latest
```
I get the following error:
```java
06:54:07,061 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.8
06:54:07,062 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
06:54:07,062 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [resource:/logback.xml]
06:54:07,062 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@314d3bb - Resource [logback.xml] occurs multiple times on the classpath.
06:54:07,062 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@314d3bb - Resource [logback.xml] occurs at [resource:/logback.xml#1]
06:54:07,062 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@314d3bb - Resource [logback.xml] occurs at [resource:/logback.xml]
06:54:07,062 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@483666d3 - URL [resource:/logback.xml] is not of type file
06:54:07,064 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
06:54:07,064 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
06:54:07,065 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
06:54:07,068 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
06:54:07,068 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
06:54:07,068 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@4a6e326e - End of configuration.
06:54:07,068 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4b14c30 - Registering current configuration as safe fallback point

 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
06:54:07.075 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2773)
        at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:292)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2735)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:840)
        at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:96)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1779)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:360)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:191)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:322)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:308)
        at example.micronaut.Application.main(Application.java:8)
```

**Comment by andriy-dmytruk** [comment]
The guide works fine for gradle, so this is strange
