### ISSUE TITLE
'java.lang.IllegalArgumentException: Cannot retrieve constraint validators' thrown form annotation processing

### ISSUE THREAD

**Issue by dbalek** [micronaut-projects/micronaut-core#9839]
### Expected Behavior

Open the attached project in VSCode without exceptions in log

### Actual Behaviour

Open the attached project in VSCode. Following exceptions appear in log whenever NBLS starts annotation processing.
```
java.lang.IllegalArgumentException: Cannot retrieve constraint validators
	at io.micronaut.validation.validator.constraints.InternalConstraintValidators.getConstraintValidators(InternalConstraintValidators.java:473)
	at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init>(DefaultConstraintValidators.java:80)
	at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init>(DefaultConstraintValidators.java:69)
	at io.micronaut.validation.validator.DefaultAnnotatedElementValidator$LocalConstraintValidators.<init>(DefaultAnnotatedElementValidator.java:54)
	at io.micronaut.validation.validator.DefaultAnnotatedElementValidator.<init>(DefaultAnnotatedElementValidator.java:48)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:74)
Caused: java.util.ServiceConfigurationError: Error loading service [io.micronaut.validation.validator.DefaultAnnotatedElementValidator]: null
	at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:76)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.micronaut.core.io.service.DefaultServiceDefinition.load(DefaultServiceDefinition.java:72)
	at io.micronaut.core.io.service.SoftServiceLoader.firstAvailable(SoftServiceLoader.java:138)
	at io.micronaut.annotation.processing.AnnotationUtils.<init>(AnnotationUtils.java:82)
	at io.micronaut.annotation.processing.AbstractInjectAnnotationProcessor.init(AbstractInjectAnnotationProcessor.java:198)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor.init(TypeElementVisitorProcessor.java:128)
```

### Steps To Reproduce

Open attached GCN application in VSCode with Language Server for Java by Apache NetBeans extension installed.
Exceptions appear in extension's log.

### Example Application

[BHdemoGradle.zip](https://github.com/micronaut-projects/micronaut-core/files/12547864/BHdemoGradle.zip)

### Version

4.0.3

**Comment by dbalek** [comment]
Problem found in the NBLS class loading - https://github.com/apache/netbeans/pull/6466
