### ISSUE TITLE
IllegalReferenceCountException when trying to stream file using RxStreamingHttpClient

### ISSUE THREAD

**Issue by rn55** [micronaut-projects/micronaut-core#9842]
### Expected Behavior

File should be downloaded

### Actual Behaviour

Micronaut logs this error:
```
15:31:04.382 [default-nioEventLoopGroup-1-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: PooledSlicedByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
        at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:116)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:282)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:363)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:438)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
```

curl's output:

```
nawrr@L32880MEU ~/tmp $ curl --location 'http://localhost:8080/binary/test1' -i -o test
  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
100 12489    0 12489    0     0   8642      0 --:--:--  0:00:01 --:--:--  8678

curl: (18) transfer closed with outstanding read data remaining
```

### Steps To Reproduce

I'm using simple method in my controller:

```
@Get(value = "/test1", produces = MediaType.APPLICATION_OCTET_STREAM)
Flowable<ByteBuffer<?>> test1() throws MalformedURLException {
        URL url = new URL("http://localhost:8085");
        HttpClientConfiguration conf = new DefaultHttpClientConfiguration();
        conf.setMaxContentLength(2147483647);
        RxStreamingHttpClient client = RxStreamingHttpClient.create(url, conf);
        return client.dataStream(HttpRequest.GET("/v1/objects/9e3aad86-491c-451c-afbc-98f8c21a6ab8/100MbFile"));
}
```
and trying to download 100MB file using curl:
```
curl --location 'http://localhost:8080/binary/test1' -i -o test
```

### Environment Information

Java 17, MacOS ventura

### Version

3.10.1

**Comment by yawkat** [comment]
Is this still an issue with 4.x?

**Comment by rn55** [comment]
Yes, I tried 4.1.0, both RxStreamingHttpClient and Rx3StreamingHttpClient.

**Comment by yawkat** [comment]
Please add a `.map(b -> (ByteBuffer<?>) ((ReferenceCounted) b).retain())` as a workaround. You could also consider ProxyHttpClient if that works for you.

This bug is a side effect of issues with the current ByteBuffer api. Basically, they are "maybe" reference counted–the netty implementation has ref counting, but others might not. Most users of ByteBuffer don't ref count properly for this reason. 

To avoid buffer leaks, the publisher returned by the client returns ByteBuffers that only are valid for the duration of the downstream publisher execution and are then released. On the other hand, when returning ByteBuffers from a controller, the http server will release those buffers and expects them to stay valid. These two approaches have their reasons and can't really be changed without a major release, but they are unfortunately incompatible.

With the migration to netty 5, I plan to make ByteBuffer Closeable (not optional anymore), which will fix this issue. Before then, we'll just have to stick with the workaround.

**Comment by graemerocher** [comment]
Triage update: this remains a valid Core HTTP client/server streaming issue, and it was confirmed on 4.1.0 after the original 3.10.1 report. The failure is caused by the old optional Netty reference-count semantics of `ByteBuffer`: `RxStreamingHttpClient` releases the buffer after downstream processing, while returning that same buffer from a controller lets the server release it again. The documented workaround is `.map(b -> (ByteBuffer<?>) ((ReferenceCounted) b).retain())`; `ProxyHttpClient` may also avoid the ownership handoff. The durable fix is the planned closeable/non-optional buffer API in the next major line, together with a Netty integration test that streams a large client response through a controller and verifies complete output without a double release.
