### ISSUE TITLE
Micronaut 4.1.3 and above response format changed, when use Mono<Page<...>>

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9887]
When I try to upgrade micronaut from 4.1.2 to 4.1.3 in `micronaut-openapi`, some tests failed:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/244338cd-7a0b-4b9b-a64b-d29771a08961)
Exception with test `ResponseBodyControllerSpec."test get paginated simple model"`:
```
io.micronaut.http.client.exceptions.HttpClientResponseException: Client '/api': Error decoding HTTP response body: Error decoding JSON stream for type [list]: Unexpected token START_OBJECT, expected START_ARRAY 
 at [Source: (byte[])"{"content":[{"color":"red","numEdges":10,"area":10.5,"convex":false,"points":["1,1","2,2","2,4"]},{"color":"red","numEdges":3,"area":10.5},{"color":"blue","points":["1,1","2,2","3,3"],"state":"running"}],"pageable":{"size":10,"number":12,"sort":{}},"totalSize":3}"; line: 1, column: 2]
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeNormalBodyParseError(DefaultHttpClient.java:2254)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2184)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2140)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2108)

....


Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [list]: Unexpected token START_OBJECT, expected START_ARRAY 
 at [Source: (byte[])"{"content":[{"color":"red","numEdges":10,"area":10.5,"convex":false,"points":["1,1","2,2","2,4"]},{"color":"red","numEdges":3,"area":10.5},{"color":"blue","points":["1,1","2,2","3,3"],"state":"running"}],"pageable":{"size":10,"number":12,"sort":{}},"totalSize":3}"; line: 1, column: 2]
	at app//io.micronaut.json.body.JsonMessageHandler.decorateRead(JsonMessageHandler.java:90)
	at app//io.micronaut.json.body.JsonMessageHandler.read(JsonMessageHandler.java:104)
	at app//io.micronaut.http.netty.body.NettyJsonHandler.read(NettyJsonHandler.java:113)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:225)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$0(FullNettyClientHttpResponse.java:174)
	at java.base@17.0.8.1/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:169)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:108)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2163)
	... 49 more
Caused by: io.micronaut.serde.exceptions.SerdeException: Unexpected token START_OBJECT, expected START_ARRAY 
 at [Source: (byte[])"{"content":[{"color":"red","numEdges":10,"area":10.5,"convex":false,"points":["1,1","2,2","2,4"]},{"color":"red","numEdges":3,"area":10.5},{"color":"blue","points":["1,1","2,2","3,3"],"state":"running"}],"pageable":{"size":10,"number":12,"sort":{}},"totalSize":3}"; line: 1, column: 2]
	at app//io.micronaut.serde.jackson.JacksonDecoder.createDeserializationException(JacksonDecoder.java:88)
	at app//io.micronaut.serde.jackson.JacksonDecoder.unexpectedToken(JacksonDecoder.java:97)
	at app//io.micronaut.serde.jackson.JacksonDecoder.decodeArray(JacksonDecoder.java:167)
	at app//io.micronaut.serde.jackson.JacksonDecoder.decodeArray(JacksonDecoder.java:46)
	at app//io.micronaut.serde.support.deserializers.collect.CollectionDeserializer.doDeserialize(CollectionDeserializer.java:45)
	at app//io.micronaut.serde.support.deserializers.collect.ArrayListDeserializer.deserialize(ArrayListDeserializer.java:41)
	at app//io.micronaut.serde.support.deserializers.collect.ArrayListDeserializer.deserializeNullable(ArrayListDeserializer.java:50)
	at app//io.micronaut.serde.support.deserializers.collect.ArrayListDeserializer.deserializeNullable(ArrayListDeserializer.java:32)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:130)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:122)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:177)
	at app//io.micronaut.json.body.JsonMessageHandler.read(JsonMessageHandler.java:102)
```

All works fine with `micronaut-core 4.1.2`

### Version

4.1.3 and above

**Comment by altro3** [comment]
Ok, what was changed: we have generated api-controller:
```java
    @Get("/getPaginatedSimpleModel")
    Mono<Page<SimpleModel>> getPaginatedSimpleModel(
        @NotNull Pageable pageable
    );
```

This is test:
```groovy
        HttpRequest<?> request = HttpRequest.GET("/getPaginatedSimpleModel?page=${page}&size=${pageSize}")
        HttpResponse<List<SimpleModel>> response = client.exchange(request, Argument.listOf(SimpleModel))
```

With micronaut `4.1.2` controller return this json:
```json
[{"color":"red","numEdges":10,"area":10.5,"convex":false,"points":["1,1","2,2","2,4"]},{"color":"red","numEdges":3,"area":10.5},{"color":"blue","points":["1,1","2,2","3,3"],"state":"running"}]
```

With micronaut `4.1.3+` this:
```json
{"content":[{"color":"red","numEdges":10,"area":10.5,"convex":false,"points":["1,1","2,2","2,4"]},{"color":"red","numEdges":3,"area":10.5},{"color":"blue","points":["1,1","2,2","3,3"],"state":"running"}],"pageable":{"size":10,"number":12,"sort":{}},"totalSize":3}
```

**Comment by altro3** [comment]
Ok, I figured out what problem is it. The problem arose after this PR: https://github.com/micronaut-projects/micronaut-core/pull/9789. Now the isWritable method is called before the createSpecific method, so we had to change the logic of the custom MessageBodyWriter. The fix can be viewed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1181

**Comment by sdelamo** [comment]
@altro3 I created a PR https://github.com/micronaut-projects/micronaut-openapi/pull/1217
