### ISSUE TITLE
Publisher<CompletedFileUpload> to receive multiple file uploads returns more than expected

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-core#9892]
### Expected Behavior

When uploading multiple files using `Publisher<CompletedFileUpload>`, respond with the expected number of files and their valid bytes.

### Actual Behaviour

In the application created as an example that uploads multiple files using `Content-Type: multipart/form-data`, I have two parameters called 'allDocuments' and 'allPhotos' that respond to the type `Publisher<CompletedFileUpload>` and another called 'photo ' which only receives a CompletedFileUpload for a single file. But also, I have additional fields such as: name (string) and age (string).

### First Scenario

Requesting the curl below:
```
curl --location 'http://localhost:8080/upload' \
--form 'allDocuments=@"assets/Sample.pdf"' \
--form 'allDocuments=@"assets/merge-files.zip"' \
--form 'allPhotos=@"assets/github.png"' \
--form 'allPhotos=@"assets/java-logo.png"' \
--form 'allPhotos=@"assets/micronaut-logo.png"' \
--form 'photo=@"assets/micronaut-logo.png"' \
--form 'age="23"'
```

And iterating the data received over a `Flux.from()`, I receive the same file more than once:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
12:37:01.134 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 377ms. Server Running: http://localhost:8080
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
```

and checking the integrity of the files, the first file received contains the expected bytes, the others return null/empty.

```
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$3
INFO: [allDocuments | doOnSuccess] Received 12 files
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): 37
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] Sample.pdf received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): 80
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): -1
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received is empty
set. 18, 2023 12:37:01 PM com.example.UploadController lambda$upload$2
INFO: [allDocuments | doOnSuccess] merge-files.zip received byte(s): -1
```

### Second Scenario

Another behavior that is important to mention is when I complement the form with the 'name' parameter, the processing of `Flux.from(allDocuments)`, which is the first `block()` of the structure, ends by reaching the stipulated timeout for no reason... just by adding the 'name' field in the request composition:

```
curl --location 'http://localhost:8080/upload' \
--form 'allDocuments=@"assets/Sample.pdf"' \
--form 'allDocuments=@"assets/merge-files.zip"' \
--form 'allPhotos=@"assets/github.png"' \
--form 'allPhotos=@"assets/java-logo.png"' \
--form 'allPhotos=@"assets/micronaut-logo.png"' \
--form 'photo=@"assets/micronaut-logo.png"' \
--form 'age="23"' \
--form 'name="weesftw"'
```

having the result below:

```
  __ __ _ _
| \/ (_) ___ _ __ ___ _ __ __ _ _ _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| | | | | (__| | | (_) | | | | (_| | |_| | |_
|_| |_|_|\___|_| \___/|_| |_|\__,_|\__,_|\__|
12:50:10.463 [main] INFO io.micronaut.runtime.Micronaut - Startup completed in 351ms. Server Running: http://localhost:8080
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: Sample.pdf
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:13 PM com.example.UploadController lambda$upload$0
INFO: [allDocuments | doOnNext] Received file: merge-files.zip
Sep. 18, 2023 12:50:28 PM com.example.UploadController lambda$upload$4
INFO: [allDocuments | doFinally] Finished processing request
12:50:28.054 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Timeout on blocking read for 15000000000 NANOSECONDS
java.lang.IllegalStateException: Timeout on blocking read for 15000000000 NANOSECONDS
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:127)
at reactor.core.publisher.Mono.block(Mono.java:1738)
at com.example.UploadController.upload(Application.java:69)
```

I can't find any source that I can understand this problem... can it be considered a bug?

### Steps To Reproduce

1. clone project
2. ./gradlew build
3. java -jar build/libs/demo-0.1-all.jar
4. execute `request1.sh` to reproduce first scenario
5. execute `request2.sh` to reproduce second scenario

the example files are in the project's assets folder... the scripts attached them.

### Environment Information

**OS**: Ubuntu 22.04.3 LTS
**JDK Version**: openjdk 17.0.7 2023-04-18

### Example Application

[multiple-upload-file-master.zip](https://github.com/user-attachments/files/16575612/multiple-upload-file-master.zip)

### Version

4.1.1

**Comment by goeh** [comment]
Same here on Micronaut 4.3.4
I have one part named "metadata" and multiple parts named "file". Even though I only send one part as "file" (for example image.jpg) I receive two parts with the same file, first part it correct, the second part is empty (InputStream is already consumed).
```
@Part("metadata") FileMetadata metadata,
@Part("file") Publisher<CompletedFileUpload> file
```

**Comment by loicmathieu** [comment]
When mixing parts of different type (files and plain value) I think you should bind the body with `@Body MultipartBody body` then check on each part if it's a `CompletedFileUpload` or not.
This works but on my side files are limited to 1GB, I plan to open an issue for that.

**Comment by graemerocher** [comment]
Triage update: this reproducer matches the delayed-route duplicate `CompletedFileUpload` failure fixed by merged PR #10713, which fixes #10578 and adds regression coverage for a multipart route with a second argument that delays execution. The root cause was that buffered partial `HttpData` pieces were all treated as completed during conversion, causing the same completed upload to be emitted repeatedly; the fix uses the completed-field stream so each part is emitted once. The current Core multipart implementation also contains the corresponding completed-publisher regression test. This issue is therefore resolved by the existing code; please reopen only if the attached application still reproduces on the current 5.x line with a minimal failing request.
