### ISSUE TITLE
ConcurrentModificationException when initializing DefaultBeanContext

### ISSUE THREAD

**Issue by xeagle2** [micronaut-projects/micronaut-core#9913]
### Expected Behavior

No errors should happen

### Actual Behaviour

Here is the stack trace:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:113)
	at io.micronaut.aot.cli.Main.run(Main.java:87)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.micronaut.aot.cli.Main.execute(Main.java:134)
	at io.micronaut.aot.cli.Main.main(Main.java:138)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.micronaut.aot.cli.Main.executeInIsolatedLoader(Main.java:107)
	... 11 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapPropertySourceLocatorPresent(DefaultApplicationContext.java:156)
	at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:308)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapEnabled(DefaultApplicationContext.java:152)
	at io.micronaut.context.DefaultApplicationContext.createEnvironment(DefaultApplicationContext.java:140)
	at io.micronaut.context.DefaultApplicationContext.getEnvironment(DefaultApplicationContext.java:174)
	at io.micronaut.aot.core.context.ApplicationContextAnalyzer.getEnvironmentNames(ApplicationContextAnalyzer.java:66)
	at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:336)
	at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
	... 16 more
```

### Steps To Reproduce

Fails on prepareJitOptimizations step: ./gradlew clean build optimizedDockerBuild

### Environment Information

- OS: OS name: "linux", version: "4.15.0-213-generic", arch: "amd64", family: "unix"
- MacOS: Ventura 13.4.1/M2
- JDK: 17.0.8, 17.0.2
- micronaut version: 4.1.1
- gradle version: 8.1.1

### Version

4.1.1

**Comment by yawkat** [comment]
@melix please check if this should be moved to micronaut-aot

**Comment by melix** [comment]
I am not sure it's an issue with AOT. The code is just:

```java
    public Set<String> getEnvironmentNames() {
        return applicationContext.getEnvironment().getActiveNames();
    }
```

which doesn't look particularly suspicious. But maybe there are some broken assumptions, like this code shouldn't be called too early?

**Comment by yawkat** [comment]
hm yea looking at the code, the list that is throwing the exception is not supposed to be modified at all after it's returned... definitely something weird going on, maybe even an actual concurrency issue :grimacing:

**Comment by xeagle2** [comment]
@yawkat @melix I might be wrong, my understanding is currently that logic is executed in one single thread, at least the implementation I see is not threadsafe there. 

Additionally I found the following fork in the code below:

```
if (allowFork) {
                ForkJoinPool.commonPool().invoke(this);
                for (RecursiveActionValuesCollector<S> task : tasks) {
                    task.join();
                    task.collect(values);
                }
            }
```

Which might be a game changer for the strategy how the **values** object is handled, which is ArrayList() and not a threadsafe.

Might it be related somehow to the issue?

**Comment by yawkat** [comment]
resolveBeanDefinitionReferences is definitely not thread safe. but it seems unlikely to be called concurrently?

`task.collect(values);` is safe because the implementations don't offload to other threads.

**Comment by yawkat** [comment]
Also should add that in most cases a ConcurrentModificationException does not actually happen due to a multi-threading issue. it happens because the collection is modified inside the loop. But in this case it might actually be due to threading.

**Comment by xeagle2** [comment]
@yawkat Do you happen to know when it's going to be fixed?

**Comment by yawkat** [comment]
no, no clue how to reproduce it

**Comment by xeagle2** [comment]
It occurs frequently (almost every day) to me. Can we please get in contact somehow to let me assist in reproducing it?

**Comment by graemerocher** [comment]
We need a reproducible example

**Comment by xeagle2** [comment]
I have made a few checks and discovered that the problem occurs only if I use io.micronaut.context.annotation.Parallel annotation for the bean and additionally when the bean is created dynamically as below

````
@Factory
public class Factory {
  @Singleton
  @Parallel
  public Bean createBean()  {
     ...
  }
}
````

Could that be the reason?

**Comment by graemerocher** [comment]
Triage: the 4.1.1 report is credible and the later comment narrows it to `@Parallel` beans created dynamically by a factory. The current 5.x source no longer scans an `ArrayList` in `DefaultApplicationContext.isBootstrapPropertySourceLocatorPresent`; it delegates to the bean-definition service, and parallel startup/shutdown lifecycle handling has since been substantially rewritten. Please rerun the smallest `@Factory + @Singleton @Parallel` example on current 5.2.x. If it still fails, capture the new stack trace and add a regression around concurrent bean discovery/initialization; otherwise close as completed by the lifecycle rewrite.
