### ISSUE TITLE
Micronaut 4 Groovy projects fail Intellij compilation

### ISSUE THREAD

**Issue by j1m-renwick** [micronaut-projects/micronaut-core#9915]
### Expected Behavior

All information on https://youtrack.jetbrains.com/issue/IDEA-331174 as I initially believed this to be an Intellij-specific issue.  

Example project included in this ticket:
[groovy-compile-bug.zip](https://github.com/micronaut-projects/micronaut-core/files/12708921/groovy-compile-bug.zip)

### Actual Behaviour

Compilation fails when building Micronaut 4 groovy projects using Intellij's compiler, that have annotations that are defined in Groovy files.  

### Steps To Reproduce

All information on https://youtrack.jetbrains.com/issue/IDEA-331174 as I initially believed this to be an Intellij-specific issue.  

They state that the problem is caused by the library `io.micronaut:micronaut-inject-groovy` starting from version 4.0.0, so raising it here for further investigation. 

### Environment Information

Operating System: MacOS Ventura, Version 13.4
JDK Version: Coretto 17

### Example Application

see attached 

### Version

4.0.3

**Comment by knisht** [comment]
Reproducer:
```
// Annotation.groovy
import java.lang.annotation.ElementType
import java.lang.annotation.Target

@Target(ElementType.FIELD)
@interface Annotation {
}
```
```
// Usage.groovy
class Usage {
    @Annotation
    String field
}
```

Then
```
groovyc Usage.groovy Annotation.groovy -cp micronaut-inject-groovy-4.1.6.jar:micronaut-core-4.1.6.jar:micronaut-core-processor-4.1.6.jar:micronaut-inject-4.1.6.jar:jakarta.annotation-api-2.1.1.jar:jakarta.inject-api-2.0.1.jar:micronaut-aop-4.1.6.jar:asm-9.5.jar:asm-commons-9.5.jar
```
Results with 
```
Invalid duplicate class definition of class Annotation : The sources file:/Users/_/Annotation.groovy and Annotation.groovy each contain a class with the name Annotation.
```

The problem is that `io.micronaut.ast.groovy.annotation.GroovyAnnotationMetadataBuilder#getAnnotationMirror` tries to find `ClassNodes` when there are none, and it results in generation of additional `SourceUnit` for `Annotation`. Maybe the annotation processing occurrs too early?

**Comment by yawkat** [comment]
does it work when building with gradle? you should let intellij delegate build tasks to gradle

**Comment by sdelamo** [comment]
Please, configure your IDE according to [USING INTELLIJ IDEA TO DEVELOP MICRONAUT APPLICATIONS](https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html) and let us know if the issue is still present.

**Comment by j1m-renwick** [comment]
When I specify the Gradle option in the IDE setup it works, as specified on that link - this is the workaround I currently have to use for the project:

![image](https://github.com/micronaut-projects/micronaut-core/assets/52238993/4f28eee8-77c8-4413-a284-0c36d89e1c0a)

However, pre Micronaut 4 the Intellij compiler option worked as well, and makes for a much faster dev experience in terms of build and start times:

<img width="981" alt="image" src="https://github.com/micronaut-projects/micronaut-core/assets/52238993/d84b19fa-6aaa-43d5-b894-4e2b2637fe1c">

**Comment by dstepanov** [comment]
Looks like a bug in the IntelliJ compiler or the Groovy compiler. None of the methods we use is supposted to create an additional class.

**Comment by timyates** [comment]
Minimal reproducer is to use

```
groovyc Usage.groovy Annotation.groovy \
    -cp libs/inject-groovy-4.1.7-SNAPSHOT.jar:libs/core-processor-4.1.7-SNAPSHOT.jar:libs/core-4.1.7-SNAPSHOT.jar \
    -e
```

Then I see

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Annotation.groovy: 5: Invalid duplicate class definition of class Annotation : The sources Annotation.groovy and Usage.groovy each contain a class with the name Annotation.
 @ line 5, column 1.
   @Target(ElementType.FIELD)
   ^

1 error

>>> stacktrace:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Annotation.groovy: 5: Invalid duplicate class definition of class Annotation : The sources Annotation.groovy and Usage.groovy each contain a class with the name Annotation.
 @ line 5, column 1.
   @Target(ElementType.FIELD)
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:910)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:647)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:311)
	at org.codehaus.groovy.tools.FileSystemCompiler.doCompilation(FileSystemCompiler.java:240)
	at org.codehaus.groovy.tools.FileSystemCompiler.commandLineCompile(FileSystemCompiler.java:165)
	at org.codehaus.groovy.tools.FileSystemCompiler.commandLineCompileWithErrorHandling(FileSystemCompiler.java:205)
	at org.codehaus.groovy.tools.FileSystemCompiler.main(FileSystemCompiler.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:115)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:37)
```

**Comment by timyates** [comment]
Got a standalone script (just requires Groovy and Bash to be installed) to reproduce the issue

```
#!/usr/bin/env bash

MICRONAUT_CORE_VERSION=4.1.6
REQUIRED_MICRONAUT_CORE_LIBS="\
inject-groovy \
core-processor \
inject \
aop \
core"

EXTRA_LIBS="\
org.ow2.asm:asm-commons:9.5 \
org.ow2.asm:asm:9.5 \
jakarta.annotation:jakarta.annotation-api:2.1.1 \
jakarta.inject:jakarta.inject-api:2.0.1"

CP="."

mkdir -p libs

for lib in $REQUIRED_MICRONAUT_CORE_LIBS; do
  if [ ! -f libs/micronaut-$lib-$MICRONAUT_CORE_VERSION.jar ]; then
    echo "Downloading $lib"
    mvn dependency:get -Dartifact=io.micronaut:micronaut-$lib:$MICRONAUT_CORE_VERSION -Ddest=./libs/ > /dev/null
  else
    echo "Already got $lib"
  fi
  CP="$CP:libs/micronaut-$lib-$MICRONAUT_CORE_VERSION.jar"
done

for lib in $EXTRA_LIBS; do
  FN="$(echo $lib | cut -d: -f2 -f3 | tr ':' "-").jar"
  if [ ! -f libs/$FN ]; then
    echo "Downloading $lib"
    mvn dependency:get -Dartifact=$lib -Ddest=./libs/ > /dev/null
  else
    echo "Already got $lib"
  fi
  CP="$CP:libs/$FN"
done

if [ ! -f Annotation.groovy ]; then
  echo "Generating Annotation.groovy"
  cat <<EOF > Annotation.groovy
import java.lang.annotation.ElementType
import java.lang.annotation.Target

@Target(ElementType.FIELD)
@interface Annotation {
}
EOF
else
  echo "Already got Annotation.groovy"
fi
if [ ! -f Usage.groovy ]; then
  echo "Generating Usage.groovy"
  cat <<EOF > Usage.groovy
// Usage.groovy
class Usage {
    @Annotation
    String field
}
EOF
else
  echo "Already got Usage.groovy"
fi

echo "Running groovyc -e -cp $CP Usage.groovy Annotation.groovy"
groovyc -e -cp $CP Usage.groovy Annotation.groovy
```

**Comment by timyates** [comment]
@dstepanov If I revert this PR https://github.com/micronaut-projects/micronaut-core/pull/9232 the compilation passes, but I am not sure what is causing the problem

**Comment by dstepanov** [comment]
That is fixing some other stuff

**Comment by dstepanov** [comment]
Can you create a test inside the core?

**Comment by timyates** [comment]
@dstepanov Reproducer here: https://github.com/micronaut-projects/micronaut-core/pull/9925

(this took more effort that it may seem from looking at it 😉)

**Comment by j1m-renwick** [comment]
Hey, is there any way of progressing this? As far as I can see it's still an issue in the latest Micronaut release

**Comment by graemerocher** [comment]
The available evidence points to the IntelliJ/Groovy compiler rather than Micronaut Core: the delegated Gradle compilation works, and the existing maintainer discussion identifies the duplicate-class behavior as an IDE/compiler issue. Core’s generated bean-definition classes are not intended to create the conflicting Groovy class. Please report or retest this with the IntelliJ/Groovy tracker; there is no Core fix to apply here.
