### ISSUE TITLE
Unable to access OCI resource with Java 17, OCI Java SDK 7 and Micronaut.

### ISSUE THREAD

**Issue by vickyrare** [micronaut-projects/micronaut-core#9998]
### Expected Behavior

Getting this weird error after upgrading to Java 17, OCI Java SDK 7 and Micronaut.

Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class com.oracle.bmc.secrets.model.SecretBundle]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:116)
	at io.micronaut.serde.support.DefaultSerdeIntrospections.lambda$getDeserializableIntrospection$1(DefaultSerdeIntrospections.java:149)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.micronaut.serde.support.DefaultSerdeIntrospections.getDeserializableIntrospection(DefaultSerdeIntrospections.java:140)
	at io.micronaut.serde.support.deserializers.ObjectDeserializer.createDeserBean(ObjectDeserializer.java:95)
	at io.micronaut.serde.support.deserializers.ObjectDeserializer.lambda$getDeserializableBean$1(ObjectDeserializer.java:87)
	at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:79)
	at io.micronaut.serde.support.deserializers.ObjectDeserializer.getDeserializableBean(ObjectDeserializer.java:88)
	at io.micronaut.serde.support.deserializers.ObjectDeserializer.createSpecific(ObjectDeserializer.java:73)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:128)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:122)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:159)
	at io.micronaut.serde.ObjectMappers$2.readValue(ObjectMappers.java:112)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:104)
	at io.micronaut.oraclecloud.httpclient.netty.NettyHttpResponse.lambda$body$0(NettyHttpResponse.java:81)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.oracle.bmc.http.internal.SyncFutureWaiter$Waiter.waitAndWork(SyncFutureWaiter.java:63)
	at com.oracle.bmc.http.internal.SyncFutureWaiter.listenForResult(SyncFutureWaiter.java:32)
	at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1046)
	... 87 more

Error returned by GetSecretBundle operation in Secrets service.(-1, null, false) Unknown error

### Actual Behaviour

Should work with any issues.

### Steps To Reproduce

Java 17, OCI Java SDK 7 and Micronaut 4

### Environment Information

Mac OS
Java 17

### Version

4.0.0

**Comment by graemerocher** [comment]
Make sure you upgrade to the latest 4.1.x release and then see https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#httpclient

You need the corresponding `micronaut-` dependency for the SDK module you are using

**Comment by yawkat** [comment]
Could not reproduce
